function [features, featureValidity] = ...
        computeLidarRingCurbFeatures(frame, cfg)
%COMPUTELIDARRINGCURBFEATURES Compute side-agnostic LiDAR ring features.
%   [FEATURES, FEATUREVALIDITY] =
%   COMPUTELIDARRINGCURBFEATURES(FRAME, CFG) computes curb evidence from the
%   valid returns of each organized LiDAR ring. Required FRAME fields x, y,
%   z, and range are [ring x azimuth-bin] matrices. An optional valid
%   matrix uses the same layout.
%
%   Empty organized bins are skipped. Valid returns are sorted by their
%   measured atan2(y,x) azimuth, and a neighborhood path is usable only when
%   every consecutive measured angular gap is no larger than 2.1 degrees by
%   default. The ordered sequence wraps through 360 degrees.
%
%   Scalar feature fields have the same size as FRAME.z. The local
%   multiscale Haar response fields have size [ring x azimuth-bin x scale].
%   Invalid feature values are NaN. FEATUREVALIDITY contains a same-named
%   logical array for every feature and a base field for finite valid input.
%
%   The Chen feature is
%       norm(sum(neighbor XYZ) - 2*k*center XYZ) ...
%           / (2*k*norm(center XYZ)).
%   bilateralTangentDeflection is the Wang-style angle between the two
%   adjacent 3D vectors. huangTangentialStrength is evaluated strictly in
%   the XY road-plane projection as
%       abs(OP dot MN) / (norm(OP)*norm(MN)),
%   where O is the sensor, P is the center return, and MN is the chord
%   joining its immediate same-ring neighbors.
%   huangRadiusRatioDeviation is the maximum available value of
%       abs(r_i/r_(i-1) - 1) and abs(r_i/r_(i+1) - 1)
%   over connected immediate same-ring neighbors.
%   huangHdInRadius evaluates Huang's three-beam same-azimuth residual
%       abs(z_C - z_B - (z_B - z_A)*d_BC/d_AB),
%   where d is XY-projected distance. Each return C evaluates triplets in
%   both ring-index directions and retains the maximum available magnitude.
%   sameRingSlopeMagnitude is the maximum available absolute atan2(dz,dxy)
%   over the two immediate same-ring edges. hataDifferentialHeightResponse
%   is the absolute Hata [-2, 0, +2] height-stencil response,
%       2*abs(z_(i+1) - z_(i-1)).
%   localMeanElevation is mean z over the statistics window.
%   ilpLineFitResidual and ilpLineSlopeMagnitude respectively report the
%   RMS residual and absolute slope of one least-squares line fitted to z
%   versus accumulated horizontal arc length.
%
%   Hata adjacent-ring compression uses each valid lower-ring return and
%   the closest-azimuth valid return in the immediately upper ring. For
%   downward vertical angles, expected flat-ground horizontal spacing is
%   computed from sensor height. Raw compression is expected spacing minus
%   observed radial spacing; normalized compression divides by expected
%   spacing.
%
%   Supported CFG fields and defaults are:
%       ringFeatureStatisticsRadius                  2 returns
%       ringFeatureChenRadius                        2 returns
%       ringFeatureChenSmoothnessThreshold           0.005
%       ringFeatureSmoothArcMaximumSearchRadius      8 returns
%       ringFeatureLineFitRadius                     3 returns
%       ringFeatureHaarScales                  [1, 2, 4] returns
%       ringFeatureMaximumAngularGapDegrees           2.1 degrees
%       ringFeatureSensorHeightM                      2.35 m
%       ringFeatureUpperVerticalAngleDegrees         10.0 degrees
%       ringFeatureLowerVerticalAngleDegrees        -30.0 degrees
%       ringFeatureVerticalAnglesDegrees             optional vector

    if nargin < 2 || isempty(cfg)
        cfg = struct();
    end
    if ~isstruct(frame) || ~isscalar(frame)
        error( ...
            "computeLidarRingCurbFeatures:InvalidFrame", ...
            "frame must be a scalar structure.");
    end
    if ~isstruct(cfg) || ~isscalar(cfg)
        error( ...
            "computeLidarRingCurbFeatures:InvalidConfig", ...
            "cfg must be a scalar structure.");
    end

    [x, y, z, radialRange, baseValid] = ...
        localValidateAndConvertFrame(frame);
    parameters = localFeatureParameters(cfg, size(z, 1));
    [features, featureValidity] = localInitializeOutputs( ...
        size(z), parameters.haarScales, baseValid);

    scalarFeatureNames = [ ...
        "heightStep", ...
        "rangeStep", ...
        "localHeightStd", ...
        "localRangeStd", ...
        "localHeightRange", ...
        "localMeanElevation", ...
        "chenSmoothness", ...
        "leftSmoothArcLength", ...
        "rightSmoothArcLength", ...
        "sameRingSlopeMagnitude", ...
        "sameRingSlopeChange", ...
        "bilateralTangentDeflection", ...
        "huangTangentialStrength", ...
        "huangRadiusRatioDeviation", ...
        "hataDifferentialHeightResponse", ...
        "radiusRatioReconstructionDeviation", ...
        "wangHorizontalSpacingRatio", ...
        "wangHorizontalSpacingExcess", ...
        "radialSecondDifference", ...
        "localChordResidual", ...
        "ilpLineFitResidual", ...
        "ilpLineSlopeMagnitude"];
    haarFeatureNames = [ ...
        "localMultiscaleHaarZ", ...
        "localMultiscaleHaarRange"];

    for ringIndex = 1:size(z, 1)
        organizedColumns = find(baseValid(ringIndex, :));
        if isempty(organizedColumns)
            continue;
        end
        measuredAzimuthDegrees = mod(atan2d( ...
            y(ringIndex, organizedColumns), ...
            x(ringIndex, organizedColumns)), 360.0);
        [measuredAzimuthDegrees, order] = sort(measuredAzimuthDegrees);
        organizedColumns = organizedColumns(order);
        row = struct( ...
            "x", x(ringIndex, organizedColumns), ...
            "y", y(ringIndex, organizedColumns), ...
            "z", z(ringIndex, organizedColumns), ...
            "range", radialRange(ringIndex, organizedColumns), ...
            "azimuthDegrees", measuredAzimuthDegrees);

        [rowFeatures, rowValidity] = ...
            localComputeOrderedRingFeatures(row, parameters);
        for fieldName = scalarFeatureNames
            features.(fieldName)(ringIndex, organizedColumns) = ...
                rowFeatures.(fieldName);
            featureValidity.(fieldName)(ringIndex, organizedColumns) = ...
                rowValidity.(fieldName);
        end
        for fieldName = haarFeatureNames
            features.(fieldName)(ringIndex, organizedColumns, :) = ...
                reshape( ...
                    rowFeatures.(fieldName), ...
                    [1, numel(organizedColumns), ...
                     numel(parameters.haarScales)]);
            featureValidity.(fieldName)( ...
                ringIndex, organizedColumns, :) = reshape( ...
                    rowValidity.(fieldName), ...
                    [1, numel(organizedColumns), ...
                     numel(parameters.haarScales)]);
        end
    end

    [features, featureValidity] = localComputeHuangHdInRadius( ...
        features, featureValidity, x, y, z, baseValid);
    [features, featureValidity] = localComputeHataCompression( ...
        features, featureValidity, x, y, baseValid, parameters);
end

function [x, y, z, radialRange, valid] = ...
        localValidateAndConvertFrame(frame)
    requiredFields = ["x", "y", "z", "range"];
    if ~all(isfield(frame, requiredFields))
        error( ...
            "computeLidarRingCurbFeatures:MissingFrameField", ...
            "frame must contain numeric x, y, z, and range matrices.");
    end

    referenceSize = size(frame.z);
    if numel(referenceSize) ~= 2 || any(referenceSize == 0)
        error( ...
            "computeLidarRingCurbFeatures:InvalidFrameSize", ...
            "frame matrices must be nonempty two-dimensional arrays.");
    end
    for fieldName = requiredFields
        candidate = frame.(fieldName);
        if ~isnumeric(candidate) || ~isreal(candidate) ...
                || ~isequal(size(candidate), referenceSize)
            error( ...
                "computeLidarRingCurbFeatures:InconsistentFrameSize", ...
                "frame.%s must be a real numeric matrix matching frame.z.", ...
                fieldName);
        end
    end

    x = double(frame.x);
    y = double(frame.y);
    z = double(frame.z);
    radialRange = double(frame.range);
    valid = isfinite(x) & isfinite(y) & isfinite(z) ...
        & isfinite(radialRange) & hypot(x, y) > eps;
    if isfield(frame, "valid")
        if ~(islogical(frame.valid) || isnumeric(frame.valid)) ...
                || ~isequal(size(frame.valid), referenceSize)
            error( ...
                "computeLidarRingCurbFeatures:InvalidValidityMask", ...
                "frame.valid must match the organized frame size.");
        end
        valid = valid & logical(frame.valid);
    end
end

function parameters = localFeatureParameters(cfg, numberOfRings)
    parameters = struct( ...
        "statisticsRadius", localPositiveIntegerConfigValue( ...
            cfg, "ringFeatureStatisticsRadius", 2), ...
        "chenRadius", localPositiveIntegerConfigValue( ...
            cfg, "ringFeatureChenRadius", 2), ...
        "chenSmoothnessThreshold", max(0.0, localScalarConfigValue( ...
            cfg, "ringFeatureChenSmoothnessThreshold", 0.005)), ...
        "smoothArcMaximumSearchRadius", ...
            localPositiveIntegerConfigValue( ...
                cfg, ...
                "ringFeatureSmoothArcMaximumSearchRadius", ...
                8), ...
        "lineFitRadius", localPositiveIntegerConfigValue( ...
            cfg, "ringFeatureLineFitRadius", 3), ...
        "haarScales", localHaarScales(cfg), ...
        "maximumAngularGapDegrees", max(eps, localScalarConfigValue( ...
            cfg, "ringFeatureMaximumAngularGapDegrees", 2.1)), ...
        "sensorHeightM", max(eps, localScalarConfigValue( ...
            cfg, "ringFeatureSensorHeightM", 2.35)), ...
        "verticalAnglesDegrees", localVerticalAngles( ...
            cfg, numberOfRings));
end

function value = localPositiveIntegerConfigValue( ...
        cfg, fieldName, defaultValue)
    value = localScalarConfigValue(cfg, fieldName, defaultValue);
    if value < 1 || value ~= floor(value)
        error( ...
            "computeLidarRingCurbFeatures:InvalidRadius", ...
            "%s must be a positive integer.", fieldName);
    end
end

function value = localScalarConfigValue(cfg, fieldName, defaultValue)
    value = double(defaultValue);
    if ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    if ~isnumeric(candidate) || ~isreal(candidate) ...
            || ~isscalar(candidate) || ~isfinite(candidate)
        error( ...
            "computeLidarRingCurbFeatures:InvalidConfigValue", ...
            "%s must be a finite real numeric scalar.", fieldName);
    end
    value = double(candidate);
end

function scales = localHaarScales(cfg)
    scales = [1, 2, 4];
    fieldName = "ringFeatureHaarScales";
    if ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    if ~isnumeric(candidate) || ~isreal(candidate) ...
            || ~isvector(candidate) || isempty(candidate) ...
            || any(~isfinite(candidate)) ...
            || any(candidate < 1) ...
            || any(candidate ~= floor(candidate))
        error( ...
            "computeLidarRingCurbFeatures:InvalidHaarScales", ...
            "ringFeatureHaarScales must contain positive integers.");
    end
    scales = unique(reshape(double(candidate), 1, []), "stable");
end

function verticalAnglesDegrees = localVerticalAngles(cfg, numberOfRings)
    fieldName = "ringFeatureVerticalAnglesDegrees";
    if isfield(cfg, fieldName)
        candidate = cfg.(fieldName);
        if ~isnumeric(candidate) || ~isreal(candidate) ...
                || ~isvector(candidate) ...
                || numel(candidate) ~= numberOfRings ...
                || any(~isfinite(candidate))
            error( ...
                "computeLidarRingCurbFeatures:InvalidVerticalAngles", ...
                "ringFeatureVerticalAnglesDegrees must contain one " + ...
                "finite angle per organized ring.");
        end
        verticalAnglesDegrees = reshape(double(candidate), 1, []);
        return;
    end
    upperAngle = localScalarConfigValue( ...
        cfg, "ringFeatureUpperVerticalAngleDegrees", 10.0);
    lowerAngle = localScalarConfigValue( ...
        cfg, "ringFeatureLowerVerticalAngleDegrees", -30.0);
    verticalAnglesDegrees = linspace( ...
        upperAngle, lowerAngle, numberOfRings);
end

function [features, validity] = localInitializeOutputs( ...
        matrixSize, haarScales, baseValid)
    emptyFeature = nan(matrixSize);
    emptyValidity = false(matrixSize);
    haarSize = [matrixSize, numel(haarScales)];
    features = struct( ...
        "heightStep", emptyFeature, ...
        "rangeStep", emptyFeature, ...
        "localHeightStd", emptyFeature, ...
        "localRangeStd", emptyFeature, ...
        "localHeightRange", emptyFeature, ...
        "localMeanElevation", emptyFeature, ...
        "chenSmoothness", emptyFeature, ...
        "leftSmoothArcLength", emptyFeature, ...
        "rightSmoothArcLength", emptyFeature, ...
        "sameRingSlopeMagnitude", emptyFeature, ...
        "sameRingSlopeChange", emptyFeature, ...
        "bilateralTangentDeflection", emptyFeature, ...
        "huangTangentialStrength", emptyFeature, ...
        "huangRadiusRatioDeviation", emptyFeature, ...
        "huangHdInRadius", emptyFeature, ...
        "hataDifferentialHeightResponse", emptyFeature, ...
        "radiusRatioReconstructionDeviation", emptyFeature, ...
        "wangHorizontalSpacingRatio", emptyFeature, ...
        "wangHorizontalSpacingExcess", emptyFeature, ...
        "radialSecondDifference", emptyFeature, ...
        "localMultiscaleHaarZ", nan(haarSize), ...
        "localMultiscaleHaarRange", nan(haarSize), ...
        "localChordResidual", emptyFeature, ...
        "hataCompressionRaw", emptyFeature, ...
        "hataCompressionExpected", emptyFeature, ...
        "hataCompressionNormalized", emptyFeature, ...
        "ilpLineFitResidual", emptyFeature, ...
        "ilpLineSlopeMagnitude", emptyFeature);
    validity = struct( ...
        "base", baseValid, ...
        "heightStep", emptyValidity, ...
        "rangeStep", emptyValidity, ...
        "localHeightStd", emptyValidity, ...
        "localRangeStd", emptyValidity, ...
        "localHeightRange", emptyValidity, ...
        "localMeanElevation", emptyValidity, ...
        "chenSmoothness", emptyValidity, ...
        "leftSmoothArcLength", emptyValidity, ...
        "rightSmoothArcLength", emptyValidity, ...
        "sameRingSlopeMagnitude", emptyValidity, ...
        "sameRingSlopeChange", emptyValidity, ...
        "bilateralTangentDeflection", emptyValidity, ...
        "huangTangentialStrength", emptyValidity, ...
        "huangRadiusRatioDeviation", emptyValidity, ...
        "huangHdInRadius", emptyValidity, ...
        "hataDifferentialHeightResponse", emptyValidity, ...
        "radiusRatioReconstructionDeviation", emptyValidity, ...
        "wangHorizontalSpacingRatio", emptyValidity, ...
        "wangHorizontalSpacingExcess", emptyValidity, ...
        "radialSecondDifference", emptyValidity, ...
        "localMultiscaleHaarZ", false(haarSize), ...
        "localMultiscaleHaarRange", false(haarSize), ...
        "localChordResidual", emptyValidity, ...
        "hataCompressionRaw", emptyValidity, ...
        "hataCompressionExpected", emptyValidity, ...
        "hataCompressionNormalized", emptyValidity, ...
        "ilpLineFitResidual", emptyValidity, ...
        "ilpLineSlopeMagnitude", emptyValidity);
end

function [features, validity] = localComputeOrderedRingFeatures( ...
        row, parameters)
    pointCount = numel(row.x);
    [features, validity] = localInitializeRowOutputs( ...
        pointCount, numel(parameters.haarScales));
    if pointCount < 2
        return;
    end

    angularGapDegrees = mod( ...
        [diff(row.azimuthDegrees), ...
         row.azimuthDegrees(1) + 360.0 - row.azimuthDegrees(end)], ...
        360.0);
    connectedEdge = ...
        angularGapDegrees > eps ...
        & angularGapDegrees <= parameters.maximumAngularGapDegrees;
    previousIndex = [pointCount, 1:(pointCount - 1)];
    nextIndex = [2:pointCount, 1];
    leftConnected = connectedEdge(previousIndex);
    rightConnected = connectedEdge;

    leftHeightStep = abs(row.z - row.z(previousIndex));
    rightHeightStep = abs(row.z(nextIndex) - row.z);
    leftRangeStep = abs(row.range - row.range(previousIndex));
    rightRangeStep = abs(row.range(nextIndex) - row.range);
    [features.heightStep, validity.heightStep] = ...
        localMaximumAvailable( ...
            leftHeightStep, leftConnected, ...
            rightHeightStep, rightConnected);
    [features.rangeStep, validity.rangeStep] = ...
        localMaximumAvailable( ...
            leftRangeStep, leftConnected, ...
            rightRangeStep, rightConnected);

    centerPoints = [row.x(:), row.y(:), row.z(:)];
    [features.chenSmoothness, validity.chenSmoothness] = ...
        localChenSmoothness( ...
            row, centerPoints, connectedEdge, parameters.chenRadius);
    edgeLengths = localRowNorms( ...
        centerPoints(nextIndex, :) - centerPoints);
    [features.leftSmoothArcLength, ...
        validity.leftSmoothArcLength] = localChenSmoothArcLength( ...
            connectedEdge, edgeLengths, features.chenSmoothness, ...
            validity.chenSmoothness, -1, ...
            parameters.chenSmoothnessThreshold, ...
            parameters.smoothArcMaximumSearchRadius);
    [features.rightSmoothArcLength, ...
        validity.rightSmoothArcLength] = localChenSmoothArcLength( ...
            connectedEdge, edgeLengths, features.chenSmoothness, ...
            validity.chenSmoothness, 1, ...
            parameters.chenSmoothnessThreshold, ...
            parameters.smoothArcMaximumSearchRadius);

    bothNeighborsValid = leftConnected & rightConnected;
    leftPoints = centerPoints(previousIndex, :);
    rightPoints = centerPoints(nextIndex, :);
    leftHorizontalGap = hypot( ...
        row.x - row.x(previousIndex), ...
        row.y - row.y(previousIndex));
    rightHorizontalGap = hypot( ...
        row.x(nextIndex) - row.x, ...
        row.y(nextIndex) - row.y);
    leftSlope = atan2( ...
        row.z - row.z(previousIndex), leftHorizontalGap);
    rightSlope = atan2( ...
        row.z(nextIndex) - row.z, rightHorizontalGap);
    leftSlopeMagnitudeValid = leftConnected & leftHorizontalGap > eps;
    rightSlopeMagnitudeValid = rightConnected & rightHorizontalGap > eps;
    [features.sameRingSlopeMagnitude, ...
        validity.sameRingSlopeMagnitude] = localMaximumAvailable( ...
            abs(leftSlope), leftSlopeMagnitudeValid, ...
            abs(rightSlope), rightSlopeMagnitudeValid);
    validity.sameRingSlopeChange = bothNeighborsValid ...
        & leftHorizontalGap > eps & rightHorizontalGap > eps;
    features.sameRingSlopeChange = abs( ...
        localWrapToPi(rightSlope - leftSlope));
    features.sameRingSlopeChange( ...
        ~validity.sameRingSlopeChange) = NaN;

    leftVector = leftPoints - centerPoints;
    rightVector = rightPoints - centerPoints;
    leftNorm = sqrt(sum(leftVector.^2, 2));
    rightNorm = sqrt(sum(rightVector.^2, 2));
    validity.bilateralTangentDeflection = ...
        reshape(bothNeighborsValid, [], 1) ...
        & leftNorm > eps & rightNorm > eps;
    bilateralCosine = sum(leftVector .* rightVector, 2) ...
        ./ (leftNorm .* rightNorm);
    bilateralCosine = min(1.0, max(-1.0, bilateralCosine));
    bilateralDeflection = pi - acos(bilateralCosine);
    bilateralDeflection( ...
        ~validity.bilateralTangentDeflection(:)) = NaN;
    features.bilateralTangentDeflection = ...
        reshape(bilateralDeflection, 1, []);
    validity.bilateralTangentDeflection = reshape( ...
        validity.bilateralTangentDeflection, 1, []);

    centerRoadPlane = centerPoints(:, 1:2);
    neighborRoadPlaneChord = ...
        rightPoints(:, 1:2) - leftPoints(:, 1:2);
    radialNorm = sqrt(sum(centerRoadPlane.^2, 2));
    chordNorm = sqrt(sum(neighborRoadPlaneChord.^2, 2));
    validity.huangTangentialStrength = ...
        reshape(bothNeighborsValid, [], 1) ...
        & radialNorm > eps & chordNorm > eps;
    huangStrength = abs(sum( ...
        centerRoadPlane .* neighborRoadPlaneChord, 2)) ...
        ./ (radialNorm .* chordNorm);
    huangStrength(~validity.huangTangentialStrength(:)) = NaN;
    features.huangTangentialStrength = reshape(huangStrength, 1, []);
    validity.huangTangentialStrength = reshape( ...
        validity.huangTangentialStrength, 1, []);

    leftRadiusRatioValid = leftConnected ...
        & abs(row.range(previousIndex)) > eps;
    rightRadiusRatioValid = rightConnected ...
        & abs(row.range(nextIndex)) > eps;
    leftRadiusRatioDeviation = nan(size(row.range));
    rightRadiusRatioDeviation = nan(size(row.range));
    leftRadiusRatioDeviation(leftRadiusRatioValid) = abs( ...
        row.range(leftRadiusRatioValid) ...
            ./ row.range(previousIndex(leftRadiusRatioValid)) - 1.0);
    rightRadiusRatioDeviation(rightRadiusRatioValid) = abs( ...
        row.range(rightRadiusRatioValid) ...
            ./ row.range(nextIndex(rightRadiusRatioValid)) - 1.0);
    [features.huangRadiusRatioDeviation, ...
        validity.huangRadiusRatioDeviation] = localMaximumAvailable( ...
            leftRadiusRatioDeviation, leftRadiusRatioValid, ...
            rightRadiusRatioDeviation, rightRadiusRatioValid);

    validity.hataDifferentialHeightResponse = bothNeighborsValid;
    features.hataDifferentialHeightResponse = 2.0 * abs( ...
        row.z(nextIndex) - row.z(previousIndex));
    features.hataDifferentialHeightResponse( ...
        ~validity.hataDifferentialHeightResponse) = NaN;

    leftAngularGap = angularGapDegrees(previousIndex);
    rightAngularGap = angularGapDegrees;
    totalAngularGap = leftAngularGap + rightAngularGap;
    validity.radiusRatioReconstructionDeviation = ...
        bothNeighborsValid & totalAngularGap > eps;
    reconstructedRadius = ...
        (rightAngularGap .* row.range(previousIndex) ...
            + leftAngularGap .* row.range(nextIndex)) ...
        ./ totalAngularGap;
    features.radiusRatioReconstructionDeviation = abs( ...
        row.range ./ reconstructedRadius - 1.0);
    validity.radiusRatioReconstructionDeviation = ...
        validity.radiusRatioReconstructionDeviation ...
        & isfinite(reconstructedRadius) ...
        & abs(reconstructedRadius) > eps;
    features.radiusRatioReconstructionDeviation( ...
        ~validity.radiusRatioReconstructionDeviation) = NaN;

    leftExpectedSpacing = localExpectedHorizontalChord( ...
        row.range, row.range(previousIndex), leftAngularGap);
    rightExpectedSpacing = localExpectedHorizontalChord( ...
        row.range, row.range(nextIndex), rightAngularGap);
    leftSpacingRatio = leftHorizontalGap ./ leftExpectedSpacing;
    rightSpacingRatio = rightHorizontalGap ./ rightExpectedSpacing;
    validity.wangHorizontalSpacingRatio = bothNeighborsValid ...
        & leftExpectedSpacing > eps & rightExpectedSpacing > eps;
    features.wangHorizontalSpacingRatio = max( ...
        leftSpacingRatio, rightSpacingRatio);
    features.wangHorizontalSpacingRatio( ...
        ~validity.wangHorizontalSpacingRatio) = NaN;
    validity.wangHorizontalSpacingExcess = ...
        validity.wangHorizontalSpacingRatio;
    features.wangHorizontalSpacingExcess = max( ...
        0.0, features.wangHorizontalSpacingRatio - 1.0);

    validity.radialSecondDifference = bothNeighborsValid;
    features.radialSecondDifference = abs( ...
        row.range(previousIndex) - 2.0 * row.range ...
            + row.range(nextIndex));
    features.radialSecondDifference( ...
        ~validity.radialSecondDifference) = NaN;

    [features.localChordResidual, validity.localChordResidual] = ...
        localChordResidual(row, previousIndex, nextIndex, ...
            bothNeighborsValid);

    [features, validity] = localWindowStatistics( ...
        features, validity, row, connectedEdge, parameters);

    [features.localMultiscaleHaarZ, ...
        validity.localMultiscaleHaarZ] = localMultiscaleHaar( ...
            row.z, connectedEdge, parameters.haarScales);
    [features.localMultiscaleHaarRange, ...
        validity.localMultiscaleHaarRange] = localMultiscaleHaar( ...
            row.range, connectedEdge, parameters.haarScales);
end

function [features, validity] = localWindowStatistics( ...
        features, validity, row, connectedEdge, parameters)
%LOCALWINDOWSTATISTICS Vectorized symmetric-window statistics and line fit.
    pointCount = numel(row.x);
    heightColumn = reshape(row.z, [], 1);
    rangeColumn = reshape(row.range, [], 1);

    statisticsConnected = localWindowAllConnected( ...
        connectedEdge, parameters.statisticsRadius);
    if any(statisticsConnected)
        window = localCircularWindowIndices(pointCount, ...
            -parameters.statisticsRadius:parameters.statisticsRadius);
        windowHeights = reshape(heightColumn(window), pointCount, []);
        windowRanges = reshape(rangeColumn(window), pointCount, []);
        heightStd = std(windowHeights, 0, 2);
        rangeStd = std(windowRanges, 0, 2);
        heightRange = max(windowHeights, [], 2) ...
            - min(windowHeights, [], 2);
        meanElevation = mean(windowHeights, 2);
        features.localHeightStd(statisticsConnected) = ...
            heightStd(statisticsConnected);
        features.localRangeStd(statisticsConnected) = ...
            rangeStd(statisticsConnected);
        features.localHeightRange(statisticsConnected) = ...
            heightRange(statisticsConnected);
        features.localMeanElevation(statisticsConnected) = ...
            meanElevation(statisticsConnected);
        validity.localHeightStd = statisticsConnected;
        validity.localRangeStd = statisticsConnected;
        validity.localHeightRange = statisticsConnected;
        validity.localMeanElevation = statisticsConnected;
    end

    lineConnected = localWindowAllConnected( ...
        connectedEdge, parameters.lineFitRadius);
    if any(lineConnected)
        centers = reshape(find(lineConnected), [], 1);
        [residuals, slopes] = localBatchLineFit( ...
            row, parameters.lineFitRadius, centers);
        features.ilpLineFitResidual(lineConnected) = residuals;
        features.ilpLineSlopeMagnitude(lineConnected) = slopes;
        validity.ilpLineFitResidual = lineConnected;
        validity.ilpLineSlopeMagnitude = lineConnected;
    end
end

function [features, validity] = localInitializeRowOutputs( ...
        pointCount, numberOfScales)
    scalarNan = nan(1, pointCount);
    scalarFalse = false(1, pointCount);
    features = struct( ...
        "heightStep", scalarNan, ...
        "rangeStep", scalarNan, ...
        "localHeightStd", scalarNan, ...
        "localRangeStd", scalarNan, ...
        "localHeightRange", scalarNan, ...
        "localMeanElevation", scalarNan, ...
        "chenSmoothness", scalarNan, ...
        "leftSmoothArcLength", scalarNan, ...
        "rightSmoothArcLength", scalarNan, ...
        "sameRingSlopeMagnitude", scalarNan, ...
        "sameRingSlopeChange", scalarNan, ...
        "bilateralTangentDeflection", scalarNan, ...
        "huangTangentialStrength", scalarNan, ...
        "huangRadiusRatioDeviation", scalarNan, ...
        "hataDifferentialHeightResponse", scalarNan, ...
        "radiusRatioReconstructionDeviation", scalarNan, ...
        "wangHorizontalSpacingRatio", scalarNan, ...
        "wangHorizontalSpacingExcess", scalarNan, ...
        "radialSecondDifference", scalarNan, ...
        "localMultiscaleHaarZ", nan(pointCount, numberOfScales), ...
        "localMultiscaleHaarRange", nan(pointCount, numberOfScales), ...
        "localChordResidual", scalarNan, ...
        "ilpLineFitResidual", scalarNan, ...
        "ilpLineSlopeMagnitude", scalarNan);
    validity = struct( ...
        "heightStep", scalarFalse, ...
        "rangeStep", scalarFalse, ...
        "localHeightStd", scalarFalse, ...
        "localRangeStd", scalarFalse, ...
        "localHeightRange", scalarFalse, ...
        "localMeanElevation", scalarFalse, ...
        "chenSmoothness", scalarFalse, ...
        "leftSmoothArcLength", scalarFalse, ...
        "rightSmoothArcLength", scalarFalse, ...
        "sameRingSlopeMagnitude", scalarFalse, ...
        "sameRingSlopeChange", scalarFalse, ...
        "bilateralTangentDeflection", scalarFalse, ...
        "huangTangentialStrength", scalarFalse, ...
        "huangRadiusRatioDeviation", scalarFalse, ...
        "hataDifferentialHeightResponse", scalarFalse, ...
        "radiusRatioReconstructionDeviation", scalarFalse, ...
        "wangHorizontalSpacingRatio", scalarFalse, ...
        "wangHorizontalSpacingExcess", scalarFalse, ...
        "radialSecondDifference", scalarFalse, ...
        "localMultiscaleHaarZ", ...
            false(pointCount, numberOfScales), ...
        "localMultiscaleHaarRange", ...
            false(pointCount, numberOfScales), ...
        "localChordResidual", scalarFalse, ...
        "ilpLineFitResidual", scalarFalse, ...
        "ilpLineSlopeMagnitude", scalarFalse);
end

function [maximumValue, valid] = localMaximumAvailable( ...
        leftValue, leftValid, rightValue, rightValid)
    valid = leftValid | rightValid;
    maximumValue = nan(size(leftValue));
    maximumValue(leftValid) = leftValue(leftValid);
    rightOnly = rightValid & ~leftValid;
    maximumValue(rightOnly) = rightValue(rightOnly);
    bothValid = leftValid & rightValid;
    maximumValue(bothValid) = max( ...
        leftValue(bothValid), rightValue(bothValid));
end

function windowIndices = localCircularWindowIndices(pointCount, offsets)
%LOCALCIRCULARWINDOWINDICES Circular neighbor indices, one row per center.
    windowIndices = mod( ...
        (1:pointCount).' + reshape(offsets, 1, []) - 1, pointCount) + 1;
end

function connected = localWindowAllConnected(connectedEdge, radius)
%LOCALWINDOWALLCONNECTED True where every edge within RADIUS is connected.
%   Edge indices (center-radius .. center+radius-1) wrap circularly, which
%   matches walking RADIUS steps in both directions from each center.
    pointCount = numel(connectedEdge);
    connected = false(1, pointCount);
    if pointCount <= 2 * radius
        return;
    end
    edgeCumulative = cumsum([0, connectedEdge, connectedEdge]);
    windowLength = 2 * radius;
    startEdge = mod((1:pointCount) - radius - 1, pointCount) + 1;
    connected = (edgeCumulative(startEdge + windowLength) ...
        - edgeCumulative(startEdge)) == windowLength;
end

function norms = localRowNorms(rowVectors)
%LOCALROWNORMS Per-row Euclidean norms matching scalar norm() bitwise.
    norms = vecnorm(rowVectors, 2, 2);
end

function [smoothness, valid] = localChenSmoothness( ...
        row, centerPoints, connectedEdge, radius)
    pointCount = numel(row.x);
    smoothness = nan(1, pointCount);
    valid = false(1, pointCount);
    windowConnected = localWindowAllConnected(connectedEdge, radius);
    if ~any(windowConnected)
        return;
    end
    centerNorms = localRowNorms(centerPoints);
    usable = windowConnected & reshape(centerNorms > eps, 1, []);
    if ~any(usable)
        return;
    end

    % Neighbor rows are summed in the original walk order:
    % center-1, center-2, ..., center-radius, center+1, ..., center+radius.
    window = localCircularWindowIndices( ...
        pointCount, [-(1:radius), 1:radius]);
    neighborSum = zeros(pointCount, 3);
    for columnIndex = 1:3
        source = centerPoints(:, columnIndex);
        windowValues = reshape(source(window), pointCount, []);
        columnSum = windowValues(:, 1);
        for windowColumn = 2:size(windowValues, 2)
            columnSum = columnSum + windowValues(:, windowColumn);
        end
        neighborSum(:, columnIndex) = columnSum;
    end
    responseVector = neighborSum - 2.0 * radius * centerPoints;
    responseNorms = localRowNorms(responseVector);
    smoothnessColumn = responseNorms ./ (2.0 * radius * centerNorms);
    smoothness(usable) = smoothnessColumn(usable);
    valid = usable;
end

function [arcLength, valid] = localChenSmoothArcLength( ...
        connectedEdge, edgeLengths, chenSmoothness, chenValidity, ...
        direction, smoothnessThreshold, maximumSearchRadius)
%LOCALCHENSMOOTHARCLENGTH Vectorized directional smooth-arc walk.
%   All centers advance one step per iteration; each stalled center keeps
%   its accumulated length, so the per-center addition order matches the
%   original scalar walk exactly.
    pointCount = numel(connectedEdge);
    arcLength = nan(1, pointCount);
    valid = false(1, pointCount);
    if pointCount < 2
        return;
    end
    edgeLengthColumn = reshape(edgeLengths, [], 1);
    if direction > 0
        targetIndex = [2:pointCount, 1];
        stepEdgeIndex = 1:pointCount;
    else
        targetIndex = [pointCount, 1:(pointCount - 1)];
        stepEdgeIndex = [pointCount, 1:(pointCount - 1)];
    end
    stepAllowed = connectedEdge(stepEdgeIndex) ...
        & chenValidity(targetIndex) ...
        & ~(chenSmoothness(targetIndex) > smoothnessThreshold);

    currentIndex = 1:pointCount;
    accumulated = zeros(1, pointCount);
    stepCount = zeros(1, pointCount);
    alive = true(1, pointCount);
    for step = 1:min(maximumSearchRadius, pointCount - 1)
        alive = alive & stepAllowed(currentIndex);
        if ~any(alive)
            break;
        end
        accumulated(alive) = accumulated(alive) ...
            + reshape(edgeLengthColumn( ...
                stepEdgeIndex(currentIndex(alive))), 1, []);
        currentIndex(alive) = targetIndex(currentIndex(alive));
        stepCount(alive) = stepCount(alive) + 1;
    end
    valid = stepCount > 0;
    arcLength(valid) = accumulated(valid);
end

function expectedSpacing = localExpectedHorizontalChord( ...
        centerRange, neighborRange, angularGapDegrees)
    localRadius = 0.5 * (abs(centerRange) + abs(neighborRange));
    expectedSpacing = ...
        2.0 * localRadius .* sind(0.5 * angularGapDegrees);
end

function [residual, valid] = localChordResidual( ...
        row, previousIndex, nextIndex, bothNeighborsValid)
    leftX = row.x(previousIndex);
    leftY = row.y(previousIndex);
    chordX = row.x(nextIndex) - leftX;
    chordY = row.y(nextIndex) - leftY;
    chordLengthSquared = chordX.^2 + chordY.^2;
    valid = bothNeighborsValid & chordLengthSquared > eps;
    projection = ...
        ((row.x - leftX) .* chordX + (row.y - leftY) .* chordY) ...
        ./ chordLengthSquared;
    projection = min(1.0, max(0.0, projection));
    closestX = leftX + projection .* chordX;
    closestY = leftY + projection .* chordY;
    residual = hypot(row.x - closestX, row.y - closestY);
    residual(~valid) = NaN;
end

function [residuals, slopes] = localBatchLineFit(row, radius, centers)
%LOCALBATCHLINEFIT Least-squares z-versus-arc line fit per center.
%   The design matrix, height vector, and accumulation order per center
%   replicate the original per-point construction exactly, and
%   pagemldivide/pagemtimes match per-page mldivide/mtimes bitwise.
    pointCount = numel(row.x);
    windowWidth = 2 * radius + 1;
    centerCount = numel(centers);
    horizontalStep = reshape(hypot( ...
        row.x([2:pointCount, 1]) - row.x, ...
        row.y([2:pointCount, 1]) - row.y), [], 1);

    arcCoordinate = zeros(centerCount, windowWidth);
    leftAccumulated = zeros(centerCount, 1);
    rightAccumulated = zeros(centerCount, 1);
    for step = 1:radius
        leftEdge = mod(centers - step - 1, pointCount) + 1;
        rightEdge = mod(centers + step - 2, pointCount) + 1;
        leftAccumulated = leftAccumulated + horizontalStep(leftEdge);
        rightAccumulated = rightAccumulated + horizontalStep(rightEdge);
        arcCoordinate(:, radius + 1 - step) = -leftAccumulated;
        arcCoordinate(:, radius + 1 + step) = rightAccumulated;
    end

    window = mod(centers + (-radius:radius) - 1, pointCount) + 1;
    heightColumn = reshape(row.z, [], 1);
    windowHeights = reshape(heightColumn(window), centerCount, []);

    designPages = ones(windowWidth, 2, centerCount);
    designPages(:, 1, :) = reshape( ...
        arcCoordinate.', windowWidth, 1, centerCount);
    heightPages = reshape( ...
        windowHeights.', windowWidth, 1, centerCount);
    coefficients = pagemldivide(designPages, heightPages);
    fitted = pagemtimes(designPages, coefficients);
    squaredResiduals = reshape( ...
        (heightPages - fitted).^2, windowWidth, centerCount);
    residuals = sqrt(mean(squaredResiduals, 1));
    slopes = reshape(abs(coefficients(1, 1, :)), 1, centerCount);
end

function [response, valid] = localMultiscaleHaar( ...
        values, connectedEdge, scales)
    pointCount = numel(values);
    response = nan(pointCount, numel(scales));
    valid = false(pointCount, numel(scales));
    valueColumn = reshape(values, [], 1);
    for scaleIndex = 1:numel(scales)
        radius = scales(scaleIndex);
        windowConnected = localWindowAllConnected( ...
            connectedEdge, radius);
        if ~any(windowConnected)
            continue;
        end
        % Left indices keep the walk order center-1, ..., center-radius.
        leftWindow = localCircularWindowIndices( ...
            pointCount, -(1:radius));
        rightWindow = localCircularWindowIndices( ...
            pointCount, 1:radius);
        leftMean = mean(reshape( ...
            valueColumn(leftWindow), pointCount, []), 2);
        rightMean = mean(reshape( ...
            valueColumn(rightWindow), pointCount, []), 2);
        scaleResponse = abs(rightMean - leftMean);
        response(windowConnected, scaleIndex) = ...
            scaleResponse(windowConnected);
        valid(:, scaleIndex) = reshape(windowConnected, [], 1);
    end
end

function [features, validity] = localComputeHuangHdInRadius( ...
        features, validity, x, y, z, baseValid)
    numberOfRings = size(x, 1);
    for ringIndex = 1:numberOfRings
        [lowerDirectionValue, lowerDirectionValid] = ...
            localHuangHdTriplet( ...
                ringIndex, -1, x, y, z, baseValid);
        [upperDirectionValue, upperDirectionValid] = ...
            localHuangHdTriplet( ...
                ringIndex, 1, x, y, z, baseValid);
        [features.huangHdInRadius(ringIndex, :), ...
            validity.huangHdInRadius(ringIndex, :)] = ...
                localMaximumAvailable( ...
                    lowerDirectionValue, lowerDirectionValid, ...
                    upperDirectionValue, upperDirectionValid);
    end
end

function [residualMagnitude, valid] = localHuangHdTriplet( ...
        cRingIndex, direction, x, y, z, baseValid)
    residualMagnitude = nan(1, size(x, 2));
    valid = false(1, size(x, 2));
    bRingIndex = cRingIndex + direction;
    aRingIndex = cRingIndex + 2 * direction;
    if aRingIndex < 1 || aRingIndex > size(x, 1)
        return;
    end

    valid = baseValid(aRingIndex, :) ...
        & baseValid(bRingIndex, :) ...
        & baseValid(cRingIndex, :);
    distanceAb = hypot( ...
        x(bRingIndex, :) - x(aRingIndex, :), ...
        y(bRingIndex, :) - y(aRingIndex, :));
    distanceBc = hypot( ...
        x(cRingIndex, :) - x(bRingIndex, :), ...
        y(cRingIndex, :) - y(bRingIndex, :));
    valid = valid & distanceAb > eps;
    residualMagnitude(valid) = abs( ...
        z(cRingIndex, valid) - z(bRingIndex, valid) ...
        - (z(bRingIndex, valid) - z(aRingIndex, valid)) ...
            .* distanceBc(valid) ./ distanceAb(valid));
end

function [features, validity] = localComputeHataCompression( ...
        features, validity, x, y, baseValid, parameters)
    numberOfRings = size(x, 1);
    for lowerRingIndex = 2:numberOfRings
        upperRingIndex = lowerRingIndex - 1;
        upperColumns = find(baseValid(upperRingIndex, :));
        lowerColumns = find(baseValid(lowerRingIndex, :));
        if isempty(upperColumns) || isempty(lowerColumns)
            continue;
        end
        upperAngle = parameters.verticalAnglesDegrees(upperRingIndex);
        lowerAngle = parameters.verticalAnglesDegrees(lowerRingIndex);
        if upperAngle >= -eps || lowerAngle >= -eps
            continue;
        end
        expectedUpperRange = ...
            parameters.sensorHeightM / tand(-upperAngle);
        expectedLowerRange = ...
            parameters.sensorHeightM / tand(-lowerAngle);
        expectedSpacing = ...
            expectedUpperRange - expectedLowerRange;
        if ~isfinite(expectedSpacing) || expectedSpacing <= eps
            continue;
        end

        upperAzimuth = mod(atan2d( ...
            y(upperRingIndex, upperColumns), ...
            x(upperRingIndex, upperColumns)), 360.0);
        lowerAzimuth = mod(atan2d( ...
            y(lowerRingIndex, lowerColumns), ...
            x(lowerRingIndex, lowerColumns)), 360.0);
        upperHorizontalRange = hypot( ...
            x(upperRingIndex, upperColumns), ...
            y(upperRingIndex, upperColumns));
        lowerHorizontalRange = hypot( ...
            x(lowerRingIndex, lowerColumns), ...
            y(lowerRingIndex, lowerColumns));
        % One row per lower-ring return; min along dim 2 picks the same
        % first-minimum upper index as the original per-point min call.
        angularDistanceMatrix = abs(localWrapTo180( ...
            reshape(upperAzimuth, 1, []) ...
            - reshape(lowerAzimuth, [], 1)));
        [minimumAngularDistance, closestUpperIndex] = ...
            min(angularDistanceMatrix, [], 2);
        withinGap = reshape(minimumAngularDistance, 1, []) ...
            <= parameters.maximumAngularGapDegrees;
        if ~any(withinGap)
            continue;
        end
        observedSpacing = abs( ...
            upperHorizontalRange(closestUpperIndex) ...
            - lowerHorizontalRange);
        rawCompression = expectedSpacing - observedSpacing;
        targetColumns = lowerColumns(withinGap);
        features.hataCompressionRaw(lowerRingIndex, targetColumns) = ...
            rawCompression(withinGap);
        features.hataCompressionExpected( ...
            lowerRingIndex, targetColumns) = expectedSpacing;
        features.hataCompressionNormalized( ...
            lowerRingIndex, targetColumns) = ...
            rawCompression(withinGap) / expectedSpacing;
        validity.hataCompressionRaw( ...
            lowerRingIndex, targetColumns) = true;
        validity.hataCompressionExpected( ...
            lowerRingIndex, targetColumns) = true;
        validity.hataCompressionNormalized( ...
            lowerRingIndex, targetColumns) = true;
    end
end

function angle = localWrapToPi(angle)
    angle = mod(angle + pi, 2.0 * pi) - pi;
end

function angle = localWrapTo180(angle)
    angle = mod(angle + 180.0, 360.0) - 180.0;
end
