function model = emptyCurbBoundaryModel()
% emptyCurbBoundaryModel Not-found curb boundary model with the full schema.
%
% One curb boundary curve, y = curvature*x^2 + slope*x + intercept in the
% detected road frame, together with its support and score bookkeeping.
% This is the single schema shared by the detector, the temporal wrapper,
% and the tracker; a model with found=false carries only defaults.

    model = struct( ...
        "found", false, ...
        "curvature", 0.0, ...
        "slope", NaN, ...
        "intercept", NaN, ...
        "minimumX", NaN, ...
        "maximumX", NaN, ...
        "minimumZ", NaN, ...
        "maximumZ", NaN, ...
        "azimuthSupport", 0, ...
        "longitudinalSpan", 0.0, ...
        "score", -inf, ...
        "selectedOuterCandidate", false);
end
