function summary = evaluateCurbDetectorDevelopmentRegression( ...
        datasetFolder, options)
%EVALUATECURBDETECTORDEVELOPMENTREGRESSION Check reviewed curb coordinates.
%   SUMMARY = EVALUATECURBDETECTORDEVELOPMENTREGRESSION() loads the
%   repository-local outer-loop dataset, organizes each selected LiDAR frame
%   into the same 64-by-1000 grid used by exportCurbPointIndices, and runs
%   the current groundPointsProcessing detector.
%
%   SUMMARY = EVALUATECURBDETECTORDEVELOPMENTREGRESSION(DATASETFOLDER,
%   OutputDirectory=DIR, FrameIndices=INDICES, NearbyToleranceM=TOLERANCE)
%   limits evaluation to zero-based frame indices and configures the nearby
%   selection distance. The default nearby tolerance is 0.30 m.
%
%   Exact selection means that the raw point matched to a reviewed
%   coordinate is selected by the detector. Nearby selection means that at
%   least one detector-selected curb point lies within NearbyToleranceM of
%   the reviewed coordinate. Existing detector masks are never read as
%   labels. These labels already informed development and are not
%   independent ground truth.

    arguments
        datasetFolder (1, 1) string = ""
        options.OutputDirectory (1, 1) string = ""
        options.FrameIndices (1, :) double ...
            {mustBeInteger, mustBeNonnegative} = []
        options.NearbyToleranceM (1, 1) double ...
            {mustBePositive, mustBeFinite} = 0.30
        options.MatchToleranceM (1, 1) double ...
            {mustBePositive, mustBeFinite} = 1.0e-4
        options.DetectorConfig (1, 1) struct = struct()
        options.LabelCatalog (1, 1) struct = struct()
        options.FrameLoader = []
        options.DetectorFunction = []
    end

    repositoryRoot = fileparts(fileparts(fileparts( ...
        mfilename("fullpath"))));
    if strlength(datasetFolder) == 0
        datasetFolder = fullfile( ...
            repositoryRoot, "simulation", "data", ...
            "carla_outer_loop_lap_10hz_20260802_epic_no_rt_auto");
    end
    if strlength(options.OutputDirectory) == 0
        options.OutputDirectory = fullfile( ...
            repositoryRoot, "simulation_output", ...
            "curb_detector_development_regression");
    end
    detectorFolder = fullfile( ...
        repositoryRoot, "perception", "curbDetectionExperiment");
    originalPath = path();
    pathCleanup = onCleanup(@() path(originalPath));
    addpath(detectorFolder);

    if isempty(fieldnames(options.LabelCatalog))
        catalog = curbRingFeatureDevelopmentLabels();
    else
        catalog = options.LabelCatalog;
    end
    localValidateCatalog(catalog);

    usesDefaultFrameLoader = isempty(options.FrameLoader);
    if usesDefaultFrameLoader
        frameLoader = @localLoadNpyFrame;
    elseif isa(options.FrameLoader, "function_handle") ...
            && isscalar(options.FrameLoader)
        frameLoader = options.FrameLoader;
    else
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "InvalidFrameLoader", ...
            "FrameLoader must be empty or a scalar function handle.");
    end
    if isempty(options.DetectorFunction)
        detectorFunction = @groundPointsProcessing;
    elseif isa(options.DetectorFunction, "function_handle") ...
            && isscalar(options.DetectorFunction)
        detectorFunction = options.DetectorFunction;
    else
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "InvalidDetectorFunction", ...
            "DetectorFunction must be empty or a scalar function handle.");
    end

    localValidateDataset( ...
        datasetFolder, catalog, usesDefaultFrameLoader);
    anchors = catalog.anchors;
    if ~isempty(options.FrameIndices)
        anchors = anchors(ismember( ...
            [anchors.frameIndex], options.FrameIndices));
    end
    if ~isfolder(options.OutputDirectory)
        mkdir(options.OutputDirectory);
    end

    labelResultsTable = localEmptyLabelResultsTable();
    statusFrameIndex = zeros(0, 1);
    statusRawPointCount = zeros(0, 1);
    statusSelectedCurbPointCount = zeros(0, 1);
    statusRoadHeadingDegrees = nan(0, 1);
    statusRoadFrameSource = strings(0, 1);
    statusCurbModelFields = strings(0, 1);
    statusRingFeatureFusionEnabled = false(0, 1);
    statusRingFeatureActivationSource = strings(0, 1);
    statusLegacyCandidateCount = zeros(0, 1);
    statusAcceptedCandidateCount = zeros(0, 1);
    statusOrientationCandidateCount = zeros(0, 1);
    statusOrientationSeedSource = strings(0, 1);
    statusFeatureAcceptedCellCount = zeros(0, 1);
    frameStatuses = strings(0, 1);
    for anchorIndex = 1:numel(anchors)
        anchor = anchors(anchorIndex);
        [coordinates, labels, indicesWithinLabel] = ...
            localAnchorCoordinates(anchor);
        if isempty(coordinates)
            statusFrameIndex(end + 1, 1) = ...
                double(anchor.frameIndex); %#ok<AGROW>
            statusRawPointCount(end + 1, 1) = 0; %#ok<AGROW>
            statusSelectedCurbPointCount(end + 1, 1) = 0; %#ok<AGROW>
            statusRoadHeadingDegrees(end + 1, 1) = NaN; %#ok<AGROW>
            statusRoadFrameSource(end + 1, 1) = ""; %#ok<AGROW>
            statusCurbModelFields(end + 1, 1) = ""; %#ok<AGROW>
            statusRingFeatureFusionEnabled(end + 1, 1) = false; %#ok<AGROW>
            statusRingFeatureActivationSource(end + 1, 1) = ""; %#ok<AGROW>
            statusLegacyCandidateCount(end + 1, 1) = 0; %#ok<AGROW>
            statusAcceptedCandidateCount(end + 1, 1) = 0; %#ok<AGROW>
            statusOrientationCandidateCount(end + 1, 1) = 0; %#ok<AGROW>
            statusOrientationSeedSource(end + 1, 1) = ""; %#ok<AGROW>
            statusFeatureAcceptedCellCount(end + 1, 1) = 0; %#ok<AGROW>
            frameStatuses(end + 1, 1) = ...
                "skipped-no-coordinate-labels"; %#ok<AGROW>
            continue
        end

        rawPoints = frameLoader(datasetFolder, anchor.frameIndex);
        localValidateRawPoints(rawPoints, anchor.frameIndex);
        [organizedFrame, rawPointIndexGrid] = ...
            organizeLidarSweepGrid(double(rawPoints));
        processingResult = detectorFunction( ...
            organizedFrame, options.DetectorConfig);
        rawCurbIndices = localRawCurbIndices( ...
            processingResult, rawPointIndexGrid);
        selectedPoints = double(rawPoints(rawCurbIndices, 1:3));

        frameResults = localEvaluateLabels( ...
            anchor.frameIndex, coordinates, labels, ...
            indicesWithinLabel, double(rawPoints(:, 1:3)), ...
            rawCurbIndices, selectedPoints, ...
            options.MatchToleranceM, options.NearbyToleranceM);
        labelResultsTable = [ ...
            labelResultsTable; frameResults]; %#ok<AGROW>
        statusFrameIndex(end + 1, 1) = ...
            double(anchor.frameIndex); %#ok<AGROW>
        statusRawPointCount(end + 1, 1) = ...
            double(size(rawPoints, 1)); %#ok<AGROW>
        statusSelectedCurbPointCount(end + 1, 1) = ...
            double(numel(rawCurbIndices)); %#ok<AGROW>
        detectorDiagnostics = localDetectorDiagnostics( ...
            processingResult);
        statusRoadHeadingDegrees(end + 1, 1) = ...
            detectorDiagnostics.roadHeadingDegrees; %#ok<AGROW>
        statusRoadFrameSource(end + 1, 1) = ...
            detectorDiagnostics.roadFrameSource; %#ok<AGROW>
        statusCurbModelFields(end + 1, 1) = ...
            detectorDiagnostics.curbModelFields; %#ok<AGROW>
        statusRingFeatureFusionEnabled(end + 1, 1) = ...
            detectorDiagnostics.ringFeatureFusionEnabled; %#ok<AGROW>
        statusRingFeatureActivationSource(end + 1, 1) = ...
            detectorDiagnostics.ringFeatureActivationSource; %#ok<AGROW>
        statusLegacyCandidateCount(end + 1, 1) = ...
            detectorDiagnostics.legacyCandidateCount; %#ok<AGROW>
        statusAcceptedCandidateCount(end + 1, 1) = ...
            detectorDiagnostics.acceptedCandidateCount; %#ok<AGROW>
        statusOrientationCandidateCount(end + 1, 1) = ...
            detectorDiagnostics.orientationCandidateCount; %#ok<AGROW>
        statusOrientationSeedSource(end + 1, 1) = ...
            detectorDiagnostics.orientationSeedSource; %#ok<AGROW>
        statusFeatureAcceptedCellCount(end + 1, 1) = ...
            detectorDiagnostics.featureAcceptedCellCount; %#ok<AGROW>
        frameStatuses(end + 1, 1) = "evaluated"; %#ok<AGROW>
    end
    clear pathCleanup;

    frameStatusTable = table( ...
        statusFrameIndex, statusRawPointCount, ...
        statusSelectedCurbPointCount, statusRoadHeadingDegrees, ...
        statusRoadFrameSource, statusCurbModelFields, ...
        statusRingFeatureFusionEnabled, ...
        statusRingFeatureActivationSource, ...
        statusLegacyCandidateCount, ...
        statusAcceptedCandidateCount, ...
        statusOrientationCandidateCount, ...
        statusOrientationSeedSource, ...
        statusFeatureAcceptedCellCount, frameStatuses, ...
        VariableNames=[ ...
            "frameIndex", "rawPointCount", ...
            "selectedCurbPointCount", "roadHeadingDegrees", ...
            "roadFrameSource", "curbModelFields", ...
            "ringFeatureFusionEnabled", ...
            "ringFeatureActivationSource", ...
            "legacyCandidateCount", ...
            "acceptedCandidateCount", ...
            "orientationCandidateCount", ...
            "orientationSeedSource", ...
            "featureAcceptedCellCount", "status"]);
    frameLabelSummaryTable = ...
        localFrameLabelSummary(labelResultsTable);
    if isempty(labelResultsTable)
        status = "no-coordinate-labels";
    else
        status = "completed-development-regression";
    end

    outputFiles = struct( ...
        "labelResultsCsv", fullfile( ...
            options.OutputDirectory, "label_results.csv"), ...
        "frameLabelSummaryCsv", fullfile( ...
            options.OutputDirectory, "frame_label_summary.csv"), ...
        "frameStatusCsv", fullfile( ...
            options.OutputDirectory, "frame_status.csv"), ...
        "summaryMat", fullfile( ...
            options.OutputDirectory, ...
            "curb_detector_development_regression.mat"));
    writetable(labelResultsTable, outputFiles.labelResultsCsv);
    writetable( ...
        frameLabelSummaryTable, outputFiles.frameLabelSummaryCsv);
    writetable(frameStatusTable, outputFiles.frameStatusCsv);

    summary = struct( ...
        "status", status, ...
        "datasetFolder", datasetFolder, ...
        "outputDirectory", options.OutputDirectory, ...
        "requestedFrameIndices", options.FrameIndices, ...
        "evaluatedFrameIndices", ...
            unique(labelResultsTable.frameIndex).', ...
        "labelCount", height(labelResultsTable), ...
        "exactSelectedCount", ...
            nnz(labelResultsTable.exactSelected), ...
        "nearbySelectedCount", ...
            nnz(labelResultsTable.nearbySelected), ...
        "nearbyToleranceM", options.NearbyToleranceM, ...
        "matchToleranceM", options.MatchToleranceM, ...
        "detectorConfig", options.DetectorConfig, ...
        "independentGroundTruth", false, ...
        "detectorMasksUsedAsTruth", false, ...
        "caveat", ...
            "These reviewed coordinates already informed detector " + ...
            "development. Results are regression evidence, not " + ...
            "held-out accuracy.", ...
        "outputFiles", outputFiles);
    save( ...
        outputFiles.summaryMat, "summary", "catalog", ...
        "labelResultsTable", "frameLabelSummaryTable", ...
        "frameStatusTable");
end


function diagnostics = localDetectorDiagnostics(processingResult)
    diagnostics = struct( ...
        "roadHeadingDegrees", NaN, ...
        "roadFrameSource", "", ...
        "curbModelFields", "", ...
        "ringFeatureFusionEnabled", false, ...
        "ringFeatureActivationSource", "", ...
        "legacyCandidateCount", 0, ...
        "acceptedCandidateCount", 0, ...
        "orientationCandidateCount", 0, ...
        "orientationSeedSource", "", ...
        "featureAcceptedCellCount", 0);
    if ~isstruct(processingResult) ...
            || ~isfield(processingResult, "curbModels") ...
            || ~isstruct(processingResult.curbModels)
        return
    end
    curbModels = processingResult.curbModels;
    diagnostics.curbModelFields = strjoin( ...
        string(fieldnames(curbModels)), "|");
    if isfield(curbModels, "roadFrame") ...
            && isstruct(curbModels.roadFrame)
        roadFrame = curbModels.roadFrame;
        if isfield(roadFrame, "headingDegrees") ...
                && isscalar(roadFrame.headingDegrees)
            diagnostics.roadHeadingDegrees = ...
                double(roadFrame.headingDegrees);
        end
        if isfield(roadFrame, "source") ...
                && isscalar(string(roadFrame.source))
            diagnostics.roadFrameSource = string(roadFrame.source);
        end
    end
    if ~isfield(curbModels, "ringFeatureFusion") ...
            || ~isstruct(curbModels.ringFeatureFusion)
        return
    end
    ringFeatureFusion = curbModels.ringFeatureFusion;
    if isfield(ringFeatureFusion, "enabled")
        candidate = ringFeatureFusion.enabled;
        if (islogical(candidate) || isnumeric(candidate)) ...
                && isscalar(candidate)
            diagnostics.ringFeatureFusionEnabled = logical(candidate);
        end
    end
    if isfield(ringFeatureFusion, "activationSource") ...
            && isscalar(string(ringFeatureFusion.activationSource))
        diagnostics.ringFeatureActivationSource = ...
            string(ringFeatureFusion.activationSource);
    end
    diagnostics.legacyCandidateCount = localDiagnosticScalar( ...
        ringFeatureFusion, "legacyCandidateCount");
    diagnostics.acceptedCandidateCount = localDiagnosticScalar( ...
        ringFeatureFusion, "acceptedCandidateCount");
    diagnostics.orientationCandidateCount = localDiagnosticScalar( ...
        ringFeatureFusion, "orientationCandidateCount");
    if isfield(ringFeatureFusion, "orientationSeedSource") ...
            && isscalar(string(ringFeatureFusion.orientationSeedSource))
        diagnostics.orientationSeedSource = ...
            string(ringFeatureFusion.orientationSeedSource);
    end
    diagnostics.featureAcceptedCellCount = localDiagnosticScalar( ...
        ringFeatureFusion, "acceptedCellCount");
end


function value = localDiagnosticScalar(source, fieldName)
    value = 0;
    if isfield(source, fieldName)
        candidate = double(source.(fieldName));
        if isscalar(candidate) && isfinite(candidate)
            value = candidate;
        end
    end
end


function localValidateCatalog(catalog)
    requiredFields = [ ...
        "datasetName", "anchors", "independentGroundTruth"];
    if ~isstruct(catalog) || ~isscalar(catalog) ...
            || ~all(isfield(catalog, requiredFields))
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:InvalidCatalog", ...
            "LabelCatalog does not have the required catalog fields.");
    end
    anchorFields = [ ...
        "frameIndex", "positiveCoordinatesM", ...
        "hardNegativeCoordinatesM"];
    if ~isstruct(catalog.anchors) ...
            || ~all(isfield(catalog.anchors, anchorFields))
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:InvalidAnchors", ...
            "LabelCatalog anchors do not have the required fields.");
    end
    for anchorIndex = 1:numel(catalog.anchors)
        anchor = catalog.anchors(anchorIndex);
        localValidateCoordinates( ...
            anchor.positiveCoordinatesM, "positive", ...
            anchor.frameIndex);
        localValidateCoordinates( ...
            anchor.hardNegativeCoordinatesM, "hard-negative", ...
            anchor.frameIndex);
    end
end


function localValidateCoordinates(coordinates, label, frameIndex)
    if ~isnumeric(coordinates) || size(coordinates, 2) ~= 3 ...
            || any(~isfinite(coordinates), "all")
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "InvalidCoordinates", ...
            "Frame %d %s coordinates must be a finite N-by-3 array.", ...
            frameIndex, label);
    end
end


function localValidateDataset( ...
        datasetFolder, catalog, usesDefaultFrameLoader)
    [~, datasetName] = fileparts(datasetFolder);
    if string(datasetName) ~= string(catalog.datasetName)
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "DatasetMismatch", ...
            "The label catalog is for %s, not %s.", ...
            catalog.datasetName, datasetName);
    end
    if usesDefaultFrameLoader ...
            && ~isfolder(fullfile(datasetFolder, "lidar"))
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:MissingLidar", ...
            "Dataset does not contain a lidar folder: %s", ...
            datasetFolder);
    end
end


function [coordinates, labels, indicesWithinLabel] = ...
        localAnchorCoordinates(anchor)
    positiveCoordinates = double(anchor.positiveCoordinatesM);
    hardNegativeCoordinates = ...
        double(anchor.hardNegativeCoordinatesM);
    positiveCount = size(positiveCoordinates, 1);
    hardNegativeCount = size(hardNegativeCoordinates, 1);
    coordinates = [positiveCoordinates; hardNegativeCoordinates];
    labels = [ ...
        repmat("positive", positiveCount, 1); ...
        repmat("hard-negative", hardNegativeCount, 1)];
    indicesWithinLabel = [ ...
        (1:positiveCount).'; (1:hardNegativeCount).'];
end


function rawPoints = localLoadNpyFrame(datasetFolder, frameIndex)
    framePath = fullfile( ...
        datasetFolder, "lidar", sprintf("%06d.npy", frameIndex));
    if ~isfile(framePath)
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:MissingFrame", ...
            "LiDAR frame does not exist: %s", framePath);
    end
    try
        rawPoints = double(py.numpy.load(framePath));
    catch exception
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:NpyLoadFailed", ...
            "Unable to load %s through NumPy: %s", ...
            framePath, exception.message);
    end
end


function localValidateRawPoints(rawPoints, frameIndex)
    if ~isnumeric(rawPoints) || size(rawPoints, 2) < 3 ...
            || isempty(rawPoints) ...
            || any(~isfinite(rawPoints(:, 1:3)), "all")
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:InvalidFrame", ...
            "Frame %d must contain finite XYZ columns.", frameIndex);
    end
end


function rawCurbIndices = localRawCurbIndices( ...
        processingResult, rawPointIndexGrid)
    if ~isstruct(processingResult) ...
            || ~isfield(processingResult, "curbs")
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "InvalidDetectorResult", ...
            "The detector result must contain a curbs field.");
    end
    organizedCurbIndices = processingResult.curbs;
    if isempty(organizedCurbIndices)
        rawCurbIndices = zeros(0, 1);
        return
    end
    if ~isnumeric(organizedCurbIndices) ...
            || size(organizedCurbIndices, 2) ~= 2 ...
            || any(~isfinite(organizedCurbIndices), "all") ...
            || any(organizedCurbIndices ~= ...
                round(organizedCurbIndices), "all") ...
            || any(organizedCurbIndices(:, 1) < 1) ...
            || any(organizedCurbIndices(:, 1) > ...
                size(rawPointIndexGrid, 2)) ...
            || any(organizedCurbIndices(:, 2) < 1) ...
            || any(organizedCurbIndices(:, 2) > ...
                size(rawPointIndexGrid, 1))
        error( ...
            "evaluateCurbDetectorDevelopmentRegression:" + ...
            "InvalidCurbIndices", ...
            "Detector curbs must be valid [azimuth, ring] indices.");
    end
    organizedLinearIndices = sub2ind( ...
        size(rawPointIndexGrid), ...
        organizedCurbIndices(:, 2), ...
        organizedCurbIndices(:, 1));
    rawCurbIndices = rawPointIndexGrid(organizedLinearIndices);
    rawCurbIndices = unique( ...
        rawCurbIndices(rawCurbIndices > 0), "stable");
end


function results = localEvaluateLabels( ...
        frameIndexValue, coordinates, labels, indicesWithinLabel, ...
        rawPoints, rawCurbIndices, selectedPoints, ...
        matchToleranceM, nearbyToleranceM)
    labelCount = size(coordinates, 1);
    frameIndex = repmat(double(frameIndexValue), labelCount, 1);
    label = labels;
    labelIndex = double(indicesWithinLabel);
    labelX = coordinates(:, 1);
    labelY = coordinates(:, 2);
    labelZ = coordinates(:, 3);
    matchedRawPointIndexZeroBased = nan(labelCount, 1);
    matchDistanceM = nan(labelCount, 1);
    labelMatched = false(labelCount, 1);
    exactSelected = false(labelCount, 1);
    nearbySelected = false(labelCount, 1);
    nearestSelectedDistanceM = inf(labelCount, 1);

    for labelIndexValue = 1:labelCount
        coordinate = coordinates(labelIndexValue, :);
        rawDistances = sqrt(sum( ...
            (rawPoints - coordinate) .^ 2, 2));
        [minimumRawDistance, matchedRawIndex] = min(rawDistances);
        matchDistanceM(labelIndexValue) = minimumRawDistance;
        if minimumRawDistance <= matchToleranceM
            labelMatched(labelIndexValue) = true;
            matchedRawPointIndexZeroBased(labelIndexValue) = ...
                matchedRawIndex - 1;
            exactSelected(labelIndexValue) = ...
                ismember(matchedRawIndex, rawCurbIndices);
        end
        if ~isempty(selectedPoints)
            selectedDistances = sqrt(sum( ...
                (selectedPoints - coordinate) .^ 2, 2));
            nearestSelectedDistanceM(labelIndexValue) = ...
                min(selectedDistances);
            nearbySelected(labelIndexValue) = ...
                nearestSelectedDistanceM(labelIndexValue) ...
                <= nearbyToleranceM;
        end
    end

    results = table( ...
        frameIndex, label, labelIndex, labelX, labelY, labelZ, ...
        matchedRawPointIndexZeroBased, matchDistanceM, labelMatched, ...
        exactSelected, nearbySelected, nearestSelectedDistanceM);
end


function summaryTable = localFrameLabelSummary(labelResultsTable)
    summaryTable = localEmptyFrameLabelSummaryTable();
    if isempty(labelResultsTable)
        return
    end
    frameIndices = unique(labelResultsTable.frameIndex, "stable");
    labelOrder = ["positive", "hard-negative"];
    for frameIndexValue = reshape(frameIndices, 1, [])
        for label = labelOrder
            selectedRows = ...
                labelResultsTable.frameIndex == frameIndexValue ...
                & labelResultsTable.label == label;
            if ~any(selectedRows)
                continue
            end
            frameLabels = labelResultsTable(selectedRows, :);
            labelCount = height(frameLabels);
            matchedRawCount = nnz(frameLabels.labelMatched);
            exactSelectedCount = nnz(frameLabels.exactSelected);
            nearbySelectedCount = nnz(frameLabels.nearbySelected);
            summaryTable(end + 1, :) = { ...
                frameIndexValue, label, labelCount, ...
                matchedRawCount, exactSelectedCount, ...
                nearbySelectedCount, ...
                exactSelectedCount / labelCount, ...
                nearbySelectedCount / labelCount}; %#ok<AGROW>
        end
    end
end


function results = localEmptyLabelResultsTable()
    results = table( ...
        Size=[0, 12], ...
        VariableTypes=[ ...
            "double", "string", repmat("double", 1, 6), ...
            repmat("logical", 1, 3), "double"], ...
        VariableNames=[ ...
            "frameIndex", "label", "labelIndex", ...
         "labelX", "labelY", "labelZ", ...
         "matchedRawPointIndexZeroBased", "matchDistanceM", ...
         "labelMatched", "exactSelected", "nearbySelected", ...
         "nearestSelectedDistanceM"]);
end


function summaryTable = localEmptyFrameLabelSummaryTable()
    summaryTable = table( ...
        Size=[0, 8], ...
        VariableTypes=[ ...
            "double", "string", repmat("double", 1, 6)], ...
        VariableNames= ...
        ["frameIndex", "label", "labelCount", "matchedRawCount", ...
         "exactSelectedCount", "nearbySelectedCount", ...
         "exactSelectedRate", "nearbySelectedRate"]);
end
