function summary = evaluateLidarRingCurbFeatures(datasetFolder, options)
%EVALUATELIDARRINGCURBFEATURES Evaluate ring features on development labels.
%   SUMMARY = EVALUATELIDARRINGCURBFEATURES() uses the repository-local
%   complete Town10HD_Opt outer-loop dataset.
%
%   SUMMARY = EVALUATELIDARRINGCURBFEATURES(DATASETFOLDER,
%   OutputDirectory=DIR, FrameIndices=INDICES) limits evaluation to the
%   selected zero-based frames and writes reproducible CSV and MAT products.
%
%   This evaluator consumes only exact coordinates declared by
%   curbRingFeatureDevelopmentLabels. It never reads curb-detector masks.
%   The labels are development regression anchors that have already informed
%   tuning and are not independent ground truth.

    arguments
        datasetFolder (1, 1) string = ""
        options.OutputDirectory (1, 1) string = ""
        options.FrameIndices (1, :) double ...
            {mustBeInteger, mustBeNonnegative} = []
        options.MatchToleranceM (1, 1) double ...
            {mustBePositive, mustBeFinite} = 1.0e-4
        options.SplitMode (1, 1) string ...
            {mustBeMember(options.SplitMode, ...
                ["leave-one-frame-out", "explicit"])} = ...
                "leave-one-frame-out"
        options.TestFrameIndices (1, :) double ...
            {mustBeInteger, mustBeNonnegative} = []
        options.FeatureConfig (1, 1) struct = struct()
        options.LocalContrastHalfWidthDegrees (1, 1) double ...
            {mustBePositive, mustBeFinite} = 12.0
        options.LocalContrastExclusionDegrees (1, 1) double ...
            {mustBeNonnegative, mustBeFinite} = 1.0
        options.LocalContrastMinimumBackgroundCount (1, 1) double ...
            {mustBeInteger, mustBePositive} = 20
    end
    if options.LocalContrastExclusionDegrees ...
            >= options.LocalContrastHalfWidthDegrees
        error( ...
            "evaluateLidarRingCurbFeatures:InvalidContrastWindow", ...
            "LocalContrastExclusionDegrees must be smaller than " + ...
            "LocalContrastHalfWidthDegrees.");
    end

    repositoryRoot = fileparts(fileparts(fileparts( ...
        mfilename("fullpath"))));
    if strlength(datasetFolder) == 0
        datasetFolder = fullfile( ...
            repositoryRoot, "simulation", "data", ...
            "carla_outer_loop_lap_10hz_20260802_epic_no_rt_auto");
    end
    if strlength(options.OutputDirectory) == 0
        options.OutputDirectory = fullfile( ...
            repositoryRoot, "simulation_output", ...
            "curb_ring_feature_development_evaluation");
    end

    catalog = curbRingFeatureDevelopmentLabels();
    localValidateDataset(datasetFolder, catalog);
    anchors = catalog.anchors;
    if ~isempty(options.FrameIndices)
        anchors = anchors(ismember( ...
            [anchors.frameIndex], options.FrameIndices));
    end

    if ~isfolder(options.OutputDirectory)
        mkdir(options.OutputDirectory);
    end

    inventoryTable = localInventoryTable(anchors);
    sampleTable = localEmptySampleTable();
    contrastTable = localEmptyContrastTable();
    fusionTable = localEmptyFusionTable();
    skippedTable = localEmptySkippedTable();

    featureFolder = fullfile( ...
        repositoryRoot, "perception", "curbDetectionExperiment");
    originalPath = path();
    pathCleanup = onCleanup(@() path(originalPath));
    addpath(featureFolder);

    for anchorIndex = 1:numel(anchors)
        anchor = anchors(anchorIndex);
        [coordinates, labelTypes, skippedTable] = ...
            localCoordinatePayload(anchor, skippedTable);
        if isempty(coordinates)
            continue;
        end

        framePath = fullfile( ...
            datasetFolder, "lidar", ...
            sprintf("%06d.npy", anchor.frameIndex));
        rawPoints = localLoadNpy(framePath);
        [organizedFrame, ~, rawToOrganized] = ...
            organizeLidarSweepGrid(rawPoints);
        [matchedLabels, skippedTable] = localMatchCoordinates( ...
            anchor.frameIndex, coordinates, labelTypes, rawPoints, ...
            rawToOrganized, options.MatchToleranceM, skippedTable);
        if isempty(matchedLabels.frameIndex)
            continue;
        end

        if exist("computeLidarRingCurbFeatures", "file") ~= 2
            error( ...
                "evaluateLidarRingCurbFeatures:MissingFeatureFunction", ...
                "computeLidarRingCurbFeatures.m is unavailable. " + ...
                "Add the feature implementation to the MATLAB path.");
        end
        [features, featureValidity] = computeLidarRingCurbFeatures( ...
            organizedFrame, options.FeatureConfig);
        frameTable = localFeatureTable( ...
            matchedLabels, features, featureValidity, ...
            size(organizedFrame.x));
        frameContrastTable = localFeatureContrastTable( ...
            matchedLabels, features, featureValidity, organizedFrame, ...
            options.LocalContrastHalfWidthDegrees, ...
            options.LocalContrastExclusionDegrees, ...
            options.LocalContrastMinimumBackgroundCount);
        frameFusionTable = localFusionLabelTable( ...
            matchedLabels, features, featureValidity);
        if isempty(sampleTable)
            sampleTable = frameTable;
        else
            if ~isequal(sampleTable.Properties.VariableNames, ...
                    frameTable.Properties.VariableNames)
                error( ...
                    "evaluateLidarRingCurbFeatures:FeatureSchemaChanged", ...
                    "The feature schema changed between evaluated frames.");
            end
            sampleTable = [sampleTable; frameTable]; %#ok<AGROW>
        end
        contrastTable = [contrastTable; frameContrastTable]; %#ok<AGROW>
        fusionTable = [fusionTable; frameFusionTable]; %#ok<AGROW>
    end
    clear pathCleanup;

    metricTable = localEvaluateSplits( ...
        sampleTable, options.SplitMode, options.TestFrameIndices);
    pooledMetricTable = localPooledFeatureMetrics(sampleTable);
    contrastSummaryTable = localSummarizeContrasts(contrastTable);
    fusionSummaryTable = localSummarizeFusion(fusionTable);
    publishedRuleTable = localPublishedRuleMetrics(sampleTable);
    if isempty(sampleTable)
        status = "no-coordinate-labels";
    elseif isempty(metricTable)
        status = "labels-loaded-no-valid-two-class-metric";
    else
        status = "completed-development-regression-evaluation";
    end

    outputFiles = struct( ...
        "inventoryCsv", fullfile( ...
            options.OutputDirectory, "development_label_inventory.csv"), ...
        "samplesCsv", fullfile( ...
            options.OutputDirectory, "matched_labeled_features.csv"), ...
        "metricsCsv", fullfile( ...
            options.OutputDirectory, "feature_metrics.csv"), ...
        "pooledMetricsCsv", fullfile( ...
            options.OutputDirectory, ...
            "feature_pooled_metrics.csv"), ...
        "localContrastsCsv", fullfile( ...
            options.OutputDirectory, "feature_local_contrasts.csv"), ...
        "localContrastSummaryCsv", fullfile( ...
            options.OutputDirectory, ...
            "feature_local_contrast_summary.csv"), ...
        "fusionPredictionsCsv", fullfile( ...
            options.OutputDirectory, ...
            "feature_family_fusion_predictions.csv"), ...
        "fusionSummaryCsv", fullfile( ...
            options.OutputDirectory, ...
            "feature_family_fusion_summary.csv"), ...
        "publishedRuleMetricsCsv", fullfile( ...
            options.OutputDirectory, ...
            "published_threshold_rule_metrics.csv"), ...
        "skippedCsv", fullfile( ...
            options.OutputDirectory, "skipped_labels.csv"), ...
        "summaryMat", fullfile( ...
            options.OutputDirectory, "evaluation_summary.mat"));

    writetable(inventoryTable, outputFiles.inventoryCsv);
    writetable(sampleTable, outputFiles.samplesCsv);
    writetable(metricTable, outputFiles.metricsCsv);
    writetable(pooledMetricTable, outputFiles.pooledMetricsCsv);
    writetable(contrastTable, outputFiles.localContrastsCsv);
    writetable( ...
        contrastSummaryTable, outputFiles.localContrastSummaryCsv);
    writetable(fusionTable, outputFiles.fusionPredictionsCsv);
    writetable(fusionSummaryTable, outputFiles.fusionSummaryCsv);
    writetable( ...
        publishedRuleTable, outputFiles.publishedRuleMetricsCsv);
    writetable(skippedTable, outputFiles.skippedCsv);

    summary = struct( ...
        "status", status, ...
        "datasetFolder", datasetFolder, ...
        "outputDirectory", options.OutputDirectory, ...
        "requestedFrameIndices", options.FrameIndices, ...
        "evaluatedFrameIndices", unique(sampleTable.frameIndex).', ...
        "matchedPositiveCount", nnz(sampleTable.label == "positive"), ...
        "matchedHardNegativeCount", ...
            nnz(sampleTable.label == "hard-negative"), ...
        "skippedRecordCount", height(skippedTable), ...
        "splitMode", options.SplitMode, ...
        "matchToleranceM", options.MatchToleranceM, ...
        "localContrastHalfWidthDegrees", ...
            options.LocalContrastHalfWidthDegrees, ...
        "localContrastExclusionDegrees", ...
            options.LocalContrastExclusionDegrees, ...
        "localContrastMinimumBackgroundCount", ...
            options.LocalContrastMinimumBackgroundCount, ...
        "validLocalContrastCount", height(contrastTable), ...
        "fusionAcceptedPositiveCount", nnz( ...
            fusionTable.label == "positive" & fusionTable.accepted), ...
        "fusionAcceptedHardNegativeCount", nnz( ...
            fusionTable.label == "hard-negative" ...
                & fusionTable.accepted), ...
        "independentGroundTruth", false, ...
        "detectorOutputsUsedAsLabels", false, ...
        "caveat", ...
            "These anchors have already informed tuning. Results are " + ...
            "development regression evidence, not held-out accuracy.", ...
        "outputFiles", outputFiles);
    save( ...
        outputFiles.summaryMat, "summary", "catalog", ...
        "inventoryTable", "sampleTable", "metricTable", ...
        "pooledMetricTable", ...
        "contrastTable", "contrastSummaryTable", ...
        "fusionTable", "fusionSummaryTable", ...
        "publishedRuleTable", "skippedTable");

    if status == "no-coordinate-labels"
        warning( ...
            "evaluateLidarRingCurbFeatures:NoCoordinateLabels", ...
            "No exact coordinate payload is available for the selected " + ...
            "development frames. Inventory and skip reports were written; " + ...
            "no detector output was substituted as truth.");
    end
end


function localValidateDataset(datasetFolder, catalog)
    if ~isfolder(datasetFolder)
        error( ...
            "evaluateLidarRingCurbFeatures:MissingDataset", ...
            "Dataset folder does not exist: %s", datasetFolder);
    end
    [~, datasetName] = fileparts(datasetFolder);
    if datasetName ~= catalog.datasetName
        error( ...
            "evaluateLidarRingCurbFeatures:DatasetMismatch", ...
            "The label catalog is for %s, not %s.", ...
            catalog.datasetName, datasetName);
    end
    if ~isfolder(fullfile(datasetFolder, "lidar"))
        error( ...
            "evaluateLidarRingCurbFeatures:MissingLidar", ...
            "Dataset does not contain a lidar folder: %s", ...
            datasetFolder);
    end
end


function inventoryTable = localInventoryTable(anchors)
    anchorCount = numel(anchors);
    frameIndex = zeros(anchorCount, 1);
    expectedPositiveCount = zeros(anchorCount, 1);
    expectedHardNegativeCount = nan(anchorCount, 1);
    admittedPositiveCount = zeros(anchorCount, 1);
    admittedHardNegativeCount = zeros(anchorCount, 1);
    positiveCoordinatesAvailable = false(anchorCount, 1);
    hardNegativeCoordinatesAvailable = false(anchorCount, 1);
    hardNegativeEvidenceDocumented = false(anchorCount, 1);
    sourceRecordIds = strings(anchorCount, 1);
    notes = strings(anchorCount, 1);
    for anchorIndex = 1:anchorCount
        anchor = anchors(anchorIndex);
        frameIndex(anchorIndex) = anchor.frameIndex;
        expectedPositiveCount(anchorIndex) = ...
            anchor.expectedPositiveCount;
        expectedHardNegativeCount(anchorIndex) = ...
            anchor.expectedHardNegativeCount;
        admittedPositiveCount(anchorIndex) = ...
            size(anchor.positiveCoordinatesM, 1);
        admittedHardNegativeCount(anchorIndex) = ...
            size(anchor.hardNegativeCoordinatesM, 1);
        positiveCoordinatesAvailable(anchorIndex) = ...
            anchor.positiveCoordinatesAvailable;
        hardNegativeCoordinatesAvailable(anchorIndex) = ...
            anchor.hardNegativeCoordinatesAvailable;
        hardNegativeEvidenceDocumented(anchorIndex) = ...
            anchor.hardNegativeEvidenceDocumented;
        sourceRecordIds(anchorIndex) = ...
            strjoin(anchor.sourceRecordIds, ";");
        notes(anchorIndex) = anchor.notes;
    end
    inventoryTable = table( ...
        frameIndex, expectedPositiveCount, expectedHardNegativeCount, ...
        admittedPositiveCount, admittedHardNegativeCount, ...
        positiveCoordinatesAvailable, ...
        hardNegativeCoordinatesAvailable, ...
        hardNegativeEvidenceDocumented, sourceRecordIds, notes);
end


function [coordinates, labelTypes, skippedTable] = ...
        localCoordinatePayload(anchor, skippedTable)
    localValidateCoordinates( ...
        anchor.positiveCoordinatesM, anchor.frameIndex, "positive");
    localValidateCoordinates( ...
        anchor.hardNegativeCoordinatesM, ...
        anchor.frameIndex, "hard-negative");
    coordinates = [ ...
        anchor.positiveCoordinatesM; ...
        anchor.hardNegativeCoordinatesM];
    labelTypes = [ ...
        repmat("positive", ...
            size(anchor.positiveCoordinatesM, 1), 1); ...
        repmat("hard-negative", ...
            size(anchor.hardNegativeCoordinatesM, 1), 1)];

    if isempty(anchor.positiveCoordinatesM)
        skippedTable = localAppendSkipped( ...
            skippedTable, anchor.frameIndex, "positive", NaN, ...
            "coordinate-payload-unavailable");
    end
    if anchor.hardNegativeEvidenceDocumented ...
            && isempty(anchor.hardNegativeCoordinatesM)
        skippedTable = localAppendSkipped( ...
            skippedTable, anchor.frameIndex, "hard-negative", NaN, ...
            "coordinate-payload-unavailable");
    end
end


function localValidateCoordinates(coordinates, frameIndex, labelType)
    if ~isnumeric(coordinates) || size(coordinates, 2) ~= 3 ...
            || any(~isfinite(coordinates), "all")
        error( ...
            "evaluateLidarRingCurbFeatures:InvalidCoordinates", ...
            "Frame %d %s coordinates must be a finite N-by-3 array.", ...
            frameIndex, labelType);
    end
end


function rawPoints = localLoadNpy(framePath)
    if ~isfile(framePath)
        error( ...
            "evaluateLidarRingCurbFeatures:MissingFrame", ...
            "LiDAR frame does not exist: %s", framePath);
    end
    try
        rawPoints = double(py.numpy.load(framePath));
    catch exception
        error( ...
            "evaluateLidarRingCurbFeatures:NpyLoadFailed", ...
            "Unable to load %s through NumPy: %s", ...
            framePath, exception.message);
    end
    if size(rawPoints, 2) < 3 ...
            || any(~isfinite(rawPoints(:, 1:3)), "all")
        error( ...
            "evaluateLidarRingCurbFeatures:InvalidFrame", ...
            "LiDAR frame must contain finite XYZ columns: %s", ...
            framePath);
    end
end


function [labels, skippedTable] = localMatchCoordinates( ...
        frameIndex, coordinates, labelTypes, rawPoints, ...
        rawToOrganized, toleranceM, skippedTable)
    labelCount = size(coordinates, 1);
    labels = struct( ...
        "frameIndex", zeros(0, 1), ...
        "label", strings(0, 1), ...
        "labelX", zeros(0, 1), ...
        "labelY", zeros(0, 1), ...
        "labelZ", zeros(0, 1), ...
        "matchedX", zeros(0, 1), ...
        "matchedY", zeros(0, 1), ...
        "matchedZ", zeros(0, 1), ...
        "rawPointIndexZeroBased", zeros(0, 1), ...
        "ringIndex", zeros(0, 1), ...
        "azimuthBinIndex", zeros(0, 1), ...
        "organizedLinearIndex", zeros(0, 1), ...
        "matchDistanceM", zeros(0, 1));
    matchedRawIndices = zeros(labelCount, 1);
    accepted = false(labelCount, 1);
    matchDistances = nan(labelCount, 1);

    for labelIndex = 1:labelCount
        displacement = rawPoints(:, 1:3) - coordinates(labelIndex, :);
        [minimumSquaredDistance, rawIndex] = min( ...
            sum(displacement.^2, 2));
        matchDistance = sqrt(minimumSquaredDistance);
        if matchDistance > toleranceM
            skippedTable = localAppendSkipped( ...
                skippedTable, frameIndex, labelTypes(labelIndex), ...
                labelIndex, "nearest-point-outside-tolerance");
        elseif rawToOrganized(rawIndex) == 0
            skippedTable = localAppendSkipped( ...
                skippedTable, frameIndex, labelTypes(labelIndex), ...
                labelIndex, "matched-point-not-retained-in-organized-grid");
        else
            duplicate = find( ...
                accepted & matchedRawIndices == rawIndex, 1);
            if isempty(duplicate)
                accepted(labelIndex) = true;
                matchedRawIndices(labelIndex) = rawIndex;
                matchDistances(labelIndex) = matchDistance;
            elseif labelTypes(duplicate) ~= labelTypes(labelIndex)
                error( ...
                    "evaluateLidarRingCurbFeatures:ConflictingLabel", ...
                    "Frame %d raw point %d has conflicting labels.", ...
                    frameIndex, rawIndex - 1);
            else
                skippedTable = localAppendSkipped( ...
                    skippedTable, frameIndex, labelTypes(labelIndex), ...
                    labelIndex, "duplicate-raw-point-label");
            end
        end
    end

    acceptedIndices = find(accepted);
    if isempty(acceptedIndices)
        return;
    end
    rawIndices = matchedRawIndices(acceptedIndices);
    organizedIndices = rawToOrganized(rawIndices);
    [ringIndices, azimuthBinIndices] = ind2sub( ...
        [64, 1000], organizedIndices);
    labels = struct( ...
        "frameIndex", repmat(frameIndex, numel(rawIndices), 1), ...
        "label", labelTypes(acceptedIndices), ...
        "labelX", coordinates(acceptedIndices, 1), ...
        "labelY", coordinates(acceptedIndices, 2), ...
        "labelZ", coordinates(acceptedIndices, 3), ...
        "matchedX", rawPoints(rawIndices, 1), ...
        "matchedY", rawPoints(rawIndices, 2), ...
        "matchedZ", rawPoints(rawIndices, 3), ...
        "rawPointIndexZeroBased", rawIndices - 1, ...
        "ringIndex", ringIndices, ...
        "azimuthBinIndex", azimuthBinIndices, ...
        "organizedLinearIndex", organizedIndices, ...
        "matchDistanceM", matchDistances(acceptedIndices));
end


function featureTable = localFeatureTable( ...
        labels, features, featureValidity, organizedSize)
    if ~isstruct(features) || ~isstruct(featureValidity)
        error( ...
            "evaluateLidarRingCurbFeatures:InvalidFeatureOutput", ...
            "Feature values and validity outputs must be structs.");
    end
    featureTable = struct2table(labels);
    featureFields = fieldnames(features);
    for fieldIndex = 1:numel(featureFields)
        fieldName = featureFields{fieldIndex};
        values = features.(fieldName);
        if isfield(featureValidity, fieldName)
            validity = featureValidity.(fieldName);
        else
            validity = isfinite(values);
        end
        if ~isnumeric(values) && ~islogical(values)
            continue;
        end
        if isequal(size(values), organizedSize)
            outputName = matlab.lang.makeValidName(fieldName);
            featureTable.(outputName) = localFeatureValues( ...
                values, validity, labels.organizedLinearIndex);
        elseif ndims(values) == 3 ...
                && size(values, 1) == organizedSize(1) ...
                && size(values, 2) == organizedSize(2)
            for scaleIndex = 1:size(values, 3)
                outputName = matlab.lang.makeValidName( ...
                    sprintf("%sScale%d", fieldName, scaleIndex));
                scaleValues = values(:, :, scaleIndex);
                if isequal(size(validity), size(values))
                    scaleValidity = validity(:, :, scaleIndex);
                else
                    scaleValidity = isfinite(scaleValues);
                end
                featureTable.(outputName) = localFeatureValues( ...
                    scaleValues, scaleValidity, ...
                    labels.organizedLinearIndex);
            end
        end
    end
end


function selectedValues = localFeatureValues( ...
        values, validity, organizedIndices)
    if ~isequal(size(values), size(validity))
        error( ...
            "evaluateLidarRingCurbFeatures:ValiditySizeMismatch", ...
            "A feature-validity array does not match its feature array.");
    end
    selectedValues = double(values(organizedIndices));
    selectedValidity = logical(validity(organizedIndices));
    selectedValues(~selectedValidity) = NaN;
end


function contrastTable = localFeatureContrastTable( ...
        labels, features, featureValidity, organizedFrame, ...
        halfWidthDegrees, exclusionDegrees, minimumBackgroundCount)
    contrastTable = localEmptyContrastTable();
    featureFields = fieldnames(features);
    measuredAzimuth = mod(atan2d( ...
        organizedFrame.y, organizedFrame.x), 360.0);
    for fieldIndex = 1:numel(featureFields)
        fieldName = featureFields{fieldIndex};
        values = features.(fieldName);
        if ~isnumeric(values) && ~islogical(values)
            continue;
        end
        if isfield(featureValidity, fieldName)
            validity = featureValidity.(fieldName);
        else
            validity = isfinite(values);
        end
        if ismatrix(values)
            contrastTable = [contrastTable; localScalarFeatureContrasts( ...
                labels, fieldName, values, validity, measuredAzimuth, ...
                halfWidthDegrees, exclusionDegrees, ...
                minimumBackgroundCount)]; %#ok<AGROW>
        elseif ndims(values) == 3 ...
                && size(values, 1) == size(organizedFrame.x, 1) ...
                && size(values, 2) == size(organizedFrame.x, 2)
            for scaleIndex = 1:size(values, 3)
                scaleName = matlab.lang.makeValidName( ...
                    sprintf("%sScale%d", fieldName, scaleIndex));
                if isequal(size(validity), size(values))
                    scaleValidity = validity(:, :, scaleIndex);
                else
                    scaleValidity = isfinite(values(:, :, scaleIndex));
                end
                contrastTable = [ ...
                    contrastTable; localScalarFeatureContrasts( ...
                        labels, scaleName, values(:, :, scaleIndex), ...
                        scaleValidity, measuredAzimuth, ...
                        halfWidthDegrees, exclusionDegrees, ...
                        minimumBackgroundCount)]; %#ok<AGROW>
            end
        end
    end
end


function fusionTable = localFusionLabelTable( ...
        labels, features, featureValidity)
    fusionTable = localEmptyFusionTable();
    [acceptedMask, diagnostics] = fuseLidarRingCurbFeatures( ...
        features, featureValidity);
    indices = labels.organizedLinearIndex;
    fusionTable = table( ...
        labels.frameIndex, labels.label, ...
        labels.rawPointIndexZeroBased, ...
        diagnostics.compressionEvidence(indices), ...
        diagnostics.verticalEvidence(indices), ...
        diagnostics.radialEvidence(indices), ...
        diagnostics.shapeEvidence(indices), ...
        diagnostics.familyVoteCount(indices), ...
        diagnostics.availableFamilyCount(indices), ...
        acceptedMask(indices), ...
        VariableNames=fusionTable.Properties.VariableNames);
end


function contrastTable = localScalarFeatureContrasts( ...
        labels, featureName, values, validity, measuredAzimuth, ...
        halfWidthDegrees, exclusionDegrees, minimumBackgroundCount)
    contrastTable = localEmptyContrastTable();
    if ~isequal(size(values), size(validity)) ...
            || ~isequal(size(values), size(measuredAzimuth))
        error( ...
            "evaluateLidarRingCurbFeatures:ContrastSizeMismatch", ...
            "Feature, validity, and azimuth arrays must have equal size.");
    end
    for labelIndex = 1:numel(labels.frameIndex)
        ringIndex = labels.ringIndex(labelIndex);
        targetLinearIndex = labels.organizedLinearIndex(labelIndex);
        targetValue = double(values(targetLinearIndex));
        if ~validity(targetLinearIndex) || ~isfinite(targetValue)
            continue;
        end
        targetAzimuth = measuredAzimuth(targetLinearIndex);
        angularDistance = abs(localWrapTo180( ...
            measuredAzimuth(ringIndex, :) - targetAzimuth));
        backgroundMask = ...
            validity(ringIndex, :) ...
            & isfinite(values(ringIndex, :)) ...
            & angularDistance >= exclusionDegrees ...
            & angularDistance <= halfWidthDegrees;
        backgroundValues = double(values(ringIndex, backgroundMask));
        if numel(backgroundValues) < minimumBackgroundCount
            continue;
        end
        backgroundMedian = median(backgroundValues);
        backgroundMad = median(abs( ...
            backgroundValues - backgroundMedian));
        robustScale = max( ...
            1.4826 * backgroundMad, ...
            eps(max(1.0, abs(backgroundMedian))));
        robustZ = (targetValue - backgroundMedian) / robustScale;
        percentileHigh = ( ...
            nnz(backgroundValues < targetValue) ...
            + 0.5 * nnz(backgroundValues == targetValue)) ...
            / numel(backgroundValues);
        newRow = table( ...
            labels.frameIndex(labelIndex), ...
            labels.label(labelIndex), ...
            labels.rawPointIndexZeroBased(labelIndex), ...
            string(featureName), targetValue, ...
            numel(backgroundValues), backgroundMedian, ...
            backgroundMad, robustZ, percentileHigh, ...
            VariableNames= ...
                contrastTable.Properties.VariableNames);
        contrastTable = [contrastTable; newRow]; %#ok<AGROW>
    end
end


function summaryTable = localSummarizeContrasts(contrastTable)
    summaryTable = localEmptyContrastSummaryTable();
    if isempty(contrastTable)
        return;
    end
    groupKeys = unique( ...
        contrastTable(:, ["featureName", "label"]), "rows", "stable");
    for groupIndex = 1:height(groupKeys)
        groupMask = ...
            contrastTable.featureName ...
                == groupKeys.featureName(groupIndex) ...
            & contrastTable.label == groupKeys.label(groupIndex);
        percentile = contrastTable.percentileHigh(groupMask);
        robustZ = contrastTable.robustZ(groupMask);
        newRow = table( ...
            groupKeys.featureName(groupIndex), ...
            groupKeys.label(groupIndex), ...
            nnz(groupMask), ...
            median(percentile), ...
            mean(percentile >= 0.80), ...
            mean(percentile <= 0.20), ...
            median(robustZ), ...
            VariableNames=summaryTable.Properties.VariableNames);
        summaryTable = [summaryTable; newRow]; %#ok<AGROW>
    end
end


function summaryTable = localSummarizeFusion(fusionTable)
    summaryTable = localEmptyFusionSummaryTable();
    if isempty(fusionTable)
        return;
    end
    frameValues = [-1; unique(fusionTable.frameIndex, "stable")];
    labels = ["positive"; "hard-negative"];
    for frameIndex = frameValues.'
        for label = labels.'
            groupMask = fusionTable.label == label;
            if frameIndex >= 0
                groupMask = groupMask ...
                    & fusionTable.frameIndex == frameIndex;
            end
            if ~any(groupMask)
                continue;
            end
            acceptedCount = nnz(fusionTable.accepted(groupMask));
            sampleCount = nnz(groupMask);
            newRow = table( ...
                frameIndex, label, sampleCount, acceptedCount, ...
                acceptedCount / sampleCount, ...
                mean(double( ...
                    fusionTable.familyVoteCount(groupMask))), ...
                mean(double( ...
                    fusionTable.availableFamilyCount(groupMask))), ...
                VariableNames=summaryTable.Properties.VariableNames);
            summaryTable = [summaryTable; newRow]; %#ok<AGROW>
        end
    end
end


function ruleTable = localPublishedRuleMetrics(sampleTable)
    ruleTable = localEmptyPublishedRuleTable();
    if isempty(sampleTable)
        return;
    end
    smoothArcLength = max( ...
        [sampleTable.leftSmoothArcLength, ...
         sampleTable.rightSmoothArcLength], [], 2, "omitmissing");
    chenSmoothnessRule = ...
        sampleTable.chenSmoothness > 0.005;
    chenHeightRangeRule = ...
        sampleTable.localHeightRange >= 0.05 ...
        & sampleTable.localHeightRange <= 0.30;
    chenSmoothArcRule = smoothArcLength > 0.60;
    hataFlatSpacingRatio = ...
        1.0 - sampleTable.hataCompressionNormalized;
    horizontalRangeM = hypot( ...
        sampleTable.matchedX, sampleTable.matchedY);
    huangRadiusRatioRule = ...
        sampleTable.huangRadiusRatioDeviation >= 0.05 ...
        & sampleTable.huangRadiusRatioDeviation <= 0.10 ...
        & horizontalRangeM <= 50.0;
    rules = { ...
        "Chen smoothness T0", chenSmoothnessRule, ...
            "Chen et al. T0=0.005"; ...
        "Chen height range", chenHeightRangeRule, ...
            "Chen et al. T2=0.05 m and T3=0.30 m"; ...
        "Chen smooth arc", chenSmoothArcRule, ...
            "Chen et al. at least one side above T1=0.60 m"; ...
        "Chen strict conjunction", ...
            chenSmoothnessRule ...
                & chenHeightRangeRule & chenSmoothArcRule, ...
            "Original three-condition conjunction"; ...
        "Huang tangential angle", ...
            sampleTable.huangTangentialStrength > 0.60, ...
            "Huang et al. cosine above 0.6; original scan-index " + ...
                "scope is not transferred to the reconstructed grid"; ...
        "Huang RadiusRatio interval", ...
            huangRadiusRatioRule, ...
            "Huang et al. |ratio-1| in [0.05,0.10] at <=50 m"; ...
        "Huang HDInRadius", ...
            sampleTable.huangHdInRadius > 0.05, ...
            "Huang et al. three-adjacent-beam residual above 0.05 m"; ...
        "Hata normalized interval", ...
            hataFlatSpacingRatio >= 0.113 ...
                & hataFlatSpacingRatio < 1.375, ...
            "Hata et al. alpha=0.113 and beta=1.375; " + ...
                "compression filter only"; ...
        "Hata differential stencil", ...
            sampleTable.hataDifferentialHeightResponse > 0.124, ...
            "Hata et al. absolute [-2,0,+2] height response " + ...
                "above 0.124 m"};
    labels = ["positive"; "hard-negative"];
    for ruleIndex = 1:size(rules, 1)
        ruleMask = logical(rules{ruleIndex, 2});
        ruleMask(~isfinite(double(ruleMask))) = false;
        for label = labels.'
            labelMask = sampleTable.label == label;
            sampleCount = nnz(labelMask);
            acceptedCount = nnz(ruleMask & labelMask);
            newRow = table( ...
                string(rules{ruleIndex, 1}), label, ...
                sampleCount, acceptedCount, ...
                acceptedCount / sampleCount, ...
                string(rules{ruleIndex, 3}), ...
                VariableNames=ruleTable.Properties.VariableNames);
            ruleTable = [ruleTable; newRow]; %#ok<AGROW>
        end
    end
end


function angle = localWrapTo180(angle)
    angle = mod(angle + 180.0, 360.0) - 180.0;
end


function metricTable = localEvaluateSplits( ...
        sampleTable, splitMode, explicitTestFrames)
    metricTable = localEmptyMetricTable();
    if isempty(sampleTable)
        return;
    end
    baseVariables = [ ...
        "frameIndex", "label", ...
        "labelX", "labelY", "labelZ", ...
        "matchedX", "matchedY", "matchedZ", ...
        "rawPointIndexZeroBased", ...
        "ringIndex", "azimuthBinIndex", ...
        "organizedLinearIndex", "matchDistanceM"];
    featureNames = setdiff( ...
        string(sampleTable.Properties.VariableNames), ...
        baseVariables, "stable");
    if isempty(featureNames)
        return;
    end

    frameIndices = unique(sampleTable.frameIndex).';
    splits = localBuildSplits( ...
        frameIndices, splitMode, explicitTestFrames);
    rowCount = numel(splits)*numel(featureNames);
    rows = repmat(localMetricRow(), rowCount, 1);
    rowIndex = 0;
    for splitIndex = 1:numel(splits)
        split = splits(splitIndex);
        trainingRows = ismember( ...
            sampleTable.frameIndex, split.trainingFrames);
        testRows = ismember( ...
            sampleTable.frameIndex, split.testFrames);
        for featureIndex = 1:numel(featureNames)
            rowIndex = rowIndex + 1;
            featureName = featureNames(featureIndex);
            trainingValues = sampleTable.(featureName)(trainingRows);
            trainingLabels = sampleTable.label(trainingRows);
            testValues = sampleTable.(featureName)(testRows);
            testLabels = sampleTable.label(testRows);
            [trainingAuc, trainingDelta, trainingPositiveCount, ...
                trainingNegativeCount] = localSeparation( ...
                    trainingValues, trainingLabels);
            [testAuc, testDelta, testPositiveCount, ...
                testNegativeCount] = localSeparation( ...
                    testValues, testLabels);

            direction = 1;
            if isfinite(trainingAuc) && trainingAuc < 0.5
                direction = -1;
            end
            rows(rowIndex) = struct( ...
                "foldIndex", splitIndex, ...
                "splitMode", splitMode, ...
                "featureName", featureName, ...
                "trainingFrames", ...
                    localFrameList(split.trainingFrames), ...
                "testFrames", localFrameList(split.testFrames), ...
                "positiveHighDirection", direction, ...
                "trainingPositiveCount", trainingPositiveCount, ...
                "trainingHardNegativeCount", trainingNegativeCount, ...
                "testPositiveCount", testPositiveCount, ...
                "testHardNegativeCount", testNegativeCount, ...
                "trainingAucRaw", trainingAuc, ...
                "trainingAucOriented", ...
                    localOrientAuc(trainingAuc, direction), ...
                "testAucRaw", testAuc, ...
                "testAucOriented", ...
                    localOrientAuc(testAuc, direction), ...
                "trainingCliffDeltaRaw", trainingDelta, ...
                "trainingCliffDeltaOriented", ...
                    direction*trainingDelta, ...
                "testCliffDeltaRaw", testDelta, ...
                "testCliffDeltaOriented", direction*testDelta);
        end
    end
    metricTable = struct2table(rows);
end


function metricTable = localPooledFeatureMetrics(sampleTable)
    metricTable = localEmptyPooledMetricTable();
    if isempty(sampleTable)
        return;
    end
    baseVariables = [ ...
        "frameIndex", "label", ...
        "labelX", "labelY", "labelZ", ...
        "matchedX", "matchedY", "matchedZ", ...
        "rawPointIndexZeroBased", ...
        "ringIndex", "azimuthBinIndex", ...
        "organizedLinearIndex", "matchDistanceM"];
    featureNames = setdiff( ...
        string(sampleTable.Properties.VariableNames), ...
        baseVariables, "stable");
    for featureName = featureNames
        positiveValues = double(sampleTable.(featureName)( ...
            sampleTable.label == "positive"));
        hardNegativeValues = double(sampleTable.(featureName)( ...
            sampleTable.label == "hard-negative"));
        positiveValues = positiveValues(isfinite(positiveValues));
        hardNegativeValues = ...
            hardNegativeValues(isfinite(hardNegativeValues));
        if isempty(positiveValues) || isempty(hardNegativeValues)
            continue;
        end
        rawAuc = localTieAwareAuc( ...
            positiveValues, hardNegativeValues);
        positiveHighDirection = 1;
        if rawAuc < 0.5
            positiveHighDirection = -1;
        end
        orientedPositive = ...
            positiveHighDirection * positiveValues;
        orientedHardNegative = ...
            positiveHighDirection * hardNegativeValues;
        hardNegativeTailThreshold = quantile( ...
            orientedHardNegative, 0.95);
        positiveTailActivation = mean( ...
            orientedPositive >= hardNegativeTailThreshold);
        hardNegativeTailActivation = mean( ...
            orientedHardNegative >= hardNegativeTailThreshold);
        orientedAuc = localOrientAuc( ...
            rawAuc, positiveHighDirection);
        newRow = table( ...
            featureName, positiveHighDirection, ...
            numel(positiveValues), numel(hardNegativeValues), ...
            rawAuc, orientedAuc, 2.0 * orientedAuc - 1.0, ...
            median(positiveValues), median(hardNegativeValues), ...
            hardNegativeTailThreshold, ...
            positiveTailActivation, ...
            hardNegativeTailActivation, ...
            VariableNames=metricTable.Properties.VariableNames);
        metricTable = [metricTable; newRow]; %#ok<AGROW>
    end
    if ~isempty(metricTable)
        metricTable = sortrows( ...
            metricTable, "pooledAucOriented", "descend");
    end
end


function splits = localBuildSplits( ...
        frameIndices, splitMode, explicitTestFrames)
    if splitMode == "leave-one-frame-out"
        splitCount = numel(frameIndices);
        splits = repmat(struct( ...
            "trainingFrames", [], "testFrames", []), ...
            splitCount, 1);
        for splitIndex = 1:splitCount
            splits(splitIndex).testFrames = frameIndices(splitIndex);
            splits(splitIndex).trainingFrames = ...
                frameIndices(frameIndices ~= frameIndices(splitIndex));
        end
    else
        if isempty(explicitTestFrames)
            error( ...
                "evaluateLidarRingCurbFeatures:MissingTestFrames", ...
                "TestFrameIndices is required for SplitMode=""explicit"".");
        end
        testFrames = intersect( ...
            frameIndices, explicitTestFrames, "stable");
        if isempty(testFrames)
            error( ...
                "evaluateLidarRingCurbFeatures:NoTestLabels", ...
                "No labeled frame belongs to TestFrameIndices.");
        end
        splits = struct( ...
            "trainingFrames", ...
                setdiff(frameIndices, testFrames, "stable"), ...
            "testFrames", testFrames);
    end
end


function [auc, cliffDelta, positiveCount, negativeCount] = ...
        localSeparation(values, labels)
    finiteRows = isfinite(values);
    positiveValues = values( ...
        finiteRows & labels == "positive");
    negativeValues = values( ...
        finiteRows & labels == "hard-negative");
    positiveCount = numel(positiveValues);
    negativeCount = numel(negativeValues);
    if positiveCount == 0 || negativeCount == 0
        auc = NaN;
        cliffDelta = NaN;
        return;
    end
    auc = localTieAwareAuc(positiveValues, negativeValues);
    cliffDelta = 2*auc - 1;
end


function auc = localTieAwareAuc(positiveValues, negativeValues)
    combinedValues = [positiveValues(:); negativeValues(:)];
    positiveCount = numel(positiveValues);
    negativeCount = numel(negativeValues);
    isPositive = [ ...
        true(positiveCount, 1); false(negativeCount, 1)];
    [sortedValues, order] = sort(combinedValues);
    sortedPositive = isPositive(order);
    ranks = zeros(size(sortedValues));
    groupStart = 1;
    while groupStart <= numel(sortedValues)
        groupEnd = groupStart;
        while groupEnd < numel(sortedValues) ...
                && sortedValues(groupEnd + 1) ...
                == sortedValues(groupStart)
            groupEnd = groupEnd + 1;
        end
        ranks(groupStart:groupEnd) = ...
            0.5*(groupStart + groupEnd);
        groupStart = groupEnd + 1;
    end
    positiveRankSum = sum(ranks(sortedPositive));
    auc = (positiveRankSum ...
        - positiveCount*(positiveCount + 1)/2) ...
        / (positiveCount*negativeCount);
end


function orientedAuc = localOrientAuc(rawAuc, direction)
    if ~isfinite(rawAuc)
        orientedAuc = NaN;
    elseif direction > 0
        orientedAuc = rawAuc;
    else
        orientedAuc = 1 - rawAuc;
    end
end


function frameList = localFrameList(frameIndices)
    if isempty(frameIndices)
        frameList = "";
    else
        frameList = strjoin(string(frameIndices), ";");
    end
end


function skippedTable = localAppendSkipped( ...
        skippedTable, frameIndex, label, labelIndex, reason)
    newRow = table( ...
        double(frameIndex), string(label), double(labelIndex), ...
        string(reason), ...
        VariableNames=skippedTable.Properties.VariableNames);
    skippedTable = [skippedTable; newRow];
end


function sampleTable = localEmptySampleTable()
    sampleTable = table( ...
        Size=[0, 13], ...
        VariableTypes=[ ...
            "double", "string", ...
            repmat("double", 1, 11)], ...
        VariableNames=[ ...
            "frameIndex", "label", ...
            "labelX", "labelY", "labelZ", ...
            "matchedX", "matchedY", "matchedZ", ...
            "rawPointIndexZeroBased", ...
            "ringIndex", "azimuthBinIndex", ...
            "organizedLinearIndex", "matchDistanceM"]);
end


function skippedTable = localEmptySkippedTable()
    skippedTable = table( ...
        Size=[0, 4], ...
        VariableTypes= ...
            ["double", "string", "double", "string"], ...
        VariableNames= ...
            ["frameIndex", "label", "labelIndex", "reason"]);
end


function contrastTable = localEmptyContrastTable()
    contrastTable = table( ...
        Size=[0, 10], ...
        VariableTypes=[ ...
            "double", "string", "double", "string", ...
            repmat("double", 1, 6)], ...
        VariableNames=[ ...
            "frameIndex", "label", "rawPointIndexZeroBased", ...
            "featureName", "featureValue", "backgroundCount", ...
            "backgroundMedian", "backgroundMad", ...
            "robustZ", "percentileHigh"]);
end


function fusionTable = localEmptyFusionTable()
    fusionTable = table( ...
        Size=[0, 10], ...
        VariableTypes=[ ...
            "double", "string", "double", ...
            repmat("logical", 1, 4), ...
            "uint8", "uint8", "logical"], ...
        VariableNames=[ ...
            "frameIndex", "label", "rawPointIndexZeroBased", ...
            "compressionEvidence", "verticalEvidence", ...
            "radialEvidence", "shapeEvidence", ...
            "familyVoteCount", "availableFamilyCount", "accepted"]);
end


function summaryTable = localEmptyContrastSummaryTable()
    summaryTable = table( ...
        Size=[0, 7], ...
        VariableTypes=[ ...
            "string", "string", repmat("double", 1, 5)], ...
        VariableNames=[ ...
            "featureName", "label", "validContrastCount", ...
            "medianPercentileHigh", "upperTailFraction", ...
            "lowerTailFraction", "medianRobustZ"]);
end


function summaryTable = localEmptyFusionSummaryTable()
    summaryTable = table( ...
        Size=[0, 7], ...
        VariableTypes=[ ...
            "double", "string", repmat("double", 1, 5)], ...
        VariableNames=[ ...
            "frameIndex", "label", "sampleCount", ...
            "acceptedCount", "acceptanceRate", ...
            "meanFamilyVoteCount", "meanAvailableFamilyCount"]);
end


function metricTable = localEmptyPooledMetricTable()
    metricTable = table( ...
        Size=[0, 12], ...
        VariableTypes=[ ...
            "string", repmat("double", 1, 11)], ...
        VariableNames=[ ...
            "featureName", "positiveHighDirection", ...
            "positiveValidCount", "hardNegativeValidCount", ...
            "pooledAucRaw", "pooledAucOriented", ...
            "cliffDeltaOriented", "positiveMedian", ...
            "hardNegativeMedian", ...
            "hardNegativeOrientedQ95Threshold", ...
            "positiveActivationAtHardNegativeQ95", ...
            "hardNegativeActivationAtQ95"]);
end


function ruleTable = localEmptyPublishedRuleTable()
    ruleTable = table( ...
        Size=[0, 6], ...
        VariableTypes=[ ...
            "string", "string", repmat("double", 1, 3), "string"], ...
        VariableNames=[ ...
            "ruleName", "label", "sampleCount", ...
            "acceptedCount", "acceptanceRate", "sourceThreshold"]);
end


function metricTable = localEmptyMetricTable()
    metricTable = struct2table(repmat(localMetricRow(), 0, 1));
end


function row = localMetricRow()
    row = struct( ...
        "foldIndex", 0, ...
        "splitMode", "", ...
        "featureName", "", ...
        "trainingFrames", "", ...
        "testFrames", "", ...
        "positiveHighDirection", 1, ...
        "trainingPositiveCount", 0, ...
        "trainingHardNegativeCount", 0, ...
        "testPositiveCount", 0, ...
        "testHardNegativeCount", 0, ...
        "trainingAucRaw", NaN, ...
        "trainingAucOriented", NaN, ...
        "testAucRaw", NaN, ...
        "testAucOriented", NaN, ...
        "trainingCliffDeltaRaw", NaN, ...
        "trainingCliffDeltaOriented", NaN, ...
        "testCliffDeltaRaw", NaN, ...
        "testCliffDeltaOriented", NaN);
end
