function summary = evaluateCurbRingFeatureBackgroundCalibration( ...
        datasetFolder, options)
%EVALUATECURBRINGFEATUREBACKGROUNDCALIBRATION Calibrate ring evidence.
%   SUMMARY = EVALUATECURBRINGFEATUREBACKGROUNDCALIBRATION() evaluates the
%   sixteen ring-local curb features and their four physical feature
%   families on the nine user-reviewed development frames.
%
%   The evaluator reports three distinct comparison populations:
%       positive         exact user-reviewed curb points
%       local-background valid cells on the same ring, 1.08 to 11.88
%                        degrees away from a positive
%       global-background all valid, non-annotated cells outside a
%                         1.08-degree same-ring exclusion around positives
%
%   A fourth, explicitly labelled hard-negative population is retained
%   separately. Global-background activation is an upper bound rather than
%   a false-positive rate because most global cells have not been manually
%   labelled and can contain real curb or other geometric discontinuities.
%
%   Candidate rules are side agnostic and frame agnostic. Each feature is
%   normalized by an explicit research baseline that is independent of the
%   production fusion thresholds. The twelve earlier baselines are the
%   pre-production development values. The four extended-feature baselines
%   equal their hard-negative 95th percentiles divided by 1.25, so the
%   common-1.25 rule evaluates those hard-negative percentiles directly.
%   Each family score is the maximum normalized member score, and optional
%   local saliency requires the family score to be above a same-ring local
%   percentile. The script does not modify the production detector or
%   feature-fusion implementation.

    arguments
        datasetFolder (1, 1) string = ""
        options.OutputDirectory (1, 1) string = ""
        options.FrameIndices (1, :) double ...
            {mustBeInteger, mustBeNonnegative} = []
        options.MatchToleranceM (1, 1) double ...
            {mustBePositive, mustBeFinite} = 1.0e-4
        options.LocalHalfWidthBins (1, 1) double ...
            {mustBeInteger, mustBePositive} = 33
        options.LocalExclusionBins (1, 1) double ...
            {mustBeInteger, mustBeNonnegative} = 3
        options.MinimumLocalCount (1, 1) double ...
            {mustBeInteger, mustBePositive} = 12
        options.CommonFamilyMultipliers (1, :) double ...
            {mustBePositive, mustBeFinite} = ...
                [1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 4.0]
        options.LocalPercentiles (1, :) double ...
            {mustBeGreaterThanOrEqual(options.LocalPercentiles, 0), ...
             mustBeLessThan(options.LocalPercentiles, 1)} = ...
                [0.0, 0.50, 0.60, 0.70, 0.75, 0.80, ...
                 0.85, 0.90, 0.95]
        options.MinimumFamilyVotes (1, :) double ...
            {mustBeInteger, mustBeGreaterThanOrEqual( ...
                options.MinimumFamilyVotes, 1), ...
             mustBeLessThanOrEqual( ...
                options.MinimumFamilyVotes, 4)} = [2, 3]
        options.MinimumSalientFamilyVotes (1, :) double ...
            {mustBeInteger, mustBeGreaterThanOrEqual( ...
                options.MinimumSalientFamilyVotes, 1), ...
             mustBeLessThanOrEqual( ...
                options.MinimumSalientFamilyVotes, 4)} = [1, 2]
        options.MinimumPositiveRecall (1, 1) double ...
            {mustBeGreaterThanOrEqual( ...
                options.MinimumPositiveRecall, 0), ...
             mustBeLessThanOrEqual( ...
                options.MinimumPositiveRecall, 1)} = 0.80
        options.MinimumFrameRecall (1, 1) double ...
            {mustBeGreaterThanOrEqual( ...
                options.MinimumFrameRecall, 0), ...
             mustBeLessThanOrEqual( ...
                options.MinimumFrameRecall, 1)} = 0.60
    end

    if options.LocalExclusionBins >= options.LocalHalfWidthBins
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "InvalidLocalWindow", ...
            "LocalExclusionBins must be smaller than " + ...
            "LocalHalfWidthBins.");
    end

    repositoryRoot = fileparts(fileparts(fileparts( ...
        mfilename("fullpath"))));
    if strlength(datasetFolder) == 0
        datasetFolder = fullfile( ...
            repositoryRoot, "simulation", "data", ...
            "carla_outer_loop_lap_10hz_20260802_epic_no_rt_auto");
    end
    if strlength(options.OutputDirectory) == 0
        options.OutputDirectory = fullfile( ...
            repositoryRoot, "simulation_output", ...
            "curb_ring_feature_extended_background_calibration");
    end
    if ~isfolder(datasetFolder)
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "MissingDataset", ...
            "Dataset folder does not exist: %s", datasetFolder);
    end
    if ~isfolder(options.OutputDirectory)
        mkdir(options.OutputDirectory);
    end

    catalog = curbRingFeatureDevelopmentLabels();
    anchors = catalog.anchors;
    if ~isempty(options.FrameIndices)
        anchors = anchors(ismember( ...
            [anchors.frameIndex], options.FrameIndices));
    end
    if isempty(anchors)
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "NoFrames", ...
            "No labelled development frame matches FrameIndices.");
    end

    featureFolder = fullfile( ...
        repositoryRoot, "perception", "curbDetectionExperiment");
    originalPath = path();
    pathCleanup = onCleanup(@() path(originalPath));
    addpath(featureFolder);

    frameCount = numel(anchors);
    featureCount = 16;
    familyCount = 4;
    positiveFeatureCells = cell(frameCount, featureCount);
    localFeatureCells = cell(frameCount, featureCount);
    globalFeatureCells = cell(frameCount, featureCount);
    hardNegativeFeatureCells = cell(frameCount, featureCount);
    positiveNormalizedCells = cell(frameCount, 1);
    positiveFeatureRankCells = cell(frameCount, 1);
    localNormalizedCells = cell(frameCount, 1);
    localFeatureRankCells = cell(frameCount, 1);
    globalNormalizedCells = cell(frameCount, 1);
    globalFeatureRankCells = cell(frameCount, 1);
    hardNegativeNormalizedCells = cell(frameCount, 1);
    hardNegativeFeatureRankCells = cell(frameCount, 1);
    positiveScoreCells = cell(frameCount, 1);
    positiveFamilyRankCells = cell(frameCount, 1);
    localScoreCells = cell(frameCount, 1);
    localFamilyRankCells = cell(frameCount, 1);
    globalScoreCells = cell(frameCount, 1);
    globalFamilyRankCells = cell(frameCount, 1);
    hardNegativeScoreCells = cell(frameCount, 1);
    hardNegativeFamilyRankCells = cell(frameCount, 1);
    positiveFrameCells = cell(frameCount, 1);
    frameSummaryRows = cell(frameCount, 1);
    featureNames = strings(1, featureCount);
    featureFamilies = strings(1, featureCount);
    defaultThresholds = nan(1, featureCount);
    familyNames = ["compression", "vertical", "radial", "shape"];

    for anchorIndex = 1:frameCount
        anchor = anchors(anchorIndex);
        framePath = fullfile( ...
            datasetFolder, "lidar", ...
            sprintf("%06d.npy", anchor.frameIndex));
        rawPoints = localLoadNpy(framePath);
        [organizedFrame, ~, rawToOrganized] = ...
            organizeLidarSweepGrid(rawPoints);
        positiveIndices = localMatchIndices( ...
            anchor.positiveCoordinatesM, rawPoints, rawToOrganized, ...
            options.MatchToleranceM, anchor.frameIndex, "positive");
        hardNegativeIndices = localMatchIndices( ...
            anchor.hardNegativeCoordinatesM, rawPoints, rawToOrganized, ...
            options.MatchToleranceM, anchor.frameIndex, "hard-negative");

        [features, validity] = computeLidarRingCurbFeatures( ...
            organizedFrame);
        [featureValues, featureValid, names, families, thresholds] = ...
            localFeatureArrays(features, validity);
        if anchorIndex == 1
            featureNames = names;
            featureFamilies = families;
            defaultThresholds = thresholds;
        elseif ~isequal(featureNames, names) ...
                || ~isequal(featureFamilies, families) ...
                || any(defaultThresholds ~= thresholds)
            error( ...
                "evaluateCurbRingFeatureBackgroundCalibration:" + ...
                "FeatureSchemaChanged", ...
                "Feature schema or default thresholds changed by frame.");
        end

        [familyScores, familyAvailable] = localFamilyScores( ...
            featureValues, featureValid, featureFamilies, ...
            defaultThresholds, familyNames);
        [normalizedFeatures, normalizedAvailable] = ...
            localNormalizedFeatures( ...
                featureValues, featureValid, defaultThresholds);
        normalizedFeatureRanks = nan( ...
            size(normalizedFeatures), "single");
        for featureIndex = 1:featureCount
            normalizedFeatureRanks(:, :, featureIndex) = ...
                localCircularPercentile( ...
                    normalizedFeatures(:, :, featureIndex), ...
                    normalizedAvailable(:, :, featureIndex), ...
                    options.LocalHalfWidthBins, ...
                    options.LocalExclusionBins, ...
                    options.MinimumLocalCount);
        end
        familyRanks = nan(size(familyScores), "single");
        for familyIndex = 1:familyCount
            familyRanks(:, :, familyIndex) = ...
                localCircularPercentile( ...
                    familyScores(:, :, familyIndex), ...
                    familyAvailable(:, :, familyIndex), ...
                    options.LocalHalfWidthBins, ...
                    options.LocalExclusionBins, ...
                    options.MinimumLocalCount);
        end
        baseValid = validity.base;
        positiveExclusion = localPositiveExclusionMask( ...
            positiveIndices, size(baseValid), ...
            options.LocalExclusionBins);
        localBackground = localPositiveNeighborhoodMask( ...
            positiveIndices, size(baseValid), ...
            options.LocalExclusionBins, ...
            options.LocalHalfWidthBins) & baseValid;
        localBackground(positiveExclusion) = false;
        globalBackground = baseValid & ~positiveExclusion;

        for featureIndex = 1:featureCount
            values = featureValues{featureIndex};
            valid = featureValid{featureIndex} & isfinite(values);
            positiveFeatureCells{anchorIndex, featureIndex} = ...
                localSelectValues(values, valid, positiveIndices);
            localFeatureCells{anchorIndex, featureIndex} = ...
                double(values(localBackground & valid));
            globalFeatureCells{anchorIndex, featureIndex} = ...
                double(values(globalBackground & valid));
            hardNegativeFeatureCells{anchorIndex, featureIndex} = ...
                localSelectValues(values, valid, hardNegativeIndices);
        end

        positiveScoreCells{anchorIndex} = ...
            localSelectRows(familyScores, positiveIndices);
        positiveFamilyRankCells{anchorIndex} = ...
            localSelectRows(familyRanks, positiveIndices);
        localScoreCells{anchorIndex} = ...
            localSelectRows(familyScores, find(localBackground));
        localFamilyRankCells{anchorIndex} = ...
            localSelectRows(familyRanks, find(localBackground));
        globalScoreCells{anchorIndex} = ...
            localSelectRows(familyScores, find(globalBackground));
        globalFamilyRankCells{anchorIndex} = ...
            localSelectRows(familyRanks, find(globalBackground));
        hardNegativeScoreCells{anchorIndex} = ...
            localSelectRows(familyScores, hardNegativeIndices);
        hardNegativeFamilyRankCells{anchorIndex} = ...
            localSelectRows(familyRanks, hardNegativeIndices);
        positiveNormalizedCells{anchorIndex} = ...
            localSelectRows(normalizedFeatures, positiveIndices);
        positiveFeatureRankCells{anchorIndex} = ...
            localSelectRows(normalizedFeatureRanks, positiveIndices);
        localNormalizedCells{anchorIndex} = ...
            localSelectRows(normalizedFeatures, find(localBackground));
        localFeatureRankCells{anchorIndex} = ...
            localSelectRows( ...
                normalizedFeatureRanks, find(localBackground));
        globalNormalizedCells{anchorIndex} = ...
            localSelectRows(normalizedFeatures, find(globalBackground));
        globalFeatureRankCells{anchorIndex} = ...
            localSelectRows( ...
                normalizedFeatureRanks, find(globalBackground));
        hardNegativeNormalizedCells{anchorIndex} = ...
            localSelectRows(normalizedFeatures, hardNegativeIndices);
        hardNegativeFeatureRankCells{anchorIndex} = ...
            localSelectRows( ...
                normalizedFeatureRanks, hardNegativeIndices);
        positiveFrameCells{anchorIndex} = repmat( ...
            anchor.frameIndex, numel(positiveIndices), 1);

        defaultAccepted = localApplyRule( ...
            localSelectRows(familyScores, find(baseValid)), ...
            localSelectRows(familyScores, find(baseValid)), ...
            ones(1, familyCount), 0.0, 2);
        frameSummaryRows{anchorIndex} = table( ...
            anchor.frameIndex, nnz(baseValid), ...
            numel(positiveIndices), numel(hardNegativeIndices), ...
            nnz(localBackground), nnz(globalBackground), ...
            nnz(defaultAccepted), mean(defaultAccepted), ...
            VariableNames=[ ...
                "frameIndex", "baseValidCount", "positiveCount", ...
                "hardNegativeCount", "localBackgroundCount", ...
                "globalBackgroundCount", ...
                "defaultAcceptedCellCount", ...
                "defaultAcceptedCellRate"]);
    end
    clear pathCleanup;

    positiveFeatureValues = localConcatenateFeatureCells( ...
        positiveFeatureCells);
    localFeatureValues = localConcatenateFeatureCells( ...
        localFeatureCells);
    globalFeatureValues = localConcatenateFeatureCells( ...
        globalFeatureCells);
    hardNegativeFeatureValues = localConcatenateFeatureCells( ...
        hardNegativeFeatureCells);
    positiveScores = vertcat(positiveScoreCells{:});
    positiveFamilyRanks = vertcat(positiveFamilyRankCells{:});
    localScores = vertcat(localScoreCells{:});
    localFamilyRanks = vertcat(localFamilyRankCells{:});
    globalScores = vertcat(globalScoreCells{:});
    globalFamilyRanks = vertcat(globalFamilyRankCells{:});
    hardNegativeScores = vertcat(hardNegativeScoreCells{:});
    hardNegativeFamilyRanks = ...
        vertcat(hardNegativeFamilyRankCells{:});
    positiveNormalized = vertcat(positiveNormalizedCells{:});
    positiveFeatureRanks = vertcat(positiveFeatureRankCells{:});
    localNormalized = vertcat(localNormalizedCells{:});
    localFeatureRanks = vertcat(localFeatureRankCells{:});
    globalNormalized = vertcat(globalNormalizedCells{:});
    globalFeatureRanks = vertcat(globalFeatureRankCells{:});
    hardNegativeNormalized = ...
        vertcat(hardNegativeNormalizedCells{:});
    hardNegativeFeatureRanks = ...
        vertcat(hardNegativeFeatureRankCells{:});
    positiveFrames = vertcat(positiveFrameCells{:});
    frameSummaryTable = vertcat(frameSummaryRows{:});

    featureMetricTable = localFeatureMetrics( ...
        featureNames, featureFamilies, defaultThresholds, ...
        positiveFeatureValues, localFeatureValues, ...
        globalFeatureValues, hardNegativeFeatureValues);
    familyMetricTable = localFamilyMetrics( ...
        familyNames, positiveScores, localScores, globalScores, ...
        hardNegativeScores);

    backgroundFamilyQuantiles = localFamilyQuantiles( ...
        globalScores, [0.90, 0.95, 0.975, 0.99]);
    [ruleGridTable, frameRuleTable] = localEvaluateRuleGrid( ...
        positiveNormalized, positiveFeatureRanks, positiveFrames, ...
        localNormalized, localFeatureRanks, ...
        globalNormalized, globalFeatureRanks, ...
        hardNegativeNormalized, hardNegativeFeatureRanks, ...
        positiveScores, positiveFamilyRanks, ...
        localScores, localFamilyRanks, ...
        globalScores, globalFamilyRanks, ...
        hardNegativeScores, hardNegativeFamilyRanks, ...
        featureFamilies, familyNames, ...
        options.CommonFamilyMultipliers, ...
        backgroundFamilyQuantiles, ...
        options.LocalPercentiles, options.MinimumFamilyVotes, ...
        options.MinimumSalientFamilyVotes);
    [recommendedRuleTable, paretoTable] = localRecommendRules( ...
        ruleGridTable, options.MinimumPositiveRecall, ...
        options.MinimumFrameRecall);
    extendedFeatureAblationTable = localExtendedFeatureAblation( ...
        positiveNormalized, positiveFeatureRanks, positiveFrames, ...
        localNormalized, localFeatureRanks, ...
        globalNormalized, globalFeatureRanks, ...
        hardNegativeNormalized, hardNegativeFeatureRanks, ...
        featureNames, featureFamilies, familyNames);

    outputFiles = struct( ...
        "featureMetricsCsv", fullfile( ...
            options.OutputDirectory, ...
            "feature_background_metrics.csv"), ...
        "familyMetricsCsv", fullfile( ...
            options.OutputDirectory, ...
            "family_background_metrics.csv"), ...
        "frameSummaryCsv", fullfile( ...
            options.OutputDirectory, ...
            "frame_background_activation.csv"), ...
        "ruleGridCsv", fullfile( ...
            options.OutputDirectory, ...
            "fusion_rule_grid.csv"), ...
        "frameRuleMetricsCsv", fullfile( ...
            options.OutputDirectory, ...
            "fusion_rule_frame_metrics.csv"), ...
        "recommendedRuleCsv", fullfile( ...
            options.OutputDirectory, ...
            "recommended_fusion_rule.csv"), ...
        "paretoRulesCsv", fullfile( ...
            options.OutputDirectory, ...
            "pareto_fusion_rules.csv"), ...
        "extendedFeatureAblationCsv", fullfile( ...
            options.OutputDirectory, ...
            "extended_feature_ablation.csv"), ...
        "summaryMat", fullfile( ...
            options.OutputDirectory, ...
            "background_calibration_summary.mat"));
    writetable(featureMetricTable, outputFiles.featureMetricsCsv);
    writetable(familyMetricTable, outputFiles.familyMetricsCsv);
    writetable(frameSummaryTable, outputFiles.frameSummaryCsv);
    writetable(ruleGridTable, outputFiles.ruleGridCsv);
    writetable(frameRuleTable, outputFiles.frameRuleMetricsCsv);
    writetable(recommendedRuleTable, outputFiles.recommendedRuleCsv);
    writetable(paretoTable, outputFiles.paretoRulesCsv);
    writetable( ...
        extendedFeatureAblationTable, ...
        outputFiles.extendedFeatureAblationCsv);

    summary = struct( ...
        "status", "completed-development-background-calibration", ...
        "datasetFolder", datasetFolder, ...
        "outputDirectory", options.OutputDirectory, ...
        "frameIndices", [anchors.frameIndex], ...
        "positiveCount", size(positiveScores, 1), ...
        "hardNegativeCount", size(hardNegativeScores, 1), ...
        "localBackgroundCount", size(localScores, 1), ...
        "globalBackgroundCount", size(globalScores, 1), ...
        "azimuthBinDegrees", 0.36, ...
        "localHalfWidthDegrees", ...
            options.LocalHalfWidthBins*0.36, ...
        "localExclusionDegrees", ...
            options.LocalExclusionBins*0.36, ...
        "minimumLocalCount", options.MinimumLocalCount, ...
        "minimumPositiveRecall", options.MinimumPositiveRecall, ...
        "minimumFrameRecall", options.MinimumFrameRecall, ...
        "featureCount", featureCount, ...
        "featureNames", featureNames, ...
        "researchBaselineThresholds", defaultThresholds, ...
        "thresholdBaselineSource", ...
            "The first twelve values are fixed pre-production " + ...
            "development baselines; the four extended values are " + ...
            "hard-negative q95 divided by 1.25.", ...
        "ablationRule", ...
            "common-1.25, member-feature saliency 0.60, " + ...
            "minimum 3 absolute families and 2 salient families", ...
        "recommendedRule", recommendedRuleTable, ...
        "globalBackgroundCaveat", ...
            "Unannotated global cells can contain true curb or other " + ...
            "legitimate discontinuities; activation is not an FPR.", ...
        "sideSpecificLogicUsed", false, ...
        "frameSpecificLogicUsed", false, ...
        "outputFiles", outputFiles);
    save( ...
        outputFiles.summaryMat, "summary", "featureMetricTable", ...
        "familyMetricTable", "frameSummaryTable", "ruleGridTable", ...
        "frameRuleTable", "recommendedRuleTable", "paretoTable", ...
        "extendedFeatureAblationTable", ...
        "backgroundFamilyQuantiles");
end


function rawPoints = localLoadNpy(framePath)
    if ~isfile(framePath)
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "MissingFrame", ...
            "LiDAR frame does not exist: %s", framePath);
    end
    try
        rawPoints = double(py.numpy.load(framePath));
    catch exception
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "NpyLoadFailed", ...
            "Unable to load %s through NumPy: %s", ...
            framePath, exception.message);
    end
    if size(rawPoints, 2) < 3 ...
            || any(~isfinite(rawPoints(:, 1:3)), "all")
        error( ...
            "evaluateCurbRingFeatureBackgroundCalibration:" + ...
            "InvalidFrame", ...
            "LiDAR frame must contain finite XYZ columns: %s", ...
            framePath);
    end
end


function organizedIndices = localMatchIndices( ...
        coordinates, rawPoints, rawToOrganized, toleranceM, ...
        frameIndex, labelName)
    organizedIndices = zeros(size(coordinates, 1), 1);
    for coordinateIndex = 1:size(coordinates, 1)
        displacement = rawPoints(:, 1:3) ...
            - coordinates(coordinateIndex, :);
        [minimumSquaredDistance, rawIndex] = min( ...
            sum(displacement.^2, 2));
        distanceM = sqrt(minimumSquaredDistance);
        if distanceM > toleranceM
            error( ...
                "evaluateCurbRingFeatureBackgroundCalibration:" + ...
                "LabelOutsideTolerance", ...
                "Frame %d %s coordinate %d is %.6g m from its " + ...
                "nearest point.", ...
                frameIndex, labelName, coordinateIndex, distanceM);
        end
        if rawToOrganized(rawIndex) == 0
            error( ...
                "evaluateCurbRingFeatureBackgroundCalibration:" + ...
                "LabelNotOrganized", ...
                "Frame %d %s coordinate %d was not retained in the " + ...
                "organized grid.", ...
                frameIndex, labelName, coordinateIndex);
        end
        organizedIndices(coordinateIndex) = ...
            rawToOrganized(rawIndex);
    end
    organizedIndices = unique(organizedIndices, "stable");
end


function [values, valid, names, families, thresholds] = ...
        localFeatureArrays(features, validity)
    values = { ...
        features.hataCompressionNormalized, ...
        features.heightStep, ...
        features.localHeightRange, ...
        features.localMultiscaleHaarZ(:, :, 1), ...
        features.wangHorizontalSpacingExcess, ...
        features.radiusRatioReconstructionDeviation, ...
        features.radialSecondDifference, ...
        features.localMultiscaleHaarRange(:, :, 1), ...
        features.huangTangentialStrength, ...
        features.sameRingSlopeChange, ...
        features.ilpLineFitResidual, ...
        features.ilpLineSlopeMagnitude, ...
        features.huangRadiusRatioDeviation, ...
        features.huangHdInRadius, ...
        features.sameRingSlopeMagnitude, ...
        features.hataDifferentialHeightResponse};
    valid = { ...
        validity.hataCompressionNormalized, ...
        validity.heightStep, ...
        validity.localHeightRange, ...
        validity.localMultiscaleHaarZ(:, :, 1), ...
        validity.wangHorizontalSpacingExcess, ...
        validity.radiusRatioReconstructionDeviation, ...
        validity.radialSecondDifference, ...
        validity.localMultiscaleHaarRange(:, :, 1), ...
        validity.huangTangentialStrength, ...
        validity.sameRingSlopeChange, ...
        validity.ilpLineFitResidual, ...
        validity.ilpLineSlopeMagnitude, ...
        validity.huangRadiusRatioDeviation, ...
        validity.huangHdInRadius, ...
        validity.sameRingSlopeMagnitude, ...
        validity.hataDifferentialHeightResponse};
    names = [ ...
        "hataCompressionNormalized", ...
        "heightStep", ...
        "localHeightRange", ...
        "localMultiscaleHaarZ", ...
        "wangHorizontalSpacingExcess", ...
        "radiusRatioReconstructionDeviation", ...
        "radialSecondDifference", ...
        "localMultiscaleHaarRange", ...
        "huangTangentialStrength", ...
        "sameRingSlopeChange", ...
        "ilpLineFitResidual", ...
        "ilpLineSlopeMagnitude", ...
        "huangRadiusRatioDeviation", ...
        "huangHdInRadius", ...
        "sameRingSlopeMagnitude", ...
        "hataDifferentialHeightResponse"];
    families = [ ...
        "compression", ...
        "vertical", "vertical", "vertical", ...
        "radial", "radial", "radial", "radial", ...
        "shape", "shape", "shape", "shape", ...
        "radial", "vertical", "shape", "vertical"];
    thresholds = [ ...
        0.2, 0.004, 0.015, 0.009, ...
        0.0045, 8.0e-5, 0.0075, 0.036, ...
        0.09, 0.0028, 0.0026, 0.02, ...
        0.00163314, 0.0159446, 0.0143248, 0.0142488];
end


function [scores, available] = localFamilyScores( ...
        values, valid, featureFamilies, thresholds, familyNames)
    gridSize = size(values{1});
    scores = nan([gridSize, numel(familyNames)]);
    available = false([gridSize, numel(familyNames)]);
    for familyIndex = 1:numel(familyNames)
        familyScore = nan(gridSize);
        familyAvailable = false(gridSize);
        memberIndices = find( ...
            featureFamilies == familyNames(familyIndex));
        for memberIndex = memberIndices
            memberValid = valid{memberIndex} ...
                & isfinite(values{memberIndex});
            normalizedValue = double(values{memberIndex}) ...
                / thresholds(memberIndex);
            firstEvidence = memberValid & ~familyAvailable;
            familyScore(firstEvidence) = ...
                normalizedValue(firstEvidence);
            sharedEvidence = memberValid & familyAvailable;
            familyScore(sharedEvidence) = max( ...
                familyScore(sharedEvidence), ...
                normalizedValue(sharedEvidence));
            familyAvailable = familyAvailable | memberValid;
        end
        familyScore(~familyAvailable) = NaN;
        scores(:, :, familyIndex) = familyScore;
        available(:, :, familyIndex) = familyAvailable;
    end
end


function [normalized, available] = localNormalizedFeatures( ...
        values, valid, thresholds)
    gridSize = size(values{1});
    featureCount = numel(values);
    normalized = nan([gridSize, featureCount]);
    available = false([gridSize, featureCount]);
    for featureIndex = 1:featureCount
        featureAvailable = valid{featureIndex} ...
            & isfinite(values{featureIndex});
        featureNormalized = double(values{featureIndex}) ...
            / thresholds(featureIndex);
        featureNormalized(~featureAvailable) = NaN;
        normalized(:, :, featureIndex) = featureNormalized;
        available(:, :, featureIndex) = featureAvailable;
    end
end


function [percentile, neighborCount] = localCircularPercentile( ...
        values, valid, halfWidthBins, exclusionBins, minimumCount)
    lowerCount = zeros(size(values), "uint16");
    equalCount = zeros(size(values), "uint16");
    neighborCount = zeros(size(values), "uint16");
    offsets = [ ...
        -halfWidthBins:-exclusionBins, ...
        exclusionBins:halfWidthBins];
    offsets(offsets == 0) = [];
    for offset = offsets
        neighborValue = circshift(values, [0, offset]);
        neighborValid = circshift(valid, [0, offset]) ...
            & isfinite(neighborValue);
        neighborCount = neighborCount + uint16(neighborValid);
        lowerCount = lowerCount + uint16( ...
            neighborValid & neighborValue < values);
        equalCount = equalCount + uint16( ...
            neighborValid & neighborValue == values);
    end
    percentile = ( ...
        single(lowerCount) + 0.5*single(equalCount)) ...
        ./ max(single(neighborCount), 1.0);
    percentile(~valid | neighborCount < minimumCount) = NaN;
end


function mask = localPositiveExclusionMask( ...
        indices, gridSize, exclusionBins)
    mask = false(gridSize);
    if isempty(indices)
        return;
    end
    [ringIndices, columnIndices] = ind2sub(gridSize, indices);
    offsets = -exclusionBins:exclusionBins;
    for index = 1:numel(indices)
        columns = mod( ...
            columnIndices(index) - 1 + offsets, gridSize(2)) + 1;
        mask(ringIndices(index), columns) = true;
    end
end


function mask = localPositiveNeighborhoodMask( ...
        indices, gridSize, exclusionBins, halfWidthBins)
    mask = false(gridSize);
    if isempty(indices)
        return;
    end
    [ringIndices, columnIndices] = ind2sub(gridSize, indices);
    offsets = [ ...
        -halfWidthBins:-exclusionBins, ...
        exclusionBins:halfWidthBins];
    offsets(offsets == 0) = [];
    for index = 1:numel(indices)
        columns = mod( ...
            columnIndices(index) - 1 + offsets, gridSize(2)) + 1;
        mask(ringIndices(index), columns) = true;
    end
end


function values = localSelectValues(array, valid, indices)
    if isempty(indices)
        values = zeros(0, 1);
        return;
    end
    values = double(array(indices));
    values(~valid(indices)) = NaN;
end


function rows = localSelectRows(array, indices)
    familyCount = size(array, 3);
    if isempty(indices)
        rows = nan(0, familyCount);
        return;
    end
    rows = nan(numel(indices), familyCount);
    for familyIndex = 1:familyCount
        familyArray = array(:, :, familyIndex);
        rows(:, familyIndex) = double(familyArray(indices));
    end
end


function output = localConcatenateFeatureCells(input)
    featureCount = size(input, 2);
    output = cell(1, featureCount);
    for featureIndex = 1:featureCount
        output{featureIndex} = vertcat(input{:, featureIndex});
    end
end


function metrics = localFeatureMetrics( ...
        names, families, thresholds, positiveValues, localValues, ...
        globalValues, hardNegativeValues)
    featureCount = numel(names);
    rows = cell(featureCount, 1);
    for featureIndex = 1:featureCount
        positive = localFinite(positiveValues{featureIndex});
        localBackground = localFinite(localValues{featureIndex});
        globalBackground = localFinite(globalValues{featureIndex});
        hardNegative = localFinite(hardNegativeValues{featureIndex});
        defaultThreshold = thresholds(featureIndex);
        common1p25Threshold = 1.25*defaultThreshold;
        globalQ95Threshold = max( ...
            defaultThreshold, ...
            localEmpiricalQuantile(globalBackground, 0.95));
        globalQ99Threshold = max( ...
            defaultThreshold, ...
            localEmpiricalQuantile(globalBackground, 0.99));
        rows{featureIndex} = table( ...
            names(featureIndex), families(featureIndex), ...
            defaultThreshold, ...
            numel(positive), localRate( ...
                positive >= defaultThreshold), ...
            numel(localBackground), localRate( ...
                localBackground >= defaultThreshold), ...
            numel(globalBackground), localRate( ...
                globalBackground >= defaultThreshold), ...
            numel(hardNegative), localRate( ...
                hardNegative >= defaultThreshold), ...
            common1p25Threshold, ...
            localRate(positive >= common1p25Threshold), ...
            localRate(localBackground >= common1p25Threshold), ...
            localRate(globalBackground >= common1p25Threshold), ...
            localRate(hardNegative >= common1p25Threshold), ...
            localAuc(positive, localBackground), ...
            localAuc(positive, globalBackground), ...
            localAuc(positive, hardNegative), ...
            globalQ95Threshold, localRate( ...
                positive >= globalQ95Threshold), ...
            localRate(localBackground >= globalQ95Threshold), ...
            localRate(globalBackground >= globalQ95Threshold), ...
            globalQ99Threshold, localRate( ...
                positive >= globalQ99Threshold), ...
            localRate(localBackground >= globalQ99Threshold), ...
            localRate(globalBackground >= globalQ99Threshold), ...
            VariableNames=[ ...
                "featureName", "family", "defaultThreshold", ...
                "positiveValidCount", "positiveDefaultActivation", ...
                "localBackgroundValidCount", ...
                "localBackgroundDefaultActivation", ...
                "globalBackgroundValidCount", ...
                "globalBackgroundDefaultActivation", ...
                "hardNegativeValidCount", ...
                "hardNegativeDefaultActivation", ...
                "common1p25Threshold", ...
                "positiveCommon1p25Activation", ...
                "localBackgroundCommon1p25Activation", ...
                "globalBackgroundCommon1p25Activation", ...
                "hardNegativeCommon1p25Activation", ...
                "positiveVsLocalBackgroundAuc", ...
                "positiveVsGlobalBackgroundAuc", ...
                "positiveVsHardNegativeAuc", ...
                "globalQ95Threshold", "positiveQ95Activation", ...
                "localBackgroundQ95Activation", ...
                "globalBackgroundQ95Activation", ...
                "globalQ99Threshold", "positiveQ99Activation", ...
                "localBackgroundQ99Activation", ...
                "globalBackgroundQ99Activation"]);
    end
    metrics = vertcat(rows{:});
end


function metrics = localFamilyMetrics( ...
        names, positiveScores, localScores, globalScores, ...
        hardNegativeScores)
    familyCount = numel(names);
    rows = cell(familyCount, 1);
    for familyIndex = 1:familyCount
        positive = localFinite(positiveScores(:, familyIndex));
        localBackground = localFinite(localScores(:, familyIndex));
        globalBackground = localFinite(globalScores(:, familyIndex));
        hardNegative = localFinite( ...
            hardNegativeScores(:, familyIndex));
        globalQ95Multiplier = max( ...
            1.0, localEmpiricalQuantile(globalBackground, 0.95));
        globalQ99Multiplier = max( ...
            1.0, localEmpiricalQuantile(globalBackground, 0.99));
        rows{familyIndex} = table( ...
            names(familyIndex), ...
            numel(positive), localRate(positive >= 1.0), ...
            numel(localBackground), ...
            localRate(localBackground >= 1.0), ...
            numel(globalBackground), ...
            localRate(globalBackground >= 1.0), ...
            numel(hardNegative), localRate(hardNegative >= 1.0), ...
            globalQ95Multiplier, ...
            localRate(positive >= globalQ95Multiplier), ...
            localRate(globalBackground >= globalQ95Multiplier), ...
            globalQ99Multiplier, ...
            localRate(positive >= globalQ99Multiplier), ...
            localRate(globalBackground >= globalQ99Multiplier), ...
            VariableNames=[ ...
                "family", "positiveValidCount", ...
                "positiveDefaultActivation", ...
                "localBackgroundValidCount", ...
                "localBackgroundDefaultActivation", ...
                "globalBackgroundValidCount", ...
                "globalBackgroundDefaultActivation", ...
                "hardNegativeValidCount", ...
                "hardNegativeDefaultActivation", ...
                "globalQ95Multiplier", "positiveQ95Activation", ...
                "globalBackgroundQ95Activation", ...
                "globalQ99Multiplier", "positiveQ99Activation", ...
                "globalBackgroundQ99Activation"]);
    end
    metrics = vertcat(rows{:});
end


function quantiles = localFamilyQuantiles(scores, probabilities)
    familyCount = size(scores, 2);
    quantiles = nan(numel(probabilities), familyCount);
    for probabilityIndex = 1:numel(probabilities)
        for familyIndex = 1:familyCount
            values = localFinite(scores(:, familyIndex));
            quantiles(probabilityIndex, familyIndex) = max( ...
                1.0, localEmpiricalQuantile( ...
                    values, probabilities(probabilityIndex)));
        end
    end
end


function [gridTable, frameTable] = localEvaluateRuleGrid( ...
        positiveFeatures, positiveRanks, positiveFrames, ...
        localFeatures, localRanks, globalFeatures, globalRanks, ...
        hardNegativeFeatures, hardNegativeRanks, ...
        positiveFamilyScores, positiveFamilyRanks, ...
        localFamilyScores, localFamilyRanks, ...
        globalFamilyScores, globalFamilyRanks, ...
        hardNegativeFamilyScores, hardNegativeFamilyRanks, ...
        featureFamilies, familyNames, ...
        commonMultipliers, backgroundQuantiles, ...
        localPercentiles, minimumVotes, minimumSalientVotes)
    familyCount = numel(familyNames);
    commonCount = numel(commonMultipliers);
    quantileCount = size(backgroundQuantiles, 1);
    thresholdCount = commonCount + quantileCount;
    thresholdModes = strings(thresholdCount, 1);
    multiplierRows = zeros(thresholdCount, familyCount);
    for multiplierIndex = 1:commonCount
        multiplier = commonMultipliers(multiplierIndex);
        thresholdModes(multiplierIndex) = ...
            "common-" + string(multiplier);
        multiplierRows(multiplierIndex, :) = ...
            repmat(multiplier, 1, familyCount);
    end
    quantileNames = ["global-q90", "global-q95", ...
        "global-q97_5", "global-q99"];
    for quantileIndex = 1:quantileCount
        outputIndex = commonCount + quantileIndex;
        thresholdModes(outputIndex) = quantileNames(quantileIndex);
        multiplierRows(outputIndex, :) = ...
            backgroundQuantiles(quantileIndex, :);
    end

    formationNames = [ ...
        "any-member", "vertical-pair", "radial-pair", ...
        "shape-pair", "vertical-radial-pairs", ...
        "all-multimember-pairs"];
    noSaliencyFormationCount = numel(formationNames);
    saliencyStrategyCount = numel(formationNames) + 1;
    saliencyCombinationCount = noSaliencyFormationCount ...
        + nnz(localPercentiles > 0)*numel(minimumSalientVotes) ...
            * saliencyStrategyCount;
    ruleCount = size(multiplierRows, 1) ...
        * saliencyCombinationCount*numel(minimumVotes);
    rows = cell(ruleCount, 1);
    frameRows = cell(ruleCount, 1);
    ruleIndex = 0;
    for thresholdIndex = 1:size(multiplierRows, 1)
        thresholds = multiplierRows(thresholdIndex, :);
        for localPercentile = localPercentiles
            if localPercentile > 0
                salientVoteCandidates = minimumSalientVotes;
                saliencyBases = [ ...
                    repmat("member-feature", ...
                        1, numel(formationNames)), ...
                    "family-maximum"];
                familyFormations = [formationNames, "any-member"];
            else
                salientVoteCandidates = 0;
                saliencyBases = repmat( ...
                    "none", 1, numel(formationNames));
                familyFormations = formationNames;
            end
            for voteCount = minimumVotes
                for salientVoteCount = salientVoteCandidates
                    for strategyIndex = 1:numel(saliencyBases)
                        saliencyBasis = saliencyBases(strategyIndex);
                        familyFormation = ...
                            familyFormations(strategyIndex);
                        minimumMemberCounts = ...
                            localFormationMemberCounts( ...
                                familyFormation);
                        ruleIndex = ruleIndex + 1;
                        if saliencyBasis == "family-maximum"
                            positiveAccepted = localApplyFamilyRule( ...
                                positiveFamilyScores, ...
                                positiveFamilyRanks, thresholds, ...
                                localPercentile, voteCount, ...
                                salientVoteCount);
                            localAccepted = localApplyFamilyRule( ...
                                localFamilyScores, localFamilyRanks, ...
                                thresholds, localPercentile, ...
                                voteCount, salientVoteCount);
                            globalAccepted = localApplyFamilyRule( ...
                                globalFamilyScores, ...
                                globalFamilyRanks, thresholds, ...
                                localPercentile, voteCount, ...
                                salientVoteCount);
                            hardNegativeAccepted = ...
                                localApplyFamilyRule( ...
                                    hardNegativeFamilyScores, ...
                                    hardNegativeFamilyRanks, ...
                                    thresholds, localPercentile, ...
                                    voteCount, salientVoteCount);
                        else
                            positiveAccepted = ...
                                localApplyFeatureRule( ...
                                    positiveFeatures, ...
                                    positiveRanks, featureFamilies, ...
                                    familyNames, thresholds, ...
                                    localPercentile, voteCount, ...
                                    salientVoteCount, ...
                                    minimumMemberCounts);
                            localAccepted = ...
                                localApplyFeatureRule( ...
                                    localFeatures, localRanks, ...
                                    featureFamilies, familyNames, ...
                                    thresholds, localPercentile, ...
                                    voteCount, salientVoteCount, ...
                                    minimumMemberCounts);
                            globalAccepted = ...
                                localApplyFeatureRule( ...
                                    globalFeatures, globalRanks, ...
                                    featureFamilies, familyNames, ...
                                    thresholds, localPercentile, ...
                                    voteCount, salientVoteCount, ...
                                    minimumMemberCounts);
                            hardNegativeAccepted = ...
                                localApplyFeatureRule( ...
                                    hardNegativeFeatures, ...
                                    hardNegativeRanks, ...
                                    featureFamilies, familyNames, ...
                                    thresholds, localPercentile, ...
                                    voteCount, salientVoteCount, ...
                                    minimumMemberCounts);
                        end
                        [minimumFrameRecall, medianFrameRecall, ...
                            currentFrameTable] = localFrameRecall( ...
                                positiveFrames, positiveAccepted, ...
                                ruleIndex);
                        frameRows{ruleIndex} = currentFrameTable;
                        rows{ruleIndex} = table( ...
                            ruleIndex, ...
                            thresholdModes(thresholdIndex), ...
                            saliencyBasis, familyFormation, ...
                            thresholds(1), thresholds(2), ...
                            thresholds(3), thresholds(4), ...
                            localPercentile, voteCount, ...
                            salientVoteCount, ...
                            nnz(positiveAccepted), ...
                            localRate(positiveAccepted), ...
                            minimumFrameRecall, ...
                            medianFrameRecall, ...
                            nnz(localAccepted), ...
                            localRate(localAccepted), ...
                            nnz(globalAccepted), ...
                            localRate(globalAccepted), ...
                            nnz(hardNegativeAccepted), ...
                            localRate(hardNegativeAccepted), ...
                            VariableNames=[ ...
                                "ruleIndex", "thresholdMode", ...
                                "saliencyBasis", "familyFormation", ...
                                "compressionMultiplier", ...
                                "verticalMultiplier", ...
                                "radialMultiplier", ...
                                "shapeMultiplier", ...
                                "localPercentile", ...
                                "minimumFamilyVotes", ...
                                "minimumSalientFamilyVotes", ...
                                "positiveAcceptedCount", ...
                                "positiveRecall", ...
                                "minimumFrameRecall", ...
                                "medianFrameRecall", ...
                                "localBackgroundAcceptedCount", ...
                                "localBackgroundActivation", ...
                                "globalBackgroundAcceptedCount", ...
                                "globalBackgroundActivation", ...
                                "hardNegativeAcceptedCount", ...
                                "hardNegativeActivation"]);
                    end
                end
            end
        end
    end
    gridTable = vertcat(rows{:});
    frameTable = vertcat(frameRows{:});
end


function counts = localFormationMemberCounts(formation)
    switch formation
        case "any-member"
            counts = [1, 1, 1, 1];
        case "vertical-pair"
            counts = [1, 2, 1, 1];
        case "radial-pair"
            counts = [1, 1, 2, 1];
        case "shape-pair"
            counts = [1, 1, 1, 2];
        case "vertical-radial-pairs"
            counts = [1, 2, 2, 1];
        case "all-multimember-pairs"
            counts = [1, 2, 2, 2];
        otherwise
            error( ...
                "evaluateCurbRingFeatureBackgroundCalibration:" + ...
                "UnknownFamilyFormation", ...
                "Unsupported family formation: %s", formation);
    end
end


function accepted = localApplyFeatureRule( ...
        normalizedFeatures, featureRanks, featureFamilies, ...
        familyNames, familyMultipliers, localPercentile, ...
        minimumVotes, minimumSalientVotes, minimumMemberCounts)
    absoluteFamilyActive = false(size(normalizedFeatures, 1), ...
        numel(familyNames));
    salientFamilyActive = false(size(normalizedFeatures, 1), ...
        numel(familyNames));
    for familyIndex = 1:numel(familyNames)
        memberMask = featureFamilies == familyNames(familyIndex);
        absoluteMemberActive = normalizedFeatures(:, memberMask) ...
            >= familyMultipliers(familyIndex);
        absoluteFamilyActive(:, familyIndex) = ...
            sum(absoluteMemberActive, 2) ...
                >= minimumMemberCounts(familyIndex);
        if localPercentile > 0
            salientMemberActive = absoluteMemberActive ...
                & featureRanks(:, memberMask) >= localPercentile;
            salientFamilyActive(:, familyIndex) = ...
                any(salientMemberActive, 2);
        end
    end
    accepted = sum(absoluteFamilyActive, 2) >= minimumVotes;
    if localPercentile > 0
        accepted = accepted ...
            & sum(salientFamilyActive, 2) >= minimumSalientVotes;
    end
end


function accepted = localApplyFamilyRule( ...
        familyScores, familyRanks, familyMultipliers, ...
        localPercentile, minimumVotes, minimumSalientVotes)
    absoluteFamilyActive = familyScores >= familyMultipliers;
    accepted = sum(absoluteFamilyActive, 2) >= minimumVotes;
    if localPercentile > 0
        salientFamilyActive = absoluteFamilyActive ...
            & familyRanks >= localPercentile;
        accepted = accepted ...
            & sum(salientFamilyActive, 2) ...
                >= minimumSalientVotes;
    end
end


function accepted = localApplyRule( ...
        scores, ranks, multipliers, localPercentile, minimumVotes)
    active = scores >= multipliers;
    if localPercentile > 0
        active = active & ranks >= localPercentile;
    end
    accepted = sum(active, 2) >= minimumVotes;
end


function [minimumRecall, medianRecall, frameTable] = ...
        localFrameRecall(frames, accepted, ruleIndex)
    uniqueFrames = unique(frames, "stable");
    frameCount = numel(uniqueFrames);
    frameRows = cell(frameCount, 1);
    recalls = nan(frameCount, 1);
    for frameIndex = 1:frameCount
        mask = frames == uniqueFrames(frameIndex);
        recalls(frameIndex) = localRate(accepted(mask));
        frameRows{frameIndex} = table( ...
            ruleIndex, uniqueFrames(frameIndex), nnz(mask), ...
            nnz(accepted(mask)), recalls(frameIndex), ...
            VariableNames=[ ...
                "ruleIndex", "frameIndex", "positiveCount", ...
                "acceptedCount", "positiveRecall"]);
    end
    minimumRecall = min(recalls);
    medianRecall = median(recalls);
    frameTable = vertcat(frameRows{:});
end


function [recommended, pareto] = localRecommendRules( ...
        grid, minimumRecall, minimumFrameRecall)
    feasible = grid.positiveRecall >= minimumRecall ...
        & grid.minimumFrameRecall >= minimumFrameRecall;
    if ~any(feasible)
        [~, bestIndex] = max( ...
            grid.positiveRecall + 0.25*grid.minimumFrameRecall ...
            - grid.globalBackgroundActivation);
        recommended = grid(bestIndex, :);
    else
        candidates = grid(feasible, :);
        candidates = sortrows( ...
            candidates, ...
            ["globalBackgroundActivation", ...
             "localBackgroundActivation", ...
             "hardNegativeActivation", ...
             "positiveRecall"], ...
            ["ascend", "ascend", "ascend", "descend"]);
        recommended = candidates(1, :);
    end

    dominated = false(height(grid), 1);
    for rowIndex = 1:height(grid)
        noWorse = ...
            grid.positiveRecall >= grid.positiveRecall(rowIndex) ...
            & grid.minimumFrameRecall ...
                >= grid.minimumFrameRecall(rowIndex) ...
            & grid.globalBackgroundActivation ...
                <= grid.globalBackgroundActivation(rowIndex) ...
            & grid.localBackgroundActivation ...
                <= grid.localBackgroundActivation(rowIndex);
        strictlyBetter = ...
            grid.positiveRecall > grid.positiveRecall(rowIndex) ...
            | grid.minimumFrameRecall ...
                > grid.minimumFrameRecall(rowIndex) ...
            | grid.globalBackgroundActivation ...
                < grid.globalBackgroundActivation(rowIndex) ...
            | grid.localBackgroundActivation ...
                < grid.localBackgroundActivation(rowIndex);
        dominated(rowIndex) = any(noWorse & strictlyBetter);
    end
    pareto = sortrows( ...
        grid(~dominated, :), ...
        ["globalBackgroundActivation", "positiveRecall"], ...
        ["ascend", "descend"]);
end


function output = localExtendedFeatureAblation( ...
        positiveFeatures, positiveRanks, positiveFrames, ...
        localFeatures, localRanks, globalFeatures, globalRanks, ...
        hardNegativeFeatures, hardNegativeRanks, ...
        featureNames, featureFamilies, familyNames)
    extendedNames = [ ...
        "huangRadiusRatioDeviation", ...
        "huangHdInRadius", ...
        "sameRingSlopeMagnitude", ...
        "hataDifferentialHeightResponse"];
    legacyMask = ~ismember(featureNames, extendedNames);
    variantNames = [ ...
        "all-16-features", ...
        "legacy-12-only", ...
        "legacy-plus-" + extendedNames, ...
        "all-minus-" + extendedNames];
    variantMasks = cell(numel(variantNames), 1);
    variantMasks{1} = true(size(featureNames));
    variantMasks{2} = legacyMask;
    for extendedIndex = 1:numel(extendedNames)
        variantMasks{2 + extendedIndex} = legacyMask ...
            | featureNames == extendedNames(extendedIndex);
        variantMasks{2 + numel(extendedNames) + extendedIndex} = ...
            featureNames ~= extendedNames(extendedIndex);
    end

    familyMultipliers = 1.25*ones(1, numel(familyNames));
    minimumMemberCounts = ones(1, numel(familyNames));
    rows = cell(numel(variantNames), 1);
    for variantIndex = 1:numel(variantNames)
        mask = variantMasks{variantIndex};
        positiveAccepted = localApplyFeatureRule( ...
            positiveFeatures(:, mask), positiveRanks(:, mask), ...
            featureFamilies(mask), familyNames, familyMultipliers, ...
            0.60, 3, 2, minimumMemberCounts);
        localAccepted = localApplyFeatureRule( ...
            localFeatures(:, mask), localRanks(:, mask), ...
            featureFamilies(mask), familyNames, familyMultipliers, ...
            0.60, 3, 2, minimumMemberCounts);
        globalAccepted = localApplyFeatureRule( ...
            globalFeatures(:, mask), globalRanks(:, mask), ...
            featureFamilies(mask), familyNames, familyMultipliers, ...
            0.60, 3, 2, minimumMemberCounts);
        hardNegativeAccepted = localApplyFeatureRule( ...
            hardNegativeFeatures(:, mask), ...
            hardNegativeRanks(:, mask), ...
            featureFamilies(mask), familyNames, familyMultipliers, ...
            0.60, 3, 2, minimumMemberCounts);
        [minimumFrameRecall, medianFrameRecall] = localFrameRecall( ...
            positiveFrames, positiveAccepted, variantIndex);
        rows{variantIndex} = table( ...
            variantNames(variantIndex), nnz(mask), ...
            nnz(positiveAccepted), localRate(positiveAccepted), ...
            minimumFrameRecall, medianFrameRecall, ...
            nnz(localAccepted), localRate(localAccepted), ...
            nnz(globalAccepted), localRate(globalAccepted), ...
            nnz(hardNegativeAccepted), ...
            localRate(hardNegativeAccepted), ...
            VariableNames=[ ...
                "variant", "featureCount", ...
                "positiveAcceptedCount", "positiveRecall", ...
                "minimumFrameRecall", "medianFrameRecall", ...
                "localBackgroundAcceptedCount", ...
                "localBackgroundActivation", ...
                "globalBackgroundAcceptedCount", ...
                "globalBackgroundActivation", ...
                "hardNegativeAcceptedCount", ...
                "hardNegativeActivation"]);
    end
    output = vertcat(rows{:});
end


function finiteValues = localFinite(values)
    finiteValues = values(isfinite(values));
end


function rate = localRate(mask)
    if isempty(mask)
        rate = NaN;
    else
        rate = mean(mask);
    end
end


function auc = localAuc(positiveValues, negativeValues)
    positiveValues = localFinite(positiveValues);
    negativeValues = localFinite(negativeValues);
    positiveCount = numel(positiveValues);
    negativeCount = numel(negativeValues);
    if positiveCount == 0 || negativeCount == 0
        auc = NaN;
        return;
    end

    combined = [positiveValues(:); negativeValues(:)];
    [~, ~, valueGroup] = unique(combined);
    groupCount = accumarray(valueGroup, 1);
    firstRank = [1; 1 + cumsum(groupCount(1:end - 1))];
    averageRank = firstRank + 0.5*(groupCount - 1);
    rankSum = sum(averageRank(valueGroup(1:positiveCount)));
    auc = (rankSum - positiveCount*(positiveCount + 1)/2) ...
        / (positiveCount*negativeCount);
end


function value = localEmpiricalQuantile(values, probability)
    values = sort(localFinite(values));
    if isempty(values)
        value = NaN;
        return;
    end
    position = 1 + (numel(values) - 1)*probability;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    if lowerIndex == upperIndex
        value = values(lowerIndex);
    else
        fraction = position - lowerIndex;
        value = values(lowerIndex)*(1 - fraction) ...
            + values(upperIndex)*fraction;
    end
end
