function resultsTable = evaluateExportedCurbMasksAgainstDevelopmentLabels( ...
        datasetFolder, maskJsonlPath, options)
%EVALUATEEXPORTEDCURBMASKSAGAINSTDEVELOPMENTLABELS Evaluate saved curb masks.
%   RESULTSTABLE = EVALUATEEXPORTEDCURBMASKSAGAINSTDEVELOPMENTLABELS( ...
%   DATASETFOLDER, MASKJSONLPATH) compares the zero-based raw-point indices
%   in an exported curb-mask JSONL file with the manually reviewed XYZ
%   coordinates returned by curbRingFeatureDevelopmentLabels.
%
%   RESULTSTABLE = EVALUATEEXPORTEDCURBMASKSAGAINSTDEVELOPMENTLABELS( ...
%   ..., OutputPath=PATH, MatchToleranceM=TOLERANCE,
%   LabelCatalog=CATALOG, FrameLoader=LOADER) optionally writes the returned
%   table, changes the maximum coordinate-to-raw-point matching distance,
%   injects a label catalog, or injects a frame loader for synthetic tests.
%   LOADER is called as LOADER(DATASETFOLDER, FRAMEINDEX).
%
%   The returned columns are frameIndex, label, count, selectedCount, and
%   selectedRate. A catalog frame absent from the JSONL file has zero
%   selections. Exported detector masks are evaluated predictions only;
%   they are never used to construct or augment the manual labels.

    arguments
        datasetFolder (1, 1) string
        maskJsonlPath (1, 1) string
        options.OutputPath (1, 1) string = ""
        options.MatchToleranceM (1, 1) double ...
            {mustBePositive, mustBeFinite} = 1.0e-4
        options.LabelCatalog (1, 1) struct = struct()
        options.FrameLoader = []
    end

    if isempty(fieldnames(options.LabelCatalog))
        catalog = curbRingFeatureDevelopmentLabels();
    else
        catalog = options.LabelCatalog;
    end
    localValidateCatalog(catalog);

    usesDefaultFrameLoader = isempty(options.FrameLoader);
    if usesDefaultFrameLoader
        frameLoader = @localLoadNpyFrame;
    elseif isa(options.FrameLoader, "function_handle") ...
            && isscalar(options.FrameLoader)
        frameLoader = options.FrameLoader;
    else
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "InvalidFrameLoader", ...
            "FrameLoader must be empty or a scalar function handle.");
    end

    localValidateDataset( ...
        datasetFolder, catalog, usesDefaultFrameLoader);
    maskRecords = localReadMaskRecords(maskJsonlPath);
    resultsTable = localEmptyResultsTable();

    for anchorIndex = 1:numel(catalog.anchors)
        anchor = catalog.anchors(anchorIndex);
        frameIndex = double(anchor.frameIndex);
        rawPoints = frameLoader(datasetFolder, frameIndex);
        localValidateRawPoints(rawPoints, frameIndex);
        selectedIndicesZeroBased = localSelectedIndices( ...
            maskRecords, frameIndex);
        localValidateSelectedIndices( ...
            selectedIndicesZeroBased, size(rawPoints, 1), frameIndex);

        resultsTable = localAppendLabelResult( ...
            resultsTable, frameIndex, "positive", ...
            anchor.positiveCoordinatesM, rawPoints(:, 1:3), ...
            selectedIndicesZeroBased, options.MatchToleranceM);
        resultsTable = localAppendLabelResult( ...
            resultsTable, frameIndex, "hard-negative", ...
            anchor.hardNegativeCoordinatesM, rawPoints(:, 1:3), ...
            selectedIndicesZeroBased, options.MatchToleranceM);
    end

    if strlength(options.OutputPath) > 0
        outputFolder = fileparts(options.OutputPath);
        if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
            mkdir(outputFolder);
        end
        writetable(resultsTable, options.OutputPath);
    end
end


function localValidateCatalog(catalog)
    requiredFields = ["anchors", "independentGroundTruth"];
    if ~isstruct(catalog) || ~isscalar(catalog) ...
            || ~all(isfield(catalog, requiredFields))
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "InvalidCatalog", ...
            "LabelCatalog does not have the required catalog fields.");
    end
    anchorFields = [ ...
        "frameIndex", "positiveCoordinatesM", ...
        "hardNegativeCoordinatesM"];
    if ~isstruct(catalog.anchors) ...
            || ~all(isfield(catalog.anchors, anchorFields))
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "InvalidAnchors", ...
            "LabelCatalog anchors do not have the required fields.");
    end

    for anchorIndex = 1:numel(catalog.anchors)
        anchor = catalog.anchors(anchorIndex);
        if ~isnumeric(anchor.frameIndex) ...
                || ~isscalar(anchor.frameIndex) ...
                || ~isfinite(anchor.frameIndex) ...
                || anchor.frameIndex < 0 ...
                || anchor.frameIndex ~= floor(anchor.frameIndex)
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "InvalidFrameIndex", ...
                "Each label-catalog frame index must be a nonnegative integer.");
        end
        localValidateCoordinates( ...
            anchor.positiveCoordinatesM, "positive", ...
            anchor.frameIndex);
        localValidateCoordinates( ...
            anchor.hardNegativeCoordinatesM, "hard-negative", ...
            anchor.frameIndex);
    end
end


function localValidateCoordinates(coordinates, label, frameIndex)
    if ~isnumeric(coordinates) || size(coordinates, 2) ~= 3 ...
            || any(~isfinite(coordinates), "all")
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "InvalidCoordinates", ...
            "Frame %d %s coordinates must be a finite N-by-3 array.", ...
            frameIndex, label);
    end
end


function localValidateDataset( ...
        datasetFolder, catalog, usesDefaultFrameLoader)
    if isfield(catalog, "datasetName")
        [~, datasetName] = fileparts(datasetFolder);
        if string(datasetName) ~= string(catalog.datasetName)
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "DatasetMismatch", ...
                "The label catalog is for %s, not %s.", ...
                catalog.datasetName, datasetName);
        end
    end
    if usesDefaultFrameLoader ...
            && ~isfolder(fullfile(datasetFolder, "lidar"))
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "MissingLidar", ...
            "Dataset does not contain a lidar folder: %s", ...
            datasetFolder);
    end
end


function records = localReadMaskRecords(maskJsonlPath)
    if ~isfile(maskJsonlPath)
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "MissingMaskFile", ...
            "The curb-mask JSONL file does not exist: %s", ...
            maskJsonlPath);
    end
    fileIdentifier = fopen(maskJsonlPath, "rt");
    if fileIdentifier < 0
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "MaskOpenFailed", ...
            "Unable to open the curb-mask JSONL file: %s", ...
            maskJsonlPath);
    end
    cleaner = onCleanup(@() fclose(fileIdentifier));

    frameIndices = zeros(0, 1);
    selectedIndices = cell(0, 1);
    lineNumber = 0;
    while ~feof(fileIdentifier)
        line = fgetl(fileIdentifier);
        lineNumber = lineNumber + 1;
        if ~ischar(line) || isempty(strtrim(line))
            continue
        end
        try
            record = jsondecode(line);
        catch exception
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "InvalidJson", ...
                "Unable to decode JSONL line %d: %s", ...
                lineNumber, exception.message);
        end
        if ~isstruct(record) || ~isscalar(record) ...
                || ~isfield(record, "frame") ...
                || ~isfield(record, "curbPointIndicesZeroBased")
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "InvalidMaskRecord", ...
                "JSONL line %d must contain frame and " + ...
                "curbPointIndicesZeroBased fields.", ...
                lineNumber);
        end

        frameIndex = double(record.frame);
        if ~isnumeric(record.frame) || ~isscalar(frameIndex) ...
                || ~isfinite(frameIndex) || frameIndex < 0 ...
                || frameIndex ~= floor(frameIndex)
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "InvalidMaskFrame", ...
                "JSONL line %d has an invalid frame index.", lineNumber);
        end
        if any(frameIndices == frameIndex)
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "DuplicateMaskFrame", ...
                "The curb-mask JSONL file contains duplicate frame %d.", ...
                frameIndex);
        end

        indices = record.curbPointIndicesZeroBased;
        if ~isnumeric(indices) || any(~isfinite(indices), "all") ...
                || any(indices < 0, "all") ...
                || any(indices ~= floor(indices), "all")
            error( ...
                "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
                "InvalidMaskIndices", ...
                "Frame %d curb indices must be nonnegative integers.", ...
                frameIndex);
        end
        frameIndices(end + 1, 1) = frameIndex; %#ok<AGROW>
        selectedIndices{end + 1, 1} = ...
            unique(double(indices(:)), "stable"); %#ok<AGROW>
    end
    clear cleaner;

    records = struct( ...
        "frameIndices", frameIndices, ...
        "selectedIndices", {selectedIndices});
end


function selectedIndices = localSelectedIndices(records, frameIndex)
    recordIndex = find(records.frameIndices == frameIndex, 1);
    if isempty(recordIndex)
        selectedIndices = zeros(0, 1);
    else
        selectedIndices = records.selectedIndices{recordIndex};
    end
end


function rawPoints = localLoadNpyFrame(datasetFolder, frameIndex)
    framePath = fullfile( ...
        datasetFolder, "lidar", sprintf("%06d.npy", frameIndex));
    if ~isfile(framePath)
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "MissingFrame", ...
            "LiDAR frame does not exist: %s", framePath);
    end
    try
        rawPoints = double(py.numpy.load(framePath));
    catch exception
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "NpyLoadFailed", ...
            "Unable to load %s through NumPy: %s", ...
            framePath, exception.message);
    end
end


function localValidateRawPoints(rawPoints, frameIndex)
    if ~isnumeric(rawPoints) || size(rawPoints, 2) < 3 ...
            || isempty(rawPoints) ...
            || any(~isfinite(rawPoints(:, 1:3)), "all")
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "InvalidFrame", ...
            "Frame %d must contain finite XYZ columns.", frameIndex);
    end
end


function localValidateSelectedIndices( ...
        selectedIndicesZeroBased, pointCount, frameIndex)
    if any(selectedIndicesZeroBased >= pointCount)
        error( ...
            "evaluateExportedCurbMasksAgainstDevelopmentLabels:" + ...
            "MaskIndexOutOfRange", ...
            "Frame %d contains a curb index outside its %d raw points.", ...
            frameIndex, pointCount);
    end
end


function resultsTable = localAppendLabelResult( ...
        resultsTable, frameIndex, label, coordinates, rawPoints, ...
        selectedIndicesZeroBased, matchToleranceM)
    coordinates = double(coordinates);
    labelCount = size(coordinates, 1);
    if labelCount == 0
        return
    end

    matchedRawIndicesZeroBased = nan(labelCount, 1);
    for coordinateIndex = 1:labelCount
        differences = rawPoints - coordinates(coordinateIndex, :);
        squaredDistances = sum(differences.^2, 2);
        [minimumSquaredDistance, rawPointIndex] = min(squaredDistances);
        if sqrt(minimumSquaredDistance) <= matchToleranceM
            matchedRawIndicesZeroBased(coordinateIndex) = ...
                rawPointIndex - 1;
        end
    end

    selected = isfinite(matchedRawIndicesZeroBased) ...
        & ismember( ...
            matchedRawIndicesZeroBased, selectedIndicesZeroBased);
    selectedCount = nnz(selected);
    resultsTable(end + 1, :) = { ...
        frameIndex, label, labelCount, selectedCount, ...
        selectedCount / labelCount};
end


function resultsTable = localEmptyResultsTable()
    resultsTable = table( ...
        Size=[0, 5], ...
        VariableTypes=[ ...
            "double", "string", "double", "double", "double"], ...
        VariableNames=[ ...
            "frameIndex", "label", "count", ...
            "selectedCount", "selectedRate"]);
end
