function summary = exportCurbPointIndices( ...
        datasetFolder, outputPath, reportInterval, detectorConfig, ...
        maximumFrameCount)
%EXPORTCURBPOINTINDICES Export raw LiDAR indices selected by curb detection.
%   Set detectorConfig.curbTemporalTrackingEnabled to true to propagate and
%   gate fitted curb quadratics with the recorded ego state
%       [x, xDot, xDDot, y, yDot, yDDot, psi, psiDot].
%   The translational states are fixed-inertial-frame quantities. The
%   exporter derives acceleration and yaw rate causally from frames.jsonl
%   when those channels are not recorded explicitly.
%   MAXIMUMFRAMECOUNT optionally limits a development export to the first
%   N chronologically sorted frames. The default Inf exports all frames.

    arguments
        datasetFolder (1, 1) string
        outputPath (1, 1) string
        reportInterval (1, 1) double ...
            {mustBeInteger, mustBePositive} = 50
        detectorConfig (1, 1) struct = struct()
        maximumFrameCount (1, 1) double = inf
    end
    if ~(isinf(maximumFrameCount) && maximumFrameCount > 0) ...
            && ~(isfinite(maximumFrameCount) ...
                && maximumFrameCount >= 1 ...
                && maximumFrameCount == floor(maximumFrameCount))
        error( ...
            "exportCurbPointIndices:InvalidMaximumFrameCount", ...
            "maximumFrameCount must be a positive integer or Inf.");
    end

    repositoryRoot = fileparts(fileparts(fileparts( ...
        mfilename("fullpath"))));
    detectorFolder = fullfile( ...
        repositoryRoot, "perception", "curbDetectionExperiment");
    lidarFolder = fullfile(datasetFolder, "lidar");
    if ~isfolder(lidarFolder)
        error("exportCurbPointIndices:MissingLidarFolder", ...
            "Unable to find the LiDAR folder: %s", lidarFolder);
    end
    if ~isfile(fullfile(detectorFolder, "groundPointsProcessing.m"))
        error("exportCurbPointIndices:MissingDetector", ...
            "Unable to find groundPointsProcessing.m in: %s", ...
            detectorFolder);
    end
    addpath(detectorFolder);

    lidarFiles = dir(fullfile(lidarFolder, "*.npy"));
    if isempty(lidarFiles)
        error("exportCurbPointIndices:NoFrames", ...
            "No .npy LiDAR frames were found in: %s", lidarFolder);
    end
    [~, order] = sort({lidarFiles.name});
    lidarFiles = lidarFiles(order);
    if isfinite(maximumFrameCount)
        lidarFiles = lidarFiles( ...
            1:min(numel(lidarFiles), maximumFrameCount));
    end
    temporalTrackingEnabled = localLogicalConfigValue( ...
        detectorConfig, "curbTemporalTrackingEnabled", false);
    if temporalTrackingEnabled
        [egoStates, sampleTimes] = localLoadEgoStateHistory( ...
            datasetFolder, lidarFiles);
    else
        egoStates = zeros(numel(lidarFiles), 8);
        sampleTimes = ones(numel(lidarFiles), 1);
    end

    outputFolder = fileparts(outputPath);
    if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
        mkdir(outputFolder);
    end
    if isfile(outputPath)
        error("exportCurbPointIndices:OutputExists", ...
            "Refusing to overwrite the existing output: %s", outputPath);
    end
    partialPath = outputPath + ".partial";
    if isfile(partialPath)
        error("exportCurbPointIndices:PartialOutputExists", ...
            "Remove or preserve the existing partial output first: %s", ...
            partialPath);
    end

    pythonEnvironment = pyenv;
    if pythonEnvironment.Status == "NotLoaded"
        pythonExecutable = ...
            "/home/zai/.cache/carla-yolo-range-venv/bin/python";
        pyenv( ...
            Version=pythonExecutable, ...
            ExecutionMode="OutOfProcess");
    end

    fileIdentifier = fopen(partialPath, "wt");
    if fileIdentifier < 0
        error("exportCurbPointIndices:OpenFailed", ...
            "Unable to open output file: %s", partialPath);
    end

    frameCount = numel(lidarFiles);
    curbCounts = zeros(frameCount, 1);
    headingDegrees = nan(frameCount, 1);
    routeWidths = nan(frameCount, 1);
    leftPredictionUsed = false(frameCount, 1);
    rightPredictionUsed = false(frameCount, 1);
    trackerReset = false(frameCount, 1);
    trackerState = [];
    try
        for fileIndex = 1:frameCount
            framePath = fullfile( ...
                lidarFolder, lidarFiles(fileIndex).name);
            [rawPoints, organizedFrame, rawPointIndexGrid] = ...
                localLoadOrganizedFrame(framePath);
            if temporalTrackingEnabled
                [processingResult, trackerState, temporalDiagnostics] = ...
                    temporalGroundPointsProcessing( ...
                        organizedFrame, egoStates(fileIndex, :), ...
                        sampleTimes(fileIndex), trackerState, ...
                        detectorConfig);
                leftPredictionUsed(fileIndex) = ...
                    temporalDiagnostics.left.usedPrediction;
                rightPredictionUsed(fileIndex) = ...
                    temporalDiagnostics.right.usedPrediction;
                trackerReset(fileIndex) = temporalDiagnostics.reset;
            else
                processingResult = groundPointsProcessing( ...
                    organizedFrame, detectorConfig);
                temporalDiagnostics = struct();
            end
            rawCurbIndices = localRawCurbIndices( ...
                processingResult.curbs, rawPointIndexGrid);
            zeroBasedIndices = reshape(rawCurbIndices - 1, 1, []);

            curbCounts(fileIndex) = numel(rawCurbIndices);
            roadFrame = processingResult.curbModels.roadFrame;
            headingDegrees(fileIndex) = roadFrame.headingDegrees;
            routeWidths(fileIndex) = roadFrame.roadWidth;
            record = struct( ...
                "frame", fileIndex - 1, ...
                "lidarFile", string(lidarFiles(fileIndex).name), ...
                "pointCount", size(rawPoints, 1), ...
                "curbPointCount", curbCounts(fileIndex), ...
                "roadHeadingDegrees", headingDegrees(fileIndex), ...
                "roadWidthM", routeWidths(fileIndex), ...
                "curbPointIndicesZeroBased", zeroBasedIndices);
            if temporalTrackingEnabled
                record.temporal = localTemporalRecord( ...
                    temporalDiagnostics, processingResult.curbModels, ...
                    egoStates(fileIndex, :), ...
                    sampleTimes(fileIndex));
                if isfield(temporalDiagnostics, "measurementSource")
                    record.temporal.measurementSource = ...
                        string(temporalDiagnostics.measurementSource);
                end
            end
            fprintf(fileIdentifier, "%s\n", jsonencode(record));

            if mod(fileIndex - 1, reportInterval) == 0
                fprintf( ...
                    "[curb frame %05d/%05d] points=%d curb=%d\n", ...
                    fileIndex - 1, frameCount - 1, ...
                    size(rawPoints, 1), curbCounts(fileIndex));
            end
        end
        fclose(fileIdentifier);
    catch exception
        if fileIdentifier >= 0
            fclose(fileIdentifier);
        end
        rethrow(exception);
    end

    [moveStatus, moveMessage] = movefile(partialPath, outputPath);
    if ~moveStatus
        error("exportCurbPointIndices:MoveFailed", ...
            "Unable to finalize %s: %s", outputPath, moveMessage);
    end
    summary = struct( ...
        "datasetFolder", datasetFolder, ...
        "outputPath", outputPath, ...
        "detectorConfig", detectorConfig, ...
        "frameCount", frameCount, ...
        "minimumCurbPointCount", min(curbCounts), ...
        "maximumCurbPointCount", max(curbCounts), ...
        "meanCurbPointCount", mean(curbCounts), ...
        "bilateralRoadFrameCount", nnz(isfinite(routeWidths)), ...
        "temporalTrackingEnabled", temporalTrackingEnabled, ...
        "leftPredictionFrameCount", nnz(leftPredictionUsed), ...
        "rightPredictionFrameCount", nnz(rightPredictionUsed), ...
        "trackerResetFrameCount", nnz(trackerReset));
    fprintf( ...
        "Exported %d curb masks: count min=%d mean=%.2f max=%d\n", ...
        frameCount, min(curbCounts), mean(curbCounts), ...
        max(curbCounts));
end


function [egoStates, sampleTimes] = localLoadEgoStateHistory( ...
        datasetFolder, lidarFiles)
    framesPath = fullfile(datasetFolder, "frames.jsonl");
    if ~isfile(framesPath)
        error( ...
            "exportCurbPointIndices:MissingFrameRecords", ...
            "Temporal tracking requires frames.jsonl: %s", ...
            framesPath);
    end

    frameCount = numel(lidarFiles);
    times = nan(frameCount, 1);
    positions = nan(frameCount, 2);
    velocities = nan(frameCount, 2);
    yawRadians = nan(frameCount, 1);
    recordsFound = false(frameCount, 1);
    fileIdentifier = fopen(framesPath, "rt");
    if fileIdentifier < 0
        error( ...
            "exportCurbPointIndices:FrameRecordsOpenFailed", ...
            "Unable to open frame records: %s", framesPath);
    end
    cleaner = onCleanup(@() fclose(fileIdentifier));
    while ~feof(fileIdentifier)
        line = fgetl(fileIdentifier);
        if ~ischar(line) || isempty(strtrim(line))
            continue;
        end
        record = jsondecode(line);
        frameIndex = double(record.frame) + 1;
        if frameIndex < 1 || frameIndex ~= floor(frameIndex)
            error( ...
                "exportCurbPointIndices:InvalidFrameIndex", ...
                "frames.jsonl contains out-of-range frame %g.", ...
                double(record.frame));
        end
        if frameIndex > frameCount
            continue;
        end
        if recordsFound(frameIndex)
            error( ...
                "exportCurbPointIndices:DuplicateFrameIndex", ...
                "frames.jsonl contains duplicate frame %d.", ...
                frameIndex - 1);
        end

        location = reshape( ...
            double(record.ego.transform.location_m), 1, []);
        velocity = reshape(double(record.ego.velocity), 1, []);
        rotationDegrees = reshape( ...
            double(record.ego.transform.rotation_deg), 1, []);
        if numel(location) < 2 || numel(velocity) < 2 ...
                || numel(rotationDegrees) < 2
            error( ...
                "exportCurbPointIndices:IncompleteEgoState", ...
                "Frame %d lacks ego x/y, velocity, or yaw.", ...
                frameIndex - 1);
        end
        [~, recordedLidarName, recordedLidarExtension] = fileparts( ...
            string(record.sensors.lidar.path));
        expectedLidarName = string(lidarFiles(frameIndex).name);
        if recordedLidarName + recordedLidarExtension ...
                ~= expectedLidarName
            error( ...
                "exportCurbPointIndices:LidarFrameMismatch", ...
                "Frame %d references %s but the sorted LiDAR file is %s.", ...
                frameIndex - 1, ...
                recordedLidarName + recordedLidarExtension, ...
                expectedLidarName);
        end

        times(frameIndex) = double(record.time);
        positions(frameIndex, :) = location(1:2);
        velocities(frameIndex, :) = velocity(1:2);
        yawRadians(frameIndex) = deg2rad(rotationDegrees(2));
        recordsFound(frameIndex) = true;
    end
    clear cleaner;

    if ~all(recordsFound)
        missingFrames = find(~recordsFound) - 1;
        error( ...
            "exportCurbPointIndices:MissingEgoStates", ...
            "frames.jsonl lacks %d frame records; first missing frame is %d.", ...
            numel(missingFrames), missingFrames(1));
    end
    if any(~isfinite([times, positions, velocities, yawRadians]), "all")
        error( ...
            "exportCurbPointIndices:NonfiniteEgoState", ...
            "Temporal tracking requires finite recorded ego states.");
    end

    timeDifferences = diff(times);
    if isempty(timeDifferences) || any(timeDifferences <= 0)
        error( ...
            "exportCurbPointIndices:InvalidFrameTimes", ...
            "frames.jsonl times must be strictly increasing.");
    end
    sampleTimes = [median(timeDifferences); timeDifferences];
    accelerations = zeros(frameCount, 2);
    accelerations(2:end, :) = ...
        diff(velocities, 1, 1) ./ timeDifferences;
    unwrappedYaw = unwrap(yawRadians);
    yawRates = zeros(frameCount, 1);
    yawRates(2:end) = diff(unwrappedYaw) ./ timeDifferences;
    egoStates = [ ...
        positions(:, 1), velocities(:, 1), accelerations(:, 1), ...
        positions(:, 2), velocities(:, 2), accelerations(:, 2), ...
        unwrappedYaw, yawRates];
end


function record = localTemporalRecord( ...
        diagnostics, curbModels, egoState, sampleTime)
    record = struct( ...
        "stateConvention", ...
            "x/y and derivatives in fixed inertial frame; psi in radians", ...
        "sampleTimeS", double(sampleTime), ...
        "egoState", reshape(double(egoState), 1, 8), ...
        "reset", logical(diagnostics.reset), ...
        "resetReason", string(diagnostics.resetReason), ...
        "positionResidualM", double(diagnostics.positionResidualM), ...
        "headingResidualRad", double(diagnostics.headingResidualRad), ...
        "roadHeadingPriorApplied", ...
            logical(diagnostics.roadHeadingPriorApplied), ...
        "roadHeadingPriorDegrees", ...
            double(diagnostics.roadHeadingPriorDegrees), ...
        "innovationToleranceM", ...
            double(diagnostics.innovationToleranceM), ...
        "measurementCorridorWidthM", ...
            double(diagnostics.measurementCorridorWidthM), ...
        "unconstrainedCorridorWidthM", ...
            double(diagnostics.unconstrainedCorridorWidthM), ...
        "corridorWidthM", double(diagnostics.corridorWidthM), ...
        "corridorResidualM", double(diagnostics.corridorResidualM), ...
        "corridorProfileResidualM", ...
            double(diagnostics.corridorProfileResidualM), ...
        "left", localTemporalSideRecord( ...
            diagnostics.left, localCombinedCurbModel( ...
                curbModels, "left")), ...
        "right", localTemporalSideRecord( ...
            diagnostics.right, localCombinedCurbModel( ...
                curbModels, "right")));
end


function record = localTemporalSideRecord(diagnostics, model)
    record = struct( ...
        "measurementFound", logical(diagnostics.measurementFound), ...
        "predictionFound", logical(diagnostics.predictionFound), ...
        "innovationM", double(diagnostics.innovationM), ...
        "age", double(diagnostics.age), ...
        "usedPrediction", logical(diagnostics.usedPrediction), ...
        "pairConstraintApplied", ...
            logical(diagnostics.pairConstraintApplied), ...
        "updateMode", string(diagnostics.updateMode), ...
        "model", localCurbModelRecord(model));
end


function record = localCurbModelRecord(model)
    record = struct( ...
        "found", logical(model.found), ...
        "curvature", double(model.curvature), ...
        "slope", double(model.slope), ...
        "intercept", double(model.intercept), ...
        "minimumX", double(model.minimumX), ...
        "maximumX", double(model.maximumX), ...
        "minimumZ", double(model.minimumZ), ...
        "maximumZ", double(model.maximumZ));
end


function model = localCombinedCurbModel(models, sideName)
    lineField = char(sideName);
    forwardField = [lineField, 'Forward'];
    if isfield(models, forwardField) ...
            && models.(forwardField).found
        model = models.(forwardField);
    elseif isfield(models, lineField) ...
            && models.(lineField).found
        model = models.(lineField);
    else
        model = struct( ...
            "found", false, ...
            "curvature", 0.0, ...
            "slope", NaN, ...
            "intercept", NaN, ...
            "minimumX", NaN, ...
            "maximumX", NaN, ...
            "minimumZ", NaN, ...
            "maximumZ", NaN);
    end
end


function value = localLogicalConfigValue(cfg, fieldName, defaultValue)
    value = logical(defaultValue);
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    if (islogical(candidate) || isnumeric(candidate)) ...
            && isscalar(candidate) && isfinite(double(candidate))
        value = logical(candidate);
    end
end


function [rawPoints, organizedFrame, rawPointIndexGrid] = ...
        localLoadOrganizedFrame(framePath)
    rawPoints = double(py.numpy.load(framePath));
    if size(rawPoints, 2) < 3
        error("exportCurbPointIndices:InvalidLidarFrame", ...
            "LiDAR frame must contain at least XYZ columns: %s", ...
            framePath);
    end
    [organizedFrame, rawPointIndexGrid] = ...
        organizeLidarSweepGrid(rawPoints);
end


function rawCurbIndices = localRawCurbIndices( ...
        organizedCurbIndices, rawPointIndexGrid)
    if isempty(organizedCurbIndices)
        rawCurbIndices = zeros(0, 1);
        return
    end
    organizedLinearIndices = sub2ind( ...
        size(rawPointIndexGrid), ...
        organizedCurbIndices(:, 2), ...
        organizedCurbIndices(:, 1));
    rawCurbIndices = rawPointIndexGrid(organizedLinearIndices);
    rawCurbIndices = unique( ...
        rawCurbIndices(rawCurbIndices > 0), "stable");
end
