function [acceptedMask, diagnostics] = ...
        fuseLidarRingCurbFeatures(features, featureValidity, cfg)
%FUSELIDARRINGCURBFEATURES Fuse side-agnostic LiDAR ring feature families.
%   [ACCEPTEDMASK, DIAGNOSTICS] =
%   FUSELIDARRINGCURBFEATURES(FEATURES, FEATUREVALIDITY, CFG) combines the
%   outputs of computeLidarRingCurbFeatures into four independent evidence
%   families. Features within compression, vertical, and shape are combined
%   by OR. Radial evidence requires two of its four members by default. A
%   A salient family must first satisfy its absolute member-count rule and
%   must also contain at least one locally salient active member. A cell is
%   accepted only when both the absolute-family and locally salient family
%   vote requirements are satisfied.
%
%   The four families are:
%       compression  Hata normalized adjacent-ring compression
%       vertical     height step, local height range, scale-1 height Haar
%       radial       Wang spacing excess, reconstructed-radius deviation,
%                    radial second difference, scale-1 range Haar
%       shape        Huang radial-tangent strength, same-ring slope change,
%                    ILP line-fit residual, ILP line-slope magnitude
%
%   Every individual feature must be finite and have a true same-named
%   FEATUREVALIDITY entry before it can make its family available or vote.
%   FEATUREVALIDITY.base gates every family. No vehicle-side, x-coordinate,
%   or y-coordinate information is consumed.
%
%   CFG is an optional scalar structure with these fields:
%       enabled                         logical scalar, default true
%       minimumFamilyVotes              integer in [1, 4], default 2
%       minimumRadialMemberVotes        integer in [1, 4], default 2
%       saliencyEnabled                 logical scalar, default true
%       localHalfWidthBins              positive integer, default 33
%       localExclusionBins              nonnegative integer, default 3
%       minimumLocalNeighborCount       positive integer, default 12
%       localPercentileThreshold        scalar in [0, 1], default 0.5
%       minimumSalientFamilyVotes       integer in [1, 4], default 2
%       thresholds                      scalar structure containing any
%                                       subset of the threshold fields below
%
%   The default thresholds are 1.25 times the development hard-negative
%   95th percentiles:
%       hataCompressionNormalized             0.25
%       heightStep                             0.005
%       localHeightRange                       0.01875
%       localMultiscaleHaarZ                   0.01125
%       wangHorizontalSpacingExcess            0.005625
%       radiusRatioReconstructionDeviation     0.00010
%       radialSecondDifference                 0.009375
%       localMultiscaleHaarRange               0.045
%       huangTangentialStrength                0.1125
%       sameRingSlopeChange                    0.0035
%       ilpLineFitResidual                     0.00325
%       ilpLineSlopeMagnitude                  0.025
%
%   Local percentiles use finite, valid values of the same member and ring
%   in a circular azimuth window. Defaults use offsets -33:-3 and 3:33,
%   thereby skipping offsets -2:2, and require at least 12 neighbors. The
%   percentile is the midrank fraction
%       (count(neighbor < value) + 0.5*count(neighbor == value)) / count.
%
%   DIAGNOSTICS contains absolute Evidence, Available, and salient masks per
%   family, member vote counts per family, familyVoteCount,
%   salientFamilyVoteCount, availableFamilyCount, effective parameters, and
%   acceptedMask. When CFG.saliencyEnabled is false, salient masks and their
%   count are false/zero and only absolute-family voting gates acceptance.
%   When CFG.enabled is false, ACCEPTEDMASK is exactly
%   FEATUREVALIDITY.base; absolute evidence, votes, and availability remain
%   diagnostic while saliency is not evaluated.

    if nargin < 3 || isempty(cfg)
        cfg = struct();
    end

    baseValid = localValidateFeatureSchema(features, featureValidity);
    parameters = localFusionParameters(cfg);

    [compressionAvailable, compressionMemberEvidence, ...
        compressionMemberSalient] = localMemberMasks( ...
        features.hataCompressionNormalized, ...
        featureValidity.hataCompressionNormalized, ...
        baseValid, parameters.thresholds.hataCompressionNormalized, ...
        parameters);

    [heightStepAvailable, heightStepEvidence, heightStepSalient] = ...
        localMemberMasks( ...
        features.heightStep, featureValidity.heightStep, baseValid, ...
        parameters.thresholds.heightStep, parameters);
    [heightRangeAvailable, heightRangeEvidence, heightRangeSalient] = ...
        localMemberMasks( ...
        features.localHeightRange, featureValidity.localHeightRange, ...
        baseValid, parameters.thresholds.localHeightRange, parameters);
    [heightHaarAvailable, heightHaarEvidence, heightHaarSalient] = ...
        localMemberMasks( ...
        features.localMultiscaleHaarZ(:, :, 1), ...
        featureValidity.localMultiscaleHaarZ(:, :, 1), baseValid, ...
        parameters.thresholds.localMultiscaleHaarZ, parameters);
    verticalAvailable = heightStepAvailable | heightRangeAvailable ...
        | heightHaarAvailable;
    verticalMemberVoteCount = uint8(heightStepEvidence) ...
        + uint8(heightRangeEvidence) + uint8(heightHaarEvidence);
    verticalEvidence = verticalMemberVoteCount >= 1;
    verticalSalientEvidence = verticalEvidence ...
        & (heightStepSalient | heightRangeSalient ...
            | heightHaarSalient);

    [spacingAvailable, spacingEvidence, spacingSalient] = ...
        localMemberMasks( ...
        features.wangHorizontalSpacingExcess, ...
        featureValidity.wangHorizontalSpacingExcess, baseValid, ...
        parameters.thresholds.wangHorizontalSpacingExcess, parameters);
    [radiusAvailable, radiusEvidence, radiusSalient] = localMemberMasks( ...
        features.radiusRatioReconstructionDeviation, ...
        featureValidity.radiusRatioReconstructionDeviation, baseValid, ...
        parameters.thresholds.radiusRatioReconstructionDeviation, ...
        parameters);
    [secondDifferenceAvailable, secondDifferenceEvidence, ...
        secondDifferenceSalient] = localMemberMasks( ...
            features.radialSecondDifference, ...
            featureValidity.radialSecondDifference, baseValid, ...
            parameters.thresholds.radialSecondDifference, parameters);
    [rangeHaarAvailable, rangeHaarEvidence, rangeHaarSalient] = ...
        localMemberMasks( ...
        features.localMultiscaleHaarRange(:, :, 1), ...
        featureValidity.localMultiscaleHaarRange(:, :, 1), baseValid, ...
        parameters.thresholds.localMultiscaleHaarRange, parameters);
    radialAvailable = spacingAvailable | radiusAvailable ...
        | secondDifferenceAvailable | rangeHaarAvailable;
    radialMemberVoteCount = uint8(spacingEvidence) ...
        + uint8(radiusEvidence) + uint8(secondDifferenceEvidence) ...
        + uint8(rangeHaarEvidence);
    radialEvidence = radialMemberVoteCount ...
        >= parameters.minimumRadialMemberVotes;
    radialSalientEvidence = radialEvidence ...
        & (spacingSalient | radiusSalient ...
            | secondDifferenceSalient | rangeHaarSalient);

    [huangAvailable, huangEvidence, huangSalient] = localMemberMasks( ...
        features.huangTangentialStrength, ...
        featureValidity.huangTangentialStrength, baseValid, ...
        parameters.thresholds.huangTangentialStrength, parameters);
    [slopeChangeAvailable, slopeChangeEvidence, slopeChangeSalient] = ...
        localMemberMasks( ...
        features.sameRingSlopeChange, ...
        featureValidity.sameRingSlopeChange, baseValid, ...
        parameters.thresholds.sameRingSlopeChange, parameters);
    [lineFitAvailable, lineFitEvidence, lineFitSalient] = ...
        localMemberMasks( ...
        features.ilpLineFitResidual, ...
        featureValidity.ilpLineFitResidual, baseValid, ...
        parameters.thresholds.ilpLineFitResidual, parameters);
    [lineSlopeAvailable, lineSlopeEvidence, lineSlopeSalient] = ...
        localMemberMasks( ...
        features.ilpLineSlopeMagnitude, ...
        featureValidity.ilpLineSlopeMagnitude, baseValid, ...
        parameters.thresholds.ilpLineSlopeMagnitude, parameters);
    shapeAvailable = huangAvailable | slopeChangeAvailable ...
        | lineFitAvailable | lineSlopeAvailable;
    shapeMemberVoteCount = uint8(huangEvidence) ...
        + uint8(slopeChangeEvidence) + uint8(lineFitEvidence) ...
        + uint8(lineSlopeEvidence);
    shapeEvidence = shapeMemberVoteCount >= 1;
    shapeSalientEvidence = shapeEvidence ...
        & (huangSalient | slopeChangeSalient ...
            | lineFitSalient | lineSlopeSalient);

    compressionMemberVoteCount = uint8(compressionMemberEvidence);
    compressionEvidence = compressionMemberVoteCount >= 1;
    compressionSalientEvidence = ...
        compressionEvidence & compressionMemberSalient;
    familyVoteCount = uint8(compressionEvidence) ...
        + uint8(verticalEvidence) + uint8(radialEvidence) ...
        + uint8(shapeEvidence);
    salientFamilyVoteCount = uint8(compressionSalientEvidence) ...
        + uint8(verticalSalientEvidence) ...
        + uint8(radialSalientEvidence) ...
        + uint8(shapeSalientEvidence);
    availableFamilyCount = uint8(compressionAvailable) ...
        + uint8(verticalAvailable) + uint8(radialAvailable) ...
        + uint8(shapeAvailable);
    continuitySupport = zeros(size(baseValid), "uint16");
    if parameters.enabled
        acceptedMask = baseValid ...
            & familyVoteCount >= parameters.minimumFamilyVotes;
        if parameters.saliencyEnabled
            acceptedMask = acceptedMask ...
                & salientFamilyVoteCount ...
                    >= parameters.minimumSalientFamilyVotes;
        end
        % A curb is a continuous structure, so its evidence arrives as a
        % connected patch of cells rather than as isolated responses. Cells
        % without enough accepted neighbours are dropped; the count excludes
        % the cell itself so a lone response can never satisfy its own test.
        %
        % This is off by default because it was measured to cost far more
        % than it earns. A curb is sampled along its length by successive
        % rings at successive azimuths, so a genuine curb cell often has
        % only one or two accepted neighbours inside a window of one ring
        % by four columns: over the 47 curb points a user reported as
        % missed in frame 929 the median support is 1. Requiring three
        % neighbours discards them while rejecting nothing, and standing
        % the rule down raises the development-label rate from 0.518 to
        % 0.591 with the false positives of frames 380 and 929 unchanged.
        % Continuity is enforced far better downstream, where the tracker
        % associates candidates along a fitted curve.
        if parameters.continuityMinimumNeighbors > 0
            continuitySupport = localNeighborhoodSupport( ...
                acceptedMask, ...
                parameters.continuityRingRadius, ...
                parameters.continuityAzimuthRadius);
            acceptedMask = acceptedMask ...
                & continuitySupport >= ...
                    parameters.continuityMinimumNeighbors;
        end
    else
        acceptedMask = baseValid;
    end

    diagnostics = struct( ...
        "compressionEvidence", compressionEvidence, ...
        "verticalEvidence", verticalEvidence, ...
        "radialEvidence", radialEvidence, ...
        "shapeEvidence", shapeEvidence, ...
        "compressionAvailable", compressionAvailable, ...
        "verticalAvailable", verticalAvailable, ...
        "radialAvailable", radialAvailable, ...
        "shapeAvailable", shapeAvailable, ...
        "compressionMemberVoteCount", compressionMemberVoteCount, ...
        "verticalMemberVoteCount", verticalMemberVoteCount, ...
        "radialMemberVoteCount", radialMemberVoteCount, ...
        "shapeMemberVoteCount", shapeMemberVoteCount, ...
        "compressionSalientEvidence", ...
            compressionSalientEvidence, ...
        "verticalSalientEvidence", verticalSalientEvidence, ...
        "radialSalientEvidence", radialSalientEvidence, ...
        "shapeSalientEvidence", shapeSalientEvidence, ...
        "continuitySupport", continuitySupport, ...
        "familyVoteCount", familyVoteCount, ...
        "salientFamilyVoteCount", salientFamilyVoteCount, ...
        "availableFamilyCount", availableFamilyCount, ...
        "baseValid", baseValid, ...
        "enabled", parameters.enabled, ...
        "minimumFamilyVotes", parameters.minimumFamilyVotes, ...
        "minimumRadialMemberVotes", ...
            parameters.minimumRadialMemberVotes, ...
        "saliencyEnabled", parameters.saliencyEnabled, ...
        "localHalfWidthBins", parameters.localHalfWidthBins, ...
        "localExclusionBins", parameters.localExclusionBins, ...
        "minimumLocalNeighborCount", ...
            parameters.minimumLocalNeighborCount, ...
        "localPercentileThreshold", ...
            parameters.localPercentileThreshold, ...
        "minimumSalientFamilyVotes", ...
            parameters.minimumSalientFamilyVotes, ...
        "thresholds", parameters.thresholds, ...
        "acceptedMask", acceptedMask);
end

function baseValid = localValidateFeatureSchema(features, featureValidity)
    if ~isstruct(features) || ~isscalar(features)
        error( ...
            "fuseLidarRingCurbFeatures:InvalidFeatures", ...
            "features must be a scalar structure.");
    end
    if ~isstruct(featureValidity) || ~isscalar(featureValidity)
        error( ...
            "fuseLidarRingCurbFeatures:InvalidValidity", ...
            "featureValidity must be a scalar structure.");
    end
    if ~isfield(featureValidity, "base")
        error( ...
            "fuseLidarRingCurbFeatures:MissingValidityField", ...
            "featureValidity must contain the base field.");
    end

    baseValid = featureValidity.base;
    if ~islogical(baseValid) || ~ismatrix(baseValid) || isempty(baseValid)
        error( ...
            "fuseLidarRingCurbFeatures:InvalidBaseValidity", ...
            "featureValidity.base must be a nonempty logical matrix.");
    end

    scalarFeatureNames = [ ...
        "hataCompressionNormalized", ...
        "heightStep", ...
        "localHeightRange", ...
        "wangHorizontalSpacingExcess", ...
        "radiusRatioReconstructionDeviation", ...
        "radialSecondDifference", ...
        "huangTangentialStrength", ...
        "sameRingSlopeChange", ...
        "ilpLineFitResidual", ...
        "ilpLineSlopeMagnitude"];
    scaleFeatureNames = [ ...
        "localMultiscaleHaarZ", ...
        "localMultiscaleHaarRange"];

    for fieldName = scalarFeatureNames
        localValidateScalarFeature( ...
            features, featureValidity, fieldName, size(baseValid));
    end
    for fieldName = scaleFeatureNames
        localValidateScaleFeature( ...
            features, featureValidity, fieldName, size(baseValid));
    end
end

function localValidateScalarFeature( ...
        features, featureValidity, fieldName, baseSize)
    localRequireFeatureFields(features, featureValidity, fieldName);
    featureValue = features.(fieldName);
    validityValue = featureValidity.(fieldName);
    if ~isnumeric(featureValue) || ~isreal(featureValue) ...
            || ~isequal(size(featureValue), baseSize)
        error( ...
            "fuseLidarRingCurbFeatures:InconsistentFeatureSize", ...
            "features.%s must be a real numeric matrix matching " + ...
            "featureValidity.base.", fieldName);
    end
    if ~islogical(validityValue) ...
            || ~isequal(size(validityValue), baseSize)
        error( ...
            "fuseLidarRingCurbFeatures:InconsistentValiditySize", ...
            "featureValidity.%s must be a logical matrix matching " + ...
            "featureValidity.base.", fieldName);
    end
end

function localValidateScaleFeature( ...
        features, featureValidity, fieldName, baseSize)
    localRequireFeatureFields(features, featureValidity, fieldName);
    featureValue = features.(fieldName);
    validityValue = featureValidity.(fieldName);
    featureSizeIsValid = isnumeric(featureValue) ...
        && isreal(featureValue) && ndims(featureValue) <= 3 ...
        && size(featureValue, 1) == baseSize(1) ...
        && size(featureValue, 2) == baseSize(2) ...
        && size(featureValue, 3) >= 1;
    if ~featureSizeIsValid
        error( ...
            "fuseLidarRingCurbFeatures:InconsistentFeatureSize", ...
            "features.%s must be a real numeric ring-by-bin-by-scale " + ...
            "array with at least one scale.", fieldName);
    end
    if ~islogical(validityValue) ...
            || ~isequal(size(validityValue), size(featureValue))
        error( ...
            "fuseLidarRingCurbFeatures:InconsistentValiditySize", ...
            "featureValidity.%s must be a logical array matching " + ...
            "features.%s.", fieldName, fieldName);
    end
end

function localRequireFeatureFields(features, featureValidity, fieldName)
    if ~isfield(features, fieldName)
        error( ...
            "fuseLidarRingCurbFeatures:MissingFeatureField", ...
            "features must contain the %s field.", fieldName);
    end
    if ~isfield(featureValidity, fieldName)
        error( ...
            "fuseLidarRingCurbFeatures:MissingValidityField", ...
            "featureValidity must contain the %s field.", fieldName);
    end
end

function parameters = localFusionParameters(cfg)
    if ~isstruct(cfg) || ~isscalar(cfg)
        error( ...
            "fuseLidarRingCurbFeatures:InvalidConfig", ...
            "cfg must be a scalar structure.");
    end
    allowedConfigFields = [ ...
        "enabled", ...
        "minimumFamilyVotes", ...
        "minimumRadialMemberVotes", ...
        "saliencyEnabled", ...
        "localHalfWidthBins", ...
        "localExclusionBins", ...
        "minimumLocalNeighborCount", ...
        "localPercentileThreshold", ...
        "minimumSalientFamilyVotes", ...
        "continuityRingRadius", ...
        "continuityAzimuthRadius", ...
        "continuityMinimumNeighbors", ...
        "thresholds"];
    unknownConfigFields = setdiff( ...
        string(fieldnames(cfg)), allowedConfigFields);
    if ~isempty(unknownConfigFields)
        error( ...
            "fuseLidarRingCurbFeatures:UnknownConfigField", ...
            "cfg contains the unsupported field %s.", ...
            unknownConfigFields(1));
    end

    thresholds = struct( ...
        "hataCompressionNormalized", 0.25, ...
        "heightStep", 0.005, ...
        "localHeightRange", 0.01875, ...
        "localMultiscaleHaarZ", 0.01125, ...
        "wangHorizontalSpacingExcess", 0.005625, ...
        "radiusRatioReconstructionDeviation", 1.0e-4, ...
        "radialSecondDifference", 0.009375, ...
        "localMultiscaleHaarRange", 0.045, ...
        "huangTangentialStrength", 0.1125, ...
        "sameRingSlopeChange", 0.0035, ...
        "ilpLineFitResidual", 0.00325, ...
        "ilpLineSlopeMagnitude", 0.025);

    enabled = true;
    if isfield(cfg, "enabled")
        if ~islogical(cfg.enabled) || ~isscalar(cfg.enabled)
            error( ...
                "fuseLidarRingCurbFeatures:InvalidEnabled", ...
                "cfg.enabled must be a logical scalar.");
        end
        enabled = cfg.enabled;
    end

    minimumFamilyVotes = localIntegerConfigValue( ...
        cfg, "minimumFamilyVotes", 2, 1, 4, ...
        "InvalidMinimumFamilyVotes");
    minimumRadialMemberVotes = localIntegerConfigValue( ...
        cfg, "minimumRadialMemberVotes", 2, 1, 4, ...
        "InvalidMinimumRadialMemberVotes");

    saliencyEnabled = true;
    if isfield(cfg, "saliencyEnabled")
        if ~islogical(cfg.saliencyEnabled) ...
                || ~isscalar(cfg.saliencyEnabled)
            error( ...
                "fuseLidarRingCurbFeatures:InvalidSaliencyEnabled", ...
                "cfg.saliencyEnabled must be a logical scalar.");
        end
        saliencyEnabled = cfg.saliencyEnabled;
    end

    localHalfWidthBins = localIntegerConfigValue( ...
        cfg, "localHalfWidthBins", 33, 1, Inf, ...
        "InvalidLocalHalfWidthBins");
    localExclusionBins = localIntegerConfigValue( ...
        cfg, "localExclusionBins", 3, 0, Inf, ...
        "InvalidLocalExclusionBins");
    if localExclusionBins >= localHalfWidthBins
        error( ...
            "fuseLidarRingCurbFeatures:InvalidLocalWindow", ...
            "cfg.localExclusionBins must be smaller than " + ...
            "cfg.localHalfWidthBins.");
    end
    maximumNeighborCount = 2 * ( ...
        localHalfWidthBins - max(localExclusionBins, 1) + 1);
    minimumLocalNeighborCount = localIntegerConfigValue( ...
        cfg, "minimumLocalNeighborCount", 12, 1, ...
        maximumNeighborCount, "InvalidMinimumLocalNeighborCount");
    localPercentileThreshold = localBoundedScalarConfigValue( ...
        cfg, "localPercentileThreshold", 0.5, 0.0, 1.0, ...
        "InvalidLocalPercentileThreshold");
    minimumSalientFamilyVotes = localIntegerConfigValue( ...
        cfg, "minimumSalientFamilyVotes", 2, 1, 4, ...
        "InvalidMinimumSalientFamilyVotes");
    continuityRingRadius = localIntegerConfigValue( ...
        cfg, "continuityRingRadius", 1, 0, Inf, ...
        "InvalidContinuityRingRadius");
    continuityAzimuthRadius = localIntegerConfigValue( ...
        cfg, "continuityAzimuthRadius", 4, 0, Inf, ...
        "InvalidContinuityAzimuthRadius");
    maximumContinuityNeighbors = ...
        (2 * continuityRingRadius + 1) ...
        * (2 * continuityAzimuthRadius + 1) - 1;
    continuityMinimumNeighbors = localIntegerConfigValue( ...
        cfg, "continuityMinimumNeighbors", 0, 0, ...
        max(0, maximumContinuityNeighbors), ...
        "InvalidContinuityMinimumNeighbors");

    if isfield(cfg, "thresholds")
        thresholds = localOverrideThresholds(thresholds, cfg.thresholds);
    end
    parameters = struct( ...
        "enabled", enabled, ...
        "minimumFamilyVotes", uint8(minimumFamilyVotes), ...
        "minimumRadialMemberVotes", ...
            uint8(minimumRadialMemberVotes), ...
        "saliencyEnabled", saliencyEnabled, ...
        "localHalfWidthBins", localHalfWidthBins, ...
        "localExclusionBins", localExclusionBins, ...
        "minimumLocalNeighborCount", minimumLocalNeighborCount, ...
        "localPercentileThreshold", localPercentileThreshold, ...
        "minimumSalientFamilyVotes", ...
            uint8(minimumSalientFamilyVotes), ...
        "continuityRingRadius", continuityRingRadius, ...
        "continuityAzimuthRadius", continuityAzimuthRadius, ...
        "continuityMinimumNeighbors", continuityMinimumNeighbors, ...
        "thresholds", thresholds);
end

function support = localNeighborhoodSupport( ...
        mask, ringRadius, azimuthRadius)
%LOCALNEIGHBORHOODSUPPORT Accepted neighbours per cell, excluding itself.
%   Azimuth wraps circularly through 360 degrees; rings do not wrap.
    counts = zeros(size(mask));
    numericMask = double(mask);
    for azimuthOffset = -azimuthRadius:azimuthRadius
        shifted = circshift(numericMask, [0, azimuthOffset]);
        if ringRadius > 0
            shifted = movsum(shifted, [ringRadius, ringRadius], 1);
        end
        counts = counts + shifted;
    end
    support = uint16(max(0, counts - numericMask));
end

function value = localIntegerConfigValue( ...
        cfg, fieldName, defaultValue, lowerBound, upperBound, errorName)
    value = defaultValue;
    if ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    if ~isnumeric(candidate) || ~isreal(candidate) ...
            || ~isscalar(candidate) || ~isfinite(candidate) ...
            || candidate ~= floor(candidate) ...
            || candidate < lowerBound || candidate > upperBound
        error( ...
            "fuseLidarRingCurbFeatures:" + errorName, ...
            "cfg.%s must be an integer in [%g, %g].", ...
            fieldName, lowerBound, upperBound);
    end
    value = double(candidate);
end

function value = localBoundedScalarConfigValue( ...
        cfg, fieldName, defaultValue, lowerBound, upperBound, errorName)
    value = defaultValue;
    if ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    if ~isnumeric(candidate) || ~isreal(candidate) ...
            || ~isscalar(candidate) || ~isfinite(candidate) ...
            || candidate < lowerBound || candidate > upperBound
        error( ...
            "fuseLidarRingCurbFeatures:" + errorName, ...
            "cfg.%s must be a finite real numeric scalar in [%g, %g].", ...
            fieldName, lowerBound, upperBound);
    end
    value = double(candidate);
end

function thresholds = localOverrideThresholds(thresholds, overrides)
    if ~isstruct(overrides) || ~isscalar(overrides)
        error( ...
            "fuseLidarRingCurbFeatures:InvalidThresholds", ...
            "cfg.thresholds must be a scalar structure.");
    end
    knownFields = string(fieldnames(thresholds));
    overrideFields = string(fieldnames(overrides));
    unknownFields = setdiff(overrideFields, knownFields);
    if ~isempty(unknownFields)
        error( ...
            "fuseLidarRingCurbFeatures:UnknownThreshold", ...
            "cfg.thresholds contains the unsupported field %s.", ...
            unknownFields(1));
    end
    for fieldName = overrideFields.'
        candidate = overrides.(fieldName);
        if ~isnumeric(candidate) || ~isreal(candidate) ...
                || ~isscalar(candidate) || ~isfinite(candidate) ...
                || candidate < 0
            error( ...
                "fuseLidarRingCurbFeatures:InvalidThreshold", ...
                "cfg.thresholds.%s must be a finite nonnegative " + ...
                "numeric scalar.", fieldName);
        end
        thresholds.(fieldName) = double(candidate);
    end
end

function [available, evidence, salient] = localMemberMasks( ...
        featureValue, validityValue, baseValid, threshold, parameters)
    available = baseValid & validityValue & isfinite(featureValue);
    evidence = available & featureValue >= threshold;
    salient = false(size(evidence));
    if ~(parameters.enabled && parameters.saliencyEnabled) ...
            || ~any(evidence, "all")
        return;
    end
    percentile = localCircularPercentile( ...
        featureValue, available, parameters.localHalfWidthBins, ...
        parameters.localExclusionBins, ...
        parameters.minimumLocalNeighborCount);
    salient = evidence ...
        & percentile >= parameters.localPercentileThreshold;
end

function percentile = localCircularPercentile( ...
        values, valid, halfWidthBins, exclusionBins, minimumCount)
    lowerCount = zeros(size(values), "uint16");
    equalCount = zeros(size(values), "uint16");
    neighborCount = zeros(size(values), "uint16");
    offsets = [ ...
        -halfWidthBins:-exclusionBins, ...
        exclusionBins:halfWidthBins];
    offsets(offsets == 0) = [];
    wrappedOffsets = unique( ...
        mod(offsets, size(values, 2)), "stable");
    wrappedOffsets(wrappedOffsets == 0) = [];
    for offset = wrappedOffsets
        neighborValue = circshift(values, [0, offset]);
        neighborValid = circshift(valid, [0, offset]) ...
            & isfinite(neighborValue);
        neighborCount = neighborCount + uint16(neighborValid);
        lowerCount = lowerCount + uint16( ...
            neighborValid & neighborValue < values);
        equalCount = equalCount + uint16( ...
            neighborValid & neighborValue == values);
    end
    percentile = ( ...
        single(lowerCount) + 0.5*single(equalCount)) ...
        ./ max(single(neighborCount), 1.0);
    percentile(~valid | neighborCount < minimumCount) = NaN;
end
