function processingResult = groundPointsProcessing(frame, cfg)
%GROUNDPOINTSPROCESSING Extract curb points from organized LiDAR.
%   PROCESSINGRESULT = GROUNDPOINTSPROCESSING(FRAME, CFG) detects curb
%   boundaries in four stages:
%
%   1. Find downward height transitions across one or more LiDAR rings.
%   2. Estimate a road-aligned frame from the candidate structure.
%   3. Fit each side's curb curve as the plain least-squares quadratic of
%      its candidate points (Wang et al., 2019).
%   4. Recover low points in a narrow band around the fitted geometry.
%
%   Allowing a small ring gap is important for ray-traced CARLA clouds, where
%   a valid return is often absent between the curb top and the road surface.
%
%   FRAME fields are organized as [ring x azimuth]:
%       x, y, z, range             Required numeric matrices.
%       valid                      Optional logical validity matrix.
%
%   CFG is optional. The following lower-camel-case fields override defaults:
%       curbMaxZ                    -1.5 m
%       curbMinVerticalDrop          0.015 m
%       curbMaxVerticalDrop          0.25 m
%       curbMaxRingGap               3 rings
%       curbMinRangeStep            -0.05 m
%       curbMaxRangeStep             0.75 m
%       curbOuterRecoveryMaxRangeStep 1.50 m
%       curbRangeStepSpacingFactor   0.9
%       curbRangeGapFloor            0.02 m
%       curbMinDropRangeRatio        0.005
%       curbMinLateralDistance       2.5 m
%       curbMaxLateralDistance      15.0 m
%       curbRingFeatureFusionEnabled automatic for the calibrated
%                                      64-by-1000 CARLA LiDAR layout
%       curbRingFeatureMinimumFamilyVotes 2 of 4 feature families
%       curbRingFeatureMinimumRadialMemberVotes 2 of 4 radial members
%       curbRingFeatureSaliencyEnabled true
%       curbRingFeatureLocalHalfWidthBins 33 azimuth bins
%       curbRingFeatureLocalExclusionBins 3 azimuth bins
%       curbRingFeatureMinimumLocalNeighborCount 12 samples
%       curbRingFeatureLocalPercentileThreshold 0.50
%       curbRingFeatureMinimumSalientFamilyVotes 2 of 4 families
%       curbRingFeatureOrientationMinimumFamilyVotes 3 of 4 families
%       curbRingFeatureOrientationRequireCompression false
%       curbRingFeatureCandidateGatingEnabled false
%       curbRingFeatureThresholds    optional threshold-override struct
%       curbRoadHeadingDegrees       automatic, degrees in sensor frame
%       curbRoadHeadingPriorDegrees  optional temporal prior, degrees
%       curbRoadHeadingPriorToleranceDegrees 20 degrees
%       curbOrientationSearchStepDegrees 1.0 degree
%       curbOrientationMaximumRange 45.0 m
%       curbOrientationSeedDistanceTolerance 0.30 m
%       curbOrientationMinimumLineSupport 20 azimuths
%       curbMinimumRoadWidth         6.0 m
%       curbMaximumRoadWidth        30.0 m
%       curbInterceptBinWidth        0.08 m
%       curbSeedDistanceTolerance    0.12 m
%       curbMinimumLineSupport      15 azimuths
%       curbMinimumLineSpan          5.0 m
%       curbSpanScoreWeight          2.0 score/m
%       curbSpanScoreSaturation     30.0 m
%       curbExpansionDistance        0.27 m
%       curbExpansionLongitudinalMargin 1.2 m
%       curbExpansionHeightMargin    0.20 m
%       curbExpansionTopSurfaceDistance 0.45 m
%       curbExpansionTopSurfaceHeightOffset 0.02 m
%       curbExpansionTopSurfaceAzimuthRadius 3 columns
%       curbExpansionTopSurfaceRingRadius 1 ring
%       curbForwardCurveExpansionDistance 0.30 m
%       curbForwardCurveExpansionLongitudinalMargin 3.6 m
%
%   Output indices use [azimuth, ring]. The output fields are:
%       left, right  Curb points classified by road-frame lateral sign.
%       curbs        Combined curb points.
%       curbModels   Fitted boundaries and road-frame diagnostics.

    if nargin < 2 || isempty(cfg)
        cfg = struct();
    end

    [numRings, numAzimuths] = size(frame.z);
    emptyIndices = zeros(0, 2);
    emptyModel = emptyCurbBoundaryModel();
    if numRings < 2 || numAzimuths < 1
        processingResult = localEmptyResult( ...
            emptyIndices, emptyModel, ...
            localEmptyRingFeatureFusionSummary( ...
                false, "insufficient-frame"));
        return;
    end

    x = double(frame.x);
    y = double(frame.y);
    z = double(frame.z);
    range = double(frame.range);
    valid = isfinite(x) & isfinite(y) & isfinite(z) & isfinite(range);
    if isfield(frame, "valid")
        valid = valid & logical(frame.valid);
    end

    maxCurbZ = min(-1.5, localConfigValue(cfg, "curbMaxZ", -1.5));
    minVerticalDrop = localConfigValue( ...
        cfg, "curbMinVerticalDrop", 0.015);
    maxVerticalDrop = localConfigValue( ...
        cfg, "curbMaxVerticalDrop", 0.25);
    maxRingGap = max(1, floor(localConfigValue( ...
        cfg, "curbMaxRingGap", 3)));
    maxRingGap = min(maxRingGap, numRings - 1);
    minRangeStep = localConfigValue(cfg, "curbMinRangeStep", -0.05);
    maxRangeStep = localConfigValue(cfg, "curbMaxRangeStep", 0.75);
    outerRecoveryMaxRangeStep = max(maxRangeStep, localConfigValue( ...
        cfg, "curbOuterRecoveryMaxRangeStep", 1.50));
    rangeStepSpacingFactor = max(0.0, localConfigValue( ...
        cfg, "curbRangeStepSpacingFactor", 0.9));
    rangeGapFloor = max(eps, localConfigValue( ...
        cfg, "curbRangeGapFloor", 0.02));
    minDropRangeRatio = max(0.0, localConfigValue( ...
        cfg, "curbMinDropRangeRatio", 0.005));
    minLateralDistance = max(0.0, localConfigValue( ...
        cfg, "curbMinLateralDistance", 2.5));
    maxLateralDistance = max(minLateralDistance, localConfigValue( ...
        cfg, "curbMaxLateralDistance", 15.0));
    [ringFeatureFusionEnabled, ringFeatureActivationSource] = ...
        localRingFeatureFusionActivation( ...
            cfg, numRings, numAzimuths);
    ringFeatureGate = true(size(valid));
    ringFeatureAvailableFamilyCount = zeros(size(valid), "uint8");
    ringFeatureFamilyVoteCount = zeros(size(valid), "uint8");
    ringFeatureCompressionEvidence = false(size(valid));
    ringFeatureFusionSummary = localEmptyRingFeatureFusionSummary( ...
        ringFeatureFusionEnabled, ringFeatureActivationSource);
    ringFeatureFusionSummary.orientationMinimumFamilyVotes = ...
        max(1, min(4, floor(localConfigValue( ...
            cfg, ...
            "curbRingFeatureOrientationMinimumFamilyVotes", ...
            3))));
    ringFeatureFusionSummary.orientationRequireCompression = ...
        localLogicalConfigValue( ...
            cfg, ...
            "curbRingFeatureOrientationRequireCompression", ...
            false);
    ringFeatureFusionSummary.candidateGatingEnabled = ...
        localLogicalConfigValue( ...
            cfg, ...
            "curbRingFeatureCandidateGatingEnabled", ...
            false);
    if ringFeatureFusionEnabled
        [ringFeatures, ringFeatureValidity] = ...
            computeLidarRingCurbFeatures(frame, cfg);
        ringFeatureFusionConfig = localRingFeatureFusionConfig(cfg);
        [ringFeatureGate, ringFeatureDiagnostics] = ...
            fuseLidarRingCurbFeatures( ...
                ringFeatures, ringFeatureValidity, ...
                ringFeatureFusionConfig);
        ringFeatureAvailableFamilyCount = ...
            ringFeatureDiagnostics.availableFamilyCount;
        ringFeatureFamilyVoteCount = ...
            ringFeatureDiagnostics.familyVoteCount;
        ringFeatureCompressionEvidence = ...
            ringFeatureDiagnostics.compressionEvidence;
        ringFeatureFusionSummary.minimumFamilyVotes = ...
            double(ringFeatureDiagnostics.minimumFamilyVotes);
        ringFeatureFusionSummary.minimumRadialMemberVotes = ...
            double(ringFeatureDiagnostics.minimumRadialMemberVotes);
        ringFeatureFusionSummary.saliencyEnabled = ...
            ringFeatureDiagnostics.saliencyEnabled;
        ringFeatureFusionSummary.localHalfWidthBins = ...
            ringFeatureDiagnostics.localHalfWidthBins;
        ringFeatureFusionSummary.localExclusionBins = ...
            ringFeatureDiagnostics.localExclusionBins;
        ringFeatureFusionSummary.minimumLocalNeighborCount = ...
            ringFeatureDiagnostics.minimumLocalNeighborCount;
        ringFeatureFusionSummary.localPercentileThreshold = ...
            ringFeatureDiagnostics.localPercentileThreshold;
        ringFeatureFusionSummary.minimumSalientFamilyVotes = ...
            double(ringFeatureDiagnostics.minimumSalientFamilyVotes);
        ringFeatureFusionSummary.thresholds = ...
            ringFeatureDiagnostics.thresholds;
        ringFeatureFusionSummary.validCellCount = ...
            nnz(ringFeatureDiagnostics.baseValid);
        ringFeatureFusionSummary.acceptedCellCount = ...
            nnz(ringFeatureGate);
    end

    fittingParameters = struct( ...
        "interceptBinWidth", max(eps, localConfigValue( ...
            cfg, "curbInterceptBinWidth", 0.08)), ...
        "seedDistanceTolerance", max(eps, localConfigValue( ...
            cfg, "curbSeedDistanceTolerance", 0.12)), ...
        "minimumLineSupport", max(2, floor(localConfigValue( ...
            cfg, "curbMinimumLineSupport", 15))), ...
        "minimumLineSpan", max(0.0, localConfigValue( ...
            cfg, "curbMinimumLineSpan", 5.0)), ...
        "spanScoreWeight", max(0.0, localConfigValue( ...
            cfg, "curbSpanScoreWeight", 2.0)), ...
        "spanScoreSaturation", max(eps, localConfigValue( ...
            cfg, "curbSpanScoreSaturation", 30.0)));
    orientationParameters = struct( ...
        "searchStepDegrees", max(0.25, localConfigValue( ...
            cfg, "curbOrientationSearchStepDegrees", 1.0)), ...
        "maximumRange", max(maxLateralDistance, localConfigValue( ...
            cfg, "curbOrientationMaximumRange", 45.0)), ...
        "minimumRoadWidth", max(2.0 * minLateralDistance, ...
            localConfigValue(cfg, "curbMinimumRoadWidth", 6.0)), ...
        "maximumRoadWidth", max(2.0 * minLateralDistance, ...
            localConfigValue(cfg, "curbMaximumRoadWidth", 30.0)), ...
        "minimumLateralDistance", minLateralDistance, ...
        "maximumLateralDistance", maxLateralDistance, ...
        "interceptBinWidth", fittingParameters.interceptBinWidth, ...
        "seedDistanceTolerance", max( ...
            fittingParameters.seedDistanceTolerance, ...
            localConfigValue( ...
                cfg, "curbOrientationSeedDistanceTolerance", 0.30)), ...
        "minimumLineSupport", max(2, floor(localConfigValue( ...
            cfg, "curbOrientationMinimumLineSupport", 20))), ...
        "minimumLineSpan", fittingParameters.minimumLineSpan, ...
        "spanScoreWeight", fittingParameters.spanScoreWeight, ...
        "spanScoreSaturation", fittingParameters.spanScoreSaturation);
    orientationParameters.maximumRoadWidth = max( ...
        orientationParameters.minimumRoadWidth, ...
        orientationParameters.maximumRoadWidth);

    expansionDistance = max(eps, localConfigValue( ...
        cfg, "curbExpansionDistance", 0.27));
    expansionLongitudinalMargin = max(0.0, localConfigValue( ...
        cfg, "curbExpansionLongitudinalMargin", 1.2));
    expansionHeightMargin = max(0.0, localConfigValue( ...
        cfg, "curbExpansionHeightMargin", 0.20));
    expansionTopSurfaceDistance = max(expansionDistance, ...
        localConfigValue(cfg, "curbExpansionTopSurfaceDistance", 0.45));
    expansionTopSurfaceHeightOffset = max(0.0, localConfigValue( ...
        cfg, "curbExpansionTopSurfaceHeightOffset", 0.02));
    expansionTopSurfaceAzimuthRadius = max(0, floor(localConfigValue( ...
        cfg, "curbExpansionTopSurfaceAzimuthRadius", 3)));
    expansionTopSurfaceRingRadius = max(0, floor(localConfigValue( ...
        cfg, "curbExpansionTopSurfaceRingRadius", 1)));
    curveExpansionDistance = max(eps, localConfigValue( ...
        cfg, "curbForwardCurveExpansionDistance", 0.30));
    curveExpansionLongitudinalMargin = max(0.0, localConfigValue( ...
        cfg, ...
        "curbForwardCurveExpansionLongitudinalMargin", ...
        3.6));

    seedLinearIndices = zeros(0, 1);
    seedAzimuthIndices = zeros(0, 1);
    orientationSeedLinearIndices = zeros(0, 1);
    orientationSeedAzimuthIndices = zeros(0, 1);
    orientationSeedWeights = zeros(0, 1);
    for ringGap = 1:maxRingGap
        upperRows = 1:(numRings - ringGap);
        lowerRows = (1 + ringGap):numRings;
        pairValid = valid(upperRows, :) & valid(lowerRows, :) & ...
            z(upperRows, :) <= maxCurbZ & ...
            z(lowerRows, :) <= maxCurbZ;

        verticalDrop = z(upperRows, :) - z(lowerRows, :);
        rangeStep = range(upperRows, :) - range(lowerRows, :);
        dropRangeRatio = verticalDrop ./ ...
            max(abs(rangeStep), rangeGapFloor);
        pairRadialDistance = hypot( ...
            0.5 * (x(upperRows, :) + x(lowerRows, :)), ...
            0.5 * (y(upperRows, :) + y(lowerRows, :)));

        candidateBaseMask = pairValid & ...
            verticalDrop >= minVerticalDrop & ...
            verticalDrop <= maxVerticalDrop & ...
            rangeStep >= minRangeStep & ...
            dropRangeRatio >= minDropRangeRatio & ...
            pairRadialDistance >= minLateralDistance & ...
            pairRadialDistance <= orientationParameters.maximumRange;
        % Consecutive beams land farther apart the farther they reach, so a
        % fixed radial-step cap silently stops accepting any pair once the
        % flat-ground spacing alone exceeds it. The typical spacing of this
        % ring pair across the sweep is that flat-ground expectation, and a
        % curb shortens the far beam, so its pair reads back a fraction of
        % that spacing. Scaling the cap by the observed spacing therefore
        % keeps the compression test meaningful at any range, while the
        % below-one factor still rejects a uniform grade that merely spans a
        % wide radial gap.
        expectedRingSpacing = localExpectedRingSpacing( ...
            rangeStep, pairValid, maxRangeStep);
        adaptiveMaxRangeStep = max( ...
            maxRangeStep, rangeStepSpacingFactor * expectedRingSpacing);
        adaptiveOuterRecoveryMaxRangeStep = max( ...
            outerRecoveryMaxRangeStep, ...
            rangeStepSpacingFactor * expectedRingSpacing);
        legacyCandidateMask = candidateBaseMask ...
            & rangeStep <= adaptiveMaxRangeStep;
        legacyOuterRecoveryCandidateMask = candidateBaseMask ...
            & rangeStep <= adaptiveOuterRecoveryMaxRangeStep;
        if ringFeatureFusionEnabled
            upperFeatureGate = ringFeatureGate(upperRows, :);
            lowerFeatureGate = ringFeatureGate(lowerRows, :);
            insufficientFeatureCoverage = ...
                max( ...
                    ringFeatureAvailableFamilyCount(upperRows, :), ...
                    ringFeatureAvailableFamilyCount(lowerRows, :)) ...
                < ringFeatureFusionSummary.minimumFamilyVotes;
            featureEligible = ...
                upperFeatureGate | lowerFeatureGate ...
                | insufficientFeatureCoverage;
            if ringFeatureFusionSummary.candidateGatingEnabled
                candidateMask = ...
                    legacyCandidateMask & featureEligible;
                outerRecoveryCandidateMask = ...
                    legacyOuterRecoveryCandidateMask ...
                    & featureEligible;
            else
                candidateMask = legacyCandidateMask;
                outerRecoveryCandidateMask = ...
                    legacyOuterRecoveryCandidateMask;
            end
            orientationFeatureGate = ...
                max( ...
                    ringFeatureFamilyVoteCount(upperRows, :), ...
                    ringFeatureFamilyVoteCount(lowerRows, :)) ...
                >= ringFeatureFusionSummary ...
                    .orientationMinimumFamilyVotes ...
                & (upperFeatureGate | lowerFeatureGate);
            if ringFeatureFusionSummary.orientationRequireCompression
                orientationFeatureGate = orientationFeatureGate ...
                    & (ringFeatureCompressionEvidence(upperRows, :) ...
                        | ringFeatureCompressionEvidence( ...
                            lowerRows, :));
            end
            orientationCandidateMask = ...
                legacyCandidateMask & orientationFeatureGate;
            ringFeatureFusionSummary.coverageFallbackCandidateCount = ...
                ringFeatureFusionSummary.coverageFallbackCandidateCount ...
                + nnz(legacyCandidateMask ...
                    & insufficientFeatureCoverage);
        else
            candidateMask = legacyCandidateMask;
            outerRecoveryCandidateMask = ...
                legacyOuterRecoveryCandidateMask;
            orientationCandidateMask = legacyCandidateMask;
        end
        ringFeatureFusionSummary.legacyCandidateCount = ...
            ringFeatureFusionSummary.legacyCandidateCount ...
            + nnz(legacyCandidateMask);
        ringFeatureFusionSummary.acceptedCandidateCount = ...
            ringFeatureFusionSummary.acceptedCandidateCount ...
            + nnz(candidateMask);
        ringFeatureFusionSummary.legacyOuterRecoveryCandidateCount = ...
            ringFeatureFusionSummary.legacyOuterRecoveryCandidateCount ...
            + nnz(legacyOuterRecoveryCandidateMask);
        ringFeatureFusionSummary.acceptedOuterRecoveryCandidateCount = ...
            ringFeatureFusionSummary.acceptedOuterRecoveryCandidateCount ...
            + nnz(outerRecoveryCandidateMask);
        ringFeatureFusionSummary.orientationCandidateCount = ...
            ringFeatureFusionSummary.orientationCandidateCount ...
            + nnz(orientationCandidateMask);

        [candidateUpperRing, candidateAzimuth] = find(candidateMask);
        candidateLowerRing = candidateUpperRing + ringGap;
        candidateLinearIndices = sub2ind( ...
            [numRings, numAzimuths], ...
            candidateLowerRing, candidateAzimuth);
        seedLinearIndices = [ ...
            seedLinearIndices; candidateLinearIndices]; %#ok<AGROW>
        seedAzimuthIndices = [ ...
            seedAzimuthIndices; candidateAzimuth]; %#ok<AGROW>

        [orientationUpperRing, orientationAzimuth] = find( ...
            orientationCandidateMask);
        orientationLowerRing = orientationUpperRing + ringGap;
        orientationLinearIndices = sub2ind( ...
            [numRings, numAzimuths], ...
            orientationLowerRing, orientationAzimuth);
        orientationUpperLinearIndices = sub2ind( ...
            [numRings, numAzimuths], ...
            orientationUpperRing, orientationAzimuth);
        orientationWeights = double(max( ...
            ringFeatureFamilyVoteCount( ...
                orientationUpperLinearIndices), ...
            ringFeatureFamilyVoteCount( ...
                orientationLinearIndices)));
        orientationSeedLinearIndices = [ ...
            orientationSeedLinearIndices; ...
            orientationLinearIndices]; %#ok<AGROW>
        orientationSeedAzimuthIndices = [ ...
            orientationSeedAzimuthIndices; ...
            orientationAzimuth]; %#ok<AGROW>
        orientationSeedWeights = [ ...
            orientationSeedWeights; ...
            orientationWeights]; %#ok<AGROW>

    end

    sensorX = x;
    sensorY = y;
    minimumOrientationSeedCount = ...
        orientationParameters.minimumLineSupport;
    useStrictOrientationSeeds = ringFeatureFusionEnabled ...
        && numel(orientationSeedLinearIndices) ...
            >= minimumOrientationSeedCount;
    if useStrictOrientationSeeds
        roadFrameSeedLinearIndices = ...
            orientationSeedLinearIndices;
        roadFrameSeedAzimuthIndices = ...
            orientationSeedAzimuthIndices;
        ringFeatureFusionSummary.orientationSeedSource = ...
            "strict-family-consensus";
    else
        roadFrameSeedLinearIndices = seedLinearIndices;
        roadFrameSeedAzimuthIndices = seedAzimuthIndices;
        if ringFeatureFusionEnabled
            ringFeatureFusionSummary.orientationSeedSource = ...
                "coverage-fallback";
        else
            ringFeatureFusionSummary.orientationSeedSource = ...
                "legacy";
        end
    end
    configuredHeading = localOptionalConfigValue( ...
        cfg, "curbRoadHeadingDegrees");
    dominantHeadingFound = false;
    if useStrictOrientationSeeds && ~isfinite(configuredHeading)
        dominantHeading = estimateRoadHeadingFromFeatureSeeds( ...
            sensorX(orientationSeedLinearIndices), ...
            sensorY(orientationSeedLinearIndices), ...
            orientationSeedAzimuthIndices, ...
            orientationSeedWeights, ...
            localDominantHeadingConfig( ...
                cfg, orientationParameters));
        if dominantHeading.found
            roadFrame = localRoadFrameFromDominantHeading( ...
                dominantHeading);
            dominantHeadingFound = true;
            ringFeatureFusionSummary.orientationSeedSource = ...
                "strict-family-dominant-line";
        end
    end
    if ~dominantHeadingFound
        roadFrame = localEstimateRoadFrame( ...
            sensorX(roadFrameSeedLinearIndices), ...
            sensorY(roadFrameSeedLinearIndices), ...
            roadFrameSeedAzimuthIndices, cfg, ...
            orientationParameters);
    end
    [x, y] = localTransformToRoadFrame( ...
        sensorX, sensorY, roadFrame.headingDegrees);

    if ~isempty(seedLinearIndices)
        seedLateralDistance = abs(y(seedLinearIndices));
        usableSeed = ...
            seedLateralDistance >= minLateralDistance ...
            & seedLateralDistance <= maxLateralDistance;
        seedLinearIndices = seedLinearIndices(usableSeed);
        seedAzimuthIndices = seedAzimuthIndices(usableSeed);
    end

    if isempty(seedLinearIndices)
        seedX = zeros(0, 1);
        seedY = zeros(0, 1);
        seedZ = zeros(0, 1);
        seedAzimuthIndices = zeros(0, 1);
    else
        seedX = x(seedLinearIndices);
        seedY = y(seedLinearIndices);
        seedZ = z(seedLinearIndices);
    end

    % Positive road-frame lateral position is reported as the right side.
    % Each side's curb curve is the plain least-squares quadratic fitted
    % to that side's candidate points (Wang et al., 2019). The line models
    % stay empty; the quadratic is the single fitted representation.
    leftModel = emptyModel;
    rightModel = emptyModel;
    leftSelector = seedY < 0;
    rightSelector = seedY > 0;
    leftForwardModel = localLeastSquaresQuadratic( ...
        seedX(leftSelector), seedY(leftSelector), ...
        seedZ(leftSelector), seedAzimuthIndices(leftSelector), ...
        fittingParameters);
    rightForwardModel = localLeastSquaresQuadratic( ...
        seedX(rightSelector), seedY(rightSelector), ...
        seedZ(rightSelector), seedAzimuthIndices(rightSelector), ...
        fittingParameters);

    leftMask = localExpandBoundaryPair( ...
        leftModel, leftForwardModel, x, y, z, valid, maxCurbZ, ...
        expansionDistance, curveExpansionDistance, ...
        expansionLongitudinalMargin, ...
        curveExpansionLongitudinalMargin, ...
        expansionHeightMargin, ...
        expansionTopSurfaceDistance, ...
        expansionTopSurfaceHeightOffset, ...
        expansionTopSurfaceAzimuthRadius, ...
        expansionTopSurfaceRingRadius);
    rightMask = localExpandBoundaryPair( ...
        rightModel, rightForwardModel, x, y, z, valid, maxCurbZ, ...
        expansionDistance, curveExpansionDistance, ...
        expansionLongitudinalMargin, ...
        curveExpansionLongitudinalMargin, ...
        expansionHeightMargin, ...
        expansionTopSurfaceDistance, ...
        expansionTopSurfaceHeightOffset, ...
        expansionTopSurfaceAzimuthRadius, ...
        expansionTopSurfaceRingRadius);
    curbMask = leftMask | rightMask;

    [curbRing, curbAzimuth] = find(curbMask);
    [leftRing, leftAzimuth] = find(leftMask);
    [rightRing, rightAzimuth] = find(rightMask);
    curbPoints = sortrows([curbAzimuth, curbRing], [1, 2]);
    leftIndices = sortrows([leftAzimuth, leftRing], [1, 2]);
    rightIndices = sortrows([rightAzimuth, rightRing], [1, 2]);

    processingResult.left = leftIndices;
    processingResult.right = rightIndices;
    processingResult.curbs = curbPoints;
    processingResult.curbModels = struct( ...
        "left", leftModel, ...
        "right", rightModel, ...
        "leftForward", leftForwardModel, ...
        "rightForward", rightForwardModel, ...
        "roadFrame", roadFrame, ...
        "ringFeatureFusion", ringFeatureFusionSummary);
end

function model = localLeastSquaresQuadratic( ...
        seedX, seedY, seedZ, seedAzimuthIndices, parameters)
%LOCALLEASTSQUARESQUADRATIC Least-squares quadratic curb curve of one side.
%   The curb curve is the plain least-squares quadratic
%   y = curvature*x^2 + slope*x + intercept over the side's candidate
%   points (Wang et al., 2019, Sec. VII-A). A side without enough support
%   or longitudinal span carries no model.
    model = emptyCurbBoundaryModel();
    seedX = reshape(double(seedX), [], 1);
    seedY = reshape(double(seedY), [], 1);
    seedZ = reshape(double(seedZ), [], 1);
    support = numel(unique(seedAzimuthIndices));
    span = 0.0;
    if ~isempty(seedX)
        span = max(seedX) - min(seedX);
    end
    if numel(seedX) < 3 ...
            || support < parameters.minimumLineSupport ...
            || span < parameters.minimumLineSpan
        return;
    end
    coefficients = polyfit(seedX, seedY, 2);
    if any(~isfinite(coefficients))
        return;
    end
    model.found = true;
    model.curvature = coefficients(1);
    model.slope = coefficients(2);
    model.intercept = coefficients(3);
    model.minimumX = min(seedX);
    model.maximumX = max(seedX);
    model.minimumZ = min(seedZ);
    model.maximumZ = max(seedZ);
    model.azimuthSupport = support;
    model.longitudinalSpan = span;
    model.score = support + parameters.spanScoreWeight ...
        * min(span, parameters.spanScoreSaturation);
end

function spacing = localExpectedRingSpacing( ...
        rangeStep, pairValid, fallbackSpacing)
%LOCALEXPECTEDRINGSPACING Median radial spacing per ring pair, per row.
%   Returns one value per upper-ring row, taken over the azimuths where the
%   pair has valid returns on both rings. Rows without a usable sample fall
%   back to the fixed cap so they keep the original behaviour.
    maskedRangeStep = rangeStep;
    maskedRangeStep(~pairValid) = NaN;
    spacing = median(maskedRangeStep, 2, "omitnan");
    spacing(~isfinite(spacing)) = fallbackSpacing;
end

function headingConfig = localDominantHeadingConfig( ...
        cfg, orientationParameters)
%LOCALDOMINANTHEADINGCONFIG Translate detector orientation parameters.
    headingConfig = struct( ...
        "searchStepDegrees", max(eps, localConfigValue( ...
            cfg, "curbOrientationSearchStepDegrees", 1.0)), ...
        "minimumLateralDistanceM", ...
            orientationParameters.minimumLateralDistance, ...
        "maximumLateralDistanceM", max( ...
            orientationParameters.minimumLateralDistance, ...
            localConfigValue( ...
                cfg, ...
                "curbOrientationMaximumLateralDistance", ...
                18.0)), ...
        "interceptBinWidthM", ...
            orientationParameters.interceptBinWidth, ...
        "seedDistanceToleranceM", ...
            orientationParameters.seedDistanceTolerance, ...
        "minimumLineSupport", ...
            orientationParameters.minimumLineSupport, ...
        "minimumLineSpanM", ...
            orientationParameters.minimumLineSpan, ...
        "spanSaturationM", ...
            orientationParameters.spanScoreSaturation, ...
        "maximumSeedWeight", 4.0, ...
        "marginSeparationDegrees", max(eps, ...
            localConfigValue( ...
                cfg, ...
                "curbOrientationMarginSeparationDegrees", ...
                8.0)));
end

function roadFrame = localRoadFrameFromDominantHeading(estimate)
%LOCALROADFRAMEFROMDOMINANTHEADING Convert one-line estimate diagnostics.
    roadFrame = localEmptyRoadFrame();
    roadFrame.found = true;
    roadFrame.headingDegrees = localNormalizeLineHeading( ...
        estimate.headingDegrees);
    roadFrame.source = "feature-dominant-line";
    roadFrame.leftSupport = estimate.azimuthSupport;
    roadFrame.rightSupport = 0;
    roadFrame.pairScore = estimate.score;
    roadFrame.scoreMargin = estimate.scoreMargin;
end

function roadFrame = localEstimateRoadFrame( ...
        seedSensorX, seedSensorY, seedAzimuth, cfg, parameters)
%LOCALESTIMATEROADFRAME Find the dominant parallel curb orientation.
    roadFrame = localEmptyRoadFrame();
    configuredHeading = localOptionalConfigValue( ...
        cfg, "curbRoadHeadingDegrees");
    if isfinite(configuredHeading)
        roadFrame.found = true;
        roadFrame.headingDegrees = localNormalizeLineHeading( ...
            configuredHeading);
        roadFrame.source = "configured";
        return;
    end
    priorHeading = localOptionalConfigValue( ...
        cfg, "curbRoadHeadingPriorDegrees");
    priorTolerance = max(0.0, localConfigValue( ...
        cfg, "curbRoadHeadingPriorToleranceDegrees", 20.0));
    if numel(seedSensorX) < 2 * parameters.minimumLineSupport
        if isfinite(priorHeading)
            roadFrame.found = true;
            roadFrame.headingDegrees = ...
                localNormalizeLineHeading(priorHeading);
            roadFrame.source = "prior-fallback";
        end
        return;
    end

    headingCandidates = ...
        -90.0:parameters.searchStepDegrees:(90.0 - eps);
    if ~any(abs(headingCandidates) <= eps)
        headingCandidates = sort([headingCandidates, 0.0]);
    end
    if isfinite(priorHeading)
        priorHeading = localNormalizeLineHeading(priorHeading);
        headingDifference = localNormalizeLineHeading( ...
            headingCandidates - priorHeading);
        headingCandidates = headingCandidates( ...
            abs(headingDifference) <= priorTolerance);
        headingCandidates = unique([ ...
            headingCandidates, priorHeading]);
    end

    bestScore = -inf;
    secondBestScore = -inf;
    for headingDegrees = headingCandidates
        [longitudinal, lateral] = localTransformToRoadFrame( ...
            seedSensorX, seedSensorY, headingDegrees);
        leftOffset = localFitOrientationOffset( ...
            longitudinal, lateral, seedAzimuth, -1, parameters);
        rightOffset = localFitOrientationOffset( ...
            longitudinal, lateral, seedAzimuth, 1, parameters);
        if ~leftOffset.found || ~rightOffset.found
            continue;
        end

        roadWidth = rightOffset.intercept - leftOffset.intercept;
        if roadWidth < parameters.minimumRoadWidth ...
                || roadWidth > parameters.maximumRoadWidth
            continue;
        end

        pairScore = leftOffset.score + rightOffset.score;
        if pairScore > bestScore
            secondBestScore = bestScore;
            bestScore = pairScore;
            roadFrame.found = true;
            roadFrame.headingDegrees = headingDegrees;
            roadFrame.roadWidth = roadWidth;
            roadFrame.leftSupport = leftOffset.azimuthSupport;
            roadFrame.rightSupport = rightOffset.azimuthSupport;
        elseif pairScore > secondBestScore
            secondBestScore = pairScore;
        end
    end

    if roadFrame.found
        if isfinite(priorHeading)
            roadFrame.source = "estimated-with-prior";
        else
            roadFrame.source = "estimated";
        end
        roadFrame.pairScore = bestScore;
        if isfinite(secondBestScore)
            roadFrame.scoreMargin = bestScore - secondBestScore;
        end
    elseif isfinite(priorHeading)
        roadFrame.found = true;
        roadFrame.headingDegrees = priorHeading;
        roadFrame.source = "prior-fallback";
    end
end

function model = localFitOrientationOffset( ...
        longitudinal, lateral, azimuth, sideSign, parameters)
%LOCALFITORIENTATIONOFFSET Score one near-constant lateral boundary.
    sideMask = ...
        sideSign * lateral >= parameters.minimumLateralDistance ...
        & sideSign * lateral <= parameters.maximumLateralDistance;
    longitudinal = longitudinal(sideMask);
    lateral = lateral(sideMask);
    azimuth = azimuth(sideMask);
    model = localEmptyOrientationOffset();
    if numel(longitudinal) < parameters.minimumLineSupport
        return;
    end

    interceptBins = round(lateral / parameters.interceptBinWidth);
    [uniqueBins, ~, group] = unique(interceptBins);
    binCounts = accumarray(group, 1);
    minimumBinCount = max(2, ceil( ...
        parameters.minimumLineSupport ...
        * parameters.interceptBinWidth ...
        / (2.0 * parameters.seedDistanceTolerance)));
    viableBins = uniqueBins(binCounts >= minimumBinCount);

    bestScore = -inf;
    for binIndex = 1:numel(viableBins)
        interceptCenter = ...
            viableBins(binIndex) * parameters.interceptBinWidth;
        inliers = abs(lateral - interceptCenter) <= ...
            parameters.seedDistanceTolerance;
        support = numel(unique(azimuth(inliers)));
        if support < parameters.minimumLineSupport
            continue;
        end

        longitudinalSpan = ...
            max(longitudinal(inliers)) - min(longitudinal(inliers));
        if longitudinalSpan < parameters.minimumLineSpan
            continue;
        end

        score = support + parameters.spanScoreWeight * min( ...
            longitudinalSpan, parameters.spanScoreSaturation);
        if score > bestScore
            bestScore = score;
            model.found = true;
            model.intercept = median(lateral(inliers));
            model.azimuthSupport = support;
            model.longitudinalSpan = longitudinalSpan;
            model.score = score;
        end
    end
end

function [roadX, roadY] = localTransformToRoadFrame( ...
        sensorX, sensorY, headingDegrees)
%LOCALTRANSFORMTOROADFRAME Rotate sensor XY into tangent-normal coordinates.
    cosine = cosd(headingDegrees);
    sine = sind(headingDegrees);
    roadX = cosine * sensorX + sine * sensorY;
    roadY = -sine * sensorX + cosine * sensorY;
end

function headingDegrees = localNormalizeLineHeading(headingDegrees)
%LOCALNORMALIZELINEHEADING Map an unoriented line angle to [-90, 90).
    headingDegrees = mod(double(headingDegrees) + 90.0, 180.0) - 90.0;
end

function model = localEmptyOrientationOffset()
%LOCALEMPTYORIENTATIONOFFSET Return an empty orientation-line score.
    model = struct( ...
        "found", false, ...
        "intercept", NaN, ...
        "azimuthSupport", 0, ...
        "longitudinalSpan", 0.0, ...
        "score", -inf);
end

function roadFrame = localEmptyRoadFrame()
%LOCALEMPTYROADFRAME Return the sensor-aligned fallback frame.
    roadFrame = struct( ...
        "found", false, ...
        "headingDegrees", 0.0, ...
        "source", "fallback", ...
        "roadWidth", NaN, ...
        "leftSupport", 0, ...
        "rightSupport", 0, ...
        "pairScore", -inf, ...
        "scoreMargin", NaN);
end

function boundaryMask = localExpandBoundaryPair( ...
        lineModel, forwardModel, x, y, z, valid, maxCurbZ, ...
        lineDistanceTolerance, forwardDistanceTolerance, ...
        lineLongitudinalMargin, forwardLongitudinalMargin, heightMargin, ...
        topSurfaceDistanceTolerance, topSurfaceHeightOffset, ...
        topSurfaceAzimuthRadius, topSurfaceRingRadius)
%LOCALEXPANDBOUNDARYPAIR Prefer a supported curve over its line anchor.
%   The line is only an anchor for the quadratic search. Retaining it beyond
%   the curve support can reintroduce a long, straight road-surface seam or
%   scenery edge. Extend a supported bidirectional curve over the line
%   anchor's observed domain and use the curve exclusively.
    if forwardModel.found
        expansionModel = forwardModel;
        if lineModel.found
            expansionModel.minimumX = min( ...
                forwardModel.minimumX, lineModel.minimumX);
            expansionModel.maximumX = max( ...
                forwardModel.maximumX, lineModel.maximumX);
        end
        boundaryMask = localExpandBoundary( ...
            expansionModel, x, y, z, valid, maxCurbZ, ...
            forwardDistanceTolerance, forwardLongitudinalMargin, ...
            heightMargin, ...
            topSurfaceDistanceTolerance, topSurfaceHeightOffset, ...
            topSurfaceAzimuthRadius, topSurfaceRingRadius);
        return;
    end

    boundaryMask = localExpandBoundary( ...
        lineModel, x, y, z, valid, maxCurbZ, ...
        lineDistanceTolerance, lineLongitudinalMargin, heightMargin, ...
        topSurfaceDistanceTolerance, topSurfaceHeightOffset, ...
        topSurfaceAzimuthRadius, topSurfaceRingRadius);
end

function boundaryMask = localExpandBoundary( ...
        model, x, y, z, valid, maxCurbZ, distanceTolerance, ...
        longitudinalMargin, heightMargin, ...
        topSurfaceDistanceTolerance, topSurfaceHeightOffset, ...
        topSurfaceAzimuthRadius, topSurfaceRingRadius)
%LOCALEXPANDBOUNDARY Recover curb-face points omitted by sparse seed detection.
    boundaryMask = false(size(valid));
    if ~model.found
        return;
    end

    curveY = model.curvature * x.^2 + model.slope * x + model.intercept;
    curveSlope = 2.0 * model.curvature * x + model.slope;
    perpendicularDistance = abs(y - curveY) ./ hypot(1.0, curveSlope);
    domainMask = valid & ...
        z <= maxCurbZ & ...
        z >= model.minimumZ - heightMargin & ...
        z <= model.maximumZ + heightMargin & ...
        x >= model.minimumX - longitudinalMargin & ...
        x <= model.maximumX + longitudinalMargin;
    boundaryMask = domainMask & ...
        perpendicularDistance <= distanceTolerance;
    topSurfaceCandidateMask = domainMask & ...
        z >= model.maximumZ + topSurfaceHeightOffset & ...
        perpendicularDistance <= max( ...
            distanceTolerance, topSurfaceDistanceTolerance);
    nearbyBoundaryMask = localCircularNeighborhoodMask( ...
        boundaryMask, topSurfaceRingRadius, topSurfaceAzimuthRadius);
    boundaryMask = boundaryMask | ...
        (topSurfaceCandidateMask & nearbyBoundaryMask);
end

function neighborhoodMask = localCircularNeighborhoodMask( ...
        mask, ringRadius, azimuthRadius)
%LOCALCIRCULARNEIGHBORHOODMASK Find nearby responses with azimuth wrapping.
    supportCount = zeros(size(mask));
    for azimuthOffset = -azimuthRadius:azimuthRadius
        shiftedMask = circshift(mask, [0, azimuthOffset]);
        supportCount = supportCount + movsum( ...
            double(shiftedMask), [ringRadius, ringRadius], 1);
    end
    neighborhoodMask = supportCount > 0;
end

function processingResult = localEmptyResult( ...
        emptyIndices, emptyModel, ringFeatureFusionSummary)
%LOCALEMPTYRESULT Return empty outputs with the normal result schema.
    processingResult.left = emptyIndices;
    processingResult.right = emptyIndices;
    processingResult.curbs = emptyIndices;
    processingResult.curbModels = struct( ...
        "left", emptyModel, ...
        "right", emptyModel, ...
        "leftForward", emptyModel, ...
        "rightForward", emptyModel, ...
        "roadFrame", localEmptyRoadFrame(), ...
        "ringFeatureFusion", ringFeatureFusionSummary);
end

function [enabled, source] = localRingFeatureFusionActivation( ...
        cfg, numberOfRings, numberOfAzimuths)
%LOCALRINGFEATUREFUSIONACTIVATION Enable only for the calibrated sensor.
    enabled = numberOfRings == 64 && numberOfAzimuths == 1000;
    source = "automatic-sensor-profile";
    fieldName = "curbRingFeatureFusionEnabled";
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    validLogical = islogical(candidate) && isscalar(candidate);
    validNumeric = isnumeric(candidate) && isreal(candidate) ...
        && isscalar(candidate) && isfinite(candidate) ...
        && (candidate == 0 || candidate == 1);
    if ~validLogical && ~validNumeric
        error( ...
            "groundPointsProcessing:InvalidRingFeatureFusionEnabled", ...
            "%s must be a logical scalar.", fieldName);
    end
    enabled = logical(candidate);
    source = "configured";
end

function fusionConfig = localRingFeatureFusionConfig(cfg)
%LOCALRINGFEATUREFUSIONCONFIG Translate detector-level fusion options.
    fusionConfig = struct("enabled", true);
    fieldMappings = [ ...
        "curbRingFeatureMinimumFamilyVotes", ...
            "minimumFamilyVotes"; ...
        "curbRingFeatureMinimumRadialMemberVotes", ...
            "minimumRadialMemberVotes"; ...
        "curbRingFeatureSaliencyEnabled", ...
            "saliencyEnabled"; ...
        "curbRingFeatureLocalHalfWidthBins", ...
            "localHalfWidthBins"; ...
        "curbRingFeatureLocalExclusionBins", ...
            "localExclusionBins"; ...
        "curbRingFeatureMinimumLocalNeighborCount", ...
            "minimumLocalNeighborCount"; ...
        "curbRingFeatureLocalPercentileThreshold", ...
            "localPercentileThreshold"; ...
        "curbRingFeatureMinimumSalientFamilyVotes", ...
            "minimumSalientFamilyVotes"; ...
        "curbRingFeatureThresholds", ...
            "thresholds"];
    for mappingIndex = 1:size(fieldMappings, 1)
        detectorField = fieldMappings(mappingIndex, 1);
        fusionField = fieldMappings(mappingIndex, 2);
        if isfield(cfg, detectorField)
            fusionConfig.(fusionField) = cfg.(detectorField);
        end
    end
end

function summary = localEmptyRingFeatureFusionSummary(enabled, source)
%LOCALEMPTYRINGFEATUREFUSIONSUMMARY Return compact fusion diagnostics.
    summary = struct( ...
        "enabled", logical(enabled), ...
        "activationSource", string(source), ...
        "minimumFamilyVotes", 2.0, ...
        "minimumRadialMemberVotes", 2.0, ...
        "saliencyEnabled", true, ...
        "localHalfWidthBins", 33.0, ...
        "localExclusionBins", 3.0, ...
        "minimumLocalNeighborCount", 12.0, ...
        "localPercentileThreshold", 0.5, ...
        "minimumSalientFamilyVotes", 2.0, ...
        "orientationMinimumFamilyVotes", 3.0, ...
        "orientationRequireCompression", false, ...
        "candidateGatingEnabled", false, ...
        "thresholds", struct(), ...
        "validCellCount", 0, ...
        "acceptedCellCount", 0, ...
        "legacyCandidateCount", 0, ...
        "acceptedCandidateCount", 0, ...
        "orientationCandidateCount", 0, ...
        "orientationSeedSource", "", ...
        "coverageFallbackCandidateCount", 0, ...
        "legacyOuterRecoveryCandidateCount", 0, ...
        "acceptedOuterRecoveryCandidateCount", 0);
end

function value = localLogicalConfigValue(cfg, fieldName, defaultValue)
%LOCALLOGICALCONFIGVALUE Return a validated logical configuration value.
    value = logical(defaultValue);
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end
    candidate = cfg.(fieldName);
    validLogical = islogical(candidate) && isscalar(candidate);
    validNumeric = isnumeric(candidate) && isreal(candidate) ...
        && isscalar(candidate) && isfinite(candidate) ...
        && (candidate == 0 || candidate == 1);
    if ~validLogical && ~validNumeric
        error( ...
            "groundPointsProcessing:InvalidLogicalConfig", ...
            "%s must be a logical scalar.", fieldName);
    end
    value = logical(candidate);
end

function value = localOptionalConfigValue(cfg, fieldName)
%LOCALOPTIONALCONFIGVALUE Return a finite scalar or NaN when unspecified.
    value = NaN;
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end

    candidateValue = double(cfg.(fieldName));
    if isscalar(candidateValue) && isfinite(candidateValue)
        value = candidateValue;
    end
end

function value = localConfigValue(cfg, fieldNames, defaultValue)
%LOCALCONFIGVALUE Return the first finite scalar configuration value.
    value = double(defaultValue);
    if ~isstruct(cfg)
        return;
    end

    fieldNames = string(fieldNames);
    for fieldIndex = 1:numel(fieldNames)
        fieldName = char(fieldNames(fieldIndex));
        if ~isfield(cfg, fieldName)
            continue;
        end

        candidateValue = double(cfg.(fieldName));
        if isscalar(candidateValue) && isfinite(candidateValue)
            value = candidateValue;
            return;
        end
    end
end
