function [organizedFrame, rawPointIndexGrid, rawToOrganized] = ...
        organizeLidarSweepGrid(rawPoints)
% organizeLidarSweepGrid Organize one raw LiDAR sweep into the 64x1000 grid.
%
% Bins the raw XYZ points of one sweep into the calibrated 64-ring by
% 1000-azimuth-bin grid (10 to -30 degree ring elevations) shared by
% every curb-detection experiment tool. When several raw points land in
% one cell, the point closest to the ring's center elevation is kept.
% organizedFrame carries x/y/z/range grids with NaN in empty cells and a
% logical valid mask. rawPointIndexGrid maps each grid cell to the raw
% row it kept (0 when empty); rawToOrganized maps each raw row to its
% grid linear index (0 when dropped).

    points = rawPoints(:, 1:3);
    horizontalRangeM = hypot(points(:, 1), points(:, 2));
    elevationDegrees = atan2d(points(:, 3), horizontalRangeM);
    azimuthDegrees = mod(atan2d(points(:, 2), points(:, 1)), 360);

    numberOfRings = 64;
    numberOfAzimuthBins = 1000;
    upperElevationDegrees = 10;
    lowerElevationDegrees = -30;
    elevationStepDegrees = ...
        (upperElevationDegrees - lowerElevationDegrees) ...
        / (numberOfRings - 1);
    azimuthStepDegrees = 360 / numberOfAzimuthBins;

    ringIndex = round( ...
        (upperElevationDegrees - elevationDegrees) ...
        / elevationStepDegrees) + 1;
    azimuthIndex = mod( ...
        round(azimuthDegrees / azimuthStepDegrees), ...
        numberOfAzimuthBins) + 1;
    validPoint = ...
        ringIndex >= 1 ...
        & ringIndex <= numberOfRings ...
        & all(isfinite(points), 2);
    rawPointIndices = find(validPoint);
    organizedLinearIndices = sub2ind( ...
        [numberOfRings, numberOfAzimuthBins], ...
        ringIndex(validPoint), azimuthIndex(validPoint));
    ringCenterElevationDegrees = upperElevationDegrees ...
        - (ringIndex(validPoint) - 1) * elevationStepDegrees;
    elevationErrorDegrees = abs( ...
        elevationDegrees(validPoint) ...
        - ringCenterElevationDegrees);
    candidateMapping = sortrows( ...
        [organizedLinearIndices, elevationErrorDegrees, rawPointIndices], ...
        [1, 2]);
    [~, uniqueCellRows] = unique( ...
        candidateMapping(:, 1), "stable");
    selectedRawPointIndices = ...
        candidateMapping(uniqueCellRows, 3);
    selectedOrganizedIndices = ...
        candidateMapping(uniqueCellRows, 1);

    emptyGrid = nan(numberOfRings, numberOfAzimuthBins);
    organizedFrame = struct( ...
        "x", emptyGrid, ...
        "y", emptyGrid, ...
        "z", emptyGrid, ...
        "range", emptyGrid, ...
        "valid", false(numberOfRings, numberOfAzimuthBins));
    organizedFrame.x(selectedOrganizedIndices) = ...
        points(selectedRawPointIndices, 1);
    organizedFrame.y(selectedOrganizedIndices) = ...
        points(selectedRawPointIndices, 2);
    organizedFrame.z(selectedOrganizedIndices) = ...
        points(selectedRawPointIndices, 3);
    organizedFrame.range(selectedOrganizedIndices) = ...
        horizontalRangeM(selectedRawPointIndices);
    organizedFrame.valid(selectedOrganizedIndices) = true;

    rawPointIndexGrid = zeros( ...
        numberOfRings, numberOfAzimuthBins);
    rawPointIndexGrid(selectedOrganizedIndices) = ...
        selectedRawPointIndices;
    rawToOrganized = zeros(size(rawPoints, 1), 1);
    rawToOrganized(selectedRawPointIndices) = selectedOrganizedIndices;
end
