function [trackedModels, state, diagnostics] = ...
        trackCurbQuadraticModels( ...
        detectedModels, egoState, sampleTime, state, cfg)
%TRACKCURBQUADRATICMODELS Track curb curves with Wang et al.'s method.
%   [TRACKEDMODELS, STATE, DIAGNOSTICS] =
%   TRACKCURBQUADRATICMODELS(DETECTEDMODELS, EGOSTATE, SAMPLETIME, STATE,
%   CFG) tracks one quadratic curb curve per side with the
%   amplitude-limiting Kalman scheme of Wang, Wu, He, and Yang, "A Point
%   Cloud-Based Robust Road Curb Detection and Tracking Method," IEEE
%   Access, vol. 7, 2019, Sec. VII.
%
%   Per side, three points with constant longitudinal stations x_s on the
%   tracked curve form the filter state. Each frame the points are
%   propagated by the exact rigid-body transform of the measured ego
%   motion (the prediction model x(k+1) = A x(k) + B u(k) of the paper),
%   and the current single-frame detection, evaluated at the same
%   stations, corrects them through a per-point Kalman update with an
%   identity observation model. Before the update, the detection passes
%   the amplitude-limiting filter: each of its coefficients may differ
%   from the previous frame's detected coefficients by at most
%   (T_a, T_b, T_c); a detection that fails the gate, or a missing
%   detection, leaves the prediction as the frame's output. The tracked
%   curve is the quadratic through the three points.
%
%   EGOSTATE is
%       [x, xDot, xDDot, y, yDot, yDDot, psi, psiDot]
%   in SI units, with x and y expressed in a fixed world frame and psi in
%   radians. Velocity, acceleration, and yaw rate predict the current pose
%   from the preceding sample to detect kinematic discontinuities.
%
%   STATE is never persistent. Pass [] to reset the tracker. A time gap,
%   kinematic discontinuity, or invalid prior also resets it explicitly.
%
%   DETECTEDMODELS follows groundPointsProcessing.curbModels. Curves are
%   represented as y = curvature*x^2 + slope*x + intercept in the detected
%   road frame.
%
%   Relevant CFG fields and defaults are:
%       curbTemporalTrackingStationsX             [-10, 0, 10] m
%       curbTemporalAmplitudeLimitCurvature       0.005 1/m
%       curbTemporalAmplitudeLimitSlope           0.5
%       curbTemporalAmplitudeLimitIntercept       0.8 m
%       curbTemporalProcessNoiseStd               0.10 m per sqrt(s)
%       curbTemporalMeasurementNoiseStd           0.12 m
%       curbTemporalMaximumPredictionFrames       30 frames
%       curbTemporalMaximumSampleTime             0.5 s
%       curbTemporalResetPositionResidual         3.0 m
%       curbTemporalResetHeadingResidual          20 degrees

    if nargin < 4
        state = [];
    end
    if nargin < 5 || isempty(cfg)
        cfg = struct();
    end
    validateattributes( ...
        egoState, {'numeric'}, ...
        {'real', 'finite', 'vector', 'numel', 8}, ...
        mfilename, 'egoState');
    validateattributes( ...
        sampleTime, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'positive'}, ...
        mfilename, 'sampleTime');
    if ~isstruct(detectedModels)
        error( ...
            "trackCurbQuadraticModels:InvalidDetectedModels", ...
            "detectedModels must be the curbModels structure.");
    end

    egoState = reshape(double(egoState), 1, 8);
    sampleTime = double(sampleTime);
    parameters = localParameters(cfg);
    currentRoadHeadingDegrees = localRoadHeading(detectedModels);
    leftMeasurement = localCombinedModel(detectedModels, "left");
    rightMeasurement = localCombinedModel(detectedModels, "right");

    [stateIsValid, positionResidual, headingResidual] = ...
        localValidateStateTransition( ...
            state, egoState, sampleTime, parameters);
    diagnostics = localEmptyDiagnostics();
    diagnostics.positionResidualM = positionResidual;
    diagnostics.headingResidualRad = headingResidual;

    if ~stateIsValid
        diagnostics.reset = ~isempty(state);
        diagnostics.resetReason = localResetReason( ...
            state, sampleTime, positionResidual, headingResidual, ...
            parameters);
        [leftSide, diagnostics.left] = localInitializeSide( ...
            leftMeasurement, parameters);
        [rightSide, diagnostics.right] = localInitializeSide( ...
            rightMeasurement, parameters);
        state = localBuildState( ...
            egoState, currentRoadHeadingDegrees, ...
            leftSide, rightSide, 1);
        trackedModels = localPackModels( ...
            detectedModels, leftSide.model, rightSide.model, parameters);
        return;
    end

    [rotation, translation] = localFrameTransform( ...
        state.previousEgoState, state.roadHeadingDegrees, ...
        egoState, currentRoadHeadingDegrees);

    [leftSide, diagnostics.left] = localTrackSide( ...
        localSideState(state, "left"), leftMeasurement, ...
        rotation, translation, sampleTime, parameters);
    [rightSide, diagnostics.right] = localTrackSide( ...
        localSideState(state, "right"), rightMeasurement, ...
        rotation, translation, sampleTime, parameters);

    state = localBuildState( ...
        egoState, currentRoadHeadingDegrees, ...
        leftSide, rightSide, state.frameCount + 1);
    trackedModels = localPackModels( ...
        detectedModels, leftSide.model, rightSide.model, parameters);
end

function parameters = localParameters(cfg)
    parameters = struct( ...
        "stationsX", localVectorConfigValue( ...
            cfg, "curbTemporalTrackingStationsX", [-10.0, 0.0, 10.0]), ...
        "amplitudeLimitCurvature", max(eps, localConfigValue( ...
            cfg, "curbTemporalAmplitudeLimitCurvature", 0.005)), ...
        "amplitudeLimitSlope", max(eps, localConfigValue( ...
            cfg, "curbTemporalAmplitudeLimitSlope", 0.5)), ...
        "amplitudeLimitIntercept", max(eps, localConfigValue( ...
            cfg, "curbTemporalAmplitudeLimitIntercept", 0.8)), ...
        "processNoiseStd", max(0.0, localConfigValue( ...
            cfg, "curbTemporalProcessNoiseStd", 0.10)), ...
        "measurementNoiseStd", max(eps, localConfigValue( ...
            cfg, "curbTemporalMeasurementNoiseStd", 0.12)), ...
        "maximumPredictionFrames", max(0, floor(localConfigValue( ...
            cfg, "curbTemporalMaximumPredictionFrames", 30))), ...
        "maximumSampleTime", max(eps, localConfigValue( ...
            cfg, "curbTemporalMaximumSampleTime", 0.5)), ...
        "resetPositionResidual", max(0.0, localConfigValue( ...
            cfg, "curbTemporalResetPositionResidual", 3.0)), ...
        "resetHeadingResidual", max(0.0, localConfigValue( ...
            cfg, "curbTemporalResetHeadingResidual", deg2rad(20.0))), ...
        "curveThreshold", max(eps, localConfigValue( ...
            cfg, "curbTemporalCurveThreshold", 1.0e-5)), ...
        "minimumStationSpread", 1.0);
    if numel(parameters.stationsX) ~= 3 ...
            || numel(unique(parameters.stationsX)) ~= 3
        error( ...
            "trackCurbQuadraticModels:InvalidTrackingStations", ...
            "curbTemporalTrackingStationsX must hold three distinct " + ...
            "longitudinal stations.");
    end
    parameters.stationsX = sort( ...
        reshape(double(parameters.stationsX), 1, 3));
end

function [isValid, positionResidual, headingResidual] = ...
        localValidateStateTransition( ...
        state, egoState, sampleTime, parameters)
    positionResidual = 0.0;
    headingResidual = 0.0;
    requiredFields = [ ...
        "initialized", "previousEgoState", "roadHeadingDegrees", ...
        "leftModel", "rightModel", "leftPoints", "rightPoints", ...
        "leftPointCovariances", "rightPointCovariances", ...
        "leftDetectedCoefficients", "rightDetectedCoefficients", ...
        "leftAge", "rightAge", "frameCount"];
    isValid = ...
        isstruct(state) ...
        && all(isfield(state, requiredFields)) ...
        && isscalar(state.initialized) ...
        && logical(state.initialized) ...
        && isnumeric(state.previousEgoState) ...
        && numel(state.previousEgoState) == 8 ...
        && all(isfinite(state.previousEgoState), "all") ...
        && sampleTime <= parameters.maximumSampleTime;
    if ~isValid
        return;
    end

    previousState = reshape(double(state.previousEgoState), 1, 8);
    predictedX = previousState(1) ...
        + sampleTime * previousState(2) ...
        + 0.5 * sampleTime^2 * previousState(3);
    predictedY = previousState(4) ...
        + sampleTime * previousState(5) ...
        + 0.5 * sampleTime^2 * previousState(6);
    predictedPsi = previousState(7) ...
        + sampleTime * previousState(8);
    positionResidual = hypot( ...
        egoState(1) - predictedX, egoState(4) - predictedY);
    headingResidual = localWrapToPi(egoState(7) - predictedPsi);
    isValid = ...
        positionResidual <= parameters.resetPositionResidual ...
        && abs(headingResidual) <= parameters.resetHeadingResidual;
end

function reason = localResetReason( ...
        state, sampleTime, positionResidual, headingResidual, parameters)
    if isempty(state)
        reason = "initialization";
    elseif sampleTime > parameters.maximumSampleTime
        reason = "sample-time-gap";
    elseif positionResidual > parameters.resetPositionResidual
        reason = "position-discontinuity";
    elseif abs(headingResidual) > parameters.resetHeadingResidual
        reason = "heading-discontinuity";
    else
        reason = "invalid-state";
    end
end

function side = localSideState(state, sideName)
    prefix = char(sideName);
    side = struct( ...
        "model", state.([prefix, 'Model']), ...
        "points", state.([prefix, 'Points']), ...
        "pointCovariances", state.([prefix, 'PointCovariances']), ...
        "detectedCoefficients", ...
            state.([prefix, 'DetectedCoefficients']), ...
        "age", state.([prefix, 'Age']));
end

function [side, diagnostics] = localInitializeSide( ...
        measurement, parameters)
    diagnostics = localEmptySideDiagnostics();
    diagnostics.measurementFound = measurement.found;
    if measurement.found
        side = localSideFromMeasurement(measurement, parameters);
        diagnostics.updateMode = "initialized";
    else
        side = localEmptySide();
        diagnostics.updateMode = "empty";
    end
    diagnostics.age = side.age;
end

function side = localEmptySide()
    side = struct( ...
        "model", emptyCurbBoundaryModel(), ...
        "points", nan(3, 2), ...
        "pointCovariances", nan(2, 2, 3), ...
        "detectedCoefficients", nan(1, 3), ...
        "age", 0);
end

function side = localSideFromMeasurement(measurement, parameters)
    coefficients = localModelCoefficients(measurement);
    side = struct( ...
        "model", measurement, ...
        "points", localCurvePoints( ...
            coefficients, parameters.stationsX), ...
        "pointCovariances", repmat( ...
            parameters.measurementNoiseStd^2 * eye(2), 1, 1, 3), ...
        "detectedCoefficients", coefficients, ...
        "age", 0);
end

function [side, diagnostics] = localTrackSide( ...
        side, measurement, rotation, translation, sampleTime, parameters)
%LOCALTRACKSIDE One side of the amplitude-limiting Kalman tracker.
    diagnostics = localEmptySideDiagnostics();
    diagnostics.measurementFound = measurement.found;
    diagnostics.previousAge = side.age;

    predictionFound = localModelIsUsable(side.model) ...
        && all(isfinite(side.points), "all");
    diagnostics.predictionFound = predictionFound;

    measurementCoefficients = localModelCoefficients(measurement);
    if measurement.found
        diagnostics.coefficientDeltas = abs( ...
            measurementCoefficients - side.detectedCoefficients);
        amplitudeAccepted = ...
            any(~isfinite(side.detectedCoefficients)) ...
            || ( ...
                diagnostics.coefficientDeltas(1) <= ...
                    parameters.amplitudeLimitCurvature ...
                && diagnostics.coefficientDeltas(2) <= ...
                    parameters.amplitudeLimitSlope ...
                && diagnostics.coefficientDeltas(3) <= ...
                    parameters.amplitudeLimitIntercept);
    else
        amplitudeAccepted = false;
    end
    diagnostics.amplitudeAccepted = amplitudeAccepted;

    if ~predictionFound
        if measurement.found
            side = localSideFromMeasurement(measurement, parameters);
            diagnostics.updateMode = "reinitialized";
        else
            side = localEmptySide();
            diagnostics.updateMode = "empty";
        end
        diagnostics.age = side.age;
        return;
    end

    % Prediction: x(k+1) = A x(k) + B u(k), the exact rigid-body point
    % transform of the measured ego motion, with covariance
    % P(k+1|k) = A P A' + Q.
    predictedPoints = (rotation * side.points.').' ...
        + repmat(reshape(translation, 1, 2), 3, 1);
    processNoise = ...
        parameters.processNoiseStd^2 * sampleTime * eye(2);
    predictedCovariances = side.pointCovariances;
    for pointIndex = 1:3
        predictedCovariances(:, :, pointIndex) = ...
            rotation * side.pointCovariances(:, :, pointIndex) ...
                * rotation.' ...
            + processNoise;
    end
    predictedModel = localModelThroughPoints( ...
        side.model, predictedPoints, rotation, translation, parameters);

    if measurement.found
        side.detectedCoefficients = measurementCoefficients;
    end

    if amplitudeAccepted && predictedModel.found
        % Measurement update at the three constant stations with an
        % identity observation model: G = P (P + R)^-1.
        measurementNoise = parameters.measurementNoiseStd^2 * eye(2);
        measuredPoints = localCurvePoints( ...
            measurementCoefficients, parameters.stationsX);
        updatedPoints = predictedPoints;
        updatedCovariances = predictedCovariances;
        for pointIndex = 1:3
            priorCovariance = predictedCovariances(:, :, pointIndex);
            gain = priorCovariance ...
                / (priorCovariance + measurementNoise);
            innovation = ...
                measuredPoints(pointIndex, :).' ...
                - predictedPoints(pointIndex, :).';
            updatedPoints(pointIndex, :) = ...
                (predictedPoints(pointIndex, :).' ...
                    + gain * innovation).';
            updatedCovariance = ...
                (eye(2) - gain) * priorCovariance ...
                    * (eye(2) - gain).' ...
                + gain * measurementNoise * gain.';
            updatedCovariances(:, :, pointIndex) = ...
                0.5 * (updatedCovariance + updatedCovariance.');
        end
        updatedModel = localQuadraticThroughPoints( ...
            measurement, updatedPoints, parameters);
        if updatedModel.found
            side.model = updatedModel;
            side.points = updatedPoints;
            side.pointCovariances = updatedCovariances;
            side.age = 0;
            diagnostics.updateMode = "measurement-update";
            diagnostics.age = side.age;
            return;
        end
    end

    if side.age < parameters.maximumPredictionFrames ...
            && predictedModel.found
        side.model = predictedModel;
        side.points = predictedPoints;
        side.pointCovariances = predictedCovariances;
        side.age = side.age + 1;
        diagnostics.updateMode = "prediction";
        diagnostics.usedPrediction = true;
    elseif measurement.found
        side = localSideFromMeasurement(measurement, parameters);
        diagnostics.updateMode = "reinitialized";
    else
        side = localEmptySide();
        diagnostics.updateMode = "expired";
    end
    diagnostics.age = side.age;
end

function [rotation, translation] = localFrameTransform( ...
        previousEgoState, previousRoadHeadingDegrees, ...
        egoState, currentRoadHeadingDegrees)
%LOCALFRAMETRANSFORM Exact previous-road-frame to current-road-frame map.
    previousState = reshape(double(previousEgoState), 1, 8);
    previousAngle = previousState(7) ...
        + deg2rad(double(previousRoadHeadingDegrees));
    currentAngle = egoState(7) ...
        + deg2rad(double(currentRoadHeadingDegrees));
    rotation = localRotationMatrix(previousAngle - currentAngle);
    worldDelta = [ ...
        previousState(1) - egoState(1); ...
        previousState(4) - egoState(4)];
    translation = localRotationMatrix(-currentAngle) * worldDelta;
end

function rotation = localRotationMatrix(angle)
    rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
end

function points = localCurvePoints(coefficients, stationsX)
    stations = reshape(stationsX, [], 1);
    points = [stations, polyval(coefficients, stations)];
end

function coefficients = localModelCoefficients(model)
    coefficients = [ ...
        double(model.curvature), ...
        double(model.slope), ...
        double(model.intercept)];
end

function model = localModelThroughPoints( ...
        previousModel, points, rotation, translation, parameters)
%LOCALMODELTHROUGHPOINTS Predicted model with a rigidly transformed domain.
    model = localQuadraticThroughPoints( ...
        previousModel, points, parameters);
    if ~model.found
        return;
    end
    domainX = [previousModel.minimumX; previousModel.maximumX];
    domainY = polyval(localModelCoefficients(previousModel), domainX);
    transformedDomain = (rotation * [domainX, domainY].').' ...
        + repmat(reshape(translation, 1, 2), 2, 1);
    model.minimumX = min(transformedDomain(:, 1));
    model.maximumX = max(transformedDomain(:, 1));
    if model.maximumX <= model.minimumX
        model = emptyCurbBoundaryModel();
    end
end

function model = localQuadraticThroughPoints( ...
        sourceModel, points, parameters)
%LOCALQUADRATICTHROUGHPOINTS Exact quadratic through three tracked points.
    model = emptyCurbBoundaryModel();
    stationSpread = max(points(:, 1)) - min(points(:, 1));
    if ~all(isfinite(points), "all") ...
            || stationSpread < parameters.minimumStationSpread
        return;
    end
    vandermonde = [points(:, 1).^2, points(:, 1), ones(3, 1)];
    coefficients = vandermonde \ points(:, 2);
    if any(~isfinite(coefficients))
        return;
    end
    model = sourceModel;
    model.found = true;
    model.curvature = coefficients(1);
    model.slope = coefficients(2);
    model.intercept = coefficients(3);
    model.selectedOuterCandidate = false;
end

function model = localCombinedModel(models, sideName)
    model = emptyCurbBoundaryModel();
    lineField = char(sideName);
    forwardField = [lineField, 'Forward'];
    if isfield(models, forwardField) ...
            && localModelIsUsable(models.(forwardField))
        model = models.(forwardField);
    elseif isfield(models, lineField) ...
            && localModelIsUsable(models.(lineField))
        model = models.(lineField);
    end
end

function trackedModels = localPackModels( ...
        detectedModels, leftModel, rightModel, parameters)
    trackedModels = detectedModels;
    [trackedModels.left, trackedModels.leftForward] = ...
        localSplitCombinedModel(leftModel, parameters.curveThreshold);
    [trackedModels.right, trackedModels.rightForward] = ...
        localSplitCombinedModel(rightModel, parameters.curveThreshold);
end

function [lineModel, forwardModel] = ...
        localSplitCombinedModel(model, curveThreshold)
    lineModel = emptyCurbBoundaryModel();
    forwardModel = emptyCurbBoundaryModel();
    if ~localModelIsUsable(model)
        return;
    end
    if abs(model.curvature) <= curveThreshold
        lineModel = model;
        lineModel.curvature = 0.0;
        return;
    end
    forwardModel = model;
    lineModel = model;
    lineModel.curvature = 0.0;
end

function state = localBuildState( ...
        egoState, roadHeadingDegrees, leftSide, rightSide, frameCount)
    state = struct( ...
        "initialized", true, ...
        "previousEgoState", reshape(double(egoState), 1, 8), ...
        "roadHeadingDegrees", double(roadHeadingDegrees), ...
        "leftModel", leftSide.model, ...
        "rightModel", rightSide.model, ...
        "leftPoints", leftSide.points, ...
        "rightPoints", rightSide.points, ...
        "leftPointCovariances", leftSide.pointCovariances, ...
        "rightPointCovariances", rightSide.pointCovariances, ...
        "leftDetectedCoefficients", leftSide.detectedCoefficients, ...
        "rightDetectedCoefficients", rightSide.detectedCoefficients, ...
        "leftAge", double(leftSide.age), ...
        "rightAge", double(rightSide.age), ...
        "frameCount", double(frameCount));
end

function headingDegrees = localRoadHeading(models)
    headingDegrees = 0.0;
    if isfield(models, "roadFrame") ...
            && isstruct(models.roadFrame) ...
            && isfield(models.roadFrame, "headingDegrees") ...
            && isscalar(models.roadFrame.headingDegrees) ...
            && isfinite(models.roadFrame.headingDegrees)
        headingDegrees = double(models.roadFrame.headingDegrees);
    end
end

function usable = localModelIsUsable(model)
    requiredFields = [ ...
        "found", "curvature", "slope", "intercept", ...
        "minimumX", "maximumX", "minimumZ", "maximumZ", ...
        "azimuthSupport", "longitudinalSpan", "score", ...
        "selectedOuterCandidate"];
    usable = ...
        isstruct(model) ...
        && all(isfield(model, requiredFields)) ...
        && isscalar(model.found) ...
        && logical(model.found) ...
        && all(isfinite([ ...
            model.curvature, model.slope, model.intercept, ...
            model.minimumX, model.maximumX])) ...
        && model.maximumX > model.minimumX;
end

function diagnostics = localEmptyDiagnostics()
    diagnostics = struct( ...
        "reset", false, ...
        "resetReason", "", ...
        "positionResidualM", 0.0, ...
        "headingResidualRad", 0.0, ...
        "left", localEmptySideDiagnostics(), ...
        "right", localEmptySideDiagnostics());
end

function diagnostics = localEmptySideDiagnostics()
    diagnostics = struct( ...
        "measurementFound", false, ...
        "predictionFound", false, ...
        "amplitudeAccepted", false, ...
        "coefficientDeltas", nan(1, 3), ...
        "previousAge", 0, ...
        "age", 0, ...
        "usedPrediction", false, ...
        "updateMode", "");
end

function angle = localWrapToPi(angle)
    angle = mod(double(angle) + pi, 2.0 * pi) - pi;
end

function value = localConfigValue(cfg, fieldName, defaultValue)
    value = double(defaultValue);
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end
    candidate = double(cfg.(fieldName));
    if isscalar(candidate) && isfinite(candidate)
        value = candidate;
    end
end

function value = localVectorConfigValue(cfg, fieldName, defaultValue)
    value = double(defaultValue);
    if ~isstruct(cfg) || ~isfield(cfg, fieldName)
        return;
    end
    candidate = double(cfg.(fieldName));
    if isvector(candidate) && all(isfinite(candidate))
        value = reshape(candidate, 1, []);
    end
end
