classdef avoidanceNativeGeometryTest < matlab.unittest.TestCase
    properties (TestParameter)
        targetCount = struct('noTarget',0,'twoTargets',2)
    end
    methods (TestClassSetup)
        function addPaths(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"controller")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"solver","bicycle")));
        end
    end
    methods (Test)
        function nativeProjectionPreservesUncertaintyAndLocalRows(testCase)
            points = 8;
            cfg = struct("model",struct("lateralDomainRadius",8,"headingDomainRadius",0.4, ...
                "speedMinimum",0,"speedMaximum",18,"lateralVelocityMaximum",3,"yawRateMaximum",1, ...
                "scheduleSpeedFloor",0.5,"slipAngleMaximum",[0.2;0.2]), ...
                "vehicle",struct("lf",1.5,"lr",1.4));
            tube = struct("stage",2, ...
                "map",reshape(sin(1:6*4*points),6,4,points)/100, ...
                "offset",repmat([30;0.1;0.02;10;0.2;0.01],1,points), ...
                "localStateMap",repmat(eye(6),1,1,points), ...
                "localInputMap",reshape(cos(1:6*2*points),6,2,points)/100, ...
                "localOffset",repmat([0.5;0;0;0;0;0],1,points), ...
                "numericalRadius",1e-8*ones(6,points));
            geometric = struct("state",[0,1,0,0,0,0;0,-1,0,0,0,0], ...
                "bound",10*ones(2,points),"source",[1;2],"normals",zeros(2,0));
            data = struct("cfg",cfg,"tube",tube,"nominal",tube.offset, ...
                "stationRange",[29;32],"stateRadius",0.001*ones(6,points), ...
                "scheduleSpeed",10, ...
                "geometricRows",geometric,"planCount",4);
            data = repmat(data,2,1);data(2).stateRadius = 2*data(2).stateRadius;
            expected = avoidanceSafetyGeometry.projectRows(data);
            actual = avoidanceProjectedRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end

        function nativeSupportsPreserveAllHalfspaceRows(testCase,targetCount)
            target = struct("center",[50;1;-10;0;0;0;pi;0],"radius",0.01*ones(8,1), ...
                "contract",struct("jerkBound",[0.1;0.1],"yawAccelerationBound",0.01), ...
                "halfLength",2.5,"halfWidth",1);
            boundary = struct("coefficients",[-0.001,0.02,0],"safeSideSign",1, ...
                "longitudinalDirection",[1;0],"lateralDirection",[0;1],"origin",[0;-10], ...
                "parameterRange",[-200;200],"normalDistanceErrorBound",0.01);
            points = 8;
            data = struct("frame",[2;-1;cos(0.2);sin(0.2);-sin(0.2);cos(0.2);0.2;0.01;0.02;0.003;30;35], ...
                "nominal",repmat([32;0.1;0.05;10;0.1;0.02],1,points), ...
                "targets",repmat(target,targetCount,1),"boundaries",boundary, ...
                "settings",[2.5;1;0.4;8;0.25],"duration",0.05,"degree",7);
            data = repmat(data,2,1);
            data(2).nominal(1,:) = 33;
            expected = avoidanceSafetyGeometry.cellRows(data);
            actual = avoidanceCellRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end
    end
end
