classdef avoidanceNativeGeometryTest < matlab.unittest.TestCase
    properties (TestParameter)
        robust = struct('executedTube',true,'nominalLookahead',false)
        targetCount = struct('noTarget',0,'twoTargets',2)
    end
    methods (TestClassSetup)
        function addPaths(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"controller")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"solver","bicycle")));
        end
    end
    methods (Test)
        function nativeNominalCheckRetainsAFutureHeadingViolation(testCase)
            rows = [eye(6);-eye(6);zeros(4,6)];
            limit = [100;8;.4;18;3;1;100;8;.4;0;3;1;.2;.2;.2;.2];
            cellData = struct("stage",2,"state",repmat(rows,1,1,2), ...
                "startState",zeros(16,6,2),"input",zeros(16,2,2), ...
                "limit",repmat(limit,1,2),"initialReserve",zeros(16,2),"slipRows",(13:16).');
            cells = repmat(cellData,2,1);cells(1).stage = 1;
            states = [0,.5,1;0,0,0;0,.1,.405;10,9.8,9.2;.02,.03,.04;.01,.02,.03];
            inputs = [.02,.03;0,0];
            data = struct("cells",cells,"states",states,"inputs",inputs, ...
                "settings",[1;.5;1.5;1.4;.2;.2;1e-6]);
            expected = avoidanceSafetyGeometry("nominalCheck",data);
            actual = avoidanceNominalCheckKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-12);
            testCase.verifyEqual(actual.violation,.005,AbsTol=1e-12);
            testCase.verifyEqual(actual.cellIndex,2);
            testCase.verifyEqual(actual.rowIndex,3);
            testCase.verifySize(actual.residuals,[32,1]);
        end

        function nativeProjectionPreservesUncertaintyAndLocalRows(testCase,robust)
            points = 2+6*double(robust);
            cfg = struct("model",struct("lateralDomainRadius",8,"headingDomainRadius",0.4, ...
                "speedMinimum",0,"speedMaximum",18,"lateralVelocityMaximum",3,"yawRateMaximum",1, ...
                "scheduleSpeedFloor",0.5,"slipAngleMaximum",[0.2;0.2]), ...
                "vehicle",struct("lf",1.5,"lr",1.4), ...
                "encounter",struct("corridorOverlap",0.1,"nominalLinearizationReserve",0.01));
            tube = struct("stage",2-double(robust), ...
                "map",reshape(sin(1:6*4*points),6,4,points)/100, ...
                "offset",repmat([30;0.1;0.02;10;0.2;0.01],1,points), ...
                "localStateMap",repmat(eye(6),1,1,points), ...
                "localInputMap",reshape(cos(1:6*2*points),6,2,points)/100, ...
                "localOffset",repmat([0.5;0;0;0;0;0],1,points), ...
                "numericalRadius",1e-8*ones(6,points));
            friction = struct("state",zeros(0,6),"input",zeros(0,2),"bound",zeros(0,1));
            if robust
                friction = struct("state",[zeros(2,4),eye(2)],"input",eye(2),"bound",[1;1]);
            end
            geometric = struct("state",[0,1,0,0,0,0;0,-1,0,0,0,0], ...
                "bound",10*ones(2,points),"anticipation",[0.01;0.02],"source",[1;2],"normals",zeros(2,0));
            data = struct("cfg",cfg,"tube",tube,"nominal",tube.offset, ...
                "stationRange",[29;32],"stateRadius",0.001*ones(6,points), ...
                "scheduleSpeed",10,"friction",friction,"maneuver",2,"futureNonlinear",~robust, ...
                "geometricRows",geometric,"domainErrorBound",0.02*ones(6,2), ...
                "initialErrorBound",0.01*ones(6,2),"planCount",4);
            data = repmat(data,2,1);data(2).maneuver = 3;
            expected = avoidanceSafetyGeometry('projectRows',data);
            actual = avoidanceProjectedRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end

        function nativeSupportsPreserveAllHalfspaceRows(testCase,robust,targetCount)
            target = struct("center",[50;1;-10;0;0;0;pi;0],"radius",0.01*ones(8,1), ...
                "contract",struct("jerkBound",[0.1;0.1],"yawAccelerationBound",0.01), ...
                "nominalEnd",[49.5;1;-10;0;0;0;pi;0],"useNominalEnd",~robust, ...
                "anticipate",~robust,"nextRadius",0.02*ones(8,1),"halfLength",2.5,"halfWidth",1);
            boundary = struct("coefficients",[-0.001,0.02,0],"safeSideSign",1, ...
                "longitudinalDirection",[1;0],"lateralDirection",[0;1],"origin",[0;-10], ...
                "parameterRange",[-200;200],"normalDistanceErrorBound",0.01);
            points = 2+6*double(robust);
            data = struct("frame",[2;-1;cos(0.2);sin(0.2);-sin(0.2);cos(0.2);0.2;0.01;0.02;0.003;30;35], ...
                "nominal",repmat([32;0.1;0.05;10;0.1;0.02],1,points), ...
                "targets",repmat(target,targetCount,1),"boundaries",boundary, ...
                "settings",[2.5;1;0.4;8;0.25],"duration",0.05,"degree",7,"robust",robust);
            data = repmat(data,2,1);
            data(2).nominal(1,:) = 33;
            expected = avoidanceSafetyGeometry('cellRows',data);
            actual = avoidanceCellRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end
    end
end
