classdef avoidanceNativeGeometryTest < matlab.unittest.TestCase
    properties (TestParameter)
        hasTarget = struct('absent',false,'present',true)
    end
    methods (TestClassSetup)
        function addPaths(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"controller")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(root,"solver","bicycle")));
        end
    end
    methods (Test)
        function nativeProjectionPreservesUncertaintyAndLocalRows(testCase)
            points = 8;
            tube = struct("stage",2, ...
                "map",reshape(sin(1:6*4*points),6,4,points)/100, ...
                "offset",repmat([30;0.1;0.02;10;0.2;0.01],1,points), ...
                "localStateMap",repmat(eye(6),1,1,points), ...
                "localInputMap",reshape(cos(1:6*2*points),6,2,points)/100, ...
                "localOffset",repmat([0.5;0;0;0;0;0],1,points), ...
                "numericalRadius",1e-8*ones(6,points));
            geometric = struct("state",[0,1,0,0,0,0;0,-1,0,0,0,0], ...
                "bound",10*ones(2,points),"source",[1;2],"normal",zeros(2,0));
            data = struct("tube",tube,"stateRadius",0.001*ones(6,points), ...
                "geometricRows",geometric,"planCount",4);
            data = repmat(data,2,1);data(2).stateRadius = 2*data(2).stateRadius;
            expected = avoidanceSafetyGeometry.projectRows(data);
            actual = avoidanceProjectedRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end

        function nativeNodeRowsMatchTheInterpretedNodeRows(testCase,hasTarget)
            target = struct("center",[50;1;-10;0;0;0;pi;0],"radius",0.01*ones(8,1),"halfLength",2.5,"halfWidth",1);
            boundary = struct("coefficients",[-0.001,0.02,0],"safeSideSign",1, ...
                "longitudinalDirection",[1;0],"lateralDirection",[0;1],"origin",[0;-10], ...
                "parameterRange",[-200;200],"normalDistanceErrorBound",0.01,"coverageRequired",1);
            data = struct("frame",[2;-1;cos(0.2);sin(0.2);-sin(0.2);cos(0.2);0.2;0.01;0.02;0.003;30;35], ...
                "pose",[2;-1;cos(.2);sin(.2);-sin(.2);cos(.2);zeros(8,1);.2;0;0;1;0;0;0;0], ...
                "domain",zeros(7,1),"nominal",[32;0.1;0.05;10;0.1;0.02], ...
                "target",target,"hasTarget",hasTarget,"boundaries",boundary, ...
                "settings",[2.5;1;0.4;8],"duration",0,"degree",0,"normal",zeros(2,0));
            data = repmat(data,2,1);data(2).nominal(1) = 33;
            expected = avoidanceSafetyGeometry.cellRows(data);
            actual = avoidanceCellRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
            testCase.verifySize(expected(1).bound,[size(expected(1).state,1),1]);
            tube = struct("stage",2,"map",reshape(sin(1:6*4),6,4)/100,"offset",[30;0.1;0.02;10;0.2;0.01], ...
                "localStateMap",eye(6)+0.01*reshape(cos(1:36),6,6),"localInputMap",reshape(cos(1:12),6,2)/100, ...
                "localOffset",[0.5;0;0;0;0;0],"numericalRadius",1e-8*ones(6,1));
            projection = struct("tube",tube,"stateRadius",0.001*ones(6,1), ...
                "geometricRows",expected(1),"planCount",4);
            testCase.verifyEqual(avoidanceProjectedRowsKernelMex(projection), ...
                avoidanceSafetyGeometry.projectRows(projection),AbsTol=1e-10);
        end

        function nativeSupportsPreserveAllHalfspaceRows(testCase,hasTarget)
            target = struct("center",[50;1;-10;0;0;0;pi;0],"radius",0.01*ones(8,1),"halfLength",2.5,"halfWidth",1);
            boundary = struct("coefficients",[-0.001,0.02,0],"safeSideSign",1, ...
                "longitudinalDirection",[1;0],"lateralDirection",[0;1],"origin",[0;-10], ...
                "parameterRange",[-200;200],"normalDistanceErrorBound",0.01,"coverageRequired",1);
            points = 8;
            data = struct("frame",[2;-1;cos(0.2);sin(0.2);-sin(0.2);cos(0.2);0.2;0.01;0.02;0.003;30;35], ...
                "pose",[2;-1;cos(.2);sin(.2);-sin(.2);cos(.2);zeros(8,1);.2;0;0;1;0;0;0;0], ...
                "domain",zeros(7,1), ...
                "nominal",repmat([32;0.1;0.05;10;0.1;0.02],1,points), ...
                "target",target,"hasTarget",hasTarget,"boundaries",boundary, ...
                "settings",[2.5;1;0.4;8],"duration",0.05,"degree",7,"normal",zeros(2,0));
            data = repmat(data,2,1);
            data(2).nominal(1,:) = 33;
            if hasTarget
                % Whole-hold cells do not enclose NRMM targets; both
                % implementations refuse them.
                testCase.verifyError(@() avoidanceSafetyGeometry.cellRows(data), ...
                    "collisionAvoidanceController:unsupportedWholeHoldTarget");
                testCase.verifyError(@() avoidanceCellRowsKernelMex(data), ...
                    "collisionAvoidanceController:unsupportedWholeHoldTarget");
                return;
            end
            expected = avoidanceSafetyGeometry.cellRows(data);
            actual = avoidanceCellRowsKernelMex(data);
            testCase.verifyEqual(actual,expected,AbsTol=1e-10);
        end
    end
end
