classdef circularCenterlineCruiseScenarioTest < matlab.unittest.TestCase
% circularCenterlineCruiseScenarioTest Circular-arc cruise behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function twoControlIntervalsBeginLeftArcTracking(testCase)
            result = runCircularCenterlineCruiseScenario( ...
                Duration=0.1, Radius=100.0, ...
                Plot=false, Report=false);

            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.geometry.type, ...
                "circularArc");
            testCase.verifyEqual(result.scenario.geometry.direction, ...
                "left");
            testCase.verifyEqual(result.scenario.geometry.radius, ...
                100.0, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.geometry.curvature, ...
                0.01, RelTol=1.0e-14);
            testCase.verifyEqual(result.controlState(1, 1:3), ...
                zeros(1, 3), AbsTol=1.0e-12);
            testCase.verifyEqual(result.controlState(1, 4), ...
                result.scenario.referenceSpeed, AbsTol=0.0);
            testCase.verifyEqual(result.controlState(1, 6), ...
                result.scenario.referenceSpeed ...
                * result.scenario.geometry.curvature, ...
                AbsTol=0.0);
            expectedCorneringStiffness = [ ...
                sum(result.plant.parameters.corneringStiffness(1:2)); ...
                sum(result.plant.parameters.corneringStiffness(3:4))];
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.corneringStiffness, ...
                expectedCorneringStiffness, ...
                RelTol=1.0e-12);
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyTrue( ...
                result.metrics.controllerCompletedScenario);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteSpeedError, ...
                result.criteria.maximumAbsoluteSpeedError);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteLateralError, ...
                result.criteria.maximumAbsoluteLateralError);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteHeadingError, ...
                result.criteria.maximumAbsoluteHeadingError);
            testCase.verifyGreaterThan( ...
                result.metrics.meanFrontWheelSteeringAngle, 0.005);
            testCase.verifyGreaterThan(result.controlState(end, 3), 0.0);
            testCase.verifyTrue(result.metrics.speedWithinTolerance);
            testCase.verifyTrue(result.metrics.lateralWithinTolerance);
            testCase.verifyTrue(result.metrics.headingWithinTolerance);
            testCase.verifyFalse(isfield(result, "diagnostics"));
        end
    end
end
