classdef circularCenterlineStraightTargetAvoidanceScenarioTest ...
        < matlab.unittest.TestCase
% circularCenterlineStraightTargetAvoidanceScenarioTest Arc avoidance behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(repositoryRoot,"config")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function uncertifiedFullHorizonPreservesTheConstructedTargetGeometry( ...
                testCase)
            result = ...
                runCircularCenterlineStraightTargetAvoidanceScenario( ...
                    Duration=0.4, ControllerConfiguration=finiteSensingValidationConfig(), ...
                    Plot=false, Report=false);
            geometry = result.scenario.geometry;
            targetPositionAtCollision = ...
                geometry.targetInitialPosition ...
                + geometry.nominalCollisionTime ...
                    * geometry.targetVelocity;

            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetSampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 8);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 0);
            testCase.verifyEqual( ...
                result.scenario.geometry.type, ...
                "circularArcStraightTargetCollision");
            testCase.verifyEqual( ...
                result.avoidance.targetInitialDistance, ...
                50.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                geometry.targetInitialPosition, ...
                result.avoidance.targetInitialPosition, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                geometry.targetVelocity, ...
                result.avoidance.targetVelocity, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                targetPositionAtCollision, ...
                geometry.nominalTargetCollisionPosition, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                geometry.targetCollisionLateralOffset, ...
                1.5, AbsTol=0.0);
            testCase.verifyEmpty(result.command);
            testCase.verifyTrue(result.failure.occurred);
            testCase.verifyEqual(result.failure.identifier,"collisionAvoidanceController:invalidExactScene");
            testCase.verifyFalse( ...
                result.metrics.controllerCompletedScenario);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.length, ...
                5.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.width, ...
                2.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.rangeMaximum, 30.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadBoundaryOffsets, ...
                [6.0; 8.0], AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadShoulderWidth, ...
                2.6, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadOuterBoundaryOffsets, ...
                [8.6; 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadTotalWidthIncludingShoulders, ...
                19.2, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.shoulderWidthToVehicleWidthRatio, ...
                1.3, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadCurbCoveragePolicy, ...
                "perceptionLimited");
            testCase.verifyEqual( ...
                result.perception.terminalSetGeometrySource, ...
                "nominalPathFrenetOffsetBands");
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.right, ...
                [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.left, ...
                [8.0, 10.6], AbsTol=1.0e-12);
            testCase.verifyFalse(isfield(result, "diagnostics"));
            testCase.verifyFalse(isfield( ...
                result.avoidance, "passingSpeedSufficient"));
        end
    end
end
