classdef circularCenterlineCruiseScenarioTest < matlab.unittest.TestCase
% circularCenterlineCruiseScenarioTest Circular-arc cruise behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(repositoryRoot,"config")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function uncertifiedFullHorizonPreservesAnalyticArcAndPlantEvidence(testCase)
            result = runCircularCenterlineCruiseScenario( ...
                Duration=0.1, Radius=100.0, ...
                ControllerConfiguration=finiteSensingValidationConfig(), ...
                Plot=false, Report=false);

            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.geometry.type, ...
                "circularArc");
            testCase.verifyEqual(result.scenario.geometry.direction, ...
                "left");
            testCase.verifyEqual(result.scenario.geometry.radius, ...
                100.0, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.geometry.curvature, ...
                0.01, RelTol=1.0e-14);
            testCase.verifyEqual(result.controlState(1, 1:2), ...
                zeros(1, 2), AbsTol=1.0e-12);
            testCase.verifyEqual(result.controlState(1, 4), ...
                result.scenario.referenceSpeed, AbsTol=0.0);
            testCase.verifyEqual(result.controlState(1, 6), ...
                hypot(result.controlState(1,4),result.controlState(1,5)) ...
                * result.scenario.geometry.curvature, ...
                AbsTol=1.0e-12);
            expectedCorneringStiffness = [ ...
                sum(result.plant.parameters.corneringStiffness(1:2)); ...
                sum(result.plant.parameters.corneringStiffness(3:4))];
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.corneringStiffness, ...
                expectedCorneringStiffness, ...
                RelTol=1.0e-12);
            testCase.verifyTrue(result.failure.occurred);
            testCase.verifyEqual(result.failure.identifier,"collisionAvoidanceController:noCertifiedContinuation");
            testCase.verifyEmpty(result.command);
            testCase.verifyFalse(result.metrics.controllerCompletedScenario);
            testCase.verifyFalse(isfield(result, "diagnostics"));
        end
    end
end
