classdef collisionAvoidanceControllerConfigTest < matlab.unittest.TestCase
    % collisionAvoidanceControllerConfigTest Acceleration-input contract.

    properties (TestParameter)
        boundField = {"longitudinalAccelerationMinimum", ...
            "longitudinalAccelerationMaximum"}
        invalidBound = struct("notANumber", NaN, "infinite", Inf, ...
            "complex", 1.0+1.0i, "empty", [], "vector", [1.0, 2.0], ...
            "text", "4", "logical", true)
        invalidInterval = struct("zeroWidth", [0.0, 0.0], ...
            "reversed", [4.0, -8.0], "positiveOnly", [1.0, 4.0], ...
            "negativeOnly", [-8.0, -1.0])
        removedOption = { ...
            struct("certification", struct("enabled", false)), ...
            struct("certification", struct("enabled", true)), ...
            struct("disjunctive", struct("nodeBudget", 0)), ...
            struct("sequentialConvex", struct("penaltySchedule", [])), ...
            struct("collision", struct("disturbanceBound", 0)), ...
            struct("clf", struct("trustRegionScale", Inf)), ...
            struct("solver", struct("function", [])), ...
            struct("solver", struct("stepToleranceRetry", []))}
        invalidActuation = {[], 1.0, struct([])}
    end

    methods (TestClassSetup)
        function addControllerPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "controller")));
        end
    end

    methods (Test)
        function removedAlgorithmOptionsAreRejected(testCase, removedOption)
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(removedOption), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function unknownNestedOptionsAreRejected(testCase)
            override = struct("controller", struct("misspelledOption", 1));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function accelerationBoundsMustBeFiniteRealScalars( ...
                testCase, boundField, invalidBound)
            override = struct("actuation", struct(boundField, invalidBound));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function accelerationIntervalMustContainZeroWithPositiveWidth( ...
                testCase, invalidInterval)
            override = struct("actuation", struct( ...
                "longitudinalAccelerationMinimum", invalidInterval(1), ...
                "longitudinalAccelerationMaximum", invalidInterval(2)));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function actuationMustBeAScalarStructure(testCase, invalidActuation)
            override = struct("actuation", {invalidActuation});

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function singlePrecisionBoundsAreNormalizedWithoutChangingUnits(testCase)
            override = struct("actuation", struct( ...
                "longitudinalAccelerationMinimum", single(-8.0), ...
                "longitudinalAccelerationMaximum", single(4.0)));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyClass(cfg.actuation.longitudinalAccelerationMinimum, ...
                "double");
            testCase.verifyClass(cfg.actuation.longitudinalAccelerationMaximum, ...
                "double");
            testCase.verifyEqual(cfg.actuation.longitudinalAccelerationMinimum, ...
                -8.0, AbsTol=0.0);
            testCase.verifyEqual(cfg.actuation.longitudinalAccelerationMaximum, ...
                4.0, AbsTol=0.0);
        end

        function zeroMaximumStillAllowsBraking(testCase)
            override = struct("actuation", struct( ...
                "longitudinalAccelerationMaximum", 0.0));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyEqual(cfg.actuation.longitudinalAccelerationMaximum, ...
                0.0, AbsTol=0.0);
            testCase.verifyLessThan(cfg.actuation.longitudinalAccelerationMinimum, ...
                0.0);
        end
    end
end
