classdef collisionAvoidanceControllerConfigTest < matlab.unittest.TestCase
    % collisionAvoidanceControllerConfigTest Signed braking-ratio contract.

    properties (TestParameter)
        boundField = {"brakingRatioMinimum", ...
            "brakingRatioMaximum"}
        invalidBound = struct("notANumber", NaN, "infinite", Inf, ...
            "complex", 1.0+1.0i, "empty", [], "vector", [1.0, 2.0], ...
            "text", "4", "logical", true)
        invalidInterval = struct("zeroWidth", [0.0, 0.0], ...
            "reversed", [4.0, -8.0], "positiveOnly", [1.0, 4.0], ...
            "negativeOnly", [-1.0, -0.2], "outsideRange", [-1.01, 1.0])
        removedOption = { ...
            struct("nonlinear", struct("maximumIterations", 8)), ...
            struct("admission", struct("widthScale", 1.2)), ...
            struct("jointCertificate", struct("proximalWeight", .001)), ...
            struct("feedbackPrediction", struct("enabled", true)), ...
            struct("encounter", struct("taylorOrder", 6)), ...
            struct("solver", struct("frameDeadlineSeconds", 1)), ...
            struct("nonlinear", struct("maximumImprovementIterations", 0)), ...
            struct("certification", struct("enabled", false)), ...
            struct("certification", struct("enabled", true)), ...
            struct("disjunctive", struct("nodeBudget", 0)), ...
            struct("sequentialConvex", struct("penaltySchedule", [])), ...
            struct("collision", struct("disturbanceBound", 0)), ...
            struct("collision", struct("clearanceMargin", 0)), ...
            struct("clf", struct("trustRegionScale", Inf)), ...
            struct("clf", struct("relaxationWeight", 100)), ...
            struct("solver", struct("function", [])), ...
            struct("solver", struct("stepToleranceRetry", [])), ...
            struct("solver", struct("method", "nonlinearShooting")), ...
            struct("solver", struct("method", "affineSocp")), ...
            struct("nonlinear", struct("horizonSeconds", 6)), ...
            struct("nonlinear", struct("certificateStep", .005)), ...
            struct("nonlinear", struct("maximumCertificateCells", 100)), ...
            struct("nonlinear", struct("targetConsistencyTolerance", 1e-8)), ...
            struct("nonlinear", struct("initialPlan", zeros(2,8))), ...
            struct("nonlinear", struct("proposalFunction", @sin))}
        invalidCrossingGap = {-0.1, Inf, NaN, [0.1, 0.2]}
        invalidActuation = {[], 1.0, struct([])}
    end

    methods (TestClassSetup)
        function addControllerPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "controller")));
        end
    end

    methods (Test)
        function targetRearAxleDistanceIsPositiveAndIndependentOfEgoGeometry(testCase)
            cfg=collisionAvoidanceControllerConfig(struct('target',struct('rearAxleDistance',1.8)));
            testCase.verifyEqual(cfg.target.rearAxleDistance,1.8);
            testCase.verifyEqual(cfg.vehicle.lr,1.65);
            testCase.verifyError(@()collisionAvoidanceControllerConfig(struct('target',struct('rearAxleDistance',0))), ...
                'collisionAvoidanceController:invalidConfiguration');
        end
        function smallDefaultCollisionBufferCanBeExplicitlyDisabled(testCase)
            cfg = collisionAvoidanceControllerConfig();
            testCase.verifyEqual(cfg.collision.safetyMarginMeters, 0.006);
            cfg = collisionAvoidanceControllerConfig( ...
                struct('collision', struct('safetyMarginMeters', 0)));
            testCase.verifyEqual(cfg.collision.safetyMarginMeters, 0);
        end

        function collisionBufferCannotBeNegativeOrNonfinite(testCase)
            for margin = [-0.1, NaN, Inf]
                testCase.verifyError(@() collisionAvoidanceControllerConfig( ...
                    struct('collision', struct('safetyMarginMeters', margin))), ...
                    'collisionAvoidanceController:invalidConfiguration');
            end
        end

        function encounterRangeDefaultsToThirtyMetersAndMayBeUnbounded(testCase)
            cfg = collisionAvoidanceControllerConfig();
            testCase.verifyEqual(cfg.collision.encounterRangeMeters, 30);
            cfg = collisionAvoidanceControllerConfig( ...
                struct('collision', struct('encounterRangeMeters', Inf)));
            testCase.verifyEqual(cfg.collision.encounterRangeMeters, Inf);
        end

        function encounterRangeMustExceedTheCollisionBuffer(testCase)
            for range = [-1, 0, NaN, 0.006]
                testCase.verifyError(@() collisionAvoidanceControllerConfig( ...
                    struct('collision', struct('encounterRangeMeters', range))), ...
                    'collisionAvoidanceController:invalidConfiguration');
            end
        end

        function solverPrecisionAndIterationLimitsAreValidated(testCase)
            invalid = {struct("constraintTolerance", 0.0), ...
                struct("optimalityTolerance", -1.0), ...
                struct("maxIterations", 0), struct("maxIterations", 1.5), ...
                struct("maxIterations", Inf)};
            for index = 1:numel(invalid)
                testCase.verifyError(@() collisionAvoidanceControllerConfig( ...
                    struct("solver", invalid{index})), ...
                    "collisionAvoidanceController:invalidConfiguration");
            end
        end

        function crossingTimeGapMustBeFiniteAndNonnegative(testCase, invalidCrossingGap)
            override = struct("performance", struct("crossingTimeGap", invalidCrossingGap));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function theOldAccelerationGainCannotRedefineThePaperRatio(testCase)
            override = struct("model", struct( ...
                "longitudinalInputGain", 0.8));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function removedAlgorithmOptionsAreRejected(testCase, removedOption)
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(removedOption), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function unknownNestedOptionsAreRejected(testCase)
            override = struct("controller", struct("misspelledOption", 1));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function brakingRatioBoundsMustBeFiniteRealScalars( ...
                testCase, boundField, invalidBound)
            override = struct("actuation", struct(boundField, invalidBound));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function brakingRatioIntervalMustContainZeroWithPositiveWidth( ...
                testCase, invalidInterval)
            override = struct("actuation", struct( ...
                "brakingRatioMinimum", invalidInterval(1), ...
                "brakingRatioMaximum", invalidInterval(2)));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function actuationMustBeAScalarStructure(testCase, invalidActuation)
            override = struct("actuation", {invalidActuation});

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function singlePrecisionBoundsAreNormalizedWithoutChangingUnits(testCase)
            override = struct("actuation", struct( ...
                "brakingRatioMinimum", single(-1.0), ...
                "brakingRatioMaximum", single(0.5)));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyClass(cfg.actuation.brakingRatioMinimum, ...
                "double");
            testCase.verifyClass(cfg.actuation.brakingRatioMaximum, ...
                "double");
            testCase.verifyEqual(cfg.actuation.brakingRatioMinimum, ...
                -1.0, AbsTol=0.0);
            testCase.verifyEqual(cfg.actuation.brakingRatioMaximum, ...
                0.5, AbsTol=0.0);
        end

        function zeroMaximumStillAllowsBraking(testCase)
            override = struct("actuation", struct( ...
                "brakingRatioMaximum", 0.0));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyEqual(cfg.actuation.brakingRatioMaximum, ...
                0.0, AbsTol=0.0);
            testCase.verifyLessThan(cfg.actuation.brakingRatioMinimum, ...
                0.0);
        end
    end
end
