classdef collisionAvoidanceControllerConfigTest < matlab.unittest.TestCase
    % collisionAvoidanceControllerConfigTest Signed braking-ratio contract.

    properties (TestParameter)
        boundField = {"brakingRatioMinimum", ...
            "brakingRatioMaximum"}
        invalidBound = struct("notANumber", NaN, "infinite", Inf, ...
            "complex", 1.0+1.0i, "empty", [], "vector", [1.0, 2.0], ...
            "text", "4", "logical", true)
        invalidInterval = struct("zeroWidth", [0.0, 0.0], ...
            "reversed", [4.0, -8.0], "positiveOnly", [1.0, 4.0], ...
            "negativeOnly", [-1.0, -0.2], "outsideRange", [-1.01, 1.0])
        removedOption = { ...
            struct("certification", struct("enabled", false)), ...
            struct("certification", struct("enabled", true)), ...
            struct("disjunctive", struct("nodeBudget", 0)), ...
            struct("sequentialConvex", struct("penaltySchedule", [])), ...
            struct("collision", struct("disturbanceBound", 0)), ...
            struct("clf", struct("trustRegionScale", Inf)), ...
            struct("solver", struct("function", [])), ...
            struct("solver", struct("stepToleranceRetry", []))}
        invalidCrossingGap = {-0.1, Inf, NaN, [0.1, 0.2]}
        invalidActuation = {[], 1.0, struct([])}
    end

    methods (TestClassSetup)
        function addControllerPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "controller")));
        end
    end

    methods (Test)
        function solverPrecisionAndIterationLimitsAreValidated(testCase)
            invalid = {struct("constraintTolerance", 0.0), ...
                struct("optimalityTolerance", -1.0), ...
                struct("maxIterations", 0), struct("maxIterations", 1.5), ...
                struct("maxIterations", Inf)};
            for index = 1:numel(invalid)
                testCase.verifyError(@() collisionAvoidanceControllerConfig( ...
                    struct("solver", invalid{index})), ...
                    "collisionAvoidanceController:invalidConfiguration");
            end
        end

        function crossingTimeGapMustBeFiniteAndNonnegative(testCase, invalidCrossingGap)
            override = struct("performance", struct("crossingTimeGap", invalidCrossingGap));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function theOldAccelerationGainCannotRedefineThePaperRatio(testCase)
            override = struct("model", struct( ...
                "longitudinalInputGain", 0.8));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function removedAlgorithmOptionsAreRejected(testCase, removedOption)
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(removedOption), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function unknownNestedOptionsAreRejected(testCase)
            override = struct("controller", struct("misspelledOption", 1));
            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function brakingRatioBoundsMustBeFiniteRealScalars( ...
                testCase, boundField, invalidBound)
            override = struct("actuation", struct(boundField, invalidBound));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function brakingRatioIntervalMustContainZeroWithPositiveWidth( ...
                testCase, invalidInterval)
            override = struct("actuation", struct( ...
                "brakingRatioMinimum", invalidInterval(1), ...
                "brakingRatioMaximum", invalidInterval(2)));

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function actuationMustBeAScalarStructure(testCase, invalidActuation)
            override = struct("actuation", {invalidActuation});

            testCase.verifyError( ...
                @() collisionAvoidanceControllerConfig(override), ...
                "collisionAvoidanceController:invalidConfiguration");
        end

        function singlePrecisionBoundsAreNormalizedWithoutChangingUnits(testCase)
            override = struct("actuation", struct( ...
                "brakingRatioMinimum", single(-1.0), ...
                "brakingRatioMaximum", single(0.5)));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyClass(cfg.actuation.brakingRatioMinimum, ...
                "double");
            testCase.verifyClass(cfg.actuation.brakingRatioMaximum, ...
                "double");
            testCase.verifyEqual(cfg.actuation.brakingRatioMinimum, ...
                -1.0, AbsTol=0.0);
            testCase.verifyEqual(cfg.actuation.brakingRatioMaximum, ...
                0.5, AbsTol=0.0);
        end

        function zeroMaximumStillAllowsBraking(testCase)
            override = struct("actuation", struct( ...
                "brakingRatioMaximum", 0.0));

            cfg = collisionAvoidanceControllerConfig(override);

            testCase.verifyEqual(cfg.actuation.brakingRatioMaximum, ...
                0.0, AbsTol=0.0);
            testCase.verifyLessThan(cfg.actuation.brakingRatioMinimum, ...
                0.0);
        end
    end
end
