classdef computeLidarRingCurbFeaturesTest < matlab.unittest.TestCase
% computeLidarRingCurbFeaturesTest Behavior of sparse ring feature extraction.

    methods (TestClassSetup)
        function addPerceptionPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, ...
                    "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (Test)
        function returnsDocumentedFieldsAndShapes(testCase)
            frame = localSparseCircularFrame(2, 1000, 180);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            expectedFields = sort([ ...
                "heightStep"; ...
                "rangeStep"; ...
                "localHeightStd"; ...
                "localRangeStd"; ...
                "localHeightRange"; ...
                "localMeanElevation"; ...
                "chenSmoothness"; ...
                "leftSmoothArcLength"; ...
                "rightSmoothArcLength"; ...
                "sameRingSlopeMagnitude"; ...
                "sameRingSlopeChange"; ...
                "bilateralTangentDeflection"; ...
                "huangTangentialStrength"; ...
                "huangRadiusRatioDeviation"; ...
                "huangHdInRadius"; ...
                "hataDifferentialHeightResponse"; ...
                "radiusRatioReconstructionDeviation"; ...
                "wangHorizontalSpacingRatio"; ...
                "wangHorizontalSpacingExcess"; ...
                "radialSecondDifference"; ...
                "localMultiscaleHaarZ"; ...
                "localMultiscaleHaarRange"; ...
                "localChordResidual"; ...
                "hataCompressionRaw"; ...
                "hataCompressionExpected"; ...
                "hataCompressionNormalized"; ...
                "ilpLineFitResidual"; ...
                "ilpLineSlopeMagnitude"]);
            testCase.verifyEqual( ...
                sort(string(fieldnames(features))), expectedFields);
            testCase.verifyEqual( ...
                sort(string(fieldnames(validity))), ...
                sort(["base"; expectedFields]));
            testCase.verifySize(features.heightStep, [2, 1000]);
            testCase.verifySize( ...
                features.localMultiscaleHaarZ, [2, 1000, 3]);
            testCase.verifyClass(validity.chenSmoothness, "logical");
        end

        function skipsEmptyOrganizedBinsWithinValidSequence(testCase)
            frame = localSparseOpenArcFrame(1, 1000, 15, 1.0);
            validColumns = find(frame.valid);
            centerColumn = validColumns(8);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue(validity.chenSmoothness(centerColumn));
            testCase.verifyTrue(validity.localHeightStd(centerColumn));
            testCase.verifyTrue( ...
                validity.localMultiscaleHaarRange(1, centerColumn, 3));
            testCase.verifyTrue(validity.ilpLineFitResidual(centerColumn));
            testCase.verifyTrue(isnan(features.heightStep(2)));
        end

        function rejectsPathAcrossLargeMeasuredAzimuthGap(testCase)
            angles = [0.0, 1.0, 2.0, 8.0, 9.0, 10.0, 11.0, 12.0];
            frame = localFrameFromAngles(1, 100, angles, 10.0);
            validColumns = find(frame.valid);
            leftOfGap = validColumns(3);
            rightOfGap = validColumns(4);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyFalse( ...
                validity.bilateralTangentDeflection(leftOfGap));
            testCase.verifyFalse( ...
                validity.localMultiscaleHaarRange(1, leftOfGap, 1));
            testCase.verifyFalse(validity.chenSmoothness(rightOfGap));
            testCase.verifyTrue(validity.heightStep(leftOfGap));
            testCase.verifyTrue(isnan( ...
                features.localChordResidual(leftOfGap)));
        end

        function wrapsMeasuredAzimuthThroughThreeHundredSixtyDegrees( ...
                testCase)
            angles = [356.0, 357.0, 358.0, 359.0, 0.0, 1.0, 2.0, 3.0];
            frame = localFrameFromAngles(1, 200, angles, 10.0);
            zeroDegreeColumn = localColumnAtAngle(frame, 0.0);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue( ...
                validity.bilateralTangentDeflection(zeroDegreeColumn));
            testCase.verifyTrue( ...
                validity.huangTangentialStrength(zeroDegreeColumn));
            testCase.verifyTrue( ...
                validity.localMultiscaleHaarRange( ...
                    1, zeroDegreeColumn, 1));
            testCase.verifyEqual( ...
                features.bilateralTangentDeflection(zeroDegreeColumn), ...
                deg2rad(1.0), AbsTol=1.0e-12);
        end

        function chenAndHuangMatchVectorDefinitions(testCase)
            frame = localSparseCircularFrame(1, 1000, 360);
            validColumns = find(frame.valid);
            centerColumn = validColumns(100);
            [centerPoint, leftPoints, rightPoints] = ...
                localDefinitionPoints(frame, centerColumn, 2);
            neighborSum = sum([leftPoints; rightPoints], 1);
            expectedChen = norm(neighborSum - 4.0 * centerPoint) ...
                / (4.0 * norm(centerPoint));
            leftImmediate = leftPoints(1, :);
            rightImmediate = rightPoints(1, :);
            chord = rightImmediate - leftImmediate;
            expectedHuang = abs(dot(centerPoint, chord)) ...
                / (norm(centerPoint) * norm(chord));

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue(validity.chenSmoothness(centerColumn));
            testCase.verifyEqual( ...
                features.chenSmoothness(centerColumn), expectedChen, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.huangTangentialStrength(centerColumn), ...
                expectedHuang, AbsTol=1.0e-12);
        end

        function huangUsesOnlyRoadPlaneProjection(testCase)
            referenceFrame = localSparseCircularFrame(1, 1000, 360);
            modifiedFrame = referenceFrame;
            validColumns = find(referenceFrame.valid);
            centerColumn = validColumns(100);
            leftColumn = validColumns(99);
            rightColumn = validColumns(101);
            modifiedFrame.z(centerColumn) = 20.0;
            modifiedFrame.z(leftColumn) = -15.0;
            modifiedFrame.z(rightColumn) = 35.0;
            centerPoint = [ ...
                referenceFrame.x(centerColumn), ...
                referenceFrame.y(centerColumn)];
            neighborChord = [ ...
                referenceFrame.x(rightColumn) ...
                    - referenceFrame.x(leftColumn), ...
                referenceFrame.y(rightColumn) ...
                    - referenceFrame.y(leftColumn)];
            expectedHuang = abs(dot(centerPoint, neighborChord)) ...
                / (norm(centerPoint) * norm(neighborChord));

            [referenceFeatures, referenceValidity] = ...
                computeLidarRingCurbFeatures(referenceFrame, struct());
            [modifiedFeatures, modifiedValidity] = ...
                computeLidarRingCurbFeatures(modifiedFrame, struct());

            testCase.verifyTrue( ...
                modifiedValidity.huangTangentialStrength(centerColumn));
            testCase.verifyEqual( ...
                modifiedFeatures.huangTangentialStrength(centerColumn), ...
                expectedHuang, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                modifiedFeatures.huangTangentialStrength(centerColumn), ...
                referenceFeatures.huangTangentialStrength(centerColumn), ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                modifiedValidity.huangTangentialStrength(centerColumn), ...
                referenceValidity.huangTangentialStrength(centerColumn));
        end

        function reconstructsConstantRadiusAndWangSpacing(testCase)
            frame = localSparseCircularFrame(1, 1000, 360);
            centerColumn = find(frame.valid, 1, "first");

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue( ...
                validity.radiusRatioReconstructionDeviation(centerColumn));
            testCase.verifyTrue( ...
                validity.huangRadiusRatioDeviation(centerColumn));
            testCase.verifyEqual( ...
                features.huangRadiusRatioDeviation(centerColumn), ...
                0.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.radiusRatioReconstructionDeviation(centerColumn), ...
                0.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.wangHorizontalSpacingRatio(centerColumn), ...
                1.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.wangHorizontalSpacingExcess(centerColumn), ...
                0.0, AbsTol=1.0e-12);
        end

        function smoothArcStopsAtChenRoughNeighbor(testCase)
            smoothFrame = localSparseCircularFrame(1, 1000, 360);
            roughFrame = smoothFrame;
            validColumns = find(smoothFrame.valid);
            centerColumn = validColumns(100);
            roughNeighborColumn = validColumns(105);
            roughFrame.z(roughNeighborColumn) = 3.0;
            cfg = struct( ...
                "ringFeatureSmoothArcMaximumSearchRadius", 5);

            [smoothFeatures, smoothValidity] = ...
                computeLidarRingCurbFeatures(smoothFrame, cfg);
            [roughFeatures, roughValidity] = ...
                computeLidarRingCurbFeatures(roughFrame, cfg);

            testCase.verifyTrue( ...
                smoothValidity.rightSmoothArcLength(centerColumn));
            testCase.verifyTrue( ...
                roughValidity.rightSmoothArcLength(centerColumn));
            testCase.verifyGreaterThan( ...
                smoothFeatures.rightSmoothArcLength(centerColumn), ...
                roughFeatures.rightSmoothArcLength(centerColumn));
        end

        function computesLocalRangeHaarAndIlpResidual(testCase)
            frame = localSparseOpenArcFrame(1, 1000, 15, 1.0);
            validColumns = find(frame.valid);
            centerColumn = validColumns(8);
            frame.z(validColumns) = 0.2 * (1:numel(validColumns));
            adjacentChordLength = hypot( ...
                frame.x(validColumns(9)) - frame.x(centerColumn), ...
                frame.y(validColumns(9)) - frame.y(centerColumn));
            expectedMeanElevation = mean(frame.z(validColumns(6:10)));
            expectedSlopeMagnitude = 0.2 / adjacentChordLength;

            [linearFeatures, linearValidity] = ...
                computeLidarRingCurbFeatures(frame, struct());
            frame.z(centerColumn) = frame.z(centerColumn) + 1.0;
            [roughFeatures, roughValidity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue( ...
                linearValidity.localHeightRange(centerColumn));
            testCase.verifyGreaterThan( ...
                linearFeatures.localHeightRange(centerColumn), 0.0);
            testCase.verifyEqual( ...
                linearFeatures.localMeanElevation(centerColumn), ...
                expectedMeanElevation, AbsTol=1.0e-12);
            testCase.verifyTrue( ...
                linearValidity.localMultiscaleHaarZ( ...
                    1, centerColumn, 3));
            testCase.verifyTrue( ...
                linearValidity.ilpLineFitResidual(centerColumn));
            testCase.verifyLessThan( ...
                linearFeatures.ilpLineFitResidual(centerColumn), 1.0e-10);
            testCase.verifyEqual( ...
                linearFeatures.ilpLineSlopeMagnitude(centerColumn), ...
                expectedSlopeMagnitude, AbsTol=1.0e-10);
            testCase.verifyTrue( ...
                roughValidity.ilpLineFitResidual(centerColumn));
            testCase.verifyGreaterThan( ...
                roughFeatures.ilpLineFitResidual(centerColumn), 0.1);
        end

        function computesSameRingSlopeAndHataDifferential(testCase)
            frame = localFrameFromAngles( ...
                1, 100, [0.0, 1.0, 2.0], 10.0);
            validColumns = find(frame.valid);
            centerColumn = validColumns(2);
            frame.z(validColumns) = [0.0, 1.0, 3.0];
            leftDistance = hypot( ...
                frame.x(centerColumn) - frame.x(validColumns(1)), ...
                frame.y(centerColumn) - frame.y(validColumns(1)));
            rightDistance = hypot( ...
                frame.x(validColumns(3)) - frame.x(centerColumn), ...
                frame.y(validColumns(3)) - frame.y(centerColumn));
            expectedSlopeMagnitude = max( ...
                abs(atan2(1.0, leftDistance)), ...
                abs(atan2(2.0, rightDistance)));

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue( ...
                validity.sameRingSlopeMagnitude(centerColumn));
            testCase.verifyEqual( ...
                features.sameRingSlopeMagnitude(centerColumn), ...
                expectedSlopeMagnitude, AbsTol=1.0e-12);
            testCase.verifyTrue( ...
                validity.hataDifferentialHeightResponse(centerColumn));
            testCase.verifyEqual( ...
                features.hataDifferentialHeightResponse(centerColumn), ...
                6.0, AbsTol=1.0e-12);
            testCase.verifyTrue( ...
                validity.sameRingSlopeMagnitude(validColumns(1)));
            testCase.verifyFalse( ...
                validity.hataDifferentialHeightResponse(validColumns(1)));
        end

        function huangHdIsZeroForThreeRingPlanarProfile(testCase)
            frame = localThreeRingHuangFrame([0.0, 0.6, 1.6]);
            pointColumn = find(frame.valid(3, :), 1, "first");

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());

            testCase.verifyTrue( ...
                validity.huangHdInRadius(1, pointColumn));
            testCase.verifyFalse( ...
                validity.huangHdInRadius(2, pointColumn));
            testCase.verifyTrue( ...
                validity.huangHdInRadius(3, pointColumn));
            testCase.verifyEqual( ...
                features.huangHdInRadius(1, pointColumn), ...
                0.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.huangHdInRadius(3, pointColumn), ...
                0.0, AbsTol=1.0e-12);
        end

        function huangHdMatchesMiddleAndEndpointPerturbations(testCase)
            perturbation = 0.4;
            middleFrame = localThreeRingHuangFrame( ...
                [0.0, 0.6 + perturbation, 1.6]);
            endpointFrame = localThreeRingHuangFrame( ...
                [0.0, 0.6, 1.6 + perturbation]);
            pointColumn = find(middleFrame.valid(3, :), 1, "first");
            distanceRatio = 5.0 / 3.0;
            expectedMiddleResidual = ...
                perturbation * (1.0 + distanceRatio);

            [middleFeatures, middleValidity] = ...
                computeLidarRingCurbFeatures(middleFrame, struct());
            [endpointFeatures, endpointValidity] = ...
                computeLidarRingCurbFeatures(endpointFrame, struct());

            testCase.verifyTrue( ...
                middleValidity.huangHdInRadius(3, pointColumn));
            testCase.verifyEqual( ...
                middleFeatures.huangHdInRadius(3, pointColumn), ...
                expectedMiddleResidual, AbsTol=1.0e-12);
            testCase.verifyTrue( ...
                endpointValidity.huangHdInRadius(3, pointColumn));
            testCase.verifyEqual( ...
                endpointFeatures.huangHdInRadius(3, pointColumn), ...
                perturbation, AbsTol=1.0e-12);
        end

        function huangHdIsInvariantToRingIndexDirection(testCase)
            frame = localThreeRingHuangFrame([0.0, 1.0, 1.6]);
            reversedFrame = frame;
            reversedFrame.x = flip(frame.x, 1);
            reversedFrame.y = flip(frame.y, 1);
            reversedFrame.z = flip(frame.z, 1);
            reversedFrame.range = flip(frame.range, 1);
            reversedFrame.valid = flip(frame.valid, 1);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct());
            [reversedFeatures, reversedValidity] = ...
                computeLidarRingCurbFeatures(reversedFrame, struct());

            testCase.verifyEqual( ...
                reversedFeatures.huangHdInRadius, ...
                flip(features.huangHdInRadius, 1), AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                reversedValidity.huangHdInRadius, ...
                flip(validity.huangHdInRadius, 1));
        end

        function computesHataAdjacentRingCompression(testCase)
            sensorHeight = 2.35;
            verticalAngles = [-10.0, -20.0];
            upperRange = sensorHeight / tand(10.0);
            lowerRange = sensorHeight / tand(20.0);
            frame = localTwoRingHataFrame( ...
                upperRange, lowerRange, 15.0);
            lowerColumn = find(frame.valid(2, :), 1, "first");
            cfg = struct( ...
                "ringFeatureSensorHeightM", sensorHeight, ...
                "ringFeatureVerticalAnglesDegrees", verticalAngles);

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, cfg);

            testCase.verifyTrue( ...
                validity.hataCompressionRaw(2, lowerColumn));
            testCase.verifyEqual( ...
                features.hataCompressionExpected(2, lowerColumn), ...
                upperRange - lowerRange, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.hataCompressionRaw(2, lowerColumn), ...
                0.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                features.hataCompressionNormalized(2, lowerColumn), ...
                0.0, AbsTol=1.0e-12);
            testCase.verifyFalse(any( ...
                validity.hataCompressionRaw(1, :), "all"));
        end

        function leavesHataInvalidWhenUpperPairIsAbsent(testCase)
            frame = localTwoRingHataFrame(12.0, 6.0, 15.0);
            frame.valid(1, :) = false;
            frame.x(1, :) = NaN;
            frame.y(1, :) = NaN;
            frame.z(1, :) = NaN;
            frame.range(1, :) = NaN;

            [features, validity] = ...
                computeLidarRingCurbFeatures(frame, struct( ...
                    "ringFeatureVerticalAnglesDegrees", [-10.0, -20.0]));

            testCase.verifyFalse(any( ...
                validity.hataCompressionRaw(2, :), "all"));
            testCase.verifyTrue(all(isnan( ...
                features.hataCompressionNormalized(2, :)), "all"));
        end

        function reflectionAcrossSensorXAxisPreservesAllFeatures(testCase)
            frame = localSparseCircularFrame(3, 1000, 360);
            reflectedFrame = frame;
            reflectedFrame.y = -reflectedFrame.y;
            cfg = struct( ...
                "ringFeatureVerticalAnglesDegrees", ...
                [-10.0, -20.0, -30.0]);

            [referenceFeatures, referenceValidity] = ...
                computeLidarRingCurbFeatures(frame, cfg);
            [reflectedFeatures, reflectedValidity] = ...
                computeLidarRingCurbFeatures(reflectedFrame, cfg);

            testCase.verifyEqual( ...
                reflectedFeatures, referenceFeatures, AbsTol=1.0e-10);
            testCase.verifyEqual( ...
                reflectedValidity, referenceValidity);
        end
    end
end

function frame = localSparseCircularFrame( ...
        numberOfRings, numberOfBins, numberOfReturns)
    angles = 360.0 * (0:(numberOfReturns - 1)) / numberOfReturns;
    frame = localFrameFromAngles( ...
        numberOfRings, numberOfBins, angles, ...
        (10.0 + (0:(numberOfRings - 1)).'));
end

function frame = localSparseOpenArcFrame( ...
        numberOfRings, numberOfBins, numberOfReturns, angleStep)
    angles = angleStep * (0:(numberOfReturns - 1));
    frame = localFrameFromAngles( ...
        numberOfRings, numberOfBins, angles, ...
        (10.0 + (0:(numberOfRings - 1)).'));
end

function frame = localFrameFromAngles( ...
        numberOfRings, numberOfBins, angles, radius)
    frame = struct( ...
        "x", nan(numberOfRings, numberOfBins), ...
        "y", nan(numberOfRings, numberOfBins), ...
        "z", nan(numberOfRings, numberOfBins), ...
        "range", nan(numberOfRings, numberOfBins), ...
        "valid", false(numberOfRings, numberOfBins));
    columns = round(linspace(1, numberOfBins, numel(angles)));
    ringRadius = reshape(radius, [], 1);
    ringRadius = repmat(ringRadius, 1, numel(angles));
    angleMatrix = repmat(angles, numberOfRings, 1);
    frame.x(:, columns) = ringRadius .* cosd(angleMatrix);
    frame.y(:, columns) = ringRadius .* sind(angleMatrix);
    frame.z(:, columns) = repmat( ...
        (0:(numberOfRings - 1)).', 1, numel(angles));
    frame.range(:, columns) = ringRadius;
    frame.valid(:, columns) = true;
end

function column = localColumnAtAngle(frame, targetAngle)
    columns = find(frame.valid(1, :));
    angles = mod(atan2d( ...
        frame.y(1, columns), frame.x(1, columns)), 360.0);
    [~, index] = min(abs( ...
        mod(angles - targetAngle + 180.0, 360.0) - 180.0));
    column = columns(index);
end

function [centerPoint, leftPoints, rightPoints] = ...
        localDefinitionPoints(frame, centerColumn, radius)
    columns = find(frame.valid(1, :));
    angles = mod(atan2d( ...
        frame.y(1, columns), frame.x(1, columns)), 360.0);
    [~, order] = sort(angles);
    columns = columns(order);
    centerIndex = find(columns == centerColumn, 1);
    pointCount = numel(columns);
    leftIndices = mod(centerIndex - (1:radius) - 1, pointCount) + 1;
    rightIndices = mod(centerIndex + (1:radius) - 1, pointCount) + 1;
    centerPoint = localPoint(frame, centerColumn);
    leftPoints = [ ...
        localPoint(frame, columns(leftIndices(1))); ...
        localPoint(frame, columns(leftIndices(2)))];
    rightPoints = [ ...
        localPoint(frame, columns(rightIndices(1))); ...
        localPoint(frame, columns(rightIndices(2)))];
end

function point = localPoint(frame, column)
    point = [frame.x(1, column), frame.y(1, column), frame.z(1, column)];
end

function frame = localTwoRingHataFrame( ...
        upperRange, lowerRange, azimuthDegrees)
    frame = struct( ...
        "x", nan(2, 20), ...
        "y", nan(2, 20), ...
        "z", nan(2, 20), ...
        "range", nan(2, 20), ...
        "valid", false(2, 20));
    upperColumn = 7;
    lowerColumn = 13;
    frame.x(1, upperColumn) = upperRange * cosd(azimuthDegrees);
    frame.y(1, upperColumn) = upperRange * sind(azimuthDegrees);
    frame.z(1, upperColumn) = -2.35;
    frame.range(1, upperColumn) = upperRange;
    frame.valid(1, upperColumn) = true;
    frame.x(2, lowerColumn) = lowerRange * cosd(azimuthDegrees);
    frame.y(2, lowerColumn) = lowerRange * sind(azimuthDegrees);
    frame.z(2, lowerColumn) = -2.35;
    frame.range(2, lowerColumn) = lowerRange;
    frame.valid(2, lowerColumn) = true;
end

function frame = localThreeRingHuangFrame(heights)
    numberOfBins = 20;
    pointColumn = 10;
    xCoordinates = [10.0; 7.0; 2.0];
    frame = struct( ...
        "x", nan(3, numberOfBins), ...
        "y", nan(3, numberOfBins), ...
        "z", nan(3, numberOfBins), ...
        "range", nan(3, numberOfBins), ...
        "valid", false(3, numberOfBins));
    frame.x(:, pointColumn) = xCoordinates;
    frame.y(:, pointColumn) = 0.0;
    frame.z(:, pointColumn) = heights(:);
    frame.range(:, pointColumn) = abs(xCoordinates);
    frame.valid(:, pointColumn) = true;
end
