classdef controllerSourceBudgetTest < matlab.unittest.TestCase
    %controllerSourceBudgetTest Enforce the complete core source-file limit.

    methods (Test)
        function coreIncludingNativeSourcesAndConfigFitsTwentyFiles(testCase)
            root = fileparts(fileparts(mfilename('fullpath')));
            sources = [dir(fullfile(root,'controller','**','*.m')); ...
                dir(fullfile(root,'controller','**','*.cpp')); ...
                dir(fullfile(root,'controller','**','*.c')); ...
                dir(fullfile(root,'controller','**','*.h')); ...
                dir(fullfile(root,'controller','**','*.hpp')); ...
                dir(fullfile(root,'config','collisionAvoidanceControllerConfig.m'))];

            testCase.verifyLessThanOrEqual(numel(sources),20, ...
                'Core sources include all controller subdirectories and controller configuration.');
        end
    end
end
