classdef encounterTestFixture
    %encounterTestFixture Declared-model fixtures, not physical validation data.
    methods (Static)
        function target = stationaryTarget()
            % A persistent remote target for objective/plant-unit tests.
            target = struct("trackId",1,"targetPositionInertial",[1000;1000], ...
                "targetVelocityInertial",zeros(2,1),"targetAccelerationInertial",zeros(2,1), ...
                "targetHeadingInertial",0,"targetYawRate",0, ...
                "predictionMotion",struct("kind","nrmm-motion-v1","curvatureMaximum",0.05));
        end

        function [ego, target, route, cfg] = crossing()
            cfg = collisionAvoidanceControllerConfig(struct("controller", ...
                struct("horizonSteps", 16, "sampleTime", 0.1), ...
                "model", struct("lateralDomainRadius", 2,"linearizationPolicy","cruise"), "referenceSpeed", 8));
            ego = struct("position", [0; 0], "yaw", 0, "speed", 8, "stateTime", 0, ...
                "perception", struct("time",0,"range",16,"completeWithinRange",true));
            route = [-100, 0; 2000, 0];
            motion = struct("kind", "nrmm-motion-v1", "curvatureMaximum", 0.05);
            target = struct("trackId", 1, "targetPositionInertial", [15; -4], ...
                "targetVelocityInertial", [0; 32], "targetAccelerationInertial", [0; 0], ...
                "targetHeadingInertial", pi/2, "targetYawRate", 0, "predictionMotion", motion);
        end

        function ego = nextEgo(stored, lane)
            state = stored.predictedState(:, 2);
            [position, heading] = laneGeometry.fromFrenet(state, lane);
            ego = struct("position", position, "yaw", heading, "speed", state(4), ...
                "lateralVelocity", state(5), "yawRate", state(6), ...
                "stateTime", stored.stateTime+stored.identity.configuration.controller.sampleTime, ...
                "heldActuatorInput", stored.appliedInput);
            if isfield(stored,"confirmation") && ~isempty(stored.confirmation)
                ego.perception = struct("time",ego.stateTime,"range",stored.confirmation.range, ...
                    "completeWithinRange",true);
            end
        end

        function [ego,target,road,cfg] = circularCrossing(curvature)
            % Mirror the complete encounter for negative curvature.
            cfg=collisionAvoidanceControllerConfig(struct('referenceSpeed',8, ...
                'controller',struct('sampleTime',.05,'horizonSteps',32,'minimumHorizonSteps',1), ...
                'model',struct('lateralDomainRadius',4), ...
                'solver',struct('frameDeadlineSeconds',30,'certificateSearchTimeLimit',30)));
            curve=struct('origin',[0;0],'heading',0,'curvature',curvature,'length',340);
            road=struct('referenceCurve',curve, ...
                'centerline',laneGeometry.referencePose(linspace(0,340,201),0,curve).');
            state=ltvBicycleModel.cruiseEquilibrium(curvature,cfg);
            ego=struct('position',[0;0],'yaw',state(3),'speed',state(4), ...
                'lateralVelocity',state(5),'yawRate',state(6),'stateTime',0, ...
                'controllerStateErrorBound',zeros(6,1), ...
                'perception',struct('time',0,'range',16,'completeWithinRange',true));
            [point,heading]=laneGeometry.referencePose(15,0,curve);
            normal=sign(curvature)*[-sin(heading);cos(heading)];
            target=struct('trackId',1,'targetPositionInertial',point-7.5*normal, ...
                'targetVelocityInertial',4*normal,'targetAccelerationInertial',zeros(2,1), ...
                'targetHeadingInertial',heading+sign(curvature)*pi/2,'targetYawRate',0, ...
                'targetPositionInertialErrorBound',zeros(2,1), ...
                'targetVelocityInertialErrorBound',zeros(2,1), ...
                'targetAccelerationInertialErrorBound',zeros(2,1), ...
                'targetYawErrorBound',0,'targetYawRateErrorBound',0, ...
                'predictionMotion',struct('kind','nrmm-motion-v1','curvatureMaximum',0.05));
        end

        function [ego,target,road,cfg] = nrmmLead(scales)
            % Straight road; a 2 m/s target 15 m ahead on a 50 m-radius NRMM
            % arc with the recorded estimator ego bound; scales are the
            % target-reaction strengths tried in order.
            cfg=collisionAvoidanceControllerConfig(struct('referenceSpeed',8, ...
                'controller',struct('sampleTime',.05,'horizonSteps',32,'minimumHorizonSteps',1), ...
                'model',struct('lateralDomainRadius',4), ...
                'solver',struct('frameDeadlineSeconds',60,'certificateSearchTimeLimit',60), ...
                'feedbackPrediction',struct('targetReaction',struct('inputWeightScales',scales))));
            road=[-100,0;2000,0];
            ego=struct('position',[0;0],'yaw',0,'speed',8,'stateTime',0, ...
                'controllerStateErrorBound',[.076;.076;.048;.089;.497;.0015], ...
                'perception',struct('time',0,'range',16,'completeWithinRange',true));
            target=struct('trackId',1,'targetPositionInertial',[15;0],'targetVelocityInertial',[2;0], ...
                'targetAccelerationInertial',[0;.08],'targetHeadingInertial',0,'targetYawRate',.04, ...
                'targetPositionInertialErrorBound',[.1;.1],'targetVelocityInertialErrorBound',[.05;.05], ...
                'targetAccelerationInertialErrorBound',[.02;.02],'targetYawErrorBound',.01, ...
                'targetYawRateErrorBound',.01, ...
                'predictionMotion',struct('kind','nrmm-motion-v1','curvatureMaximum',.03,'speedRateMaximum',1));
        end

        function result = fail(~, ~)
            result = struct("decision", [], "exitFlag", -999, "output", struct());
        end
    end
end
