classdef estimatedStateAvoidanceScenarioTest < matlab.unittest.TestCase
% estimatedStateAvoidanceScenarioTest NRMM estimator/controller integration.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "config")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "estimator"), ...
                    IncludingSubfolders=true));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function configuredSensorsProduceCascadedHighGainDesign(testCase)
            cfg = estimatorControllerIntegrationConfig();
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 15.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            [context, initialization] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);
            design = initialization.observerDesign;

            testCase.verifyEqual( ...
                cfg.sensor.radar.rangeMaximum, 30.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.sensor.radar.targetPublicationPolicy, ...
                "currentRadarVisibilityRequiredInternalTrackMayCoast");
            testCase.verifyEqual( ...
                cfg.sensor.radar.maximumTrackCoastDuration, ...
                0.50, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.runtime.samplePeriod, 0.0125, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.ego.yaw.sideslipDomainMaximum, ...
                0.12, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.ego.yaw ...
                    .singleTrackYawRateMismatchMaximum, ...
                0.10, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.initialization.minimumRadarSamples, 1, ...
                AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.initialization.targetSpeedPrior, 15.0, ...
                AbsTol=0.0);
            testCase.verifyEqual(design.coreIss.stateOrder,["yaw";"bodyVelocity";"target"]);
            testCase.verifyGreaterThan(design.target.lipschitzCertificate.phiAcceleration,0.0);
            testCase.verifyGreaterThan(design.target.lambda,0.0);
            testCase.verifyEqual( ...
                context.observerSamplesSinceLastControllerTime, 0);
            testCase.verifyEqual( ...
                initialization.observerSamplePeriod, 0.0125, AbsTol=0.0);
        end

        function sampledImuAndGnssPreserveRotationCorrespondence(testCase)
            cfg = localConfiguration(20260813);
            cfg.noiseModel = "none";
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 10.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            [context, ~] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);
            target = localRadarExitTarget(0.0, initialEgo);
            context = nrmmEstimatorControllerAdapter( ...
                "sample", context, 0.0, initialEgo, target);
            currentEgo = struct( ...
                "position", [0.9; 0.1], ...
                "yawAngle", 0.4, ...
                "longitudinalVelocity", 8.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", -0.2);
            target = localRadarExitTarget(0.1, currentEgo);
            [~, ~, ~, frame] = nrmmEstimatorControllerAdapter( ...
                "sample", context, 0.1, currentEgo, target);
            previousFraction = 0.875;
            previousYaw = previousFraction*currentEgo.yawAngle;
            previousSpeed = (1.0-previousFraction) ...
                    * initialEgo.longitudinalVelocity ...
                + previousFraction*currentEgo.longitudinalVelocity;
            previousRotation = [cos(previousYaw), -sin(previousYaw); ...
                sin(previousYaw), cos(previousYaw)];
            currentRotation = [cos(currentEgo.yawAngle), ...
                -sin(currentEgo.yawAngle); ...
                sin(currentEgo.yawAngle), cos(currentEgo.yawAngle)];
            expectedInertialAcceleration = ( ...
                currentRotation*[currentEgo.longitudinalVelocity; 0.0] ...
                - previousRotation*[previousSpeed; 0.0]) ...
                / cfg.observer.runtime.samplePeriod;
            measuredInertialAcceleration = currentRotation ...
                * [frame.longitudinalAcceleration; ...
                    frame.lateralAcceleration];

            testCase.verifyEqual(measuredInertialAcceleration, ...
                expectedInertialAcceleration, AbsTol=1.0e-12);
        end

        function initializationRemovesKinematicSideslipFromCourse(testCase)
            cfg = estimatorControllerIntegrationConfig();
            cfg.noiseModel = "none";
            trueYaw = 0.35;
            trueSideslip = 0.05;
            speed = 10.0;
            rearAxleDistance = ...
                cfg.observer.ego.yaw.rearAxleDistance;
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", trueYaw, ...
                "longitudinalVelocity", speed*cos(trueSideslip), ...
                "lateralVelocity", speed*sin(trueSideslip), ...
                "yawRate", speed*sin(trueSideslip)/rearAxleDistance);

            [~, initialization] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);

            testCase.verifyEqual(initialization.egoInitialYaw, ...
                trueYaw, AbsTol=1.0e-12);
            testCase.verifyEqual(initialization.egoInitialBodyVelocity, ...
                speed*[cos(trueSideslip); sin(trueSideslip)], ...
                AbsTol=1.0e-12);
        end

        function straightAvoidanceUsesOnlyEstimatedStates(testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=2.2, ...
                TargetInitialLongitudinalDistance=23.0, ...
                UseStateEstimator=true, ...
                EstimatorConfiguration=localConfiguration(20260728), ...
                Plot=false, Report=false);

            localVerifySuccessfulAvoidance(testCase, result);
        end

        function circularAvoidanceUsesOnlyEstimatedStates(testCase)
            result = ...
                runCircularCenterlineStraightTargetAvoidanceScenario( ...
                    Duration=2.2, ...
                    Radius=60.0, ...
                    TargetInitialDistance=23.0, ...
                    UseStateEstimator=true, ...
                    EstimatorConfiguration= ...
                        localConfiguration(20260729), ...
                    Plot=false, Report=false);

            localVerifySuccessfulAvoidance(testCase, result);
        end

        function activeSuiteContainsOnlyStraightAndCircularRoads( ...
                testCase)
            result = runEstimatedStateAvoidanceScenarios( ...
                Duration=0.1, ...
                RequireCruiseRecovery=false, ...
                RequireCoupledManeuver=false, ...
                RequirePreDetectionCruise=false, ...
                Report=false, Progress=false);

            testCase.verifyEqual( ...
                result.scenarioNames, ["straight"; "circular"]);
            testCase.verifySize(result.scenarioPassed, [2, 1]);
            testCase.verifySize(result.coupledScenario, [2, 1]);
            testCase.verifyTrue(isfield(result, "straight"));
            testCase.verifyTrue(isfield(result, "circular"));
            testCase.verifyFalse(isfield(result, "sCurve"));
        end

        function directCircularEncounterSurvivesDelayedAcquisition( ...
                testCase)
            cfg = localConfiguration(20260729);
            cfg.initialization.targetSpeedPrior = 10.0;
            cfg.vehicle.targetSpeed = 10.0;
            result = ...
                runCircularCenterlineStraightTargetAvoidanceScenario( ...
                    Duration=5.5, ...
                    ReferenceSpeed=10.0, ...
                    Radius=60.0, ...
                    ArcLengthAfter=300.0, ...
                    TargetSpeed=10.0, ...
                    TargetInitialDistance=100.0, ...
                    TargetCollisionLateralOffset=0.8, ...
                    TargetLength=5.0, ...
                    TargetWidth=2.0, ...
                    UseStateEstimator=true, ...
                    EstimatorConfiguration=cfg, ...
                    Plot=false, Report=false);

            localVerifySuccessfulAvoidance(testCase, result);
            localVerifyPreDetectionCruise(testCase, result);
            testCase.verifyGreaterThan( ...
                max(abs(result.controlTracking.lateralError)), 1.0);
            testCase.verifyGreaterThan( ...
                max(cellfun(@(command) ...
                    abs(command.frontWheelSteeringAngle), ...
                    result.command)), 0.15);
        end

        function directStraightEncounterSurvivesDelayedAcquisition( ...
                testCase)
            cfg = localConfiguration(20260728);
            cfg.initialization.targetSpeedPrior = 10.0;
            cfg.vehicle.targetSpeed = 10.0;
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=5.5, ...
                ReferenceSpeed=10.0, ...
                TargetSpeed=10.0, ...
                TargetInitialLongitudinalDistance=100.0, ...
                TargetLateralOffset=0.8, ...
                TargetLength=5.0, ...
                TargetWidth=2.0, ...
                UseStateEstimator=true, ...
                EstimatorConfiguration=cfg, ...
                Plot=false, Report=false);

            localVerifySuccessfulAvoidance(testCase, result);
            localVerifyPreDetectionCruise(testCase, result);
            testCase.verifyGreaterThan( ...
                max(abs(result.controlTracking.lateralError)), 1.0);
            testCase.verifyGreaterThan( ...
                max(cellfun(@(command) ...
                    abs(command.frontWheelSteeringAngle), ...
                    result.command)), 0.15);
        end

        function straightTargetIsAcquiredAfterOutOfRangeCruise( ...
                testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=2.8, ...
                TargetInitialLongitudinalDistance=100.0, ...
                UseStateEstimator=true, ...
                EstimatorConfiguration=localConfiguration(20260731), ...
                Plot=false, Report=false);
            targetEstimateAvailable = ~cellfun( ...
                @isempty, result.targetEstimate);
            firstEstimateIdx = find( ...
                targetEstimateAvailable, 1, "first");
            preDetection = evaluatePreDetectionCruise( ...
                result, MinimumDuration=2.0);

            testCase.verifyFalse( ...
                result.estimator.initialization ...
                    .targetInitiallyAcquired);
            testCase.verifyFalse( ...
                result.perception.targetDetectionAvailable(1));
            testCase.verifyTrue(preDetection.passed);
            testCase.verifyGreaterThanOrEqual( ...
                preDetection.preDetectionDuration, 2.0);
            testCase.verifyLessThanOrEqual( ...
                preDetection.firstDetectionRange, ...
                result.perception.rangeMaximum+1.0e-10);
            testCase.verifyGreaterThan( ...
                preDetection.firstDetectionRange, 25.0);
            testCase.verifyNotEmpty(firstEstimateIdx);
            testCase.verifyEqual( ...
                result.controlTime(firstEstimateIdx), 2.4, ...
                AbsTol=1.0e-12);
            % Measured on the cascaded-observer closed loop: the radar
            % range crossing lands on this 0.0125 s observer sample.
            testCase.verifyEqual( ...
                result.estimator.metrics.targetAcquisitionTime, ...
                2.35, AbsTol=1.0e-12);
            testCase.verifyTrue( ...
                result.estimator.metrics.targetAcquisitionOccurred);
            testCase.verifyEqual( ...
                result.targetEstimate{firstEstimateIdx} ...
                    .velocityInitializationMethod, ...
                "radialOncomingConfiguredSpeedPrior");
            testCase.verifyFalse(result.failure.occurred, ...
                result.failure.message);
            testCase.verifyTrue(result.roadSafety.noBoundaryCrossing);
        end

        function acquiredTargetFollowsFiniteRadarLifecycle(testCase)
            cfg = localConfiguration(20260731);
            cfg.noiseModel = "none";
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 15.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            targetStateFunction = @(time, egoState) ...
                localRadarExitTarget(time, egoState);
            [context, initialization] = ...
                nrmmEstimatorControllerAdapter( ...
                    "initialize", cfg, initialEgo, ...
                    targetStateFunction);

            targetAtZero = targetStateFunction(0.0, initialEgo);
            [context, visibleEgo, visibleTarget, visibleFrame] = ...
                nrmmEstimatorControllerAdapter( ...
                    "sample", context, 0.0, initialEgo, ...
                    targetAtZero);
            nextEgo = initialEgo;
            nextEgo.position = [1.5; 0.0];
            targetAtNextSample = ...
                targetStateFunction(0.1, nextEgo);
            [context, hiddenEgo, hiddenTarget, hiddenFrame] = ...
                nrmmEstimatorControllerAdapter( ...
                    "sample", context, 0.1, nextEgo, ...
                    targetAtNextSample);
            retiredEgo = hiddenEgo;
            for time = (0.2:0.1:3.0)
                nextEgo.position = [15.0*time; 0.0];
                targetAtNextSample = ...
                    targetStateFunction(time, nextEgo);
                [context, retiredEgo, retiredTarget] = ...
                    nrmmEstimatorControllerAdapter( ...
                        "sample", context, time, nextEgo, ...
                        targetAtNextSample);
            end

            testCase.verifyTrue( ...
                initialization.targetInitiallyAcquired);
            testCase.verifyTrue(visibleFrame.radarDetectionAvailable);
            testCase.verifyNotEmpty(visibleTarget);
            testCase.verifyTrue(visibleEgo.targetEstimatePublished);
            testCase.verifyFalse(hiddenFrame.radarDetectionAvailable);
            testCase.verifyEmpty(hiddenTarget);
            testCase.verifyEmpty(hiddenEgo.targetEstimates);
            testCase.verifyTrue(hiddenEgo.targetTrackAcquired);
            testCase.verifyFalse(hiddenEgo.targetEstimatePublished);
            testCase.verifyEqual( ...
                hiddenEgo.targetPublicationPolicy, ...
                "currentRadarVisibilityRequiredInternalTrackMayCoast");
            testCase.verifyEqual( ...
                hiddenEgo.targetTrackStatus, "coasting");
            testCase.verifyEqual( ...
                hiddenEgo.targetTrackCoastAge, 0.0375, ...
                AbsTol=1.0e-12);
            testCase.verifyEmpty(retiredTarget);
            testCase.verifyFalse(retiredEgo.targetTrackAcquired);
            testCase.verifyFalse( ...
                retiredEgo.targetEstimatePublished);
            testCase.verifyEqual( ...
                retiredEgo.targetTrackStatus, "dormant");
            testCase.verifyEqual( ...
                retiredEgo.targetTrackRetirementCount, 1);
            testCase.verifyEqual( ...
                retiredEgo.targetLastRetirementTime, 0.575, ...
                AbsTol=1.0e-12);
            testCase.verifyTrue(all(isfinite( ...
                context.runtime.targetState), "all"));
            testCase.verifyTrue(all(isfinite( ...
                context.currentOutput.egoState), "all"));
        end
    end
end

function cfg = localConfiguration(seed)
    cfg = estimatorControllerIntegrationConfig();
    cfg.randomSeed = seed;
    cfg.observer.ego.domain.yawRateMaximum = 0.75;
end

function localVerifySuccessfulAvoidance(testCase, result)
    testCase.verifyFalse(result.failure.occurred, ...
        localFailureDiagnostic(result));
    testCase.verifyTrue(result.metrics.controllerCompletedScenario);
    testCase.verifyTrue(result.avoidance.baselineCollides);
    testCase.verifyTrue(result.avoidance.collisionFree);
    testCase.verifyTrue(result.roadSafety.noBoundaryCrossing);
    testCase.verifyTrue( ...
        result.roadSafety.allRectanglesCoveredByPerceivedSegments);
    testCase.verifyGreaterThanOrEqual( ...
        result.roadSafety.minimumBoundaryFunctionMargin, ...
        -result.roadSafety.contactTolerance);
    testCase.verifyGreaterThan( ...
        result.avoidance.minimumControlledSeparatingAxisMargin, 0.0);
    testCase.verifyTrue(result.avoidance.passedTarget);
    testCase.verifyTrue(result.avoidance.remainedMoving);
    testCase.verifyGreaterThan( ...
        result.avoidance.minimumEgoLongitudinalSpeed, 0.0);
    testCase.verifyEqual( ...
        result.scenario.stateSource, "onlineNrmmTrackingRuntime");
    testCase.verifyTrue(result.estimator.enabled);
    testCase.verifyTrue( ...
        result.estimator.metrics.allEstimatesFinite);
    testCase.verifyTrue( ...
        result.estimator.metrics.controllerInputsFromEstimator);
    testCase.verifyTrue( ...
        result.estimator.metrics.sensorContractValid);
    testCase.verifyTrue( ...
        result.estimator.metrics.radarDetectionOccurred);
    testCase.verifyTrue( ...
        result.estimator.metrics.allRadarDetectionsWithinRange);
    testCase.verifyTrue( ...
        result.estimator.metrics.targetPublicationWithinRadarVisibility);
    firstTargetIdx = find(~cellfun( ...
        @isempty, result.targetEstimate), 1, "first");
    egoOutput = result.controllerEgoEstimate{firstTargetIdx};
    sensorFrame = result.estimator.sensorFrame{firstTargetIdx};
    rotation = [ ...
        cos(egoOutput.egoYaw), -sin(egoOutput.egoYaw); ...
        sin(egoOutput.egoYaw), cos(egoOutput.egoYaw)];
    synchronizedTargetPosition = egoOutput.egoState([1, 4]) ...
        + rotation*sensorFrame.radarRelativePosition.';
    firstTarget = result.targetEstimate{firstTargetIdx};
    observerCfg = result.estimator.configuration.observer;
    testCase.verifyLessThanOrEqual( ...
        firstTarget.lastRadarTime, firstTarget.stateTime+1.0e-12);
    measurementAge = max(0.0, ...
        firstTarget.stateTime-firstTarget.lastRadarTime);
    % A flowing observer is not a radar reset.  During the held-input
    % phase its relative-position rate is bounded by target speed, ego
    % speed, and rotation of the measured line of sight.  One observer
    % period covers the output/predictor phase offset at a coincident
    % timestamp; the remaining terms cover the two radar endpoints and
    % the published ego-position radius.
    relativeRateMaximum = ...
        observerCfg.target.domain.speedMaximum ...
        + observerCfg.ego.domain.speedMaximum ...
        + observerCfg.ego.domain.yawRateMaximum ...
            * result.estimator.configuration.sensor.radar.rangeMaximum;
    firstEstimateConsistencyRadius = relativeRateMaximum ...
        * (measurementAge+observerCfg.runtime.samplePeriod) ...
        + 2.0*result.estimator.configuration.sensor.radar ...
            .positionNoiseMaximum ...
        + result.estimator.configuration.publishedErrorBound ...
            .egoPosition;
    testCase.verifyLessThanOrEqual(norm( ...
        firstTarget.targetPositionInertial ...
            - synchronizedTargetPosition), ...
        firstEstimateConsistencyRadius);
    testCase.verifyLessThanOrEqual( ...
        result.estimator.metrics.maximumDetectedTargetRange, 30.0);
    testCase.verifyEqual( ...
        result.controllerConfiguration.vehicle.length, ...
        5.0, AbsTol=0.0);
    testCase.verifyEqual( ...
        result.controllerConfiguration.vehicle.width, ...
        2.0, AbsTol=0.0);
    testCase.verifyEqual( ...
        result.controllerConfiguration.target.defaultLength, ...
        5.0, AbsTol=0.0);
    testCase.verifyEqual( ...
        result.controllerConfiguration.target.defaultWidth, ...
        2.0, AbsTol=0.0);
    testCase.verifyEqual(result.perception.rangeMaximum, ...
        30.0, AbsTol=0.0);
    testCase.verifyEqual(result.perception.roadBoundaryOffsets, ...
        [6.0; 8.0], AbsTol=0.0);
    maximumRoadPointRange = max(cellfun( ...
        @(value) max([ ...
            value.roadGeometry.boundaries.maximumSourcePointRange]), ...
        result.perception.roadBoundaryFit));
    candidateRoadRows = cellfun( ...
        @(value) value.candidateSafetyRowCount, ...
        result.perception.controllerRoadAudit);
    testCase.verifyLessThanOrEqual( ...
        maximumRoadPointRange, 30.0 + 1.0e-10);
    testCase.verifyGreaterThan(min(candidateRoadRows), 0);
end

function localVerifyPreDetectionCruise(testCase, result)
    preDetection = evaluatePreDetectionCruise( ...
        result, MinimumDuration=2.0);
    testCase.verifyTrue(preDetection.passed);
    testCase.verifyTrue(preDetection.cruiseMaintained);
    testCase.verifyGreaterThanOrEqual( ...
        preDetection.preDetectionDuration, 2.0);
end

function target = localRadarExitTarget(time, ~)
    target = struct( ...
        "targetPositionInertial", [29.0 + 30.0*time; 0.0]);
end

function diagnostic = localFailureDiagnostic(result)
    if isempty(result.command)
        maximumSteering = NaN;
    else
        maximumSteering = max(cellfun(@(command) ...
            abs(command.frontWheelSteeringAngle), result.command));
    end
    diagnostic = sprintf( ...
        "%s | failure time %.3f s; dRect %.6f m; " ...
        + "road margin %.6f; max |steer| %.6f rad; " ...
        + "max |lateral error| %.6f m", ...
        result.failure.message, result.failure.time, ...
        result.avoidance.minimumControlledSeparatingAxisMargin, ...
        result.roadSafety.minimumBoundaryFunctionMargin, ...
        maximumSteering, ...
        max(abs(result.controlTracking.lateralError)));
end
