classdef estimatedStateAvoidanceVideoTest < matlab.unittest.TestCase
% estimatedStateAvoidanceVideoTest Video rendering behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
        end
    end

    methods (Test)
        function completeVisualizationWritesPlayableVideo(testCase)
            outputPath = string(tempname)+" video.mp4";
            cleanup = onCleanup(@() localDelete(outputPath));

            metadata = renderEstimatedStateAvoidanceVideo( ...
                localSyntheticResult(), outputPath, ...
                FramePeriod=0.1, FrameRate=5.0, ...
                HoldLastFrameSeconds=0.0, FigureVisible=false);

            testCase.verifyTrue(isfile(outputPath));
            testCase.verifyGreaterThan(metadata.fileSizeBytes, 0.0);
            testCase.verifyEqual(metadata.frameCount, 3);
            testCase.verifyGreaterThan(metadata.width, 0.0);
            testCase.verifyGreaterThan(metadata.height, 0.0);
            testCase.verifyEqual( ...
                metadata.width/metadata.height, 16.0/9.0, ...
                RelTol=0.01);
            testCase.verifyTrue(metadata.collisionFree);
            testCase.verifyEqual(metadata.perceptionRange, 30.0);
            testCase.verifyTrue( ...
                metadata.roadBoundaryVisualizationIncluded);
            testCase.verifyTrue( ...
                metadata.shoulderVisualizationIncluded);
            testCase.verifyEqual( ...
                metadata.roadShoulderWidth, 2.6, AbsTol=0.0);
            testCase.verifyEqual( ...
                metadata.roadOuterBoundaryOffsets, ...
                [8.6; 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                metadata.roadTotalWidthIncludingShoulders, ...
                19.2, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                metadata.perceivedRoadBoundaryCount, 2);
            testCase.verifyLessThanOrEqual( ...
                metadata.maximumPerceivedRoadSourcePointRange, ...
                metadata.perceptionRange+1.0e-12);
            testCase.verifyLessThanOrEqual( ...
                metadata.maximumRenderedRoadBoundaryRange, ...
                metadata.perceptionRange+1.0e-12);
            testCase.verifyEqual( ...
                metadata.minimumRoadBoundaryMargin, ...
                4.8, AbsTol=1.0e-12);
            testCase.verifyTrue(metadata.noRoadBoundaryCrossing);
            testCase.verifyTrue(metadata.cruiseRecovered);
            testCase.verifyEqual( ...
                metadata.maximumRecoveryCourseHeadingError, ...
                0.0, AbsTol=0.0);
            testCase.verifyTrue(metadata.coupledManeuverObserved);
            testCase.verifyEqual( ...
                metadata.maximumContinuousCoupledDuration, ...
                0.2, AbsTol=1.0e-12);
            probeCommand = "env -u LD_LIBRARY_PATH ffprobe " ...
                + "-v error -select_streams v:0 " ...
                + "-show_entries stream=codec_name,width,height " ...
                + "-of default=noprint_wrappers=1 " ...
                + localShellQuote(outputPath);
            [probeStatus, probeOutput] = system(probeCommand);
            testCase.verifyEqual(probeStatus, 0, probeOutput);
            testCase.verifySubstring(probeOutput, "codec_name=h264");
            testCase.verifySubstring(probeOutput, ...
                "width="+string(metadata.width));
            testCase.verifySubstring(probeOutput, ...
                "height="+string(metadata.height));
        end
    end
end

function result = localSyntheticResult()
    time = [0.0; 0.1; 0.2];
    egoPosition = [0.0, 0.0; 0.5, 0.05; 1.0, 0.1];
    targetPosition = [10.0, 0.5; 9.5, 0.5; 9.0, 0.5];
    vehicle = struct("length", 5.0, "width", 2.0);
    targetLength = 4.8;
    targetWidth = 1.9;
    command = repmat({struct( ...
        "frontAxleTorque", 120.0, ...
        "frontWheelSteeringAngle", 0.01, ...
        "longitudinalAcceleration", 0.2)}, 2, 1);
    egoEstimate = repmat({struct( ...
        "egoState", [0.0; 5.0; 0.0; 0.0; 0.0; 0.0], ...
        "egoYaw", 0.0)}, 2, 1);
    egoEstimate{2}.egoState([1, 4]) = [0.52; 0.04];
    targetEstimate = repmat({struct( ...
        "targetPositionInertial", [10.0; 0.5], ...
        "targetVelocityInertial", [-5.0; 0.0])}, 2, 1);
    targetEstimate{2}.targetPositionInertial = [9.48; 0.52];
    sensorFrame = { ...
        struct( ...
            "radarDetectionAvailable", true, ...
            "radarRelativePosition", [10.0, 0.5]); ...
        struct( ...
            "radarDetectionAvailable", true, ...
            "radarRelativePosition", [8.96, 0.48])};
    roadBoundaryFit = { ...
        localRoadPerception(egoPosition(1, 1)); ...
        localRoadPerception(egoPosition(2, 1))};

    result = struct();
    result.scenario = struct( ...
        "centerline", [-10.0, 0.0; 20.0, 0.0], ...
        "description", "Synthetic video test", ...
        "referenceSpeed", 5.0, ...
        "stateSource", "onlineNrmmTrackingRuntime");
    result.plantTrace = struct( ...
        "time", time, ...
        "positionX", egoPosition(:, 1), ...
        "positionY", egoPosition(:, 2), ...
        "yaw", zeros(3, 1), ...
        "longitudinalVelocity", 5.0*ones(3, 1));
    result.targetTruth = struct( ...
        "time", time, ...
        "position", targetPosition, ...
        "yaw", pi*ones(3, 1), ...
        "length", targetLength, ...
        "width", targetWidth);
    result.controllerConfiguration = struct("vehicle", vehicle);
    result.controlTime = time;
    result.controlState = [ ...
        egoPosition(:, 1), egoPosition(:, 2), zeros(3, 1), ...
        [5.0; 4.8; 4.6], [0.0; 0.4; 0.8], ...
        0.2*ones(3, 1)];
    result.controlTracking = struct( ...
        "lateralError", [0.0; 0.05; 0.10], ...
        "headingError", zeros(3, 1));
    result.command = command;
    result.controllerEgoEstimate = egoEstimate;
    result.targetEstimate = targetEstimate;
    result.baseline = struct( ...
        "egoPosition", egoPosition, ...
        "separatingAxisMargin", [2.75; 1.75; 0.75]);
    result.avoidance = struct( ...
        "passedTarget", true, ...
        "remainedMoving", true, ...
        "recoveredCruise", true, ...
        "minimumEgoLongitudinalSpeed", 5.0, ...
        "maximumRecoverySpeedError", 0.0, ...
        "maximumRecoveryLateralError", 0.1, ...
        "maximumRecoveryHeadingError", 0.0);
    result.metrics = struct( ...
        "meanSolveTime", 0.01, ...
        "maximumSolveTime", 0.02);
    result.estimator = struct( ...
        "enabled", true, ...
        "sensorFrame", {sensorFrame});
    result.perception = struct( ...
        "rangeMaximum", 30.0, ...
        "targetDetectionAvailable", true(2, 1), ...
        "roadBoundaryOffsets", [6.0; 8.0], ...
        "roadShoulderWidth", 2.6, ...
        "roadOuterBoundaryOffsets", [8.6; 10.6], ...
        "roadTotalWidthIncludingShoulders", 19.2, ...
        "roadBoundaryFit", {roadBoundaryFit});
    result.roadSafety = struct( ...
        "conservativeBoundaryFunctionMargin", [ ...
            5.0, 7.0; 4.9, 6.9; 4.8, 6.8], ...
        "minimumBoundaryFunctionMargin", 4.8, ...
        "noBoundaryCrossing", true);
    result.maneuverCoupling = evaluateManeuverCoupling( ...
        result, MinimumCoupledDuration=0.2);
end

function perception = localRoadPerception(egoPositionX)
    parameter = [-25.0; 0.0; 25.0];
    origin = [egoPositionX; 0.0];
    longitudinalDirection = [1.0; 0.0];
    lateralDirection = [0.0; 1.0];
    rightBoundary = localBoundary( ...
        origin, longitudinalDirection, lateralDirection, ...
        parameter, -8.6, 1.0, "right");
    leftBoundary = localBoundary( ...
        origin, longitudinalDirection, lateralDirection, ...
        parameter, 10.6, -1.0, "left");
    perception = struct( ...
        "rangeMaximum", 30.0, ...
        "egoPose", [egoPositionX; 0.0; 0.0], ...
        "roadGeometry", struct( ...
            "boundaries", [rightBoundary; leftBoundary]));
end

function boundary = localBoundary( ...
        origin, longitudinalDirection, lateralDirection, ...
        parameter, lateralCoordinate, safeSideSign, boundaryId)
    sourcePoints = origin.' ...
        + parameter*longitudinalDirection.' ...
        + lateralCoordinate*lateralDirection.';
    boundary = struct( ...
        "origin", origin, ...
        "longitudinalDirection", longitudinalDirection, ...
        "lateralDirection", lateralDirection, ...
        "coefficients", [0.0, 0.0, lateralCoordinate], ...
        "parameterRange", [parameter(1), parameter(end)], ...
        "safeSideSign", safeSideSign, ...
        "boundaryId", boundaryId, ...
        "sourcePoints", sourcePoints, ...
        "sourcePointRange", vecnorm( ...
            sourcePoints-origin.', 2, 2), ...
        "verticalFitErrorBound", 0.0);
end

function localDelete(path)
    if isfile(path)
        delete(path);
    end
end

function quoted = localShellQuote(value)
    quoted = "'" + replace(string(value), "'", "'""'""'") + "'";
end
