classdef estimatedStateAvoidanceScenarioTest < matlab.unittest.TestCase
% estimatedStateAvoidanceScenarioTest NRMM estimator/controller integration.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "config")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "estimator"), ...
                    IncludingSubfolders=true));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function adapterRetainsThePublishedControllerTimeEstimate(testCase)
            cfg = estimatorControllerIntegrationConfig();
            ego = struct("position",[0;0],"yawAngle",0, ...
                "longitudinalVelocity",10,"lateralVelocity",0,"yawRate",0);
            context = nrmmEstimatorControllerAdapter("initialize",cfg,ego,@localRadarExitTarget);
            [context,published] = nrmmEstimatorControllerAdapter( ...
                "sample",context,0,ego,localRadarExitTarget(0,ego));
            testCase.verifyEqual(context.currentOutput,published,AbsTol=0);
            testCase.verifyEqual(published.stateTime,0,AbsTol=0);
            testCase.verifyEqual(context.runtime.currentTime,cfg.observer.runtime.samplePeriod,AbsTol=1e-14);
        end

        function adapterInitializesAtStandstillWithoutACourseDirection(testCase)
            cfg = estimatorControllerIntegrationConfig();
            cfg.observer.ego.domain.speedMinimum = 0;
            cfg.noiseModel = "none";
            ego = struct("position",[0;0],"yawAngle",0.7, ...
                "longitudinalVelocity",0,"lateralVelocity",0,"yawRate",0);
            [context,initialization] = nrmmEstimatorControllerAdapter( ...
                "initialize",cfg,ego,@localRadarExitTarget);
            testCase.verifyEqual(initialization.egoInitialBodyVelocity,[0;0],AbsTol=0);
            testCase.verifyTrue(context.currentOutput.orientationCertificateAvailable);
            testCase.verifyEqual(context.currentOutput.egoYawErrorBound,pi,AbsTol=0);
            testCase.verifyTrue(all(isfinite(context.runtime.targetState)));
        end

        function configuredSensorsProduceCascadedHighGainDesign(testCase)
            cfg = estimatorControllerIntegrationConfig();
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 15.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            [context, initialization] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);
            design = initialization.observerDesign;

            testCase.verifyEqual( ...
                cfg.sensor.radar.rangeMaximum, 30.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.sensor.radar.targetPublicationPolicy, ...
                "currentRadarVisibilityRequiredInternalTrackMayCoast");
            testCase.verifyEqual( ...
                cfg.sensor.radar.maximumTrackCoastDuration, ...
                0.50, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.runtime.samplePeriod, 0.0125, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.ego.yaw.sideslipDomainMaximum, ...
                0.12, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.observer.ego.yaw ...
                    .singleTrackYawRateMismatchMaximum, ...
                0.25, AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.initialization.minimumRadarSamples, 1, ...
                AbsTol=0.0);
            testCase.verifyEqual( ...
                cfg.initialization.targetSpeedPrior, 15.0, ...
                AbsTol=0.0);
            testCase.verifyEqual(design.coreIss.stateOrder,["bodyVelocity";"target"]);
            testCase.verifyGreaterThan(design.target.lipschitzCertificate.phiAcceleration,0.0);
            testCase.verifyGreaterThan(design.target.lambda,0.0);
            testCase.verifyEqual( ...
                context.observerSamplesSinceLastControllerTime, 0);
            testCase.verifyEqual( ...
                initialization.observerSamplePeriod, 0.0125, AbsTol=0.0);
        end

        function sampledImuAndGnssPreserveRotationCorrespondence(testCase)
            cfg = localConfiguration(20260813);
            cfg.noiseModel = "none";
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 10.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            [context, ~] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);
            target = localRadarExitTarget(0.0, initialEgo);
            context = nrmmEstimatorControllerAdapter( ...
                "sample", context, 0.0, initialEgo, target);
            currentEgo = struct( ...
                "position", [0.9; 0.1], ...
                "yawAngle", 0.4, ...
                "longitudinalVelocity", 8.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", -0.2);
            target = localRadarExitTarget(0.1, currentEgo);
            [~, ~, ~, frame] = nrmmEstimatorControllerAdapter( ...
                "sample", context, 0.1, currentEgo, target);
            previousFraction = 0.875;
            previousYaw = previousFraction*currentEgo.yawAngle;
            previousSpeed = (1.0-previousFraction) ...
                    * initialEgo.longitudinalVelocity ...
                + previousFraction*currentEgo.longitudinalVelocity;
            previousRotation = [cos(previousYaw), -sin(previousYaw); ...
                sin(previousYaw), cos(previousYaw)];
            currentRotation = [cos(currentEgo.yawAngle), ...
                -sin(currentEgo.yawAngle); ...
                sin(currentEgo.yawAngle), cos(currentEgo.yawAngle)];
            expectedInertialAcceleration = ( ...
                currentRotation*[currentEgo.longitudinalVelocity; 0.0] ...
                - previousRotation*[previousSpeed; 0.0]) ...
                / cfg.observer.runtime.samplePeriod;
            measuredInertialAcceleration = currentRotation ...
                * [frame.longitudinalAcceleration; ...
                    frame.lateralAcceleration];

            testCase.verifyEqual(measuredInertialAcceleration, ...
                expectedInertialAcceleration, AbsTol=1.0e-12);
        end

        function initializationRemovesKinematicSideslipFromCourse(testCase)
            cfg = estimatorControllerIntegrationConfig();
            cfg.noiseModel = "none";
            trueYaw = 0.35;
            trueSideslip = 0.05;
            speed = 10.0;
            rearAxleDistance = ...
                cfg.observer.ego.yaw.rearAxleDistance;
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", trueYaw, ...
                "longitudinalVelocity", speed*cos(trueSideslip), ...
                "lateralVelocity", speed*sin(trueSideslip), ...
                "yawRate", speed*sin(trueSideslip)/rearAxleDistance);

            [~, initialization] = nrmmEstimatorControllerAdapter( ...
                "initialize", cfg, initialEgo, @localRadarExitTarget);

            testCase.verifyEqual(initialization.egoInitialYaw, ...
                trueYaw, AbsTol=1.0e-12);
            testCase.verifyEqual(initialization.egoInitialBodyVelocity, ...
                speed*[cos(trueSideslip); sin(trueSideslip)], ...
                AbsTol=1.0e-12);
        end

        function straightAdmissionFailureRetainsEstimatedInputs(testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=2.2, ...
                TargetInitialLongitudinalDistance=23.0, ...
                UseStateEstimator=true, ...
                EstimatorConfiguration=localConfiguration(20260728), ...
                Plot=false, Report=false);

            localVerifyReportedAdmissionFailure(testCase, result);
        end

        function circularAdmissionFailureRetainsEstimatedInputs(testCase)
            result = ...
                runCircularCenterlineStraightTargetAvoidanceScenario( ...
                    Duration=2.2, ...
                    Radius=60.0, ...
                    TargetInitialDistance=23.0, ...
                    UseStateEstimator=true, ...
                    EstimatorConfiguration= ...
                        localConfiguration(20260729), ...
                    Plot=false, Report=false);

            localVerifyReportedAdmissionFailure(testCase, result);
        end

        function activeSuiteContainsOnlyStraightAndCircularRoads( ...
                testCase)
            result = runEstimatedStateAvoidanceScenarios( ...
                Duration=0.1, ...
                RequireCruiseRecovery=false, ...
                RequireCoupledManeuver=false, ...
                RequirePreDetectionCruise=false, ...
                Report=false, Progress=false);

            testCase.verifyEqual( ...
                result.scenarioNames, ["straight"; "circular"]);
            testCase.verifySize(result.scenarioPassed, [2, 1]);
            testCase.verifySize(result.coupledScenario, [2, 1]);
            testCase.verifyTrue(isfield(result, "straight"));
            testCase.verifyTrue(isfield(result, "circular"));
            testCase.verifyFalse(isfield(result, "sCurve"));
        end

        function circularFullHorizonAdmissionFailureRetainsSensorEvidence( ...
                testCase)
            cfg = localConfiguration(20260908);
            cfg.initialization.targetSpeedPrior = 10.0;
            cfg.vehicle.targetSpeed = 10.0;
            result = ...
                runCircularCenterlineStraightTargetAvoidanceScenario( ...
                    Duration=0.1, ...
                    ReferenceSpeed=10.0, ...
                    Radius=60.0, ...
                    ArcLengthAfter=300.0, ...
                    TargetSpeed=10.0, ...
                    TargetInitialDistance=100.0, ...
                    TargetCollisionLateralOffset=0.8, ...
                    TargetLength=5.0, ...
                    TargetWidth=2.0, ...
                    UseStateEstimator=true, ...
                    EstimatorConfiguration=cfg, ...
                    ControllerConfiguration=finiteSensingValidationConfig(), ...
                    Plot=false, Report=false);

            localVerifyUncertifiedFullHorizon(testCase,result);
        end

        function straightAdmissionSucceedsBeforeChangedRoadStopsExecution( ...
                testCase)
            cfg = localConfiguration(20260728);
            cfg.initialization.targetSpeedPrior = 10.0;
            cfg.vehicle.targetSpeed = 10.0;
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=0.1, ...
                ReferenceSpeed=10.0, ...
                TargetSpeed=10.0, ...
                TargetInitialLongitudinalDistance=100.0, ...
                TargetLateralOffset=0.8, ...
                TargetLength=5.0, ...
                TargetWidth=2.0, ...
                UseStateEstimator=true, ...
                EstimatorConfiguration=cfg, ...
                ControllerConfiguration=finiteSensingValidationConfig(), ...
                Plot=false, Report=false);

            testCase.verifyTrue(result.failure.occurred);
            testCase.verifyEqual(result.failure.identifier,"collisionAvoidanceController:changedExecutionContract");
            testCase.verifyEqual(result.metrics.completedControlSteps,1);
            testCase.verifyEqual(result.failure.time,result.scenario.sampleTime,AbsTol=1e-12);
            testCase.verifyTrue(result.attempts.metadata{1}.planCertified);
            testCase.verifyEmpty(result.attempts.targetEstimate{1});
            testCase.verifyNotEmpty(result.command);
        end

        function unseenTargetsDoNotHideAnUncertifiedEgoHorizon(testCase)
            result = runOncomingVehicleAvoidanceScenario(Duration=0.1, ...
                TargetInitialLongitudinalDistance=100, UseStateEstimator=true, ...
                EstimatorConfiguration=localConfiguration(20260731), ...
                ControllerConfiguration=finiteSensingValidationConfig(), Plot=false, Report=false);
            localVerifyUncertifiedFullHorizon(testCase,result);
            testCase.verifyFalse(result.estimator.initialization.targetInitiallyAcquired);
            testCase.verifyFalse(result.attempts.targetVisible(1));
            testCase.verifyFalse(result.estimator.metrics.targetAcquisitionOccurred);
        end

        function acquiredTargetFollowsFiniteRadarLifecycle(testCase)
            cfg = localConfiguration(20260731);
            cfg.noiseModel = "none";
            initialEgo = struct( ...
                "position", [0.0; 0.0], ...
                "yawAngle", 0.0, ...
                "longitudinalVelocity", 15.0, ...
                "lateralVelocity", 0.0, ...
                "yawRate", 0.0);
            targetStateFunction = @(time, egoState) ...
                localRadarExitTarget(time, egoState);
            [context, initialization] = ...
                nrmmEstimatorControllerAdapter( ...
                    "initialize", cfg, initialEgo, ...
                    targetStateFunction);

            targetAtZero = targetStateFunction(0.0, initialEgo);
            [context, visibleEgo, visibleTarget, visibleFrame] = ...
                nrmmEstimatorControllerAdapter( ...
                    "sample", context, 0.0, initialEgo, ...
                    targetAtZero);
            nextEgo = initialEgo;
            nextEgo.position = [1.5; 0.0];
            targetAtNextSample = ...
                targetStateFunction(0.1, nextEgo);
            [context, hiddenEgo, hiddenTarget, hiddenFrame] = ...
                nrmmEstimatorControllerAdapter( ...
                    "sample", context, 0.1, nextEgo, ...
                    targetAtNextSample);
            retiredEgo = hiddenEgo;
            for time = (0.2:0.1:3.0)
                nextEgo.position = [15.0*time; 0.0];
                targetAtNextSample = ...
                    targetStateFunction(time, nextEgo);
                [context, retiredEgo, retiredTarget] = ...
                    nrmmEstimatorControllerAdapter( ...
                        "sample", context, time, nextEgo, ...
                        targetAtNextSample);
            end

            testCase.verifyTrue( ...
                initialization.targetInitiallyAcquired);
            testCase.verifyTrue(visibleFrame.radarDetectionAvailable);
            testCase.verifyNotEmpty(visibleTarget);
            testCase.verifyTrue(visibleEgo.targetEstimatePublished);
            testCase.verifyFalse(hiddenFrame.radarDetectionAvailable);
            testCase.verifyEmpty(hiddenTarget);
            testCase.verifyEmpty(hiddenEgo.targetEstimates);
            testCase.verifyTrue(hiddenEgo.targetTrackAcquired);
            testCase.verifyFalse(hiddenEgo.targetEstimatePublished);
            testCase.verifyEqual( ...
                hiddenEgo.targetPublicationPolicy, ...
                "currentRadarVisibilityRequiredInternalTrackMayCoast");
            testCase.verifyEqual( ...
                hiddenEgo.targetTrackStatus, "coasting");
            testCase.verifyEqual( ...
                hiddenEgo.targetTrackCoastAge, 0.0375, ...
                AbsTol=1.0e-12);
            testCase.verifyEmpty(retiredTarget);
            testCase.verifyFalse(retiredEgo.targetTrackAcquired);
            testCase.verifyFalse( ...
                retiredEgo.targetEstimatePublished);
            testCase.verifyEqual( ...
                retiredEgo.targetTrackStatus, "dormant");
            testCase.verifyEqual( ...
                retiredEgo.targetTrackRetirementCount, 1);
            testCase.verifyEqual( ...
                retiredEgo.targetLastRetirementTime, 0.575, ...
                AbsTol=1.0e-12);
            testCase.verifyTrue(all(isfinite( ...
                context.runtime.targetState), "all"));
            testCase.verifyTrue(all(isfinite( ...
                context.currentOutput.egoState), "all"));
        end
    end
end

function cfg = localConfiguration(seed)
    cfg = estimatorControllerIntegrationConfig();
    cfg.randomSeed = seed;
    cfg.observer.ego.domain.yawRateMaximum = 0.75;
end

function localVerifyReportedAdmissionFailure(testCase,result)
    testCase.assertTrue(result.failure.occurred);
    testCase.verifyTrue(any(string(result.failure.identifier) == [ ...
        "collisionAvoidanceController:noCertifiedContinuation", ...
        "collisionAvoidanceController:invalidUncertaintyChart", ...
        "collisionAvoidanceController:invalidBarrierAdmission"]));
    testCase.verifyEqual(result.metrics.completedControlSteps,0);
    testCase.verifyEmpty(result.command);
    testCase.verifyEqual(result.scenario.stateSource,"onlineNrmmTrackingRuntime");
    testCase.verifyTrue(result.estimator.enabled);
    testCase.verifyNotEmpty(result.attempts.controllerEgoEstimate{1});
    input = result.attempts.controllerEgoEstimate{1};
    testCase.verifyEqual(input.stateTime,result.attempts.time(1),AbsTol=1e-12);
    testCase.verifyTrue(isfield(input,"controllerErrorBound"));
    testCase.verifyFalse(input.controllerErrorBound.futurePredictionIncluded);
    testCase.verifyTrue(all(isfinite(input.egoState)));
end

function target = localRadarExitTarget(time, ~)
    target = struct( ...
        "targetPositionInertial", [29.0 + 30.0*time; 0.0]);
end

function localVerifyUncertifiedFullHorizon(testCase,result)
    localVerifyReportedAdmissionFailure(testCase,result);
    testCase.verifyEqual(result.failure.identifier,"collisionAvoidanceController:noCertifiedContinuation");
    testCase.verifyEmpty(result.attempts.targetEstimate{1});
end
