classdef evaluateExportedCurbMasksAgainstDevelopmentLabelsTest ...
        < matlab.unittest.TestCase
% evaluateExportedCurbMasksAgainstDevelopmentLabelsTest Synthetic checks.

    properties
        TemporaryDirectory (1, 1) string
        MaskJsonlPath (1, 1) string
        OutputPath (1, 1) string
    end

    methods (TestClassSetup)
        function addScriptPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (TestMethodSetup)
        function createTemporaryFiles(testCase)
            testCase.TemporaryDirectory = string(tempname);
            mkdir(testCase.TemporaryDirectory);
            testCase.addTeardown( ...
                @() rmdir(testCase.TemporaryDirectory, "s"));
            testCase.MaskJsonlPath = fullfile( ...
                testCase.TemporaryDirectory, "curb_masks.jsonl");
            testCase.OutputPath = fullfile( ...
                testCase.TemporaryDirectory, "label_rates.csv");

            record = struct( ...
                "frame", 7, ...
                "curbPointIndicesZeroBased", [0, 2]);
            fileIdentifier = fopen(testCase.MaskJsonlPath, "wt");
            testCase.assertGreaterThanOrEqual(fileIdentifier, 0);
            cleaner = onCleanup(@() fclose(fileIdentifier));
            fprintf(fileIdentifier, "%s\n", jsonencode(record));
            clear cleaner;
        end
    end

    methods (Test)
        function mapsManualCoordinatesToExactRawIndices(testCase)
            actual = ...
                evaluateExportedCurbMasksAgainstDevelopmentLabels( ...
                    "synthetic", testCase.MaskJsonlPath, ...
                    OutputPath=testCase.OutputPath, ...
                    MatchToleranceM=1.0e-8, ...
                    LabelCatalog=testCase.syntheticCatalog(), ...
                    FrameLoader=@testCase.syntheticFrameLoader);

            expected = table( ...
                [7; 7; 8], ...
                ["positive"; "hard-negative"; "positive"], ...
                [2; 2; 1], [1; 1; 0], [0.5; 0.5; 0.0], ...
                VariableNames=[ ...
                    "frameIndex", "label", "count", ...
                    "selectedCount", "selectedRate"]);
            written = readtable(testCase.OutputPath, TextType="string");

            testCase.verifyEqual(actual, expected);
            testCase.verifyEqual(written, expected);
        end
    end

    methods (Static)
        function catalog = syntheticCatalog()
            frameSevenPoints = ...
                evaluateExportedCurbMasksAgainstDevelopmentLabelsTest ...
                .syntheticFrameLoader("", 7);
            frameEightPoints = ...
                evaluateExportedCurbMasksAgainstDevelopmentLabelsTest ...
                .syntheticFrameLoader("", 8);
            anchors = [ ...
                struct( ...
                    "frameIndex", 7, ...
                    "positiveCoordinatesM", ...
                        frameSevenPoints(1:2, 1:3), ...
                    "hardNegativeCoordinatesM", ...
                        frameSevenPoints(3:4, 1:3)); ...
                struct( ...
                    "frameIndex", 8, ...
                    "positiveCoordinatesM", ...
                        frameEightPoints(2, 1:3), ...
                    "hardNegativeCoordinatesM", zeros(0, 3))];
            catalog = struct( ...
                "datasetName", "synthetic", ...
                "independentGroundTruth", false, ...
                "anchors", anchors);
        end

        function rawPoints = syntheticFrameLoader(~, frameIndex)
            switch frameIndex
                case 7
                    rawPoints = [ ...
                        0, 0, 0, 10; ...
                        1, 0, 0, 20; ...
                        2, 0, 0, 30; ...
                        3, 0, 0, 40];
                case 8
                    rawPoints = [ ...
                        10, 0, 0, 50; ...
                        11, 0, 0, 60];
                otherwise
                    error( ...
                        "evaluateExportedCurbMasksAgainstDevelopmentLabelsTest:" + ...
                        "UnexpectedFrame", ...
                        "Synthetic frame %d was not configured.", ...
                        frameIndex);
            end
        end
    end
end
