classdef evaluateCurbRingFeatureBackgroundCalibrationTest ...
        < matlab.unittest.TestCase
%EVALUATECURBRINGFEATUREBACKGROUNDCALIBRATIONTEST Integration regression.

    properties (SetAccess = private)
        RepositoryRoot (1, 1) string
    end

    methods (TestClassSetup)
        function addResearchScripts(testCase)
            testFile = mfilename("fullpath");
            testCase.RepositoryRoot = ...
                string(fileparts(fileparts(testFile)));
            import matlab.unittest.fixtures.PathFixture
            testCase.applyFixture(PathFixture( ...
                fullfile(testCase.RepositoryRoot, "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (Test)
        function writesSideAgnosticBackgroundMetrics(testCase)
            datasetFolder = fullfile( ...
                testCase.RepositoryRoot, "simulation", "data", ...
                "carla_outer_loop_lap_10hz_20260802_epic_no_rt_auto");
            testCase.assumeTrue(isfolder(datasetFolder), ...
                "The repository-local development dataset is unavailable.");

            import matlab.unittest.fixtures.TemporaryFolderFixture
            temporaryFolder = testCase.applyFixture( ...
                TemporaryFolderFixture);
            outputDirectory = string(temporaryFolder.Folder);
            clear evaluateCurbRingFeatureBackgroundCalibration ...
                computeLidarRingCurbFeatures
            summary = evaluateCurbRingFeatureBackgroundCalibration( ...
                datasetFolder, ...
                OutputDirectory=outputDirectory, ...
                FrameIndices=12, ...
                CommonFamilyMultipliers=[1.0, 1.25], ...
                LocalPercentiles=[0.0, 0.5], ...
                MinimumFamilyVotes=2, ...
                MinimumSalientFamilyVotes=[1, 2]);

            testCase.verifyEqual(summary.positiveCount, 16);
            testCase.verifyEqual(summary.hardNegativeCount, 45);
            testCase.verifyEqual(summary.featureCount, 16);
            testCase.verifyFalse(summary.sideSpecificLogicUsed);
            testCase.verifyFalse(summary.frameSpecificLogicUsed);
            testCase.verifyTrue(isfile( ...
                summary.outputFiles.featureMetricsCsv));
            testCase.verifyTrue(isfile( ...
                summary.outputFiles.familyMetricsCsv));
            testCase.verifyTrue(isfile( ...
                summary.outputFiles.ruleGridCsv));
            testCase.verifyTrue(isfile( ...
                summary.outputFiles.recommendedRuleCsv));
            testCase.verifyTrue(isfile( ...
                summary.outputFiles.extendedFeatureAblationCsv));

            featureMetrics = readtable( ...
                summary.outputFiles.featureMetricsCsv);
            testCase.verifyEqual(height(featureMetrics), 16);
            testCase.verifyEqual( ...
                unique(string(featureMetrics.family)), ...
                ["compression"; "radial"; "shape"; "vertical"]);
            expectedExtendedNames = [ ...
                "huangRadiusRatioDeviation"; ...
                "huangHdInRadius"; ...
                "sameRingSlopeMagnitude"; ...
                "hataDifferentialHeightResponse"];
            expectedExtendedBaselines = [ ...
                0.00163314; 0.0159446; 0.0143248; 0.0142488];
            extendedMetrics = featureMetrics( ...
                ismember(string(featureMetrics.featureName), ...
                    expectedExtendedNames), :);
            [~, order] = ismember( ...
                expectedExtendedNames, ...
                string(extendedMetrics.featureName));
            extendedMetrics = extendedMetrics(order, :);
            testCase.verifyEqual( ...
                string(extendedMetrics.featureName), ...
                expectedExtendedNames);
            testCase.verifyEqual( ...
                extendedMetrics.defaultThreshold, ...
                expectedExtendedBaselines, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                string(extendedMetrics.family), ...
                ["radial"; "vertical"; "shape"; "vertical"]);
            testCase.verifyEqual( ...
                extendedMetrics.common1p25Threshold, ...
                1.25*expectedExtendedBaselines, RelTol=1.0e-12);
            testCase.verifyGreaterThanOrEqual( ...
                extendedMetrics.positiveVsHardNegativeAuc, 0);
            testCase.verifyLessThanOrEqual( ...
                extendedMetrics.positiveVsHardNegativeAuc, 1);
            ruleGrid = readtable(summary.outputFiles.ruleGridCsv);
            thresholdMode = string(ruleGrid.thresholdMode);
            familyFormation = string(ruleGrid.familyFormation);
            baseline = ruleGrid( ...
                thresholdMode == "common-1" ...
                & familyFormation == "any-member" ...
                & ruleGrid.localPercentile == 0 ...
                & ruleGrid.minimumFamilyVotes == 2, :);
            testCase.verifyEqual(height(baseline), 1);
            testCase.verifyGreaterThan( ...
                baseline.positiveRecall, 0.80);
            testCase.verifyGreaterThan( ...
                baseline.globalBackgroundActivation, 0);
            testCase.verifyLessThanOrEqual( ...
                baseline.globalBackgroundActivation, 1);
            ablation = readtable( ...
                summary.outputFiles.extendedFeatureAblationCsv);
            testCase.verifyEqual(height(ablation), 10);
            testCase.verifyEqual( ...
                string(ablation.variant(1:2)), ...
                ["all-16-features"; "legacy-12-only"]);
        end
    end
end
