classdef evaluateCurbDetectorDevelopmentRegressionTest ...
        < matlab.unittest.TestCase
% evaluateCurbDetectorDevelopmentRegressionTest Synthetic regression checks.

    properties
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function addScriptPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (TestMethodSetup)
        function createOutputDirectory(testCase)
            testCase.OutputDirectory = string(tempname);
            mkdir(testCase.OutputDirectory);
            testCase.addTeardown( ...
                @() rmdir(testCase.OutputDirectory, "s"));
        end
    end

    methods (Test)
        function mapsExactAndNearbySelectionsToRawLabels(testCase)
            summary = evaluateCurbDetectorDevelopmentRegression( ...
                "synthetic", ...
                OutputDirectory=testCase.OutputDirectory, ...
                NearbyToleranceM=0.30, ...
                MatchToleranceM=1.0e-8, ...
                LabelCatalog=testCase.syntheticCatalog(), ...
                FrameLoader=@testCase.syntheticFrameLoader, ...
                DetectorFunction=@testCase.syntheticDetector);

            results = readtable( ...
                summary.outputFiles.labelResultsCsv, ...
                TextType="string");
            frameSummary = readtable( ...
                summary.outputFiles.frameLabelSummaryCsv, ...
                TextType="string");

            testCase.verifyEqual( ...
                results.matchedRawPointIndexZeroBased, (0:3).');
            testCase.verifyEqual( ...
                logical(results.exactSelected), ...
                [true; false; true; false]);
            testCase.verifyEqual( ...
                logical(results.nearbySelected), ...
                [true; true; true; false]);
            testCase.verifyLessThan( ...
                results.nearestSelectedDistanceM(2), 0.30);
            testCase.verifyEqual( ...
                frameSummary.exactSelectedRate, [0.5; 0.5], ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                frameSummary.nearbySelectedRate, [1.0; 0.5], ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                summary.status, ...
                "completed-development-regression");
            testCase.verifyTrue( ...
                isfile(summary.outputFiles.summaryMat));
            testCase.verifyFalse(summary.detectorMasksUsedAsTruth);
        end

        function dominantFeatureLineAvoidsOrthogonalHeadingJump(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            datasetFolder = fullfile( ...
                repositoryRoot, "simulation", "data", ...
                "carla_outer_loop_lap_10hz_20260802_epic_no_rt_auto");
            testCase.assumeTrue(isfolder(datasetFolder), ...
                "The repository-local development dataset is unavailable.");

            summary = evaluateCurbDetectorDevelopmentRegression( ...
                datasetFolder, ...
                OutputDirectory=testCase.OutputDirectory, ...
                FrameIndices=[109, 122, 130, 144]);
            frameStatus = readtable( ...
                summary.outputFiles.frameStatusCsv, ...
                TextType="string");

            testCase.verifyLessThanOrEqual( ...
                abs(frameStatus.roadHeadingDegrees), ...
                10 * ones(height(frameStatus), 1));
            testCase.verifyEqual( ...
                frameStatus.roadFrameSource, ...
                repmat( ...
                    "feature-dominant-line", ...
                    height(frameStatus), 1));
        end
    end

    methods (Static)
        function catalog = syntheticCatalog()
            points = ...
                evaluateCurbDetectorDevelopmentRegressionTest ...
                .syntheticRawPoints();
            anchor = struct( ...
                "frameIndex", 7, ...
                "positiveCoordinatesM", points(1:2, 1:3), ...
                "hardNegativeCoordinatesM", points(3:4, 1:3));
            catalog = struct( ...
                "datasetName", "synthetic", ...
                "independentGroundTruth", false, ...
                "anchors", anchor);
        end

        function rawPoints = syntheticFrameLoader(~, frameIndex)
            assert(frameIndex == 7);
            rawPoints = ...
                evaluateCurbDetectorDevelopmentRegressionTest ...
                .syntheticRawPoints();
        end

        function processingResult = syntheticDetector(frame, ~)
            validLinearIndices = find(frame.valid);
            selectedLinearIndices = ...
                validLinearIndices([1, 3]);
            [ringIndices, azimuthIndices] = ind2sub( ...
                size(frame.valid), selectedLinearIndices);
            processingResult = struct( ...
                "curbs", [azimuthIndices, ringIndices]);
        end

        function rawPoints = syntheticRawPoints()
            azimuthDegrees = [0; 1; 20; 40];
            horizontalRangeM = 10 * ones(4, 1);
            ringIndex = 20;
            elevationDegrees = 10 ...
                - (ringIndex - 1) * 40 / 63;
            rawPoints = [ ...
                horizontalRangeM .* cosd(azimuthDegrees), ...
                horizontalRangeM .* sind(azimuthDegrees), ...
                horizontalRangeM .* tand(elevationDegrees) ...
                    .* ones(4, 1), ...
                (10:10:40).'];
        end
    end
end
