classdef evaluatePreDetectionCruiseTest < matlab.unittest.TestCase
% evaluatePreDetectionCruiseTest Pre-detection cruise acceptance.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
        end
    end

    methods (Test)
        function targetEntersRangeAfterTwoSecondsOfCruise(testCase)
            result = localResult(93.0);

            evaluation = evaluatePreDetectionCruise( ...
                result, MinimumDuration=2.0);

            testCase.verifyTrue(evaluation.passed);
            testCase.verifyTrue(evaluation.startsOutsideRange);
            testCase.verifyTrue( ...
                evaluation.detectionTransitionObserved);
            testCase.verifyTrue(evaluation.firstDetectionIsInRange);
            testCase.verifyEqual( ...
                evaluation.initialTargetRange, 93.0, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                evaluation.firstDetectionTime, 2.1, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                evaluation.firstDetectionRange, 30.0, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                evaluation.preDetectionDuration, 2.1, ...
                AbsTol=1.0e-12);
            testCase.verifyTrue(evaluation.cruiseMaintained);
            testCase.verifyEqual( ...
                evaluation.lateralTolerance, 0.25, AbsTol=0.0);
            testCase.verifyEqual( ...
                evaluation.headingTolerance, 0.03, AbsTol=0.0);
        end

        function initiallyVisibleTargetFailsThePhase(testCase)
            result = localResult(30.0);

            evaluation = evaluatePreDetectionCruise( ...
                result, MinimumDuration=2.0);

            testCase.verifyFalse(evaluation.passed);
            testCase.verifyFalse(evaluation.startsOutsideRange);
            testCase.verifyFalse( ...
                evaluation.detectionTransitionObserved);
            testCase.verifyEqual( ...
                evaluation.firstDetectionTime, 0.0, ...
                AbsTol=0.0);
        end
    end
end

function result = localResult(initialTargetRange)
    time = (0.0:0.1:3.0).';
    egoPositionX = 15.0*time;
    targetPositionX = initialTargetRange-15.0*time;
    targetRange = abs(targetPositionX-egoPositionX);
    detection = targetRange <= 30.0;
    targetTruth = arrayfun( ...
        @(positionX) struct( ...
            "targetPositionInertial", [positionX; 0.0]), ...
        targetPositionX, UniformOutput=false);
    result = struct( ...
        "scenario", struct("referenceSpeed", 15.0), ...
        "controlTime", time, ...
        "controlState", [ ...
            egoPositionX, zeros(size(time)), ...
            zeros(size(time)), 15.0*ones(size(time)), ...
            zeros(size(time)), zeros(size(time))], ...
        "controlTracking", struct( ...
            "lateralError", zeros(size(time)), ...
            "headingError", zeros(size(time))), ...
        "targetTruthAtControlSample", {targetTruth}, ...
        "perception", struct( ...
            "rangeMaximum", 30.0, ...
            "targetDetectionAvailable", detection));
end
