classdef fitPerceivedRoadBoundariesTest < matlab.unittest.TestCase
% fitPerceivedRoadBoundariesTest Sensor-limited quadratic curb fitting.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "controller")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
        end
    end

    methods (Test)
        function straightRoadUsesDeclaredOffsetsAndRange(testCase)
            positionX = (-100.0:0.1:100.0).';
            centerline = [positionX, zeros(size(positionX))];

            perception = fitPerceivedRoadBoundaries( ...
                centerline, [0.0; 0.0; 0.0]);
            rightBoundary = perception.roadGeometry.boundaries(1);
            leftBoundary = perception.roadGeometry.boundaries(2);
            rightMargin = quadraticRoadBoundaryRectangleMargin( ...
                [0.0; 0.0; 0.0], [5.0; 2.0], rightBoundary);
            leftMargin = quadraticRoadBoundaryRectangleMargin( ...
                [0.0; 0.0; 0.0], [5.0; 2.0], leftBoundary);

            testCase.verifyEqual(perception.rangeMaximum, ...
                30.0, AbsTol=0.0);
            testCase.verifyEqual(perception.rightOffset, ...
                6.0, AbsTol=0.0);
            testCase.verifyEqual(perception.leftOffset, ...
                8.0, AbsTol=0.0);
            testCase.verifyEqual(perception.shoulderWidth, ...
                2.6, AbsTol=0.0);
            testCase.verifyEqual(perception.rightOuterOffset, ...
                8.6, AbsTol=1.0e-12);
            testCase.verifyEqual(perception.leftOuterOffset, ...
                10.6, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                rightBoundary.coefficients, [0.0, 0.0, -8.6], ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                leftBoundary.coefficients, [0.0, 0.0, 10.6], ...
                AbsTol=1.0e-12);
            testCase.verifyEqual(rightMargin, 7.6, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual(leftMargin, 9.6, ...
                AbsTol=1.0e-12);
            testCase.verifyLessThanOrEqual( ...
                max([ ...
                    rightBoundary.maximumSourcePointRange, ...
                    leftBoundary.maximumSourcePointRange]), ...
                30.0 + 1.0e-12);
            testCase.verifyEqual( ...
                [rightBoundary.coveragePolicy, ...
                    leftBoundary.coveragePolicy], ...
                ["perceptionLimited", "perceptionLimited"]);
            testCase.verifyEqual( ...
                [rightBoundary.geometrySource, ...
                    leftBoundary.geometrySource], ...
                ["sensedRoadCurb", "sensedRoadCurb"]);
            bands = perception.roadGeometry ...
                .terminalLateralOffsetBands;
            testCase.verifyEqual( ...
                bands.right, [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                bands.left, [8.0, 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                perception.coveragePolicy, "perceptionLimited");
            testCase.verifyEqual( ...
                perception.terminalSetGeometrySource, ...
                "nominalPathFrenetOffsetBands");
            testCase.verifyFalse(isfield( ...
                perception.roadGeometry, "terminalShoulders"));
        end

        function curvedRoadProducesFiniteConservativeFits(testCase)
            radius = 50.0;
            arcLength = (-60.0:0.1:120.0).';
            angle = arcLength / radius;
            centerline = [ ...
                radius*sin(angle), radius*(1.0-cos(angle))];

            perception = fitPerceivedRoadBoundaries( ...
                centerline, [0.0; 0.0; 0.0]);
            boundaries = perception.roadGeometry.boundaries;
            coefficients = vertcat(boundaries.coefficients);
            fitError = [boundaries.verticalFitErrorBound];
            sourceRange = [boundaries.maximumSourcePointRange];

            testCase.verifyTrue(all(isfinite(coefficients), "all"));
            testCase.verifyGreaterThan( ...
                min(abs(coefficients(:, 1))), 1.0e-3);
            testCase.verifyGreaterThanOrEqual(fitError, 0.0);
            testCase.verifyLessThan(max(fitError), 0.5);
            testCase.verifyLessThanOrEqual( ...
                max(sourceRange), 30.0 + 1.0e-12);
            testCase.verifyGreaterThan( ...
                min([boundaries.sourcePointCount]), 100);
            bands = perception.roadGeometry ...
                .terminalLateralOffsetBands;
            testCase.verifyEqual( ...
                bands.right, [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                bands.left, [8.0, 10.6], AbsTol=1.0e-12);
        end
    end
end
