classdef fuseLidarRingCurbFeaturesTest < matlab.unittest.TestCase
% fuseLidarRingCurbFeaturesTest Behavior of side-agnostic family fusion.

    methods (TestClassSetup)
        function addPerceptionPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, ...
                    "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (Test)
        function thresholdsAreInclusiveAtBoundary(testCase)
            [features, validity] = localFeatureInputs([1, 2]);
            features.hataCompressionNormalized(:) = 0.25;
            features.heightStep = [0.005, 0.005 - 1.0e-12];
            cfg = struct("saliencyEnabled", false);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyEqual(accepted, [true, false]);
            testCase.verifyEqual( ...
                diagnostics.compressionEvidence, [true, true]);
            testCase.verifyEqual( ...
                diagnostics.verticalEvidence, [true, false]);
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount, uint8([2, 1]));
        end

        function invalidOrNonfiniteFeaturesCannotVote(testCase)
            [features, validity] = localFeatureInputs([1, 2]);
            validity = localInvalidateFeatureMasks(validity);
            features.hataCompressionNormalized = [1.0, NaN];
            features.ilpLineSlopeMagnitude = [1.0, Inf];

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity);

            testCase.verifyFalse(any(accepted, "all"));
            testCase.verifyFalse(any( ...
                diagnostics.compressionEvidence, "all"));
            testCase.verifyFalse(any(diagnostics.shapeEvidence, "all"));
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount, uint8([0, 0]));
            testCase.verifyEqual( ...
                diagnostics.availableFamilyCount, uint8([0, 0]));
        end

        function requiresTwoOfFourFamiliesByDefault(testCase)
            [features, validity] = localFeatureInputs([1, 4]);
            features.hataCompressionNormalized(2:4) = 1.0;
            features.heightStep(3:4) = 1.0;
            features.wangHorizontalSpacingExcess(4) = 1.0;
            features.radialSecondDifference(4) = 1.0;
            features.huangTangentialStrength(4) = 1.0;
            cfg = struct("saliencyEnabled", false);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyEqual( ...
                diagnostics.familyVoteCount, uint8([0, 1, 2, 4]));
            testCase.verifyEqual( ...
                diagnostics.radialMemberVoteCount, uint8([0, 0, 0, 2]));
            testCase.verifyEqual( ...
                diagnostics.availableFamilyCount, uint8([4, 4, 4, 4]));
            testCase.verifyEqual(accepted, [false, false, true, true]);
        end

        function radialFamilyRequiresTwoMembers(testCase)
            [features, validity] = localFeatureInputs([1, 2]);
            features.wangHorizontalSpacingExcess(:) = 1.0;
            features.radialSecondDifference(2) = 1.0;
            cfg = struct( ...
                "minimumFamilyVotes", 1, ...
                "saliencyEnabled", false);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyEqual( ...
                diagnostics.radialMemberVoteCount, uint8([1, 2]));
            testCase.verifyEqual( ...
                diagnostics.radialEvidence, [false, true]);
            testCase.verifyEqual(accepted, [false, true]);
        end

        function incompleteRadialFamilyCannotSupplySalientVote(testCase)
            [features, validity] = localFeatureInputs([1, 80]);
            targetColumn = 40;
            features.hataCompressionNormalized(targetColumn) = 1.0;
            features.heightStep(targetColumn) = 1.0;
            features.wangHorizontalSpacingExcess(targetColumn) = 1.0;
            cfg = struct("minimumSalientFamilyVotes", 3);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyTrue( ...
                diagnostics.compressionSalientEvidence(targetColumn));
            testCase.verifyTrue( ...
                diagnostics.verticalSalientEvidence(targetColumn));
            testCase.verifyFalse( ...
                diagnostics.radialEvidence(targetColumn));
            testCase.verifyFalse( ...
                diagnostics.radialSalientEvidence(targetColumn));
            testCase.verifyEqual( ...
                diagnostics.salientFamilyVoteCount(targetColumn), ...
                uint8(2));
            testCase.verifyFalse(accepted(targetColumn));
        end

        function localSaliencyAcceptsAtMinimumNeighborCount(testCase)
            [features, validity, targetColumn] = ...
                localTwoFamilySpike(12);

            % The spike is deliberately isolated to exercise the voting
            % rule alone, so the spatial-continuity gate is stood down.
            [accepted, diagnostics] = fuseLidarRingCurbFeatures( ...
                features, validity, localWithoutContinuity());

            testCase.verifyTrue(accepted(targetColumn));
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount(targetColumn), uint8(2));
            testCase.verifyEqual( ...
                diagnostics.salientFamilyVoteCount(targetColumn), ...
                uint8(2));
            testCase.verifyTrue( ...
                diagnostics.compressionSalientEvidence(targetColumn));
            testCase.verifyTrue( ...
                diagnostics.verticalSalientEvidence(targetColumn));
        end

        function sparseLocalBackgroundCannotBecomeSalient(testCase)
            [features, validity, targetColumn] = ...
                localTwoFamilySpike(11);

            [accepted, diagnostics] = fuseLidarRingCurbFeatures( ...
                features, validity, localWithoutContinuity());

            testCase.verifyFalse(accepted(targetColumn));
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount(targetColumn), uint8(2));
            testCase.verifyEqual( ...
                diagnostics.salientFamilyVoteCount(targetColumn), ...
                uint8(0));
        end

        function disabledSaliencyUsesOnlyAbsoluteFamilyVotes(testCase)
            [features, validity, targetColumn] = ...
                localTwoFamilySpike(11);
            cfg = localWithoutContinuity();
            cfg.saliencyEnabled = false;

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyTrue(accepted(targetColumn));
            testCase.verifyFalse(diagnostics.saliencyEnabled);
            testCase.verifyFalse(any( ...
                diagnostics.compressionSalientEvidence, "all"));
            testCase.verifyFalse(any( ...
                diagnostics.verticalSalientEvidence, "all"));
            testCase.verifyEqual( ...
                diagnostics.salientFamilyVoteCount, ...
                zeros(1, 80, "uint8"));
        end

        function mirrorsFeatureEvidenceWithoutSideSpecificBehavior(testCase)
            [features, validity] = localFeatureInputs([2, 80]);
            targetColumns = [25, 57];
            features.hataCompressionNormalized(:, targetColumns) = 1.0;
            features.heightStep(:, targetColumns) = 1.0;
            features.x = repmat(1:80, 2, 1);
            features.y = [-80:-1; 1:80];
            mirroredFeatures = localFlipFeatureFields(features);
            mirroredValidity = localFlipFeatureFields(validity);

            % Isolated target columns exercise side symmetry alone, so
            % the spatial-continuity gate is stood down here.
            [referenceAccepted, referenceDiagnostics] = ...
                fuseLidarRingCurbFeatures( ...
                    features, validity, localWithoutContinuity());
            [mirroredAccepted, mirroredDiagnostics] = ...
                fuseLidarRingCurbFeatures( ...
                    mirroredFeatures, mirroredValidity, ...
                    localWithoutContinuity());

            testCase.verifyEqual( ...
                mirroredAccepted, flip(referenceAccepted, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.familyVoteCount, ...
                flip(referenceDiagnostics.familyVoteCount, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.compressionEvidence, ...
                flip(referenceDiagnostics.compressionEvidence, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.verticalEvidence, ...
                flip(referenceDiagnostics.verticalEvidence, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.radialEvidence, ...
                flip(referenceDiagnostics.radialEvidence, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.shapeEvidence, ...
                flip(referenceDiagnostics.shapeEvidence, 2));
            testCase.verifyEqual( ...
                mirroredDiagnostics.salientFamilyVoteCount, ...
                flip(referenceDiagnostics.salientFamilyVoteCount, 2));
            testCase.verifyTrue(all( ...
                referenceAccepted(:, targetColumns), "all"));
        end

        function isolatedEvidenceFailsSpatialContinuity(testCase)
            [features, validity] = localFeatureInputs([3, 40]);
            features.hataCompressionNormalized(2, 20) = 1.0;
            features.heightStep(2, 20) = 1.0;
            arcColumns = 24:32;
            features.hataCompressionNormalized(2, arcColumns) = 1.0;
            features.heightStep(2, arcColumns) = 1.0;

            accepted = fuseLidarRingCurbFeatures( ...
                features, validity, ...
                struct("continuityMinimumNeighbors", 3, ...
                       "continuityAzimuthRadius", 4, ...
                       "continuityRingRadius", 0));

            testCase.verifyFalse(accepted(2, 20));
            testCase.verifyTrue(accepted(2, 28));
        end

        function disabledFusionAcceptsExactlyBaseValid(testCase)
            [features, validity] = localFeatureInputs([1, 3]);
            validity.base = [true, false, true];
            cfg = struct("enabled", false);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyEqual(accepted, validity.base);
            testCase.verifyFalse(diagnostics.enabled);
            testCase.verifyEqual( ...
                diagnostics.acceptedMask, validity.base);
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount, uint8([0, 0, 0]));
            testCase.verifyEqual( ...
                diagnostics.availableFamilyCount, uint8([4, 0, 4]));
        end

        function reportsCalibratedDefaultThresholds(testCase)
            [features, validity] = localFeatureInputs([1, 1]);
            cfg = struct("enabled", false);
            expectedThresholds = struct( ...
                "hataCompressionNormalized", 0.25, ...
                "heightStep", 0.005, ...
                "localHeightRange", 0.01875, ...
                "localMultiscaleHaarZ", 0.01125, ...
                "wangHorizontalSpacingExcess", 0.005625, ...
                "radiusRatioReconstructionDeviation", 1.0e-4, ...
                "radialSecondDifference", 0.009375, ...
                "localMultiscaleHaarRange", 0.045, ...
                "huangTangentialStrength", 0.1125, ...
                "sameRingSlopeChange", 0.0035, ...
                "ilpLineFitResidual", 0.00325, ...
                "ilpLineSlopeMagnitude", 0.025);

            [~, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyEqual( ...
                diagnostics.thresholds, expectedThresholds);
            testCase.verifyEqual( ...
                diagnostics.minimumRadialMemberVotes, uint8(2));
            testCase.verifyEqual( ...
                diagnostics.minimumSalientFamilyVotes, uint8(2));
        end

        function supportsPartialThresholdAndVoteOverrides(testCase)
            [features, validity] = localFeatureInputs([1, 1]);
            validity = localInvalidateFeatureMasks(validity);
            validity.hataCompressionNormalized(:) = true;
            features.hataCompressionNormalized(:) = 0.30;
            oneVoteCfg = struct("minimumFamilyVotes", 1);
            overrideCfg = struct( ...
                "minimumFamilyVotes", 1, ...
                "saliencyEnabled", false, ...
                "thresholds", struct( ...
                    "hataCompressionNormalized", 0.50));
            oneVoteCfg.saliencyEnabled = false;

            defaultAccepted = fuseLidarRingCurbFeatures( ...
                features, validity, oneVoteCfg);
            [overrideAccepted, diagnostics] = ...
                fuseLidarRingCurbFeatures( ...
                    features, validity, overrideCfg);

            testCase.verifyTrue(defaultAccepted);
            testCase.verifyFalse(overrideAccepted);
            testCase.verifyEqual( ...
                diagnostics.thresholds.hataCompressionNormalized, ...
                0.50, AbsTol=0.0);
            testCase.verifyEqual(diagnostics.minimumFamilyVotes, uint8(1));
        end

        function ilpLineSlopeContributesShapeEvidence(testCase)
            [features, validity] = localFeatureInputs([1, 1]);
            validity = localInvalidateFeatureMasks(validity);
            validity.ilpLineSlopeMagnitude(:) = true;
            features.ilpLineSlopeMagnitude(:) = 0.025;
            cfg = struct( ...
                "minimumFamilyVotes", 1, ...
                "saliencyEnabled", false);

            [accepted, diagnostics] = ...
                fuseLidarRingCurbFeatures(features, validity, cfg);

            testCase.verifyTrue(accepted);
            testCase.verifyTrue(diagnostics.shapeEvidence);
            testCase.verifyEqual( ...
                diagnostics.familyVoteCount, uint8(1));
            testCase.verifyEqual( ...
                diagnostics.availableFamilyCount, uint8(1));
        end

        function missingRequiredFeatureIsRejected(testCase)
            [features, validity] = localFeatureInputs([1, 1]);
            features = rmfield(features, "heightStep");

            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures(features, validity), ...
                "fuseLidarRingCurbFeatures:MissingFeatureField");
        end

        function inconsistentValiditySizeIsRejected(testCase)
            [features, validity] = localFeatureInputs([1, 2]);
            validity.localMultiscaleHaarRange = true(1, 3, 2);

            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures(features, validity), ...
                "fuseLidarRingCurbFeatures:InconsistentValiditySize");
        end

        function invalidThresholdOverrideIsRejected(testCase)
            [features, validity] = localFeatureInputs([1, 1]);
            cfg = struct( ...
                "thresholds", struct("sameRingSlopeChange", -1.0));

            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, cfg), ...
                "fuseLidarRingCurbFeatures:InvalidThreshold");
        end

        function invalidSaliencyConfigurationIsRejected(testCase)
            [features, validity] = localFeatureInputs([1, 1]);

            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, ...
                    struct("saliencyEnabled", 1)), ...
                "fuseLidarRingCurbFeatures:InvalidSaliencyEnabled");
            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, struct( ...
                        "localHalfWidthBins", 3, ...
                        "localExclusionBins", 3)), ...
                "fuseLidarRingCurbFeatures:InvalidLocalWindow");
            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, struct( ...
                        "localHalfWidthBins", 5, ...
                        "localExclusionBins", 3, ...
                        "minimumLocalNeighborCount", 7)), ...
                "fuseLidarRingCurbFeatures:" + ...
                    "InvalidMinimumLocalNeighborCount");
            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, ...
                    struct("localPercentileThreshold", 1.1)), ...
                "fuseLidarRingCurbFeatures:" + ...
                    "InvalidLocalPercentileThreshold");
            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, ...
                    struct("minimumRadialMemberVotes", 5)), ...
                "fuseLidarRingCurbFeatures:" + ...
                    "InvalidMinimumRadialMemberVotes");
            testCase.verifyError( ...
                @() fuseLidarRingCurbFeatures( ...
                    features, validity, ...
                    struct("minimumSalientFamilyVotes", 0)), ...
                "fuseLidarRingCurbFeatures:" + ...
                    "InvalidMinimumSalientFamilyVotes");
        end
    end
end

function [features, validity] = localFeatureInputs(matrixSize)
    scalarZeros = zeros(matrixSize);
    scalarTrue = true(matrixSize);
    scaleSize = [matrixSize, 2];
    features = struct( ...
        "hataCompressionNormalized", scalarZeros, ...
        "heightStep", scalarZeros, ...
        "localHeightRange", scalarZeros, ...
        "localMultiscaleHaarZ", zeros(scaleSize), ...
        "wangHorizontalSpacingExcess", scalarZeros, ...
        "radiusRatioReconstructionDeviation", scalarZeros, ...
        "radialSecondDifference", scalarZeros, ...
        "localMultiscaleHaarRange", zeros(scaleSize), ...
        "huangTangentialStrength", scalarZeros, ...
        "sameRingSlopeChange", scalarZeros, ...
        "ilpLineFitResidual", scalarZeros, ...
        "ilpLineSlopeMagnitude", scalarZeros);
    validity = struct( ...
        "base", scalarTrue, ...
        "hataCompressionNormalized", scalarTrue, ...
        "heightStep", scalarTrue, ...
        "localHeightRange", scalarTrue, ...
        "localMultiscaleHaarZ", true(scaleSize), ...
        "wangHorizontalSpacingExcess", scalarTrue, ...
        "radiusRatioReconstructionDeviation", scalarTrue, ...
        "radialSecondDifference", scalarTrue, ...
        "localMultiscaleHaarRange", true(scaleSize), ...
        "huangTangentialStrength", scalarTrue, ...
        "sameRingSlopeChange", scalarTrue, ...
        "ilpLineFitResidual", scalarTrue, ...
        "ilpLineSlopeMagnitude", scalarTrue);
end

function validity = localInvalidateFeatureMasks(validity)
    fieldNames = setdiff(string(fieldnames(validity)), "base");
    for fieldName = fieldNames.'
        validity.(fieldName)(:) = false;
    end
end

function [features, validity, targetColumn] = ...
        localTwoFamilySpike(neighborCount)
    numberOfBins = 80;
    targetColumn = 40;
    [features, validity] = localFeatureInputs([1, numberOfBins]);
    validity = localInvalidateFeatureMasks(validity);
    backgroundColumns = 7:(6 + neighborCount);
    validColumns = [backgroundColumns, targetColumn];
    validity.hataCompressionNormalized(validColumns) = true;
    validity.heightStep(validColumns) = true;
    features.hataCompressionNormalized(targetColumn) = 1.0;
    features.heightStep(targetColumn) = 1.0;
end

function output = localFlipFeatureFields(input)
    output = input;
    fieldNames = string(fieldnames(input));
    for fieldName = fieldNames.'
        output.(fieldName) = flip(input.(fieldName), 2);
    end
end

function cfg = localWithoutContinuity()
%LOCALWITHOUTCONTINUITY Stand down the spatial-continuity gate.
%   Tests that probe voting, saliency, or side symmetry build deliberately
%   isolated evidence, which the continuity gate would otherwise reject.
    cfg = struct("continuityMinimumNeighbors", 0);
end
