classdef nrmmObserverVectorFieldTest < matlab.unittest.TestCase
    % nrmmObserverVectorFieldTest Verify the extracted continuous core.

    properties
        Design
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            repoRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "estimator")));
        end
    end

    methods (TestMethodSetup)
        function synthesizeDesign(testCase)
            testCase.Design = synthesizeNrmmObserverGains( ...
                nrmmTrackingConfig());
        end
    end

    methods (Test)
        function egoEquationsMatchCovariantForm(testCase)
            yaw = 0.3;
            yawRate = 0.12;
            bodyVelocity = [8.0; 0.6];
            acceleration = [0.4; 1.1];
            gnssVelocity = [7.7; 2.9];
            position = [4.0; -2.0];
            positionReference = [4.2; -1.7];
            yawHeading = 0.38;
            estimate = struct( ...
                "yaw", yaw, ...
                "bodyVelocity", bodyVelocity, ...
                "position", position, ...
                "targetState", zeros(6, 0));
            measurement = struct( ...
                "yawRate", yawRate, ...
                "yawHeading", yawHeading, ...
                "gnssVelocity", gnssVelocity, ...
                "bodyAcceleration", acceleration, ...
                "positionReference", positionReference, ...
                "radarReference", zeros(2, 0), ...
                "radarAvailable", false(0, 1));
            rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
            planarCross = [0.0, -1.0; 1.0, 0.0];
            expectedYaw = yawRate ...
                + testCase.Design.yaw.correctionBandwidth ...
                    * (yawHeading-yaw);
            expectedVelocity = acceleration-yawRate ...
                    * planarCross*bodyVelocity ...
                + testCase.Design.velocity.gain ...
                    * (rotation.'*gnssVelocity-bodyVelocity);
            expectedPosition = rotation*bodyVelocity ...
                + testCase.Design.position.gain ...
                    * (positionReference-position);

            [derivative, model] = nrmmObserverVectorField( ...
                estimate, measurement, testCase.Design);

            testCase.verifyEqual(derivative.yaw, expectedYaw, ...
                AbsTol=1.0e-14);
            testCase.verifyEqual(derivative.bodyVelocity, ...
                expectedVelocity, AbsTol=1.0e-14);
            testCase.verifyEqual(derivative.position, ...
                expectedPosition, AbsTol=1.0e-14);
            testCase.verifyEqual(model.inertialVelocity, ...
                rotation*bodyVelocity, AbsTol=1.0e-14);
        end

        function yawCorrectionUsesContinuousCircularLift(testCase)
            estimate = localEstimate(pi-0.1);
            measurement = localMeasurement(-pi+0.1, true);
            expected = measurement.yawRate ...
                + 0.2*testCase.Design.yaw.correctionBandwidth;

            derivative = nrmmObserverVectorField( ...
                estimate, measurement, testCase.Design);

            testCase.verifyEqual(derivative.yaw, expected, ...
                AbsTol=1.0e-14);
        end

        function radarInnovationEntersAllCovariantChainRows(testCase)
            estimate = localEstimate(0.2);
            measurement = localMeasurement(0.25, true);
            ego = struct( ...
                "bodyVelocity", estimate.bodyVelocity, ...
                "yawRate", measurement.yawRate);
            plant = nrmmTargetTrackerDerivative( ...
                estimate.targetState, ego, testCase.Design.target.domain);
            innovation = measurement.radarReference ...
                - estimate.targetState(1:2);
            gains = testCase.Design.target.innovationGains;
            expected = plant+[gains(1)*innovation; ...
                gains(2)*innovation; gains(3)*innovation];

            [derivative, model] = nrmmObserverVectorField( ...
                estimate, measurement, testCase.Design);

            testCase.verifyEqual(derivative.targetState, expected, ...
                RelTol=1.0e-13, AbsTol=1.0e-10);
            testCase.verifyEqual(model.targetPlantDerivative, plant, ...
                AbsTol=1.0e-14);
        end

        function radarDropoutRemovesOnlyMeasurementInjection(testCase)
            estimate = localEstimate(-0.1);
            measurement = localMeasurement(-0.05, false);
            ego = struct( ...
                "bodyVelocity", estimate.bodyVelocity, ...
                "yawRate", measurement.yawRate);
            expected = nrmmTargetTrackerDerivative( ...
                estimate.targetState, ego, testCase.Design.target.domain);

            derivative = nrmmObserverVectorField( ...
                estimate, measurement, testCase.Design);

            testCase.verifyEqual(derivative.targetState, expected, ...
                AbsTol=1.0e-14);
        end
    end
end

function estimate = localEstimate(yaw)
    estimate = struct( ...
        "yaw", yaw, ...
        "bodyVelocity", [8.0; 0.5], ...
        "position", [2.0; -1.0], ...
        "targetState", [18.0; 2.0; 12.0; 1.0; 0.3; 0.4]);
end

function measurement = localMeasurement(yawHeading, radarAvailable)
    measurement = struct( ...
        "yawRate", 0.1, ...
        "yawHeading", yawHeading, ...
        "gnssVelocity", [7.8; 2.2], ...
        "bodyAcceleration", [0.2; 0.9], ...
        "positionReference", [2.1; -0.8], ...
        "radarReference", [17.7; 2.3], ...
        "radarAvailable", radarAvailable);
end
