classdef observerGainSynthesisTest < matlab.unittest.TestCase
    % observerGainSynthesisTest Verify solved gains and certificates.

    properties
        Cfg
        Design
    end

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            repoRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "estimator")));
        end
    end

    methods (TestMethodSetup)
        function synthesizeDefaultDesign(testCase)
            testCase.Cfg = nrmmTrackingConfig();
            testCase.Design = synthesizeNrmmObserverGains(testCase.Cfg);
        end
    end

    methods (Test)
        function allGainsAreSolvedWithoutManualDesignFields(testCase)
            cfg = testCase.Cfg;
            design = testCase.Design;

            testCase.verifyFalse(isfield(cfg, "observerDesign"));
            gains = [design.velocity.gain; ...
                design.position.gain; design.target.innovationGains];
            testCase.verifyTrue(all(isfinite(gains)));
            testCase.verifyGreaterThan(gains, zeros(size(gains)));
            testCase.verifyEqual(design.target.shape, "lmi-solved");
            testCase.verifyEqual(design.gainSelection.method, ...
                "structured-lipschitz-iss-minimax-synthesis");
            testCase.verifyEqual(design.gainSelection.scalarMethod, ...
                "minimum-bandwidth-continuous-decay");
        end

        function yawMeasurementContainsNoReliabilityTuning(testCase)
            yaw = testCase.Design.yaw;
            fields = string(fieldnames(yaw));

            testCase.verifyEqual(yaw.measurementMethod, ...
                "kinematic-sideslip-corrected-certified-correspondence");
            testCase.verifyFalse(any(ismember(fields, ...
                ["courseFraction", "preferredChannel", "courseGain", ...
                "accelerationGain", "minimumChannelFraction"])));
            testCase.verifyEqual(yaw.courseModel.rearAxleDistance, ...
                testCase.Cfg.ego.yaw.rearAxleDistance, AbsTol=0.0);
            testCase.verifyEqual( ...
                yaw.courseModel.singleTrackYawRateMismatchMaximum, ...
                testCase.Cfg.ego.yaw ...
                    .singleTrackYawRateMismatchMaximum, AbsTol=0.0);
        end

        function velocityCertificateIsExactAtYawRateVertices(testCase)
            certificate = testCase.Design.velocity;
            yawRate = ...
                testCase.Design.operatingDomain.measuredYawRateMaximum;
            planarCross = [0.0, -1.0; 1.0, 0.0];
            positiveVertex = -certificate.gain*eye(2) ...
                - yawRate*planarCross;
            negativeVertex = -certificate.gain*eye(2) ...
                + yawRate*planarCross;
            positiveResidual = positiveVertex.'+positiveVertex ...
                + 2.0*certificate.lambda*eye(2);
            negativeResidual = negativeVertex.'+negativeVertex ...
                + 2.0*certificate.lambda*eye(2);

            testCase.verifyEqual(certificate.lyapunovMatrix, eye(2), ...
                AbsTol=0.0);
            testCase.verifyEqual(certificate.lambda, certificate.gain, ...
                AbsTol=0.0);
            testCase.verifyEqual(positiveResidual, zeros(2), ...
                AbsTol=1.0e-14);
            testCase.verifyEqual(negativeResidual, zeros(2), ...
                AbsTol=1.0e-14);
        end

        function targetDirectionIsRecoveredFromFixedRegionLmi(testCase)
            certificate = testCase.Design.target;
            chainMatrix = [0.0, 1.0, 0.0; ...
                0.0, 0.0, 1.0; 0.0, 0.0, 0.0];
            outputVector = [1.0; 0.0; 0.0];
            expectedMatrix = chainMatrix ...
                - certificate.injectionVector*outputVector.';
            identityResidual = certificate.closedLoopMatrix.' ...
                * certificate.lyapunovMatrix ...
                + certificate.lyapunovMatrix ...
                    * certificate.closedLoopMatrix+eye(3);
            designMatrix = certificate.designLyapunovMatrix;
            recoveredVariable = designMatrix ...
                * certificate.injectionVector;
            weighted = designMatrix*chainMatrix ...
                - recoveredVariable*outputVector.';
            regionResidual = weighted+weighted.' ...
                + 2.0*designMatrix;
            boundedRealResidual = [ ...
                certificate.closedLoopMatrix.'*designMatrix ...
                    + designMatrix*certificate.closedLoopMatrix+eye(3), ...
                    -recoveredVariable; ...
                -recoveredVariable.', -certificate.shapeObjectiveValue];

            testCase.verifyEqual(certificate.shape, "lmi-solved");
            testCase.verifyEqual(certificate.normalizedDecayRate, 1.0, ...
                AbsTol=0.0);
            testCase.verifyEqual(certificate.closedLoopMatrix, ...
                expectedMatrix, AbsTol=1.0e-12);
            testCase.verifyLessThanOrEqual( ...
                max(real(certificate.closedLoopPoles)), ...
                -1.0*(1.0-1.0e-6));
            testCase.verifyLessThanOrEqual( ...
                max(eig((regionResidual+regionResidual.')/2.0)), ...
                1.0e-7);
            testCase.verifyLessThanOrEqual(max(eig( ...
                (boundedRealResidual+boundedRealResidual.')/2.0)), ...
                1.0e-7);
            testCase.verifyEqual(identityResidual, zeros(3), ...
                AbsTol=1.0e-10);
            testCase.verifyGreaterThanOrEqual( ...
                certificate.certificateResidualMargin, -1.0e-9);
        end

        function targetGainsRetainHighGainScalingAndCertifiedDecay(testCase)
            certificate = testCase.Design.target;
            expectedInnovation = certificate.injectionVector ...
                .*[certificate.bandwidth;certificate.bandwidth^2;certificate.bandwidth^3];
            testCase.verifyEqual(certificate.innovationGains,expectedInnovation,RelTol=1e-12);
            testCase.verifyGreaterThanOrEqual(certificate.lambda,certificate.minimumDecayRate);
            testCase.verifyGreaterThanOrEqual(certificate.bandwidth,certificate.bandwidthSearchBracket(1));
            testCase.verifyLessThanOrEqual(certificate.bandwidth,certificate.bandwidthSearchBracket(2));
            testCase.verifyGreaterThanOrEqual(min(eig(certificate.lipschitzDissipationMatrix)),-1e-8);
            testCase.verifyGreaterThan(certificate.lipschitzMultipliers,zeros(2,1));
            testCase.verifyGreaterThan(certificate.transitLyapunovBound, ...
                testCase.Design.ultimateBounds.targetLyapunov);
        end

        function scalarBandwidthsMeetContinuousTransitDecay(testCase)
            cfg = testCase.Cfg;
            gains = [testCase.Design.velocity.gain; testCase.Design.position.gain];
            transitTime = cfg.target.domain.relativePositionMaximum ...
                /(cfg.ego.domain.speedMaximum+cfg.target.domain.speedMaximum);

            testCase.verifyEqual(exp(-gains*transitTime), ...
                0.05*ones(2,1), AbsTol=1.0e-12);
            testCase.verifyGreaterThan(gains, zeros(2,1));
        end

        function analyticLipschitzBoundsImproveTheCoarseProductBounds(testCase)
            constants = localDerivedConstants(testCase.Cfg);
            target = testCase.Design.target;
            lipschitz = target.lipschitzCertificate;

            testCase.verifyEqual(target.domain.yawRateMaximum, ...
                constants.targetYawRateMaximum, RelTol=1.0e-12);
            testCase.verifyEqual(target.domain.accelerationNormBound, ...
                constants.targetAccelerationNormBound, RelTol=1.0e-12);
            testCase.verifyLessThan(lipschitz.phiVelocity,constants.phiVelocityLipschitz);
            testCase.verifyLessThan(lipschitz.phiAcceleration,constants.phiAccelerationLipschitz);
            testCase.verifyLessThan(lipschitz.phi,constants.phiLipschitz);
        end

        function noAuxiliaryComparisonMatrixIsExposed(testCase)
            design = testCase.Design;

            testCase.verifyFalse(isfield(design, "comparison"));
            testCase.verifyFalse(isfield(design.ultimateBounds, ...
                "comparisonState"));
            testCase.verifySize(design.coreIss.matrix, [2, 2]);
            testCase.verifyEqual(diag(design.coreIss.matrix), ...
                -[design.velocity.lambda; design.target.lambda], ...
                RelTol=1.0e-12);
        end

        function coreCopositiveWeightsSatisfyExactIdentity(testCase)
            certificate = testCase.Design.coreIss;

            testCase.verifyEqual(certificate.type, ...
                "linear-copositive");
            testCase.verifyEqual(certificate.weights.' ...
                * certificate.matrix, -ones(1, 2), ...
                RelTol=1.0e-12, AbsTol=1.0e-12);
            testCase.verifyEqual(certificate.decayRate, ...
                1.0/max(certificate.weights), RelTol=1.0e-12);
            testCase.verifyEqual(certificate.inputProjection, ...
                certificate.weights.'*certificate.input, ...
                RelTol=1.0e-12);
        end

        function ultimateBoundsFollowTriangularForwardSubstitution(testCase)
            cfg = testCase.Cfg;
            design = testCase.Design;
            bounds = design.ultimateBounds;
            expectedYaw = pi;
            expectedVelocity = design.velocity.disturbanceBound/design.velocity.lambda;
            expectedPosition = cfg.measurement.gps.positionNoiseMaximum ...
                + cfg.measurement.gps.velocityNoiseMaximum/design.position.gain;
            expectedTarget = (design.coupling.targetVelocityCoupling ...
                    * expectedVelocity+design.target.disturbanceBound) ...
                / design.target.lambda;

            testCase.verifyEqual(bounds.yaw, expectedYaw, ...
                RelTol=1.0e-12);
            testCase.verifyEqual(bounds.bodyVelocity, ...
                expectedVelocity, RelTol=1.0e-12);
            testCase.verifyEqual(bounds.position, expectedPosition, ...
                RelTol=1.0e-12);
            testCase.verifyEqual(bounds.targetLyapunov, ...
                expectedTarget, RelTol=1.0e-12);
            testCase.verifyEqual(bounds.relativePosition, ...
                bounds.targetLyapunov*design.target.componentConversion(1), ...
                RelTol=1.0e-12);
        end

        function runtimeTimingDoesNotChangeContinuousDesign(testCase)
            cfg = testCase.Cfg;
            cfg.runtime.samplePeriod = 2.0;
            cfg.runtime.integrationStepMaximum = 0.001;
            design = synthesizeNrmmObserverGains(cfg);

            testCase.verifyEqual(design, testCase.Design, AbsTol=1.0e-12);
        end

        function continuousDesignNeedsNoRuntimeConfiguration(testCase)
            cfg = rmfield(testCase.Cfg, "runtime");
            design = synthesizeNrmmObserverGains(cfg);

            testCase.verifyEqual(design, testCase.Design, AbsTol=1.0e-12);
        end

        function physicalTransitTimeChangesContinuousDecay(testCase)
            cfg = testCase.Cfg;
            cfg.target.domain.relativePositionMaximum = ...
                2.0*cfg.target.domain.relativePositionMaximum;
            design = synthesizeNrmmObserverGains(cfg);

            testCase.verifyEqual(design.velocity.gain, ...
                0.5*testCase.Design.velocity.gain, AbsTol=1.0e-12);
            testCase.verifyEqual(design.position.gain, ...
                0.5*testCase.Design.position.gain, AbsTol=1.0e-12);
            testCase.verifyEqual(design.target.minimumDecayRate, ...
                0.5*testCase.Design.target.minimumDecayRate, AbsTol=1.0e-12);
        end

        function declaredUncertaintyPropagatesIntoContinuousBounds(testCase)
            gyroConfig = testCase.Cfg;
            gyroConfig.measurement.gyroscope.noiseMaximum = 0.004;
            gyroDesign = synthesizeNrmmObserverGains(gyroConfig);
            positionConfig = testCase.Cfg;
            positionConfig.measurement.gps.positionNoiseMaximum = 0.24;
            positionDesign = synthesizeNrmmObserverGains(positionConfig);

            testCase.verifyGreaterThan(gyroDesign.ultimateBounds.bodyVelocity, ...
                testCase.Design.ultimateBounds.bodyVelocity);
            testCase.verifyGreaterThan(positionDesign.ultimateBounds.position, ...
                testCase.Design.ultimateBounds.position);
        end

        function exactDataDegeneracyUsesPhysicalTieBreak(testCase)
            cfg = testCase.Cfg;
            cfg.ego.yaw.singleTrackYawRateMismatchMaximum = 0.0;
            cfg.measurement.gps.positionNoiseMaximum = 0.0;
            cfg.measurement.gps.velocityNoiseMaximum = 0.0;
            cfg.measurement.imu.noiseMaximum = 0.0;
            cfg.measurement.gyroscope.noiseMaximum = 0.0;
            cfg.measurement.radar.noiseMaximum = 0.0;
            design = synthesizeNrmmObserverGains(cfg);
            minimumGain = log(20.0)/design.gainSelection.domainTransitTime;

            testCase.verifyEqual(design.velocity.gain, minimumGain, ...
                RelTol=1.0e-12);
            testCase.verifyEqual(design.position.gain, minimumGain, ...
                RelTol=1.0e-12);
            testCase.verifyEqual(design.target.bandwidthActiveConstraint, ...
                "domain-transit-decay");
        end

        function invalidDesignRequestsAreRejected(testCase)
            legacyGain = testCase.Cfg;
            legacyGain.observerDesign.decayRate.yaw = 2.0;
            invalidSideslip = testCase.Cfg;
            invalidSideslip.ego.yaw.sideslipDomainMaximum = pi/2;
            invalidRearAxle = testCase.Cfg;
            invalidRearAxle.ego.yaw.rearAxleDistance = 0.0;
            invalidMismatch = testCase.Cfg;
            invalidMismatch.ego.yaw ...
                .singleTrackYawRateMismatchMaximum = -0.01;
            invalidSpeed = testCase.Cfg;
            invalidSpeed.ego.domain.speedMinimum = ...
                invalidSpeed.ego.domain.speedMaximum+1;

            testCase.verifyError(@() synthesizeNrmmObserverGains( ...
                legacyGain), ...
                "synthesizeNrmmObserverGains:legacyManualGainConfiguration");
            testCase.verifyError(@() synthesizeNrmmObserverGains( ...
                invalidSideslip), ...
                "synthesizeNrmmObserverGains:invalidSideslipBound");
            testCase.verifyError(@() synthesizeNrmmObserverGains( ...
                invalidRearAxle), ...
                "synthesizeNrmmObserverGains:invalidPositiveScalar");
            testCase.verifyError(@() synthesizeNrmmObserverGains( ...
                invalidMismatch), ...
                "synthesizeNrmmObserverGains:invalidNonnegativeScalar");
            testCase.verifyError(@() synthesizeNrmmObserverGains( ...
                invalidSpeed), ...
                "synthesizeNrmmObserverGains:invalidEgoSpeedInterval");
        end
    end
end

function constants = localDerivedConstants(cfg)
% localDerivedConstants Recompute the target-domain Lipschitz constants.
    speedMinimum = cfg.target.domain.speedMinimum;
    speedMaximum = cfg.target.domain.speedMaximum;
    accelerationMaximum = cfg.target.domain.scalarAccelerationMaximum;
    yawRateMaximum = speedMaximum ...
        * sin(cfg.target.domain.sideslipMaximum) ...
        / cfg.target.domain.rearAxleDistance;
    accelerationNormBound = hypot(accelerationMaximum, ...
        speedMaximum*yawRateMaximum);
    accelerationVelocityLipschitz = ...
        2.0*accelerationNormBound/speedMinimum;
    yawRateVelocityLipschitz = ...
        3.0*accelerationNormBound/speedMinimum^2;
    yawRateAccelerationLipschitz = 1.0/speedMinimum;
    phiVelocityLipschitz = yawRateMaximum^2 ...
        + 2.0*yawRateMaximum*speedMaximum*yawRateVelocityLipschitz ...
        + 3.0*(2.0*accelerationMaximum*yawRateMaximum/speedMinimum ...
            + accelerationMaximum*yawRateVelocityLipschitz ...
            + yawRateMaximum*accelerationVelocityLipschitz);
    phiAccelerationLipschitz = ...
        2.0*yawRateMaximum*speedMaximum*yawRateAccelerationLipschitz ...
        + 3.0*(accelerationMaximum*yawRateAccelerationLipschitz ...
            + yawRateMaximum);

    constants = struct( ...
        "targetYawRateMaximum", yawRateMaximum, ...
        "targetAccelerationNormBound", accelerationNormBound, ...
        "phiVelocityLipschitz", phiVelocityLipschitz, ...
        "phiAccelerationLipschitz", phiAccelerationLipschitz, ...
        "phiLipschitz", hypot(phiVelocityLipschitz, ...
            phiAccelerationLipschitz));
end
