classdef oncomingVehicleAvoidanceScenarioTest < matlab.unittest.TestCase
% oncomingVehicleAvoidanceScenarioTest High-fidelity avoidance behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(repositoryRoot,"config")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function limitedRoadCoverageAdmitsOnlyCoveredLookahead( ...
                testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=0.1, ControllerConfiguration=finiteSensingValidationConfig(), ...
                TargetInitialLongitudinalDistance=120.0, ...
                Plot=false, Report=false);

            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetSampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 2);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 2);
            testCase.verifyEqual( ...
                result.controlTime, [0;0.05;0.1], AbsTol=1e-12);
            testCase.verifyNumElements(result.command,2);
            testCase.verifyNumElements(result.attempts.targetEstimate, 2);

            testCase.verifyEqual( ...
                result.avoidance.targetLateralOffset, ...
                1.5, AbsTol=0.0);
            testCase.verifyTrue( ...
                abs(result.avoidance.targetLateralOffset) ...
                < 0.5 * ( ...
                    result.controllerConfiguration.vehicle.width + 2.0));
            testCase.verifyEmpty(result.attempts.targetEstimate{1});
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.length, ...
                5.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.width, ...
                2.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.rangeMaximum, 30.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadShoulderWidth, ...
                2.6, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadOuterBoundaryOffsets, ...
                [8.6; 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadTotalWidthIncludingShoulders, ...
                19.2, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.shoulderWidthToVehicleWidthRatio, ...
                1.3, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadCurbCoveragePolicy, ...
                "perceptionLimited");
            testCase.verifyEqual( ...
                result.perception.terminalSetGeometrySource, ...
                "nominalPathFrenetOffsetBands");
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.right, ...
                [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.left, ...
                [8.0, 10.6], AbsTol=1.0e-12);
            testCase.verifyFalse(isfield(result, "diagnostics"));
        end

        function anOutOfRangeTargetPermitsFreshCruiseSolves( ...
                testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=0.3, ControllerConfiguration=finiteSensingValidationConfig(), ...
                Plot=false, Report=false);

            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 6);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 6);
            testCase.verifyEqual( ...
                result.controlTime, (0:6).'*0.05, ...
                AbsTol=1.0e-15);
            testCase.verifyNumElements(result.command,6);
            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyFalse(any( ...
                result.perception.targetDetectionAvailable));
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyFalse(isfield( ...
                result.avoidance, "passingSpeedSufficient"));
        end
    end
end
