classdef oncomingVehicleAvoidanceScenarioTest < matlab.unittest.TestCase
% oncomingVehicleAvoidanceScenarioTest High-fidelity avoidance behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function feasibleColdStartProducesAHardConstraintCommand( ...
                testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=0.1, ...
                TargetInitialLongitudinalDistance=120.0, ...
                Plot=false, Report=false);

            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.1, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetSampleTime, ...
                0.1, AbsTol=0.0);
            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 1);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 1);
            testCase.verifyEqual( ...
                result.controlTime, [0.0; 0.1], AbsTol=0.0);
            testCase.verifyNumElements(result.command, 1);
            testCase.verifyNumElements(result.targetEstimate, 1);

            testCase.verifyEqual( ...
                result.avoidance.targetLateralOffset, ...
                1.5, AbsTol=0.0);
            testCase.verifyTrue( ...
                abs(result.avoidance.targetLateralOffset) ...
                < 0.5 * ( ...
                    result.controllerConfiguration.vehicle.width + 2.0));
            testCase.verifyTrue( ...
                result.avoidance.offsetBelowCombinedHalfWidths);
            testCase.verifyEmpty(result.targetEstimate{1});
            testCase.verifyTrue(result.roadSafety.noBoundaryCrossing);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.length, ...
                5.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.width, ...
                2.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.rangeMaximum, 30.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadShoulderWidth, ...
                2.6, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadOuterBoundaryOffsets, ...
                [8.6; 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadTotalWidthIncludingShoulders, ...
                19.2, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.shoulderWidthToVehicleWidthRatio, ...
                1.3, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadCurbCoveragePolicy, ...
                "perceptionLimited");
            testCase.verifyEqual( ...
                result.perception.terminalSetGeometrySource, ...
                "nominalPathFrenetOffsetBands");
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.right, ...
                [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.left, ...
                [8.0, 10.6], AbsTol=1.0e-12);
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyFalse(isfield(result, "diagnostics"));
        end

        function fiftyMeterColdStartProducesAHardConstraintCommand( ...
                testCase)
            result = runOncomingVehicleAvoidanceScenario( ...
                Duration=0.3, ...
                Plot=false, Report=false);

            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 3);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 3);
            testCase.verifyEqual( ...
                result.controlTime, (0.0:0.1:0.3).', ...
                AbsTol=1.0e-15);
            testCase.verifyNumElements(result.command, 3);
            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyFalse(any( ...
                result.perception.targetDetectionAvailable));
            testCase.verifyTrue(result.roadSafety.noBoundaryCrossing);
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyFalse(isfield( ...
                result.avoidance, "passingSpeedSufficient"));
        end
    end
end
