classdef onlineNrmmTrackingRuntimeTest < matlab.unittest.TestCase
% onlineNrmmTrackingRuntimeTest Synchronized runtime and planner contracts.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            repoRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "config")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "estimator"), IncludingSubfolders=true));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "controller")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repoRoot, "scripts")));
        end
    end

    methods (TestMethodSetup)
        function resetControllerState(~)
            collisionAvoidanceController("resetNominalTrajectory");
        end
    end

    methods (Test)
        function stepAdvancesOutputTimeByOneSamplePeriod(testCase)
            runtime = localRuntime(1);
            samplePeriod = runtime.samplePeriod;

            [runtime, output] = onlineNrmmTrackingRuntime( ...
                "step", runtime, localCruiseFrame(0.0));

            testCase.verifyEqual(output.time, samplePeriod, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual(output.stateTime, output.time, ...
                AbsTol=0.0);
            testCase.verifyEqual(output.inputSampleTime, 0.0, AbsTol=0.0);
            testCase.verifyEqual(output.lastGnssTime, 0.0, AbsTol=0.0);
            testCase.verifyEqual(output.lastImuTime, 0.0, AbsTol=0.0);
            testCase.verifyEqual( ...
                output.lastGyroscopeTime, 0.0, AbsTol=0.0);
            testCase.verifyEqual(output.lastRadarTime, 0.0, AbsTol=0.0);
            testCase.verifyEqual(runtime.currentTime, samplePeriod, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                output.targetEstimates(1).estimateTime, samplePeriod, ...
                AbsTol=1.0e-12);

            [~, secondOutput] = onlineNrmmTrackingRuntime( ...
                "step", runtime, localCruiseFrame(samplePeriod));

            testCase.verifyEqual(secondOutput.time, 2.0*samplePeriod, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                secondOutput.inputSampleTime, samplePeriod, AbsTol=0.0);
        end

        function outputActionLeavesRuntimeStateUntouched(testCase)
            runtime = localRuntime(1);
            [runtime, stepOutput] = onlineNrmmTrackingRuntime( ...
                "step", runtime, localCruiseFrame(0.0));
            probeFrame = localCruiseFrame(runtime.samplePeriod);

            firstProbe = onlineNrmmTrackingRuntime( ...
                "output", runtime, probeFrame);
            secondProbe = onlineNrmmTrackingRuntime( ...
                "output", runtime, probeFrame);

            testCase.verifyEqual(firstProbe.time, runtime.currentTime, ...
                AbsTol=0.0);
            testCase.verifyEqual(firstProbe.stateTime, ...
                runtime.currentTime, AbsTol=0.0);
            testCase.verifyEqual(firstProbe.inputSampleTime, ...
                probeFrame.time, AbsTol=0.0);
            testCase.verifyEqual(firstProbe.egoPositionInertial, ...
                stepOutput.egoPositionInertial, AbsTol=0.0);
            testCase.verifyEqual(firstProbe.targetStates, ...
                stepOutput.targetStates, AbsTol=0.0);
            testCase.verifyEqual(secondProbe, firstProbe);

            [~, nextOutput] = onlineNrmmTrackingRuntime( ...
                "step", runtime, probeFrame);

            testCase.verifyEqual(nextOutput.time, ...
                probeFrame.time+runtime.samplePeriod, AbsTol=1.0e-12);
        end

        function framesMustLieOnTheSampleGrid(testCase)
            runtime = localRuntime(1);
            offGridFrame = localCruiseFrame(0.02);

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, offGridFrame), ...
                "onlineNrmmTrackingRuntime:offSampleGrid");
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "output", runtime, offGridFrame), ...
                "onlineNrmmTrackingRuntime:offSampleGrid");

            [runtime, ~] = onlineNrmmTrackingRuntime( ...
                "step", runtime, localCruiseFrame(0.0));

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, localCruiseFrame(0.08)), ...
                "onlineNrmmTrackingRuntime:offSampleGrid");
        end

        function initializationRequiresEveryInitialStateOption(testCase)
            cfg = nrmmTrackingConfig();
            design = nrmmWindowEstimatorDesign(cfg);
            requiredOptionNames = ["egoInitialPosition", ...
                "egoInitialYaw", "egoInitialBodyVelocity", ...
                "targetInitialState"];

            for optionName = requiredOptionNames
                options = rmfield(localOptions(1), optionName);
                testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                    "initialize", cfg, options, design), ...
                    "onlineNrmmTrackingRuntime:missingInitialState", ...
                    "Missing " + optionName + " must be rejected.");
            end
        end

        function initializationRejectsWrongSizedOptions(testCase)
            cfg = nrmmTrackingConfig();
            design = nrmmWindowEstimatorDesign(cfg);
            invalidCases = { ...
                "egoInitialPosition", [0.0; 0.0; 0.0]; ...
                "egoInitialYaw", [0.0; 0.0]; ...
                "egoInitialBodyVelocity", 10.0; ...
                "targetInitialState", zeros(5, 1)};

            for caseIdx = 1:size(invalidCases, 1)
                options = localOptions(1);
                options.(invalidCases{caseIdx, 1}) = ...
                    invalidCases{caseIdx, 2};
                testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                    "initialize", cfg, options, design), ...
                    "onlineNrmmTrackingRuntime:invalidInitialState", ...
                    "Wrong-sized " + invalidCases{caseIdx, 1} ...
                        + " must be rejected.");
            end

            twoTargetOptions = localOptions(2);
            twoTargetOptions.targetInitialState = ...
                [100.0; 2.0; -12.0; 0.0; 0.0; 0.0];
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "initialize", cfg, twoTargetOptions, design), ...
                "onlineNrmmTrackingRuntime:invalidInitialState");

            fractionalCountOptions = localOptions(1);
            fractionalCountOptions.targetCount = 1.5;
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "initialize", cfg, fractionalCountOptions, design), ...
                "onlineNrmmTrackingRuntime:invalidOption");
        end

        function multiTargetInitializationRequiresStableIdentifiers( ...
                testCase)
            cfg = nrmmTrackingConfig();
            design = nrmmWindowEstimatorDesign(cfg);
            options = rmfield(localOptions(2), "targetIdentifiers");

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "initialize", cfg, options, design), ...
                "onlineNrmmTrackingRuntime:missingTargetIdentifiers");
        end

        function initializationRejectsDuplicateTargetIdentifiers(testCase)
            cfg = nrmmTrackingConfig();
            design = nrmmWindowEstimatorDesign(cfg);
            options = localOptions(2);
            options.targetIdentifiers = ["same"; "same"];

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "initialize", cfg, options, design), ...
                "onlineNrmmTrackingRuntime:invalidTargetIdentifiers");
        end

        function initializationRejectsInconsistentSamplePeriod(testCase)
            cfg = nrmmTrackingConfig();
            design = nrmmWindowEstimatorDesign(cfg);
            mismatchedCfg = cfg;
            mismatchedCfg.runtime.samplePeriod = ...
                2.0*cfg.runtime.samplePeriod;

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "initialize", mismatchedCfg, localOptions(1), design), ...
                "onlineNrmmTrackingRuntime:inconsistentSamplePeriod");
        end

        function everyFrameRequiresSynchronizedRadar(testCase)
            runtime = localRuntime(1);
            frame = rmfield(localCruiseFrame(0.0), ...
                "radarRelativePosition");

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, frame), ...
                "onlineNrmmTrackingRuntime:missingSynchronizedRadar");
        end

        function everyFrameRequiresGnssVelocity(testCase)
            runtime = localRuntime(1);
            frame = rmfield(localCruiseFrame(0.0), "vyGps");

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, frame), ...
                "onlineNrmmTrackingRuntime:missingSynchronizedSignal");
        end

        function radarRowsMustMatchDetectionAvailability(testCase)
            availableWithNaN = localCruiseFrame(0.0);
            availableWithNaN.radarRelativePosition = [NaN, NaN];
            unavailableWithFinite = localCruiseFrame(0.0);
            unavailableWithFinite.radarDetectionAvailable = false;

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", localRuntime(1), availableWithNaN), ...
                "onlineNrmmTrackingRuntime:invalidSynchronizedRadar");
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", localRuntime(1), unavailableWithFinite), ...
                "onlineNrmmTrackingRuntime:invalidSynchronizedRadar");
        end

        function multiTargetFrameRequiresKnownUniqueIdentifiers(testCase)
            runtime = localRuntime(2);
            radar = [100.0, 2.0; 80.0, -2.0];
            missingIdentifiersFrame = localFrame(0.0, [0.0; 0.0], radar);
            duplicateIdentifiersFrame = localFrame( ...
                0.0, [0.0; 0.0], radar, ["same"; "same"]);
            unknownIdentifierFrame = localFrame(0.0, [0.0; 0.0], radar, ...
                ["test-target-1"; "not-initialized"]);

            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, missingIdentifiersFrame), ...
                "onlineNrmmTrackingRuntime:missingRadarTargetIdentifiers");
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, duplicateIdentifiersFrame), ...
                "onlineNrmmTrackingRuntime:invalidRadarTargetIdentifiers");
            testCase.verifyError(@() onlineNrmmTrackingRuntime( ...
                "step", runtime, unknownIdentifierFrame), ...
                "onlineNrmmTrackingRuntime:unknownRadarTargetIdentifier");
        end

        function radarIdentifiersMakeRowOrderIrrelevant(testCase)
            radar = [100.0, 2.0; 80.0, -2.0];
            identifiers = ["test-target-1"; "test-target-2"];

            [~, canonicalOutput] = onlineNrmmTrackingRuntime( ...
                "step", localRuntime(2), ...
                localFrame(0.0, [0.0; 0.0], radar, identifiers));
            [~, permutedOutput] = onlineNrmmTrackingRuntime( ...
                "step", localRuntime(2), ...
                localFrame(0.0, [0.0; 0.0], ...
                    radar([2, 1], :), identifiers([2, 1])));

            testCase.verifyEqual(permutedOutput.targetStates, ...
                canonicalOutput.targetStates, AbsTol=1.0e-13);
            testCase.verifyEqual( ...
                string({canonicalOutput.targetEstimates.trackId}).', ...
                identifiers);

            slotOptions = rmfield(localOptions(1), "targetIdentifiers");
            cfg = nrmmTrackingConfig();
            slotRuntime = onlineNrmmTrackingRuntime("initialize", ...
                cfg, slotOptions, nrmmWindowEstimatorDesign(cfg));
            [~, slotOutput] = onlineNrmmTrackingRuntime( ...
                "step", slotRuntime, localCruiseFrame(0.0));

            testCase.verifyFalse( ...
                isfield(slotOutput.targetEstimates, "trackId"));
            testCase.verifyEqual( ...
                slotOutput.targetEstimates(1).temporarySlotIdentifier, ...
                "target-slot-1");
        end

        function planningInputsConsumeSynchronizedEstimatorOutput(testCase)
            runtime = localRuntime(1);
            samplePeriod = runtime.samplePeriod;
            frameTime = 0.0;
            output = struct();
            for frameIdx = 1:3
                frame = localCruiseFrame(frameTime);
                frame.yawRateMeasured = 0.05;
                [runtime, output] = onlineNrmmTrackingRuntime( ...
                    "step", runtime, frame);
                frameTime = frameTime+samplePeriod;
            end
            controllerCfg = collisionAvoidanceControllerConfig();
            controllerCfg.referenceSpeed = 10.0;
            [ego, ~, ~, targets] = readPlanningInputs( ...
                output, [], localControllerRoad(output.egoPositionInertial), ...
                controllerCfg);

            testCase.verifyEqual(ego.position, ...
                output.egoPositionInertial, AbsTol=1.0e-12);
            testCase.verifyEqual(ego.inertialVelocity, ...
                output.egoState([2, 5]), AbsTol=1.0e-12);
            testCase.verifyEqual(ego.modelState(6), ...
                output.egoYawRate, AbsTol=0.0);
            testCase.verifyEqual(output.egoYawRate, 0.05, AbsTol=0.0);
            testCase.verifyEqual(targets(1).position, ...
                output.targetEstimates(1).targetPositionInertial, ...
                AbsTol=1.0e-12);
        end

        function multipleTargetsUseOneSynchronizedFrame(testCase)
            runtime = localRuntime(2);
            radar = [100.0, 2.0; 80.0, -2.0];
            identifiers = ["test-target-1"; "test-target-2"];

            [~, output] = onlineNrmmTrackingRuntime("step", runtime, ...
                localFrame(0.0, [0.0; 0.0], radar, identifiers));

            testCase.verifySize(output.targetStates, [2, 6]);
            testCase.verifyGreaterThan(norm( ...
                output.targetStates(1, :)-output.targetStates(2, :)), ...
                1.0);
        end
    end
end

function runtime = localRuntime(targetCount)
    cfg = nrmmTrackingConfig();
    runtime = onlineNrmmTrackingRuntime( ...
        "initialize", cfg, localOptions(targetCount), ...
        nrmmWindowEstimatorDesign(cfg));
end

function options = localOptions(targetCount)
    targetState = zeros(6, targetCount);
    for targetIdx = 1:targetCount
        targetState(:, targetIdx) = [100.0-20.0*(targetIdx-1); ...
            2.0-4.0*(targetIdx-1); -12.0; 0.0; 0.0; 0.0];
    end
    options = struct( ...
        "initialTime", 0.0, ...
        "targetCount", targetCount, ...
        "egoInitialPosition", [0.0; 0.0], ...
        "egoInitialYaw", 0.0, ...
        "egoInitialBodyVelocity", [10.0; 0.0], ...
        "targetInitialState", targetState);
    options.targetIdentifiers = ...
        "test-target-" + string((1:targetCount).');
end

function frame = localFrame( ...
        time, gpsPosition, radarPosition, radarTargetIdentifiers)
    frame = struct( ...
        "time", time, ...
        "xGps", gpsPosition(1), ...
        "yGps", gpsPosition(2), ...
        "vxGps", 10.0, ...
        "vyGps", 0.0, ...
        "longitudinalAcceleration", 0.0, ...
        "lateralAcceleration", 0.0, ...
        "yawRateMeasured", 0.0, ...
        "radarRelativePosition", radarPosition);
    if nargin >= 4
        frame.radarTargetIdentifiers = radarTargetIdentifiers;
    end
end

function frame = localCruiseFrame(time)
% Frames consistent with the localOptions single-target equilibrium:
% the ego cruises at [10; 0] m/s with zero yaw while the oncoming
% target closes at 22 m/s along the same lane.
    frame = localFrame(time, [10.0*time; 0.0], [100.0-22.0*time, 2.0]);
end

function road = localControllerRoad(anchorPosition)
% Perceived road input for the estimator-to-planner parsing contract.

    centerline = [-100.0, 0.0; 200.0, 0.0];
    perception = fitPerceivedRoadBoundaries( ...
        centerline, [anchorPosition(:); 0.0], ...
        PerceptionRange=30.0, ...
        RightOffset=0.001, LeftOffset=8.0, ...
        ShoulderWidth=2.60, ...
        RouteBranchId="through");
    road = perception.roadGeometry;
    road.boundaries = struct([]);
end
