classdef shoulderTerminalControllerTest < matlab.unittest.TestCase
% shoulderTerminalControllerTest Independent terminal-controller behavior.

    methods (TestClassSetup)
        function addControllerPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "config")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "controller")));
        end
    end

    methods (Test)
        function movingStateCommandsBrakingWithoutMpc(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 10.0; 0.0; 0.0];

            result = shoulderTerminalController( ...
                state, zeros(6, 1), localStraightReference(), cfg);

            testCase.verifyEqual( ...
                result.controller, "shoulderTerminalController");
            testCase.verifyEqual( ...
                result.framework, ...
                "IndependentTerminalFrenetBandFeedback");
            testCase.verifyFalse(result.taskComplete);
            testCase.verifySize(result.actuatorInput, [2, 1]);
            % The commanded torque exactly inverts the smooth braking
            % split so the realized total force matches the commanded
            % deceleration.
            smoothingWidth = cfg.actuation.torqueSmoothingWidth;
            rearShare = ...
                (1.0 - cfg.actuation.frontBrakingTorqueRatio) ...
                / cfg.actuation.frontBrakingTorqueRatio;
            rearTorque = rearShare * result.frontAxleTorque ...
                / (1.0 + exp( ...
                    result.frontAxleTorque / smoothingWidth));
            realizedForce = ...
                (result.frontAxleTorque + rearTorque) ...
                / cfg.vehicle.wheelRadius;
            expectedForce = ...
                -cfg.terminalController.commandedDeceleration ...
                * cfg.vehicle.m;
            testCase.verifyEqual(realizedForce, expectedForce, ...
                RelTol=1.0e-6);
            testCase.verifyLessThanOrEqual( ...
                result.frontAxleTorque, 0.0);
            testCase.verifyEqual( ...
                result.desiredLongitudinalAcceleration, ...
                -cfg.terminalController.commandedDeceleration, ...
                AbsTol=1.0e-12);
        end

        function controllerRequiresNoMpcConfiguration(testCase)
            cfg = collisionAvoidanceControllerConfig();
            terminalCfg = struct( ...
                "controller", cfg.controller, ...
                "vehicle", cfg.vehicle, ...
                "model", cfg.model, ...
                "tire", cfg.tire, ...
                "terminalController", cfg.terminalController, ...
                "actuation", cfg.actuation);

            result = shoulderTerminalController( ...
                [0.0; 0.0; 0.0; 5.0; 0.0; 0.0], ...
                zeros(6, 1), localStraightReference(), terminalCfg);

            testCase.verifyFalse(result.taskComplete);
            testCase.verifySize(result.actuatorInput, [2, 1]);
            testCase.verifyLessThan(result.frontAxleTorque, 0.0);
        end

        function steeringPerformsFrenetBandKeeping(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 5.0; 0.2; 0.1];
            reference = struct( ...
                "curvature", 0.01, ...
                "lateralError", 0.5, ...
                "headingError", 0.1);

            result = shoulderTerminalController( ...
                state, zeros(6, 1), reference, cfg);

            yawRateError = ...
                state(6)-reference.curvature*state(4);
            expectedSteering = ...
                atan(cfg.vehicle.wheelbase*reference.curvature) ...
                - cfg.terminalController.lateralPositionGain ...
                    * reference.lateralError ...
                - cfg.terminalController.headingGain ...
                    * reference.headingError ...
                - cfg.terminalController.lateralVelocityGain ...
                    * state(5) ...
                - cfg.terminalController.yawRateGain*yawRateError;
            testCase.verifyEqual( ...
                result.frontWheelSteeringAngle, ...
                expectedSteering, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.actuatorInput(2), ...
                result.frontWheelSteeringAngle, AbsTol=0.0);
        end

        function stoppedStateReturnsNoControl(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 0.0; 0.0; 0.0];

            result = shoulderTerminalController( ...
                state, zeros(6, 1), localStraightReference(), cfg);

            testCase.verifyTrue(result.taskComplete);
            testCase.verifyEmpty(result.actuatorInput);
            testCase.verifyEmpty(result.frontAxleTorque);
            testCase.verifyEmpty(result.frontWheelSteeringAngle);
            testCase.verifyEqual( ...
                result.desiredLongitudinalAcceleration, ...
                0.0, AbsTol=0.0);
        end

        function speedErrorBoundPreventsPrematureCompletion(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 0.0; 0.0; 0.0];
            errorBound = [0.0; 0.0; 0.0; 0.02; 0.0; 0.0];

            result = shoulderTerminalController( ...
                state, errorBound, localStraightReference(), cfg);

            testCase.verifyFalse(result.taskComplete);
            testCase.verifySize(result.actuatorInput, [2, 1]);
            testCase.verifyLessThan(result.frontAxleTorque, 0.0);
            testCase.verifyEqual( ...
                result.longitudinalSpeedUpperBound, ...
                0.02, AbsTol=0.0);
        end

        function residualLateralMotionPreventsCompletion(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 0.0; 0.03; 0.0];

            result = shoulderTerminalController( ...
                state, zeros(6, 1), localStraightReference(), cfg);

            testCase.verifyFalse(result.taskComplete);
            testCase.verifySize(result.actuatorInput, [2, 1]);
            testCase.verifyGreaterThan( ...
                result.lateralSpeedUpperBound, ...
                result.stoppedLateralSpeedTolerance);
        end

        function residualYawMotionPreventsCompletion(testCase)
            cfg = collisionAvoidanceControllerConfig();
            state = [0.0; 0.0; 0.0; 0.0; 0.0; 0.02];

            result = shoulderTerminalController( ...
                state, zeros(6, 1), localStraightReference(), cfg);

            testCase.verifyFalse(result.taskComplete);
            testCase.verifySize(result.actuatorInput, [2, 1]);
            testCase.verifyGreaterThan( ...
                result.yawRateUpperBound, ...
                result.stoppedYawRateTolerance);
        end

        function largeStoppedSpeedToleranceIsRejected(testCase)
            cfg = collisionAvoidanceControllerConfig();
            cfg.terminalController.stoppedSpeedTolerance = 1.0;

            testCase.verifyError(@() shoulderTerminalController( ...
                zeros(6, 1), zeros(6, 1), ...
                localStraightReference(), cfg), ...
                "shoulderTerminalController:invalidConfiguration");
        end

        function largeStoppedLateralToleranceIsRejected(testCase)
            cfg = collisionAvoidanceControllerConfig();
            cfg.terminalController.stoppedLateralSpeedTolerance = 1.0;

            testCase.verifyError(@() shoulderTerminalController( ...
                zeros(6, 1), zeros(6, 1), ...
                localStraightReference(), cfg), ...
                "shoulderTerminalController:invalidConfiguration");
        end

        function largeStoppedYawToleranceIsRejected(testCase)
            cfg = collisionAvoidanceControllerConfig();
            cfg.terminalController.stoppedYawRateTolerance = 1.0;

            testCase.verifyError(@() shoulderTerminalController( ...
                zeros(6, 1), zeros(6, 1), ...
                localStraightReference(), cfg), ...
                "shoulderTerminalController:invalidConfiguration");
        end

        function declaredVehicleModelStopsMonotonically(testCase)
            cfg = collisionAvoidanceControllerConfig();

            [speed, frontAxleTorque, finalState, taskComplete] = ...
                localClosedLoopStop(cfg);

            testCase.verifyTrue(taskComplete);
            testCase.verifyLessThanOrEqual( ...
                max(diff(speed)), 1.0e-10);
            testCase.verifyLessThanOrEqual( ...
                speed(end), ...
                cfg.terminalController.stoppedSpeedTolerance);
            testCase.verifyLessThanOrEqual( ...
                max(frontAxleTorque), 0.0);
            testCase.verifyLessThan( ...
                min(frontAxleTorque), 0.0);
            testCase.verifyEqual( ...
                finalState(5:6), zeros(2, 1), ...
                AbsTol=1.0e-12);
        end
    end
end

function reference = localStraightReference()
    reference = struct( ...
        "curvature", 0.0, ...
        "lateralError", 0.0, ...
        "headingError", 0.0);
end

function [speed, frontAxleTorque, state, taskComplete] = ...
        localClosedLoopStop(cfg)
    maximumStepCount = 100;
    state = [0.0; 0.0; 0.0; 10.0; 0.0; 0.0];
    speed = nan(maximumStepCount+1, 1);
    frontAxleTorque = nan(maximumStepCount, 1);
    speed(1) = state(4);
    completedStep = 0;
    taskComplete = false;
    for stepIdx = 1:maximumStepCount
        terminalResult = shoulderTerminalController( ...
            state, zeros(6, 1), ...
            localStraightReference(), cfg);
        if terminalResult.taskComplete
            taskComplete = true;
            completedStep = stepIdx-1;
            break;
        end
        frontAxleTorque(stepIdx) = ...
            terminalResult.frontAxleTorque;
        state = localNonlinearBicycleStep( ...
            state, terminalResult.frontAxleTorque, ...
            terminalResult.frontWheelSteeringAngle, ...
            cfg.controller.sampleTime, cfg);
        speed(stepIdx+1) = state(4);
        completedStep = stepIdx;
    end
    speed = speed(1:completedStep+1);
    frontAxleTorque = frontAxleTorque(1:completedStep);
end

function stateNext = localNonlinearBicycleStep( ...
        state, frontAxleTorque, steeringAngle, sampleTime, cfg)
% Surrogate nonlinear-bicycle plant for the closed-loop tests.
%
% Deliberately NOT the controller's prediction model, so closing the
% loop through it exercises the controller against dynamics it does
% not itself hold: the kinematics keep the exact trigonometry, the
% slip angles use the true longitudinal speed instead of the frozen
% schedule speed, the bilinear terms are retained, and the combined
% force is clipped to the friction CIRCLE rather than to the inscribed
% polygon the controller constrains itself by. Sub-stepped for
% integration accuracy. The commanded axle torque enters through the
% same smooth one-sided braking split the command reports.

    mass = cfg.vehicle.m;
    yawInertia = cfg.vehicle.Iz;
    lf = cfg.vehicle.lf;
    lr = cfg.vehicle.lr;
    corneringFront = cfg.tire.corneringStiffness(1);
    corneringRear = cfg.tire.corneringStiffness(2);
    frictionLimit = min(cfg.tire.frictionCoefficient) ...
        * cfg.vehicle.gravity;
    rearShare = (1.0 - cfg.actuation.frontBrakingTorqueRatio) ...
        / cfg.actuation.frontBrakingTorqueRatio;
    smoothingWidth = cfg.actuation.torqueSmoothingWidth;
    rearAxleTorque = rearShare * frontAxleTorque ...
        / (1.0 + exp(frontAxleTorque / smoothingWidth));
    longitudinalForce = (frontAxleTorque + rearAxleTorque) ...
        / cfg.vehicle.wheelRadius;

    substepCount = 5;
    stepTime = sampleTime / substepCount;
    stateNext = state;
    for substepIdx = 1:substepCount
        speed = max(stateNext(4), 0.5);
        frontSlipAngle = steeringAngle ...
            - (stateNext(5) + lf * stateNext(6)) / speed;
        rearSlipAngle = -(stateNext(5) - lr * stateNext(6)) / speed;
        frontLateralForce = corneringFront * frontSlipAngle;
        rearLateralForce = corneringRear * rearSlipAngle;
        longitudinalAcceleration = longitudinalForce / mass;
        lateralAcceleration = ...
            (frontLateralForce + rearLateralForce) / mass;
        demand = hypot( ...
            longitudinalAcceleration, lateralAcceleration);
        if demand > frictionLimit
            scale = frictionLimit / demand;
            longitudinalAcceleration = ...
                longitudinalAcceleration * scale;
            frontLateralForce = frontLateralForce * scale;
            rearLateralForce = rearLateralForce * scale;
            lateralAcceleration = lateralAcceleration * scale;
        end
        derivative = [ ...
            stateNext(4) * cos(stateNext(3)) ...
                - stateNext(5) * sin(stateNext(3)); ...
            stateNext(4) * sin(stateNext(3)) ...
                + stateNext(5) * cos(stateNext(3)); ...
            stateNext(6); ...
            longitudinalAcceleration ...
                + stateNext(5) * stateNext(6); ...
            lateralAcceleration - stateNext(4) * stateNext(6); ...
            (lf * frontLateralForce - lr * rearLateralForce) ...
                / yawInertia];
        stateNext = stateNext + stepTime * derivative;
        stateNext(4) = max(stateNext(4), 0.0);
    end
end
