classdef straightCenterlineCruiseScenarioTest < matlab.unittest.TestCase
% straightCenterlineCruiseScenarioTest High-fidelity cruise behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function oneControlIntervalUsesAConsistentPlantContract(testCase)
            result = runStraightCenterlineCruiseScenario( ...
                Duration=0.1, ...
                Plot=false, Report=false);

            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.1, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 1);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 1);
            testCase.verifyEqual(result.controlState(1, 1:3), ...
                zeros(1, 3), AbsTol=0.0);
            testCase.verifyEqual(result.controlState(1, 4), ...
                result.scenario.referenceSpeed, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.plant.adapter.controllerCoordinateConvention, ...
                "xForwardYLeftZUp");
            testCase.verifyEqual( ...
                result.plant.adapter.plantCoordinateConvention, ...
                "saeXForwardYRightZDown");
            testCase.verifyEqual( ...
                result.plant.adapter.lateralStateSign, -1.0, ...
                AbsTol=0.0);
            testCase.verifyEqual( ...
                result.plant.adapter.steeringAngleSign, -1.0, ...
                AbsTol=0.0);
            testCase.verifyLessThanOrEqual( ...
                result.plant.initialization.maximumAbsoluteLongitudinalSlip, ...
                1.0e-3);
            testCase.verifyLessThanOrEqual( ...
                result.plant.initialization ...
                    .actualMaximumAbsoluteLongitudinalSlip, ...
                1.0e-3);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.m, ...
                result.plant.parameters.mass, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.Iz, ...
                result.plant.parameters.yawInertia, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.lf, ...
                result.plant.parameters.frontAxleDistance, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.lr, ...
                result.plant.parameters.rearAxleDistance, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.frontTrackWidth, ...
                result.plant.parameters.trackWidth, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.rearTrackWidth, ...
                result.plant.parameters.trackWidth, RelTol=1.0e-12);
            expectedCorneringStiffness = [ ...
                sum(result.plant.parameters.corneringStiffness(1:2)); ...
                sum(result.plant.parameters.corneringStiffness(3:4))];
            frontNormalLoad = ...
                sum(result.plant.parameters.staticNormalLoad(1:2));
            rearNormalLoad = ...
                sum(result.plant.parameters.staticNormalLoad(3:4));
            expectedFrictionCoefficient = [ ...
                dot(result.plant.parameters.frictionCoefficient(1:2), ...
                    result.plant.parameters.staticNormalLoad(1:2)) ...
                    / frontNormalLoad; ...
                dot(result.plant.parameters.frictionCoefficient(3:4), ...
                    result.plant.parameters.staticNormalLoad(3:4)) ...
                    / rearNormalLoad];
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.corneringStiffness, ...
                expectedCorneringStiffness, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.frictionCoefficient, ...
                expectedFrictionCoefficient, ...
                RelTol=1.0e-12);
            testCase.verifyFalse(result.failure.occurred);
            testCase.verifyTrue( ...
                result.metrics.controllerCompletedScenario);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteSpeedError, ...
                result.criteria.maximumAbsoluteSpeedError);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteLateralPosition, ...
                result.criteria.maximumAbsoluteLateralPosition);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteHeadingError, ...
                result.criteria.maximumAbsoluteHeadingError);
            testCase.verifyTrue(result.metrics.speedWithinTolerance);
            testCase.verifyTrue(result.metrics.lateralWithinTolerance);
            testCase.verifyTrue(result.metrics.headingWithinTolerance);
            testCase.verifyFalse(isfield(result, "diagnostics"));
        end
    end
end
