classdef straightCenterlineCruiseScenarioTest < matlab.unittest.TestCase
% straightCenterlineCruiseScenarioTest High-fidelity cruise behavior.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "scripts")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(repositoryRoot, "config")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function anUncertifiedFullHorizonStopsBeforeThePhysicalPlant(testCase)
            configuration = finiteSensingValidationConfig();
            result = runStraightCenterlineCruiseScenario( ...
                Duration=0.1, ...
                PerceptionRange=50.0, RoadBoundaryOffsets=[6.0; 6.0], ...
                ControllerConfiguration=configuration, ...
                Plot=false, Report=false);
            testCase.assertTrue(result.failure.occurred);
            testCase.verifyEqual(result.failure.identifier,"collisionAvoidanceController:noCertifiedContinuation");

            testCase.verifyEqual(result.scenario.targetCount, 0);
            testCase.verifyEqual(result.scenario.sampleTime, ...
                0.05, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.metrics.requestedControlSteps, 2);
            testCase.verifyEqual( ...
                result.metrics.completedControlSteps, 0);
            testCase.verifyEqual(result.controlState(1, 1:3), ...
                zeros(1, 3), AbsTol=0.0);
            testCase.verifyEqual(result.controlState(1, 4), ...
                result.scenario.referenceSpeed, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.plant.adapter.controllerCoordinateConvention, ...
                "xForwardYLeftZUp");
            testCase.verifyEqual( ...
                result.plant.adapter.plantCoordinateConvention, ...
                "saeXForwardYRightZDown");
            testCase.verifyEqual( ...
                result.plant.adapter.lateralStateSign, -1.0, ...
                AbsTol=0.0);
            testCase.verifyEqual( ...
                result.plant.adapter.steeringAngleSign, -1.0, ...
                AbsTol=0.0);
            testCase.verifyLessThanOrEqual( ...
                result.plant.initialization.maximumAbsoluteLongitudinalSlip, ...
                1.0e-3);
            testCase.verifyTrue(isnan(result.plant.initialization.actualMaximumAbsoluteLongitudinalSlip));
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.m, ...
                result.plant.parameters.mass, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.Iz, ...
                result.plant.parameters.yawInertia, RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.lf, ...
                result.plant.parameters.frontAxleDistance, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.lr, ...
                result.plant.parameters.rearAxleDistance, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.vehicle.centerOfGravityHeight, ...
                result.plant.parameters.cgHeight, RelTol=1.0e-12);
            expectedCorneringStiffness = [ ...
                sum(result.plant.parameters.corneringStiffness(1:2)); ...
                sum(result.plant.parameters.corneringStiffness(3:4))];
            frontNormalLoad = ...
                sum(result.plant.parameters.staticNormalLoad(1:2));
            rearNormalLoad = ...
                sum(result.plant.parameters.staticNormalLoad(3:4));
            expectedFrictionCoefficient = [ ...
                dot(result.plant.parameters.frictionCoefficient(1:2), ...
                    result.plant.parameters.staticNormalLoad(1:2)) ...
                    / frontNormalLoad; ...
                dot(result.plant.parameters.frictionCoefficient(3:4), ...
                    result.plant.parameters.staticNormalLoad(3:4)) ...
                    / rearNormalLoad];
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.corneringStiffness, ...
                expectedCorneringStiffness, ...
                RelTol=1.0e-12);
            testCase.verifyEqual( ...
                result.controllerConfiguration.tire.frictionCoefficient, ...
                expectedFrictionCoefficient, ...
                RelTol=1.0e-12);
            testCase.verifyEqual(result.controllerConfiguration.roadLoad.dragCoefficient, ...
                result.plant.parameters.dragCoefficient, AbsTol=0.0);
            testCase.verifyGreaterThan(result.controllerConfiguration.roadLoad.rollingCoefficient, 0.0);
            testCase.verifyEqual(result.plant.parameters.rollingCoefficients, ...
                [0.01; 0; 0.0004; 0.00004; 0; 0; 0.85; -0.4], AbsTol=1.0e-12);
            testCase.verifyNotEqual(result.plant.parameters.rollingCoefficients, ...
                result.plant.parameters.rollingInactiveMaskCoefficients);
            testCase.verifySize(result.plantTrace.wheelLongitudinalForce, ...
                [numel(result.plantTrace.time), 4]);
            testCase.verifySize(result.plantTrace.wheelRollingMoment, ...
                [numel(result.plantTrace.time), 4]);
            testCase.verifyEmpty(result.plantTrace.wheelRollingMoment);
            testCase.verifyFalse( ...
                result.metrics.controllerCompletedScenario);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteSpeedError, ...
                result.criteria.maximumAbsoluteSpeedError);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteLateralPosition, ...
                result.criteria.maximumAbsoluteLateralPosition);
            testCase.verifyLessThanOrEqual( ...
                result.metrics.maximumAbsoluteHeadingError, ...
                result.criteria.maximumAbsoluteHeadingError);
            testCase.verifyTrue(result.metrics.speedWithinTolerance);
            testCase.verifyTrue(result.metrics.lateralWithinTolerance);
            testCase.verifyTrue(result.metrics.headingWithinTolerance);
        end

        function failedFirstAcquisitionRemainsInTheAttemptLog(testCase)
            target = struct("targetPositionInertial", [0.0; 0.0], ...
                "targetVelocityInertial", [0.0; 0.0], ...
                "targetYawInertial", 0.0, "targetYawRate", 0.0);
            result = runStraightCenterlineCruiseScenario( ...
                Duration=0.05, PerceptionRange=50.0, ...
                TargetStateFunction=@(time, ego) target, ...
                ControllerConfiguration=struct( ...
                    "controller", struct("horizonSteps", 24)), ...
                Plot=false, Report=false);
            testCase.verifyTrue(result.failure.occurred);
            testCase.verifyEqual(result.metrics.completedControlSteps, 0);
            testCase.verifyEqual(result.attempts.time, 0.0, AbsTol=0.0);
            testCase.verifyTrue(result.attempts.targetVisible);
            testCase.verifySize(result.attempts.metadata, [1, 1]);
            testCase.verifyEmpty(result.attempts.metadata{1});
            testCase.verifyFalse(result.metrics.controllerCompletedScenario);
        end
    end
end
