classdef temporalGroundPointsProcessingTest < matlab.unittest.TestCase
% temporalGroundPointsProcessingTest Temporal curb-detector integration.

    methods (TestClassSetup)
        function addPerceptionPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (Test)
        function initializationWithoutCurbDetectionFailsFast(testCase)
            frame = localSparseFrame();
            testCase.verifyError( ...
                @() temporalGroundPointsProcessing( ...
                    frame, zeros(1, 8), 0.1, [], struct()), ...
                "temporalGroundPointsProcessing:" + ...
                "InitializationDetectionFailed");
        end

        function propagatesRoadHeadingByMeasuredEgoYaw(testCase)
            frame = localSparseFrame();
            state = localTrackerState();
            state.leftModel.curvature = 0.0;
            state.rightModel.curvature = 0.0;
            currentEgoState = zeros(1, 8);
            currentEgoState(7) = deg2rad(10);

            [result, ~, diagnostics] = ...
                temporalGroundPointsProcessing( ...
                    frame, currentEgoState, 0.1, state, struct());

            testCase.verifyTrue( ...
                diagnostics.roadHeadingPriorApplied);
            testCase.verifyEqual( ...
                diagnostics.roadHeadingPriorDegrees, -10, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.curbModels.roadFrame.headingDegrees, -10, ...
                AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.curbModels.roadFrame.source, "prior-fallback");
        end

        function explicitRoadHeadingOverridesTemporalPrior(testCase)
            frame = localSparseFrame();
            state = localTrackerState();
            cfg = struct("curbRoadHeadingDegrees", 15);
            egoState = zeros(1, 8);
            egoState(7) = deg2rad(10);

            [result, ~, diagnostics] = ...
                temporalGroundPointsProcessing( ...
                    frame, egoState, 0.1, state, cfg);

            testCase.verifyFalse( ...
                diagnostics.roadHeadingPriorApplied);
            testCase.verifyTrue(isnan( ...
                diagnostics.roadHeadingPriorDegrees));
            testCase.verifyEqual( ...
                result.curbModels.roadFrame.headingDegrees, 15, ...
                AbsTol=1.0e-12);
        end

        function quadraticTangentCorrectsTranslationPrediction(testCase)
            frame = localSparseFrame();
            state = localTrackerState();
            egoState = zeros(1, 8);
            egoState(1) = 1;

            [result, ~, diagnostics] = ...
                temporalGroundPointsProcessing( ...
                    frame, egoState, 0.1, state, struct());

            expectedHeadingDegrees = rad2deg(atan(0.2));
            testCase.verifyTrue( ...
                diagnostics.roadHeadingPriorApplied);
            testCase.verifyEqual( ...
                diagnostics.roadHeadingPriorDegrees, ...
                expectedHeadingDegrees, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.curbModels.roadFrame.headingDegrees, ...
                expectedHeadingDegrees, AbsTol=1.0e-12);
        end
    end
end

function state = localTrackerState()
    model = struct( ...
        "found", true, ...
        "curvature", 0.1, ...
        "slope", 0.0, ...
        "intercept", -8.0, ...
        "minimumX", -20.0, ...
        "maximumX", 20.0, ...
        "minimumZ", -3.0, ...
        "maximumZ", -2.0, ...
        "azimuthSupport", 20, ...
        "longitudinalSpan", 40.0, ...
        "score", 100.0, ...
        "selectedOuterCandidate", false);
    rightModel = model;
    rightModel.intercept = 8.0;
    state = struct( ...
        "initialized", true, ...
        "previousEgoState", zeros(1, 8), ...
        "roadHeadingDegrees", 0.0, ...
        "leftModel", model, ...
        "rightModel", rightModel, ...
        "leftAge", 0, ...
        "rightAge", 0, ...
        "corridorWidthM", 16.0, ...
        "frameCount", 1);
end

function frame = localSparseFrame()
    x = [5, 6; 5, 6];
    y = [-2, 2; -2, 2];
    z = -2 * ones(2);
    frame = struct( ...
        "x", x, ...
        "y", y, ...
        "z", z, ...
        "range", hypot(x, y), ...
        "valid", true(2));
end
