classdef trackCurbQuadraticModelsTest < matlab.unittest.TestCase
% trackCurbQuadraticModelsTest Amplitude-limiting Kalman curb tracking.
%   The tracker follows Wang et al. (2019, Sec. VII): three constant-x
%   points per side are propagated by the measured ego motion and
%   corrected by the current detection, which must first pass the
%   amplitude-limiting filter on its coefficient increments.

    methods (TestClassSetup)
        function addPerceptionPath(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(fullfile( ...
                    repositoryRoot, ...
                    "perception", ...
                    "curbDetectionExperiment")));
        end
    end

    methods (Test)
        function propagatesCurveUsingInertialEgoCoordinates(testCase)
            leftModel = localModel(-0.004, 0.02, -6.0);
            rightModel = localModel(-0.004, 0.02, 5.0);
            detectedModels = localDetectedModels( ...
                leftModel, rightModel);
            initialEgoState = zeros(1, 8);

            [~, state] = trackCurbQuadraticModels( ...
                detectedModels, initialEgoState, 0.1, [], struct());

            currentEgoState = [1.0, 10.0, 0.0, 0.2, 2.0, 0.0, 0.0, 0.0];
            emptyDetections = localDetectedModels( ...
                localEmptyModel(), localEmptyModel());
            [trackedModels, ~, diagnostics] = ...
                trackCurbQuadraticModels( ...
                    emptyDetections, currentEgoState, 0.1, ...
                    state, struct());
            trackedLeft = localCombinedModel(trackedModels, "left");

            expectedCoefficients = [ ...
                -0.004, ...
                2.0 * -0.004 * 1.0 + 0.02, ...
                -0.004 * 1.0^2 + 0.02 * 1.0 - 6.0 - 0.2];
            testCase.verifyEqual( ...
                [ ...
                    trackedLeft.curvature, ...
                    trackedLeft.slope, ...
                    trackedLeft.intercept], ...
                expectedCoefficients, AbsTol=2.0e-3);
            testCase.verifyTrue(diagnostics.left.usedPrediction);
            testCase.verifyEqual( ...
                diagnostics.left.updateMode, "prediction");
        end

        function doesNotRotateInertialVelocityByEgoHeading(testCase)
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            initialEgoState = [ ...
                0.0, 10.0, 0.0, ...
                0.0, 0.0, 0.0, ...
                pi / 2.0, 0.0];
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, initialEgoState, 0.1, [], struct());
            currentEgoState = [ ...
                1.0, 10.0, 0.0, ...
                0.0, 0.0, 0.0, ...
                pi / 2.0, 0.0];
            emptyDetections = localDetectedModels( ...
                localEmptyModel(), localEmptyModel());

            [trackedModels, ~, diagnostics] = ...
                trackCurbQuadraticModels( ...
                    emptyDetections, currentEgoState, 0.1, ...
                    state, struct());

            testCase.verifyFalse(diagnostics.reset);
            testCase.verifyEqual( ...
                diagnostics.positionResidualM, 0.0, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                trackedModels.left.intercept, -5.0, AbsTol=2.0e-3);
            testCase.verifyTrue(diagnostics.left.usedPrediction);
        end

        function amplitudeFilterRejectsOneFrameCoefficientJump(testCase)
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            jumpedModels = localDetectedModels( ...
                localModel(0.0, 0.0, -3.0), ...
                localModel(0.0, 0.0, 5.0));

            [trackedModels, ~, diagnostics] = ...
                trackCurbQuadraticModels( ...
                    jumpedModels, zeros(1, 8), 0.1, ...
                    state, struct());

            testCase.verifyEqual( ...
                trackedModels.left.intercept, -6.0, AbsTol=1.0e-10);
            testCase.verifyFalse(diagnostics.left.amplitudeAccepted);
            testCase.verifyTrue(diagnostics.left.usedPrediction);
            testCase.verifyGreaterThan( ...
                diagnostics.left.coefficientDeltas(3), 0.8);
            testCase.verifyTrue(diagnostics.right.amplitudeAccepted);
            testCase.verifyFalse(diagnostics.right.usedPrediction);
        end

        function persistentCoefficientJumpIsAdoptedAtTheSecondFrame( ...
                testCase)
            % The amplitude-limiting filter compares consecutive detected
            % coefficient sets, so a detection that keeps reporting the
            % new geometry passes the gate one frame later.
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            jumpedModels = localDetectedModels( ...
                localModel(0.0, 0.0, -3.0), ...
                localModel(0.0, 0.0, 5.0));

            [~, state, firstDiagnostics] = trackCurbQuadraticModels( ...
                jumpedModels, zeros(1, 8), 0.1, state, struct());
            [~, ~, secondDiagnostics] = trackCurbQuadraticModels( ...
                jumpedModels, zeros(1, 8), 0.1, state, struct());

            testCase.verifyFalse(firstDiagnostics.left.amplitudeAccepted);
            testCase.verifyTrue(secondDiagnostics.left.amplitudeAccepted);
            testCase.verifyEqual( ...
                secondDiagnostics.left.updateMode, "measurement-update");
        end

        function blendsAConsistentMeasurement(testCase)
            initialModels = localDetectedModels( ...
                localModel(-0.003, 0.01, -6.0), ...
                localModel(-0.003, 0.01, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            updatedModels = localDetectedModels( ...
                localModel(-0.004, 0.02, -6.2), ...
                localModel(-0.004, 0.02, 4.8));

            [trackedModels, ~, diagnostics] = ...
                trackCurbQuadraticModels( ...
                    updatedModels, zeros(1, 8), 0.1, ...
                    state, struct());
            trackedLeft = localCombinedModel(trackedModels, "left");

            % The filter corrects towards the measurement without reaching
            % it, so the estimate lies strictly between the two.
            testCase.verifyGreaterThan(trackedLeft.intercept, -6.2);
            testCase.verifyLessThan(trackedLeft.intercept, -6.0);
            testCase.verifyGreaterThan(trackedLeft.curvature, -0.004);
            testCase.verifyLessThan(trackedLeft.curvature, -0.003);
            testCase.verifyEqual( ...
                diagnostics.left.updateMode, "measurement-update");
            testCase.verifyFalse(diagnostics.left.usedPrediction);
        end

        function coastsAcrossAThreeSecondDetectionOutage(testCase)
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            emptyDetections = localDetectedModels( ...
                localEmptyModel(), localEmptyModel());

            for frameIndex = 1:30
                [trackedModels, state, diagnostics] = ...
                    trackCurbQuadraticModels( ...
                        emptyDetections, zeros(1, 8), 0.1, ...
                        state, struct());
            end

            testCase.verifyTrue(trackedModels.left.found);
            testCase.verifyTrue(trackedModels.right.found);
            testCase.verifyEqual(diagnostics.left.age, 30);
            testCase.verifyEqual(diagnostics.right.age, 30);
            testCase.verifyEqual( ...
                diagnostics.left.updateMode, "prediction");
        end

        function expiresAfterTheCoastingBudgetAndReports(testCase)
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            emptyDetections = localDetectedModels( ...
                localEmptyModel(), localEmptyModel());

            for frameIndex = 1:31
                [trackedModels, state, diagnostics] = ...
                    trackCurbQuadraticModels( ...
                        emptyDetections, zeros(1, 8), 0.1, ...
                        state, struct());
            end

            testCase.verifyFalse(trackedModels.left.found);
            testCase.verifyFalse(trackedModels.leftForward.found);
            testCase.verifyEqual( ...
                diagnostics.left.updateMode, "expired");
        end

        function resetsAfterAnInertialPoseDiscontinuity(testCase)
            initialModels = localDetectedModels( ...
                localModel(0.0, 0.0, -6.0), ...
                localModel(0.0, 0.0, 5.0));
            [~, state] = trackCurbQuadraticModels( ...
                initialModels, zeros(1, 8), 0.1, [], struct());
            replacementModels = localDetectedModels( ...
                localModel(0.0, 0.0, -7.0), ...
                localModel(0.0, 0.0, 6.0));
            discontinuousEgoState = [ ...
                100.0, 0.0, 0.0, ...
                -50.0, 0.0, 0.0, ...
                0.0, 0.0];

            [trackedModels, ~, diagnostics] = ...
                trackCurbQuadraticModels( ...
                    replacementModels, discontinuousEgoState, ...
                    0.1, state, struct());

            testCase.verifyTrue(diagnostics.reset);
            testCase.verifyEqual( ...
                diagnostics.resetReason, "position-discontinuity");
            testCase.verifyEqual( ...
                trackedModels.left.intercept, -7.0, AbsTol=1.0e-10);
            testCase.verifyEqual( ...
                diagnostics.left.updateMode, "initialized");
        end
    end
end

function models = localDetectedModels(leftModel, rightModel)
    [leftLine, leftForward] = localSplitModel(leftModel);
    [rightLine, rightForward] = localSplitModel(rightModel);
    models = struct( ...
        "left", leftLine, ...
        "right", rightLine, ...
        "leftForward", leftForward, ...
        "rightForward", rightForward, ...
        "roadFrame", struct( ...
            "found", true, ...
            "headingDegrees", 0.0, ...
            "source", "test", ...
            "roadWidth", NaN, ...
            "leftSupport", 0, ...
            "rightSupport", 0, ...
            "pairScore", -inf, ...
            "scoreMargin", NaN));
end

function [lineModel, forwardModel] = localSplitModel(model)
    lineModel = localEmptyModel();
    forwardModel = localEmptyModel();
    if ~model.found
        return;
    end
    if abs(model.curvature) <= 1.0e-10
        lineModel = model;
    else
        lineModel = model;
        lineModel.curvature = 0.0;
        forwardModel = model;
    end
end

function model = localCombinedModel(models, sideName)
    lineField = char(sideName);
    forwardField = [lineField, 'Forward'];
    if models.(forwardField).found
        model = models.(forwardField);
    else
        model = models.(lineField);
    end
end

function model = localModel(curvature, slope, intercept)
    model = struct( ...
        "found", true, ...
        "curvature", curvature, ...
        "slope", slope, ...
        "intercept", intercept, ...
        "minimumX", -15.0, ...
        "maximumX", 15.0, ...
        "minimumZ", -2.7, ...
        "maximumZ", -2.5, ...
        "azimuthSupport", 80, ...
        "longitudinalSpan", 30.0, ...
        "score", 120.0, ...
        "selectedOuterCandidate", false);
end

function model = localEmptyModel()
    model = struct( ...
        "found", false, ...
        "curvature", 0.0, ...
        "slope", NaN, ...
        "intercept", NaN, ...
        "minimumX", NaN, ...
        "maximumX", NaN, ...
        "minimumZ", NaN, ...
        "maximumZ", NaN, ...
        "azimuthSupport", 0, ...
        "longitudinalSpan", 0.0, ...
        "score", -inf, ...
        "selectedOuterCandidate", false);
end
