classdef varyingCurvatureShoulderGeometryTest ...
        < matlab.unittest.TestCase
% varyingCurvatureShoulderGeometryTest S-curve shoulder construction.

    methods (TestClassSetup)
        function addRepositoryPaths(testCase)
            repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                    fullfile(repositoryRoot, "scripts")));
            testCase.assumeFalse(isempty(which("PassVeh14DOF.sltx")), ...
                "Vehicle Dynamics Blockset PassVeh14DOF is unavailable.");
        end
    end

    methods (Test)
        function sCurveUsesVehicleWidthShoulders(testCase)
            result = ...
                runVaryingCurvatureStraightTargetAvoidanceScenario( ...
                    Duration=0.1, Plot=false, Report=false);

            testCase.verifyFalse(result.failure.occurred, ...
                result.failure.message);
            testCase.verifyEqual( ...
                result.scenario.geometry.roadShoulderWidth, ...
                2.6, AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadBoundaryOffsets, ...
                [6.0; 8.0], AbsTol=0.0);
            testCase.verifyEqual( ...
                result.perception.roadOuterBoundaryOffsets, ...
                [8.6; 10.6], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.roadTotalWidthIncludingShoulders, ...
                19.2, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.shoulderWidthToVehicleWidthRatio, ...
                1.3, AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.right, ...
                [-8.6, -6.0], AbsTol=1.0e-12);
            testCase.verifyEqual( ...
                result.perception.terminalLateralOffsetBands.left, ...
                [8.0, 10.6], AbsTol=1.0e-12);
            testCase.verifyTrue(result.roadSafety.noBoundaryCrossing);
        end
    end
end
