cd('/home/zai/Downloads/ResearchProjects/collisionAvoidance');
files={'tests/twoStagePredictiveControlTest.m','tests/clfNominalRecoveryTest.m', ...
    'tests/nonlinearPredictiveSafetyTest.m','tests/terminalContinuationTest.m', ...
    'tests/freePoseTerminalTest.m','tests/collisionAvoidanceControllerConfigTest.m', ...
    'tests/controllerSourceBudgetTest.m','tests/movingTargetFlowTest.m','tests/controllerKernelTest.m'};
results=runtests(files);disp(table(results));
save('/home/zai/.cache/collisionAvoidance/unbounded-steering-20261001/test-results.mat','results');
summary=struct('total',numel(results),'passed',nnz([results.Passed]),'failed',nnz([results.Failed]), ...
    'incomplete',nnz([results.Incomplete]),'names',{string({results.Name})},'durations',[results.Duration]);
f=fopen('/home/zai/.cache/collisionAvoidance/unbounded-steering-20261001/test-results.json','w');fprintf(f,'%s\n',jsonencode(summary));fclose(f);assertSuccess(results);
