function design = nrmmWindowEstimatorDesign(cfg)
% nrmmWindowEstimatorDesign Validate bounds and derive finite-window constants.
% No observer gains, Riccati equation, or nonlinear stability LMI is needed.

    target = cfg.target.domain;
    ego = cfg.ego.domain;
    positive = [cfg.runtime.samplePeriod, cfg.window.duration, ...
        cfg.window.minimumFitSpan, cfg.window.maximumIterations, ...
        cfg.window.numericalAllowance, target.speedMinimum, ...
        target.speedMaximum-target.speedMinimum, target.rearAxleDistance, ...
        target.relativePositionMaximum, ego.speedMinimum, ...
        ego.speedMaximum-ego.speedMinimum, cfg.ego.yaw.rearAxleDistance];
    nonnegative = [target.scalarAccelerationMaximum, ...
        target.sideslipMaximum, ego.yawRateMaximum, ...
        cfg.ego.yaw.sideslipDomainMaximum, ...
        cfg.ego.yaw.singleTrackYawRateMismatchMaximum, ...
        cfg.measurement.gps.positionNoiseMaximum, ...
        cfg.measurement.gps.velocityNoiseMaximum, ...
        cfg.measurement.imu.noiseMaximum, ...
        cfg.measurement.gyroscope.noiseMaximum, ...
        cfg.measurement.radar.noiseMaximum, ...
        cfg.target.model.scalarAccelerationRateMaximum, ...
        cfg.target.model.curvatureRateMaximum];
    intersample = [cfg.ego.intersample.accelerationMaximum, ...
        cfg.ego.intersample.yawAccelerationMaximum];
    if any(~isfinite(positive) | positive <= 0) ...
            || any(~isfinite(nonnegative) | nonnegative < 0) ...
            || any(isnan(intersample) | intersample < 0) ...
            || max(target.sideslipMaximum, ...
                cfg.ego.yaw.sideslipDomainMaximum) >= pi/2 ...
            || cfg.window.minimumFitSpan > cfg.window.duration ...
            || cfg.window.maximumIterations ~= fix(cfg.window.maximumIterations)
        error("nrmmWindowEstimatorDesign:invalidConfiguration", ...
            "Window, physical-domain, and sensor bounds are inconsistent.");
    end
    curvature = sin(target.sideslipMaximum)/target.rearAxleDistance;
    speed = target.speedMaximum;
    acceleration = target.scalarAccelerationMaximum;
    target.curvatureMaximum = curvature;
    target.yawRateMaximum = curvature*speed;
    target.accelerationNormBound = hypot(acceleration, curvature*speed^2);
    % sdot in a fixed frame = (Adot-kappa^2 V^3)e
    %                         +(3 A kappa V+kappadot V^2)Je.
    target.jerkNormBound = hypot( ...
        cfg.target.model.scalarAccelerationRateMaximum+curvature^2*speed^3, ...
        3*acceleration*curvature*speed ...
        +cfg.target.model.curvatureRateMaximum*speed^2);
    design = struct("method", "exact-flow-finite-window", ...
        "samplePeriod", cfg.runtime.samplePeriod, "configuration", cfg, ...
        "target", struct("domain", target), ...
        "yaw", struct("courseModel", cfg.ego.yaw), ...
        "sensors", struct( ...
            "velocityNoiseMaximum", cfg.measurement.gps.velocityNoiseMaximum, ...
            "gyroscopeNoiseMaximum", cfg.measurement.gyroscope.noiseMaximum));
end
