function certificate = nrmmTargetLipschitzCertificate(domain)
% nrmmTargetLipschitzCertificate Bound the unchanged saturated NRMM map.
%
% For all q1,q2,s1,s2 in R^2, the extension in
% nrmmTargetTrackerDerivative satisfies
%   |Phi_e(q1,s1)-Phi_e(q2,s2)| <= Lq*|q1-q2|+Ls*|s1-s2|.
% Bounds are analytic over all radial and scalar saturation regions, not a
% sampled Jacobian maximum. The acceleration Jacobian retains its 2-by-2
% directional structure. See OBSERVER_ISS_THEORY.md for the derivation.

    fields = ["speedMinimum","speedMaximum","accelerationNormBound", ...
        "scalarAccelerationMaximum","yawRateMaximum"];
    for field = fields
        validateattributes(domain.(field),{'double'}, ...
            {'scalar','real','finite','positive'},mfilename,field);
    end
    minimumSpeed = domain.speedMinimum;
    maximumSpeed = domain.speedMaximum;
    if maximumSpeed <= minimumSpeed
        error("nrmmTargetLipschitzCertificate:invalidSpeedInterval", ...
            "The target speed maximum must exceed its positive minimum.");
    end
    accelerationNorm = domain.accelerationNormBound;
    scalarAcceleration = domain.scalarAccelerationMaximum;
    yawRate = domain.yawRateMaximum;

    accelerationVelocity = accelerationNorm/minimumSpeed;
    yawVelocity = accelerationNorm ...
        *max(1/minimumSpeed^2,2/maximumSpeed^2);
    weightedYawVelocity = accelerationNorm ...
        *max(1/minimumSpeed,2/maximumSpeed);
    phiVelocity = yawRate^2+2*yawRate*weightedYawVelocity ...
        +3*scalarAcceleration*yawRate/minimumSpeed ...
        +3*yawRate*accelerationVelocity ...
        +3*scalarAcceleration*yawVelocity;
    accelerationJacobianEnvelope = [0,2*yawRate; ...
        3*yawRate,3*scalarAcceleration/minimumSpeed];
    phiAcceleration = norm(accelerationJacobianEnvelope,2);
    certificate = struct( ...
        "scalarAccelerationVelocity",accelerationVelocity, ...
        "scalarAccelerationAcceleration",1, ...
        "yawRateVelocity",yawVelocity, ...
        "yawRateAcceleration",1/minimumSpeed, ...
        "velocityWeightedYawRateVelocity",weightedYawVelocity, ...
        "accelerationJacobianEnvelope",accelerationJacobianEnvelope, ...
        "phiVelocity",phiVelocity, ...
        "phiAcceleration",phiAcceleration, ...
        "phi",hypot(phiVelocity,phiAcceleration), ...
        "scope","global analytic bounds for the unchanged saturation extension");
end
