function varargout = onlineNrmmTrackingRuntime(action, varargin)
% onlineNrmmTrackingRuntime Run the cascaded measured-input NRMM observer.
%
% Every frame contains one externally synchronized GNSS position, GNSS
% velocity, IMU body-acceleration, and gyroscope sample. A radar row is
% used only when its detection-availability flag is true; an unavailable
% row advances prediction without radar innovation.
%
% The observer is the cascade
%
%   1. Certified yaw measurement. The GNSS course pair subtracts the
%      online kinematic sideslip estimate asin(lrE*u3/||vm||) and adds its
%      pointwise certified error from GNSS velocity error, gyro error, and
%      declared single-track mismatch. Its arc centre yF drives
%      psiHatDot = u3 + kt*wrap(yF-psiHat) and its radius BF is the
%      certified measurement error. There is one yaw bandwidth and no
%      channel-reliability gain. The published yaw rate is measured u3.
%      An uninformative pair is a violated operating-domain assumption.
%   2. Body-velocity observer
%      vHatDot = am - u3*J*vHat + kv*(R(psiHat)'*vm - vHat). The measured
%      acceleration is used directly; no derivative of any measurement is
%      assumed zero. Inertial-sensor biases are neglected, so no stage
%      carries a bias state and no estimate feeds back into the yaw error.
%   3. Position observer pHatDot = R(psiHat)*vHat + kp*(pm - pHat).
%   4. High-gain target observer in the transformed NRMM coordinates
%      [rho; q; s]. Its normalized injection direction and physical
%      bandwidth are synthesized offline; the resulting three gains act
%      on the radar relative-position residual.
%
% The GNSS-position and radar innovations are formed against continuous
% output predictors rather than zero-order-held samples: at each frame the
% predictor is reset from the measurement and then integrated with its own
% output dynamics across the interval, so the innovation does
% not accumulate the known motion of the measured quantity between
% samples. This is the sampled-data realization of the continuous-time
% observer; a zero-order hold would inject the intersample motion into the
% wT^3-weighted acceleration channel. The low-gain GNSS-velocity and
% pseudo-heading innovations use the held samples directly.
%
% Neither the ego jerk nor any yaw-rate derivative appears in the observer
% equations. The target nonlinearity is evaluated through the globally
% Lipschitz saturation extension in nrmmTargetTrackerDerivative, so the
% runtime never rejects a sample for leaving the certified operating
% domain; domain exits are audited and reported, not gated on. All
% continuous stages are advanced by fixed-step RK4 substeps with the frame
% measurements held over the interval.
% The Lyapunov/Lipschitz theorem covers the continuous vector field. Holds,
% output-predictor resets, dropouts and RK4 are explicitly outside that
% exponential-stability theorem. A separate comparison recursion in
% nrmmPositionErrorBound encloses their effects at each accepted state time.
% targetEstimates(i).relativePositionErrorBound is the conditional Euclidean
% position radius in the ego body frame; invalid bounds publish Inf. The
% accompanying metadata states its time, assumptions and numerical scope.
% See scripts/NRMM_IMPLEMENTATION_NOTES.md Section 5 for the position enclosure
% and its floating-point and future-prediction limitations.

    action = lower(string(action));
    if ~isscalar(action)
        error("onlineNrmmTrackingRuntime:invalidAction", ...
            "action must be 'initialize', 'step', 'output', or 'resetTarget'.");
    end
    switch action
        case "initialize"
            varargout{1} = localInitialize(varargin{:});
        case "step"
            [varargout{1}, varargout{2}] = localStep(varargin{:});
        case "output"
            varargout{1} = localCurrentOutput(varargin{:});
        case "resettarget"
            varargout{1} = localResetTarget(varargin{:});
        otherwise
            error("onlineNrmmTrackingRuntime:invalidAction", ...
                "action must be 'initialize', 'step', 'output', or 'resetTarget'.");
    end
end

function runtime = localResetTarget(runtime,index,physicalState)
% localResetTarget Reinitialize one acquired track without changing ego states.
    validateattributes(index,{'double'},{'scalar','integer','positive', ...
        '<=',runtime.targetCount});
    validateattributes(physicalState,{'double'},{'vector','numel',6,'finite','real'});
    physicalState = physicalState(:);
    runtime.targetState(:,index) = physicalState;
    runtime.targetOutputPredictor(:,index) = physicalState(1:2);
    runtime.lastRadarTime(index) = NaN;
    runtime.positionErrorBound = nrmmPositionErrorBound("reset", ...
        runtime.positionErrorBound,index,localBoundState(localPackState(runtime),runtime.targetCount));
    audit = localOperatingDomainAudit(localPackState(runtime),runtime,"track-reset");
    runtime.lastIntervalDomainAudit = audit;
    runtime.estimatedDomainAudit = localMergeDomainAudits( ...
        runtime.estimatedDomainAudit,audit);
    runtime.lastIntervalTargetCertifiedSpeedDomainValid = audit.speedValid;
    runtime.targetCertifiedSpeedDomainValid = ...
        runtime.targetCertifiedSpeedDomainValid && audit.speedValid;
    runtime.minimumReconstructedTargetSpeed = min( ...
        runtime.minimumReconstructedTargetSpeed,audit.minimumTargetSpeed);
end

function runtime = localInitialize(cfg, options, observerDesign)
    localAddProjectPaths();
    if nargin < 1 || isempty(cfg)
        cfg = nrmmTrackingConfig();
    end
    if nargin < 2 || isempty(options)
        options = struct();
    end
    if nargin < 3 || isempty(observerDesign)
        observerDesign = synthesizeNrmmObserverGains(cfg);
    end

    samplePeriod = cfg.runtime.samplePeriod;
    integrationStepMaximum = cfg.runtime.integrationStepMaximum;
    validateattributes(samplePeriod, {'double'}, ...
        {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
        'cfg.runtime.samplePeriod');
    validateattributes(integrationStepMaximum, {'double'}, ...
        {'real', 'scalar', 'finite', 'positive'}, mfilename, ...
        'cfg.runtime.integrationStepMaximum');
    integrationSubstepCount = max( ...
        1, ceil(samplePeriod/integrationStepMaximum));
    integrationStep = samplePeriod/integrationSubstepCount;

    targetCount = localOptionPositiveInteger(options, "targetCount", 1);
    initialTime = localOptionFiniteScalar(options, "initialTime", 0.0);
    egoPosition = localRequiredOptionVector( ...
        options, "egoInitialPosition", 2);
    egoYaw = localWrapToPi(localRequiredOptionScalar( ...
        options, "egoInitialYaw"));
    egoBodyVelocity = localRequiredOptionVector( ...
        options, "egoInitialBodyVelocity", 2);
    targetState = localInitialTargets(options, targetCount);
    [targetIdentifiers, targetIdentifiersStable] = ...
        localTargetIdentifiers(options, targetCount);

    runtime = struct( ...
        "observerDesign", observerDesign, ...
        "samplePeriod", samplePeriod, ...
        "integrationStep", integrationStep, ...
        "integrationSubstepCount", integrationSubstepCount, ...
        "currentTime", initialTime, ...
        "yawEstimate", egoYaw, ...
        "bodyVelocityEstimate", egoBodyVelocity, ...
        "positionEstimate", egoPosition, ...
        "gnssPositionPredictor", egoPosition, ...
        "targetState", targetState, ...
        "targetOutputPredictor", targetState(1:2, :), ...
        "targetCount", targetCount, ...
        "targetIdentifiers", targetIdentifiers, ...
        "targetIdentifiersStable", targetIdentifiersStable, ...
        "lastInputSampleTime", NaN, ...
        "lastGnssTime", NaN, ...
        "lastImuTime", NaN, ...
        "lastGyroscopeTime", NaN, ...
        "lastRadarTime", NaN(targetCount, 1), ...
        "targetCertifiedSpeedDomainValid", true, ...
        "minimumReconstructedTargetSpeed", Inf, ...
        "lastIntervalTargetCertifiedSpeedDomainValid", true);
    initialAudit = localOperatingDomainAudit( ...
        localPackState(runtime), runtime, "initialization");
    runtime.estimatedDomainAudit = initialAudit;
    runtime.lastIntervalDomainAudit = initialAudit;
    runtime.targetCertifiedSpeedDomainValid = initialAudit.speedValid;
    runtime.minimumReconstructedTargetSpeed = initialAudit.minimumTargetSpeed;
    runtime.lastIntervalTargetCertifiedSpeedDomainValid = ...
        initialAudit.speedValid;
    prior = struct();
    if isfield(options,"initialErrorBounds")
        prior = options.initialErrorBounds;
    end
    runtime.positionErrorBound = nrmmPositionErrorBound("initialize", ...
        observerDesign,cfg,localBoundState(localPackState(runtime),targetCount),initialTime,prior);
end

function [runtime, output] = localStep(runtime, frame)
    observerInput = localSynchronizedInput(frame, runtime);
    tolerance = localTimeTolerance([observerInput.time; ...
        runtime.currentTime; runtime.samplePeriod]);
    if abs(observerInput.time-runtime.currentTime) > tolerance
        error("onlineNrmmTrackingRuntime:offSampleGrid", ...
            "The synchronized frame time must equal the observer time.");
    end

    runtime.gnssPositionPredictor = observerInput.gnssPosition;
    runtime.targetOutputPredictor( ...
        :, observerInput.radarDetectionAvailable) = ...
        observerInput.radarRelativePosition( ...
            observerInput.radarDetectionAvailable, :).';
    runtime.positionErrorBound = nrmmPositionErrorBound("measure", ...
        runtime.positionErrorBound,observerInput, ...
        localBoundState(localPackState(runtime),runtime.targetCount));
    [state, intervalAudit, runtime.positionErrorBound] = localRungeKuttaInterval( ...
        localPackState(runtime), observerInput, runtime);
    [runtime.yawEstimate, ...
        runtime.bodyVelocityEstimate, ...
        runtime.positionEstimate, runtime.gnssPositionPredictor, ...
        runtime.targetState, runtime.targetOutputPredictor] = ...
        localUnpackState(state, runtime.targetCount);
    runtime.yawEstimate = localWrapToPi(runtime.yawEstimate);
    runtime.targetCertifiedSpeedDomainValid = ...
        runtime.targetCertifiedSpeedDomainValid ...
        && intervalAudit.speedValid;
    runtime.minimumReconstructedTargetSpeed = min( ...
        runtime.minimumReconstructedTargetSpeed, ...
        intervalAudit.minimumTargetSpeed);
    runtime.lastIntervalTargetCertifiedSpeedDomainValid = ...
        intervalAudit.speedValid;
    runtime.estimatedDomainAudit = localMergeDomainAudits( ...
        runtime.estimatedDomainAudit, intervalAudit);
    runtime.lastIntervalDomainAudit = intervalAudit;
    runtime.currentTime = observerInput.time+runtime.samplePeriod;
    runtime.positionErrorBound.time = runtime.currentTime;
    runtime = localRecordMeasurementTimes(runtime, observerInput);
    output = localOutput(runtime, observerInput);
end

function output = localCurrentOutput(runtime, frame)
    observerInput = localSynchronizedInput(frame, runtime);
    tolerance = localTimeTolerance([observerInput.time; ...
        runtime.currentTime; runtime.samplePeriod]);
    if abs(observerInput.time-runtime.currentTime) > tolerance
        error("onlineNrmmTrackingRuntime:offSampleGrid", ...
            "The synchronized frame time must equal the observer time.");
    end
    outputRuntime = localRecordMeasurementTimes(runtime, observerInput);
    outputRuntime.currentTime = runtime.currentTime;
    boundState = localBoundState(localPackState(runtime),runtime.targetCount);
    boundState.radarPredictor(:,observerInput.radarDetectionAvailable) = ...
        observerInput.radarRelativePosition(observerInput.radarDetectionAvailable,:).';
    outputRuntime.positionErrorBound = nrmmPositionErrorBound("measure", ...
        runtime.positionErrorBound,observerInput,boundState);
    output = localOutput(outputRuntime, observerInput);
end

function [nextState, intervalAudit, positionErrorBound] = localRungeKuttaInterval( ...
        state, observerInput, runtime)
    nextState = state;
    intervalAudit = localOperatingDomainAudit( ...
        nextState, runtime, "interval-start", observerInput);
    step = runtime.integrationStep;
    positionErrorBound = runtime.positionErrorBound;
    for substepIdx = 1:runtime.integrationSubstepCount
        first = localObserverDerivative( ...
            nextState, observerInput, runtime);
        second = localObserverDerivative( ...
            nextState+0.5*step*first, observerInput, runtime);
        third = localObserverDerivative( ...
            nextState+0.5*step*second, observerInput, runtime);
        fourth = localObserverDerivative( ...
            nextState+step*third, observerInput, runtime);
        previousState = nextState;
        nextState = nextState+(step/6.0)*(first+2.0*second ...
            + 2.0*third+fourth);
        if any(~isfinite(nextState))
            error("onlineNrmmTrackingRuntime:nonfiniteObserverState", ...
                "The cascaded observer produced a nonfinite state.");
        end
        positionErrorBound = nrmmPositionErrorBound("advance",positionErrorBound, ...
            observerInput,localBoundState(previousState,runtime.targetCount), ...
            localBoundState(nextState,runtime.targetCount), ...
            localBoundState(first,runtime.targetCount),step);
        substepAudit = localOperatingDomainAudit( ...
            nextState, runtime, ...
            "substep-" + string(substepIdx) + "-accepted", ...
            observerInput);
        intervalAudit = localMergeDomainAudits( ...
            intervalAudit, substepAudit);
    end
end

function derivative = localObserverDerivative(state, observerInput, runtime)
    [yawEstimate, bodyVelocity, ...
        position, gnssPositionPredictor, targetState, ...
        targetOutputPredictor] = ...
        localUnpackState(state, runtime.targetCount);
    design = runtime.observerDesign;
    yawRateMeasured = observerInput.yawRate;
    gnssVelocity = observerInput.gnssVelocity;

    measuredBodyAcceleration = observerInput.bodyAcceleration;
    yawMeasurement = localCertifiedYawMeasurement( ...
        gnssVelocity, yawRateMeasured, design);
    observerEstimate = struct( ...
        "yaw", yawEstimate, ...
        "bodyVelocity", bodyVelocity, ...
        "position", position, ...
        "targetState", targetState);
    vectorFieldInput = struct( ...
        "yawRate", yawRateMeasured, ...
        "yawHeading", yawMeasurement.heading, ...
        "gnssVelocity", gnssVelocity, ...
        "bodyAcceleration", measuredBodyAcceleration, ...
        "positionReference", gnssPositionPredictor, ...
        "radarReference", targetOutputPredictor, ...
        "radarAvailable", observerInput.radarDetectionAvailable);
    [observerDerivative, observerModel] = nrmmObserverVectorField( ...
        observerEstimate, vectorFieldInput, design);
    gnssPredictorDerivative = observerModel.inertialVelocity;
    % The radar reference is expressed in the moving ego frame too.
    % Its residual obeys rDot = -(K1*I+u3*J)*r while radar is available.
    planarCross = [0,-1;1,0];
    targetPredictorDerivative = observerModel.targetPlantDerivative(1:2,:) ...
        -yawRateMeasured*planarCross*(targetOutputPredictor-targetState(1:2,:));
    derivative = [ ...
        observerDerivative.yaw; ...
        observerDerivative.bodyVelocity; ...
        observerDerivative.position; gnssPredictorDerivative; ...
        observerDerivative.targetState(:); targetPredictorDerivative(:)];
end

function audit = localOperatingDomainAudit( ...
        state, runtime, location, observerInput)
% localOperatingDomainAudit Audit domain assumptions without gating.
%
% The audit records whether the estimated states and measured inputs lie
% inside the certified operating domain of the boundedness theorem. It is
% reporting only: the Lipschitz extension keeps the observer well defined
% outside the domain, so no rejection is performed.

    if nargin < 4
        observerInput = struct();
    end
    [~, bodyVelocity, ~, ~, targetState] = ...
        localUnpackState(state, runtime.targetCount);
    design = runtime.observerDesign;
    domain = design.operatingDomain;
    targetDomain = design.target.domain;
    ego = struct("bodyVelocity", bodyVelocity, "yawRate", 0.0);
    tolerance = 128.0*eps(max(1.0, max(abs(state))));
    minimumTargetSpeed = Inf;
    maximumTargetAcceleration = 0.0;
    maximumTargetYawRate = 0.0;
    maximumRelativePosition = 0.0;
    saturationObserved = false;
    valid = true;
    speedValid = true;
    violationQuantities = strings(0, 1);
    violationLocations = strings(0, 1);
    for targetIdx = 1:runtime.targetCount
        [~, estimate] = nrmmTargetTrackerDerivative( ...
            targetState(:, targetIdx), ego, targetDomain);
        targetLabel = location+"-target-"+string(targetIdx);
        minimumTargetSpeed = min( ...
            minimumTargetSpeed, estimate.targetSpeed);
        maximumTargetAcceleration = max(maximumTargetAcceleration, ...
            abs(estimate.targetScalarAcceleration));
        maximumTargetYawRate = max(maximumTargetYawRate, ...
            abs(estimate.targetYawRate));
        relativePositionNorm = norm(estimate.relativePosition);
        maximumRelativePosition = max( ...
            maximumRelativePosition, relativePositionNorm);
        saturationObserved = saturationObserved ...
            || estimate.saturationActive;
        [valid, speedValid, violationQuantities, violationLocations] = ...
            localAuditUpperAndLowerBound( ...
            estimate.targetSpeed, targetDomain.speedMinimum, ...
            targetDomain.speedMaximum, "targetSpeed", targetLabel, ...
            valid, speedValid, violationQuantities, ...
            violationLocations, tolerance);
        [valid, ~, violationQuantities, violationLocations] = ...
            localAuditUpperAndLowerBound( ...
            relativePositionNorm, 0.0, ...
            targetDomain.relativePositionMaximum, ...
            "relativePosition", targetLabel, valid, true, ...
            violationQuantities, violationLocations, tolerance);
        if estimate.saturationActive
            valid = false;
            violationQuantities = [violationQuantities; ...
                estimate.saturatedQuantities]; %#ok<AGROW>
            violationLocations = [violationLocations; ...
                repmat(targetLabel, ...
                    numel(estimate.saturatedQuantities), 1)]; %#ok<AGROW>
        end
    end

    egoSpeed = norm(bodyVelocity);
    [valid, ~, violationQuantities, violationLocations] = ...
        localAuditUpperAndLowerBound( ...
        egoSpeed, domain.egoSpeedMinimum, domain.egoSpeedMaximum, ...
        "egoSpeed", location, valid, true, ...
        violationQuantities, violationLocations, tolerance);

    courseDirectionMagnitude = Inf;
    measuredYawRateMagnitude = 0.0;
    if isfield(observerInput, "gnssVelocity")
        courseDirectionMagnitude = norm(observerInput.gnssVelocity);
        measuredYawRateMagnitude = abs(observerInput.yawRate);
        courseGeometry = certifiedKinematicCourseCorrespondence( ...
            observerInput.gnssVelocity, observerInput.yawRate, ...
            design.yaw.courseModel.rearAxleDistance, ...
            design.sensors.velocityNoiseMaximum, ...
            design.sensors.gyroscopeNoiseMaximum, ...
            design.yaw.courseModel.singleTrackYawRateMismatchMaximum, ...
            design.yaw.courseModel.sideslipDomainMaximum);
        courseDirectionValid = courseGeometry.correspondence.informative;
        courseKinematicInversionValid = courseGeometry.inversionValid;
        courseModelBoundsConsistent = courseGeometry.boundsConsistent;
        courseTrueSpeedLowerBound = courseGeometry.trueSpeedLowerBound;
        courseSideslipErrorMaximum = courseGeometry.sideslipErrorMaximum;
        [valid, ~, violationQuantities, violationLocations] = ...
            localAuditUpperAndLowerBound( ...
            measuredYawRateMagnitude, 0.0, ...
            domain.measuredYawRateMaximum, ...
            "measuredYawRate", location, valid, true, ...
            violationQuantities, violationLocations, tolerance);
    else
        courseDirectionValid = true;
        courseKinematicInversionValid = true;
        courseModelBoundsConsistent = true;
        courseTrueSpeedLowerBound = Inf;
        courseSideslipErrorMaximum = 0.0;
    end
    directionViolationQuantities = strings(0, 1);
    directionViolationLocations = strings(0, 1);
    if ~courseDirectionValid
        directionViolationQuantities(end+1, 1) = ...
            "courseDirectionMagnitude";
        directionViolationLocations(end+1, 1) = location;
    end

    audit = struct( ...
        "valid", valid, ...
        "speedValid", speedValid, ...
        "directionEndpointsValid", courseDirectionValid, ...
        "yawMeasurementAvailable", courseDirectionValid, ...
        "courseDirectionValid", courseDirectionValid, ...
        "courseKinematicInversionValid", ...
            courseKinematicInversionValid, ...
        "courseModelBoundsConsistent", ...
            courseModelBoundsConsistent, ...
        "minimumCourseTrueSpeedLowerBound", ...
            courseTrueSpeedLowerBound, ...
        "maximumCourseSideslipError", ...
            courseSideslipErrorMaximum, ...
        "headingCorrectionGatedByDirectionAudit", false, ...
        "minimumCourseDirectionMagnitude", courseDirectionMagnitude, ...
        "maximumMeasuredYawRate", measuredYawRateMagnitude, ...
        "minimumTargetSpeed", minimumTargetSpeed, ...
        "maximumTargetScalarAcceleration", maximumTargetAcceleration, ...
        "maximumTargetYawRate", maximumTargetYawRate, ...
        "maximumRelativePosition", maximumRelativePosition, ...
        "targetSaturationObserved", saturationObserved, ...
        "minimumEgoSpeed", egoSpeed, ...
        "maximumEgoSpeed", egoSpeed, ...
        "evaluationPointCount", 1, ...
        "violationQuantities", violationQuantities, ...
        "violationLocations", violationLocations, ...
        "directionViolationQuantities", directionViolationQuantities, ...
        "directionViolationLocations", directionViolationLocations, ...
        "estimatedStateChecked", true, ...
        "trueTrajectoryChecked", false);
end

function [valid, selectedBoundValid, quantities, locations] = ...
        localAuditUpperAndLowerBound( ...
        value, lowerBound, upperBound, quantity, location, ...
        valid, selectedBoundValid, quantities, locations, tolerance)
    within = value >= lowerBound-tolerance ...
        && value <= upperBound+tolerance;
    valid = valid && within;
    selectedBoundValid = selectedBoundValid && within;
    if ~within
        quantities(end+1, 1) = quantity;
        locations(end+1, 1) = location;
    end
end

function combined = localMergeDomainAudits(first, second)
    combined = first;
    combined.valid = first.valid && second.valid;
    combined.speedValid = first.speedValid && second.speedValid;
    combined.directionEndpointsValid = ...
        first.directionEndpointsValid ...
        && second.directionEndpointsValid;
    combined.yawMeasurementAvailable = ...
        first.yawMeasurementAvailable && second.yawMeasurementAvailable;
    combined.courseDirectionValid = ...
        first.courseDirectionValid && second.courseDirectionValid;
    combined.courseKinematicInversionValid = ...
        first.courseKinematicInversionValid ...
        && second.courseKinematicInversionValid;
    combined.courseModelBoundsConsistent = ...
        first.courseModelBoundsConsistent ...
        && second.courseModelBoundsConsistent;
    combined.minimumCourseTrueSpeedLowerBound = min( ...
        first.minimumCourseTrueSpeedLowerBound, ...
        second.minimumCourseTrueSpeedLowerBound);
    combined.maximumCourseSideslipError = max( ...
        first.maximumCourseSideslipError, ...
        second.maximumCourseSideslipError);
    combined.minimumCourseDirectionMagnitude = min( ...
        first.minimumCourseDirectionMagnitude, ...
        second.minimumCourseDirectionMagnitude);
    combined.maximumMeasuredYawRate = max( ...
        first.maximumMeasuredYawRate, second.maximumMeasuredYawRate);
    combined.minimumTargetSpeed = min( ...
        first.minimumTargetSpeed, second.minimumTargetSpeed);
    combined.maximumTargetScalarAcceleration = max( ...
        first.maximumTargetScalarAcceleration, ...
        second.maximumTargetScalarAcceleration);
    combined.maximumTargetYawRate = max( ...
        first.maximumTargetYawRate, second.maximumTargetYawRate);
    combined.maximumRelativePosition = max( ...
        first.maximumRelativePosition, ...
        second.maximumRelativePosition);
    combined.targetSaturationObserved = ...
        first.targetSaturationObserved ...
        || second.targetSaturationObserved;
    combined.minimumEgoSpeed = min( ...
        first.minimumEgoSpeed, second.minimumEgoSpeed);
    combined.maximumEgoSpeed = max( ...
        first.maximumEgoSpeed, second.maximumEgoSpeed);
    combined.evaluationPointCount = ...
        first.evaluationPointCount+second.evaluationPointCount;
    combined.violationQuantities = [ ...
        first.violationQuantities; second.violationQuantities];
    combined.violationLocations = [ ...
        first.violationLocations; second.violationLocations];
    combined.directionViolationQuantities = [ ...
        first.directionViolationQuantities; ...
        second.directionViolationQuantities];
    combined.directionViolationLocations = [ ...
        first.directionViolationLocations; ...
        second.directionViolationLocations];
    combined.estimatedStateChecked = ...
        first.estimatedStateChecked && second.estimatedStateChecked;
    combined.trueTrajectoryChecked = ...
        first.trueTrajectoryChecked && second.trueTrajectoryChecked;
end

function output = localOutput(runtime, observerInput)
    design = runtime.observerDesign;
    rotation = localRotation(runtime.yawEstimate);
    inertialVelocity = rotation*runtime.bodyVelocityEstimate;
    measuredBodyAcceleration = observerInput.bodyAcceleration;
    inertialAcceleration = rotation*measuredBodyAcceleration;
    yawMeasurement = localCertifiedYawMeasurement( ...
        observerInput.gnssVelocity, observerInput.yawRate, design);
    courseHeading = yawMeasurement.heading;
    egoState = [ ...
        runtime.positionEstimate(1); inertialVelocity(1); ...
        inertialAcceleration(1); runtime.positionEstimate(2); ...
        inertialVelocity(2); inertialAcceleration(2)];

    output = struct( ...
        "time", runtime.currentTime, ...
        "stateTime", runtime.currentTime, ...
        "inputSampleTime", observerInput.time, ...
        "lastGnssTime", runtime.lastGnssTime, ...
        "lastImuTime", runtime.lastImuTime, ...
        "lastGyroscopeTime", runtime.lastGyroscopeTime, ...
        "lastRadarTime", runtime.lastRadarTime, ...
        "egoState", egoState, ...
        "egoPositionInertial", runtime.positionEstimate, ...
        "egoVelocityInertial", inertialVelocity, ...
        "egoBodyVelocity", runtime.bodyVelocityEstimate, ...
        "egoAccelerationBody", measuredBodyAcceleration, ...
        "egoAccelerationInertial", inertialAcceleration, ...
        "egoYaw", runtime.yawEstimate, ...
        "egoYawRate", observerInput.yawRate, ...
        "egoYawRateMeasured", observerInput.yawRate, ...
        "yawCoursePseudoHeading", courseHeading, ...
        "yawCourseEstimatedSideslip", ...
            yawMeasurement.course.estimatedSideslip, ...
        "yawCourseSideslipErrorMaximum", ...
            yawMeasurement.course.sideslipErrorMaximum, ...
        "yawCourseSideslipSineErrorMaximum", ...
            yawMeasurement.course.sineErrorMaximum, ...
        "yawCourseSideslipSpeedErrorContribution", ...
            yawMeasurement.course.speedErrorContribution, ...
        "yawCourseSideslipYawRateAndModelContribution", ...
            yawMeasurement.course.yawRateAndModelContribution, ...
        "yawCourseTrueSideslipInterval", ...
            yawMeasurement.course.trueSideslipInterval, ...
        "yawCourseMeasuredSpeed", yawMeasurement.course.measuredSpeed, ...
        "yawCourseTrueSpeedLowerBound", ...
            yawMeasurement.course.trueSpeedLowerBound, ...
        "yawCourseKinematicInversionValid", ...
            yawMeasurement.course.inversionValid, ...
        "yawCourseModelBoundsConsistent", ...
            yawMeasurement.course.boundsConsistent, ...
        "yawCourseCertifiedRadius", yawMeasurement.radius, ...
        "yawCourseChannelValid", yawMeasurement.informative, ...
        "yawCourseInnovation", localWrapToPi( ...
            courseHeading-runtime.yawEstimate), ...
        "yawInnovationChartCompatible", abs(localWrapToPi( ...
            courseHeading-runtime.yawEstimate))+yawMeasurement.radius < pi, ...
        "certificateScope",struct( ...
            "continuousVectorField",true,"sampledImplementationCertified",false, ...
            "yawChartAssessment","pointwise only; invariance is a theorem assumption"), ...
        "radarDetectionAvailable", ...
            observerInput.radarDetectionAvailable, ...
        "targetCertifiedSpeedDomainValid", ...
            runtime.targetCertifiedSpeedDomainValid, ...
        "targetCertifiedSpeedDomainValidThisInterval", ...
            runtime.lastIntervalTargetCertifiedSpeedDomainValid, ...
        "minimumReconstructedTargetSpeed", ...
            runtime.minimumReconstructedTargetSpeed, ...
        "estimatedOperatingDomainValid", ...
            runtime.estimatedDomainAudit.valid, ...
        "estimatedOperatingDomainValidThisInterval", ...
            runtime.lastIntervalDomainAudit.valid, ...
        "estimatedOperatingDomainAudit", ...
            runtime.estimatedDomainAudit, ...
        "lastIntervalOperatingDomainAudit", ...
            runtime.lastIntervalDomainAudit, ...
        "targetStates", runtime.targetState.', ...
        "targetEstimates", localTargetEstimates(runtime, observerInput));
    output.relativePositionErrorBound = runtime.positionErrorBound.targetComponents(1,:).';
    output.relativePositionErrorBound(~runtime.positionErrorBound.valid) = Inf;
    output.positionErrorBoundAvailable = runtime.positionErrorBound.valid(:) ...
        & isfinite(output.relativePositionErrorBound);
    output.egoYawErrorBound = runtime.positionErrorBound.yaw;
    output.egoBodyVelocityErrorBound = runtime.positionErrorBound.bodyVelocity;
end

function estimates = localTargetEstimates(runtime, observerInput)
    design = runtime.observerDesign;
    rotation = localRotation(runtime.yawEstimate);
    planarCross = [0.0, -1.0; 1.0, 0.0];
    ego = struct( ...
        "bodyVelocity", runtime.bodyVelocityEstimate, ...
        "yawRate", observerInput.yawRate);
    measuredBodyAcceleration = observerInput.bodyAcceleration;
    estimates = struct([]);
    for targetIdx = 1:runtime.targetCount
        [~, estimate] = nrmmTargetTrackerDerivative( ...
            runtime.targetState(:, targetIdx), ego, ...
            design.target.domain);
        estimate.certifiedSpeedMinimum = ...
            design.target.domain.speedMinimum;
        estimate.certifiedSpeedDomainValid = ...
            estimate.targetSpeed >= estimate.certifiedSpeedMinimum;
        estimate.relativePositionDerivative = ...
            estimate.targetVelocity-runtime.bodyVelocityEstimate ...
            - observerInput.yawRate*planarCross ...
                * estimate.relativePosition;
        estimate.velocityDifferenceEgoFrame = ...
            estimate.targetVelocity-runtime.bodyVelocityEstimate;
        estimate.accelerationDifferenceEgoFrame = ...
            estimate.targetAcceleration-measuredBodyAcceleration;
        estimate.targetPositionInertial = runtime.positionEstimate ...
            + rotation*estimate.relativePosition;
        estimate.targetVelocityInertial = ...
            rotation*estimate.targetVelocity;
        estimate.targetAccelerationInertial = ...
            rotation*estimate.targetAcceleration;
        estimate.targetCourseAngleInertial = localWrapToPi( ...
            runtime.yawEstimate+estimate.targetCourseAngleEgoFrame);
        estimate.targetHeadingInertial = localWrapToPi( ...
            estimate.targetCourseAngleInertial ...
            - estimate.targetSideslip);
        estimate.stateTime = runtime.currentTime;
        estimate.estimateTime = runtime.currentTime;
        estimate.lastRadarTime = runtime.lastRadarTime(targetIdx);
        radius = runtime.positionErrorBound.targetComponents(1,targetIdx);
        available = runtime.positionErrorBound.valid(targetIdx) && isfinite(radius);
        if ~available
            radius = Inf;
        end
        estimate.relativePositionErrorBound = radius;
        estimate.inertialRelativePositionErrorBound = radius ...
            +2*runtime.positionErrorBound.trueRangeMaximum(targetIdx) ...
            *sin(min(runtime.positionErrorBound.yaw,pi)/2);
        estimate.positionErrorBound = struct("time",runtime.currentTime, ...
            "radius",radius,"frame","ego-body-at-state-time", ...
            "available",available,"reason",runtime.positionErrorBound.reason(targetIdx), ...
            "integrationErrorIncluded",true,"floatingPointVerified",false, ...
            "scope",runtime.positionErrorBound.scope, ...
            "futurePredictionIncluded",false);
        % Retained as a compatibility alias with corrected semantics.
        estimate.measurementTime = estimate.lastRadarTime;
        if runtime.targetIdentifiersStable
            estimate.trackId = runtime.targetIdentifiers(targetIdx);
        else
            estimate.temporarySlotIdentifier = ...
                "target-slot-" + string(targetIdx);
        end
        if isempty(estimates)
            estimates = estimate;
        else
            estimates(targetIdx, 1) = estimate;
        end
    end
end

function runtime = localRecordMeasurementTimes(runtime, observerInput)
    runtime.lastInputSampleTime = observerInput.time;
    runtime.lastGnssTime = observerInput.time;
    runtime.lastImuTime = observerInput.time;
    runtime.lastGyroscopeTime = observerInput.time;
    runtime.lastRadarTime( ...
        observerInput.radarDetectionAvailable) = observerInput.time;
end

function observerInput = localSynchronizedInput(frame, runtime)
    [radarRelativePosition, radarDetectionAvailable] = ...
        localRadarPosition(frame, runtime);
    observerInput = struct( ...
        "time", localRequiredFrameScalar(frame, "time"), ...
        "gnssPosition", [ ...
            localRequiredFrameScalar(frame, "xGps"); ...
            localRequiredFrameScalar(frame, "yGps")], ...
        "gnssVelocity", [ ...
            localRequiredFrameScalar(frame, "vxGps"); ...
            localRequiredFrameScalar(frame, "vyGps")], ...
        "bodyAcceleration", [ ...
            localRequiredFrameScalar(frame, "longitudinalAcceleration"); ...
            localRequiredFrameScalar(frame, "lateralAcceleration")], ...
        "yawRate", localRequiredFrameScalar(frame, "yawRateMeasured"), ...
        "radarRelativePosition", radarRelativePosition, ...
        "radarDetectionAvailable", radarDetectionAvailable, ...
        "radarTargetIdentifiers", runtime.targetIdentifiers);
end

function [radar, available] = localRadarPosition(frame, runtime)
    targetCount = runtime.targetCount;
    if ~isstruct(frame) || ~isscalar(frame) ...
            || ~isfield(frame, "radarRelativePosition") ...
            || isempty(frame.radarRelativePosition)
        error("onlineNrmmTrackingRuntime:missingSynchronizedRadar", ...
            "Every observer frame must contain synchronized radar positions.");
    end
    radar = double(frame.radarRelativePosition);
    if targetCount == 1 && isvector(radar) && numel(radar) == 2
        radar = radar(:).';
    end
    available = true(targetCount, 1);
    if isfield(frame, "radarDetectionAvailable") ...
            && ~isempty(frame.radarDetectionAvailable)
        available = frame.radarDetectionAvailable;
        if targetCount == 1 && isscalar(available)
            available = available(:);
        end
        if ~islogical(available)
            if isnumeric(available) && all(isfinite(available), "all") ...
                    && all(available == 0.0 | available == 1.0, "all")
                available = logical(available);
            else
                error("onlineNrmmTrackingRuntime:" ...
                    + "invalidRadarDetectionAvailability", ...
                    "radarDetectionAvailable must be logical.");
            end
        end
    end
    validSize = isequal(size(radar), [targetCount, 2]) ...
        && isequal(size(available), [targetCount, 1]);
    if ~validSize
        error("onlineNrmmTrackingRuntime:invalidSynchronizedRadar", ...
            "Radar data must contain one two-vector and one flag per target.");
    end
    identifiersRequired = targetCount > 1;
    identifiersProvided = isfield(frame, "radarTargetIdentifiers") ...
        && ~isempty(frame.radarTargetIdentifiers);
    if identifiersRequired && ~identifiersProvided
        error("onlineNrmmTrackingRuntime:missingRadarTargetIdentifiers", ...
            "Multi-target frames must contain radarTargetIdentifiers.");
    end
    if identifiersProvided
        inputIdentifiers = string(frame.radarTargetIdentifiers(:));
        identifiersValid = numel(inputIdentifiers) == targetCount ...
            && all(~ismissing(inputIdentifiers)) ...
            && all(strlength(inputIdentifiers) > 0) ...
            && numel(unique(inputIdentifiers)) == targetCount;
        if ~identifiersValid
            error("onlineNrmmTrackingRuntime:" ...
                + "invalidRadarTargetIdentifiers", ...
                "radarTargetIdentifiers must be unique nonempty text.");
        end
        [knownIdentifiers, inputOrder] = ismember( ...
            runtime.targetIdentifiers, inputIdentifiers);
        if ~all(knownIdentifiers) ...
                || ~all(ismember(inputIdentifiers, ...
                    runtime.targetIdentifiers))
            error("onlineNrmmTrackingRuntime:" ...
                + "unknownRadarTargetIdentifier", ...
                "Every radar identifier must match an initialized track.");
        end
        radar = radar(inputOrder, :);
        available = available(inputOrder);
    end
    availableRowsFinite = all(isfinite(radar(available, :)), "all");
    unavailableRowsMissing = all( ...
        isnan(radar(~available, :)), "all");
    if ~availableRowsFinite || ~unavailableRowsMissing
        error("onlineNrmmTrackingRuntime:invalidSynchronizedRadar", ...
            "Detected radar rows must be finite and unavailable rows NaN.");
    end
end

function state = localPackState(runtime)
    state = [ ...
        runtime.yawEstimate; ...
        runtime.bodyVelocityEstimate; ...
        runtime.positionEstimate; runtime.gnssPositionPredictor; ...
        runtime.targetState(:); runtime.targetOutputPredictor(:)];
end

function [yawEstimate, bodyVelocity, ...
        position, gnssPositionPredictor, targetState, ...
        targetOutputPredictor] = localUnpackState(state, targetCount)
    yawEstimate = state(1);
    bodyVelocity = state(2:3);
    position = state(4:5);
    gnssPositionPredictor = state(6:7);
    targetStateEnd = 7+6*targetCount;
    targetState = reshape(state(8:targetStateEnd), 6, targetCount);
    targetOutputPredictor = reshape( ...
        state((targetStateEnd+1):end), 2, targetCount);
end

function state = localBoundState(packed,targetCount)
    [yaw,velocity,~,~,target,predictor] = localUnpackState(packed,targetCount);
    state = struct("yaw",yaw,"bodyVelocity",velocity, ...
        "targetState",target,"radarPredictor",predictor);
end

function targetState = localInitialTargets(options, targetCount)
    if ~isfield(options, "targetInitialState") ...
            || isempty(options.targetInitialState)
        error("onlineNrmmTrackingRuntime:missingInitialState", ...
            "options.targetInitialState is required.");
    end
    targetState = double(options.targetInitialState);
    if targetCount == 1 && isvector(targetState) ...
            && numel(targetState) == 6
        targetState = targetState(:);
    end
    if ~isequal(size(targetState), [6, targetCount]) ...
            || any(~isfinite(targetState), "all")
        error("onlineNrmmTrackingRuntime:invalidInitialState", ...
            "targetInitialState must be a finite 6-by-targetCount " ...
            + "matrix of [rho; q; s] columns.");
    end
end

function [identifiers, stable] = ...
        localTargetIdentifiers(options, targetCount)
    stable = false;
    identifiers = "target-slot-" + string((1:targetCount).');
    if ~isfield(options, "targetIdentifiers") ...
            || isempty(options.targetIdentifiers)
        if targetCount > 1
            error("onlineNrmmTrackingRuntime:" ...
                + "missingTargetIdentifiers", ...
                "Multi-target initialization requires stable target identifiers.");
        end
        return;
    end
    identifiers = string(options.targetIdentifiers(:));
    if numel(identifiers) ~= targetCount ...
            || any(ismissing(identifiers)) ...
            || any(strlength(identifiers) == 0) ...
            || numel(unique(identifiers)) ~= targetCount
        error("onlineNrmmTrackingRuntime:invalidTargetIdentifiers", ...
            "options.targetIdentifiers must contain one unique, nonempty " ...
            + "identifier per target.");
    end
    stable = true;
end

function value = localOptionPositiveInteger(options, fieldName, defaultValue)
    value = localOptionFiniteScalar(options, fieldName, defaultValue);
    if value < 1.0 || value ~= floor(value)
        error("onlineNrmmTrackingRuntime:invalidOption", ...
            "options.%s must be a positive integer.", fieldName);
    end
    value = double(value);
end

function value = localOptionFiniteScalar(options, fieldName, defaultValue)
    if isfield(options, fieldName) && ~isempty(options.(fieldName))
        value = double(options.(fieldName));
    else
        value = defaultValue;
    end
    if ~isscalar(value) || ~isfinite(value)
        error("onlineNrmmTrackingRuntime:invalidOption", ...
            "options.%s must be a finite scalar.", fieldName);
    end
end

function value = localRequiredOptionScalar(options, fieldName)
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        error("onlineNrmmTrackingRuntime:missingInitialState", ...
            "options.%s is required.", fieldName);
    end
    value = double(options.(fieldName));
    if ~isscalar(value) || ~isfinite(value)
        error("onlineNrmmTrackingRuntime:invalidInitialState", ...
            "options.%s must be a finite scalar.", fieldName);
    end
end

function value = localRequiredOptionVector(options, fieldName, count)
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        error("onlineNrmmTrackingRuntime:missingInitialState", ...
            "options.%s is required.", fieldName);
    end
    value = localOptionVector(options, fieldName, count, []);
end

function value = localOptionVector(options, fieldName, count, defaultValue)
    if isfield(options, fieldName) && ~isempty(options.(fieldName))
        value = double(options.(fieldName));
    else
        value = defaultValue;
    end
    if ~isequal(size(value), [count, 1]) || any(~isfinite(value))
        error("onlineNrmmTrackingRuntime:invalidInitialState", ...
            "options.%s must be a finite %d-by-1 vector.", ...
            fieldName, count);
    end
end

function value = localRequiredFrameScalar(frame, fieldName)
    if ~isstruct(frame) || ~isscalar(frame) ...
            || ~isfield(frame, fieldName) || isempty(frame.(fieldName))
        error("onlineNrmmTrackingRuntime:missingSynchronizedSignal", ...
            "Every observer frame must contain %s.", fieldName);
    end
    value = double(frame.(fieldName));
    if ~isscalar(value) || ~isfinite(value)
        error("onlineNrmmTrackingRuntime:invalidSynchronizedSignal", ...
            "frame.%s must be a finite scalar.", fieldName);
    end
end

function rotation = localRotation(yaw)
    rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
end

function value = localWrapToPi(value)
    value = mod(value+pi, 2.0*pi)-pi;
end

function tolerance = localTimeTolerance(time)
    tolerance = 64.0*eps(max(1.0, max(abs(time))));
end

function localAddProjectPaths()
    estimatorRoot = fileparts(mfilename("fullpath"));
    repoRoot = fileparts(estimatorRoot);
    addpath(fullfile(repoRoot, "config"));
    addpath(estimatorRoot);
end

function measurement = localCertifiedYawMeasurement( ...
        gnssVelocity, yawRateMeasured, design)
% localCertifiedYawMeasurement Certified GNSS-course yaw arc.
%
% The corrected course pair is the only rotation correspondence: its arc
% centre is the yaw measurement yF and its radius is BF. An uninformative
% pair is a violated operating-domain assumption, not an estimator output.
    courseGeometry = certifiedKinematicCourseCorrespondence( ...
        gnssVelocity, yawRateMeasured, ...
        design.yaw.courseModel.rearAxleDistance, ...
        design.sensors.velocityNoiseMaximum, ...
        design.sensors.gyroscopeNoiseMaximum, ...
        design.yaw.courseModel.singleTrackYawRateMismatchMaximum, ...
        design.yaw.courseModel.sideslipDomainMaximum);
    course = courseGeometry.correspondence;
    if ~course.informative
        error("onlineNrmmTrackingRuntime:uninformativeCourseChannel", ...
            "The certified course pair must be informative.");
    end
    measurement = struct( ...
        "heading", course.heading, ...
        "radius", course.radius, ...
        "informative", course.informative, ...
        "course", courseGeometry);
end
