function design = synthesizeNrmmObserverGains(cfg)
% synthesizeNrmmObserverGains Construct the cascaded observer certificates.
%
% Inertial-sensor biases are neglected, so no stage carries a bias state
% and the cascade is strictly feedforward. Configuration supplies only
% compact operating domains and deterministic sensor bounds. Runtime timing
% is not an input to the design. Every observer gain is recovered from a stated
% optimization problem. The objective, normalized pole region, and derived
% minimum decay rate are explicit engineering design conventions.
%
%   1. Yaw observer: the GNSS course pair defines one certified arc. Its
%      centre yF and radius BF follow from the pointwise kinematic sideslip
%      estimate asin(lrE*u3/||vm||) with a certified residual radius from
%      GNSS and gyro errors plus declared single-track mismatch, and
%      psiHatDot = u3 + kt*wrap(yF-psiHat) uses the solved correction
%      bandwidth kt. No channel-reliability gain or reliability-to-weight
%      map exists.
%   2. Body-velocity observer with gain kv. Its error matrix is
%      -kv*I - u3*J, whose rotation term is skew-symmetric, so P = I
%      certifies the decay rate lambda_v = kv exactly for every measured
%      yaw rate bounded by omegabar_m and with no bound on its derivative.
%   3. Position observer with gain kp.
%   4. High-gain NRMM target observer in [rho; q; s] coordinates. A
%      Sharma-type observer LMI recovers its normalized direction, the
%      unique Lyapunov identity fixes the certificate, and a physical
%      minimax solve uses structured Lipschitz dissipation to select omega_T.
%      The innovation gains are
%      [l1*wT; l2*wT^2; l3*wT^3].
%
% The essential three-state core chi = [xpsi; xv; WT] obeys a positive
% lower-triangular comparison system. Backward positive weights w satisfy
% w'*A = -ones(1,3), giving the explicit copositive Lyapunov function
% Vc=w'*chi, conditional on the invariant yaw innovation chart. Position
% is a downstream output stage; ultimate bounds follow by triangular
% forward substitution. The sampled implementation requires a separate proof.
%
% The yaw, velocity, and position gains minimize k subject to the continuous
% decay constraint exp(-k*Tdomain) <= 0.05. The solution log(20)/Tdomain uses the
% physical domain transit time and is independent of runtime timing.
% This minimum-bandwidth preference is explicit: ISS alone does not select
% a unique gain, and b+a/k alone has no finite interior minimum when a > 0.
% Design-validity violations or infeasible LMIs raise errors because they
% are synthesis preconditions of the boundedness theorem.

    localAddProjectPaths();
    if nargin < 1 || isempty(cfg)
        cfg = nrmmTrackingConfig();
    end
    if isfield(cfg, "observerDesign")
        error("synthesizeNrmmObserverGains:legacyManualGainConfiguration", ...
            "observerDesign gain/decay fields are no longer accepted; " ...
            + "all observer gains are synthesized from continuous domains and bounds.");
    end

    %% Sensor error bounds (Sec. 3)
    positionNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "positionNoiseMaximum"]);
    velocityNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "velocityNoiseMaximum"]);
    accelerometerNoise = localNonnegative(cfg, ...
        ["measurement", "imu", "noiseMaximum"]);
    gyroscopeNoise = localNonnegative(cfg, ...
        ["measurement", "gyroscope", "noiseMaximum"]);
    radarNoise = localNonnegative(cfg, ...
        ["measurement", "radar", "noiseMaximum"]);

    %% Ego operating domain (Assumption 1)
    egoSpeedMaximum = localPositive(cfg, ["ego", "domain", "speedMaximum"]);
    egoSpeedMinimum = localPositive(cfg, ["ego", "domain", "speedMinimum"]);
    if egoSpeedMinimum >= egoSpeedMaximum
        error("synthesizeNrmmObserverGains:invalidEgoSpeedInterval", ...
            "The ego speed interval requires V_{E,min} < Vbar_E.");
    end
    egoYawRateMaximum = localNonnegative(cfg, ...
        ["ego", "domain", "yawRateMaximum"]);
    measuredYawRateMaximum = egoYawRateMaximum+gyroscopeNoise;

    %% Certified yaw-measurement constants (Secs. 4, 11)
    egoRearAxleDistance = localPositive(cfg, ...
        ["ego", "yaw", "rearAxleDistance"]);
    sideslipDomainMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "sideslipDomainMaximum"]);
    if sideslipDomainMaximum >= 0.5*pi
        error("synthesizeNrmmObserverGains:invalidSideslipBound", ...
            "The ego side-slip inversion domain must be below pi/2.");
    end
    singleTrackYawRateMismatchMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "singleTrackYawRateMismatchMaximum"]);

    %% Physical horizon and solver constraints
    targetSpeedMaximum = localPositive(cfg, ...
        ["target", "domain", "speedMaximum"]);
    relativePositionMaximum = localPositive(cfg, ...
        ["target", "domain", "relativePositionMaximum"]);
    domainTransitTime = relativePositionMaximum ...
        /(egoSpeedMaximum+targetSpeedMaximum);
    scalarGainBounds = [log(20.0)/domainTransitTime, Inf];

    %% Solved ego-observer gains (Sec. 9)
    courseUniformCertificate = localUniformCourseRadius( ...
        egoSpeedMinimum, egoYawRateMaximum, egoRearAxleDistance, ...
        sideslipDomainMaximum, velocityNoise, gyroscopeNoise, ...
        singleTrackYawRateMismatchMaximum);
    yawUniformRadiusMaximum = courseUniformCertificate.radius;
    [yawCorrectionBandwidth, yawGainSolution] = ...
        localSolveScalarCorrectionGain(gyroscopeNoise, ...
            yawUniformRadiusMaximum, domainTransitTime, "yaw");
    yawDisturbance = gyroscopeNoise ...
        + yawCorrectionBandwidth*yawUniformRadiusMaximum;
    yawUltimate = yawUniformRadiusMaximum ...
        + gyroscopeNoise/yawCorrectionBandwidth;
    %% Body-velocity observer (Sec. 7)
    velocityProcessBound = egoSpeedMaximum*gyroscopeNoise ...
        + accelerometerNoise;
    velocityMeasurementEquivalent = ...
        egoSpeedMaximum*yawUltimate+velocityNoise;
    [velocityGain, velocityGainSolution] = ...
        localSolveScalarCorrectionGain(velocityProcessBound, ...
            velocityMeasurementEquivalent, domainTransitTime, "bodyVelocity");
    % A_v(u3) = -kv*I - u3*J has skew-symmetric rotation part, so
    % A_v' + A_v = -2*kv*I identically. P = I is therefore an exact
    % certificate: lambda_v = kv with unit conditioning.
    velocityLambda = velocityGain;
    velocityLyapunovMatrix = eye(2);
    localAssertVelocityCertificate( ...
        velocityGain, measuredYawRateMaximum, velocityLambda);
    velocityDisturbance = velocityProcessBound ...
        + velocityGain*velocityNoise;

    %% Feedforward cascade couplings (Secs. 7-8)
    velocityYawCoupling = velocityGain*egoSpeedMaximum;
    velocityUltimate = ...
        (velocityYawCoupling*yawUltimate+velocityDisturbance)/velocityLambda;

    positionProcessBound = egoSpeedMaximum*yawUltimate+velocityUltimate;
    [positionGain, positionGainSolution] = ...
        localSolveScalarCorrectionGain(positionProcessBound, ...
            positionNoise, domainTransitTime, "position");

    %% Target domain and Lipschitz constants (Sec. 5)
    targetSpeedMinimum = localPositive(cfg, ...
        ["target", "domain", "speedMinimum"]);
    if targetSpeedMaximum <= targetSpeedMinimum
        error("synthesizeNrmmObserverGains:invalidTargetSpeedInterval", ...
            "The target speed interval requires V_{C,min} < Vbar_C.");
    end
    targetAccelerationMaximum = localPositive(cfg, ...
        ["target", "domain", "scalarAccelerationMaximum"]);
    targetSideslipMaximum = localPositive(cfg, ...
        ["target", "domain", "sideslipMaximum"]);
    rearAxleDistance = localPositive(cfg, ...
        ["target", "domain", "rearAxleDistance"]);
    targetYawRateMaximum = ...
        targetSpeedMaximum*sin(targetSideslipMaximum)/rearAxleDistance;
    targetAccelerationNormBound = hypot(targetAccelerationMaximum, ...
        targetSpeedMaximum*targetYawRateMaximum);
    targetLipschitz = nrmmTargetLipschitzCertificate(struct( ...
        "speedMinimum",targetSpeedMinimum,"speedMaximum",targetSpeedMaximum, ...
        "scalarAccelerationMaximum",targetAccelerationMaximum, ...
        "yawRateMaximum",targetYawRateMaximum, ...
        "accelerationNormBound",targetAccelerationNormBound));
    scalarAccelerationRateMaximum = localNonnegative(cfg, ...
        ["target","model","scalarAccelerationRateMaximum"]);
    curvatureRateMaximum = localNonnegative(cfg, ...
        ["target","model","curvatureRateMaximum"]);
    modelJerkMaximum = hypot(scalarAccelerationRateMaximum, ...
        targetSpeedMaximum^2*curvatureRateMaximum);

    %% Solved normalized target shape and physical bandwidth (Secs. 9-10)
    targetCertificate = synthesizeTargetTrackerCertificate( ...
        targetLipschitz, struct( ...
            "velocityUltimate", velocityUltimate, ...
            "relativePositionMaximum", relativePositionMaximum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "gyroscopeNoiseMaximum", gyroscopeNoise, ...
            "radarNoiseMaximum", radarNoise, ...
            "modelJerkMaximum",modelJerkMaximum), domainTransitTime);
    targetBandwidth = targetCertificate.bandwidth;
    targetInputScale = targetCertificate.inputScale;
    targetInjectionVector = targetCertificate.injectionVector;
    targetClosedLoopMatrix = targetCertificate.closedLoopMatrix;
    targetLyapunovMatrix = targetCertificate.lyapunovMatrix;
    targetEigMinimum = targetCertificate.eigenvalueMinimum;
    targetEigMaximum = targetCertificate.eigenvalueMaximum;
    targetLambda = targetCertificate.lambda;
    targetGainConstant = targetCertificate.gainConstant;
    targetVelocityCoupling = targetCertificate.velocityCoupling;
    targetDisturbance = targetCertificate.disturbanceBound;

    %% Explicit copositive ISS certificate for the essential core
    coreCertificate = nrmmObserverCertificate(struct( ...
        "yawDecayRate", yawCorrectionBandwidth, ...
        "velocityDecayRate", velocityLambda, ...
        "targetDecayRate", targetLambda, ...
        "velocityYawCoupling", velocityYawCoupling, ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "input", [yawDisturbance; velocityDisturbance; targetDisturbance]));

    %% Ultimate bounds (Cors. 8.1-8.2)
    % Scalar forward substitution down the triangular cascade.
    positionUltimate = positionNoise ...
        + (egoSpeedMaximum*yawUltimate+velocityUltimate)/positionGain;
    targetUltimate = ...
        (targetVelocityCoupling*velocityUltimate+targetDisturbance) ...
        / targetLambda;
    relativePositionUltimate = targetCertificate.relativePositionUltimate;
    targetVelocityUltimate = targetCertificate.targetVelocityUltimate;
    targetAccelerationUltimate = targetCertificate.targetAccelerationUltimate;
    controllerRelativePositionUltimate = relativePositionUltimate ...
        + relativePositionMaximum*yawUltimate;

    %% Assembled design
    design = struct();
    design.construction = ...
        "certified rotation correspondences, covariant observer chains, " ...
        + "and an explicit triangular copositive ISS certificate";
    design.sensors = struct( ...
        "positionNoiseMaximum", positionNoise, ...
        "velocityNoiseMaximum", velocityNoise, ...
        "accelerometerNoiseMaximum", accelerometerNoise, ...
        "gyroscopeNoiseMaximum", gyroscopeNoise, ...
        "radarNoiseMaximum", radarNoise);
    design.yaw = struct( ...
        "correctionBandwidth", yawCorrectionBandwidth, ...
        "courseModel", struct( ...
            "rearAxleDistance", egoRearAxleDistance, ...
            "sideslipDomainMaximum", sideslipDomainMaximum, ...
            "singleTrackYawRateMismatchMaximum", ...
                singleTrackYawRateMismatchMaximum, ...
            "relation", ...
                "omegaE=VE*sin(betaE)/lrE+boundedMismatch"), ...
        "uniformCourseRadiusMaximum", yawUniformRadiusMaximum, ...
        "uniformCourseCertificate", courseUniformCertificate, ...
        "measurementMethod", ...
            "kinematic-sideslip-corrected-certified-correspondence", ...
        "courseErrorVectorRadius", velocityNoise, ...
        "disturbanceBound", yawDisturbance, ...
        "gainOptimization", yawGainSolution);
    design.velocity = struct( ...
        "gain", velocityGain, ...
        "lyapunovMatrix", velocityLyapunovMatrix, ...
        "lambda", velocityLambda, ...
        "gainConstant", 1.0, ...
        "disturbanceBound", velocityDisturbance, ...
        "gainOptimization", velocityGainSolution);
    design.position = struct( ...
        "gain", positionGain, ...
        "gainOptimization", positionGainSolution);
    design.target = struct( ...
        "shape", targetCertificate.shape, ...
        "shapeConstruction", targetCertificate.construction, ...
        "bandwidth", targetBandwidth, ...
        "injectionVector", targetInjectionVector, ...
        "innovationGains", [ ...
            targetInjectionVector(1)*targetBandwidth; ...
            targetInjectionVector(2)*targetBandwidth^2; ...
            targetInjectionVector(3)*targetBandwidth^3], ...
        "closedLoopMatrix", targetClosedLoopMatrix, ...
        "closedLoopPoles", targetCertificate.closedLoopPoles, ...
        "normalizedDecayRate", ...
            targetCertificate.normalizedDecayRate, ...
        "domainTransitDecayRate", ...
            targetCertificate.domainTransitDecayRate, ...
        "designLyapunovMatrix", ...
            targetCertificate.designLyapunovMatrix, ...
        "lyapunovMatrix", targetLyapunovMatrix, ...
        "eigenvalueMinimum", targetEigMinimum, ...
        "eigenvalueMaximum", targetEigMaximum, ...
        "lambda", targetLambda, ...
        "gainConstant", targetGainConstant, ...
        "thresholdConstant", targetCertificate.thresholdConstant, ...
        "certificateResidualMargin", targetCertificate.residualMargin, ...
        "shapeObjectiveValue", targetCertificate.designObjectiveValue, ...
        "certificateObjectiveValue", ...
            targetCertificate.ultimateObjectiveValue, ...
        "initialLyapunovBound", ...
            targetCertificate.initialLyapunovBound, ...
        "transitLyapunovBound", ...
            targetCertificate.transitLyapunovBound, ...
        "normalizedComponentBounds", ...
            targetCertificate.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", ...
            targetCertificate.bandwidthActiveConstraint, ...
        "bandwidthSearchBracket", ...
            targetCertificate.bandwidthSearchBracket, ...
        "inputScale", targetInputScale, ...
        "disturbanceBound", targetDisturbance, ...
        "lipschitzCertificate",targetLipschitz, ...
        "lipschitzMultipliers",targetCertificate.lipschitzMultipliers, ...
        "lipschitzDissipationMatrix",targetCertificate.lipschitzDissipationMatrix, ...
        "lipschitzResidualMargin",targetCertificate.lipschitzResidualMargin, ...
        "componentConversion",targetCertificate.componentConversion, ...
        "disturbanceCoefficients",targetCertificate.disturbanceCoefficients, ...
        "minimumDecayRate",targetCertificate.minimumDecayRate, ...
        "modelJerkMaximum",modelJerkMaximum, ...
        "domain", struct( ...
            "speedMinimum", targetSpeedMinimum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "scalarAccelerationMaximum", targetAccelerationMaximum, ...
            "yawRateMaximum", targetYawRateMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "sideslipMaximum", targetSideslipMaximum, ...
            "rearAxleDistance", rearAxleDistance, ...
            "relativePositionMaximum", relativePositionMaximum));
    design.coupling = struct( ...
        "velocityYawCoupling", velocityYawCoupling, ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "feedforward", true);
    design.coreIss = coreCertificate;
    design.ultimateBounds = struct( ...
        "yaw", yawUltimate, ...
        "bodyVelocity", velocityUltimate, ...
        "position", positionUltimate, ...
        "targetLyapunov", targetUltimate, ...
        "relativePosition", relativePositionUltimate, ...
        "targetVelocity", targetVelocityUltimate, ...
        "targetAcceleration", targetAccelerationUltimate, ...
        "yawRate", gyroscopeNoise, ...
        "inertialVelocity", velocityUltimate ...
            + egoSpeedMaximum*yawUltimate, ...
        "targetPositionInertial", positionUltimate ...
            + relativePositionUltimate ...
            + relativePositionMaximum*yawUltimate, ...
        "targetVelocityInertial", targetVelocityUltimate ...
            + targetSpeedMaximum*yawUltimate, ...
        "targetAccelerationInertial", targetAccelerationUltimate ...
            + targetAccelerationNormBound*yawUltimate, ...
        "velocityDifference", targetVelocityUltimate+velocityUltimate, ...
        "accelerationDifference", targetAccelerationUltimate+accelerometerNoise);
    design.ultimateBounds.controllerRelativePosition = ...
        controllerRelativePositionUltimate;
    design.gainSelection = struct( ...
        "method", "structured-lipschitz-iss-minimax-synthesis", ...
        "scalarMethod", "minimum-bandwidth-continuous-decay", ...
        "domainTransitTime", domainTransitTime, ...
        "scalarGainBounds", scalarGainBounds, ...
        "yawProgram", yawGainSolution, ...
        "velocityProgram", velocityGainSolution, ...
        "positionProgram", positionGainSolution, ...
        "achievedDecayRates", struct( ...
            "yaw", yawCorrectionBandwidth, ...
            "bodyVelocity", velocityLambda, ...
            "position", positionGain, ...
            "target", targetLambda), ...
        "targetShapeMethod", "normalized-observer-lmi", ...
        "targetBandwidthMethod", ...
            "normalized-ultimate-bound-with-domain-transit-decay", ...
        "targetBandwidth", targetBandwidth);
    design.certificateScope = struct( ...
        "timeModel","continuous observer with continuous bounded-error measurements", ...
        "yawCondition","compatible innovation chart with invariant error radius", ...
        "sampledImplementationCertified",false, ...
        "qualification","the certificate concerns the continuous vector field under its stated premises");
    design.operatingDomain = struct( ...
        "egoSpeedMinimum", egoSpeedMinimum, ...
        "egoSpeedMaximum", egoSpeedMaximum, ...
        "egoYawRateMaximum", egoYawRateMaximum, ...
        "measuredYawRateMaximum", measuredYawRateMaximum, ...
        "egoSideslipDomainMaximum", sideslipDomainMaximum, ...
        "egoSingleTrackYawRateMismatchMaximum", ...
            singleTrackYawRateMismatchMaximum, ...
        "target", design.target.domain, ...
        "containmentScope", ...
            "estimated runtime states and measured inputs only; " ...
            + "truth trajectories require offline audit");
end

function certificate = localUniformCourseRadius(speedMinimum, ...
        yawRateMaximum, rearAxleDistance, sideslipDomainMaximum, ...
        velocityNoise, gyroscopeNoise, modelMismatchMaximum)
% localUniformCourseRadius Lift the pointwise course proof to the domain.

    measuredSpeedMinimum = speedMinimum-velocityNoise;
    trueSpeedLowerBound = speedMinimum-2.0*velocityNoise;
    if trueSpeedLowerBound <= 0.0
        error("synthesizeNrmmObserverGains:uncertifiedCourseSpeed", ...
            "ego.domain.speedMinimum must exceed twice the GNSS velocity-error radius.");
    end
    measuredYawRateMaximum = yawRateMaximum+gyroscopeNoise;
    normalizedYawRateMaximum = rearAxleDistance ...
        * measuredYawRateMaximum/measuredSpeedMinimum;
    if normalizedYawRateMaximum >= 1.0
        error("synthesizeNrmmObserverGains:uncertifiedCourseInversion", ...
            "The declared ego domain cannot certify the course-channel asin inversion.");
    end
    directionRadius = asin(velocityNoise/measuredSpeedMinimum);
    speedContribution = rearAxleDistance*measuredYawRateMaximum ...
        * velocityNoise/(measuredSpeedMinimum*trueSpeedLowerBound);
    yawRateAndModelContribution = rearAxleDistance ...
        *(gyroscopeNoise+modelMismatchMaximum)/trueSpeedLowerBound;
    sineErrorMaximum = speedContribution+yawRateAndModelContribution;
    inverseDomainMaximum = max(sin(sideslipDomainMaximum), ...
        normalizedYawRateMaximum);
    inverseLipschitz = 1.0/sqrt(1.0-inverseDomainMaximum^2);
    sideslipErrorMaximum = inverseLipschitz*sineErrorMaximum;
    radius = directionRadius+sideslipErrorMaximum;
    if ~isfinite(radius) || radius >= pi
        error("synthesizeNrmmObserverGains:uncertifiedCourseRadius", ...
            "The declared domain does not yield a proper uniform course-yaw arc.");
    end
    certificate = struct( ...
        "radius", radius, ...
        "directionRadius", directionRadius, ...
        "sideslipErrorMaximum", sideslipErrorMaximum, ...
        "sineErrorMaximum", sineErrorMaximum, ...
        "speedErrorContribution", speedContribution, ...
        "yawRateAndModelContribution", ...
            yawRateAndModelContribution, ...
        "measuredSpeedMinimum", measuredSpeedMinimum, ...
        "trueSpeedLowerBound", trueSpeedLowerBound, ...
        "normalizedYawRateMaximum", normalizedYawRateMaximum, ...
        "inverseLipschitz", inverseLipschitz);
end

function [gain, solution] = localSolveScalarCorrectionGain( ...
        processBound, measurementEquivalentBound, domainTransitTime, stage)
% localSolveScalarCorrectionGain Minimize bandwidth at the required decay.
%
% For D+e <= -k*e+a+k*b, every k > 0 supplies continuous decay k and
% ultimate radius b+a/k. Require exp(-k*Tdomain) <= 0.05 and minimize k;
% the physical transit time fixes the unique solution log(20)/Tdomain.
% The 5 percent residual is a continuous settling preference. Sensor bounds
% affect the resulting radius, not this minimum-bandwidth preference.

    gain = log(20.0)/domainTransitTime;
    disturbanceContribution = processBound/gain;
    solution = struct( ...
        "stage", stage, ...
        "method", "minimum-bandwidth-continuous-decay", ...
        "processBound", processBound, ...
        "measurementEquivalentBound", measurementEquivalentBound, ...
        "minimumDecayRate", gain, ...
        "transitResidualFraction", 0.05, ...
        "gain", gain, ...
        "disturbanceContribution", disturbanceContribution, ...
        "ultimateBound", measurementEquivalentBound+disturbanceContribution, ...
        "objectiveValue", gain, ...
        "activeConstraint", "domain-transit-decay");
end

function localAssertVelocityCertificate(velocityGain, yawRateBound, lambda)
% localAssertVelocityCertificate Verify P = I certifies the decay rate.
%
% The claim A_v(u3)' + A_v(u3) = -2*lambda*I is an identity in u3, not a
% numerical solution, but it is the load-bearing step of the velocity
% stage, so it is checked at both interval vertices before use.

    planarCross = [0.0, -1.0; 1.0, 0.0];
    for vertex = [-yawRateBound, yawRateBound]
        systemMatrix = -velocityGain*eye(2)-vertex*planarCross;
        residual = systemMatrix.'+systemMatrix+2.0*lambda*eye(2);
        if max(abs(residual), [], "all") > 128.0*eps(max(1.0, lambda))
            error("synthesizeNrmmObserverGains:invalidVelocityCertificate", ...
                "P = I must certify the velocity decay rate exactly.");
        end
    end
end

function value = localPositive(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value <= 0.0
        error("synthesizeNrmmObserverGains:invalidPositiveScalar", ...
            "%s must be a finite positive scalar.", strjoin(path, "."));
    end
end

function value = localNonnegative(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value < 0.0
        error("synthesizeNrmmObserverGains:invalidNonnegativeScalar", ...
            "%s must be a finite nonnegative scalar.", strjoin(path, "."));
    end
end

function value = localField(cfg, path)
    value = cfg;
    for fieldIdx = 1:numel(path)
        fieldName = char(path(fieldIdx));
        if ~isstruct(value) || ~isfield(value, fieldName) ...
                || isempty(value.(fieldName))
            error("synthesizeNrmmObserverGains:missingConfiguration", ...
                "%s is required.", strjoin(path, "."));
        end
        value = value.(fieldName);
    end
end

function localAddProjectPaths()
    estimatorRoot = fileparts(mfilename("fullpath"));
    repoRoot = fileparts(estimatorRoot);
    addpath(fullfile(repoRoot, "config"));
    addpath(estimatorRoot);
end
