function design = synthesizeNrmmObserverGains(cfg)
% synthesizeNrmmObserverGains Construct the cascaded observer certificates.
%
% Inertial-sensor biases are neglected, so no stage carries a bias state
% and the cascade is strictly feedforward. Configuration supplies only
% compact operating domains, deterministic sensor bounds, and the sampled
% realization period. Every observer gain is recovered from a stated
% optimization problem; no desired pole, decay rate, gain shape, or
% bandwidth is entered by the user.
%
%   1. Yaw observer: the GNSS course pair defines one certified arc. Its
%      centre yF and radius BF follow from the pointwise kinematic sideslip
%      estimate asin(lrE*u3/||vm||) with a certified residual radius from
%      GNSS and gyro errors plus declared single-track mismatch, and
%      psiHatDot = u3 + kt*(yF-psiHat) uses the solved correction
%      bandwidth kt. No channel-reliability gain or reliability-to-weight
%      map exists.
%   2. Body-velocity observer with gain kv. Its error matrix is
%      -kv*I - u3*J, whose rotation term is skew-symmetric, so P = I
%      certifies the decay rate lambda_v = kv exactly for every measured
%      yaw rate bounded by omegabar_m and with no bound on its derivative.
%   3. Position observer with gain kp.
%   4. High-gain NRMM target observer in [rho; q; s] coordinates. A
%      Sharma-type observer LMI recovers its normalized direction, the
%      unique Lyapunov identity fixes the certificate, and a physical
%      minimax solve selects omega_T. The innovation gains are
%      [l1*wT; l2*wT^2; l3*wT^3].
%
% The essential three-state core chi = [xpsi; xv; WT] obeys a positive
% lower-triangular comparison system. Backward positive weights w satisfy
% w'*A = -ones(1,3), giving the explicit copositive Lyapunov function
% Vc=w'*chi. The acceleration certificate precedes this core and position
% is a downstream output-filter corollary; their ultimate bounds follow by
% scalar forward substitution, so no auxiliary five-state matrix exists.
%
% The yaw, velocity, and position gains solve the closed-form scalar
% balance k = proj(sqrt(a/(Ts*b))), the exact minimizer of
% max(a/k, Ts*b*k): persistent-dynamics leakage against the one-sample
% innovation contribution, projected onto the physical gain interval
% between the e-fold domain-transit rate and the nonexpansive
% sampled-correction rate.
% Design-validity violations or infeasible LMIs raise errors because they
% are synthesis preconditions of the boundedness theorem.

    localAddProjectPaths();
    if nargin < 1 || isempty(cfg)
        cfg = nrmmTrackingConfig();
    end
    if isfield(cfg, "observerDesign")
        error("synthesizeNrmmObserverGains:legacyManualGainConfiguration", ...
            "observerDesign gain/decay fields are no longer accepted; " ...
            + "all observer gains are synthesized from domains, bounds, and timing.");
    end
    samplePeriod = localPositive(cfg, ["runtime", "samplePeriod"]);

    %% Sensor error bounds (Sec. 3)
    positionNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "positionNoiseMaximum"]);
    velocityNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "velocityNoiseMaximum"]);
    accelerometerNoise = localNonnegative(cfg, ...
        ["measurement", "imu", "noiseMaximum"]);
    gyroscopeNoise = localNonnegative(cfg, ...
        ["measurement", "gyroscope", "noiseMaximum"]);
    radarNoise = localNonnegative(cfg, ...
        ["measurement", "radar", "noiseMaximum"]);

    %% Ego operating domain (Assumption 1)
    egoSpeedMaximum = localPositive(cfg, ["ego", "domain", "speedMaximum"]);
    egoSpeedMinimum = localPositive(cfg, ["ego", "domain", "speedMinimum"]);
    if egoSpeedMinimum >= egoSpeedMaximum
        error("synthesizeNrmmObserverGains:invalidEgoSpeedInterval", ...
            "The ego speed interval requires V_{E,min} < Vbar_E.");
    end
    egoYawRateMaximum = localNonnegative(cfg, ...
        ["ego", "domain", "yawRateMaximum"]);
    measuredYawRateMaximum = egoYawRateMaximum+gyroscopeNoise;

    %% Certified yaw-measurement constants (Secs. 4, 11)
    egoRearAxleDistance = localPositive(cfg, ...
        ["ego", "yaw", "rearAxleDistance"]);
    sideslipDomainMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "sideslipDomainMaximum"]);
    if sideslipDomainMaximum >= 0.5*pi
        error("synthesizeNrmmObserverGains:invalidSideslipBound", ...
            "The ego side-slip inversion domain must be below pi/2.");
    end
    singleTrackYawRateMismatchMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "singleTrackYawRateMismatchMaximum"]);

    %% Physical horizon and solver constraints
    targetSpeedMaximum = localPositive(cfg, ...
        ["target", "domain", "speedMaximum"]);
    relativePositionMaximum = localPositive(cfg, ...
        ["target", "domain", "relativePositionMaximum"]);
    domainTransitTime = relativePositionMaximum ...
        /(egoSpeedMaximum+targetSpeedMaximum);
    scalarGainBounds = [1.0/domainTransitTime, 1.0/samplePeriod];
    scalarSampleProductBounds = scalarGainBounds*samplePeriod;

    %% Solved ego-observer gains (Sec. 9)
    courseUniformCertificate = localUniformCourseRadius( ...
        egoSpeedMinimum, egoYawRateMaximum, egoRearAxleDistance, ...
        sideslipDomainMaximum, velocityNoise, gyroscopeNoise, ...
        singleTrackYawRateMismatchMaximum);
    yawUniformRadiusMaximum = courseUniformCertificate.radius;
    [yawCorrectionBandwidth, yawGainSolution] = ...
        localSolveScalarCorrectionGain(gyroscopeNoise, ...
            yawUniformRadiusMaximum, samplePeriod, ...
            domainTransitTime, "yaw");
    yawDisturbance = gyroscopeNoise ...
        + yawCorrectionBandwidth*yawUniformRadiusMaximum;
    yawUltimate = yawUniformRadiusMaximum ...
        + gyroscopeNoise/yawCorrectionBandwidth;
    %% Body-velocity observer (Sec. 7)
    velocityProcessBound = egoSpeedMaximum*gyroscopeNoise ...
        + accelerometerNoise;
    velocityMeasurementEquivalent = ...
        egoSpeedMaximum*yawUltimate+velocityNoise;
    [velocityGain, velocityGainSolution] = ...
        localSolveScalarCorrectionGain(velocityProcessBound, ...
            velocityMeasurementEquivalent, samplePeriod, ...
            domainTransitTime, "bodyVelocity");
    % A_v(u3) = -kv*I - u3*J has skew-symmetric rotation part, so
    % A_v' + A_v = -2*kv*I identically. P = I is therefore an exact
    % certificate: lambda_v = kv with unit conditioning.
    velocityLambda = velocityGain;
    velocityLyapunovMatrix = eye(2);
    localAssertVelocityCertificate( ...
        velocityGain, measuredYawRateMaximum, velocityLambda);
    velocityDisturbance = velocityProcessBound ...
        + velocityGain*velocityNoise;

    %% Feedforward cascade couplings (Secs. 7-8)
    velocityYawCoupling = velocityGain*egoSpeedMaximum;
    velocityUltimate = ...
        (velocityYawCoupling*yawUltimate+velocityDisturbance)/velocityLambda;

    positionProcessBound = egoSpeedMaximum*yawUltimate+velocityUltimate;
    [positionGain, positionGainSolution] = ...
        localSolveScalarCorrectionGain(positionProcessBound, ...
            positionNoise, samplePeriod, domainTransitTime, "position");

    %% Target domain and Lipschitz constants (Sec. 5)
    targetSpeedMinimum = localPositive(cfg, ...
        ["target", "domain", "speedMinimum"]);
    if targetSpeedMaximum <= targetSpeedMinimum
        error("synthesizeNrmmObserverGains:invalidTargetSpeedInterval", ...
            "The target speed interval requires V_{C,min} < Vbar_C.");
    end
    targetAccelerationMaximum = localPositive(cfg, ...
        ["target", "domain", "scalarAccelerationMaximum"]);
    targetSideslipMaximum = localPositive(cfg, ...
        ["target", "domain", "sideslipMaximum"]);
    rearAxleDistance = localPositive(cfg, ...
        ["target", "domain", "rearAxleDistance"]);
    targetYawRateMaximum = ...
        targetSpeedMaximum*sin(targetSideslipMaximum)/rearAxleDistance;
    targetAccelerationNormBound = hypot(targetAccelerationMaximum, ...
        targetSpeedMaximum*targetYawRateMaximum);
    scalarAccelerationVelocityLipschitz = ...
        2.0*targetAccelerationNormBound/targetSpeedMinimum;
    scalarAccelerationAccelerationLipschitz = 1.0;
    yawRateVelocityLipschitz = ...
        3.0*targetAccelerationNormBound/targetSpeedMinimum^2;
    yawRateAccelerationLipschitz = 1.0/targetSpeedMinimum;
    phiVelocityLipschitz = targetYawRateMaximum^2 ...
        + 2.0*targetYawRateMaximum*targetSpeedMaximum ...
            * yawRateVelocityLipschitz ...
        + 3.0*(2.0*targetAccelerationMaximum*targetYawRateMaximum ...
                / targetSpeedMinimum ...
            + targetAccelerationMaximum*yawRateVelocityLipschitz ...
            + targetYawRateMaximum ...
                * scalarAccelerationVelocityLipschitz);
    phiAccelerationLipschitz = ...
        2.0*targetYawRateMaximum*targetSpeedMaximum ...
            * yawRateAccelerationLipschitz ...
        + 3.0*(targetAccelerationMaximum*yawRateAccelerationLipschitz ...
            + targetYawRateMaximum ...
                * scalarAccelerationAccelerationLipschitz);
    phiLipschitz = hypot(phiVelocityLipschitz, phiAccelerationLipschitz);

    %% Solved normalized target shape and physical bandwidth (Secs. 9-10)
    targetCertificate = synthesizeTargetTrackerCertificate( ...
        phiLipschitz, struct( ...
            "velocityUltimate", velocityUltimate, ...
            "relativePositionMaximum", relativePositionMaximum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "gyroscopeNoiseMaximum", gyroscopeNoise, ...
            "radarNoiseMaximum", radarNoise), domainTransitTime);
    targetBandwidth = targetCertificate.bandwidth;
    targetInputScale = targetCertificate.inputScale;
    targetInjectionVector = targetCertificate.injectionVector;
    targetClosedLoopMatrix = targetCertificate.closedLoopMatrix;
    targetLyapunovMatrix = targetCertificate.lyapunovMatrix;
    targetEigMinimum = targetCertificate.eigenvalueMinimum;
    targetEigMaximum = targetCertificate.eigenvalueMaximum;
    targetLambda = targetCertificate.lambda;
    targetGainConstant = targetCertificate.gainConstant;
    targetVelocityCoupling = targetCertificate.velocityCoupling;
    targetDisturbance = targetCertificate.disturbanceBound;

    %% Explicit copositive ISS certificate for the essential core
    coreCertificate = nrmmObserverCertificate(struct( ...
        "yawDecayRate", yawCorrectionBandwidth, ...
        "velocityDecayRate", velocityLambda, ...
        "targetDecayRate", targetLambda, ...
        "velocityYawCoupling", velocityYawCoupling, ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "input", [yawDisturbance; velocityDisturbance; targetDisturbance]));

    %% Ultimate bounds (Cors. 8.1-8.2)
    % Scalar forward substitution down the triangular cascade.
    positionUltimate = positionNoise ...
        + (egoSpeedMaximum*yawUltimate+velocityUltimate)/positionGain;
    targetUltimate = ...
        (targetVelocityCoupling*velocityUltimate+targetDisturbance) ...
        / targetLambda;
    relativePositionUltimate = targetUltimate ...
        / (targetBandwidth^2*sqrt(targetEigMinimum));
    targetVelocityUltimate = targetUltimate ...
        / (targetBandwidth*sqrt(targetEigMinimum));
    targetAccelerationUltimate = targetUltimate/sqrt(targetEigMinimum);
    controllerRelativePositionUltimate = relativePositionUltimate ...
        + relativePositionMaximum*yawUltimate;

    %% Assembled design
    design = struct();
    design.samplePeriod = samplePeriod;
    design.construction = ...
        "certified rotation correspondences, covariant observer chains, " ...
        + "and an explicit triangular copositive ISS certificate";
    design.sensors = struct( ...
        "positionNoiseMaximum", positionNoise, ...
        "velocityNoiseMaximum", velocityNoise, ...
        "accelerometerNoiseMaximum", accelerometerNoise, ...
        "gyroscopeNoiseMaximum", gyroscopeNoise, ...
        "radarNoiseMaximum", radarNoise);
    design.yaw = struct( ...
        "correctionBandwidth", yawCorrectionBandwidth, ...
        "courseModel", struct( ...
            "rearAxleDistance", egoRearAxleDistance, ...
            "sideslipDomainMaximum", sideslipDomainMaximum, ...
            "singleTrackYawRateMismatchMaximum", ...
                singleTrackYawRateMismatchMaximum, ...
            "relation", ...
                "omegaE=VE*sin(betaE)/lrE+boundedMismatch"), ...
        "uniformCourseRadiusMaximum", yawUniformRadiusMaximum, ...
        "uniformCourseCertificate", courseUniformCertificate, ...
        "measurementMethod", ...
            "kinematic-sideslip-corrected-certified-correspondence", ...
        "courseErrorVectorRadius", velocityNoise, ...
        "disturbanceBound", yawDisturbance, ...
        "gainOptimization", yawGainSolution);
    design.velocity = struct( ...
        "gain", velocityGain, ...
        "lyapunovMatrix", velocityLyapunovMatrix, ...
        "lambda", velocityLambda, ...
        "gainConstant", 1.0, ...
        "disturbanceBound", velocityDisturbance, ...
        "gainOptimization", velocityGainSolution);
    design.position = struct( ...
        "gain", positionGain, ...
        "gainOptimization", positionGainSolution);
    design.target = struct( ...
        "shape", targetCertificate.shape, ...
        "shapeConstruction", targetCertificate.construction, ...
        "bandwidth", targetBandwidth, ...
        "injectionVector", targetInjectionVector, ...
        "innovationGains", [ ...
            targetInjectionVector(1)*targetBandwidth; ...
            targetInjectionVector(2)*targetBandwidth^2; ...
            targetInjectionVector(3)*targetBandwidth^3], ...
        "closedLoopMatrix", targetClosedLoopMatrix, ...
        "closedLoopPoles", targetCertificate.closedLoopPoles, ...
        "normalizedDecayRate", ...
            targetCertificate.normalizedDecayRate, ...
        "domainTransitDecayRate", ...
            targetCertificate.domainTransitDecayRate, ...
        "designLyapunovMatrix", ...
            targetCertificate.designLyapunovMatrix, ...
        "lyapunovMatrix", targetLyapunovMatrix, ...
        "eigenvalueMinimum", targetEigMinimum, ...
        "eigenvalueMaximum", targetEigMaximum, ...
        "lambda", targetLambda, ...
        "gainConstant", targetGainConstant, ...
        "thresholdConstant", targetCertificate.thresholdConstant, ...
        "certificateResidualMargin", targetCertificate.residualMargin, ...
        "shapeObjectiveValue", targetCertificate.designObjectiveValue, ...
        "certificateObjectiveValue", ...
            targetCertificate.ultimateObjectiveValue, ...
        "initialLyapunovBound", ...
            targetCertificate.initialLyapunovBound, ...
        "transitLyapunovBound", ...
            targetCertificate.transitLyapunovBound, ...
        "normalizedComponentBounds", ...
            targetCertificate.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", ...
            targetCertificate.bandwidthActiveConstraint, ...
        "bandwidthSearchBracket", ...
            targetCertificate.bandwidthSearchBracket, ...
        "inputScale", targetInputScale, ...
        "disturbanceBound", targetDisturbance, ...
        "lipschitzCertificate", struct( ...
            "scalarAccelerationVelocity", ...
                scalarAccelerationVelocityLipschitz, ...
            "scalarAccelerationAcceleration", ...
                scalarAccelerationAccelerationLipschitz, ...
            "yawRateVelocity", yawRateVelocityLipschitz, ...
            "yawRateAcceleration", yawRateAccelerationLipschitz, ...
            "phiVelocity", phiVelocityLipschitz, ...
            "phiAcceleration", phiAccelerationLipschitz, ...
            "phi", phiLipschitz, ...
            "minimumStabilityBandwidth", ...
                targetCertificate.thresholdConstant*phiLipschitz, ...
            "assignedBandwidth", targetBandwidth), ...
        "domain", struct( ...
            "speedMinimum", targetSpeedMinimum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "scalarAccelerationMaximum", targetAccelerationMaximum, ...
            "yawRateMaximum", targetYawRateMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "sideslipMaximum", targetSideslipMaximum, ...
            "rearAxleDistance", rearAxleDistance, ...
            "relativePositionMaximum", relativePositionMaximum));
    design.coupling = struct( ...
        "velocityYawCoupling", velocityYawCoupling, ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "feedforward", true);
    design.coreIss = coreCertificate;
    design.ultimateBounds = struct( ...
        "yaw", yawUltimate, ...
        "bodyVelocity", velocityUltimate, ...
        "position", positionUltimate, ...
        "targetLyapunov", targetUltimate, ...
        "relativePosition", relativePositionUltimate, ...
        "targetVelocity", targetVelocityUltimate, ...
        "targetAcceleration", targetAccelerationUltimate, ...
        "yawRate", gyroscopeNoise, ...
        "inertialVelocity", velocityUltimate ...
            + egoSpeedMaximum*yawUltimate, ...
        "targetPositionInertial", positionUltimate ...
            + relativePositionUltimate ...
            + relativePositionMaximum*yawUltimate, ...
        "targetVelocityInertial", targetVelocityUltimate ...
            + targetSpeedMaximum*yawUltimate, ...
        "targetAccelerationInertial", targetAccelerationUltimate ...
            + targetAccelerationNormBound*yawUltimate, ...
        "velocityDifference", targetVelocityUltimate+velocityUltimate, ...
        "accelerationDifference", targetAccelerationUltimate ...
            + velocityUltimate+accelerometerNoise);
    design.ultimateBounds.controllerRelativePosition = ...
        controllerRelativePositionUltimate;
    design.gainSelection = struct( ...
        "method", "certificate-normalized-minimax-synthesis", ...
        "scalarMethod", "closed-form-disturbance-innovation-balance", ...
        "domainTransitTime", domainTransitTime, ...
        "scalarGainBounds", scalarGainBounds, ...
        "scalarSampleProductBounds", scalarSampleProductBounds, ...
        "yawProgram", yawGainSolution, ...
        "velocityProgram", velocityGainSolution, ...
        "positionProgram", positionGainSolution, ...
        "achievedDecayRates", struct( ...
            "yaw", yawCorrectionBandwidth, ...
            "bodyVelocity", velocityLambda, ...
            "position", positionGain, ...
            "target", targetLambda), ...
        "targetShapeMethod", "normalized-observer-lmi", ...
        "targetBandwidthMethod", ...
            "transit-plus-ultimate-normalized-state-minimax", ...
        "targetBandwidth", targetBandwidth, ...
        "targetBandwidthSampleProduct", targetBandwidth*samplePeriod);
    design.operatingDomain = struct( ...
        "egoSpeedMinimum", egoSpeedMinimum, ...
        "egoSpeedMaximum", egoSpeedMaximum, ...
        "egoYawRateMaximum", egoYawRateMaximum, ...
        "measuredYawRateMaximum", measuredYawRateMaximum, ...
        "egoSideslipDomainMaximum", sideslipDomainMaximum, ...
        "egoSingleTrackYawRateMismatchMaximum", ...
            singleTrackYawRateMismatchMaximum, ...
        "target", design.target.domain, ...
        "containmentScope", ...
            "estimated runtime states and measured inputs only; " ...
            + "truth trajectories require offline audit");
end

function certificate = localUniformCourseRadius(speedMinimum, ...
        yawRateMaximum, rearAxleDistance, sideslipDomainMaximum, ...
        velocityNoise, gyroscopeNoise, modelMismatchMaximum)
% localUniformCourseRadius Lift the pointwise course proof to the domain.

    measuredSpeedMinimum = speedMinimum-velocityNoise;
    trueSpeedLowerBound = speedMinimum-2.0*velocityNoise;
    if trueSpeedLowerBound <= 0.0
        error("synthesizeNrmmObserverGains:uncertifiedCourseSpeed", ...
            "ego.domain.speedMinimum must exceed twice the GNSS velocity-error radius.");
    end
    measuredYawRateMaximum = yawRateMaximum+gyroscopeNoise;
    normalizedYawRateMaximum = rearAxleDistance ...
        * measuredYawRateMaximum/measuredSpeedMinimum;
    if normalizedYawRateMaximum >= 1.0
        error("synthesizeNrmmObserverGains:uncertifiedCourseInversion", ...
            "The declared ego domain cannot certify the course-channel asin inversion.");
    end
    directionRadius = asin(velocityNoise/measuredSpeedMinimum);
    speedContribution = rearAxleDistance*measuredYawRateMaximum ...
        * velocityNoise/(measuredSpeedMinimum*trueSpeedLowerBound);
    yawRateAndModelContribution = rearAxleDistance ...
        *(gyroscopeNoise+modelMismatchMaximum)/trueSpeedLowerBound;
    sineErrorMaximum = speedContribution+yawRateAndModelContribution;
    inverseDomainMaximum = max(sin(sideslipDomainMaximum), ...
        normalizedYawRateMaximum);
    inverseLipschitz = 1.0/sqrt(1.0-inverseDomainMaximum^2);
    sideslipErrorMaximum = inverseLipschitz*sineErrorMaximum;
    radius = directionRadius+sideslipErrorMaximum;
    if ~isfinite(radius) || radius >= pi
        error("synthesizeNrmmObserverGains:uncertifiedCourseRadius", ...
            "The declared domain does not yield a proper uniform course-yaw arc.");
    end
    certificate = struct( ...
        "radius", radius, ...
        "directionRadius", directionRadius, ...
        "sideslipErrorMaximum", sideslipErrorMaximum, ...
        "sineErrorMaximum", sineErrorMaximum, ...
        "speedErrorContribution", speedContribution, ...
        "yawRateAndModelContribution", ...
            yawRateAndModelContribution, ...
        "measuredSpeedMinimum", measuredSpeedMinimum, ...
        "trueSpeedLowerBound", trueSpeedLowerBound, ...
        "normalizedYawRateMaximum", normalizedYawRateMaximum, ...
        "inverseLipschitz", inverseLipschitz);
end

function [gain, solution] = localSolveScalarCorrectionGain( ...
        processBound, measurementEquivalentBound, samplePeriod, ...
        domainTransitTime, stage)
% localSolveScalarCorrectionGain Balance leakage against innovation.
%
% The bandwidth is the exact minimizer of
%
%   max(a/k, Ts*b*k),  1/Tdomain <= k <= 1/Ts,
%
% persistent-disturbance leakage against the largest one-sample innovation
% displacement, whose unconstrained balance point is k = sqrt(a/(Ts*b)).
% A vanishing coefficient activates the corresponding endpoint (a = 0:
% minimum decay, b = 0: one-sample correction), and exact data a = b = 0
% takes the minimum-decay tie-break.

    lowerSampleProduct = samplePeriod/domainTransitTime;
    upperSampleProduct = 1.0;
    if lowerSampleProduct > upperSampleProduct
        error("synthesizeNrmmObserverGains:infeasibleScalarGainBounds", ...
            "The sample period exceeds the operating-domain transit time.");
    end
    lowerGain = 1.0/domainTransitTime;
    upperGain = 1.0/samplePeriod;
    if processBound > 0.0 && measurementEquivalentBound > 0.0
        unconstrainedOptimum = sqrt(processBound ...
            /(samplePeriod*measurementEquivalentBound));
    elseif processBound == 0.0 && measurementEquivalentBound > 0.0
        unconstrainedOptimum = 0.0;
    elseif processBound > 0.0
        unconstrainedOptimum = Inf;
    else
        unconstrainedOptimum = NaN;
    end
    if isnan(unconstrainedOptimum)
        gain = lowerGain;
    else
        gain = min(max(unconstrainedOptimum, lowerGain), upperGain);
    end
    sampleProduct = gain*samplePeriod;
    disturbanceContribution = processBound/gain;
    innovationContribution = samplePeriod ...
        * measurementEquivalentBound*gain;
    balanceTolerance = 1.0e-7*max(1.0, ...
        max(disturbanceContribution, innovationContribution));
    if isfinite(unconstrainedOptimum) && gain > lowerGain ...
            && gain < upperGain ...
            && abs(disturbanceContribution-innovationContribution) ...
                > balanceTolerance
        error("synthesizeNrmmObserverGains:invalidScalarGainSolution", ...
            "The recovered %s gain failed its a-posteriori certificate.", ...
            stage);
    end
    boundTolerance = 1.0e-7*max(1.0, sampleProduct);
    if abs(sampleProduct-lowerSampleProduct) <= boundTolerance
        activeConstraint = "domain-transit-decay";
    elseif abs(sampleProduct-upperSampleProduct) <= boundTolerance
        activeConstraint = "one-sample-correction";
    else
        activeConstraint = "disturbance-innovation-balance";
    end
    solution = struct( ...
        "stage", stage, ...
        "method", "closed-form-disturbance-innovation-balance", ...
        "processBound", processBound, ...
        "measurementEquivalentBound", measurementEquivalentBound, ...
        "unconstrainedOptimum", unconstrainedOptimum, ...
        "sampleProduct", sampleProduct, ...
        "sampleProductBounds", ...
            [lowerSampleProduct, upperSampleProduct], ...
        "disturbanceContribution", disturbanceContribution, ...
        "innovationContribution", innovationContribution, ...
        "objectiveValue", max(disturbanceContribution, ...
            innovationContribution), ...
        "activeConstraint", activeConstraint);
end

function localAssertVelocityCertificate(velocityGain, yawRateBound, lambda)
% localAssertVelocityCertificate Verify P = I certifies the decay rate.
%
% The claim A_v(u3)' + A_v(u3) = -2*lambda*I is an identity in u3, not a
% numerical solution, but it is the load-bearing step of the velocity
% stage, so it is checked at both interval vertices before use.

    planarCross = [0.0, -1.0; 1.0, 0.0];
    for vertex = [-yawRateBound, yawRateBound]
        systemMatrix = -velocityGain*eye(2)-vertex*planarCross;
        residual = systemMatrix.'+systemMatrix+2.0*lambda*eye(2);
        if max(abs(residual), [], "all") > 128.0*eps(max(1.0, lambda))
            error("synthesizeNrmmObserverGains:invalidVelocityCertificate", ...
                "P = I must certify the velocity decay rate exactly.");
        end
    end
end

function value = localPositive(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value <= 0.0
        error("synthesizeNrmmObserverGains:invalidPositiveScalar", ...
            "%s must be a finite positive scalar.", strjoin(path, "."));
    end
end

function value = localNonnegative(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value < 0.0
        error("synthesizeNrmmObserverGains:invalidNonnegativeScalar", ...
            "%s must be a finite nonnegative scalar.", strjoin(path, "."));
    end
end

function value = localField(cfg, path)
    value = cfg;
    for fieldIdx = 1:numel(path)
        fieldName = char(path(fieldIdx));
        if ~isstruct(value) || ~isfield(value, fieldName) ...
                || isempty(value.(fieldName))
            error("synthesizeNrmmObserverGains:missingConfiguration", ...
                "%s is required.", strjoin(path, "."));
        end
        value = value.(fieldName);
    end
end

function localAddProjectPaths()
    estimatorRoot = fileparts(mfilename("fullpath"));
    repoRoot = fileparts(estimatorRoot);
    addpath(fullfile(repoRoot, "config"));
    addpath(estimatorRoot);
end
