function certificate = synthesizeTargetTrackerCertificate( ...
        lipschitz, chain, domainTransitTime)
% synthesizeTargetTrackerCertificate Retain the high-gain chain and certify it.
%
% One LMI in the gains and a metric selects l: among gains that satisfy the
% Lipschitz dissipation inequality at the required decay it minimizes a
% bound on the variance that white output noise leaves in the velocity
% error. At each candidate physical bandwidth, a second LMI selects a free
% Lyapunov metric and two Lipschitz multipliers.
% The physical gains remain [l1*w;l2*w^2;l3*w^3].
% Separate global Lipschitz channels Lq and Ls enter a two-multiplier
% dissipation inequality after scaling z=[eRho;eQ/w;eS/w^2].
%
% The bandwidth objective is the largest domain-normalized ultimate
% component bound, subject to a guaranteed decay rate of at least the
% inverse domain transit time. That decay preference is explicit; it is
% not imposed by the ISS theorem. The noise variance is a performance
% preference among certified gains; it is not a deterministic error bound.
% Numerical searches return a feasible, independently checked certificate,
% without a global optimization claim.

    arguments
        lipschitz (1, 1) struct
        chain (1, 1) struct
        domainTransitTime (1, 1) double {mustBePositive, mustBeFinite}
    end
    validateattributes(lipschitz.phiVelocity,{'double'}, ...
        {'scalar','finite','positive'});
    validateattributes(lipschitz.phiAcceleration,{'double'}, ...
        {'scalar','finite','positive'});

    chain = localValidatedChain(chain);
    chainMatrix = [0.0, 1.0, 0.0; 0.0, 0.0, 1.0; 0.0, 0.0, 0.0];
    outputVector = [1.0; 0.0; 0.0];
    unitVector = [0.0; 0.0; 1.0];
    normalizedDecayRate = 1.0;

    localPrepareSolver();
    domainTransitDecayRate = 1.0/domainTransitTime;
    [injectionVector, shape] = localSolveNoiseShape(chainMatrix, ...
        outputVector, unitVector, lipschitz, domainTransitDecayRate);
    closedLoopMatrix = chainMatrix-injectionVector*outputVector.';
    [bound, lyapunovMatrix] = localOptimizeBandwidth(closedLoopMatrix, ...
        injectionVector, lipschitz, chain, unitVector, domainTransitTime);
    construction = ...
        "noise-variance-lipschitz-lmi-plus-free-metric-lipschitz-iss";

    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    lyapunovResidual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix;
    lyapunovEigenvalues = eig(lyapunovMatrix);
    residualMargin = -max(eig( ...
        (lyapunovResidual+lyapunovResidual.')/2.0));
    if min(lyapunovEigenvalues) <= 0.0 || residualMargin < -1.0e-8
        error("synthesizeTargetTrackerCertificate:invalidCertificate", ...
            "The selected target shape lacks a valid Lyapunov certificate.");
    end

    closedLoopPoles = sort(eig(closedLoopMatrix));
    if max(real(closedLoopPoles)) ...
            > -normalizedDecayRate*(1.0-1.0e-6)
        error("synthesizeTargetTrackerCertificate:invalidNormalizedDecay", ...
            "The normalized target shape must lie at or left of Re(s)=-1.");
    end

    certificate = struct( ...
        "shape", "lmi-solved", ...
        "construction", construction, ...
        "injectionVector", injectionVector, ...
        "closedLoopMatrix", closedLoopMatrix, ...
        "closedLoopPoles", closedLoopPoles, ...
        "normalizedDecayRate", normalizedDecayRate, ...
        "designLyapunovMatrix", shape.lyapunovMatrix, ...
        "designObjectiveValue", shape.objective, ...
        "designBandwidth", shape.bandwidth, ...
        "designLipschitzMultipliers", shape.multipliers, ...
        "lyapunovMatrix", lyapunovMatrix, ...
        "thresholdConstant", 2*norm(lyapunovMatrix*unitVector), ...
        "minimumDecayRate", 1/domainTransitTime, ...
        "lipschitzMultipliers", bound.multipliers, ...
        "lipschitzDissipationMatrix", bound.dissipationMatrix, ...
        "lipschitzResidualMargin", bound.lipschitzResidualMargin, ...
        "componentConversion", bound.componentConversion, ...
        "disturbanceCoefficients", bound.disturbanceCoefficients, ...
        "eigenvalueMinimum", min(lyapunovEigenvalues), ...
        "eigenvalueMaximum", max(lyapunovEigenvalues), ...
        "domainTransitDecayRate", domainTransitDecayRate, ...
        "lambda", bound.lambda, ...
        "bandwidth", bound.bandwidth, ...
        "gainConstant", bound.gainConstant, ...
        "inputScale", bound.inputScale, ...
        "velocityCoupling", bound.velocityCoupling, ...
        "disturbanceBound", bound.disturbanceBound, ...
        "targetUltimate", bound.targetUltimate, ...
        "initialLyapunovBound", bound.initialLyapunovBound, ...
        "transitLyapunovBound", bound.transitLyapunovBound, ...
        "relativePositionUltimate", bound.relativePositionUltimate, ...
        "targetVelocityUltimate", bound.targetVelocityUltimate, ...
        "targetAccelerationUltimate", ...
            bound.targetAccelerationUltimate, ...
        "normalizedComponentBounds", ...
            bound.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", bound.activeConstraint, ...
        "bandwidthSearchBracket", bound.searchBracket, ...
        "residualMargin", residualMargin, ...
        "ultimateObjectiveValue", bound.objectiveValue);
end

function chain = localValidatedChain(chain)
    positiveFields = ["relativePositionMaximum", "speedMaximum", ...
        "accelerationNormBound"];
    nonnegativeFields = ["velocityUltimate", ...
        "gyroscopeNoiseMaximum", "radarNoiseMaximum", "modelJerkMaximum"];
    for fieldName = positiveFields
        chain.(fieldName) = localScalarField(chain, fieldName, true);
    end
    for fieldName = nonnegativeFields
        chain.(fieldName) = localScalarField(chain, fieldName, false);
    end
end

function value = localScalarField(input, fieldName, positive)
    if ~isfield(input, fieldName)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s is required.", fieldName);
    end
    value = double(input.(fieldName));
    if ~isscalar(value) || ~isfinite(value)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
    invalidSign = value < 0.0 || (positive && value <= 0.0);
    if invalidSign
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
end

function [injectionVector, shape] = localSolveNoiseShape( ...
        chainMatrix, outputVector, unitVector, lipschitz, decayRate)
% localSolveNoiseShape Minimize output-noise velocity variance among certified gains.
%
% With Y = P*L the Lipschitz dissipation inequality at the required decay
% and the observability-Gramian inequality of the map from output noise to
% velocity error are jointly linear in P, Y and the multipliers, and L'*P*L
% bounds the squared H2 norm of that map. One metric serves both
% inequalities, so the optimum is an upper bound and the gains it returns
% already admit a certificate. They are returned as a shape with unit
% slowest rate; shape.bandwidth is that rate and the metric is physical.

    velocitySelector = diag([0.0, 1.0, 0.0]);
    sensitivities = [lipschitz.phiVelocity; lipschitz.phiAcceleration];
    metricVariable = sdpvar(3, 3);
    gainVariable = sdpvar(3, 1);
    multiplierVariable = sdpvar(2, 1);
    varianceVariable = sdpvar(1, 1);
    margin = 1.0e-7;
    weighted = metricVariable*chainMatrix-gainVariable*outputVector.';
    derivative = weighted+weighted.';
    direction = metricVariable*unitVector;
    dissipation = [derivative+2.0*decayRate*metricVariable ...
            + diag([0.0; multiplierVariable.*sensitivities.^2]), ...
            direction, direction; ...
        direction.', -multiplierVariable(1), 0.0; ...
        direction.', 0.0, -multiplierVariable(2)];
    constraints = [ ...
        metricVariable >= margin*eye(3), ...
        multiplierVariable >= margin, ...
        dissipation <= -margin*eye(5), ...
        derivative+velocitySelector <= -margin*eye(3), ...
        [varianceVariable, gainVariable.'; gainVariable, metricVariable] >= 0];
    diagnostics = optimize(constraints, varianceVariable, ...
        localSolverOptions());
    if diagnostics.problem ~= 0
        error("synthesizeTargetTrackerCertificate:infeasibleShape", ...
            "The target noise-shape LMI failed: %s", diagnostics.info);
    end

    metric = value(metricVariable);
    metric = (metric+metric.')/2.0;
    multipliers = value(multiplierVariable);
    gains = metric\value(gainVariable);
    physicalMatrix = chainMatrix-gains*outputVector.';
    derivative = physicalMatrix.'*metric+metric*physicalMatrix;
    direction = metric*unitVector;
    dissipationResidual = derivative+2.0*decayRate*metric ...
        + diag([0.0; multipliers.*sensitivities.^2]) ...
        + sum(1.0./multipliers)*(direction*direction.');
    gramianResidual = derivative+velocitySelector;
    rates = -real(eig(physicalMatrix));
    if any(~isfinite(gains)) || min(eig(metric)) <= 0.0 ...
            || any(multipliers <= 0.0) || min(rates) <= 0.0 ...
            || max(eig((dissipationResidual ...
                + dissipationResidual.')/2.0)) > 1.0e-8 ...
            || max(eig((gramianResidual+gramianResidual.')/2.0)) > 1.0e-8
        error("synthesizeTargetTrackerCertificate:invalidShapeSolution", ...
            "The recovered target noise shape failed certification.");
    end
    bandwidth = min(rates);
    injectionVector = gains./[bandwidth; bandwidth^2; bandwidth^3];
    shape = struct("lyapunovMatrix", metric, "multipliers", multipliers, ...
        "bandwidth", bandwidth, "objective", gains.'*metric*gains);
end

function [bestBound, metric] = localOptimizeBandwidth(closedLoopMatrix, ...
        injectionVector, lipschitz, chain, unitVector, domainTransitTime)
% Re-solve the metric at each bandwidth; do not constrain A'P+PA to -I.

    requiredRate = 1/domainTransitTime;
    disturbancePresent = chain.velocityUltimate > 0 ...
        || chain.gyroscopeNoiseMaximum > 0 || chain.radarNoiseMaximum > 0 ...
        || chain.modelJerkMaximum > 0;
    evaluate = @(bandwidth) localTargetBound(bandwidth,closedLoopMatrix, ...
        injectionVector,lipschitz,chain,unitVector,domainTransitTime);
    objective = @(bandwidth) localTargetObjective(bandwidth,evaluate,disturbancePresent);
    grid = 1+1e-6;
    values = objective(grid);
    % Bracket a feasible local minimum without asserting global optimality.
    for iteration = 1:20
        grid(end+1) = 2*grid(end); %#ok<AGROW>
        values(end+1) = objective(grid(end)); %#ok<AGROW>
        [bestValue,index] = min(values);
        if isfinite(bestValue) && index < numel(grid)
            break
        end
    end
    if ~isfinite(bestValue) || index == numel(grid)
        error("synthesizeTargetTrackerCertificate:unboundedBandwidthSearch", ...
            "Could not bracket a certified finite bandwidth minimum.");
    end
    searchBracket = [grid(max(1,index-1)),grid(index+1)];
    interior = fminbnd(objective,searchBracket(1),searchBracket(2), ...
        optimset("Display","off","TolX",1e-5));
    candidates = [grid(index),interior,searchBracket];
    [~,index] = min(arrayfun(objective,candidates));
    bestBound = evaluate(candidates(index));
    if ~isfield(bestBound,"lambda") || bestBound.lambda < requiredRate
        error("synthesizeTargetTrackerCertificate:invalidDecay", ...
            "The selected target gains lack the required decay certificate.");
    end
    metric = bestBound.lyapunovMatrix;
    if disturbancePresent
        bestBound.activeConstraint = "normalized-ultimate-state-bound";
    else
        bestBound.activeConstraint = "domain-transit-decay";
    end
    bestBound.searchBracket = searchBracket;
end

function objective = localTargetObjective(bandwidth,evaluate,disturbancePresent)
    bound = evaluate(bandwidth);
    objective = bound.objectiveValue;
    if ~disturbancePresent && isfinite(objective)
        objective = bandwidth;
    end
end

function bound = localTargetBound(bandwidth,closedLoopMatrix, ...
        injectionVector,lipschitz,chain,unitVector,domainTransitTime)
% localTargetBound Use the metric's actual input and output directions.

    lambda = 1/domainTransitTime;
    [lyapunovMatrix,multipliers,dissipationMatrix] = localSolveMetric( ...
        bandwidth,closedLoopMatrix,lipschitz,unitVector,lambda);
    if isempty(lyapunovMatrix)
        bound = struct("objectiveValue",Inf);
        return
    end
    scale = [1;1/bandwidth;1/bandwidth^2];
    physicalBounds = [chain.relativePositionMaximum;chain.speedMaximum; ...
        chain.accelerationNormBound];
    scaledBounds = scale.*physicalBounds;
    gyroCoefficient = sqrt(scaledBounds.'*abs(lyapunovMatrix)*scaledBounds);
    velocityCoupling = sqrt(lyapunovMatrix(1,1));
    radarCoefficient = bandwidth ...
        *sqrt(injectionVector.'*lyapunovMatrix*injectionVector);
    modelCoefficient = sqrt(lyapunovMatrix(3,3))/bandwidth^2;
    disturbanceBound = gyroCoefficient*chain.gyroscopeNoiseMaximum ...
        +radarCoefficient*chain.radarNoiseMaximum ...
        +modelCoefficient*chain.modelJerkMaximum;
    targetUltimate = (velocityCoupling*chain.velocityUltimate ...
        +disturbanceBound)/lambda;
    inverseMetric = lyapunovMatrix\eye(3);
    componentConversion = sqrt(diag(inverseMetric))./scale;
    ultimate = componentConversion*targetUltimate;
    initialLyapunovBound = 2*sqrt(scaledBounds.'*abs(lyapunovMatrix)*scaledBounds);
    transitLyapunovBound = exp(-lambda*domainTransitTime) ...
        *initialLyapunovBound+targetUltimate;
    normalizedComponentBounds = ultimate./physicalBounds;
    residualMargin = min(eig((dissipationMatrix+dissipationMatrix.')/2));
    if ~isfinite(residualMargin) || residualMargin < -1e-8
        error("synthesizeTargetTrackerCertificate:invalidLipschitzCertificate", ...
            "The structured Lipschitz dissipation inequality failed verification.");
    end
    bound = struct("bandwidth",bandwidth,"lambda",lambda, ...
        "lyapunovMatrix",lyapunovMatrix, ...
        "multipliers",multipliers,"dissipationMatrix",dissipationMatrix, ...
        "lipschitzResidualMargin",residualMargin, ...
        "gainConstant",sqrt(max(eig(lyapunovMatrix))), ...
        "inputScale",gyroCoefficient,"velocityCoupling",velocityCoupling, ...
        "disturbanceCoefficients",struct("gyro",gyroCoefficient, ...
            "radar",radarCoefficient,"modelJerk",modelCoefficient), ...
        "disturbanceBound",disturbanceBound,"targetUltimate",targetUltimate, ...
        "componentConversion",componentConversion, ...
        "initialLyapunovBound",initialLyapunovBound, ...
        "transitLyapunovBound",transitLyapunovBound, ...
        "relativePositionUltimate",ultimate(1), ...
        "targetVelocityUltimate",ultimate(2), ...
        "targetAccelerationUltimate",ultimate(3), ...
        "normalizedComponentBounds",normalizedComponentBounds, ...
        "objectiveValue",max(normalizedComponentBounds));
end

function [metric,multipliers,residual] = localSolveMetric( ...
        bandwidth,closedLoopMatrix,lipschitz,unitVector,lambda)
% A free metric reduces conservatism while retaining the same decay floor.
% The Schur complement bounds the two independent Lipschitz channels.
% P >= I fixes homogeneous scaling; trace(P) prefers a compact metric.

    metricVariable = sdpvar(3,3);
    multiplierVariable = sdpvar(2,1);
    sensitivities = [lipschitz.phiVelocity/bandwidth;lipschitz.phiAcceleration];
    weighted = bandwidth*(closedLoopMatrix.'*metricVariable ...
        +metricVariable*closedLoopMatrix)+2*lambda*metricVariable ...
        +diag([0;multiplierVariable.*sensitivities.^2]);
    direction = metricVariable*unitVector;
    block = [weighted,direction,direction; ...
        direction.',-multiplierVariable(1),0; ...
        direction.',0,-multiplierVariable(2)];
    margin = 1e-6;
    diagnostics = optimize([metricVariable >= eye(3), ...
        multiplierVariable >= margin,block <= -margin*eye(5)], ...
        trace(metricVariable),localSolverOptions());
    metric = [];
    multipliers = [];
    residual = [];
    % Infeasible or numerically unresolved points cannot certify a candidate.
    if diagnostics.problem ~= 0
        return
    end
    candidate = value(metricVariable);
    candidate = (candidate+candidate.')/2;
    multipliers = value(multiplierVariable);
    if any(~isfinite(candidate),"all") || any(~isfinite(multipliers)) ...
            || min(eig(candidate)) < 1-1e-7 || any(multipliers <= 0)
        return
    end
    direction = candidate*unitVector;
    residual = -bandwidth*(closedLoopMatrix.'*candidate ...
        +candidate*closedLoopMatrix)-2*lambda*candidate ...
        -diag([0;multipliers.*sensitivities.^2]) ...
        -sum(1./multipliers)*(direction*direction.');
    residual = (residual+residual.')/2;
    if any(~isfinite(residual),"all") || min(eig(residual)) < -1e-8
        return
    end
    metric = candidate;
end

function localPrepareSolver()
% localPrepareSolver Put the vendored YALMIP and SeDuMi trees on the path.

    if ~isempty(which("optimize")) && ~isempty(which("sedumi"))
        return
    end
    estimatorRoot = fileparts(mfilename("fullpath"));
    solverRoot = fullfile(fileparts(estimatorRoot), "solver");
    yalmipRoot = fullfile(solverRoot, "YALMIP");
    sedumiRoot = fullfile(solverRoot, "sedumi");
    if ~isfolder(yalmipRoot) || ~isfolder(sedumiRoot)
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "The optimized target shape requires YALMIP and SeDuMi in %s.", ...
            solverRoot);
    end
    addpath(genpath(yalmipRoot));
    addpath(genpath(sedumiRoot));
    if isempty(which("optimize")) || isempty(which("sedumi"))
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "YALMIP and SeDuMi were found in %s but did not load.", ...
            solverRoot);
    end
end

function options = localSolverOptions()
% localSolverOptions Deterministic YALMIP settings.

    options = sdpsettings('solver', 'sedumi', 'verbose', 0, ...
        'cachesolvers', 1, 'warning', 0);
end
