function certificate = synthesizeTargetTrackerCertificate( ...
        phiLipschitz, chain, domainTransitTime)
% synthesizeTargetTrackerCertificate Solve and certify the target gains.
%
% The normalized covariant chain has A(l) = Ac-l*e1'. Its injection shape
% is recovered from the Sharma-type observer LMI
%
%   P >= I,
%   He(P*Ac-R*e1')+2*P < 0,
%
% by l = P\R, while a bounded-real block minimizes the normalized
% measurement-noise-to-chain-state H-infinity gain. The normalized decay
% region is fixed at Re(s) <= -1, so the LMI selects shape rather than
% physical speed. For that solved shape, the unique identity
% A(l)'*P0+P0*A(l) = -I removes certificate scaling as a second design
% choice.
%
% The physical bandwidth is also solved rather than requested. Over the
% open nonlinear-stability region, a scalar minimax program minimizes the
% largest normalized rho-, q-, and s-bound obtained by adding the
% domain-transit transient to the ultimate disturbance radius. The
% domain-transit rate is only a tie-break in the exact-data case, where the
% disturbance objective has no finite high-bandwidth minimizer. Thus every
% target gain [l1*w; l2*w^2; l3*w^3] follows from an LMI, a Lyapunov
% equation, and a certificate objective; no pole shape, target decay rate,
% or physical bandwidth is entered by the user.

    arguments
        phiLipschitz (1, 1) double {mustBePositive, mustBeFinite}
        chain (1, 1) struct
        domainTransitTime (1, 1) double {mustBePositive, mustBeFinite}
    end

    chain = localValidatedChain(chain);
    chainMatrix = [0.0, 1.0, 0.0; 0.0, 0.0, 1.0; 0.0, 0.0, 0.0];
    outputVector = [1.0; 0.0; 0.0];
    unitVector = [0.0; 0.0; 1.0];
    normalizedDecayRate = 1.0;

    localPrepareSolver();
    [injectionVector, designMatrix, designObjective] = ...
        localSolveNormalizedShape( ...
            chainMatrix, outputVector, normalizedDecayRate);
    closedLoopMatrix = chainMatrix-injectionVector*outputVector.';
    lyapunovMatrix = localSolveLyapunovIdentity(closedLoopMatrix);
    domainTransitDecayRate = 1.0/domainTransitTime;
    bound = localOptimizeBandwidth(lyapunovMatrix, injectionVector, ...
        phiLipschitz, chain, unitVector, domainTransitTime);
    construction = ...
        "normalized-observer-lmi-plus-certificate-minimax";

    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    lyapunovResidual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix+eye(3);
    lyapunovEigenvalues = eig(lyapunovMatrix);
    residualMargin = -max(eig( ...
        (lyapunovResidual+lyapunovResidual.')/2.0));
    if min(lyapunovEigenvalues) <= 0.0 || residualMargin < -1.0e-8
        error("synthesizeTargetTrackerCertificate:invalidCertificate", ...
            "The selected target shape lacks a valid Lyapunov certificate.");
    end

    closedLoopPoles = sort(eig(closedLoopMatrix));
    if max(real(closedLoopPoles)) ...
            > -normalizedDecayRate*(1.0-1.0e-6)
        error("synthesizeTargetTrackerCertificate:invalidNormalizedDecay", ...
            "The normalized target shape must lie at or left of Re(s)=-1.");
    end

    certificate = struct( ...
        "shape", "lmi-solved", ...
        "construction", construction, ...
        "injectionVector", injectionVector, ...
        "closedLoopMatrix", closedLoopMatrix, ...
        "closedLoopPoles", closedLoopPoles, ...
        "normalizedDecayRate", normalizedDecayRate, ...
        "designLyapunovMatrix", designMatrix, ...
        "designObjectiveValue", designObjective, ...
        "lyapunovMatrix", lyapunovMatrix, ...
        "thresholdConstant", bound.thresholdConstant, ...
        "eigenvalueMinimum", min(lyapunovEigenvalues), ...
        "eigenvalueMaximum", max(lyapunovEigenvalues), ...
        "domainTransitDecayRate", domainTransitDecayRate, ...
        "lambda", bound.lambda, ...
        "bandwidth", bound.bandwidth, ...
        "gainConstant", bound.gainConstant, ...
        "inputScale", bound.inputScale, ...
        "velocityCoupling", bound.velocityCoupling, ...
        "disturbanceBound", bound.disturbanceBound, ...
        "targetUltimate", bound.targetUltimate, ...
        "initialLyapunovBound", bound.initialLyapunovBound, ...
        "transitLyapunovBound", bound.transitLyapunovBound, ...
        "relativePositionUltimate", bound.relativePositionUltimate, ...
        "targetVelocityUltimate", bound.targetVelocityUltimate, ...
        "targetAccelerationUltimate", ...
            bound.targetAccelerationUltimate, ...
        "normalizedComponentBounds", ...
            bound.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", bound.activeConstraint, ...
        "bandwidthSearchBracket", bound.searchBracket, ...
        "residualMargin", residualMargin, ...
        "ultimateObjectiveValue", bound.objectiveValue);
end

function chain = localValidatedChain(chain)
    positiveFields = ["relativePositionMaximum", "speedMaximum", ...
        "accelerationNormBound"];
    nonnegativeFields = ["velocityUltimate", ...
        "gyroscopeNoiseMaximum", "radarNoiseMaximum"];
    for fieldName = positiveFields
        chain.(fieldName) = localScalarField(chain, fieldName, true);
    end
    for fieldName = nonnegativeFields
        chain.(fieldName) = localScalarField(chain, fieldName, false);
    end
end

function value = localScalarField(input, fieldName, positive)
    if ~isfield(input, fieldName)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s is required.", fieldName);
    end
    value = double(input.(fieldName));
    if ~isscalar(value) || ~isfinite(value)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
    invalidSign = value < 0.0 || (positive && value <= 0.0);
    if invalidSign
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
end

function [injectionVector, lyapunovMatrix, objective] = ...
        localSolveNormalizedShape(chainMatrix, outputVector, decayRate)
% localSolveNormalizedShape Minimize normalized noise-to-state H-infinity gain.

    lyapunovVariable = sdpvar(3, 3);
    injectionVariable = sdpvar(3, 1);
    boundedRealVariable = sdpvar(1, 1);
    margin = 1.0e-6;
    weighted = lyapunovVariable*chainMatrix ...
        - injectionVariable*outputVector.';
    boundedRealMatrix = [ ...
        weighted+weighted.'+eye(3), -injectionVariable; ...
        -injectionVariable.', -boundedRealVariable];
    constraints = [ ...
        lyapunovVariable >= eye(3), ...
        weighted+weighted.'+2.0*decayRate*lyapunovVariable ...
            <= -margin*eye(3), ...
        boundedRealVariable >= 0.0, ...
        boundedRealMatrix <= -margin*eye(4)];
    diagnostics = optimize(constraints, boundedRealVariable, ...
        localSolverOptions());
    if diagnostics.problem ~= 0
        error("synthesizeTargetTrackerCertificate:infeasibleShape", ...
            "The normalized target-shape LMI failed: %s", ...
            diagnostics.info);
    end

    lyapunovMatrix = value(lyapunovVariable);
    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    injectionVector = lyapunovMatrix\value(injectionVariable);
    closedLoopMatrix = ...
        chainMatrix-injectionVector*outputVector.';
    regionResidual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix ...
        + 2.0*decayRate*lyapunovMatrix;
    boundedRealResidual = [ ...
        closedLoopMatrix.'*lyapunovMatrix ...
            + lyapunovMatrix*closedLoopMatrix+eye(3), ...
            -lyapunovMatrix*injectionVector; ...
        -injectionVector.'*lyapunovMatrix, ...
            -value(boundedRealVariable)];
    if min(eig(lyapunovMatrix)) < 1.0-1.0e-7 ...
            || max(eig((regionResidual+regionResidual.')/2.0)) > 1.0e-7 ...
            || max(eig((boundedRealResidual ...
                + boundedRealResidual.')/2.0)) > 1.0e-7
        error("synthesizeTargetTrackerCertificate:invalidShapeSolution", ...
            "The recovered normalized target shape failed certification.");
    end
    objective = value(boundedRealVariable);
end

function lyapunovMatrix = localSolveLyapunovIdentity(closedLoopMatrix)
% localSolveLyapunovIdentity Fix the certificate by A'P+PA=-I.

    stateDimension = size(closedLoopMatrix, 1);
    identity = eye(stateDimension);
    lyapunovOperator = kron(identity, closedLoopMatrix.') ...
        + kron(closedLoopMatrix.', identity);
    vectorizedMatrix = -lyapunovOperator\identity(:);
    lyapunovMatrix = reshape( ...
        vectorizedMatrix, stateDimension, stateDimension);
    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    residual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix+identity;
    tolerance = 1024.0*eps(max(1.0, norm(lyapunovMatrix)));
    if min(eig(lyapunovMatrix)) <= 0.0 ...
            || max(abs(residual), [], "all") > tolerance
        error("synthesizeTargetTrackerCertificate:invalidLyapunovIdentity", ...
            "The solved target shape did not yield a valid unique certificate.");
    end
end

function bestBound = localOptimizeBandwidth(lyapunovMatrix, ...
        injectionVector, phiLipschitz, chain, unitVector, ...
        domainTransitTime)
% localOptimizeBandwidth Minimize transit-plus-ultimate state bounds.

    eigenvalueMaximum = max(eig(lyapunovMatrix));
    thresholdConstant = 2.0*norm(lyapunovMatrix*unitVector);
    stabilityThreshold = thresholdConstant*phiLipschitz;
    strictMargin = max(1.0e-8*max(1.0, stabilityThreshold), ...
        1024.0*eps(max(1.0, stabilityThreshold)));
    lowerBandwidth = stabilityThreshold+strictMargin;
    objective = @(bandwidth) localTargetObjective( ...
        bandwidth, lyapunovMatrix, injectionVector, ...
        phiLipschitz, chain, unitVector, domainTransitTime);

    disturbancePresent = chain.velocityUltimate > 0.0 ...
        || chain.gyroscopeNoiseMaximum > 0.0 ...
        || chain.radarNoiseMaximum > 0.0;
    if ~disturbancePresent
        bestBandwidth = stabilityThreshold ...
            + 2.0*eigenvalueMaximum/domainTransitTime;
        searchBracket = [bestBandwidth, bestBandwidth];
    else
        grid = lowerBandwidth*2.0.^(0:20);
        values = arrayfun(objective, grid);
        [~, gridMinimum] = min(values);
        if gridMinimum == numel(grid)
            error("synthesizeTargetTrackerCertificate:unboundedBandwidthSearch", ...
                "The target minimax bandwidth search failed to bracket a minimum.");
        end
        lowerIndex = max(1, gridMinimum-1);
        upperIndex = gridMinimum+1;
        searchBracket = [grid(lowerIndex), grid(upperIndex)];
        options = optimset("Display", "off", "TolX", ...
            1.0e-10*max(1.0, lowerBandwidth));
        interiorBandwidth = fminbnd( ...
            objective, searchBracket(1), searchBracket(2), options);
        candidates = unique([lowerBandwidth, interiorBandwidth, ...
            searchBracket]);
        candidateValues = arrayfun(objective, candidates);
        [~, bestIndex] = min(candidateValues);
        bestBandwidth = candidates(bestIndex);
    end

    bestBound = localTargetBound(bestBandwidth, lyapunovMatrix, ...
        injectionVector, phiLipschitz, chain, unitVector, ...
        domainTransitTime);
    activeTolerance = 1.0e-8*max(1.0, lowerBandwidth);
    if abs(bestBandwidth-lowerBandwidth) <= activeTolerance
        bestBound.activeConstraint = "nonlinear-stability";
    elseif ~disturbancePresent
        bestBound.activeConstraint = "exact-data-domain-transit-tie-break";
    else
        bestBound.activeConstraint = "normalized-state-minimax";
    end
    bestBound.searchBracket = searchBracket;
end

function objectiveValue = localTargetObjective(bandwidth, ...
        lyapunovMatrix, injectionVector, phiLipschitz, chain, unitVector, ...
        domainTransitTime)
% localTargetObjective Return the dimensionless worst component bound.

    bound = localTargetBound(bandwidth, lyapunovMatrix, ...
        injectionVector, phiLipschitz, chain, unitVector, ...
        domainTransitTime);
    objectiveValue = bound.objectiveValue;
end

function bound = localTargetBound(bandwidth, lyapunovMatrix, ...
        injectionVector, phiLipschitz, chain, unitVector, ...
        domainTransitTime)
% localTargetBound Evaluate the physical-bandwidth ISS bound exactly.

    eigenvalues = eig(lyapunovMatrix);
    eigenvalueMinimum = min(eigenvalues);
    eigenvalueMaximum = max(eigenvalues);
    thresholdConstant = 2.0*norm(lyapunovMatrix*unitVector);
    lambda = (bandwidth-thresholdConstant*phiLipschitz) ...
        / (2.0*eigenvalueMaximum);
    if ~isfinite(lambda) || lambda <= 0.0
        bound = struct("objectiveValue", Inf);
        return
    end
    gainConstant = eigenvalueMaximum/sqrt(eigenvalueMinimum);
    inputScale = sqrt( ...
        bandwidth^4*chain.relativePositionMaximum^2 ...
        + bandwidth^2*chain.speedMaximum^2 ...
        + chain.accelerationNormBound^2);
    velocityCoupling = gainConstant*bandwidth^2;
    disturbanceBound = gainConstant*( ...
        inputScale*chain.gyroscopeNoiseMaximum ...
        + norm(injectionVector)*bandwidth^3 ...
            * chain.radarNoiseMaximum);
    targetUltimate = (velocityCoupling*chain.velocityUltimate ...
        + disturbanceBound)/lambda;
    initialLyapunovBound = sqrt(eigenvalueMaximum)*sqrt( ...
        bandwidth^4*(2.0*chain.relativePositionMaximum)^2 ...
        + bandwidth^2*(2.0*chain.speedMaximum)^2 ...
        + (2.0*chain.accelerationNormBound)^2);
    transitLyapunovBound = exp(-lambda*domainTransitTime) ...
        * initialLyapunovBound+targetUltimate;
    conversion = sqrt(eigenvalueMinimum);
    relativePositionUltimate = targetUltimate ...
        /(bandwidth^2*conversion);
    targetVelocityUltimate = targetUltimate/(bandwidth*conversion);
    targetAccelerationUltimate = targetUltimate/conversion;
    normalizedComponentBounds = [ ...
        transitLyapunovBound/(bandwidth^2*conversion ...
            * chain.relativePositionMaximum); ...
        transitLyapunovBound/(bandwidth*conversion ...
            * chain.speedMaximum); ...
        transitLyapunovBound/(conversion ...
            * chain.accelerationNormBound)];
    bound = struct( ...
        "thresholdConstant", thresholdConstant, ...
        "bandwidth", bandwidth, ...
        "lambda", lambda, ...
        "gainConstant", gainConstant, ...
        "inputScale", inputScale, ...
        "velocityCoupling", velocityCoupling, ...
        "disturbanceBound", disturbanceBound, ...
        "targetUltimate", targetUltimate, ...
        "initialLyapunovBound", initialLyapunovBound, ...
        "transitLyapunovBound", transitLyapunovBound, ...
        "relativePositionUltimate", relativePositionUltimate, ...
        "targetVelocityUltimate", targetVelocityUltimate, ...
        "targetAccelerationUltimate", targetAccelerationUltimate, ...
        "normalizedComponentBounds", normalizedComponentBounds, ...
        "objectiveValue", max(normalizedComponentBounds));
end

function localPrepareSolver()
% localPrepareSolver Put the vendored YALMIP and SeDuMi trees on the path.

    if ~isempty(which("optimize")) && ~isempty(which("sedumi"))
        return
    end
    estimatorRoot = fileparts(mfilename("fullpath"));
    solverRoot = fullfile(fileparts(estimatorRoot), "solver");
    yalmipRoot = fullfile(solverRoot, "YALMIP");
    sedumiRoot = fullfile(solverRoot, "sedumi");
    if ~isfolder(yalmipRoot) || ~isfolder(sedumiRoot)
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "The optimized target shape requires YALMIP and SeDuMi in %s.", ...
            solverRoot);
    end
    addpath(genpath(yalmipRoot));
    addpath(genpath(sedumiRoot));
    if isempty(which("optimize")) || isempty(which("sedumi"))
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "YALMIP and SeDuMi were found in %s but did not load.", ...
            solverRoot);
    end
end

function options = localSolverOptions()
% localSolverOptions Deterministic YALMIP settings.

    options = sdpsettings('solver', 'sedumi', 'verbose', 0, ...
        'cachesolvers', 1, 'warning', 0);
end
