function certificate = synthesizeTargetTrackerCertificate( ...
        lipschitz, chain, domainTransitTime)
% synthesizeTargetTrackerCertificate Retain the high-gain chain and certify it.
%
% A normalized observer LMI selects l and the identity A(l)'P+PA(l)=-I
% fixes its Lyapunov metric. The physical gains remain [l1*w;l2*w^2;l3*w^3].
% Separate global Lipschitz channels Lq and Ls enter a two-multiplier
% dissipation inequality after scaling z=[eRho;eQ/w;eS/w^2].
%
% The engineering objective is the largest domain-normalized ultimate
% component bound, subject to a guaranteed decay rate of at least the
% inverse domain transit time. That decay preference is explicit; it is
% not imposed by the ISS theorem. Numerical searches return a feasible,
% independently checked certificate, without a global optimization claim.

    arguments
        lipschitz (1, 1) struct
        chain (1, 1) struct
        domainTransitTime (1, 1) double {mustBePositive, mustBeFinite}
    end
    validateattributes(lipschitz.phiVelocity,{'double'}, ...
        {'scalar','finite','positive'});
    validateattributes(lipschitz.phiAcceleration,{'double'}, ...
        {'scalar','finite','positive'});

    chain = localValidatedChain(chain);
    chainMatrix = [0.0, 1.0, 0.0; 0.0, 0.0, 1.0; 0.0, 0.0, 0.0];
    outputVector = [1.0; 0.0; 0.0];
    unitVector = [0.0; 0.0; 1.0];
    normalizedDecayRate = 1.0;

    localPrepareSolver();
    [injectionVector, designMatrix, designObjective] = ...
        localSolveNormalizedShape( ...
            chainMatrix, outputVector, normalizedDecayRate);
    closedLoopMatrix = chainMatrix-injectionVector*outputVector.';
    lyapunovMatrix = localSolveLyapunovIdentity(closedLoopMatrix);
    domainTransitDecayRate = 1.0/domainTransitTime;
    bound = localOptimizeBandwidth(lyapunovMatrix, injectionVector, ...
        lipschitz, chain, unitVector, domainTransitTime);
    construction = ...
        "normalized-observer-lmi-plus-structured-lipschitz-iss";

    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    lyapunovResidual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix+eye(3);
    lyapunovEigenvalues = eig(lyapunovMatrix);
    residualMargin = -max(eig( ...
        (lyapunovResidual+lyapunovResidual.')/2.0));
    if min(lyapunovEigenvalues) <= 0.0 || residualMargin < -1.0e-8
        error("synthesizeTargetTrackerCertificate:invalidCertificate", ...
            "The selected target shape lacks a valid Lyapunov certificate.");
    end

    closedLoopPoles = sort(eig(closedLoopMatrix));
    if max(real(closedLoopPoles)) ...
            > -normalizedDecayRate*(1.0-1.0e-6)
        error("synthesizeTargetTrackerCertificate:invalidNormalizedDecay", ...
            "The normalized target shape must lie at or left of Re(s)=-1.");
    end

    certificate = struct( ...
        "shape", "lmi-solved", ...
        "construction", construction, ...
        "injectionVector", injectionVector, ...
        "closedLoopMatrix", closedLoopMatrix, ...
        "closedLoopPoles", closedLoopPoles, ...
        "normalizedDecayRate", normalizedDecayRate, ...
        "designLyapunovMatrix", designMatrix, ...
        "designObjectiveValue", designObjective, ...
        "lyapunovMatrix", lyapunovMatrix, ...
        "thresholdConstant", 2*norm(lyapunovMatrix*unitVector), ...
        "minimumDecayRate", 1/domainTransitTime, ...
        "lipschitzMultipliers", bound.multipliers, ...
        "lipschitzDissipationMatrix", bound.dissipationMatrix, ...
        "lipschitzResidualMargin", bound.lipschitzResidualMargin, ...
        "componentConversion", bound.componentConversion, ...
        "disturbanceCoefficients", bound.disturbanceCoefficients, ...
        "eigenvalueMinimum", min(lyapunovEigenvalues), ...
        "eigenvalueMaximum", max(lyapunovEigenvalues), ...
        "domainTransitDecayRate", domainTransitDecayRate, ...
        "lambda", bound.lambda, ...
        "bandwidth", bound.bandwidth, ...
        "gainConstant", bound.gainConstant, ...
        "inputScale", bound.inputScale, ...
        "velocityCoupling", bound.velocityCoupling, ...
        "disturbanceBound", bound.disturbanceBound, ...
        "targetUltimate", bound.targetUltimate, ...
        "initialLyapunovBound", bound.initialLyapunovBound, ...
        "transitLyapunovBound", bound.transitLyapunovBound, ...
        "relativePositionUltimate", bound.relativePositionUltimate, ...
        "targetVelocityUltimate", bound.targetVelocityUltimate, ...
        "targetAccelerationUltimate", ...
            bound.targetAccelerationUltimate, ...
        "normalizedComponentBounds", ...
            bound.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", bound.activeConstraint, ...
        "bandwidthSearchBracket", bound.searchBracket, ...
        "residualMargin", residualMargin, ...
        "ultimateObjectiveValue", bound.objectiveValue);
end

function chain = localValidatedChain(chain)
    positiveFields = ["relativePositionMaximum", "speedMaximum", ...
        "accelerationNormBound"];
    nonnegativeFields = ["velocityUltimate", ...
        "gyroscopeNoiseMaximum", "radarNoiseMaximum", "modelJerkMaximum"];
    for fieldName = positiveFields
        chain.(fieldName) = localScalarField(chain, fieldName, true);
    end
    for fieldName = nonnegativeFields
        chain.(fieldName) = localScalarField(chain, fieldName, false);
    end
end

function value = localScalarField(input, fieldName, positive)
    if ~isfield(input, fieldName)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s is required.", fieldName);
    end
    value = double(input.(fieldName));
    if ~isscalar(value) || ~isfinite(value)
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
    invalidSign = value < 0.0 || (positive && value <= 0.0);
    if invalidSign
        error("synthesizeTargetTrackerCertificate:invalidChain", ...
            "chain.%s has an invalid bound.", fieldName);
    end
end

function [injectionVector, lyapunovMatrix, objective] = ...
        localSolveNormalizedShape(chainMatrix, outputVector, decayRate)
% localSolveNormalizedShape Minimize normalized noise-to-state H-infinity gain.

    lyapunovVariable = sdpvar(3, 3);
    injectionVariable = sdpvar(3, 1);
    boundedRealVariable = sdpvar(1, 1);
    margin = 1.0e-6;
    weighted = lyapunovVariable*chainMatrix ...
        - injectionVariable*outputVector.';
    boundedRealMatrix = [ ...
        weighted+weighted.'+eye(3), -injectionVariable; ...
        -injectionVariable.', -boundedRealVariable];
    constraints = [ ...
        lyapunovVariable >= eye(3), ...
        weighted+weighted.'+2.0*decayRate*lyapunovVariable ...
            <= -margin*eye(3), ...
        boundedRealVariable >= 0.0, ...
        boundedRealMatrix <= -margin*eye(4)];
    diagnostics = optimize(constraints, boundedRealVariable, ...
        localSolverOptions());
    if diagnostics.problem ~= 0
        error("synthesizeTargetTrackerCertificate:infeasibleShape", ...
            "The normalized target-shape LMI failed: %s", ...
            diagnostics.info);
    end

    lyapunovMatrix = value(lyapunovVariable);
    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    injectionVector = lyapunovMatrix\value(injectionVariable);
    closedLoopMatrix = ...
        chainMatrix-injectionVector*outputVector.';
    regionResidual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix ...
        + 2.0*decayRate*lyapunovMatrix;
    boundedRealResidual = [ ...
        closedLoopMatrix.'*lyapunovMatrix ...
            + lyapunovMatrix*closedLoopMatrix+eye(3), ...
            -lyapunovMatrix*injectionVector; ...
        -injectionVector.'*lyapunovMatrix, ...
            -value(boundedRealVariable)];
    if min(eig(lyapunovMatrix)) < 1.0-1.0e-7 ...
            || max(eig((regionResidual+regionResidual.')/2.0)) > 1.0e-7 ...
            || max(eig((boundedRealResidual ...
                + boundedRealResidual.')/2.0)) > 1.0e-7
        error("synthesizeTargetTrackerCertificate:invalidShapeSolution", ...
            "The recovered normalized target shape failed certification.");
    end
    objective = value(boundedRealVariable);
end

function lyapunovMatrix = localSolveLyapunovIdentity(closedLoopMatrix)
% localSolveLyapunovIdentity Fix the certificate by A'P+PA=-I.

    stateDimension = size(closedLoopMatrix, 1);
    identity = eye(stateDimension);
    lyapunovOperator = kron(identity, closedLoopMatrix.') ...
        + kron(closedLoopMatrix.', identity);
    vectorizedMatrix = -lyapunovOperator\identity(:);
    lyapunovMatrix = reshape( ...
        vectorizedMatrix, stateDimension, stateDimension);
    lyapunovMatrix = (lyapunovMatrix+lyapunovMatrix.')/2.0;
    residual = closedLoopMatrix.'*lyapunovMatrix ...
        + lyapunovMatrix*closedLoopMatrix+identity;
    tolerance = 1024.0*eps(max(1.0, norm(lyapunovMatrix)));
    if min(eig(lyapunovMatrix)) <= 0.0 ...
            || max(abs(residual), [], "all") > tolerance
        error("synthesizeTargetTrackerCertificate:invalidLyapunovIdentity", ...
            "The solved target shape did not yield a valid unique certificate.");
    end
end

function bestBound = localOptimizeBandwidth(lyapunovMatrix, ...
        injectionVector, lipschitz, chain, unitVector, domainTransitTime)
% localOptimizeBandwidth Minimize ultimate bounds with a declared decay floor.

    requiredRate = 1/domainTransitTime;
    rate = @(bandwidth) localStructuredRate( ...
        bandwidth,lyapunovMatrix,lipschitz,unitVector);
    lowerBandwidth = 1+1e-8;
    if rate(lowerBandwidth) < requiredRate
        upperBandwidth = 2*lowerBandwidth;
        while rate(upperBandwidth) < requiredRate
            upperBandwidth = 2*upperBandwidth;
            if upperBandwidth > 1e6
                error("synthesizeTargetTrackerCertificate:infeasibleDecay", ...
                    "Failed to bracket the required structured decay rate.");
            end
        end
        lowerBandwidth = fzero(@(bandwidth) rate(bandwidth)-requiredRate, ...
            [lowerBandwidth,upperBandwidth]);
        lowerBandwidth = lowerBandwidth+1e-7*max(1,lowerBandwidth);
    end
    objective = @(bandwidth) localTargetObjective(bandwidth, ...
        lyapunovMatrix,injectionVector,lipschitz,chain,unitVector,domainTransitTime);
    disturbancePresent = chain.velocityUltimate > 0 ...
        || chain.gyroscopeNoiseMaximum > 0 || chain.radarNoiseMaximum > 0 ...
        || chain.modelJerkMaximum > 0;
    if ~disturbancePresent
        bestBandwidth = lowerBandwidth;
        searchBracket = [lowerBandwidth,lowerBandwidth];
    else
        grid = lowerBandwidth*2.^(0:12);
        values = arrayfun(objective,grid);
        [~,index] = min(values);
        if index == numel(grid)
            error("synthesizeTargetTrackerCertificate:unboundedBandwidthSearch", ...
                "The ultimate-bound search did not bracket a finite minimum.");
        end
        searchBracket = [grid(max(1,index-1)),grid(index+1)];
        interior = fminbnd(objective,searchBracket(1),searchBracket(2), ...
            optimset("Display","off","TolX",1e-8*lowerBandwidth));
        candidates = [lowerBandwidth,interior,searchBracket];
        [~,index] = min(arrayfun(objective,candidates));
        bestBandwidth = candidates(index);
    end
    bestBound = localTargetBound(bestBandwidth,lyapunovMatrix, ...
        injectionVector,lipschitz,chain,unitVector,domainTransitTime);
    if bestBound.lambda < requiredRate*(1-1e-7)
        error("synthesizeTargetTrackerCertificate:invalidDecay", ...
            "The selected target gains violate their declared decay constraint.");
    end
    if abs(bestBandwidth-lowerBandwidth) <= 1e-6*lowerBandwidth
        bestBound.activeConstraint = "domain-transit-decay";
    else
        bestBound.activeConstraint = "normalized-ultimate-state-bound";
    end
    bestBound.searchBracket = searchBracket;
end

function objective = localTargetObjective(bandwidth,lyapunovMatrix, ...
        injectionVector,lipschitz,chain,unitVector,domainTransitTime)
    bound = localTargetBound(bandwidth,lyapunovMatrix,injectionVector, ...
        lipschitz,chain,unitVector,domainTransitTime);
    objective = bound.objectiveValue;
end

function bound = localTargetBound(bandwidth,lyapunovMatrix, ...
        injectionVector,lipschitz,chain,unitVector,domainTransitTime)
% localTargetBound Use the metric's actual input and output directions.

    [lambda,multipliers,dissipationMatrix] = localStructuredRate( ...
        bandwidth,lyapunovMatrix,lipschitz,unitVector);
    if lambda <= 0
        bound = struct("objectiveValue",Inf);
        return
    end
    scale = [1;1/bandwidth;1/bandwidth^2];
    physicalBounds = [chain.relativePositionMaximum;chain.speedMaximum; ...
        chain.accelerationNormBound];
    scaledBounds = scale.*physicalBounds;
    gyroCoefficient = sqrt(scaledBounds.'*abs(lyapunovMatrix)*scaledBounds);
    velocityCoupling = sqrt(lyapunovMatrix(1,1));
    radarCoefficient = bandwidth ...
        *sqrt(injectionVector.'*lyapunovMatrix*injectionVector);
    modelCoefficient = sqrt(lyapunovMatrix(3,3))/bandwidth^2;
    disturbanceBound = gyroCoefficient*chain.gyroscopeNoiseMaximum ...
        +radarCoefficient*chain.radarNoiseMaximum ...
        +modelCoefficient*chain.modelJerkMaximum;
    targetUltimate = (velocityCoupling*chain.velocityUltimate ...
        +disturbanceBound)/lambda;
    inverseMetric = lyapunovMatrix\eye(3);
    componentConversion = sqrt(diag(inverseMetric))./scale;
    ultimate = componentConversion*targetUltimate;
    initialLyapunovBound = 2*sqrt(scaledBounds.'*abs(lyapunovMatrix)*scaledBounds);
    transitLyapunovBound = exp(-lambda*domainTransitTime) ...
        *initialLyapunovBound+targetUltimate;
    normalizedComponentBounds = ultimate./physicalBounds;
    residualMargin = min(eig((dissipationMatrix+dissipationMatrix.')/2));
    if ~isfinite(residualMargin) || residualMargin < -1e-8
        error("synthesizeTargetTrackerCertificate:invalidLipschitzCertificate", ...
            "The structured Lipschitz dissipation inequality failed verification.");
    end
    bound = struct("bandwidth",bandwidth,"lambda",lambda, ...
        "multipliers",multipliers,"dissipationMatrix",dissipationMatrix, ...
        "lipschitzResidualMargin",residualMargin, ...
        "gainConstant",sqrt(max(eig(lyapunovMatrix))), ...
        "inputScale",gyroCoefficient,"velocityCoupling",velocityCoupling, ...
        "disturbanceCoefficients",struct("gyro",gyroCoefficient, ...
            "radar",radarCoefficient,"modelJerk",modelCoefficient), ...
        "disturbanceBound",disturbanceBound,"targetUltimate",targetUltimate, ...
        "componentConversion",componentConversion, ...
        "initialLyapunovBound",initialLyapunovBound, ...
        "transitLyapunovBound",transitLyapunovBound, ...
        "relativePositionUltimate",ultimate(1), ...
        "targetVelocityUltimate",ultimate(2), ...
        "targetAccelerationUltimate",ultimate(3), ...
        "normalizedComponentBounds",normalizedComponentBounds, ...
        "objectiveValue",max(normalizedComponentBounds));
end

function [lambda,multipliers,residual] = localStructuredRate( ...
        bandwidth,metric,lipschitz,unitVector)
% localStructuredRate Optimize two Young multipliers and verify the result.
%
% M = w*I - tq*(Lq/w)^2*e2*e2' - ts*Ls^2*e3*e3'
%             - (1/tq+1/ts)*(P*e3)*(P*e3)'.
% M >= 2*lambda*P certifies Wdot <= -lambda*W before exogenous inputs.
% Every returned rate is checked algebraically; optimizer success is not
% the certificate, nor is the numerical maximizer claimed to be global.

    direction = metric*unitVector;
    sensitivities = [lipschitz.phiVelocity/bandwidth;lipschitz.phiAcceleration];
    initial = log(norm(direction)./sensitivities);
    objective = @(logMultipliers) localRateLoss(logMultipliers, ...
        bandwidth,metric,direction,sensitivities);
    optimum = fminsearch(objective,initial, ...
        optimset("Display","off","TolX",1e-8,"TolFun",1e-10));
    multipliers = exp(optimum);
    matrix = bandwidth*eye(3) ...
        -diag([0;multipliers.*sensitivities.^2]) ...
        -sum(1./multipliers)*(direction*direction.');
    rawRate = 0.5*min(real(eig(matrix,metric)));
    lambda = rawRate-1e-8*max(1,abs(rawRate));
    residual = matrix-2*lambda*metric;
end

function loss = localRateLoss(logMultipliers,bandwidth,metric,direction,sensitivities)
    if any(abs(logMultipliers) > 60)
        loss = realmax;
        return
    end
    multipliers = exp(logMultipliers);
    matrix = bandwidth*eye(3) ...
        -diag([0;multipliers.*sensitivities.^2]) ...
        -sum(1./multipliers)*(direction*direction.');
    loss = -0.5*min(real(eig(matrix,metric)));
end

function localPrepareSolver()
% localPrepareSolver Put the vendored YALMIP and SeDuMi trees on the path.

    if ~isempty(which("optimize")) && ~isempty(which("sedumi"))
        return
    end
    estimatorRoot = fileparts(mfilename("fullpath"));
    solverRoot = fullfile(fileparts(estimatorRoot), "solver");
    yalmipRoot = fullfile(solverRoot, "YALMIP");
    sedumiRoot = fullfile(solverRoot, "sedumi");
    if ~isfolder(yalmipRoot) || ~isfolder(sedumiRoot)
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "The optimized target shape requires YALMIP and SeDuMi in %s.", ...
            solverRoot);
    end
    addpath(genpath(yalmipRoot));
    addpath(genpath(sedumiRoot));
    if isempty(which("optimize")) || isempty(which("sedumi"))
        error("synthesizeTargetTrackerCertificate:missingLmiSolver", ...
            "YALMIP and SeDuMi were found in %s but did not load.", ...
            solverRoot);
    end
end

function options = localSolverOptions()
% localSolverOptions Deterministic YALMIP settings.

    options = sdpsettings('solver', 'sedumi', 'verbose', 0, ...
        'cachesolvers', 1, 'warning', 0);
end
