function design = synthesizeNrmmObserverGains(cfg)
% synthesizeNrmmObserverGains Construct the cascaded observer certificates.
%
% The core is direct kinematic body velocity followed by the retained NRMM
% target chain. The common gyro error is combined before its norm is bounded.
% Yaw is a propagated/intersected output set with no correction gain or state.
% The fixed velocity gain retains the explicit minimum-bandwidth transit-decay
% preference. The certificate does not imply that larger gains always help;
% gains near a representative longitudinal speed/l suppress first-order gyro
% forcing. Target shape/extension and structured Lipschitz design are retained.
% Runtime timing is not an input to continuous gain synthesis. Sample holds,
% numerical integration and orientation-set propagation are certified separately.

    localAddProjectPaths();
    if nargin < 1 || isempty(cfg)
        cfg = nrmmTrackingConfig();
    end
    if isfield(cfg, "observerDesign")
        error("synthesizeNrmmObserverGains:legacyManualGainConfiguration", ...
            "observerDesign gain/decay fields are no longer accepted; " ...
            + "all observer gains are synthesized from continuous domains and bounds.");
    end

    %% Sensor error bounds (Sec. 3)
    positionNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "positionNoiseMaximum"]);
    velocityNoise = localNonnegative(cfg, ...
        ["measurement", "gps", "velocityNoiseMaximum"]);
    accelerometerNoise = localNonnegative(cfg, ...
        ["measurement", "imu", "noiseMaximum"]);
    gyroscopeNoise = localNonnegative(cfg, ...
        ["measurement", "gyroscope", "noiseMaximum"]);
    radarNoise = localNonnegative(cfg, ...
        ["measurement", "radar", "noiseMaximum"]);

    %% Ego operating domain (Assumption 1)
    egoSpeedMaximum = localNonnegative(cfg, ["ego", "domain", "speedMaximum"]);
    egoSpeedMinimum = localNonnegative(cfg, ["ego", "domain", "speedMinimum"]);
    if egoSpeedMinimum > egoSpeedMaximum
        error("synthesizeNrmmObserverGains:invalidEgoSpeedInterval", ...
            "The ego speed interval requires 0 <= V_{E,min} <= Vbar_E.");
    end
    egoYawRateMaximum = localNonnegative(cfg, ...
        ["ego", "domain", "yawRateMaximum"]);
    measuredYawRateMaximum = egoYawRateMaximum+gyroscopeNoise;

    %% Bounded-mismatch forward kinematics and output-only orientation
    egoRearAxleDistance = localPositive(cfg, ...
        ["ego", "yaw", "rearAxleDistance"]);
    sideslipDomainMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "sideslipDomainMaximum"]);
    if sideslipDomainMaximum >= 0.5*pi
        error("synthesizeNrmmObserverGains:invalidSideslipBound", ...
            "The ego side-slip inversion domain must be below pi/2.");
    end
    singleTrackYawRateMismatchMaximum = localNonnegative(cfg, ...
        ["ego", "yaw", "singleTrackYawRateMismatchMaximum"]);

    %% Physical horizon and solver constraints
    targetSpeedMaximum = localPositive(cfg, ...
        ["target", "domain", "speedMaximum"]);
    relativePositionMaximum = localPositive(cfg, ...
        ["target", "domain", "relativePositionMaximum"]);
    domainTransitTime = relativePositionMaximum ...
        /(egoSpeedMaximum+targetSpeedMaximum);
    scalarGainBounds = [log(20.0)/domainTransitTime, Inf];

    %% Direct body-velocity observer with a shared gyro disturbance
    sensors = struct("positionNoiseMaximum",positionNoise, ...
        "velocityNoiseMaximum",velocityNoise, ...
        "accelerometerNoiseMaximum",accelerometerNoise, ...
        "gyroscopeNoiseMaximum",gyroscopeNoise,"radarNoiseMaximum",radarNoise);
    courseModel = struct("rearAxleDistance",egoRearAxleDistance, ...
        "sideslipDomainMaximum",sideslipDomainMaximum, ...
        "singleTrackYawRateMismatchMaximum",singleTrackYawRateMismatchMaximum, ...
        "relation","omegaE=vEy/lrE+boundedMismatch");
    velocityGain = log(20.0)/domainTransitTime;
    velocityCertificate = nrmmVelocityDisturbanceBound(velocityGain, ...
        [egoSpeedMinimum,egoSpeedMaximum],courseModel,sensors);
    velocityLambda = velocityGain;
    velocityLyapunovMatrix = eye(2);
    localAssertVelocityCertificate(velocityGain,measuredYawRateMaximum,velocityLambda);
    velocityDisturbance = velocityCertificate.disturbanceBound;
    velocityUltimate = velocityCertificate.ultimateBound;
    velocityGainSolution = struct("stage","bodyVelocity", ...
        "method","minimum-bandwidth-continuous-decay", ...
        "minimumDecayRate",velocityGain,"transitResidualFraction",0.05, ...
        "gain",velocityGain,"ultimateBound",velocityUltimate, ...
        "objectiveValue",velocityGain,"activeConstraint","domain-transit-decay");
    % Position is an independent downstream GNSS output, not a yaw-mediated
    % input to the body-frame observer. S^1 is the unconditional yaw set cap.
    yawUltimate = pi;
    [positionGain, positionGainSolution] = localSolveScalarCorrectionGain( ...
        velocityNoise,positionNoise,domainTransitTime,"position");

    %% Target domain and Lipschitz constants (Sec. 5)
    targetSpeedMinimum = localPositive(cfg, ...
        ["target", "domain", "speedMinimum"]);
    if targetSpeedMaximum <= targetSpeedMinimum
        error("synthesizeNrmmObserverGains:invalidTargetSpeedInterval", ...
            "The target speed interval requires V_{C,min} < Vbar_C.");
    end
    targetAccelerationMaximum = localPositive(cfg, ...
        ["target", "domain", "scalarAccelerationMaximum"]);
    targetSideslipMaximum = localPositive(cfg, ...
        ["target", "domain", "sideslipMaximum"]);
    rearAxleDistance = localPositive(cfg, ...
        ["target", "domain", "rearAxleDistance"]);
    targetYawRateMaximum = ...
        targetSpeedMaximum*sin(targetSideslipMaximum)/rearAxleDistance;
    targetAccelerationNormBound = hypot(targetAccelerationMaximum, ...
        targetSpeedMaximum*targetYawRateMaximum);
    targetLipschitz = nrmmTargetLipschitzCertificate(struct( ...
        "speedMinimum",targetSpeedMinimum,"speedMaximum",targetSpeedMaximum, ...
        "scalarAccelerationMaximum",targetAccelerationMaximum, ...
        "yawRateMaximum",targetYawRateMaximum, ...
        "accelerationNormBound",targetAccelerationNormBound));
    scalarAccelerationRateMaximum = localNonnegative(cfg, ...
        ["target","model","scalarAccelerationRateMaximum"]);
    curvatureRateMaximum = localNonnegative(cfg, ...
        ["target","model","curvatureRateMaximum"]);
    modelJerkMaximum = hypot(scalarAccelerationRateMaximum, ...
        targetSpeedMaximum^2*curvatureRateMaximum);

    %% Solved normalized target shape and physical bandwidth (Secs. 9-10)
    targetCertificate = synthesizeTargetTrackerCertificate( ...
        targetLipschitz, struct( ...
            "velocityUltimate", velocityUltimate, ...
            "relativePositionMaximum", relativePositionMaximum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "gyroscopeNoiseMaximum", gyroscopeNoise, ...
            "radarNoiseMaximum", radarNoise, ...
            "modelJerkMaximum",modelJerkMaximum), domainTransitTime);
    targetBandwidth = targetCertificate.bandwidth;
    targetInputScale = targetCertificate.inputScale;
    targetInjectionVector = targetCertificate.injectionVector;
    targetClosedLoopMatrix = targetCertificate.closedLoopMatrix;
    targetLyapunovMatrix = targetCertificate.lyapunovMatrix;
    targetEigMinimum = targetCertificate.eigenvalueMinimum;
    targetEigMaximum = targetCertificate.eigenvalueMaximum;
    targetLambda = targetCertificate.lambda;
    targetGainConstant = targetCertificate.gainConstant;
    targetVelocityCoupling = targetCertificate.velocityCoupling;
    targetDisturbance = targetCertificate.disturbanceBound;

    %% Explicit copositive ISS certificate for the essential core
    coreCertificate = nrmmObserverCertificate(struct( ...
        "velocityDecayRate", velocityLambda, ...
        "targetDecayRate", targetLambda, ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "input", [velocityDisturbance; targetDisturbance]));

    %% Ultimate bounds (Cors. 8.1-8.2)
    % Scalar forward substitution down the triangular cascade.
    positionUltimate = positionNoise ...
        + velocityNoise/positionGain;
    targetUltimate = ...
        (targetVelocityCoupling*velocityUltimate+targetDisturbance) ...
        / targetLambda;
    relativePositionUltimate = targetCertificate.relativePositionUltimate;
    targetVelocityUltimate = targetCertificate.targetVelocityUltimate;
    targetAccelerationUltimate = targetCertificate.targetAccelerationUltimate;
    controllerRelativePositionUltimate = relativePositionUltimate ...
        + 2*relativePositionMaximum;

    %% Assembled design
    design = struct();
    design.construction = "direct kinematic velocity with common gyro error, " ...
        + "retained NRMM chain, and output-only orientation sets";
    design.sensors = sensors;
    design.yaw = struct("courseModel",courseModel, ...
        "measurementMethod","kinematic-sideslip-corrected-certified-correspondence", ...
        "representation","propagated-intersected-circle-set", ...
        "maximumRadius",pi);
    design.velocity = struct( ...
        "gain", velocityGain, ...
        "lyapunovMatrix", velocityLyapunovMatrix, ...
        "lambda", velocityLambda, ...
        "gainConstant", 1.0, ...
        "disturbanceBound", velocityDisturbance, ...
        "disturbanceCertificate", velocityCertificate, ...
        "gainOptimization", velocityGainSolution);
    design.position = struct( ...
        "gain", positionGain, ...
        "gainOptimization", positionGainSolution);
    design.target = struct( ...
        "shape", targetCertificate.shape, ...
        "shapeConstruction", targetCertificate.construction, ...
        "bandwidth", targetBandwidth, ...
        "injectionVector", targetInjectionVector, ...
        "innovationGains", [ ...
            targetInjectionVector(1)*targetBandwidth; ...
            targetInjectionVector(2)*targetBandwidth^2; ...
            targetInjectionVector(3)*targetBandwidth^3], ...
        "closedLoopMatrix", targetClosedLoopMatrix, ...
        "closedLoopPoles", targetCertificate.closedLoopPoles, ...
        "normalizedDecayRate", ...
            targetCertificate.normalizedDecayRate, ...
        "domainTransitDecayRate", ...
            targetCertificate.domainTransitDecayRate, ...
        "designLyapunovMatrix", ...
            targetCertificate.designLyapunovMatrix, ...
        "lyapunovMatrix", targetLyapunovMatrix, ...
        "eigenvalueMinimum", targetEigMinimum, ...
        "eigenvalueMaximum", targetEigMaximum, ...
        "lambda", targetLambda, ...
        "gainConstant", targetGainConstant, ...
        "thresholdConstant", targetCertificate.thresholdConstant, ...
        "certificateResidualMargin", targetCertificate.residualMargin, ...
        "shapeObjectiveValue", targetCertificate.designObjectiveValue, ...
        "certificateObjectiveValue", ...
            targetCertificate.ultimateObjectiveValue, ...
        "initialLyapunovBound", ...
            targetCertificate.initialLyapunovBound, ...
        "transitLyapunovBound", ...
            targetCertificate.transitLyapunovBound, ...
        "normalizedComponentBounds", ...
            targetCertificate.normalizedComponentBounds, ...
        "bandwidthActiveConstraint", ...
            targetCertificate.bandwidthActiveConstraint, ...
        "bandwidthSearchBracket", ...
            targetCertificate.bandwidthSearchBracket, ...
        "inputScale", targetInputScale, ...
        "disturbanceBound", targetDisturbance, ...
        "lipschitzCertificate",targetLipschitz, ...
        "lipschitzMultipliers",targetCertificate.lipschitzMultipliers, ...
        "lipschitzDissipationMatrix",targetCertificate.lipschitzDissipationMatrix, ...
        "lipschitzResidualMargin",targetCertificate.lipschitzResidualMargin, ...
        "componentConversion",targetCertificate.componentConversion, ...
        "disturbanceCoefficients",targetCertificate.disturbanceCoefficients, ...
        "minimumDecayRate",targetCertificate.minimumDecayRate, ...
        "modelJerkMaximum",modelJerkMaximum, ...
        "domain", struct( ...
            "speedMinimum", targetSpeedMinimum, ...
            "speedMaximum", targetSpeedMaximum, ...
            "scalarAccelerationMaximum", targetAccelerationMaximum, ...
            "yawRateMaximum", targetYawRateMaximum, ...
            "accelerationNormBound", targetAccelerationNormBound, ...
            "sideslipMaximum", targetSideslipMaximum, ...
            "rearAxleDistance", rearAxleDistance, ...
            "relativePositionMaximum", relativePositionMaximum));
    design.coupling = struct( ...
        "targetVelocityCoupling", targetVelocityCoupling, ...
        "feedforward", true);
    design.coreIss = coreCertificate;
    design.ultimateBounds = struct( ...
        "yaw", yawUltimate, ...
        "bodyVelocity", velocityUltimate, ...
        "position", positionUltimate, ...
        "targetLyapunov", targetUltimate, ...
        "relativePosition", relativePositionUltimate, ...
        "targetVelocity", targetVelocityUltimate, ...
        "targetAcceleration", targetAccelerationUltimate, ...
        "yawRate", gyroscopeNoise, ...
        "inertialVelocity", velocityUltimate ...
            + 2*egoSpeedMaximum, ...
        "targetPositionInertial", positionUltimate ...
            + relativePositionUltimate ...
            + 2*relativePositionMaximum, ...
        "targetVelocityInertial", targetVelocityUltimate ...
            + 2*targetSpeedMaximum, ...
        "targetAccelerationInertial", targetAccelerationUltimate ...
            + 2*targetAccelerationNormBound, ...
        "velocityDifference", targetVelocityUltimate+velocityUltimate, ...
        "accelerationDifference", targetAccelerationUltimate+accelerometerNoise);
    design.ultimateBounds.controllerRelativePosition = ...
        controllerRelativePositionUltimate;
    design.gainSelection = struct( ...
        "method", "structured-lipschitz-iss-minimax-synthesis", ...
        "scalarMethod", "minimum-bandwidth-continuous-decay", ...
        "domainTransitTime", domainTransitTime, ...
        "scalarGainBounds", scalarGainBounds, ...
        "velocityProgram", velocityGainSolution, ...
        "positionProgram", positionGainSolution, ...
        "achievedDecayRates", struct( ...
            "bodyVelocity", velocityLambda, ...
            "position", positionGain, ...
            "target", targetLambda), ...
        "targetShapeMethod", "normalized-observer-lmi", ...
        "targetBandwidthMethod", ...
            "normalized-ultimate-bound-with-domain-transit-decay", ...
        "targetBandwidth", targetBandwidth);
    design.certificateScope = struct( ...
        "timeModel","continuous observer with continuous bounded-error measurements", ...
        "yawCondition","output set containment only; no yaw condition for core ISS", ...
        "sampledImplementationCertified",false, ...
        "qualification","the certificate concerns the continuous vector field under its stated premises");
    design.operatingDomain = struct( ...
        "egoSpeedMinimum", egoSpeedMinimum, ...
        "egoSpeedMaximum", egoSpeedMaximum, ...
        "egoYawRateMaximum", egoYawRateMaximum, ...
        "measuredYawRateMaximum", measuredYawRateMaximum, ...
        "egoSideslipDomainMaximum", sideslipDomainMaximum, ...
        "egoSingleTrackYawRateMismatchMaximum", ...
            singleTrackYawRateMismatchMaximum, ...
        "target", design.target.domain, ...
        "containmentScope", ...
            "estimated runtime states and measured inputs only; " ...
            + "truth trajectories require offline audit");
end

function [gain, solution] = localSolveScalarCorrectionGain( ...
        processBound, measurementEquivalentBound, domainTransitTime, stage)
% localSolveScalarCorrectionGain Minimize bandwidth at the required decay.
%
% For D+e <= -k*e+a+k*b, every k > 0 supplies continuous decay k and
% ultimate radius b+a/k. Require exp(-k*Tdomain) <= 0.05 and minimize k;
% the physical transit time fixes the unique solution log(20)/Tdomain.
% The 5 percent residual is a continuous settling preference. Sensor bounds
% affect the resulting radius, not this minimum-bandwidth preference.

    gain = log(20.0)/domainTransitTime;
    disturbanceContribution = processBound/gain;
    solution = struct( ...
        "stage", stage, ...
        "method", "minimum-bandwidth-continuous-decay", ...
        "processBound", processBound, ...
        "measurementEquivalentBound", measurementEquivalentBound, ...
        "minimumDecayRate", gain, ...
        "transitResidualFraction", 0.05, ...
        "gain", gain, ...
        "disturbanceContribution", disturbanceContribution, ...
        "ultimateBound", measurementEquivalentBound+disturbanceContribution, ...
        "objectiveValue", gain, ...
        "activeConstraint", "domain-transit-decay");
end

function localAssertVelocityCertificate(velocityGain, yawRateBound, lambda)
% localAssertVelocityCertificate Verify P = I certifies the decay rate.
%
% The claim A_v(u3)' + A_v(u3) = -2*lambda*I is an identity in u3, not a
% numerical solution, but it is the load-bearing step of the velocity
% stage, so it is checked at both interval vertices before use.

    planarCross = [0.0, -1.0; 1.0, 0.0];
    for vertex = [-yawRateBound, yawRateBound]
        systemMatrix = -velocityGain*eye(2)-vertex*planarCross;
        residual = systemMatrix.'+systemMatrix+2.0*lambda*eye(2);
        if max(abs(residual), [], "all") > 128.0*eps(max(1.0, lambda))
            error("synthesizeNrmmObserverGains:invalidVelocityCertificate", ...
                "P = I must certify the velocity decay rate exactly.");
        end
    end
end

function value = localPositive(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value <= 0.0
        error("synthesizeNrmmObserverGains:invalidPositiveScalar", ...
            "%s must be a finite positive scalar.", strjoin(path, "."));
    end
end

function value = localNonnegative(cfg, path)
    value = double(localField(cfg, path));
    if ~isscalar(value) || ~isfinite(value) || value < 0.0
        error("synthesizeNrmmObserverGains:invalidNonnegativeScalar", ...
            "%s must be a finite nonnegative scalar.", strjoin(path, "."));
    end
end

function value = localField(cfg, path)
    value = cfg;
    for fieldIdx = 1:numel(path)
        fieldName = char(path(fieldIdx));
        if ~isstruct(value) || ~isfield(value, fieldName) ...
                || isempty(value.(fieldName))
            error("synthesizeNrmmObserverGains:missingConfiguration", ...
                "%s is required.", strjoin(path, "."));
        end
        value = value.(fieldName);
    end
end

function localAddProjectPaths()
    estimatorRoot = fileparts(mfilename("fullpath"));
    repoRoot = fileparts(estimatorRoot);
    addpath(fullfile(repoRoot, "config"));
    addpath(estimatorRoot);
end
