function evaluateEstimatorDesign(repositoryRoot,outputFile)
%evaluateEstimatorDesign Export the synthesized estimator design quoted in the manuscript.
% Runs the committed gain synthesis on the default configuration and writes
% the numbers of paper/manuscript.tex, Section VI-A. No trajectory is simulated.
    addpath(fullfile(repositoryRoot,'config'),fullfile(repositoryRoot,'estimator'));
    cfg=nrmmTrackingConfig();
    design=synthesizeNrmmObserverGains(cfg);
    t=design.target;
    s=struct('matlabVersion',version, ...
        'egoRearAxleDistance',cfg.ego.yaw.rearAxleDistance, ...
        'domainTransitTime',design.gainSelection.domainTransitTime, ...
        'yawGain',design.yaw.correctionBandwidth,'velocityGain',design.velocity.gain, ...
        'positionGain',design.position.gain, ...
        'velocityDisturbanceBound',design.velocity.disturbanceBound, ...
        'velocityCertificate',design.velocity.disturbanceCertificate, ...
        'shapeSlowestRate',t.shapeBandwidth,'shapeVarianceBound',t.shapeObjectiveValue, ...
        'shape',t.injectionVector,'bandwidth',t.bandwidth,'innovationGains',t.innovationGains, ...
        'normalizedPolesReal',real(t.closedLoopPoles),'normalizedPolesImaginary',imag(t.closedLoopPoles), ...
        'lyapunovMatrix',t.lyapunovMatrix,'decayRate',t.lambda, ...
        'lipschitzVelocity',t.lipschitzCertificate.phiVelocity, ...
        'lipschitzAcceleration',t.lipschitzCertificate.phiAcceleration, ...
        'lipschitzMultipliers',t.lipschitzMultipliers,'lipschitzResidualMargin',t.lipschitzResidualMargin, ...
        'componentConversion',t.componentConversion,'disturbanceCoefficients',t.disturbanceCoefficients, ...
        'targetDisturbanceBound',t.disturbanceBound,'bandwidthSearchBracket',t.bandwidthSearchBracket, ...
        'targetDomain',t.domain,'comparisonMatrix',design.coreIss.matrix, ...
        'comparisonInput',design.coreIss.input,'ultimateBounds',design.ultimateBounds);
    fid=fopen(outputFile,'w');fwrite(fid,jsonencode(s,'PrettyPrint',true));fclose(fid);
end
