function cfg = collisionAvoidanceControllerConfig(userCfg)
% collisionAvoidanceControllerConfig Defaults and merge for the controller.
%
% Returns the predictive-certificate controller configuration, with supplied
% overrides merged recursively over the declared defaults. Every field
% the controller reads is defined here; a missing field is a
% configuration error at the consuming module rather than a silent
% default there.
% Longitudinal-acceleration limits are validated here and normalized to
% double scalars in m/s^2 before model and tire modules consume them.
%
% The defaults describe a mid-size passenger car with the Ge et al.
% (2022) input [deltaF; a] and the forward-Euler Frenet LTV bicycle
% stage model of LTV_BICYCLE_MODEL.md.

    if nargin < 1
        userCfg = [];
    end
    cfg = localDefaults();
    if ~isempty(userCfg)
        if ~isstruct(userCfg) || ~isscalar(userCfg)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "The configuration override must be a scalar structure.");
        end
        cfg = localMergeStructure(cfg, userCfg);
    end
    cfg.actuation = localNormalizeActuation(cfg.actuation);
    localValidate(cfg);
end

function cfg = localDefaults()
    cfg = struct();

    % Route-following cruise demand of the CLF.
    cfg.referenceSpeed = 15.0;

    % Closed-loop period and prediction horizon. Every prediction
    % stage is one sample, so the plan advances one node per sample.
    cfg.controller = struct( ...
        "sampleTime", 0.05, ...
        "horizonSteps", 48, ...
        "shiftConsistencyTolerance", 1.0e-8, ...
        "stationTrustRadius", 2.0);

    % Geometric clearance in metres, imposed at every prediction node.
    cfg.collision = struct("clearanceMargin", 0.25);

    % Vehicle geometry and inertia.
    cfg.vehicle = struct( ...
        "m", 1650.0, ...
        "Iz", 1700.0, ...
        "lf", 1.4, ...
        "lr", 1.65, ...
        "wheelbase", 3.05, ...
        "length", 4.8, ...
        "width", 1.9, ...
        "gravity", 9.81, ...
        "centerOfGravityHeight", 0.55);
    cfg.tire = struct( ...
        "corneringStiffness", [96000.0; 96000.0], ...
        "frictionCoefficient", [0.85; 0.85]);
    cfg.actuation = struct( ...
        "brakingForceDistribution", [0.625; 0.375], ...
        "longitudinalAccelerationMinimum", -8.0, ...
        "longitudinalAccelerationMaximum", 4.0);

    % Zero speed is admitted by the regularized scheduled model. The tire
    % denominator alone uses scheduleSpeedFloor. Geometry is certified on
    % finite station intervals and the declared lateral/heading domains.
    cfg.model = struct( ...
        "speedMinimum", 0.0, ...
        "speedMaximum", 18.0, ...
        "lateralDomainRadius", 12.0, ...
        "scheduleSpeedFloor", 12.0, ...
        "frontWheelSteeringAngleMaximum", deg2rad(40.0), ...
        "frictionPolygonEdgeCount", 8, ...
        "slipAngleMaximum", deg2rad([10.0; 10.0]), ...
        "headingDomainRadius", 0.40, ...
        "ltvModelErrorRateBound", zeros(6, 1), ...
        "plantModelResidualRateBound", zeros(6, 1));

    % The complete bicycle continuation reaches rest. backupDeceleration
    % determines only the initial braking schedule and continuation length;
    % full physical actuator/tire constraints apply at every stage.
    cfg.terminal = struct("backupDeceleration", 5.0, ...
        "supportDirectionCount", 64);

    % Road-geometry implementation allowances.
    cfg.road = struct( ...
        "orthonormalTolerance", 1.0e-9, ...
        "parameterRangeTolerance", 1.0e-3);

    % Riccati error scales, input weights, exact first-step decrease rate
    % and the linear cost of its single relaxation.
    cfg.clf = struct( ...
        "lateralPositionErrorScale", 0.5, ...
        "headingErrorScale", 0.1, ...
        "speedErrorScale", 0.25, ...
        "lateralVelocityErrorScale", 0.5, ...
        "yawRateErrorScale", 0.2, ...
        "frontWheelSteeringAngleWeight", 1.0, ...
        "longitudinalAccelerationWeight", 1.0, ...
        "decreaseRateFraction", 0.9, ...
        "certificateSpeedFloor", 5.0, ...
        "relaxationWeight", 100.0);

    % One joint conic solve per sample. The optional solver hook receives
    % (phase, problem); problem.defaultSolver runs the built-in coneprog.
    cfg.solver = struct( ...
        "jointFunction", [], ...
        "maxIterations", 400, ...
        "constraintTolerance", 1.0e-7, ...
        "optimalityTolerance", 1.0e-7);

    % Fallback target rectangle when an estimate publishes no extent.
    cfg.target = struct( ...
        "defaultLength", 4.8, ...
        "defaultWidth", 1.9);
end

function base = localMergeStructure(base, overrides)
    fields = fieldnames(overrides);
    for fieldIdx = 1:numel(fields)
        name = fields{fieldIdx};
        value = overrides.(name);
        if ~isfield(base, name)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "Unknown controller configuration field: %s.", name);
        end
        if isstruct(base.(name)) ...
                && isstruct(value) && isscalar(value) ...
                && isscalar(base.(name))
            base.(name) = localMergeStructure(base.(name), value);
        else
            base.(name) = value;
        end
    end
end

function actuation = localNormalizeActuation(actuation)
% Keep the acceleration-input contract at the configuration boundary.
    if ~isstruct(actuation) || ~isscalar(actuation)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "cfg must contain a scalar actuation structure.");
    end
    names = ["longitudinalAccelerationMinimum", ...
        "longitudinalAccelerationMaximum"];
    for name = names
        value = actuation.(name);
        if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
                || ~isfinite(value)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "actuation.%s must be a finite real scalar.", name);
        end
        actuation.(name) = double(value);
    end
    minimum = actuation.longitudinalAccelerationMinimum;
    maximum = actuation.longitudinalAccelerationMaximum;
    if minimum >= maximum || minimum > 0.0 || maximum < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "Longitudinal-acceleration limits must satisfy " ...
            + "aMinimum <= 0 <= aMaximum and aMinimum < aMaximum.");
    end
end

function localValidate(cfg)
    if cfg.model.speedMinimum ~= 0.0 || cfg.model.speedMaximum <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "The rest certificate requires speedMinimum = 0 and speedMaximum > 0.");
    end
    if cfg.model.scheduleSpeedFloor <= 0.0 ...
            || cfg.model.scheduleSpeedFloor > cfg.model.speedMaximum
        error("collisionAvoidanceController:invalidConfiguration", ...
            "scheduleSpeedFloor must be positive and no greater than speedMaximum.");
    end
    localValidateNonnegativeScalar(cfg.controller.stationTrustRadius, ...
        "controller.stationTrustRadius");
    localValidateNonnegativeScalar(cfg.model.lateralDomainRadius, ...
        "model.lateralDomainRadius");
    if cfg.controller.stationTrustRadius == 0.0 || cfg.model.lateralDomainRadius == 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "Station and lateral domain radii must be positive.");
    end
    if cfg.controller.horizonSteps < 2 ...
            || cfg.controller.horizonSteps ~= round(cfg.controller.horizonSteps)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "controller.horizonSteps must be an integer of at least 2.");
    end
    if cfg.controller.sampleTime <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "controller.sampleTime must be positive.");
    end
    if ~isnumeric(cfg.clf.relaxationWeight) ...
            || ~isscalar(cfg.clf.relaxationWeight) ...
            || ~isfinite(cfg.clf.relaxationWeight) ...
            || cfg.clf.relaxationWeight <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "clf.relaxationWeight must be a positive finite scalar.");
    end
    if cfg.clf.decreaseRateFraction <= 0.0 ...
            || cfg.clf.decreaseRateFraction > 1.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "clf.decreaseRateFraction must lie in (0, 1].");
    end
    if ~isnumeric(cfg.collision.clearanceMargin) ...
            || ~isscalar(cfg.collision.clearanceMargin) ...
            || ~isfinite(cfg.collision.clearanceMargin) ...
            || cfg.collision.clearanceMargin < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "collision.clearanceMargin must be a nonnegative finite " ...
            + "scalar.");
    end
    localValidateNonnegativeInteger( ...
        cfg.terminal.supportDirectionCount, "terminal.supportDirectionCount");
    if cfg.terminal.supportDirectionCount < 8
        error("collisionAvoidanceController:invalidConfiguration", ...
            "terminal.supportDirectionCount must be an integer of at least 8.");
    end
    localValidateNonnegativeScalar( ...
        cfg.controller.shiftConsistencyTolerance, ...
        "controller.shiftConsistencyTolerance");
    if ~isempty(cfg.solver.jointFunction) ...
            && ~isa(cfg.solver.jointFunction, "function_handle")
        error("collisionAvoidanceController:invalidConfiguration", ...
            "solver.jointFunction must be empty or a function handle.");
    end
    % Forward-Euler stability of the declared stage model: the lateral
    % and yaw stiffness rates scale as 1/vBar, so the sample time and
    % the schedule speed floor carry the obligation together
    % (LTV_BICYCLE_MODEL.md).
    corneringStiffness = double(cfg.tire.corneringStiffness(:));
    if isscalar(corneringStiffness)
        corneringStiffness = repmat(corneringStiffness, 2, 1);
    end
    lateralRate = sum(corneringStiffness) ...
        / (cfg.vehicle.m*cfg.model.scheduleSpeedFloor);
    yawRate = (cfg.vehicle.lf^2*corneringStiffness(1) ...
            + cfg.vehicle.lr^2*corneringStiffness(2)) ...
        / (cfg.vehicle.Iz*cfg.model.scheduleSpeedFloor);
    stiffestRate = max(lateralRate, yawRate);
    if cfg.controller.sampleTime*stiffestRate >= 2.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "The forward-Euler stage step is unstable at the declared " ...
            + "schedule speed floor: sampleTime * %.3f 1/s must stay " ...
            + "below 2.", stiffestRate);
    end
    localValidateTerminal(cfg);
end

function localValidateNonnegativeInteger(value, name)
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
            || ~isfinite(value) || value < 0.0 || value ~= round(value)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "%s must be a nonnegative integer.", name);
    end
end

function localValidateNonnegativeScalar(value, name)
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
            || ~isfinite(value) || value < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "%s must be a nonnegative finite scalar.", name);
    end
end

function localValidateTerminal(cfg)
    localValidateNonnegativeScalar(cfg.terminal.backupDeceleration, ...
        "terminal.backupDeceleration");
    if cfg.terminal.backupDeceleration <= 0.0 ...
            || cfg.terminal.backupDeceleration > -cfg.actuation.longitudinalAccelerationMinimum
        error("collisionAvoidanceController:invalidConfiguration", ...
            "backupDeceleration must be positive and within the braking limit.");
    end
end
