function cfg = collisionAvoidanceControllerConfig(userCfg)
% collisionAvoidanceControllerConfig Defaults and merge for the controller.
%
% Returns the predictive-certificate controller configuration, with supplied
% overrides merged recursively over the declared defaults. Every field
% the controller reads is defined here; a missing field is a
% configuration error at the consuming module rather than a silent
% default there.
% Signed braking-ratio limits are validated here and normalized to
% dimensionless double scalars before model and tire modules consume them.
%
% The defaults describe a mid-size passenger car with input [deltaF; beta],
% locally linearized modified Fiala tires and the held-input Frenet LTV bicycle
% stage model of LTV_BICYCLE_MODEL.md.

    if nargin < 1
        userCfg = [];
    end
    cfg = localDefaults();
    if ~isempty(userCfg)
        if ~isstruct(userCfg) || ~isscalar(userCfg)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "The configuration override must be a scalar structure.");
        end
        cfg = localMergeStructure(cfg, userCfg);
    end
    cfg.actuation = localNormalizeActuation(cfg.actuation);
    localValidate(cfg);
end

function cfg = localDefaults()
    cfg = struct();

    % Route-following cruise demand of the CLF.
    cfg.referenceSpeed = 15.0;

    % Closed-loop period and prediction horizon. Every prediction
    % stage is one sample, so the plan advances one node per sample.
    cfg.controller = struct( ...
        "sampleTime", 0.05, ...
        "horizonSteps", 48, ...
        "stationTrustRadius", 2.0);

    % Geometric clearance in metres, certified throughout every held interval.
    cfg.collision = struct("clearanceMargin", 0.25);

    % Complete encounter certificates. Separating supports
    % normals are separate certificate variables. All cells share the issued
    % held input within a sample. Certificate margins are normalized across
    % the physical hard rows; every predicted interval is certified.
    cfg.encounter = struct("perceptionExitBuffer", 0.1, ...
        "minimumCells", 2, "taylorOrder", 6, ...
        "numericalMargin", 1.0e-6, "maximumCarriedMargin", 1.0, ...
        "inputRateWeight", 0.02);

    % Vehicle geometry and inertia.
    cfg.vehicle = struct( ...
        "m", 1650.0, ...
        "Iz", 1700.0, ...
        "lf", 1.4, ...
        "lr", 1.65, ...
        "wheelbase", 3.05, ...
        "length", 4.8, ...
        "width", 1.9, ...
        "gravity", 9.81, ...
        "centerOfGravityHeight", 0.55);
    cfg.tire = struct( ...
        "corneringStiffness", [96000.0; 96000.0], ...
        "frictionCoefficient", [0.85; 0.85]);
    cfg.actuation = struct( ...
        "brakingRatioMinimum", -1.0, ...
        "brakingRatioMaximum", 1.0);

    % Passive flat-road force, separate from gross commanded acceleration.
    % Scenario adapters replace these generic values with plant parameters.
    cfg.roadLoad = struct( ...
        "airDensity", 1.225, ...
        "dragCoefficient", 0.30, ...
        "frontalArea", 2.2, ...
        "rollingCoefficient", 0.01, ...
        "rollingSpeedCoefficient", 0.0, ...
        "rollingQuarticCoefficient", 0.0, ...
        "rollingTransitionSpeed", 0.5);

    % Zero speed is admitted by the regularized scheduled model. The tire
    % denominator alone uses scheduleSpeedFloor. Geometry is certified on
    % finite station intervals and the declared lateral/heading domains.
    cfg.model = struct( ...
        "speedMinimum", 0.0, ...
        "speedMaximum", 18.0, ...
        "lateralDomainRadius", 12.0, ...
        "scheduleSpeedFloor", 1.0, ...
        "frontWheelSteeringAngleMaximum", deg2rad(40.0), ...
        "frontWheelSteeringRateMaximum", Inf, ...
        "brakingRatioRateMaximum", Inf, ...
        "frictionPolygonSides", 12, ...
        "slipAngleMaximum", deg2rad([10.0; 10.0]), ...
        "headingDomainRadius", 0.40, "linearizationPolicy", "trajectory", ...
        "lateralVelocityMaximum", 12.0, ...
        "yawRateMaximum", 5.0, ...
        "ltvModelErrorRateBound", zeros(6, 1), ...
        "plantModelResidualRateBound", zeros(6, 1));

    % Road-geometry implementation allowances.
    cfg.road = struct( ...
        "orthonormalTolerance", 1.0e-9, ...
        "parameterRangeTolerance", 1.0e-3);

    % Continuous Riccati error scales and normalized input effort weights.
    % Online input weights penalize deviation from the certificate operating input.
    % decreaseRateFraction scales the certified decay rate (1/s); slack has
    % units of V per second and a squared cost weighted by relaxationWeight.
    cfg.clf = struct( ...
        "lateralPositionErrorScale", 0.5, ...
        "headingErrorScale", 0.1, ...
        "speedErrorScale", 0.25, ...
        "lateralVelocityErrorScale", 0.5, ...
        "yawRateErrorScale", 0.2, ...
        "frontWheelSteeringAngleWeight", 1.0, ...
        "brakingRatioWeight", 1.0, ...
        "decreaseRateFraction", 0.9, ...
        "certificateSpeedFloor", 5.0, ...
        "relaxationWeight", 100.0, ...
        "referenceOffset", zeros(5, 1), ...
        "referenceRate", zeros(5, 1), "referenceEpoch", 0.0);

    % One hard-margin LP followed by a CLF SOCP. The hook receives (phase,
    % problem), with P/q/A/b/cones fields and a [plan; delta] decision.
    % problem.defaultSolver invokes the native sparse conic solver.
    cfg.solver = struct( ...
        "jointFunction", [], ...
        "maxIterations", 400, ...
        "constraintTolerance", 1.0e-7, ...
        "optimalityTolerance", 1.0e-7);

    % Fallback target rectangle when an estimate publishes no extent.
    cfg.target = struct( ...
        "defaultLength", 4.8, ...
        "defaultWidth", 1.9);
end

function base = localMergeStructure(base, overrides)
    fields = fieldnames(overrides);
    for fieldIdx = 1:numel(fields)
        name = fields{fieldIdx};
        value = overrides.(name);
        if ~isfield(base, name)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "Unknown controller configuration field: %s.", name);
        end
        if isstruct(base.(name)) ...
                && isstruct(value) && isscalar(value) ...
                && isscalar(base.(name))
            base.(name) = localMergeStructure(base.(name), value);
        else
            base.(name) = value;
        end
    end
end

function actuation = localNormalizeActuation(actuation)
% Keep the signed braking-ratio contract at the configuration boundary.
    if ~isstruct(actuation) || ~isscalar(actuation)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "cfg must contain a scalar actuation structure.");
    end
    names = ["brakingRatioMinimum", ...
        "brakingRatioMaximum"];
    for name = names
        value = actuation.(name);
        if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
                || ~isfinite(value)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "actuation.%s must be a finite real scalar.", name);
        end
        actuation.(name) = double(value);
    end
    minimum = actuation.brakingRatioMinimum;
    maximum = actuation.brakingRatioMaximum;
    if minimum < -1.0 || maximum > 1.0 ...
            || minimum >= maximum || minimum > 0.0 || maximum < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "Signed braking-ratio limits must satisfy " ...
            + "-1 <= betaMinimum <= 0 <= betaMaximum <= 1 with positive width.");
    end
end

function localValidate(cfg)
    validateattributes(cfg.encounter.perceptionExitBuffer, {'double'}, {'scalar', 'real', 'finite', 'positive'});
    for name = ["m", "Iz", "lf", "lr", "wheelbase", "length", "width", "gravity"]
        localValidateNonnegativeScalar(cfg.vehicle.(name), "vehicle."+name);
        if cfg.vehicle.(name) == 0
            error("collisionAvoidanceController:invalidConfiguration", "vehicle.%s must be positive.", name);
        end
    end
    if ~isscalar(string(cfg.model.linearizationPolicy)) ...
            || ~any(string(cfg.model.linearizationPolicy)==["currentState","trajectory","cruise"])
        error("collisionAvoidanceController:invalidConfiguration","Unknown linearization policy.");
    end
    for name = ["speedMinimum", "speedMaximum", "scheduleSpeedFloor", "headingDomainRadius", ...
            "frontWheelSteeringAngleMaximum"]
        localValidateNonnegativeScalar(cfg.model.(name), "model."+name);
    end
    localValidateNonnegativeScalar(cfg.referenceSpeed, "referenceSpeed");
    localValidateNonnegativeScalar(cfg.controller.sampleTime, "controller.sampleTime");
    localValidateNonnegativeScalar(cfg.controller.horizonSteps, "controller.horizonSteps");
    validateattributes(cfg.model.frontWheelSteeringRateMaximum,{'double'},{'scalar','real','positive'});
    validateattributes(cfg.model.brakingRatioRateMaximum,{'double'},{'scalar','real','positive'});
    validateattributes(cfg.model.frictionPolygonSides,{'double'},{'scalar','integer','>=',4});
    validateattributes(cfg.encounter.minimumCells, {'double'}, ...
        {'scalar', 'integer', '>=', 1});
    validateattributes(cfg.encounter.taylorOrder, {'double'}, ...
        {'scalar', 'integer', '>=', 3, '<=', 10});
    for name = ["numericalMargin", "maximumCarriedMargin", ...
            "inputRateWeight"]
        localValidateNonnegativeScalar(cfg.encounter.(name), "encounter."+name);
    end
    if cfg.encounter.numericalMargin <= 0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "encounter.numericalMargin must be positive.");
    end
    validateattributes(cfg.clf.referenceRate, {'double'}, ...
        {'real', 'finite', 'size', [5, 1]});
    validateattributes(cfg.clf.referenceOffset, {'double'}, ...
        {'real', 'finite', 'size', [5, 1]});
    validateattributes(cfg.clf.referenceEpoch, {'double'}, {'real', 'finite', 'scalar'});
    validateattributes(cfg.model.lateralVelocityMaximum, {'double'}, {'real', 'finite', 'scalar', 'positive'});
    validateattributes(cfg.model.yawRateMaximum, {'double'}, {'real', 'finite', 'scalar', 'positive'});
    for name = string(fieldnames(cfg.roadLoad)).'
        localValidateNonnegativeScalar(cfg.roadLoad.(name), "roadLoad."+name);
    end
    if cfg.roadLoad.rollingTransitionSpeed <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "roadLoad.rollingTransitionSpeed must be positive.");
    end
    if cfg.model.speedMaximum <= cfg.model.speedMinimum
        error("collisionAvoidanceController:invalidConfiguration", ...
            "The finite speed domain must have a positive width.");
    end
    if cfg.model.scheduleSpeedFloor <= 0.0 ...
            || cfg.model.scheduleSpeedFloor > cfg.model.speedMaximum
        error("collisionAvoidanceController:invalidConfiguration", ...
            "scheduleSpeedFloor must be positive and no greater than speedMaximum.");
    end
    localValidateNonnegativeScalar(cfg.controller.stationTrustRadius, ...
        "controller.stationTrustRadius");
    localValidateNonnegativeScalar(cfg.model.lateralDomainRadius, ...
        "model.lateralDomainRadius");
    for name = ["ltvModelErrorRateBound", "plantModelResidualRateBound"]
        value = cfg.model.(name);
        if ~isnumeric(value) || ~isreal(value) || ~isvector(value) ...
                || numel(value) ~= 6 || any(~isfinite(value)) || any(value < 0)
            error("collisionAvoidanceController:invalidConfiguration", ...
                "model.%s must contain six finite nonnegative continuous-rate bounds.", name);
        end
        cfg.model.(name) = double(value(:));
    end
    if cfg.controller.stationTrustRadius == 0.0 || cfg.model.lateralDomainRadius == 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "Station and lateral domain radii must be positive.");
    end
    if cfg.controller.horizonSteps < 1 ...
            || cfg.controller.horizonSteps ~= round(cfg.controller.horizonSteps)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "controller.horizonSteps must be a positive integer.");
    end
    if cfg.controller.sampleTime <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "controller.sampleTime must be positive.");
    end
    if ~isnumeric(cfg.clf.relaxationWeight) ...
            || ~isscalar(cfg.clf.relaxationWeight) ...
            || ~isfinite(cfg.clf.relaxationWeight) ...
            || cfg.clf.relaxationWeight <= 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "clf.relaxationWeight must be a positive finite scalar.");
    end
    localValidateNonnegativeScalar(cfg.clf.decreaseRateFraction, "clf.decreaseRateFraction");
    if cfg.clf.decreaseRateFraction <= 0.0 ...
            || cfg.clf.decreaseRateFraction > 1.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "clf.decreaseRateFraction must lie in (0, 1].");
    end
    if ~isnumeric(cfg.collision.clearanceMargin) ...
            || ~isscalar(cfg.collision.clearanceMargin) ...
            || ~isfinite(cfg.collision.clearanceMargin) ...
            || cfg.collision.clearanceMargin < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "collision.clearanceMargin must be a nonnegative finite " ...
            + "scalar.");
    end
    if ~isempty(cfg.solver.jointFunction) ...
            && ~isa(cfg.solver.jointFunction, "function_handle")
        error("collisionAvoidanceController:invalidConfiguration", ...
            "solver.jointFunction must be empty or a function handle.");
    end
    for name = ["constraintTolerance", "optimalityTolerance"]
        localValidateNonnegativeScalar(cfg.solver.(name), "solver."+name);
        if cfg.solver.(name) == 0.0
            error("collisionAvoidanceController:invalidConfiguration", ...
                "solver.%s must be positive.", name);
        end
    end
    localValidateNonnegativeScalar(cfg.solver.maxIterations, "solver.maxIterations");
    if cfg.solver.maxIterations < 1 ...
            || cfg.solver.maxIterations ~= fix(cfg.solver.maxIterations)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "solver.maxIterations must be a positive integer.");
    end
    localValidateVehicleAndTire(cfg);
end

function localValidateNonnegativeScalar(value, name)
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
            || ~isfinite(value) || value < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "%s must be a nonnegative finite scalar.", name);
    end
end

function localValidateVehicleAndTire(cfg)
    friction = cfg.tire.frictionCoefficient;
    if ~isnumeric(friction) || ~isreal(friction) || ~isvector(friction) ...
            || ~ismember(numel(friction), [1, 2]) ...
            || any(~isfinite(friction)) || any(friction <= 0.0)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "tire.frictionCoefficient must be positive scalar or front/rear values.");
    end
    for name = ["gravity", "lf", "lr"]
        localValidateNonnegativeScalar(cfg.vehicle.(name), "vehicle."+name);
        if cfg.vehicle.(name) == 0.0
            error("collisionAvoidanceController:invalidConfiguration", ...
                "vehicle.%s must be positive.", name);
        end
    end
end
