function experiment = controllerDesignExperimentConfig()
% controllerDesignExperimentConfig Paired crossing-target experiments.
% SI units throughout. Both trials use the same controller and plant.
% The nominal counterfactual omits target observations only; it introduces
% no alternate controller algorithm. The target moves at constant velocity.
% Duration and the final observation window bound data collection only.
% The recovery objective is eventual nominal cruise, with no settling deadline.

    experiment = struct();
    experiment.duration = 10.0;
    experiment.referenceSpeed = 15.0;
    experiment.targetSpeed = 8.0;
    experiment.nominalCollisionTime = 6.0;
    experiment.perceptionRange = 50.0;
    experiment.egoSize = [4.8; 1.9];
    experiment.targetSize = [4.8; 1.9];
    experiment.roadBoundaryOffsets = [6.0; 6.0];
    experiment.shoulderWidth = 2.6;
    experiment.centerlineSpacing = 0.1;
    experiment.controllerConfiguration = struct( ...
        "controller", struct("sampleTime", 0.05, "horizonSteps", 24), ...
        "solver", struct("constraintTolerance", 1.0e-6, ...
            "optimalityTolerance", 1.0e-6));
    experiment.criteria = struct( ...
        "minimumCruiseDuration", 2.0, ...
        "speedTolerance", 0.5, ...
        "lateralTolerance", 0.2, ...
        "headingTolerance", 0.02, ...
        "finalObservationWindow", 1.0, ...
        "contactTolerance", 1.0e-9);
    names = ["straight", "arc"];
    curvatures = [0.0, 1.0/400.0];
    station = experiment.referenceSpeed*experiment.nominalCollisionTime;
    for idx = 1:2
        curvature = curvatures(idx);
        heading = curvature*station;
        if curvature == 0.0
            collisionPosition = [station; 0.0];
        else
            collisionPosition = [sin(heading); 1.0-cos(heading)]/curvature;
        end
        targetVelocity = experiment.targetSpeed*[-sin(heading); cos(heading)];
        scenes(idx) = struct( ...
            "name", names(idx), ...
            "curvature", curvature, ...
            "initialYawRate", experiment.referenceSpeed*curvature, ...
            "collisionPosition", collisionPosition, ...
            "collisionHeading", heading, ...
            "targetInitialPosition", collisionPosition ...
                - experiment.nominalCollisionTime*targetVelocity, ...
            "targetVelocity", targetVelocity, ...
            "targetYaw", atan2(targetVelocity(2), targetVelocity(1))); %#ok<AGROW>
    end
    experiment.scenes = scenes;
end
