root=fileparts(fileparts(fileparts(mfilename('fullpath'))));cd(root);
output=tempname;mkdir(output);
files={'tests/nonlinearPredictiveSafetyTest.m','tests/terminalContinuationTest.m', ...
    'tests/freePoseTerminalTest.m','tests/movingTargetFlowTest.m', ...
    'tests/collisionAvoidanceControllerConfigTest.m','tests/controllerKernelTest.m', ...
    'tests/controllerSourceBudgetTest.m','tests/modifiedFialaTireTest.m', ...
    'tests/longitudinalRoadLoadTest.m','tests/controllerInputGeometryTest.m', ...
    'tests/sweptCollisionIntervalTest.m'};
results=runtests(files);entries=table(results);
writetable(entries,fullfile(output,'regression.csv'));
save(fullfile(output,'regression.mat'),'results');
sourceFiles={'controller/collisionAvoidanceController.m','controller/solvePredictiveControl.m', ...
    'controller/nonlinearBicycleModel.m','controller/modifiedFialaTire.m', ...
    'controller/predictiveSafetyGeometry.m','controller/terminalContinuation.m', ...
    'config/collisionAvoidanceControllerConfig.m','scripts/buildControllerKernels.m', ...
    'scripts/runNonlinearPredictiveSafetyValidation.m','scripts/validateNonlinearPredictiveController.m', ...
    'tests/twoStagePredictiveControlTest.m','tests/clfNominalRecoveryTest.m'};
findings=cell(size(sourceFiles));
for index=1:numel(sourceFiles)
    findings{index}=struct('file',sourceFiles{index},'findings',checkcode(sourceFiles{index},'-config=factory','-id'));
end
file=fopen(fullfile(output,'code-analysis.json'),'w');
fprintf(file,'%s\n',jsonencode([findings{:}],PrettyPrint=true));fclose(file);
assertSuccess(results);
