function information = buildAvoidanceGeometryKernel()
%buildAvoidanceGeometryKernel Compile complete held-interval geometry.
    root = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(root,"controller"));
    output = fullfile(root,"solver","bicycle");
    if ~isfolder(output),mkdir(output);end
    addpath(output);
    wrapper = fullfile(output,"avoidanceCellRowsKernel.m");
    file = fopen(wrapper,"w");
    assert(file>=0,"buildAvoidanceGeometryKernel:writeFailed","Cannot create generated adapter.");
    cleanup = onCleanup(@() fclose(file));
    fprintf(file,"function rows = avoidanceCellRowsKernel(data)\nrows = avoidanceSafetyGeometry.cellRows(data);\nend\n");
    clear cleanup;
    target = struct("center",zeros(8,1),"radius",zeros(8,1), ...
        "contract",struct("jerkBound",zeros(2,1),"yawAccelerationBound",0), ...
        "halfLength",0,"halfWidth",0);
    boundary = struct("coefficients",zeros(1,3),"safeSideSign",0, ...
        "longitudinalDirection",zeros(2,1),"lateralDirection",zeros(2,1),"origin",zeros(2,1), ...
        "parameterRange",zeros(2,1),"normalDistanceErrorBound",0);
    data = struct("frame",coder.typeof(zeros(12,1)),"nominal",coder.typeof(0,[6,Inf],[false,true]), ...
        "targets",coder.typeof(target,[Inf,1],[true,false]), ...
        "boundaries",coder.typeof(boundary,[Inf,1],[true,false]), ...
        "settings",coder.typeof(zeros(5,1)),"duration",coder.typeof(0), ...
        "degree",coder.typeof(0));
    data = coder.newtype('struct',data,[Inf,1],[true,false]);
    settings = coder.config("mex");settings.GenerateReport = false;settings.EnableOpenMP = false;
    clear avoidanceCellRowsKernelMex;
    codegen("-config",settings,wrapper,"-args",{data}, ...
        "-o",fullfile(output,"avoidanceCellRowsKernelMex"),"-d",fullfile(output,"generatedGeometry"));
    wrapper = fullfile(output,"avoidanceProjectedRowsKernel.m");
    file = fopen(wrapper,"w");
    assert(file>=0,"buildAvoidanceGeometryKernel:writeFailed","Cannot create generated adapter.");
    cleanup = onCleanup(@() fclose(file));
    fprintf(file,"function rows = avoidanceProjectedRowsKernel(data)\nrows = avoidanceSafetyGeometry.projectRows(data);\nend\n");
    clear cleanup;
    clear avoidanceProjectedRowsKernelMex;
    codegen("-config",settings,wrapper,"-args",{localProjectionType()}, ...
        "-o",fullfile(output,"avoidanceProjectedRowsKernelMex"),"-d",fullfile(output,"generatedProjection"));
    rehash;
    information = struct("binary",fullfile(output,"avoidanceCellRowsKernelMex."+mexext), ...
        "projectionBinary",fullfile(output,"avoidanceProjectedRowsKernelMex."+mexext), ...
        "matlabVersion",string(version),"algorithmSource","controller/avoidanceSafetyGeometry.m");
end

function data = localProjectionType()
    scalar = coder.typeof(0);
    cfg = struct("model",struct("lateralDomainRadius",0,"headingDomainRadius",0, ...
        "speedMinimum",0,"speedMaximum",0,"lateralVelocityMaximum",0,"yawRateMaximum",0, ...
        "scheduleSpeedFloor",0,"slipAngleMaximum",zeros(2,1)), ...
        "vehicle",struct("lf",0,"lr",0));
    tube = struct("stage",scalar,"map",coder.typeof(0,[6,Inf,Inf],[false,true,true]), ...
        "offset",coder.typeof(0,[6,Inf],[false,true]), ...
        "localStateMap",coder.typeof(0,[6,6,Inf],[false,false,true]), ...
        "localInputMap",coder.typeof(0,[6,2,Inf],[false,false,true]), ...
        "localOffset",coder.typeof(0,[6,Inf],[false,true]), ...
        "numericalRadius",coder.typeof(0,[6,Inf],[false,true]));
    rows = struct("state",coder.typeof(0,[Inf,6],[true,false]), ...
        "bound",coder.typeof(0,[Inf,Inf],[true,true]), ...
        "source",coder.typeof(0,[Inf,1],[true,false]),"normals",coder.typeof(0,[2,Inf],[false,true]));
    data = struct("cfg",coder.typeof(cfg),"tube",coder.newtype('struct',tube), ...
        "nominal",coder.typeof(0,[6,Inf],[false,true]),"stationRange",coder.typeof(zeros(2,1)), ...
        "stateRadius",coder.typeof(0,[6,Inf],[false,true]),"scheduleSpeed",scalar, ...
        "geometricRows",coder.newtype('struct',rows),"planCount",scalar);
    data = coder.newtype('struct',data,[Inf,1],[true,false]);
end
