function [centerline, geometry] = circularCenterlinePolyline(options)
% circularCenterlinePolyline Sample a left circular arc as a centerline.
%
% Builds the chord-aligned polygonal sampling of a constant-curvature
% left circle from the scenario options (Radius, ArcLengthBefore,
% ArcLengthAfter, CenterlineSpacing), so the ego starts with zero heading
% error, and returns the sampled N-by-2 centerline together with the
% exact arc geometry the scenario evaluators use.
    spacing = options.centerlineSpacing;
    firstIndex = -ceil(options.arcLengthBefore / spacing) - 1;
    lastIndex = ceil(options.arcLengthAfter / spacing);
    sampleIndex = (firstIndex:lastIndex).' + 0.5;
    arcLength = spacing * sampleIndex;
    angle = arcLength / options.radius;
    initialChordHeight = options.radius ...
        * (1.0 - cos(spacing / (2.0 * options.radius)));

    centerline = [ ...
        options.radius * sin(angle), ...
        options.radius * (1.0 - cos(angle)) - initialChordHeight];
    geometry = struct( ...
        "direction", "left", ...
        "radius", options.radius, ...
        "curvature", 1.0 / options.radius, ...
        "arcLengthBefore", options.arcLengthBefore, ...
        "arcLengthAfter", options.arcLengthAfter, ...
        "centerlineSpacing", spacing, ...
        "maximumPolylineSagitta", initialChordHeight);
end
