function coupling = evaluateManeuverCoupling(result, varargin)
% evaluateManeuverCoupling Quantify simultaneous body-frame acceleration.
%
% Longitudinal and lateral acceleration are reconstructed from consecutive
% truth states [x, y, yaw, v_x, v_y, yawRate]. A coupled interval satisfies
% both absolute acceleration thresholds. The maneuver is significant when
% one uninterrupted run of coupled intervals meets MinimumCoupledDuration.

    options = localOptions(varargin{:});
    [time, state] = localControlTrace(result);
    intervalDuration = diff(time);
    longitudinalVelocity = state(:, 4);
    lateralVelocity = state(:, 5);
    yawRate = state(:, 6);
    midpointLateralVelocity = 0.5 * ( ...
        lateralVelocity(1:end-1) + lateralVelocity(2:end));
    midpointLongitudinalVelocity = 0.5 * ( ...
        longitudinalVelocity(1:end-1) ...
        + longitudinalVelocity(2:end));
    midpointYawRate = 0.5 * (yawRate(1:end-1) + yawRate(2:end));

    longitudinalAcceleration = ...
        diff(longitudinalVelocity) ./ intervalDuration ...
        - midpointYawRate .* midpointLateralVelocity;
    lateralAcceleration = ...
        diff(lateralVelocity) ./ intervalDuration ...
        + midpointYawRate .* midpointLongitudinalVelocity;
    coupledMask = ...
        abs(longitudinalAcceleration) ...
            >= options.longitudinalAccelerationThreshold ...
        & abs(lateralAcceleration) ...
            >= options.lateralAccelerationThreshold;
    [maximumContinuousDuration, runCount] = ...
        localMaximumContinuousDuration(coupledMask, intervalDuration);
    simultaneousAccelerationProduct = ...
        abs(longitudinalAcceleration .* lateralAcceleration);

    coupling = struct( ...
        "time", time(2:end), ...
        "intervalDuration", intervalDuration, ...
        "longitudinalAcceleration", longitudinalAcceleration, ...
        "lateralAcceleration", lateralAcceleration, ...
        "longitudinalAccelerationThreshold", ...
            options.longitudinalAccelerationThreshold, ...
        "lateralAccelerationThreshold", ...
            options.lateralAccelerationThreshold, ...
        "minimumCoupledDuration", options.minimumCoupledDuration, ...
        "coupledMask", coupledMask, ...
        "coupledSampleCount", nnz(coupledMask), ...
        "coupledDuration", sum(intervalDuration(coupledMask)), ...
        "maximumContinuousCoupledDuration", ...
            maximumContinuousDuration, ...
        "coupledRunCount", runCount, ...
        "maximumAbsoluteLongitudinalAcceleration", ...
            max(abs(longitudinalAcceleration), [], "omitmissing"), ...
        "maximumAbsoluteLateralAcceleration", ...
            max(abs(lateralAcceleration), [], "omitmissing"), ...
        "maximumSimultaneousAccelerationProduct", ...
            max(simultaneousAccelerationProduct, [], "omitmissing"), ...
        "significant", maximumContinuousDuration ...
            + localTolerance(options.minimumCoupledDuration) ...
            >= options.minimumCoupledDuration, ...
        "accelerationFrame", "egoBody", ...
        "calculationMethod", ...
            "finiteDifferenceVelocityWithMidpointRotatingFrameTerm");
end

function [time, state] = localControlTrace(result)
    if ~isstruct(result) || ~isscalar(result) ...
            || ~isfield(result, "controlTime") ...
            || ~isfield(result, "controlState")
        error("evaluateManeuverCoupling:invalidResult", ...
            "Result must contain controlTime and controlState.");
    end
    time = double(result.controlTime(:));
    state = double(result.controlState);
    if size(state, 2) ~= 6 || size(state, 1) ~= numel(time) ...
            || numel(time) < 2 || any(~isfinite(time)) ...
            || any(~isfinite(state), "all") ...
            || any(diff(time) <= 0.0)
        error("evaluateManeuverCoupling:invalidControlTrace", ...
            "Control trace must contain at least two finite, " ...
            + "strictly time-ordered six-state samples.");
    end
end

function [maximumDuration, runCount] = ...
        localMaximumContinuousDuration(mask, intervalDuration)
    transitions = diff([false; mask(:); false]);
    runStart = find(transitions == 1);
    runEnd = find(transitions == -1) - 1;
    runCount = numel(runStart);
    maximumDuration = 0.0;
    for runIdx = 1:runCount
        runDuration = sum( ...
            intervalDuration(runStart(runIdx):runEnd(runIdx)));
        maximumDuration = max(maximumDuration, runDuration);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "LongitudinalAccelerationThreshold", ...
        1.0, @localPositiveScalar);
    addParameter(parser, "LateralAccelerationThreshold", ...
        3.0, @localPositiveScalar);
    addParameter(parser, "MinimumCoupledDuration", ...
        0.3, @localPositiveScalar);
    parse(parser, varargin{:});
    options = struct( ...
        "longitudinalAccelerationThreshold", ...
            double(parser.Results.LongitudinalAccelerationThreshold), ...
        "lateralAccelerationThreshold", ...
            double(parser.Results.LateralAccelerationThreshold), ...
        "minimumCoupledDuration", ...
            double(parser.Results.MinimumCoupledDuration));
end

function tolerance = localTolerance(value)
    tolerance = 100.0 * eps(max(1.0, abs(value)));
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end
