function safety = evaluatePerceivedRoadBoundarySafety( ...
        plantTrace, perception, sampleTime, vehicleSize)
% evaluatePerceivedRoadBoundarySafety Check the complete ego rectangle.
%
% Every plant-output pose is paired with the road-boundary fit used over
% its enclosing control interval. The exact minimum of each quadratic
% boundary function over the complete oriented rectangle is then reduced
% by the continuous source-polyline fit-error bound.

    localValidateInputs(plantTrace, perception, sampleTime, vehicleSize);
    sampleCount = numel(plantTrace.time);
    boundaryCount = 2;
    fittedMargin = NaN(sampleCount, boundaryCount);
    conservativeMargin = NaN(sampleCount, boundaryCount);
    sourceDomainCovered = false(sampleCount, boundaryCount);
    controlStep = NaN(sampleCount, 1);
    boundaryIds = ["right", "left"];
    timeTolerance = 100.0 * eps(max( ...
        1.0, max([sampleTime; plantTrace.time(:)])));

    for sampleIdx = 1:sampleCount
        stepIdx = ceil( ...
            (plantTrace.time(sampleIdx) - timeTolerance) / sampleTime);
        stepIdx = min(max(stepIdx, 1), numel(perception));
        controlStep(sampleIdx) = stepIdx;
        road = perception{stepIdx}.roadGeometry;
        pose = [ ...
            plantTrace.positionX(sampleIdx); ...
            plantTrace.positionY(sampleIdx); ...
            plantTrace.yaw(sampleIdx)];
        for boundaryIdx = 1:boundaryCount
            boundary = road.boundaries(boundaryIdx);
            sourceDomainCovered(sampleIdx, boundaryIdx) = ...
                localRectangleInsideParameterRange( ...
                    pose, vehicleSize, boundary);
            if sourceDomainCovered(sampleIdx, boundaryIdx)
                fittedMargin(sampleIdx, boundaryIdx) = ...
                    quadraticRoadBoundaryRectangleMargin( ...
                        pose, vehicleSize, boundary);
                conservativeMargin(sampleIdx, boundaryIdx) = ...
                    fittedMargin(sampleIdx, boundaryIdx) ...
                    - boundary.verticalFitErrorBound;
            end
        end
    end

    tolerance = 1.0e-9;
    allRectanglesCovered = all(sourceDomainCovered, "all");
    noBoundaryCrossing = allRectanglesCovered ...
        && all(conservativeMargin >= -tolerance, "all");
    if isempty(conservativeMargin)
        minimumMargin = NaN;
        minimumByBoundary = NaN(1, boundaryCount);
    else
        minimumMargin = min(conservativeMargin, [], "all");
        minimumByBoundary = min(conservativeMargin, [], 1);
    end
    safety = struct( ...
        "boundaryIds", boundaryIds, ...
        "controlStep", controlStep, ...
        "fittedBoundaryFunctionMargin", fittedMargin, ...
        "conservativeBoundaryFunctionMargin", ...
            conservativeMargin, ...
        "sourceDomainCovered", sourceDomainCovered, ...
        "allRectanglesCoveredByPerceivedSegments", ...
            allRectanglesCovered, ...
        "minimumBoundaryFunctionMargin", minimumMargin, ...
        "minimumBoundaryFunctionMarginByBoundary", ...
            minimumByBoundary, ...
        "noBoundaryCrossing", noBoundaryCrossing, ...
        "contactTolerance", tolerance, ...
        "method", ...
            "exact rectangle/quadratic minimum minus continuous " ...
                + "source-polyline fit-error bound");
end

function covered = localRectangleInsideParameterRange( ...
        pose, vehicleSize, boundary)
    halfLength = 0.5 * vehicleSize(1);
    halfWidth = 0.5 * vehicleSize(2);
    heading = [cos(pose(3)); sin(pose(3))];
    normal = [-heading(2); heading(1)];
    centerParameter = boundary.longitudinalDirection.' ...
        * (pose(1:2) - boundary.origin);
    parameterRadius = halfLength * abs( ...
            boundary.longitudinalDirection.' * heading) ...
        + halfWidth * abs( ...
            boundary.longitudinalDirection.' * normal);
    rectangleRange = centerParameter ...
        + [-parameterRadius, parameterRadius];
    tolerance = 100.0 * eps(max( ...
        [1.0, abs(rectangleRange), abs(boundary.parameterRange)]));
    covered = rectangleRange(1) ...
            >= boundary.parameterRange(1) - tolerance ...
        && rectangleRange(2) ...
            <= boundary.parameterRange(2) + tolerance;
end

function localValidateInputs( ...
        plantTrace, perception, sampleTime, vehicleSize)
    requiredFields = [ ...
        "time", "positionX", "positionY", "yaw"];
    if ~isstruct(plantTrace) ...
            || ~all(isfield(plantTrace, requiredFields))
        error("evaluatePerceivedRoadBoundarySafety:invalidTrace", ...
            "plantTrace is missing pose fields.");
    end
    sampleCount = numel(plantTrace.time);
    if any([ ...
            numel(plantTrace.positionX), ...
            numel(plantTrace.positionY), ...
            numel(plantTrace.yaw)] ~= sampleCount)
        error("evaluatePerceivedRoadBoundarySafety:invalidTrace", ...
            "Plant trace pose fields must have equal lengths.");
    end
    if sampleCount > 0 && isempty(perception)
        error("evaluatePerceivedRoadBoundarySafety:missingPerception", ...
            "Each nonempty trace needs road-perception samples.");
    end
    if ~iscell(perception)
        error("evaluatePerceivedRoadBoundarySafety:invalidPerception", ...
            "perception must be a cell array.");
    end
    if ~isnumeric(sampleTime) || ~isscalar(sampleTime) ...
            || ~isfinite(sampleTime) || sampleTime <= 0.0
        error("evaluatePerceivedRoadBoundarySafety:invalidSampleTime", ...
            "sampleTime must be positive and finite.");
    end
    if ~isnumeric(vehicleSize) || numel(vehicleSize) ~= 2 ...
            || any(~isfinite(vehicleSize), "all") ...
            || any(vehicleSize <= 0.0, "all")
        error("evaluatePerceivedRoadBoundarySafety:invalidVehicleSize", ...
            "vehicleSize must contain positive length and width.");
    end
end
