function evaluation = evaluatePreDetectionCruise(result, varargin)
% evaluatePreDetectionCruise Verify cruise before target perception.
%
% The target must start outside the declared sensing range, remain
% undetected for the requested duration while the ego follows its
% centerline at the reference speed, and then produce an in-range
% detection. Ranges are evaluated from target truth and plant/control
% truth only for scenario acceptance; they are not supplied to the
% controller.

    options = localOptions(varargin{:});
    localValidateResult(result);

    detectionAvailable = logical( ...
        result.perception.targetDetectionAvailable(:));
    sampleCount = min([ ...
        numel(detectionAvailable), ...
        numel(result.controlTime), ...
        size(result.controlState, 1), ...
        numel(result.controlTracking.lateralError), ...
        numel(result.controlTracking.headingError), ...
        numel(result.targetTruthAtControlSample)]);
    detectionAvailable = detectionAvailable(1:sampleCount);
    sampleTime = result.controlTime(1:sampleCount);

    targetRange = NaN(sampleCount, 1);
    for sampleIdx = 1:sampleCount
        target = result.targetTruthAtControlSample{sampleIdx};
        targetPosition = target.targetPositionInertial(:);
        egoPosition = result.controlState(sampleIdx, 1:2).';
        targetRange(sampleIdx) = norm(targetPosition-egoPosition);
    end

    firstDetectionIdx = find(detectionAvailable, 1, "first");
    if isempty(firstDetectionIdx)
        firstDetectionTime = NaN;
        firstDetectionRange = NaN;
        preDetectionIdx = 1:sampleCount;
    else
        firstDetectionTime = sampleTime(firstDetectionIdx);
        firstDetectionRange = targetRange(firstDetectionIdx);
        preDetectionIdx = 1:(firstDetectionIdx-1);
    end

    if isempty(preDetectionIdx)
        maximumSpeedError = NaN;
        maximumLateralError = NaN;
        maximumHeadingError = NaN;
        cruiseMaintained = false;
    else
        speedError = result.controlState(preDetectionIdx, 4) ...
            - result.scenario.referenceSpeed;
        lateralError = result.controlTracking ...
            .lateralError(preDetectionIdx);
        headingError = result.controlTracking ...
            .headingError(preDetectionIdx);
        maximumSpeedError = max(abs(speedError));
        maximumLateralError = max(abs(lateralError));
        maximumHeadingError = max(abs(headingError));
        cruiseMaintained = ...
            maximumSpeedError <= options.speedTolerance ...
            && maximumLateralError <= options.lateralTolerance ...
            && maximumHeadingError <= options.headingTolerance;
    end

    rangeMaximum = result.perception.rangeMaximum;
    rangeTolerance = 100.0*eps(max(1.0, rangeMaximum));
    startsOutsideRange = ~detectionAvailable(1) ...
        && targetRange(1) > rangeMaximum+rangeTolerance;
    detectionTransitionObserved = ~isempty(firstDetectionIdx) ...
        && firstDetectionIdx > 1;
    firstDetectionIsInRange = detectionTransitionObserved ...
        && firstDetectionRange <= rangeMaximum+rangeTolerance;
    preDetectionDuration = firstDetectionTime-sampleTime(1);
    durationSatisfied = isfinite(preDetectionDuration) ...
        && preDetectionDuration ...
            >= options.minimumDuration-rangeTolerance;
    passed = startsOutsideRange ...
        && detectionTransitionObserved ...
        && firstDetectionIsInRange ...
        && durationSatisfied ...
        && cruiseMaintained;

    evaluation = struct( ...
        "passed", passed, ...
        "startsOutsideRange", startsOutsideRange, ...
        "detectionTransitionObserved", ...
            detectionTransitionObserved, ...
        "firstDetectionIsInRange", firstDetectionIsInRange, ...
        "initialTargetRange", targetRange(1), ...
        "firstDetectionTime", firstDetectionTime, ...
        "firstDetectionRange", firstDetectionRange, ...
        "preDetectionDuration", preDetectionDuration, ...
        "minimumRequiredDuration", options.minimumDuration, ...
        "preDetectionSampleCount", numel(preDetectionIdx), ...
        "cruiseMaintained", cruiseMaintained, ...
        "maximumSpeedError", maximumSpeedError, ...
        "maximumLateralError", maximumLateralError, ...
        "maximumHeadingError", maximumHeadingError, ...
        "speedTolerance", options.speedTolerance, ...
        "lateralTolerance", options.lateralTolerance, ...
        "headingTolerance", options.headingTolerance, ...
        "targetRangeAtControlSample", targetRange, ...
        "detectionAvailable", detectionAvailable, ...
        "method", ...
            "truth-audited out-of-range cruise followed by " ...
                + "an in-range sensor detection");
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "MinimumDuration", 2.0, ...
        @localNonnegativeScalar);
    addParameter(parser, "SpeedTolerance", 0.5, ...
        @localNonnegativeScalar);
    addParameter(parser, "LateralTolerance", 0.25, ...
        @localNonnegativeScalar);
    addParameter(parser, "HeadingTolerance", 0.03, ...
        @localNonnegativeScalar);
    parse(parser, varargin{:});
    options = struct( ...
        "minimumDuration", ...
            double(parser.Results.MinimumDuration), ...
        "speedTolerance", ...
            double(parser.Results.SpeedTolerance), ...
        "lateralTolerance", ...
            double(parser.Results.LateralTolerance), ...
        "headingTolerance", ...
            double(parser.Results.HeadingTolerance));
end

function localValidateResult(result)
    requiredFields = [ ...
        "perception", "controlTime", "controlState", ...
        "controlTracking", "targetTruthAtControlSample", ...
        "scenario"];
    if ~isstruct(result) || ~isscalar(result) ...
            || ~all(isfield(result, requiredFields)) ...
            || ~isfield(result.perception, ...
                "targetDetectionAvailable") ...
            || ~isfield(result.perception, "rangeMaximum") ...
            || ~isfield(result.controlTracking, "lateralError") ...
            || ~isfield(result.controlTracking, "headingError") ...
            || ~isfield(result.scenario, "referenceSpeed")
        error("evaluatePreDetectionCruise:invalidResult", ...
            "Result does not contain synchronized scenario signals.");
    end
    if isempty(result.perception.targetDetectionAvailable)
        error("evaluatePreDetectionCruise:emptyResult", ...
            "At least one perception sample is required.");
    end
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end
