function assessment = evaluateControllerDesignExperiment( ...
        nominal, avoidance, scene, experiment)
% evaluateControllerDesignExperiment Evaluate physical control-step poses.
% SAT determines contact independently of the controller's distance code.
% Dense plant outputs and inter-sample motion do not enter collision tests.
% An interrupted run never establishes collision freedom for the scenario.
% Actual road margins use the analytic scene, independently of perceived fits.

    criteria = experiment.criteria;
    [nominalMargin, nominalTarget] = localSeparation(nominal, scene, experiment);
    [avoidanceMargin, avoidanceTarget] = localSeparation(avoidance, scene, experiment);
    firstContact = find(nominalMargin <= criteria.contactTolerance, 1);
    nominalContactTime = NaN;
    if ~isempty(firstContact)
        nominalContactTime = nominal.controlTime(firstContact);
    end
    firstVisible = find(avoidance.attempts.targetVisible, 1);
    firstDetectionTime = NaN;
    firstDetectionRange = NaN;
    if ~isempty(firstVisible)
        firstDetectionTime = avoidance.attempts.time(firstVisible);
        firstDetectionRange = norm(avoidanceTarget(firstVisible,:) ...
            - avoidance.controlState(firstVisible,1:2));
    end
    ranges = vecnorm(avoidanceTarget-avoidance.controlState(:,1:2), 2, 2);
    expectedVisible = ranges(1:numel(avoidance.attempts.time)) ...
        <= experiment.perceptionRange ...
            + 100.0*eps(experiment.perceptionRange);
    visibilityPass = isequal(expectedVisible, avoidance.attempts.targetVisible) ...
        && ranges(1) > experiment.perceptionRange ...
        && isfinite(firstDetectionTime) ...
        && firstDetectionTime >= criteria.minimumCruiseDuration;
    cruiseSamples = avoidance.controlTime <= firstDetectionTime;
    cruisePass = any(cruiseSamples) ...
        && localTrackingPass(avoidance, cruiseSamples, experiment);
    nominalThreatPass = nominal.metrics.controllerCompletedScenario ...
        && nominal.metrics.cruiseMaintained && isfinite(nominalContactTime);
    completed = avoidance.metrics.controllerCompletedScenario ...
        && ~avoidance.failure.occurred ...
        && abs(avoidance.controlTime(end)-experiment.duration) < 1.0e-9;
    noContactObserved = all(isfinite(avoidanceMargin)) ...
        && all(avoidanceMargin > criteria.contactTolerance);
    collisionPass = completed && noContactObserved;
    roadMargin = localRoadMargin(avoidance.controlState, scene, experiment);
    roadPass = completed && all(roadMargin >= -criteria.contactTolerance);
    recoverySamples = avoidance.controlTime ...
        >= experiment.duration-criteria.recoveryWindow-1.0e-9;
    recoveryPass = completed && any(recoverySamples) ...
        && firstDetectionTime < experiment.duration-criteria.recoveryWindow ...
        && localTrackingPass(avoidance, recoverySamples, experiment);
    cfg = avoidance.controllerConfiguration;
    commandPass = ~isempty(avoidance.command);
    maxFrictionUtilization = NaN;
    if commandPass
        commands = [avoidance.command{:}];
        inputs = [commands.actuatorInput];
        utilization = [commands.axleFrictionUtilization];
        maxFrictionUtilization = max(utilization, [], "all");
        tolerance = 10.0*cfg.solver.constraintTolerance;
        commandPass = all(isfinite(inputs), "all") ...
            && all(abs(inputs(1,:)) <= cfg.model.frontWheelSteeringAngleMaximum+tolerance) ...
            && all(inputs(2,:) >= cfg.actuation.longitudinalAccelerationMinimum-tolerance) ...
            && all(inputs(2,:) <= cfg.actuation.longitudinalAccelerationMaximum+tolerance) ...
            && maxFrictionUtilization <= 1.0+tolerance;
    end
    metadata = avoidance.attempts.metadata;
    hasMetadata = cellfun(@(entry) ~isempty(entry), metadata);
    hardRowsPass = false;
    maxHardRowViolation = NaN;
    if any(hasMetadata)
        entries = [metadata{hasMetadata}];
        maxHardRowViolation = max([entries.hardRowViolation]);
        hardRowsPass = completed && all(hasMetadata) ...
            && all([entries.hardCbfSatisfied]) ...
            && all([entries.terminalInvariantCertified]);
    end
    controlsPass = completed && commandPass && hardRowsPass;
    deadlinePass = completed && all(isfinite(avoidance.attempts.solveTime)) ...
        && all(avoidance.attempts.solveTime <= cfg.controller.sampleTime);
    scenarioValid = nominalThreatPass && visibilityPass && cruisePass;
    functionalPass = scenarioValid && collisionPass && roadPass ...
        && recoveryPass && controlsPass;

    summary = table(scene.name, firstDetectionTime, firstDetectionRange, ...
        nominalContactTime, min(nominalMargin), min(avoidanceMargin), ...
        avoidance.controlTime(end), min(roadMargin), ...
        max(avoidance.attempts.solveTime), ...
        scenarioValid, cruisePass, completed, collisionPass, roadPass, ...
        recoveryPass, controlsPass, functionalPass, deadlinePass, ...
        VariableNames=["scene", "firstDetectionTime", "firstDetectionRange", ...
        "nominalContactTime", "nominalMinimumSatMargin", "avoidanceMinimumSatMargin", ...
        "completedTime", "minimumRoadMargin", "maximumSolveTime", ...
        "scenarioValid", "cruisePass", "completed", "collisionPass", "roadPass", ...
        "recoveryPass", "controlsPass", "functionalPass", "deadlinePass"]);
    assessment = struct( ...
        "summary", summary, "noContactObserved", noContactObserved, ...
        "nominalThreatPass", nominalThreatPass, "visibilityPass", visibilityPass, ...
        "maximumCommandedFrictionUtilization", maxFrictionUtilization, ...
        "maximumHardRowViolation", maxHardRowViolation, ...
        "nominalSeparationMargin", nominalMargin, ...
        "avoidanceSeparationMargin", avoidanceMargin, ...
        "nominalTargetPosition", nominalTarget, ...
        "avoidanceTargetPosition", avoidanceTarget, ...
        "roadMargin", roadMargin, ...
        "collisionEvaluation", "oriented rectangles at control steps only");
end

function [margin, targetPosition] = localSeparation(result, scene, experiment)
    time = result.controlTime;
    targetPosition = scene.targetInitialPosition.' + time*scene.targetVelocity.';
    margin = rectangleSeparationMargin( ...
        result.controlState(:,1:2), result.controlState(:,3), ...
        targetPosition, repmat(scene.targetYaw, numel(time), 1), ...
        experiment.egoSize(1), experiment.egoSize(2), ...
        experiment.targetSize(1), experiment.targetSize(2));
end

function passed = localTrackingPass(result, samples, experiment)
    passed = all(abs(result.controlState(samples,4)-experiment.referenceSpeed) ...
            <= experiment.criteria.speedTolerance) ...
        && all(abs(result.controlTracking.lateralError(samples)) ...
            <= experiment.criteria.lateralTolerance) ...
        && all(abs(result.controlTracking.headingError(samples)) ...
            <= experiment.criteria.headingTolerance);
end

function margin = localRoadMargin(state, scene, experiment)
    halfSize = experiment.egoSize/2.0;
    rightExtent = experiment.roadBoundaryOffsets(1)+experiment.shoulderWidth;
    leftExtent = experiment.roadBoundaryOffsets(2)+experiment.shoulderWidth;
    margin = NaN(size(state,1), 1);
    corner = halfSize.*[1, 1, -1, -1; 1, -1, -1, 1];
    for idx = 1:size(state,1)
        yaw = state(idx,3);
        rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
        corners = state(idx,1:2).'+rotation*corner;
        if scene.curvature == 0.0
            margin(idx) = min([min(corners(2,:))+rightExtent, ...
                leftExtent-max(corners(2,:))]);
        else
            radius = 1.0/scene.curvature;
            center = [0.0; radius];
            centerBody = rotation.'*(center-state(idx,1:2).');
            minimumRadius = norm(max(abs(centerBody)-halfSize, 0.0));
            maximumRadius = max(vecnorm(corners-center, 2, 1));
            margin(idx) = min([radius+rightExtent-maximumRadius, ...
                minimumRadius-(radius-leftExtent)]);
        end
    end
end
