function perception = fitPerceivedRoadBoundaries( ...
        centerline, egoPose, varargin)
% fitPerceivedRoadBoundaries Fit local quadratic road-boundary segments.
%
% The supplied right and left offsets locate the lane edges. A shoulder is
% added outside each edge, and the two outer shoulder edges become the hard
% road curbs. Only curb samples inside the declared radial perception range
% are fitted and returned as roadGeometry.boundaries. Those finite fits use
% coveragePolicy="perceptionLimited" and are never extrapolated.
%
% The terminal-set geometry is not another fitted trajectory. The supplied
% centerline is the nominal path, and the two terminal components are
% represented directly by their constant signed Frenet lateral-offset bands
% I_R and I_L. Finite fitted curves remain sensor products used only by the
% ordinary road-safety rows.

    options = localOptions(varargin{:});
    centerline = localCenterline( ...
        centerline, min(0.25, options.perceptionRange / 100.0));
    egoPose = localEgoPose(egoPose);
    [~, vertexNormal] = localVertexFrames(centerline);
    projection = localCenterlineProjection(egoPose(1:2), centerline);
    routeHeading = [cos(egoPose(3)); sin(egoPose(3))];
    if projection.tangent.' * routeHeading <= 0.0
        error("fitPerceivedRoadBoundaries:oppositeRouteDirection", ...
            "The ordered centerline must point along the ego route.");
    end

    longitudinalDirection = projection.tangent;
    lateralDirection = [ ...
        -longitudinalDirection(2); longitudinalDirection(1)];
    origin = projection.point;
    rightOuterTruth = centerline ...
        - (options.rightOffset + options.shoulderWidth) ...
            * vertexNormal.';
    leftOuterTruth = centerline ...
        + (options.leftOffset + options.shoulderWidth) ...
            * vertexNormal.';
    routeBranchId = options.routeBranchId;

    rightOuterBoundary = localFitBoundary( ...
        rightOuterTruth, egoPose(1:2), origin, ...
        longitudinalDirection, lateralDirection, ...
        options.perceptionRange, 1.0, ...
        "right-road-curb", routeBranchId, ...
        "perceptionLimited", "sensedRoadCurb");
    leftOuterBoundary = localFitBoundary( ...
        leftOuterTruth, egoPose(1:2), origin, ...
        longitudinalDirection, lateralDirection, ...
        options.perceptionRange, -1.0, ...
        "left-road-curb", routeBranchId, ...
        "perceptionLimited", "sensedRoadCurb");
    boundaries = [rightOuterBoundary; leftOuterBoundary];
    terminalLateralOffsetBands = struct( ...
        "right", [ ...
            -(options.rightOffset+options.shoulderWidth), ...
            -options.rightOffset], ...
        "left", [ ...
            options.leftOffset, ...
            options.leftOffset+options.shoulderWidth]);
    roadGeometry = struct( ...
        "centerline", centerline, ...
        "boundaries", boundaries, ...
        "terminalLateralOffsetBands", ...
            terminalLateralOffsetBands, ...
        "boundaryGeometrySource", "sensedRoadCurb", ...
        "terminalSetGeometrySource", ...
            "nominalPathFrenetOffsetBands", ...
        "routeBranchId", routeBranchId);

    perception = struct( ...
        "rangeMaximum", options.perceptionRange, ...
        "rightOffset", options.rightOffset, ...
        "leftOffset", options.leftOffset, ...
        "shoulderWidth", options.shoulderWidth, ...
        "rightOuterOffset", ...
            options.rightOffset + options.shoulderWidth, ...
        "leftOuterOffset", ...
            options.leftOffset + options.shoulderWidth, ...
        "egoPose", egoPose, ...
        "frameOrigin", origin, ...
        "longitudinalDirection", longitudinalDirection, ...
        "lateralDirection", lateralDirection, ...
        "routeBranchId", routeBranchId, ...
        "coveragePolicy", "perceptionLimited", ...
        "terminalLateralOffsetBands", ...
            terminalLateralOffsetBands, ...
        "terminalSetGeometrySource", ...
            "nominalPathFrenetOffsetBands", ...
        "roadGeometry", roadGeometry);
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "PerceptionRange", 30.0, ...
        @localPositiveScalar);
    addParameter(parser, "RightOffset", 6.0, ...
        @localPositiveScalar);
    addParameter(parser, "LeftOffset", 8.0, ...
        @localPositiveScalar);
    addParameter(parser, "ShoulderWidth", 2.6, ...
        @localPositiveScalar);
    addParameter(parser, "RouteBranchId", "perceived-route", ...
        @localTextScalar);
    parse(parser, varargin{:});
    options = struct( ...
        "perceptionRange", double(parser.Results.PerceptionRange), ...
        "rightOffset", double(parser.Results.RightOffset), ...
        "leftOffset", double(parser.Results.LeftOffset), ...
        "shoulderWidth", double(parser.Results.ShoulderWidth), ...
        "routeBranchId", string(parser.Results.RouteBranchId));
end

function centerline = localCenterline(value, maximumSpacing)
    if ~isnumeric(value) || ~isreal(value) ...
            || size(value, 2) ~= 2 || size(value, 1) < 2 ...
            || any(~isfinite(value), "all")
        error("fitPerceivedRoadBoundaries:invalidCenterline", ...
            "centerline must be a finite real N-by-2 array with N >= 2.");
    end
    centerline = double(value);
    segment = diff(centerline, 1, 1);
    segmentLength = vecnorm(segment, 2, 2);
    if any(segmentLength <= 0.0)
        error("fitPerceivedRoadBoundaries:invalidCenterline", ...
            "Consecutive centerline samples must be distinct.");
    end
    subdivisionCount = max(1, ceil(segmentLength / maximumSpacing));
    sampleCount = sum(subdivisionCount) + 1;
    resampled = NaN(sampleCount, 2);
    firstSample = 1;
    for segmentIdx = 1:numel(segmentLength)
        fraction = (0:(subdivisionCount(segmentIdx) - 1)).' ...
            / subdivisionCount(segmentIdx);
        segmentSamples = centerline(segmentIdx, :) ...
            + fraction .* segment(segmentIdx, :);
        lastSample = firstSample + subdivisionCount(segmentIdx) - 1;
        resampled(firstSample:lastSample, :) = segmentSamples;
        firstSample = lastSample + 1;
    end
    resampled(end, :) = centerline(end, :);
    centerline = resampled;
end

function egoPose = localEgoPose(value)
    if ~isnumeric(value) || ~isreal(value) || numel(value) ~= 3 ...
            || any(~isfinite(value), "all")
        error("fitPerceivedRoadBoundaries:invalidEgoPose", ...
            "egoPose must contain finite [x; y; yaw].");
    end
    egoPose = double(value(:));
end

function [vertexTangent, vertexNormal] = localVertexFrames(centerline)
    segment = diff(centerline, 1, 1);
    segmentTangent = segment ./ vecnorm(segment, 2, 2);
    vertexTangent = [ ...
        segmentTangent(1, :); ...
        segmentTangent(1:(end - 1), :) ...
            + segmentTangent(2:end, :); ...
        segmentTangent(end, :)];
    tangentNorm = vecnorm(vertexTangent, 2, 2);
    if any(tangentNorm <= 100.0 * eps)
        error("fitPerceivedRoadBoundaries:reversingCenterline", ...
            "The centerline contains a local direction reversal.");
    end
    vertexTangent = vertexTangent ./ tangentNorm;
    vertexNormal = [-vertexTangent(:, 2), vertexTangent(:, 1)].';
end

function projection = localCenterlineProjection(position, centerline)
    segment = diff(centerline, 1, 1);
    segmentLengthSquared = sum(segment.^2, 2);
    relative = position.' - centerline(1:(end - 1), :);
    fraction = sum(relative .* segment, 2) ./ segmentLengthSquared;
    fraction = min(max(fraction, 0.0), 1.0);
    point = centerline(1:(end - 1), :) + fraction .* segment;
    [~, segmentIdx] = min(sum((position.' - point).^2, 2));
    tangent = segment(segmentIdx, :).';
    tangent = tangent / norm(tangent);
    projection = struct( ...
        "point", point(segmentIdx, :).', ...
        "tangent", tangent, ...
        "segmentIndex", segmentIdx, ...
        "fraction", fraction(segmentIdx));
end

function boundary = localFitBoundary( ...
        truthPoints, egoPosition, origin, ...
        longitudinalDirection, lateralDirection, ...
        perceptionRange, safeSideSign, boundaryId, routeBranchId, ...
        coveragePolicy, geometrySource)
    pointRange = vecnorm(truthPoints - egoPosition.', 2, 2);
    rangeTolerance = 100.0 * eps(max(1.0, perceptionRange));
    visible = pointRange <= perceptionRange + rangeTolerance;
    visible = localConnectedVisibility(visible, pointRange);
    boundary = localFitSelectedBoundary( ...
        truthPoints, visible, pointRange, origin, ...
        longitudinalDirection, lateralDirection, ...
        safeSideSign, boundaryId, routeBranchId, ...
        coveragePolicy, geometrySource);
end

function boundary = localFitSelectedBoundary( ...
        truthPoints, selected, pointRange, origin, ...
        longitudinalDirection, lateralDirection, ...
        safeSideSign, boundaryId, routeBranchId, ...
        coveragePolicy, geometrySource)
    selectedIdx = find(selected);
    if numel(selectedIdx) < 3
        error("fitPerceivedRoadBoundaries:insufficientPoints", ...
            "Boundary %s has fewer than three source samples " ...
            + "inside its finite fitting interval.", boundaryId);
    end

    sourcePoints = truthPoints(selectedIdx, :);
    localPoint = sourcePoints.' - origin;
    parameter = longitudinalDirection.' * localPoint;
    lateral = lateralDirection.' * localPoint;
    [parameter, order] = sort(parameter(:));
    lateral = lateral(order);
    sourcePoints = sourcePoints(order, :);
    pointRange = pointRange(selectedIdx(order));
    if any(diff(parameter) <= 0.0)
        error("fitPerceivedRoadBoundaries:nonGraphBoundary", ...
            "Boundary %s is not a single-valued local graph.", ...
            boundaryId);
    end

    coefficients = polyfit(parameter, lateral, 2);
    fittedLateral = polyval(coefficients, parameter);
    residual = lateral - fittedLateral;
    verticalErrorBound = localContinuousPolylineFitError( ...
        parameter, lateral, coefficients);
    parameterRange = [parameter(1), parameter(end)];

    boundary = struct( ...
        "origin", origin, ...
        "longitudinalDirection", longitudinalDirection, ...
        "lateralDirection", lateralDirection, ...
        "coefficients", coefficients, ...
        "parameterRange", parameterRange, ...
        "safeSideSign", safeSideSign, ...
        "normalDistanceErrorBound", verticalErrorBound, ...
        "routeBranchId", routeBranchId, ...
        "boundaryId", string(boundaryId), ...
        "coveragePolicy", string(coveragePolicy), ...
        "geometrySource", string(geometrySource), ...
        "sensedParameterRange", parameterRange, ...
        "sourceParameterRange", parameterRange, ...
        "sourcePoints", sourcePoints, ...
        "sourceParameter", parameter, ...
        "sourceLateralCoordinate", lateral, ...
        "sourcePointRange", pointRange, ...
        "sourcePointCount", numel(parameter), ...
        "maximumSourcePointRange", max(pointRange), ...
        "rootMeanSquareFitResidual", sqrt(mean(residual.^2)), ...
        "maximumAbsoluteFitResidual", max(abs(residual)), ...
        "verticalFitErrorBound", verticalErrorBound);
end

function connected = localConnectedVisibility(visible, pointRange)
    visibleIdx = find(visible);
    connected = false(size(visible));
    if isempty(visibleIdx)
        return;
    end
    gap = [0; find(diff(visibleIdx) > 1); numel(visibleIdx)];
    blockCount = numel(gap) - 1;
    blockMinimumRange = Inf(blockCount, 1);
    for blockIdx = 1:blockCount
        block = visibleIdx((gap(blockIdx) + 1):gap(blockIdx + 1));
        blockMinimumRange(blockIdx) = min(pointRange(block));
    end
    [~, selectedBlock] = min(blockMinimumRange);
    selected = visibleIdx( ...
        (gap(selectedBlock) + 1):gap(selectedBlock + 1));
    connected(selected) = true;
end

function errorBound = localContinuousPolylineFitError( ...
        parameter, lateral, coefficients)
    segmentCount = numel(parameter) - 1;
    errorBound = 0.0;
    for segmentIdx = 1:segmentCount
        s0 = parameter(segmentIdx);
        s1 = parameter(segmentIdx + 1);
        l0 = lateral(segmentIdx);
        l1 = lateral(segmentIdx + 1);
        lineSlope = (l1 - l0) / (s1 - s0);
        candidate = NaN(3, 1);
        candidate(1:2) = [s0; s1];
        candidateCount = 2;
        if coefficients(1) ~= 0.0
            stationary = (lineSlope - coefficients(2)) ...
                / (2.0 * coefficients(1));
            if stationary > s0 && stationary < s1
                candidateCount = 3;
                candidate(candidateCount) = stationary;
            end
        end
        candidate = candidate(1:candidateCount);
        lineValue = l0 + lineSlope * (candidate - s0);
        residual = lineValue - polyval(coefficients, candidate);
        errorBound = max(errorBound, max(abs(residual)));
    end
    errorBound = errorBound ...
        + 100.0 * eps(max(1.0, max(abs(lateral))));
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localTextScalar(value)
    valid = ischar(value) ...
        || (isstring(value) && isscalar(value) ...
            && ~ismissing(value) && strlength(value) > 0);
end
