function summary = generateEstimatedStateAvoidanceVideos(varargin)
% generateEstimatedStateAvoidanceVideos Simulate and render three videos.
%
% The active straight and circular cases and the retained S-curve
% visualization case use the configured
% GNSS/IMU/gyroscope/radar estimator-controller interface. The target
% starts outside that range. The ego first cruises on the centerline, then
% the target enters the shared sensing range and is provisionally acquired
% from the first radar sample using the configured oncoming-speed prior.
% The internal target track may coast for the configured finite timeout,
% but it is published to the controller only while radar currently
% observes it; an expired track is retired. Every video shows the shared
% target/road sensing range, the current finite quadratic fits of the
% sensed left and right outer curbs, and the known nominal-path-offset
% shoulder corridors. The retained S curve is generated here for the
% requested visualization but remains outside the active two-road
% controller acceptance entry point.
% MP4 files are written to the repository root unless OutputDirectory is
% set.

    options = localOptions(varargin{:});
    repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repositoryRoot, "config"));
    addpath(fullfile(repositoryRoot, "scripts"));

    outputDirectory = options.outputDirectory;
    if strlength(outputDirectory) == 0
        outputDirectory = string(repositoryRoot);
    end

    scenarioResult = runEstimatedStateAvoidanceScenarios( ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetSpeed=options.targetSpeed, ...
        StraightTargetInitialDistance= ...
            options.straightTargetInitialDistance, ...
        StraightTargetLateralOffset= ...
            options.straightTargetLateralOffset, ...
        StraightTargetWidth=options.straightTargetWidth, ...
        CurvedTargetInitialDistance= ...
            options.curvedTargetInitialDistance, ...
        CurvedTargetWidth=options.curvedTargetWidth, ...
        CurvedTargetCollisionLateralOffset= ...
            options.curvedTargetCollisionLateralOffset, ...
        CurvedArcLengthAfter=options.curvedArcLengthAfter, ...
        CircularRadius=options.circularRadius, ...
        RecoveryWindow=options.recoveryWindow, ...
        RequireCruiseRecovery=true, ...
        MinimumPreDetectionCruiseDuration= ...
            options.minimumPreDetectionCruiseDuration, ...
        RequirePreDetectionCruise=true, ...
        LongitudinalAccelerationThreshold= ...
            options.longitudinalAccelerationThreshold, ...
        LateralAccelerationThreshold= ...
            options.lateralAccelerationThreshold, ...
        MinimumCoupledDuration=options.minimumCoupledDuration, ...
        RequireCoupledManeuver=true, ...
        Seed=options.seed, ...
        Report=options.report, ...
        Progress=options.progress);
    if ~scenarioResult.allScenariosPassed
        failedScenario = scenarioResult.scenarioNames( ...
            ~scenarioResult.scenarioPassed);
        failureText = strjoin(failedScenario, ", ");
        if ~scenarioResult.couplingRequirementMet
            if strlength(failureText) > 0
                failureText = failureText ...
                    + "; coupled-maneuver suite coverage";
            else
                failureText = "coupled-maneuver suite coverage";
            end
        end
        error("generateEstimatedStateAvoidanceVideos:" ...
            + "scenarioAcceptanceFailed", ...
            "Refusing to render failed scenario(s): %s.", ...
            failureText);
    end

    sCurveConfiguration = scenarioResult.configuration;
    sCurveConfiguration.randomSeed = options.seed+2;
    sCurveConfiguration.observer.ego.domain.yawRateMaximum = max( ...
        sCurveConfiguration.observer.ego.domain.yawRateMaximum, ...
        1.5*options.referenceSpeed*options.sCurveMaximumCurvature);
    sCurve = runVaryingCurvatureStraightTargetAvoidanceScenario( ...
        MaximumCurvature=options.sCurveMaximumCurvature, ...
        CurvatureWavelength=options.sCurveCurvatureWavelength, ...
        ArcLengthBefore=options.sCurveArcLengthBefore, ...
        ArcLengthAfter=options.sCurveArcLengthAfter, ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetSpeed=options.targetSpeed, ...
        TargetInitialDistance=options.sCurveTargetInitialDistance, ...
        TargetCollisionLateralOffset= ...
            options.sCurveTargetCollisionLateralOffset, ...
        TargetLength=5.0, ...
        TargetWidth=options.sCurveTargetWidth, ...
        PerceptionRange=30.0, ...
        RightRoadBoundaryOffset=6.0, ...
        LeftRoadBoundaryOffset=8.0, ...
        RoadShoulderWidth=2.6, ...
        EgoLength=5.0, EgoWidth=2.0, ...
        UseStateEstimator=true, ...
        EstimatorConfiguration=sCurveConfiguration, ...
        RecoveryWindow=options.recoveryWindow, ...
        RecoverySpeedTolerance=0.5, ...
        RecoveryLateralTolerance=0.2, ...
        RecoveryHeadingTolerance=0.02, ...
        Plot=false, Report=false, Progress=options.progress);
    sCurve.maneuverCoupling = evaluateManeuverCoupling( ...
        sCurve, ...
        LongitudinalAccelerationThreshold= ...
            options.longitudinalAccelerationThreshold, ...
        LateralAccelerationThreshold= ...
            options.lateralAccelerationThreshold, ...
        MinimumCoupledDuration=options.minimumCoupledDuration);
    sCurve.preDetectionCruise = evaluatePreDetectionCruise( ...
        sCurve, ...
        MinimumDuration=options.minimumPreDetectionCruiseDuration, ...
        SpeedTolerance=0.5, ...
        LateralTolerance=0.25, ...
        HeadingTolerance=0.03);
    sCurvePassed = localScenarioPassed(sCurve);

    scenarioResult.sCurve = sCurve;
    scenarioResult.scenarioNames = [ ...
        scenarioResult.scenarioNames; "sCurve"];
    scenarioResult.scenarioPassed = [ ...
        scenarioResult.scenarioPassed; sCurvePassed];
    scenarioResult.coupledScenario = [ ...
        scenarioResult.coupledScenario; ...
        sCurve.maneuverCoupling.significant];
    scenarioResult.couplingRequirementMet = ...
        ~scenarioResult.requireCoupledManeuver ...
        || any(scenarioResult.coupledScenario);
    scenarioResult.allScenariosPassed = ...
        all(scenarioResult.scenarioPassed) ...
        && scenarioResult.couplingRequirementMet;
    if ~scenarioResult.allScenariosPassed
        failedScenario = scenarioResult.scenarioNames( ...
            ~scenarioResult.scenarioPassed);
        failureText = strjoin(failedScenario, ", ");
        if ~scenarioResult.couplingRequirementMet
            failureText = strjoin( ...
                [failureText; "coupled-maneuver suite coverage"], ...
                ", ");
        end
        error("generateEstimatedStateAvoidanceVideos:" ...
            + "scenarioAcceptanceFailed", ...
            "Refusing to render failed scenario(s): %s.", ...
            failureText);
    end

    scenarioFields = ["straight"; "circular"; "sCurve"];
    scenarioLabels = [ ...
        "Straight-road oncoming-target avoidance"; ...
        compose("Circular-road (R = %.0f m) " ...
            + "straight-target avoidance", ...
            options.circularRadius); ...
        compose("Finite S-curve (|kappa|max = %.3f 1/m) " ...
            + "straight-target avoidance", ...
            options.sCurveMaximumCurvature)];
    fileNames = [ ...
        "estimated_state_avoidance_straight.mp4"; ...
        "estimated_state_avoidance_circular.mp4"; ...
        "estimated_state_avoidance_s_curve.mp4"];
    video = cell(numel(scenarioFields), 1);
    for scenarioIdx = 1:numel(scenarioFields)
        outputPath = fullfile( ...
            outputDirectory, fileNames(scenarioIdx));
        if options.progress
            fprintf("Rendering %s\n", outputPath);
        end
        video{scenarioIdx} = renderEstimatedStateAvoidanceVideo( ...
            scenarioResult.(scenarioFields(scenarioIdx)), ...
            outputPath, ...
            FramePeriod=options.framePeriod, ...
            FrameRate=options.frameRate, ...
            Quality=options.quality, ...
            HoldLastFrameSeconds=options.holdLastFrameSeconds, ...
            FigureVisible=options.figureVisible, ...
            ScenarioLabel=scenarioLabels(scenarioIdx), ...
            FfmpegPreset=options.ffmpegPreset, ...
            FfmpegCrf=options.ffmpegCrf);
    end
    video = vertcat(video{:});

    summary = struct( ...
        "scenarioResult", scenarioResult, ...
        "video", video, ...
        "allScenariosPassed", scenarioResult.allScenariosPassed, ...
        "allVideosCreated", all(isfile(string({video.outputPath}))));
    if options.report
        localReport(summary);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "OutputDirectory", "", @localTextScalar);
    % Match the suite's recovery-observation interval.
    addParameter(parser, "Duration", 18.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 10.0, @localPositiveScalar);
    addParameter(parser, "TargetSpeed", 10.0, @localPositiveScalar);
    addParameter(parser, "StraightTargetInitialDistance", ...
        100.0, @localPositiveScalar);
    addParameter(parser, "StraightTargetLateralOffset", ...
        0.8, @localFiniteScalar);
    addParameter(parser, "StraightTargetWidth", ...
        2.00, @localPositiveScalar);
    addParameter(parser, "CurvedTargetInitialDistance", ...
        100.0, @localPositiveScalar);
    addParameter(parser, "CurvedTargetWidth", ...
        2.00, @localPositiveScalar);
    addParameter(parser, "CurvedTargetCollisionLateralOffset", ...
        1.2, @localFiniteScalar);
    addParameter(parser, "CurvedArcLengthAfter", ...
        300.0, @localPositiveScalar);
    addParameter(parser, "Seed", 20260728, @localIntegerScalar);
    addParameter(parser, "CircularRadius", 60.0, ...
        @localPositiveScalar);
    addParameter(parser, "SCurveMaximumCurvature", 0.01, ...
        @localPositiveScalar);
    addParameter(parser, "SCurveCurvatureWavelength", 80.0, ...
        @localPositiveScalar);
    addParameter(parser, "SCurveArcLengthBefore", 40.0, ...
        @localNonnegativeScalar);
    addParameter(parser, "SCurveArcLengthAfter", 300.0, ...
        @localPositiveScalar);
    addParameter(parser, "SCurveTargetInitialDistance", 80.0, ...
        @localPositiveScalar);
    addParameter(parser, "SCurveTargetCollisionLateralOffset", ...
        1.2, @localFiniteScalar);
    addParameter(parser, "SCurveTargetWidth", 2.0, ...
        @localPositiveScalar);
    addParameter(parser, "RecoveryWindow", 1.0, ...
        @localPositiveScalar);
    addParameter(parser, "MinimumPreDetectionCruiseDuration", ...
        2.0, @localNonnegativeScalar);
    addParameter(parser, "LongitudinalAccelerationThreshold", ...
        1.0, @localPositiveScalar);
    addParameter(parser, "LateralAccelerationThreshold", ...
        3.0, @localPositiveScalar);
    addParameter(parser, "MinimumCoupledDuration", ...
        0.3, @localPositiveScalar);
    addParameter(parser, "FramePeriod", 0.05, @localPositiveScalar);
    addParameter(parser, "FrameRate", 20.0, @localPositiveScalar);
    addParameter(parser, "Quality", 90.0, @localValidQuality);
    addParameter(parser, "HoldLastFrameSeconds", ...
        1.0, @localNonnegativeScalar);
    addParameter(parser, "FigureVisible", false, @localLogicalScalar);
    addParameter(parser, "FfmpegPreset", "medium", @localTextScalar);
    addParameter(parser, "FfmpegCrf", 18.0, @localValidCrf);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", true, @localLogicalScalar);
    parse(parser, varargin{:});
    options = struct( ...
        "outputDirectory", string(parser.Results.OutputDirectory), ...
        "duration", double(parser.Results.Duration), ...
        "referenceSpeed", double(parser.Results.ReferenceSpeed), ...
        "targetSpeed", double(parser.Results.TargetSpeed), ...
        "straightTargetInitialDistance", ...
            double(parser.Results.StraightTargetInitialDistance), ...
        "straightTargetLateralOffset", ...
            double(parser.Results.StraightTargetLateralOffset), ...
        "straightTargetWidth", ...
            double(parser.Results.StraightTargetWidth), ...
        "curvedTargetInitialDistance", ...
            double(parser.Results.CurvedTargetInitialDistance), ...
        "curvedTargetWidth", ...
            double(parser.Results.CurvedTargetWidth), ...
        "curvedTargetCollisionLateralOffset", ...
            double(parser.Results ...
                .CurvedTargetCollisionLateralOffset), ...
        "curvedArcLengthAfter", ...
            double(parser.Results.CurvedArcLengthAfter), ...
        "seed", double(parser.Results.Seed), ...
        "circularRadius", double(parser.Results.CircularRadius), ...
        "sCurveMaximumCurvature", ...
            double(parser.Results.SCurveMaximumCurvature), ...
        "sCurveCurvatureWavelength", ...
            double(parser.Results.SCurveCurvatureWavelength), ...
        "sCurveArcLengthBefore", ...
            double(parser.Results.SCurveArcLengthBefore), ...
        "sCurveArcLengthAfter", ...
            double(parser.Results.SCurveArcLengthAfter), ...
        "sCurveTargetInitialDistance", ...
            double(parser.Results.SCurveTargetInitialDistance), ...
        "sCurveTargetCollisionLateralOffset", ...
            double(parser.Results ...
                .SCurveTargetCollisionLateralOffset), ...
        "sCurveTargetWidth", ...
            double(parser.Results.SCurveTargetWidth), ...
        "recoveryWindow", double(parser.Results.RecoveryWindow), ...
        "minimumPreDetectionCruiseDuration", ...
            double(parser.Results ...
                .MinimumPreDetectionCruiseDuration), ...
        "longitudinalAccelerationThreshold", ...
            double(parser.Results.LongitudinalAccelerationThreshold), ...
        "lateralAccelerationThreshold", ...
            double(parser.Results.LateralAccelerationThreshold), ...
        "minimumCoupledDuration", ...
            double(parser.Results.MinimumCoupledDuration), ...
        "framePeriod", double(parser.Results.FramePeriod), ...
        "frameRate", double(parser.Results.FrameRate), ...
        "quality", double(parser.Results.Quality), ...
        "holdLastFrameSeconds", ...
            double(parser.Results.HoldLastFrameSeconds), ...
        "figureVisible", logical(parser.Results.FigureVisible), ...
        "ffmpegPreset", string(parser.Results.FfmpegPreset), ...
        "ffmpegCrf", double(parser.Results.FfmpegCrf), ...
        "report", logical(parser.Results.Report), ...
        "progress", logical(parser.Results.Progress));
end

function localReport(summary)
    fprintf("\nEstimator-in-the-loop avoidance videos\n");
    for videoIdx = 1:numel(summary.video)
        video = summary.video(videoIdx);
        fprintf("  %s\n", video.outputPath);
        fprintf("    %dx%d, %.1f fps, %d frames, %.2f s, %.1f MiB\n", ...
            video.width, video.height, video.frameRate, ...
            video.frameCount, video.videoDuration, ...
            video.fileSizeBytes/(1024.0^2));
        fprintf("    minimum d_rect %.4f m, collision free: %d\n", ...
            video.minimumSeparatingAxisMargin, video.collisionFree);
        fprintf("    perception %.1f m; %d road fits; " ...
            + "minimum road margin %.4f m; contained: %d\n", ...
            video.perceptionRange, ...
            video.perceivedRoadBoundaryCount, ...
            video.minimumRoadBoundaryMargin, ...
            video.noRoadBoundaryCrossing);
        fprintf("    target first detected at %.2f s after " ...
            + "%.2f s of out-of-range cruise\n", ...
            video.firstTargetDetectionTime, ...
            video.preDetectionCruiseDuration);
        fprintf("    cruise recovered: %d; final-window " ...
            + "speed/lateral/course-heading errors " ...
            + "%.3f m/s / %.3f m / %.3f rad\n", ...
            video.cruiseRecovered, ...
            video.maximumRecoverySpeedError, ...
            video.maximumRecoveryLateralError, ...
            video.maximumRecoveryHeadingError);
        fprintf("    coupled maneuver: %d; longest %.2f s; " ...
            + "peak |a_x| / |a_y| %.2f / %.2f m/s^2\n", ...
            video.coupledManeuverObserved, ...
            video.maximumContinuousCoupledDuration, ...
            video.maximumAbsoluteLongitudinalAcceleration, ...
            video.maximumAbsoluteLateralAcceleration);
    end
    fprintf("  Scenarios passed: %d; videos created: %d\n\n", ...
        summary.allScenariosPassed, summary.allVideosCreated);
end

function passed = localScenarioPassed(result)
    passed = ~result.failure.occurred ...
        && result.metrics.controllerCompletedScenario ...
        && result.avoidance.baselineCollides ...
        && result.avoidance.collisionFree ...
        && result.roadSafety.noBoundaryCrossing ...
        && result.avoidance.passedTarget ...
        && result.avoidance.remainedMoving ...
        && result.avoidance.recoveredCruise ...
        && result.estimator.metrics.allEstimatesFinite ...
        && result.estimator.metrics.controllerInputsFromEstimator ...
        && result.estimator.metrics.sensorContractValid ...
        && result.estimator.metrics.targetAcquisitionOccurred ...
        && result.estimator.metrics.allRadarDetectionsWithinRange ...
        && result.preDetectionCruise.passed;
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localIntegerScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value == floor(value);
end

function valid = localValidQuality(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0 && value <= 100.0;
end

function valid = localValidCrf(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0 && value <= 51.0;
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localTextScalar(value)
    valid = ischar(value) || (isstring(value) && isscalar(value));
end
