function varargout = nrmmEstimatorControllerAdapter(action, varargin)
% nrmmEstimatorControllerAdapter Connect synthetic sensors to the NRMM.
%
% This adapter is intentionally one-way:
%   plant/target truth -> allowed synthetic sensors -> NRMM -> controller.
% Plant truth is used only to synthesize measurements and evaluate results.

    action = lower(string(action));
    switch action
        case "initialize"
            [varargout{1}, varargout{2}] = localInitialize(varargin{:});
        case "sample"
            [varargout{1}, varargout{2}, varargout{3}, ...
                varargout{4}, varargout{5}] = localSample(varargin{:});
        otherwise
            error("nrmmEstimatorControllerAdapter:invalidAction", ...
                "action must be 'initialize' or 'sample'.");
    end
end

function [context, initialization] = localInitialize( ...
        cfg, initialEgoTruth, targetStateFunction)
    localAddProjectPaths();
    localValidateConfiguration(cfg);
    if ~isa(targetStateFunction, "function_handle")
        error("nrmmEstimatorControllerAdapter:invalidTargetFunction", ...
            "targetStateFunction must be a function handle.");
    end

    samplePeriod = cfg.observer.runtime.samplePeriod;
    historyStepCount = round( ...
        cfg.initialization.historyDuration/samplePeriod);
    durationError = abs(historyStepCount*samplePeriod ...
        - cfg.initialization.historyDuration);
    if durationError > 100.0*eps(max( ...
            1.0, cfg.initialization.historyDuration))
        error("nrmmEstimatorControllerAdapter:invalidHistoryDuration", ...
            "The initialization history must use whole observer samples.");
    end
    historyTime = (-historyStepCount:0).' * samplePeriod;
    stream = RandStream("mt19937ar", Seed=cfg.randomSeed);
    frame = cell(numel(historyTime), 1);
    audit = cell(numel(historyTime), 1);
    egoTruth = cell(numel(historyTime), 1);
    for sampleIdx = 1:numel(historyTime)
        egoTruth{sampleIdx} = localHistoricalEgoState( ...
            initialEgoTruth, historyTime(sampleIdx));
        targetTruth = targetStateFunction( ...
            historyTime(sampleIdx), egoTruth{sampleIdx});
        bodyAcceleration = localNominalBodyAcceleration( ...
            egoTruth{sampleIdx});
        [frame{sampleIdx}, audit{sampleIdx}] = localSensorFrame( ...
            cfg, stream, historyTime(sampleIdx), ...
            egoTruth{sampleIdx}, bodyAcceleration, targetTruth);
    end

    observerDesign = nrmmWindowEstimatorDesign(cfg.observer);
    egoInitial = localInitialEgoEstimate(frame, observerDesign);
    [targetInitialState, targetAcquired, targetAcquisition] = ...
        localInitialTargetEstimate( ...
            historyTime, frame, egoInitial.position, ...
            egoInitial.yaw, cfg);
    options = struct( ...
        "initialTime", 0.0, ...
        "targetCount", 1, ...
        "egoInitialPosition", egoInitial.position, ...
        "egoInitialYaw", egoInitial.yaw, ...
        "egoInitialBodyVelocity", egoInitial.bodyVelocity, ...
        "targetInitialState", targetInitialState, ...
        "targetIdentifiers", "synthetic-radar-track-1");
    runtime = onlineNrmmTrackingRuntime( ...
        "initialize", cfg.observer, options, observerDesign);
    currentFrame = frame{end};
    currentOutput = onlineNrmmTrackingRuntime( ...
        "output", runtime, currentFrame);

    context = struct( ...
        "configuration", cfg, ...
        "observerDesign", observerDesign, ...
        "runtime", runtime, ...
        "randomStream", stream, ...
        "currentOutput", currentOutput, ...
        "targetStateFunction", targetStateFunction, ...
        "targetAcquired", targetAcquired, ...
        "targetAcquisition", targetAcquisition, ...
        "targetAcquisitionTime", ...
            localInitialAcquisitionTime(targetAcquired), ...
        "targetLastDetectionTime", ...
            localInitialAcquisitionTime(targetAcquired), ...
        "targetTrackStatus", ...
            localInitialTrackStatus(targetAcquired), ...
        "targetRetirementCount", 0, ...
        "targetLastRetirementTime", NaN, ...
        "initialFramePending", true, ...
        "initialFrame", currentFrame, ...
        "initialAudit", audit{end}, ...
        "previousControllerTime", 0.0, ...
        "previousControllerEgoTruth", initialEgoTruth, ...
        "previousObserverEgoTruth", initialEgoTruth, ...
        "observerSamplesSinceLastControllerTime", 0);
    initialization = struct( ...
        "historyTime", historyTime, ...
        "sensorFrame", {frame}, ...
        "measurementAudit", {audit}, ...
        "egoInitialPosition", egoInitial.position, ...
        "egoInitialYaw", egoInitial.yaw, ...
        "egoInitialBodyVelocity", egoInitial.bodyVelocity, ...
        "targetInitialState", targetInitialState, ...
        "targetInitiallyAcquired", targetAcquired, ...
        "targetAcquisition", targetAcquisition, ...
        "observerDesign", observerDesign, ...
        "observerSamplePeriod", samplePeriod);
end

function [context, egoEstimate, targetEstimate, frame, audit] = ...
        localSample(context, time, egoTruth, targetTruth)
    context = localAdvanceObserverToControllerTime( ...
        context, time, egoTruth);
    tolerance = 64.0*eps(max( ...
        1.0, max(abs([time; context.runtime.currentTime]))));
    if abs(time-context.runtime.currentTime) > tolerance
        error("nrmmEstimatorControllerAdapter:offSampleGrid", ...
            "The controller and estimator sample times must remain aligned.");
    end

    if context.initialFramePending
        frame = context.initialFrame;
        audit = context.initialAudit;
        context.initialFramePending = false;
    else
        bodyAcceleration = localSampledBodyAcceleration( ...
            context.previousObserverEgoTruth, egoTruth, ...
            context.configuration.observer.runtime.samplePeriod);
        [frame, audit] = localSensorFrame( ...
            context.configuration, context.randomStream, time, ...
            egoTruth, bodyAcceleration, targetTruth);
    end

    egoEstimate = localCurrentEgoEstimate( ...
        context.currentOutput, frame, ...
        context.configuration.observer.runtime.samplePeriod);
    [context, targetJustAcquired] = ...
        localUpdateTargetAcquisition( ...
            context, frame, egoEstimate);
    context = localUpdateTargetLifecycle( ...
        context, frame, egoEstimate);
    if targetJustAcquired
        context.currentOutput = onlineNrmmTrackingRuntime( ...
            "output", context.runtime, frame);
        egoEstimate = localCurrentEgoEstimate( ...
            context.currentOutput, frame, ...
            context.configuration.observer.runtime.samplePeriod);
    end
    if context.targetAcquired
        rawTargetEstimate = egoEstimate.targetEstimates;
        rawTargetEstimate = localLabelTargetEstimate( ...
            rawTargetEstimate, context.targetAcquisition);
        publicationPolicy = string( ...
            context.configuration.sensor.radar ...
                .targetPublicationPolicy);
        if publicationPolicy ...
                == "currentRadarVisibilityRequiredInternalTrackMayCoast" ...
                && frame.radarDetectionAvailable
            targetEstimate = rawTargetEstimate;
        else
            targetEstimate = struct([]);
        end
    else
        rawTargetEstimate = struct([]);
        targetEstimate = struct([]);
    end
    [egoEstimate, targetEstimate] = localAttachErrorBounds( ...
        egoEstimate, targetEstimate, context.configuration);
    egoEstimate.rawNrmmTargetEstimates = rawTargetEstimate;
    egoEstimate.targetEstimates = targetEstimate;
    egoEstimate.targetTrackAcquired = context.targetAcquired;
    egoEstimate.targetEstimatePublished = ~isempty(targetEstimate);
    egoEstimate.targetPublicationPolicy = string( ...
        context.configuration.sensor.radar.targetPublicationPolicy);
    egoEstimate.targetAcquisitionTime = ...
        context.targetAcquisitionTime;
    egoEstimate.targetTrackStatus = context.targetTrackStatus;
    egoEstimate.targetTrackCoastAge = ...
        localTargetTrackCoastAge(context, frame.time);
    egoEstimate.targetMaximumCoastDuration = ...
        context.configuration.sensor.radar ...
            .maximumTrackCoastDuration;
    egoEstimate.targetTrackRetirementCount = ...
        context.targetRetirementCount;
    egoEstimate.targetLastRetirementTime = ...
        context.targetLastRetirementTime;
    if ~context.targetAcquired
        context = localAnchorDormantTarget( ...
            context, egoEstimate);
    end
    observerFrame = frame;
    if ~context.targetAcquired || targetJustAcquired
        observerFrame = localFrameWithoutRadar(frame);
    end
    [context.runtime, context.currentOutput] = ...
        onlineNrmmTrackingRuntime( ...
            "step", context.runtime, observerFrame);
    context.previousControllerTime = time;
    context.previousControllerEgoTruth = egoTruth;
    context.previousObserverEgoTruth = egoTruth;
end

function context = localAdvanceObserverToControllerTime( ...
        context, controllerTime, controllerEgoTruth)
% localAdvanceObserverToControllerTime Process buffered sensor-rate samples.
%
% The plant and controller are evaluated at 10 Hz, whereas the configured
% output-predictor realization runs at 80 Hz. At a controller instant all
% sensor samples from the completed plant interval are causally available.
% The harness reconstructs their ego states by interpolation and evaluates
% the declared analytic target trajectory at each sensor timestamp.

    samplePeriod = ...
        context.configuration.observer.runtime.samplePeriod;
    remainingTime = controllerTime-context.runtime.currentTime;
    tolerance = 100.0*eps(max(1.0, max(abs([ ...
        controllerTime; context.runtime.currentTime; samplePeriod]))));
    if remainingTime < -tolerance
        error("nrmmEstimatorControllerAdapter:nonmonotonicControllerTime", ...
            "Controller times must increase monotonically.");
    end
    missingSampleCount = round(max(0.0, remainingTime)/samplePeriod);
    if abs(remainingTime-missingSampleCount*samplePeriod) > tolerance
        error("nrmmEstimatorControllerAdapter:offObserverSampleGrid", ...
            "Controller times must lie on the observer sample grid.");
    end

    controllerInterval = ...
        controllerTime-context.previousControllerTime;
    if missingSampleCount > 0 && controllerInterval <= 0.0
        error("nrmmEstimatorControllerAdapter:invalidControllerInterval", ...
            "A positive controller interval is required for sensor interpolation.");
    end
    for sampleIdx = 1:missingSampleCount
        sampleTime = context.runtime.currentTime;
        fraction = (sampleTime-context.previousControllerTime) ...
            / controllerInterval;
        intermediateEgoTruth = localInterpolateEgoState( ...
            context.previousControllerEgoTruth, controllerEgoTruth, ...
            fraction);
        bodyAcceleration = localSampledBodyAcceleration( ...
            context.previousObserverEgoTruth, intermediateEgoTruth, ...
            samplePeriod);
        intermediateTargetTruth = context.targetStateFunction( ...
            sampleTime, intermediateEgoTruth);
        [frame, ~] = localSensorFrame( ...
            context.configuration, context.randomStream, sampleTime, ...
            intermediateEgoTruth, bodyAcceleration, ...
            intermediateTargetTruth);
        intermediateEgoEstimate = localCurrentEgoEstimate( ...
            context.currentOutput, frame, samplePeriod);
        [context, targetJustAcquired] = ...
            localUpdateTargetAcquisition( ...
                context, frame, intermediateEgoEstimate);
        context = localUpdateTargetLifecycle( ...
            context, frame, intermediateEgoEstimate);
        if targetJustAcquired
            context.currentOutput = onlineNrmmTrackingRuntime( ...
                "output", context.runtime, frame);
        end
        observerFrame = frame;
        if ~context.targetAcquired || targetJustAcquired
            observerFrame = localFrameWithoutRadar(frame);
        end
        [context.runtime, context.currentOutput] = ...
            onlineNrmmTrackingRuntime( ...
                "step", context.runtime, observerFrame);
        context.previousObserverEgoTruth = intermediateEgoTruth;
    end
    context.observerSamplesSinceLastControllerTime = ...
        missingSampleCount+1;
end

function state = localInterpolateEgoState( ...
        initialState, finalState, fraction)
    if ~isscalar(fraction) || ~isfinite(fraction) ...
            || fraction < 0.0 || fraction > 1.0
        error("nrmmEstimatorControllerAdapter:invalidInterpolation", ...
            "The sensor-time interpolation fraction must be in [0, 1].");
    end
    initialYaw = localEgoYaw(initialState);
    yawDifference = atan2( ...
        sin(localEgoYaw(finalState)-initialYaw), ...
        cos(localEgoYaw(finalState)-initialYaw));
    position = (1.0-fraction)*localEgoPosition(initialState) ...
        + fraction*localEgoPosition(finalState);
    bodyVelocity = (1.0-fraction)*localBodyVelocity(initialState) ...
        + fraction*localBodyVelocity(finalState);
    yawRate = (1.0-fraction)*localEgoYawRate(initialState) ...
        + fraction*localEgoYawRate(finalState);
    state = struct( ...
        "position", position, ...
        "yawAngle", initialYaw+fraction*yawDifference, ...
        "longitudinalVelocity", bodyVelocity(1), ...
        "lateralVelocity", bodyVelocity(2), ...
        "yawRate", yawRate);
end

function estimate = localCurrentEgoEstimate(output, ~, ~)
    estimate = output;
end

function [egoEstimate, targetEstimate] = localAttachErrorBounds( ...
        egoEstimate, targetEstimate, cfg)
% Publish the estimation error radii alongside the estimates.
%
% Without these fields the controller receives six numbers that are
% indistinguishable from a truth state, its optional error-bound inputs
% default to zero, and every collision and road tightening it computes
% is multiplied by zero. Declaring the radii is what makes the
% controller's row tightenings nonempty.

    if ~isfield(cfg, "publishedErrorBound")
        return;
    end
    bound = cfg.publishedErrorBound;
    egoEstimate.controllerErrorBoundSource = "configured-engineering-assumption";
    % Controller state order is
    % [x; y; yaw; longitudinalVelocity; lateralVelocity; yawRate].
    egoEstimate.controllerStateErrorBound = [ ...
        bound.egoPosition; bound.egoPosition; bound.egoYaw; ...
        bound.egoVelocity; bound.egoVelocity; bound.egoYawRate];
    for targetIdx = 1:numel(targetEstimate)
        targetEstimate(targetIdx).controllerErrorBoundSource = "configured-engineering-assumption";
        targetEstimate(targetIdx).targetPositionInertialErrorBound = ...
            bound.targetPosition * ones(2, 1);
        targetEstimate(targetIdx).targetVelocityInertialErrorBound = ...
            bound.targetVelocity * ones(2, 1);
        targetEstimate(targetIdx).targetYawErrorBound = ...
            bound.targetYaw;
        targetEstimate(targetIdx).targetYawRateErrorBound = ...
            bound.targetYawRate;
    end
end

function estimate = localLabelTargetEstimate(estimate, acquisition)
    for targetIdx = 1:numel(estimate)
        estimate(targetIdx).velocityInitializationMethod = ...
            acquisition.velocityInitializationMethod;
        estimate(targetIdx).source = ...
            "NRMM exact-flow finite-window estimator";
    end
end

function egoInitial = localInitialEgoEstimate(frame, observerDesign)
% localInitialEgoEstimate Seed body velocity and yaw from joint sensor information.
%
% GNSS velocity is directly sensed, so the seed needs no history secant:
% position and velocity come from the newest frame. Initial yaw applies the
% same certified kinematic sideslip correction as the online course channel
% instead of making a zero-sideslip assumption.

    latestFrame = frame{end};
    position = [latestFrame.xGps; latestFrame.yGps];
    inertialVelocity = [latestFrame.vxGps; latestFrame.vyGps];
    information = nrmmBodyVelocitySet(inertialVelocity, latestFrame.yawRateMeasured, ...
        observerDesign.configuration);
    if ~information.nonempty
        error("nrmmEstimatorControllerAdapter:unobservableInitialCourse", ...
            "GNSS velocity and yaw rate have an empty body-velocity information set.");
    end
    yaw = atan2(inertialVelocity(2), inertialVelocity(1)) ...
        -atan2(information.representative(2), information.representative(1));
    egoInitial = struct("position", position, "yaw", yaw, ...
        "bodyVelocity", information.representative, "inertialVelocity", inertialVelocity);
end

function [targetState, acquired, acquisition] = ...
        localInitialTargetEstimate( ...
            historyTime, frame, egoPosition, egoYaw, cfg)
    detectionAvailable = cellfun( ...
        @(value) logical(value.radarDetectionAvailable), frame);
    minimumSampleCount = cfg.initialization.minimumRadarSamples;
    lastUnavailableIdx = find( ...
        ~detectionAvailable, 1, "last");
    if isempty(lastUnavailableIdx)
        trailingDetectionIdx = (1:numel(frame)).';
    else
        trailingDetectionIdx = ...
            ((lastUnavailableIdx+1):numel(frame)).';
    end

    acquisition = struct( ...
        "minimumSampleCount", minimumSampleCount, ...
        "time", historyTime(trailingDetectionIdx), ...
        "radarRelativePosition", localRadarRows( ...
            frame, trailingDetectionIdx), ...
        "targetPositionInertial", ...
            localInitialTargetPositionRows( ...
                frame, trailingDetectionIdx), ...
        "velocityInitializationMethod", "", ...
        "consecutiveDetectionCount", ...
            numel(trailingDetectionIdx));
    if numel(trailingDetectionIdx) >= minimumSampleCount
        % Initialization may use every consecutive detection already
        % present in the declared history window. Delayed online
        % acquisition below remains causal and triggers as soon as the
        % configured minimum count is reached.
        selectedIdx = trailingDetectionIdx;
        detectionTime = historyTime(selectedIdx);
        targetPositionInertial = ...
            acquisition.targetPositionInertial;
        [targetState, ~] = localTargetStateFromInertialWindow( ...
            detectionTime, targetPositionInertial, ...
            egoPosition, egoYaw, cfg);
        acquisition.velocityInitializationMethod = ...
            localTargetVelocityInitializationMethod( ...
                numel(detectionTime));
        acquired = true;
    else
        targetState = localDormantTargetState(cfg);
        acquired = false;
    end
end

function radarPosition = localRadarRows(frame, sampleIdx)
    if isempty(sampleIdx)
        radarPosition = zeros(0, 2);
        return;
    end
    radarPosition = cell2mat(cellfun( ...
        @(value) value.radarRelativePosition, ...
        frame(sampleIdx), UniformOutput=false));
end

function targetPosition = localInitialTargetPositionRows( ...
        frame, sampleIdx)
% Each history frame carries measured GNSS position and velocity, so the
% radar rows rotate into the inertial frame with the per-frame course.
    if isempty(sampleIdx)
        targetPosition = zeros(0, 2);
        return;
    end
    radarPosition = localRadarRows(frame, sampleIdx);
    targetPosition = NaN(numel(sampleIdx), 2);
    for positionIdx = 1:numel(sampleIdx)
        frameIdx = sampleIdx(positionIdx);
        egoPosition = [ ...
            frame{frameIdx}.xGps; frame{frameIdx}.yGps];
        courseAngle = atan2( ...
            frame{frameIdx}.vyGps, frame{frameIdx}.vxGps);
        rotation = localRotation(courseAngle);
        targetPosition(positionIdx, :) = ...
            (egoPosition ...
                + rotation*radarPosition(positionIdx, :).').';
    end
end

function targetState = localDormantTargetState(cfg)
% localDormantTargetState Park a constant-velocity phantom ahead of range.
%
% In the transformed coordinates the target velocity q is the absolute
% target velocity in the ego frame, so a dormant oncoming phantom is
% simply q = [-targetSpeed; 0] with zero absolute acceleration; no ego
% state enters the prior.
    relativePosition = [ ...
        cfg.sensor.radar.rangeMaximum+10.0; 0.0];
    targetVelocityEgoFrame = [-cfg.vehicle.targetSpeed; 0.0];
    targetState = [ ...
        relativePosition; targetVelocityEgoFrame; zeros(2, 1)];
end

function [context, justAcquired] = ...
        localUpdateTargetAcquisition(context, frame, egoEstimate)
    justAcquired = false;
    if context.targetAcquired
        return;
    end

    acquisition = context.targetAcquisition;
    if frame.radarDetectionAvailable
        acquisition = localAppendRadarDetection( ...
            acquisition, frame, egoEstimate, ...
            context.configuration.observer.runtime.samplePeriod);
    else
        acquisition.time = zeros(0, 1);
        acquisition.radarRelativePosition = zeros(0, 2);
        acquisition.targetPositionInertial = zeros(0, 2);
        acquisition.velocityInitializationMethod = "";
        acquisition.consecutiveDetectionCount = 0;
    end
    context.targetAcquisition = acquisition;
    if acquisition.consecutiveDetectionCount ...
            < acquisition.minimumSampleCount
        return;
    end

    selectedIdx = ...
        (acquisition.consecutiveDetectionCount ...
            - acquisition.minimumSampleCount+1) ...
        :acquisition.consecutiveDetectionCount;
    [targetState, targetSpeed] = ...
        localTargetStateFromInertialWindow( ...
            acquisition.time(selectedIdx), ...
            acquisition.targetPositionInertial(selectedIdx, :), ...
            egoEstimate.egoPositionInertial, egoEstimate.egoYaw, ...
            context.configuration);
    acquisition.velocityInitializationMethod = ...
        localTargetVelocityInitializationMethod( ...
            numel(selectedIdx));
    context.targetAcquisition = acquisition;
    context.runtime = onlineNrmmTrackingRuntime("resetTarget", context.runtime, 1, targetState);
    context.runtime.targetCertifiedSpeedDomainValid = true;
    context.runtime.minimumReconstructedTargetSpeed = targetSpeed;
    context.runtime.lastIntervalTargetCertifiedSpeedDomainValid = true;
    context.targetAcquired = true;
    context.targetAcquisitionTime = frame.time;
    justAcquired = true;
end

function context = localUpdateTargetLifecycle( ...
        context, frame, egoEstimate)
    if ~context.targetAcquired
        context.targetTrackStatus = "dormant";
        return;
    end
    if frame.radarDetectionAvailable
        context.targetLastDetectionTime = frame.time;
        context.targetTrackStatus = "confirmed";
        return;
    end

    coastAge = frame.time-context.targetLastDetectionTime;
    maximumCoastDuration = ...
        context.configuration.sensor.radar ...
            .maximumTrackCoastDuration;
    tolerance = 100.0*eps(max( ...
        1.0, max(abs([frame.time; ...
            context.targetLastDetectionTime; ...
            maximumCoastDuration]))));
    if coastAge <= maximumCoastDuration+tolerance
        context.targetTrackStatus = "coasting";
        return;
    end

    context.targetAcquired = false;
    context.targetTrackStatus = "dormant";
    context.targetRetirementCount = ...
        context.targetRetirementCount+1;
    context.targetLastRetirementTime = frame.time;
    context.targetLastDetectionTime = NaN;
    context.targetAcquisition = localEmptyTargetAcquisition( ...
        context.targetAcquisition.minimumSampleCount);
    context = localAnchorDormantTarget(context, egoEstimate);
end

function context = localAnchorDormantTarget(context, ~)
    targetState = localDormantTargetState(context.configuration);
    context.runtime = onlineNrmmTrackingRuntime("resetTarget", context.runtime, 1, targetState);
    context.runtime.lastIntervalTargetCertifiedSpeedDomainValid = true;
    context.runtime.minimumReconstructedTargetSpeed = min( ...
        context.runtime.minimumReconstructedTargetSpeed, ...
        context.configuration.vehicle.targetSpeed);
end

function acquisition = localEmptyTargetAcquisition(minimumSampleCount)
    acquisition = struct( ...
        "minimumSampleCount", minimumSampleCount, ...
        "time", zeros(0, 1), ...
        "radarRelativePosition", zeros(0, 2), ...
        "targetPositionInertial", zeros(0, 2), ...
        "velocityInitializationMethod", "", ...
        "consecutiveDetectionCount", 0);
end

function age = localTargetTrackCoastAge(context, time)
    if context.targetTrackStatus == "coasting"
        age = time-context.targetLastDetectionTime;
    elseif context.targetTrackStatus == "confirmed"
        age = 0.0;
    else
        age = NaN;
    end
end

function acquisition = localAppendRadarDetection( ...
        acquisition, frame, egoEstimate, samplePeriod)
    rotation = localRotation(egoEstimate.egoYaw);
    targetPosition = ...
        (egoEstimate.egoPositionInertial ...
            + rotation*frame.radarRelativePosition(:)).';
    tolerance = 100.0*eps(max( ...
        1.0, max(abs([frame.time; acquisition.time(:)]))));
    if isempty(acquisition.time)
        acquisition.time = frame.time;
        acquisition.radarRelativePosition = ...
            frame.radarRelativePosition;
        acquisition.targetPositionInertial = targetPosition;
    elseif abs(frame.time-acquisition.time(end)) <= tolerance
        acquisition.time(end) = frame.time;
        acquisition.radarRelativePosition(end, :) = ...
            frame.radarRelativePosition;
        acquisition.targetPositionInertial(end, :) = ...
            targetPosition;
    elseif abs(frame.time-acquisition.time(end)-samplePeriod) ...
            <= tolerance
        acquisition.time(end+1, 1) = frame.time;
        acquisition.radarRelativePosition(end+1, :) = ...
            frame.radarRelativePosition;
        acquisition.targetPositionInertial(end+1, :) = ...
            targetPosition;
    else
        acquisition.time = frame.time;
        acquisition.radarRelativePosition = ...
            frame.radarRelativePosition;
        acquisition.targetPositionInertial = targetPosition;
    end
    acquisition.consecutiveDetectionCount = ...
        numel(acquisition.time);
end

function [targetState, reconstructedTargetSpeed] = ...
        localTargetStateFromInertialWindow( ...
            detectionTime, targetPositionInertial, ...
            egoPosition, egoYaw, cfg)
% The transformed target state is [rho; q; s]: radar relative position,
% absolute target velocity in the ego frame, and absolute target
% acceleration in the ego frame. The velocity prior supplies q directly
% and the acceleration prior is the constant-velocity zero.
    if any(abs(diff(detectionTime) ...
            - cfg.observer.runtime.samplePeriod) ...
            > 100.0*eps(max(1.0, max(abs(detectionTime)))))
        error("nrmmEstimatorControllerAdapter:nonconsecutiveRadarHistory", ...
            "Target initialization requires consecutive radar samples.");
    end
    targetPosition = targetPositionInertial(end, :).';
    if isscalar(detectionTime)
        lineOfSight = targetPosition - egoPosition;
        lineOfSightNorm = norm(lineOfSight);
        if lineOfSightNorm ...
                <= 100.0*eps(max(1.0, lineOfSightNorm))
            error("nrmmEstimatorControllerAdapter:" ...
                    + "invalidTargetInitialization", ...
                "The radial oncoming velocity prior requires a " ...
                + "nonzero radar line of sight.");
        end
        targetVelocity = ...
            -cfg.initialization.targetSpeedPrior ...
                * lineOfSight/lineOfSightNorm;
    else
        targetModel = [ones(size(detectionTime)), detectionTime] ...
            \ targetPositionInertial;
        rawTargetVelocity = targetModel(2, :).';
        rawTargetSpeed = norm(rawTargetVelocity);
        if rawTargetSpeed ...
                < cfg.observer.target.domain.speedMinimum
            error("nrmmEstimatorControllerAdapter:" ...
                    + "invalidTargetInitialization", ...
                "Radar/GNSS samples reconstructed a target below the " ...
                + "configured NRMM speed domain.");
        end
        targetVelocity = cfg.initialization.targetSpeedPrior ...
            * rawTargetVelocity/rawTargetSpeed;
    end
    reconstructedTargetSpeed = norm(targetVelocity);
    rotationTranspose = localRotation(egoYaw).';
    relativePosition = rotationTranspose ...
        * (targetPosition-egoPosition);
    targetVelocityEgoFrame = rotationTranspose*targetVelocity;
    targetState = [ ...
        relativePosition; targetVelocityEgoFrame; zeros(2, 1)];
end

function method = localTargetVelocityInitializationMethod(sampleCount)
    if sampleCount == 1
        method = "radialOncomingConfiguredSpeedPrior";
    else
        method = "radarPositionWindowDirectionConfiguredSpeedMagnitude";
    end
end

function time = localInitialAcquisitionTime(acquired)
    if acquired
        time = 0.0;
    else
        time = NaN;
    end
end

function status = localInitialTrackStatus(acquired)
    if acquired
        status = "confirmed";
    else
        status = "dormant";
    end
end

function frame = localFrameWithoutRadar(frame)
    frame.radarRelativePosition = [NaN, NaN];
    frame.radarDetectionAvailable = false;
end

function [frame, audit] = localSensorFrame( ...
        cfg, stream, time, egoTruth, bodyAcceleration, targetTruth)
    unitNoise = localUnitNoise(stream, 9, cfg.noiseModel);
    position = localEgoPosition(egoTruth);
    yaw = localEgoYaw(egoTruth);
    yawRate = localEgoYawRate(egoTruth);
    inertialVelocity = localRotation(yaw)*localBodyVelocity(egoTruth);
    targetPosition = localTargetPosition(targetTruth);
    relativeInertial = targetPosition-position;
    targetRange = norm(relativeInertial);
    rangeTolerance = 100.0*eps(max( ...
        1.0, cfg.sensor.radar.rangeMaximum));
    detected = targetRange <= cfg.sensor.radar.rangeMaximum ...
        + rangeTolerance;
    if detected
        radarRelativePosition = ...
            (localRotation(yaw).'*relativeInertial).' ...
            + cfg.sensor.radar.positionNoiseMaximum ...
                * unitNoise(6:7);
    else
        radarRelativePosition = [NaN, NaN];
    end

    frame = struct( ...
        "time", time, ...
        "xGps", position(1) ...
            + cfg.sensor.gnss.positionNoiseMaximum*unitNoise(1), ...
        "yGps", position(2) ...
            + cfg.sensor.gnss.positionNoiseMaximum*unitNoise(2), ...
        "vxGps", inertialVelocity(1) ...
            + cfg.sensor.gnss.velocityNoiseMaximum*unitNoise(8), ...
        "vyGps", inertialVelocity(2) ...
            + cfg.sensor.gnss.velocityNoiseMaximum*unitNoise(9), ...
        "longitudinalAcceleration", bodyAcceleration(1) ...
            + cfg.sensor.imu.accelerationNoiseMaximum*unitNoise(3), ...
        "lateralAcceleration", bodyAcceleration(2) ...
            + cfg.sensor.imu.accelerationNoiseMaximum*unitNoise(4), ...
        "yawRateMeasured", yawRate ...
            + cfg.sensor.gyroscope.yawRateNoiseMaximum*unitNoise(5), ...
        "radarRelativePosition", radarRelativePosition, ...
        "radarDetectionAvailable", detected);
    audit = struct( ...
        "time", time, ...
        "targetRange", targetRange, ...
        "radarDetectionAvailable", detected, ...
        "radarRangeMaximum", cfg.sensor.radar.rangeMaximum);
end

function unitNoise = localUnitNoise(stream, count, noiseModel)
    switch lower(string(noiseModel))
        case "none"
            unitNoise = zeros(1, count);
        case "boundeduniform"
            unitNoise = 2.0*rand(stream, 1, count)-1.0;
        otherwise
            error("nrmmEstimatorControllerAdapter:invalidNoiseModel", ...
                "noiseModel must be 'none' or 'boundedUniform'.");
    end
end

function acceleration = localSampledBodyAcceleration( ...
        previousState, currentState, samplePeriod)
% localSampledBodyAcceleration Preserve the sampled rotation correspondence.
%
% The harness interpolates yaw and yaw rate independently between plant
% outputs. Differencing body velocity and then adding the pointwise yaw-rate
% term does not, in general, equal the derivative of the GNSS inertial
% velocity synthesized from those same interpolants. Form the backward
% inertial-velocity difference first, then express that acceleration in the
% current body frame. Consequently the noiseless synthetic measurements
% satisfy aI = R(psi)*aE exactly at every sensor sample.
    previousInertialVelocity = localRotation( ...
        localEgoYaw(previousState))*localBodyVelocity(previousState);
    currentRotation = localRotation(localEgoYaw(currentState));
    currentInertialVelocity = ...
        currentRotation*localBodyVelocity(currentState);
    inertialAcceleration = (currentInertialVelocity ...
        - previousInertialVelocity)/samplePeriod;
    acceleration = currentRotation.'*inertialAcceleration;
end

function acceleration = localNominalBodyAcceleration(state)
    planarCross = [0.0, -1.0; 1.0, 0.0];
    acceleration = localEgoYawRate(state) ...
        * planarCross*localBodyVelocity(state);
end

function state = localHistoricalEgoState(initialState, time)
    position = localEgoPosition(initialState);
    yaw = localEgoYaw(initialState);
    yawRate = localEgoYawRate(initialState);
    bodyVelocity = localBodyVelocity(initialState);
    historicalYaw = yaw+yawRate*time;
    if abs(yawRate) <= 1.0e-10
        displacement = localRotation(yaw)*bodyVelocity*time;
    else
        terminalYaw = historicalYaw;
        displacement = [ ...
            bodyVelocity(1)*(sin(terminalYaw)-sin(yaw))/yawRate ...
                + bodyVelocity(2)*(cos(terminalYaw)-cos(yaw))/yawRate; ...
            bodyVelocity(1)*(cos(yaw)-cos(terminalYaw))/yawRate ...
                + bodyVelocity(2)*(sin(terminalYaw)-sin(yaw))/yawRate];
    end
    state = struct( ...
        "position", position+displacement, ...
        "yawAngle", historicalYaw, ...
        "longitudinalVelocity", bodyVelocity(1), ...
        "lateralVelocity", bodyVelocity(2), ...
        "yawRate", yawRate);
end

function position = localEgoPosition(state)
    if isfield(state, "position")
        position = double(state.position(:));
    else
        position = [double(state.positionX); double(state.positionY)];
    end
end

function yaw = localEgoYaw(state)
    if isfield(state, "yawAngle")
        yaw = double(state.yawAngle);
    else
        yaw = double(state.yaw);
    end
end

function yawRate = localEgoYawRate(state)
    yawRate = double(state.yawRate);
end

function velocity = localBodyVelocity(state)
    velocity = [ ...
        double(state.longitudinalVelocity); ...
        double(state.lateralVelocity)];
end

function position = localTargetPosition(target)
    if ~isstruct(target) || numel(target) ~= 1 ...
            || ~isfield(target, "targetPositionInertial")
        error("nrmmEstimatorControllerAdapter:invalidTargetTruth", ...
            "The integration test requires one target truth trajectory.");
    end
    position = double(target.targetPositionInertial(:));
    if numel(position) ~= 2 || any(~isfinite(position))
        error("nrmmEstimatorControllerAdapter:invalidTargetTruth", ...
            "targetPositionInertial must be a finite two-vector.");
    end
end

function localValidateConfiguration(cfg)
    required = ["randomSeed", "noiseModel", "sensor", ...
        "initialization", "observer", "vehicle"];
    if ~isstruct(cfg) || ~isscalar(cfg) || ~all(isfield(cfg, required))
        error("nrmmEstimatorControllerAdapter:invalidConfiguration", ...
            "cfg must come from estimatorControllerIntegrationConfig.");
    end
    publicationPolicyValid = ...
        isfield(cfg.sensor, "radar") ...
        && isfield(cfg.sensor.radar, "targetPublicationPolicy") ...
        && isscalar(string( ...
            cfg.sensor.radar.targetPublicationPolicy)) ...
        && string(cfg.sensor.radar.targetPublicationPolicy) ...
            == "currentRadarVisibilityRequiredInternalTrackMayCoast";
    trackCoastDurationValid = ...
        isfield(cfg.sensor.radar, "maximumTrackCoastDuration") ...
        && isscalar(cfg.sensor.radar.maximumTrackCoastDuration) ...
        && isfinite(cfg.sensor.radar.maximumTrackCoastDuration) ...
        && cfg.sensor.radar.maximumTrackCoastDuration >= 0.0;
    if cfg.observer.runtime.samplePeriod <= 0.0 ...
            || cfg.sensor.radar.rangeMaximum <= 0.0 ...
            || ~publicationPolicyValid ...
            || ~trackCoastDurationValid ...
            || cfg.initialization.minimumRadarSamples < 1 ...
            || ~isfield(cfg.initialization, "targetSpeedPrior") ...
            || ~isfinite(cfg.initialization.targetSpeedPrior) ...
            || cfg.initialization.targetSpeedPrior ...
                < cfg.observer.target.domain.speedMinimum ...
            || ~isfield(cfg.vehicle, "targetSpeed") ...
            || ~isfinite(cfg.vehicle.targetSpeed) ...
            || cfg.vehicle.targetSpeed <= 0.0
        error("nrmmEstimatorControllerAdapter:invalidConfiguration", ...
            "Sample time, radar range/publication/coast policy, and " ...
            + "initialization count are invalid.");
    end
end

function rotation = localRotation(yaw)
    rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
end

function localAddProjectPaths()
    repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repositoryRoot, "config"));
    addpath(genpath(fullfile(repositoryRoot, "estimator")));
end
