function [minimumSafeSideValue, witness] = ...
        quadraticRoadBoundaryRectangleMargin( ...
            egoPose, vehicleSize, boundary)
%quadraticRoadBoundaryRectangleMargin Exact rectangle/quadratic margin.
%
% egoPose is [positionX; positionY; yaw] and vehicleSize is
% [overallLength; overallWidth]. The boundary is a finite local quadratic
% graph with the same fields accepted by collisionAvoidanceController:
%
%   origin, longitudinalDirection, lateralDirection, coefficients,
%   parameterRange, safeSideSign.
%
% The function minimizes
%
%   safeSideSign * (l - polyval(coefficients, s))
%
% over the complete oriented ego rectangle. This offline utility supports
% road-boundary evaluation and unit tests. The online controller uses a conservative
% affine tangent row and does not perform nonlinear rollout validation.

    egoPose = localFiniteVector(egoPose, 3, "egoPose");
    vehicleSize = localFiniteVector(vehicleSize, 2, "vehicleSize");
    if any(vehicleSize <= 0.0)
        error("quadraticRoadBoundaryRectangleMargin:invalidVehicle", ...
            "vehicleSize must contain positive length and width.");
    end
    boundary = localValidateBoundary(boundary);

    yaw = egoPose(3);
    headingDirection = [cos(yaw); sin(yaw)];
    headingNormal = [-sin(yaw); cos(yaw)];
    rectangleMap = [ ...
        0.5 * vehicleSize(1) * headingDirection, ...
        0.5 * vehicleSize(2) * headingNormal];
    centerOffset = egoPose(1:2) - boundary.origin;
    centerS = boundary.longitudinalDirection.' * centerOffset;
    centerL = boundary.lateralDirection.' * centerOffset;
    rectangleS = boundary.longitudinalDirection.' * rectangleMap;
    rectangleL = boundary.lateralDirection.' * rectangleMap;

    cornerCoordinates = [ ...
        -1.0, -1.0, 1.0, 1.0; ...
        -1.0, 1.0, -1.0, 1.0];
    cornerS = centerS + rectangleS * cornerCoordinates;
    domainTolerance = 100.0 * eps(max( ...
        [1.0, abs(cornerS), abs(boundary.parameterRange)]));
    if min(cornerS) < boundary.parameterRange(1) - domainTolerance ...
            || max(cornerS) ...
                > boundary.parameterRange(2) + domainTolerance
        error("quadraticRoadBoundaryRectangleMargin:" ...
                + "outsideParameterRange", ...
            "The complete rectangle must lie within the finite " ...
            + "boundary parameter range.");
    end

    coefficients = boundary.coefficients;
    quadraticCoefficient = coefficients(1);
    linearCoefficient = coefficients(2);
    safeSideSign = boundary.safeSideSign;
    quadraticMatrix = -safeSideSign * quadraticCoefficient ...
        * (rectangleS.' * rectangleS);
    linearVector = safeSideSign * ( ...
        rectangleL.' ...
        - (2.0 * quadraticCoefficient * centerS ...
            + linearCoefficient) * rectangleS.');
    constant = safeSideSign * ( ...
        centerL - polyval(coefficients, centerS));

    candidateCoordinates = cornerCoordinates;
    for fixedCoordinate = [-1.0, 1.0]
        edgeQuadratic = quadraticMatrix(2, 2);
        edgeLinear = 2.0 * quadraticMatrix(1, 2) ...
            * fixedCoordinate + linearVector(2);
        stationaryCoordinate = localStationaryCoordinate( ...
            edgeQuadratic, edgeLinear);
        if ~isempty(stationaryCoordinate)
            candidateCoordinates(:, end + 1) = [ ...
                fixedCoordinate; stationaryCoordinate]; %#ok<AGROW>
        end

        edgeQuadratic = quadraticMatrix(1, 1);
        edgeLinear = 2.0 * quadraticMatrix(1, 2) ...
            * fixedCoordinate + linearVector(1);
        stationaryCoordinate = localStationaryCoordinate( ...
            edgeQuadratic, edgeLinear);
        if ~isempty(stationaryCoordinate)
            candidateCoordinates(:, end + 1) = [ ...
                stationaryCoordinate; fixedCoordinate]; %#ok<AGROW>
        end
    end

    candidateValues = sum(candidateCoordinates ...
        .* (quadraticMatrix * candidateCoordinates), 1) ...
        + linearVector.' * candidateCoordinates + constant;
    [minimumSafeSideValue, minimumIdx] = min(candidateValues);
    rectangleCoordinate = candidateCoordinates(:, minimumIdx);
    point = egoPose(1:2) + rectangleMap * rectangleCoordinate;
    localOffset = point - boundary.origin;
    witness = struct( ...
        "point", point, ...
        "rectangleCoordinate", rectangleCoordinate, ...
        "localLongitudinalCoordinate", ...
            boundary.longitudinalDirection.' * localOffset, ...
        "localLateralCoordinate", ...
            boundary.lateralDirection.' * localOffset, ...
        "safeSideValue", minimumSafeSideValue);
end

function coordinate = localStationaryCoordinate( ...
        quadraticCoefficient, linearCoefficient)
    coefficientScale = max( ...
        [1.0, abs(quadraticCoefficient), abs(linearCoefficient)]);
    if abs(quadraticCoefficient) ...
            <= 100.0 * eps(coefficientScale)
        coordinate = zeros(0, 1);
        return;
    end
    coordinate = -linearCoefficient ...
        / (2.0 * quadraticCoefficient);
    coordinateTolerance = 100.0 * eps(max(1.0, abs(coordinate)));
    if coordinate < -1.0 - coordinateTolerance ...
            || coordinate > 1.0 + coordinateTolerance
        coordinate = zeros(0, 1);
        return;
    end
    coordinate = min(max(coordinate, -1.0), 1.0);
end

function boundary = localValidateBoundary(boundary)
    if ~isstruct(boundary) || ~isscalar(boundary)
        error("quadraticRoadBoundaryRectangleMargin:invalidBoundary", ...
            "boundary must be a scalar structure.");
    end
    requiredFields = [ ...
        "origin", "longitudinalDirection", "lateralDirection", ...
        "coefficients", "parameterRange", "safeSideSign"];
    if any(~isfield(boundary, requiredFields))
        error("quadraticRoadBoundaryRectangleMargin:invalidBoundary", ...
            "boundary is missing a required finite-quadratic field.");
    end
    boundary.origin = localFiniteVector( ...
        boundary.origin, 2, "boundary.origin");
    boundary.longitudinalDirection = localFiniteVector( ...
        boundary.longitudinalDirection, 2, ...
        "boundary.longitudinalDirection");
    boundary.lateralDirection = localFiniteVector( ...
        boundary.lateralDirection, 2, ...
        "boundary.lateralDirection");
    frame = [boundary.longitudinalDirection, ...
        boundary.lateralDirection];
    if norm(frame.' * frame - eye(2), inf) > 1.0e-10 ...
            || det(frame) <= 0.0 ...
            || abs(det(frame) - 1.0) > 2.0e-10
        error("quadraticRoadBoundaryRectangleMargin:invalidBoundary", ...
            "Boundary directions must form a right-handed " ...
            + "orthonormal frame.");
    end
    boundary.coefficients = localFiniteVector( ...
        boundary.coefficients, 3, ...
        "boundary.coefficients").';
    boundary.parameterRange = localFiniteVector( ...
        boundary.parameterRange, 2, ...
        "boundary.parameterRange").';
    if boundary.parameterRange(1) >= boundary.parameterRange(2)
        error("quadraticRoadBoundaryRectangleMargin:invalidBoundary", ...
            "boundary.parameterRange must increase strictly.");
    end
    signValue = boundary.safeSideSign;
    if ~isnumeric(signValue) || ~isreal(signValue) ...
            || ~isscalar(signValue) ...
            || ~any(double(signValue) == [-1.0, 1.0])
        error("quadraticRoadBoundaryRectangleMargin:invalidBoundary", ...
            "boundary.safeSideSign must be +1 or -1.");
    end
    boundary.safeSideSign = double(signValue);
end

function value = localFiniteVector(value, count, fieldName)
    if ~isnumeric(value) || ~isreal(value) ...
            || numel(value) ~= count ...
            || any(~isfinite(value), "all")
        error("quadraticRoadBoundaryRectangleMargin:invalidInput", ...
            "%s must contain %d finite real values.", ...
            fieldName, count);
    end
    value = double(value(:));
end
