function metadata = renderEstimatedStateAvoidanceVideo( ...
        result, outputPath, varargin)
% renderEstimatedStateAvoidanceVideo Render one avoidance result as video.
%
% The synchronized visualization shows the road, the current finite
% quadratic outer-curb fits, their sensed source points, the shared
% target/road perception range, the known nominal-path-offset shoulder
% corridors, vehicle rectangles, plant and target truth, estimator outputs,
% ego speed, the signed rectangle
% separating-axis margin d_rect, controller inputs, and actual body-frame
% longitudinal/lateral accelerations. MATLAB writes Motion JPEG directly.
% MP4 output is transcoded to H.264 with ffmpeg for broad playback
% compatibility.

    options = localOptions(varargin{:});
    outputPath = localOutputPath(outputPath);
    localValidateResult(result);
    data = localAnimationData(result, options.framePeriod);

    outputDirectory = fileparts(outputPath);
    if strlength(outputDirectory) == 0
        outputDirectory = string(pwd);
        outputPath = fullfile(outputDirectory, outputPath);
    end
    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end

    [writerPath, writerProfile, transcodeToMp4] = ...
        localWriterConfiguration(outputPath);
    writer = VideoWriter(writerPath, writerProfile);
    writer.FrameRate = options.frameRate;
    if isprop(writer, "Quality")
        writer.Quality = options.quality;
    end

    [figureHandle, graphics] = localCreateFigure( ...
        result, data, options);
    figureCleanup = onCleanup(@() localCloseFigure(figureHandle));
    writerCleanup = onCleanup(@() localCloseWriter(writer));
    open(writer);

    frameSize = [1920, 1080];
    for frameIdx = 1:numel(data.time)
        localUpdateFigure(graphics, result, data, frameIdx);
        drawnow;
        frame = localFullHdFrame(getframe(figureHandle));
        writeVideo(writer, frame);
    end

    holdFrameCount = round( ...
        options.holdLastFrameSeconds * options.frameRate);
    if holdFrameCount > 0
        localShowCompletion(graphics, result, data);
        drawnow;
        frame = localFullHdFrame(getframe(figureHandle));
        for frameIdx = 1:holdFrameCount
            writeVideo(writer, frame);
        end
    end
    close(writer);
    clear writerCleanup;

    if transcodeToMp4
        localTranscodeToMp4(writerPath, outputPath, options);
        delete(writerPath);
    end

    fileInformation = dir(outputPath);
    coupling = data.coupling;
    metadata = struct( ...
        "outputPath", string(outputPath), ...
        "frameRate", options.frameRate, ...
        "framePeriod", options.framePeriod, ...
        "simulationDuration", data.time(end)-data.time(1), ...
        "frameCount", numel(data.time)+holdFrameCount, ...
        "videoDuration", ...
            (numel(data.time)+holdFrameCount)/options.frameRate, ...
        "width", frameSize(1), ...
        "height", frameSize(2), ...
        "fileSizeBytes", fileInformation.bytes, ...
        "minimumSeparatingAxisMargin", min(data.separationMargin), ...
        "collisionFree", all(data.separationMargin > 0.0), ...
        "perceptionRange", data.perception.rangeMaximum, ...
        "roadBoundaryVisualizationIncluded", true, ...
        "shoulderVisualizationIncluded", true, ...
        "roadShoulderWidth", ...
            result.perception.roadShoulderWidth, ...
        "roadOuterBoundaryOffsets", ...
            result.perception.roadOuterBoundaryOffsets, ...
        "roadTotalWidthIncludingShoulders", ...
            result.perception.roadTotalWidthIncludingShoulders, ...
        "perceivedRoadBoundaryCount", ...
            data.perception.boundaryCount, ...
        "maximumPerceivedRoadSourcePointRange", ...
            data.perception.maximumSourcePointRange, ...
        "maximumRenderedRoadBoundaryRange", ...
            data.perception.maximumRenderedFitRange, ...
        "minimumRoadBoundaryMargin", min(data.roadMargin), ...
        "noRoadBoundaryCrossing", ...
            result.roadSafety.noBoundaryCrossing, ...
        "firstTargetDetectionTime", ...
            data.estimate.firstDetectionTime, ...
        "preDetectionCruiseDuration", ...
            data.estimate.firstDetectionTime-data.time(1), ...
        "cruiseRecovered", result.avoidance.recoveredCruise, ...
        "maximumRecoverySpeedError", ...
            result.avoidance.maximumRecoverySpeedError, ...
        "maximumRecoveryLateralError", ...
            result.avoidance.maximumRecoveryLateralError, ...
        "maximumRecoveryHeadingError", ...
            result.avoidance.maximumRecoveryHeadingError, ...
        "maximumRecoveryCourseHeadingError", ...
            result.avoidance.maximumRecoveryHeadingError, ...
        "coupledManeuverObserved", coupling.significant, ...
        "coupledSampleCount", coupling.coupledSampleCount, ...
        "maximumContinuousCoupledDuration", ...
            coupling.maximumContinuousCoupledDuration, ...
        "maximumAbsoluteLongitudinalAcceleration", ...
            coupling.maximumAbsoluteLongitudinalAcceleration, ...
        "maximumAbsoluteLateralAcceleration", ...
            coupling.maximumAbsoluteLateralAcceleration, ...
        "maximumSimultaneousAccelerationProduct", ...
            coupling.maximumSimultaneousAccelerationProduct);
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "FramePeriod", 0.025, @localPositiveScalar);
    addParameter(parser, "FrameRate", 20.0, @localPositiveScalar);
    addParameter(parser, "Quality", 90.0, @localValidQuality);
    addParameter(parser, "HoldLastFrameSeconds", ...
        1.0, @localNonnegativeScalar);
    addParameter(parser, "FigureVisible", false, @localLogicalScalar);
    addParameter(parser, "ScenarioLabel", "", @localTextScalar);
    addParameter(parser, "FfmpegPreset", "medium", @localTextScalar);
    addParameter(parser, "FfmpegCrf", 18.0, @localValidCrf);
    parse(parser, varargin{:});
    options = struct( ...
        "framePeriod", double(parser.Results.FramePeriod), ...
        "frameRate", double(parser.Results.FrameRate), ...
        "quality", double(parser.Results.Quality), ...
        "holdLastFrameSeconds", ...
            double(parser.Results.HoldLastFrameSeconds), ...
        "figureVisible", logical(parser.Results.FigureVisible), ...
        "scenarioLabel", string(parser.Results.ScenarioLabel), ...
        "ffmpegPreset", string(parser.Results.FfmpegPreset), ...
        "ffmpegCrf", double(parser.Results.FfmpegCrf));
end

function outputPath = localOutputPath(value)
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error("renderEstimatedStateAvoidanceVideo:invalidOutputPath", ...
            "OutputPath must be a character vector or string scalar.");
    end
    outputPath = string(value);
    [~, ~, extension] = fileparts(outputPath);
    if ~ismember(lower(string(extension)), [".mp4", ".avi"])
        error("renderEstimatedStateAvoidanceVideo:invalidOutputFormat", ...
            "OutputPath must use an .mp4 or .avi extension.");
    end
end

function localValidateResult(result)
    requiredFields = [ ...
        "scenario"; "plantTrace"; "targetTruth"; ...
        "controllerConfiguration"; "controlTime"; "command"; ...
        "controlState"; ...
        "controllerEgoEstimate"; "targetEstimate"; "avoidance"; ...
        "baseline"; "estimator"; "controlTracking"; ...
        "perception"; "roadSafety"];
    if ~isstruct(result) || ~isscalar(result) ...
            || ~all(isfield(result, requiredFields))
        error("renderEstimatedStateAvoidanceVideo:invalidResult", ...
            "Result is not a complete estimator-in-the-loop scenario.");
    end
    if isempty(result.plantTrace.time) ...
            || isempty(result.targetTruth.time)
        error("renderEstimatedStateAvoidanceVideo:emptyResult", ...
            "Result must contain nonempty ego and target traces.");
    end
    if ~result.estimator.enabled
        error("renderEstimatedStateAvoidanceVideo:estimatorDisabled", ...
            "The visualization requires estimator-in-the-loop results.");
    end
    if ~isfield(result.perception, "rangeMaximum") ...
            || ~isfield(result.perception, "roadBoundaryFit") ...
            || ~isfield(result.perception, ...
                "roadBoundaryOffsets") ...
            || ~isfield(result.perception, ...
                "roadShoulderWidth") ...
            || ~isfield(result.perception, ...
                "roadOuterBoundaryOffsets") ...
            || ~isfield(result.perception, ...
                "roadTotalWidthIncludingShoulders") ...
            || ~isfinite(result.perception.rangeMaximum) ...
            || result.perception.rangeMaximum <= 0.0 ...
            || numel(result.perception.roadBoundaryOffsets) ~= 2 ...
            || any(~isfinite( ...
                result.perception.roadBoundaryOffsets), "all") ...
            || any(result.perception.roadBoundaryOffsets <= 0.0) ...
            || ~isscalar(result.perception.roadShoulderWidth) ...
            || ~isfinite(result.perception.roadShoulderWidth) ...
            || result.perception.roadShoulderWidth <= 0.0 ...
            || numel(result.perception.roadOuterBoundaryOffsets) ~= 2 ...
            || any(~isfinite( ...
                result.perception.roadOuterBoundaryOffsets), "all") ...
            || any(result.perception.roadOuterBoundaryOffsets ...
                <= result.perception.roadBoundaryOffsets, "all") ...
            || ~isscalar( ...
                result.perception.roadTotalWidthIncludingShoulders) ...
            || ~isfinite( ...
                result.perception.roadTotalWidthIncludingShoulders) ...
            || result.perception.roadTotalWidthIncludingShoulders <= 0.0 ...
            || ~iscell(result.perception.roadBoundaryFit) ...
            || isempty(result.perception.roadBoundaryFit) ...
            || any(cellfun(@isempty, ...
                result.perception.roadBoundaryFit))
        error("renderEstimatedStateAvoidanceVideo:" ...
            + "missingRoadPerception", ...
            "The visualization requires finite road-boundary fits.");
    end
    expectedOuterOffsets = ...
        result.perception.roadBoundaryOffsets(:) ...
            + result.perception.roadShoulderWidth;
    expectedTotalWidth = ...
        sum(result.perception.roadBoundaryOffsets) ...
            + 2.0*result.perception.roadShoulderWidth;
    geometryTolerance = 100.0*eps(max( ...
        [1.0; expectedOuterOffsets; expectedTotalWidth]));
    if any(abs( ...
            result.perception.roadOuterBoundaryOffsets(:) ...
                - expectedOuterOffsets) > geometryTolerance) ...
            || abs( ...
                result.perception.roadTotalWidthIncludingShoulders ...
                    - expectedTotalWidth) > geometryTolerance
        error("renderEstimatedStateAvoidanceVideo:" ...
            + "inconsistentShoulderGeometry", ...
            "Shoulder width, outer offsets, and total road width " ...
                + "must describe the same geometry.");
    end
    if ~isfield(result.roadSafety, ...
            "conservativeBoundaryFunctionMargin") ...
            || ~isfield(result.roadSafety, ...
                "noBoundaryCrossing")
        error("renderEstimatedStateAvoidanceVideo:" ...
            + "missingRoadSafety", ...
            "The visualization requires road-boundary safety results.");
    end
end

function data = localAnimationData(result, framePeriod)
    sourceTime = result.plantTrace.time(:);
    finiteMask = isfinite(sourceTime);
    sourceTime = sourceTime(finiteMask);
    [sourceTime, uniqueIdx] = unique(sourceTime, "stable");
    if numel(sourceTime) < 2
        error("renderEstimatedStateAvoidanceVideo:shortTrace", ...
            "The plant trace must contain at least two unique times.");
    end

    frameTime = (sourceTime(1):framePeriod:sourceTime(end)).';
    if sourceTime(end)-frameTime(end) ...
            > 100.0*eps(max(1.0, sourceTime(end)))
        frameTime(end+1, 1) = sourceTime(end);
    end

    ego = struct( ...
        "position", [ ...
            localInterpolate(sourceTime, ...
                result.plantTrace.positionX(finiteMask), ...
                uniqueIdx, frameTime), ...
            localInterpolate(sourceTime, ...
                result.plantTrace.positionY(finiteMask), ...
                uniqueIdx, frameTime)], ...
        "yaw", localInterpolate(sourceTime, ...
            unwrap(result.plantTrace.yaw(finiteMask)), ...
            uniqueIdx, frameTime), ...
        "speed", localInterpolate(sourceTime, ...
            result.plantTrace.longitudinalVelocity(finiteMask), ...
            uniqueIdx, frameTime));

    targetTime = result.targetTruth.time(:);
    [targetTime, targetUniqueIdx] = unique(targetTime, "stable");
    target = struct( ...
        "position", [ ...
            interp1(targetTime, ...
                result.targetTruth.position(targetUniqueIdx, 1), ...
                frameTime, "linear", "extrap"), ...
            interp1(targetTime, ...
                result.targetTruth.position(targetUniqueIdx, 2), ...
                frameTime, "linear", "extrap")], ...
        "yaw", interp1(targetTime, ...
            unwrap(result.targetTruth.yaw(targetUniqueIdx)), ...
            frameTime, "linear", "extrap"));

    estimate = localEstimatorSignals(result, frameTime);
    input = localInputSignals(result);
    if isfield(result, "maneuverCoupling")
        coupling = result.maneuverCoupling;
    else
        coupling = evaluateManeuverCoupling(result);
    end
    separationMargin = rectangleSeparationMargin( ...
        ego.position, ego.yaw, target.position, target.yaw, ...
        result.controllerConfiguration.vehicle.length, ...
        result.controllerConfiguration.vehicle.width, ...
        result.targetTruth.length, result.targetTruth.width);
    baselineMarginSource = ...
        result.baseline.separatingAxisMargin(finiteMask);
    baselineMargin = interp1(sourceTime, ...
        baselineMarginSource(uniqueIdx), ...
        frameTime, "linear", "extrap");
    trackingSampleCount = min( ...
        numel(result.controlTime), ...
        numel(result.controlTracking.lateralError));
    trackingTime = result.controlTime(1:trackingSampleCount);
    tracking = struct( ...
        "lateralError", interp1(trackingTime, ...
            result.controlTracking.lateralError( ...
                1:trackingSampleCount), ...
            frameTime, "linear", "extrap"), ...
        "headingError", interp1(trackingTime, ...
            unwrap(result.controlTracking.headingError( ...
                1:trackingSampleCount)), ...
            frameTime, "linear", "extrap"));
    perception = localPerceptionSignals(result, frameTime);
    roadMargin = localRoadMarginSignal( ...
        result, sourceTime, finiteMask, uniqueIdx, frameTime);

    data = struct( ...
        "time", frameTime, ...
        "ego", ego, ...
        "target", target, ...
        "estimate", estimate, ...
        "tracking", tracking, ...
        "input", input, ...
        "coupling", coupling, ...
        "separationMargin", separationMargin, ...
        "baselineMargin", baselineMargin, ...
        "perception", perception, ...
        "roadMargin", roadMargin);
end

function value = localInterpolate( ...
        sourceTime, sourceValue, uniqueIdx, queryTime)
    sourceValue = sourceValue(:);
    value = interp1(sourceTime, sourceValue(uniqueIdx), ...
        queryTime, "linear", "extrap");
end

function estimate = localEstimatorSignals(result, frameTime)
    sampleCount = min([ ...
        numel(result.controllerEgoEstimate), ...
        numel(result.targetEstimate), ...
        numel(result.estimator.sensorFrame), ...
        numel(result.controlTime)-1]);
    sampleTime = result.controlTime(1:sampleCount);
    egoPosition = NaN(sampleCount, 2);
    egoYaw = NaN(sampleCount, 1);
    egoSpeed = NaN(sampleCount, 1);
    targetPosition = NaN(sampleCount, 2);
    targetYaw = NaN(sampleCount, 1);
    radarTargetPosition = NaN(sampleCount, 2);
    radarDetected = false(sampleCount, 1);
    targetEstimateAvailable = false(sampleCount, 1);
    for sampleIdx = 1:sampleCount
        egoOutput = result.controllerEgoEstimate{sampleIdx};
        targetOutput = result.targetEstimate{sampleIdx};
        egoPosition(sampleIdx, :) = ...
            egoOutput.egoState([1, 4]).';
        egoYaw(sampleIdx) = egoOutput.egoYaw;
        egoSpeed(sampleIdx) = norm(egoOutput.egoState([2, 5]));
        if ~isempty(targetOutput)
            targetEstimateAvailable(sampleIdx) = true;
            targetPosition(sampleIdx, :) = ...
                targetOutput.targetPositionInertial(:).';
            targetVelocity = ...
                targetOutput.targetVelocityInertial(:);
            if norm(targetVelocity) > 100.0*eps
                targetYaw(sampleIdx) = atan2( ...
                    targetVelocity(2), targetVelocity(1));
            elseif sampleIdx > 1
                targetYaw(sampleIdx) = targetYaw(sampleIdx-1);
            end
        end
        frame = result.estimator.sensorFrame{sampleIdx};
        radarDetected(sampleIdx) = logical( ...
            frame.radarDetectionAvailable);
        if radarDetected(sampleIdx)
            rotation = localRotation(egoOutput.egoYaw);
            radarTargetPosition(sampleIdx, :) = ...
                (egoOutput.egoState([1, 4]) ...
                    + rotation ...
                        * frame.radarRelativePosition(:)).';
        end
    end
    targetYaw = localUnwrapFinite(targetYaw);
    frameRadarDetected = logical(localPreviousInterpolation( ...
        sampleTime, double(radarDetected), frameTime));
    firstDetectionIdx = find(radarDetected, 1, "first");
    if isempty(firstDetectionIdx)
        firstDetectionTime = NaN;
    else
        firstDetectionTime = sampleTime(firstDetectionIdx);
    end

    estimate = struct( ...
        "egoPosition", localLinearInterpolation( ...
            sampleTime, egoPosition, frameTime), ...
        "egoYaw", localLinearInterpolation( ...
            sampleTime, unwrap(egoYaw), frameTime), ...
        "egoSpeed", localLinearInterpolation( ...
            sampleTime, egoSpeed, frameTime), ...
        "targetPosition", localLinearInterpolation( ...
            sampleTime, targetPosition, frameTime), ...
        "targetYaw", localLinearInterpolation( ...
            sampleTime, targetYaw, frameTime), ...
        "targetEstimateAvailable", ...
            logical(localPreviousInterpolation( ...
                sampleTime, double(targetEstimateAvailable), ...
                frameTime)), ...
        "radarTargetPosition", localPreviousInterpolation( ...
            sampleTime, radarTargetPosition, frameTime), ...
        "radarDetected", frameRadarDetected, ...
        "firstDetectionTime", firstDetectionTime);
end

function value = localUnwrapFinite(value)
    finiteIdx = find(isfinite(value));
    if ~isempty(finiteIdx)
        value(finiteIdx) = unwrap(value(finiteIdx));
    end
end

function value = localLinearInterpolation(sampleTime, sampleValue, queryTime)
    sampleTime = sampleTime(:);
    value = interp1(sampleTime, sampleValue, queryTime, ...
        "linear", "extrap");
end

function value = localPreviousInterpolation(sampleTime, sampleValue, queryTime)
    sampleTime = sampleTime(:);
    value = interp1(sampleTime, sampleValue, queryTime, ...
        "previous", "extrap");
end

function input = localInputSignals(result)
    sampleCount = min(numel(result.command), numel(result.controlTime)-1);
    sampleTime = result.controlTime(1:sampleCount);
    frontAxleTorque = cellfun( ...
        @(value) value.frontAxleTorque, result.command(1:sampleCount));
    steeringAngle = cellfun( ...
        @(value) value.frontWheelSteeringAngle, ...
        result.command(1:sampleCount));
    input = struct( ...
        "time", sampleTime, ...
        "frontAxleTorque", frontAxleTorque(:), ...
        "steeringAngle", steeringAngle(:));
end

function perception = localPerceptionSignals(result, frameTime)
    fit = result.perception.roadBoundaryFit;
    sampleCount = min(numel(fit), numel(result.controlTime)-1);
    sampleTime = result.controlTime(1:sampleCount);
    stepIndex = ones(size(frameTime));
    timeTolerance = 100.0*eps(max(1.0, max(frameTime)));
    for frameIdx = 1:numel(frameTime)
        previousIdx = find(sampleTime <= ...
            frameTime(frameIdx)+timeTolerance, 1, "last");
        if ~isempty(previousIdx)
            stepIndex(frameIdx) = previousIdx;
        end
    end

    boundaryCount = 0;
    maximumSourcePointRange = 0.0;
    maximumRenderedFitRange = 0.0;
    for sampleIdx = 1:sampleCount
        currentPerception = fit{sampleIdx};
        boundaries = currentPerception.roadGeometry.boundaries;
        if numel(boundaries) ~= 2
            error("renderEstimatedStateAvoidanceVideo:" ...
                + "invalidRoadBoundaryCount", ...
                "Each road-perception sample must contain " ...
                    + "right and left boundaries.");
        end
        boundaryCount = max(boundaryCount, numel(boundaries));
        for boundaryIdx = 1:numel(boundaries)
            boundary = boundaries(boundaryIdx);
            maximumSourcePointRange = max( ...
                maximumSourcePointRange, ...
                max(boundary.sourcePointRange));
            fitPoint = localBoundaryFitPoints( ...
                currentPerception, boundary);
            finitePoint = all(isfinite(fitPoint), 2);
            if any(finitePoint)
                fitRange = vecnorm( ...
                    fitPoint(finitePoint, :) ...
                        - currentPerception.egoPose(1:2).', ...
                    2, 2);
                maximumRenderedFitRange = max( ...
                    maximumRenderedFitRange, max(fitRange));
            end
        end
    end

    perception = struct( ...
        "stepIndex", stepIndex, ...
        "rangeMaximum", result.perception.rangeMaximum, ...
        "boundaryCount", boundaryCount, ...
        "maximumSourcePointRange", maximumSourcePointRange, ...
        "maximumRenderedFitRange", maximumRenderedFitRange);
end

function roadMargin = localRoadMarginSignal( ...
        result, sourceTime, finiteMask, uniqueIdx, frameTime)
    margin = result.roadSafety ...
        .conservativeBoundaryFunctionMargin;
    if size(margin, 1) ~= numel(result.plantTrace.time)
        error("renderEstimatedStateAvoidanceVideo:" ...
            + "inconsistentRoadSafety", ...
            "Road margins must align with the plant trace.");
    end
    margin = min(margin(finiteMask, :), [], 2);
    roadMargin = interp1(sourceTime, margin(uniqueIdx), ...
        frameTime, "linear", "extrap");
end

function [figureHandle, graphics] = localCreateFigure( ...
        result, data, options)
    visibility = "off";
    if options.figureVisible
        visibility = "on";
    end
    figureHandle = figure( ...
        Name="Estimator-in-the-loop avoidance visualization", ...
        NumberTitle="off", ...
        Color="w", ...
        Visible=visibility, ...
        MenuBar="none", ...
        ToolBar="none", ...
        Resize="off", ...
        Position=[40, 40, 1280, 720]);
    layout = tiledlayout(figureHandle, 3, 4, ...
        TileSpacing="compact", Padding="compact");

    trajectoryAxes = nexttile(layout, 1, [3, 3]);
    hold(trajectoryAxes, "on");
    grid(trajectoryAxes, "on");
    axis(trajectoryAxes, "equal");
    roadGraphics = localDrawRoad( ...
        trajectoryAxes, result.scenario.centerline, ...
        result.perception.roadBoundaryOffsets, ...
        result.perception.roadShoulderWidth);
    perceptionRangeArea = patch(trajectoryAxes, NaN, NaN, ...
        [0.20, 0.70, 0.90], EdgeColor="none", ...
        FaceAlpha=0.07, HandleVisibility="off");
    perceptionRange = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.00, 0.55, 0.75], LineStyle="--", ...
        LineWidth=1.5, ...
        DisplayName=compose("%.0f m perception range", ...
            result.perception.rangeMaximum));
    centerline = plot(trajectoryAxes, ...
        result.scenario.centerline(:, 1), ...
        result.scenario.centerline(:, 2), ...
        "k--", LineWidth=1.1, DisplayName="Centerline");
    rightBoundaryFit = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.10, 0.60, 0.20], LineWidth=2.5, ...
        DisplayName="Sensed right outer curb");
    leftBoundaryFit = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.80, 0.18, 0.18], LineWidth=2.5, ...
        DisplayName="Sensed left outer curb");
    rightBoundarySamples = plot(trajectoryAxes, NaN, NaN, ...
        ".", Color=[0.05, 0.35, 0.10], MarkerSize=7, ...
        HandleVisibility="off");
    leftBoundarySamples = plot(trajectoryAxes, NaN, NaN, ...
        ".", Color=[0.50, 0.06, 0.06], MarkerSize=7, ...
        HandleVisibility="off");
    perceptionRangeLabel = text(trajectoryAxes, NaN, NaN, "", ...
        HorizontalAlignment="center", ...
        VerticalAlignment="bottom", FontSize=8, ...
        FontWeight="bold", Color=[0.00, 0.35, 0.50], ...
        BackgroundColor="w", Margin=2, ...
        HandleVisibility="off");
    baseline = plot(trajectoryAxes, ...
        result.baseline.egoPosition(:, 1), ...
        result.baseline.egoPosition(:, 2), ...
        Color=[0.55, 0.55, 0.55], ...
        LineStyle=":", LineWidth=1.2, ...
        DisplayName="No-avoidance baseline");
    targetPlan = plot(trajectoryAxes, ...
        data.target.position(:, 1), data.target.position(:, 2), ...
        Color=[0.85, 0.33, 0.10], ...
        LineStyle="--", LineWidth=1.0, ...
        DisplayName="Target truth path");
    egoTrail = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.00, 0.45, 0.74], LineWidth=2.3, ...
        DisplayName="Ego truth");
    targetTrail = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.85, 0.33, 0.10], LineWidth=2.0, ...
        DisplayName="Target truth");
    egoEstimateTrail = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.00, 0.72, 0.72], LineStyle=":", ...
        LineWidth=1.5, DisplayName="Ego estimate");
    targetEstimateTrail = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.64, 0.08, 0.75], LineStyle=":", ...
        LineWidth=1.5, DisplayName="Target estimate");
    egoPatch = patch(trajectoryAxes, NaN, NaN, ...
        [0.10, 0.55, 0.95], EdgeColor=[0.00, 0.18, 0.42], ...
        FaceAlpha=0.88, LineWidth=1.5, HandleVisibility="off");
    targetPatch = patch(trajectoryAxes, NaN, NaN, ...
        [0.95, 0.45, 0.10], EdgeColor=[0.45, 0.12, 0.02], ...
        FaceAlpha=0.88, LineWidth=1.5, HandleVisibility="off");
    egoNose = plot(trajectoryAxes, NaN, NaN, ...
        "k-", LineWidth=1.8, HandleVisibility="off");
    targetNose = plot(trajectoryAxes, NaN, NaN, ...
        "k-", LineWidth=1.8, HandleVisibility="off");
    egoEstimateMarker = plot(trajectoryAxes, NaN, NaN, ...
        "+", Color=[0.00, 0.72, 0.72], MarkerSize=10, ...
        LineWidth=2.0, HandleVisibility="off");
    targetEstimateMarker = plot(trajectoryAxes, NaN, NaN, ...
        "x", Color=[0.64, 0.08, 0.75], MarkerSize=10, ...
        LineWidth=2.0, HandleVisibility="off");
    radarLine = plot(trajectoryAxes, NaN, NaN, ...
        Color=[0.64, 0.08, 0.75], ...
        LineStyle="--", LineWidth=1.0, HandleVisibility="off");
    radarMeasurementMarker = plot(trajectoryAxes, NaN, NaN, ...
        "o", Color=[0.64, 0.08, 0.75], ...
        MarkerFaceColor=[0.90, 0.72, 0.95], ...
        MarkerSize=6, LineWidth=1.2, ...
        HandleVisibility="off");
    status = text(trajectoryAxes, 0.015, 0.985, "", ...
        Units="normalized", VerticalAlignment="top", ...
        FontName="Monospaced", FontSize=10, ...
        Color=[0.08, 0.08, 0.08], ...
        BackgroundColor="w", Margin=5);
    xlabel(trajectoryAxes, "Inertial x (m)");
    ylabel(trajectoryAxes, "Inertial y (m)");
    trajectoryLegend = legend(trajectoryAxes, ...
        [perceptionRange, roadGraphics.shoulderSurface, ...
        roadGraphics.laneEdge, rightBoundaryFit, leftBoundaryFit, ...
        centerline, baseline, targetPlan, egoTrail, targetTrail, ...
        egoEstimateTrail, targetEstimateTrail], ...
        Location="southoutside", Orientation="horizontal", ...
        NumColumns=4, FontSize=6.7);

    speedAxes = nexttile(layout, 4);
    hold(speedAxes, "on");
    grid(speedAxes, "on");
    yline(speedAxes, result.scenario.referenceSpeed, ...
        "k--", "Reference", HandleVisibility="off");
    speedTruth = plot(speedAxes, NaN, NaN, ...
        Color=[0.00, 0.45, 0.74], LineWidth=1.8, ...
        DisplayName="Truth v_x");
    speedEstimate = plot(speedAxes, NaN, NaN, ...
        Color=[0.00, 0.72, 0.72], LineStyle=":", ...
        LineWidth=1.6, DisplayName="Estimated |v|");
    speedCursor = xline(speedAxes, data.time(1), ...
        Color=[0.25, 0.25, 0.25], HandleVisibility="off");
    xlim(speedAxes, [data.time(1), data.time(end)]);
    ylim(speedAxes, localPaddedLimits([ ...
        data.ego.speed; data.estimate.egoSpeed; ...
        result.scenario.referenceSpeed]));
    title(speedAxes, "Ego speed", Color=[0.08, 0.08, 0.08]);
    xlabel(speedAxes, "Time (s)");
    ylabel(speedAxes, "Speed (m/s)");
    speedLegend = legend(speedAxes, Location="best", FontSize=8);

    marginAxes = nexttile(layout, 8);
    hold(marginAxes, "on");
    grid(marginAxes, "on");
    yline(marginAxes, 0.0, "r-", "d_{rect}=0", ...
        HandleVisibility="off");
    baselineMargin = plot(marginAxes, ...
        data.time, data.baselineMargin, ...
        Color=[0.70, 0.70, 0.70], LineStyle=":", ...
        LineWidth=1.0, DisplayName="No avoidance");
    controlledMargin = plot(marginAxes, NaN, NaN, ...
        Color=[0.47, 0.67, 0.19], LineWidth=1.9, ...
        DisplayName="Controlled");
    currentMargin = plot(marginAxes, NaN, NaN, "o", ...
        MarkerFaceColor=[0.47, 0.67, 0.19], ...
        MarkerEdgeColor=[0.16, 0.32, 0.04], ...
        HandleVisibility="off");
    marginCursor = xline(marginAxes, data.time(1), ...
        Color=[0.25, 0.25, 0.25], HandleVisibility="off");
    xlim(marginAxes, [data.time(1), data.time(end)]);
    ylim(marginAxes, localMarginLimits( ...
        data.separationMargin, data.baselineMargin));
    title(marginAxes, "Collision constraint", ...
        Color=[0.08, 0.08, 0.08]);
    xlabel(marginAxes, "Time (s)");
    ylabel(marginAxes, "d_{rect} (m)");
    marginLegend = legend(marginAxes, ...
        [baselineMargin, controlledMargin], ...
        Location="best", FontSize=8);

    inputAxes = nexttile(layout, 12);
    hold(inputAxes, "on");
    grid(inputAxes, "on");
    yyaxis(inputAxes, "left");
    frontAxleTorque = plot(inputAxes, NaN, NaN, ...
        Color=[0.49, 0.18, 0.56], LineWidth=1.6, ...
        DisplayName="Front-axle torque (kN m)");
    steeringAngle = plot(inputAxes, NaN, NaN, ...
        Color=[0.93, 0.69, 0.13], LineWidth=1.6, ...
        DisplayName="Steering (rad)");
    ylabel(inputAxes, "Torque (kN m) / angle (rad)");
    yyaxis(inputAxes, "right");
    longitudinalAcceleration = plot(inputAxes, NaN, NaN, ...
        Color=[0.64, 0.08, 0.18], LineStyle=":", ...
        LineWidth=1.7, DisplayName="Body a_x");
    lateralAcceleration = plot(inputAxes, NaN, NaN, ...
        Color=[0.10, 0.55, 0.25], LineStyle="--", ...
        LineWidth=1.7, DisplayName="Body a_y");
    ylabel(inputAxes, "Body acceleration (m/s^2)");
    inputCursor = xline(inputAxes, data.time(1), ...
        Color=[0.25, 0.25, 0.25], HandleVisibility="off");
    xlim(inputAxes, [data.time(1), data.time(end)]);
    title(inputAxes, "Control and coupled motion", ...
        Color=[0.08, 0.08, 0.08]);
    xlabel(inputAxes, "Time (s)");
    inputLegend = legend(inputAxes, ...
        [frontAxleTorque, steeringAngle, ...
            longitudinalAcceleration, lateralAcceleration], ...
        Location="best", FontSize=7);

    scenarioLabel = options.scenarioLabel;
    if strlength(scenarioLabel) == 0
        scenarioLabel = string(result.scenario.description);
    end
    titleText = scenarioLabel ...
        + " | estimator-in-the-loop | sensed road + target range = " ...
        + compose("%.0f m", result.perception.rangeMaximum) ...
        + compose(" | %.1f m shoulders per side", ...
            result.perception.roadShoulderWidth) ...
        + " | truth rectangles define d_{rect}";
    titleHandle = sgtitle(layout, titleText, ...
        FontWeight="bold", Color=[0.08, 0.08, 0.08]);
    localStyleAxes( ...
        [trajectoryAxes, speedAxes, marginAxes, inputAxes], ...
        [trajectoryLegend, speedLegend, marginLegend, inputLegend]);

    graphics = struct( ...
        "figure", figureHandle, ...
        "title", titleHandle, ...
        "trajectoryAxes", trajectoryAxes, ...
        "perceptionRangeArea", perceptionRangeArea, ...
        "perceptionRange", perceptionRange, ...
        "perceptionRangeLabel", perceptionRangeLabel, ...
        "rightBoundaryFit", rightBoundaryFit, ...
        "leftBoundaryFit", leftBoundaryFit, ...
        "rightBoundarySamples", rightBoundarySamples, ...
        "leftBoundarySamples", leftBoundarySamples, ...
        "egoTrail", egoTrail, ...
        "targetTrail", targetTrail, ...
        "egoEstimateTrail", egoEstimateTrail, ...
        "targetEstimateTrail", targetEstimateTrail, ...
        "egoPatch", egoPatch, ...
        "targetPatch", targetPatch, ...
        "egoNose", egoNose, ...
        "targetNose", targetNose, ...
        "egoEstimateMarker", egoEstimateMarker, ...
        "targetEstimateMarker", targetEstimateMarker, ...
        "radarLine", radarLine, ...
        "radarMeasurementMarker", radarMeasurementMarker, ...
        "status", status, ...
        "speedTruth", speedTruth, ...
        "speedEstimate", speedEstimate, ...
        "speedCursor", speedCursor, ...
        "controlledMargin", controlledMargin, ...
        "currentMargin", currentMargin, ...
        "marginCursor", marginCursor, ...
        "frontAxleTorque", frontAxleTorque, ...
        "steeringAngle", steeringAngle, ...
        "longitudinalAcceleration", longitudinalAcceleration, ...
        "lateralAcceleration", lateralAcceleration, ...
        "inputCursor", inputCursor);
end

function localStyleAxes(axesHandles, legendHandles)
    for axesIdx = 1:numel(axesHandles)
        axesHandle = axesHandles(axesIdx);
        axesHandle.Color = [1.0, 1.0, 1.0];
        axesHandle.XColor = [0.10, 0.10, 0.10];
        axesHandle.GridColor = [0.55, 0.55, 0.55];
        axesHandle.GridAlpha = 0.30;
        for rulerIdx = 1:numel(axesHandle.YAxis)
            axesHandle.YAxis(rulerIdx).Color = [0.10, 0.10, 0.10];
        end
    end
    for legendIdx = 1:numel(legendHandles)
        legendHandle = legendHandles(legendIdx);
        legendHandle.Color = [1.0, 1.0, 1.0];
        legendHandle.TextColor = [0.08, 0.08, 0.08];
        legendHandle.EdgeColor = [0.55, 0.55, 0.55];
    end
end

function graphics = localDrawRoad( ...
        axesHandle, centerline, boundaryOffsets, shoulderWidth)
    position = double(centerline);
    tangent = [gradient(position(:, 1)), gradient(position(:, 2))];
    tangentNorm = vecnorm(tangent, 2, 2);
    tangent = tangent ./ tangentNorm;
    normal = [-tangent(:, 2), tangent(:, 1)];
    rightOffset = boundaryOffsets(1);
    leftOffset = boundaryOffsets(2);
    leftLaneEdge = position + leftOffset*normal;
    rightLaneEdge = position - rightOffset*normal;
    leftShoulderOuter = position ...
        + (leftOffset+shoulderWidth)*normal;
    rightShoulderOuter = position ...
        - (rightOffset+shoulderWidth)*normal;

    shoulderSurface = patch(axesHandle, ...
        [leftShoulderOuter(:, 1); ...
            flipud(rightShoulderOuter(:, 1))], ...
        [leftShoulderOuter(:, 2); ...
            flipud(rightShoulderOuter(:, 2))], ...
        [0.82, 0.78, 0.66], EdgeColor="none", ...
        FaceAlpha=0.75, ...
        DisplayName=compose("%.1f m nominal shoulders", ...
            shoulderWidth));
    patch(axesHandle, ...
        [leftLaneEdge(:, 1); flipud(rightLaneEdge(:, 1))], ...
        [leftLaneEdge(:, 2); flipud(rightLaneEdge(:, 2))], ...
        [0.93, 0.93, 0.93], EdgeColor="none", ...
        HandleVisibility="off");
    laneEdge = plot(axesHandle, ...
        leftLaneEdge(:, 1), leftLaneEdge(:, 2), ...
        Color=[0.80, 0.55, 0.05], LineStyle="--", ...
        LineWidth=1.4, DisplayName="Lane edge / shoulder entry");
    plot(axesHandle, ...
        rightLaneEdge(:, 1), rightLaneEdge(:, 2), ...
        Color=[0.80, 0.55, 0.05], LineStyle="--", ...
        LineWidth=1.4, HandleVisibility="off");
    plot(axesHandle, ...
        leftShoulderOuter(:, 1), leftShoulderOuter(:, 2), ...
        Color=[0.25, 0.25, 0.25], LineStyle=":", ...
        LineWidth=1.0, HandleVisibility="off");
    plot(axesHandle, ...
        rightShoulderOuter(:, 1), rightShoulderOuter(:, 2), ...
        Color=[0.25, 0.25, 0.25], LineStyle=":", ...
        LineWidth=1.0, HandleVisibility="off");
    graphics = struct( ...
        "shoulderSurface", shoulderSurface, ...
        "laneEdge", laneEdge);
end

function fitPoint = localBoundaryFitPoints(perception, boundary)
    parameterRange = boundary.parameterRange;
    parameterCount = max( ...
        80, ceil(diff(parameterRange)/0.20)+1);
    parameter = linspace( ...
        parameterRange(1), parameterRange(2), parameterCount);
    lateral = polyval(boundary.coefficients, parameter);
    fitPoint = ( ...
        boundary.origin ...
        + boundary.longitudinalDirection*parameter ...
        + boundary.lateralDirection*lateral).';
    fitRange = vecnorm( ...
        fitPoint-perception.egoPose(1:2).', 2, 2);
    rangeTolerance = 100.0*eps(max( ...
        1.0, perception.rangeMaximum));
    fitPoint(fitRange > ...
        perception.rangeMaximum+rangeTolerance, :) = NaN;
end

function localUpdateBoundaryGraphics( ...
        fitHandle, sampleHandle, perception, boundary)
    fitPoint = localBoundaryFitPoints(perception, boundary);
    sourcePoint = boundary.sourcePoints;
    set(fitHandle, ...
        XData=fitPoint(:, 1), YData=fitPoint(:, 2));
    set(sampleHandle, ...
        XData=sourcePoint(:, 1), YData=sourcePoint(:, 2));
end

function localUpdateFigure(graphics, result, data, frameIdx)
    time = data.time(frameIdx);
    egoPosition = data.ego.position(frameIdx, :).';
    targetPosition = data.target.position(frameIdx, :).';
    estimatedEgoPosition = ...
        data.estimate.egoPosition(frameIdx, :).';
    estimatedTargetPosition = ...
        data.estimate.targetPosition(frameIdx, :).';
    egoYaw = data.ego.yaw(frameIdx);
    targetYaw = data.target.yaw(frameIdx);
    egoLength = result.controllerConfiguration.vehicle.length;
    egoWidth = result.controllerConfiguration.vehicle.width;
    targetLength = result.targetTruth.length;
    targetWidth = result.targetTruth.width;
    perceptionStep = data.perception.stepIndex(frameIdx);
    perception = result.perception ...
        .roadBoundaryFit{perceptionStep};
    perceptionCenter = perception.egoPose(1:2);
    perceptionAngle = linspace(0.0, 2.0*pi, 181);
    perceptionPoint = perceptionCenter ...
        + perception.rangeMaximum ...
            * [cos(perceptionAngle); sin(perceptionAngle)];
    set(graphics.perceptionRangeArea, ...
        XData=perceptionPoint(1, :), ...
        YData=perceptionPoint(2, :));
    set(graphics.perceptionRange, ...
        XData=perceptionPoint(1, :), ...
        YData=perceptionPoint(2, :));
    set(graphics.perceptionRangeLabel, ...
        Position=[ ...
            perceptionCenter(1), ...
            perceptionCenter(2)+perception.rangeMaximum, ...
            0.0], ...
        String=compose("%.0f m sensing limit", ...
            perception.rangeMaximum));
    boundaries = perception.roadGeometry.boundaries;
    localUpdateBoundaryGraphics( ...
        graphics.rightBoundaryFit, ...
        graphics.rightBoundarySamples, ...
        perception, boundaries(1));
    localUpdateBoundaryGraphics( ...
        graphics.leftBoundaryFit, ...
        graphics.leftBoundarySamples, ...
        perception, boundaries(2));

    egoVertices = localPoseRectangle( ...
        egoPosition, egoYaw, egoLength, egoWidth);
    targetVertices = localPoseRectangle( ...
        targetPosition, targetYaw, targetLength, targetWidth);
    set(graphics.egoPatch, ...
        XData=egoVertices(1, :), YData=egoVertices(2, :));
    set(graphics.targetPatch, ...
        XData=targetVertices(1, :), YData=targetVertices(2, :));
    set(graphics.egoNose, ...
        XData=[egoPosition(1), ...
            egoPosition(1)+0.5*egoLength*cos(egoYaw)], ...
        YData=[egoPosition(2), ...
            egoPosition(2)+0.5*egoLength*sin(egoYaw)]);
    set(graphics.targetNose, ...
        XData=[targetPosition(1), ...
            targetPosition(1)+0.5*targetLength*cos(targetYaw)], ...
        YData=[targetPosition(2), ...
            targetPosition(2)+0.5*targetLength*sin(targetYaw)]);
    set(graphics.egoTrail, ...
        XData=data.ego.position(1:frameIdx, 1), ...
        YData=data.ego.position(1:frameIdx, 2));
    set(graphics.targetTrail, ...
        XData=data.target.position(1:frameIdx, 1), ...
        YData=data.target.position(1:frameIdx, 2));
    set(graphics.egoEstimateTrail, ...
        XData=data.estimate.egoPosition(1:frameIdx, 1), ...
        YData=data.estimate.egoPosition(1:frameIdx, 2));
    set(graphics.targetEstimateTrail, ...
        XData=data.estimate.targetPosition(1:frameIdx, 1), ...
        YData=data.estimate.targetPosition(1:frameIdx, 2));
    set(graphics.egoEstimateMarker, ...
        XData=estimatedEgoPosition(1), ...
        YData=estimatedEgoPosition(2));
    set(graphics.targetEstimateMarker, ...
        XData=estimatedTargetPosition(1), ...
        YData=estimatedTargetPosition(2));

    if data.estimate.radarDetected(frameIdx)
        radarTargetPosition = ...
            data.estimate.radarTargetPosition(frameIdx, :).';
        set(graphics.radarLine, ...
            XData=[estimatedEgoPosition(1), ...
                radarTargetPosition(1)], ...
            YData=[estimatedEgoPosition(2), ...
                radarTargetPosition(2)]);
        set(graphics.radarMeasurementMarker, ...
            XData=radarTargetPosition(1), ...
            YData=radarTargetPosition(2));
        radarState = "DETECTED";
    else
        set(graphics.radarLine, XData=NaN, YData=NaN);
        set(graphics.radarMeasurementMarker, ...
            XData=NaN, YData=NaN);
        if any(data.estimate.radarDetected(1:frameIdx))
            radarState = "POST-DETECTION OUT OF RANGE";
        else
            radarState = "PRE-DETECTION CRUISE";
        end
    end

    margin = data.separationMargin(frameIdx);
    accelerationIdx = find( ...
        data.coupling.time <= time ...
            + 100.0*eps(max(1.0, time)), 1, "last");
    if isempty(accelerationIdx)
        bodyLongitudinalAcceleration = NaN;
        bodyLateralAcceleration = NaN;
        couplingState = "NO";
    else
        bodyLongitudinalAcceleration = ...
            data.coupling.longitudinalAcceleration(accelerationIdx);
        bodyLateralAcceleration = ...
            data.coupling.lateralAcceleration(accelerationIdx);
        couplingState = localYesNo( ...
            data.coupling.coupledMask(accelerationIdx));
    end
    egoPositionError = norm(estimatedEgoPosition-egoPosition);
    targetPositionError = ...
        norm(estimatedTargetPosition-targetPosition);
    roadMargin = data.roadMargin(frameIdx);
    graphics.status.String = sprintf( ...
        "t = %4.2f s | v_x = %5.2f m/s | " ...
        + "d_rect = %+6.3f m (>0 safe)\n" ...
        + "centerline e_y = %+6.3f m | e_psi = %+6.3f rad | " ...
        + "radar = %s\n" ...
        + "perception = %.1f m | road margin = %+6.3f m | " ...
        + "sensed outer-curb fits = %d\n" ...
        + "shoulders = %.1f m/side | outer offsets R/L = " ...
        + "%.1f/%.1f m\n" ...
        + "body a_x = %+6.2f m/s^2 | a_y = %+6.2f m/s^2 | " ...
        + "coupled = %s\n" ...
        + "ego position error = %.3f m | " ...
        + "target position error = %.3f m", ...
        time, data.ego.speed(frameIdx), margin, ...
        data.tracking.lateralError(frameIdx), ...
        data.tracking.headingError(frameIdx), radarState, ...
        perception.rangeMaximum, roadMargin, ...
        numel(boundaries), ...
        result.perception.roadShoulderWidth, ...
        result.perception.roadOuterBoundaryOffsets(1), ...
        result.perception.roadOuterBoundaryOffsets(2), ...
        bodyLongitudinalAcceleration, ...
        bodyLateralAcceleration, couplingState, ...
        egoPositionError, targetPositionError);
    if margin > 0.0
        graphics.egoPatch.FaceColor = [0.10, 0.55, 0.95];
    else
        graphics.egoPatch.FaceColor = [0.90, 0.10, 0.10];
    end

    [xLimits, yLimits] = localCameraLimits( ...
        egoPosition, targetPosition, ...
        perception.rangeMaximum);
    xlim(graphics.trajectoryAxes, xLimits);
    ylim(graphics.trajectoryAxes, yLimits);

    set(graphics.speedTruth, ...
        XData=data.time(1:frameIdx), ...
        YData=data.ego.speed(1:frameIdx));
    set(graphics.speedEstimate, ...
        XData=data.time(1:frameIdx), ...
        YData=data.estimate.egoSpeed(1:frameIdx));
    graphics.speedCursor.Value = time;
    set(graphics.controlledMargin, ...
        XData=data.time(1:frameIdx), ...
        YData=data.separationMargin(1:frameIdx));
    set(graphics.currentMargin, XData=time, YData=margin);
    graphics.marginCursor.Value = time;

    inputMask = data.input.time <= time ...
        + 100.0*eps(max(1.0, time));
    set(graphics.frontAxleTorque, ...
        XData=data.input.time(inputMask), ...
        YData=1.0e-3*data.input.frontAxleTorque(inputMask));
    set(graphics.steeringAngle, ...
        XData=data.input.time(inputMask), ...
        YData=data.input.steeringAngle(inputMask));
    accelerationMask = data.coupling.time <= time ...
        + 100.0*eps(max(1.0, time));
    set(graphics.longitudinalAcceleration, ...
        XData=data.coupling.time(accelerationMask), ...
        YData=data.coupling ...
            .longitudinalAcceleration(accelerationMask));
    set(graphics.lateralAcceleration, ...
        XData=data.coupling.time(accelerationMask), ...
        YData=data.coupling.lateralAcceleration(accelerationMask));
    graphics.inputCursor.Value = time;
end

function localShowCompletion(graphics, result, data)
    if all(data.separationMargin > 0.0) ...
            && result.avoidance.passedTarget ...
            && result.avoidance.remainedMoving ...
            && result.avoidance.recoveredCruise
        outcome = "COMPLETE: collision avoided; " ...
            + "centerline cruise recovered";
    elseif all(data.separationMargin > 0.0) ...
            && result.avoidance.passedTarget ...
            && result.avoidance.remainedMoving
        outcome = "COMPLETE: collision avoided; recovery failed";
    elseif all(data.separationMargin > 0.0)
        outcome = "COMPLETE: collision avoided";
    else
        outcome = "COMPLETE: collision occurred";
    end
    graphics.status.String = sprintf( ...
        "%s\nminimum d_rect = %.3f m | " ...
        + "minimum road margin = %.3f m | road contained = %s\n" ...
        + "perception range = %.1f m | shoulders = %.1f m/side | " ...
        + "road width = %.1f m\n" ...
        + "minimum ego speed = %.3f m/s\n" ...
        + "final-window max |speed/lateral/heading error| = " ...
        + "%.3f m/s / %.3f m / %.3f rad\n" ...
        + "coupled maneuver = %s | longest %.2f s " ...
        + "(required %.2f s) | peak |a_x a_y| = %.2f", ...
        outcome, min(data.separationMargin), ...
        min(data.roadMargin), ...
        localYesNo(result.roadSafety.noBoundaryCrossing), ...
        data.perception.rangeMaximum, ...
        result.perception.roadShoulderWidth, ...
        result.perception.roadTotalWidthIncludingShoulders, ...
        result.avoidance.minimumEgoLongitudinalSpeed, ...
        result.avoidance.maximumRecoverySpeedError, ...
        result.avoidance.maximumRecoveryLateralError, ...
        result.avoidance.maximumRecoveryHeadingError, ...
        localYesNo(data.coupling.significant), ...
        data.coupling.maximumContinuousCoupledDuration, ...
        data.coupling.minimumCoupledDuration, ...
        data.coupling.maximumSimultaneousAccelerationProduct);
end

function value = localYesNo(condition)
    if condition
        value = "YES";
    else
        value = "NO";
    end
end

function frame = localFullHdFrame(frame)
    targetHeight = 1080;
    targetWidth = 1920;
    image = frame.cdata;
    image = localCenteredCrop(image, targetHeight, targetWidth);
    imageHeight = size(image, 1);
    imageWidth = size(image, 2);
    canvas = repmat( ...
        uint8(255), targetHeight, targetWidth, size(image, 3));
    firstRow = floor((targetHeight-imageHeight)/2) + 1;
    firstColumn = floor((targetWidth-imageWidth)/2) + 1;
    canvas( ...
        firstRow:(firstRow+imageHeight-1), ...
        firstColumn:(firstColumn+imageWidth-1), :) = image;
    frame.cdata = canvas;
    frame.colormap = [];
end

function image = localCenteredCrop(image, targetHeight, targetWidth)
    imageHeight = size(image, 1);
    imageWidth = size(image, 2);
    if imageHeight > targetHeight
        firstRow = floor((imageHeight-targetHeight)/2) + 1;
        image = image(firstRow:(firstRow+targetHeight-1), :, :);
    end
    if imageWidth > targetWidth
        firstColumn = floor((imageWidth-targetWidth)/2) + 1;
        image = image(:, firstColumn:(firstColumn+targetWidth-1), :);
    end
end

function vertices = localPoseRectangle(position, yaw, length, width)
    bodyVertices = 0.5 * [ ...
        length, length, -length, -length; ...
        width, -width, -width, width];
    rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
    vertices = rotation*bodyVertices+position;
end

function rotation = localRotation(yaw)
    rotation = [cos(yaw), -sin(yaw); sin(yaw), cos(yaw)];
end

function [xLimits, yLimits] = localCameraLimits( ...
        egoPosition, targetPosition, perceptionRange)
    relativePosition = targetPosition-egoPosition;
    rangePadding = 3.0;
    xLimits = egoPosition(1) ...
        + [-perceptionRange-rangePadding, ...
            perceptionRange+rangePadding];
    yLimits = egoPosition(2) ...
        + [-perceptionRange-rangePadding, ...
            perceptionRange+rangePadding];
    if norm(relativePosition) <= 65.0
        targetPadding = 6.0;
        xLimits(1) = min( ...
            xLimits(1), targetPosition(1)-targetPadding);
        xLimits(2) = max( ...
            xLimits(2), targetPosition(1)+targetPadding);
        yLimits(1) = min( ...
            yLimits(1), targetPosition(2)-targetPadding);
        yLimits(2) = max( ...
            yLimits(2), targetPosition(2)+targetPadding);
    end
end

function limits = localPaddedLimits(value)
    finiteValue = value(isfinite(value));
    minimum = min(finiteValue);
    maximum = max(finiteValue);
    padding = max(0.5, 0.10*(maximum-minimum));
    limits = [minimum-padding, maximum+padding];
end

function limits = localMarginLimits(controlledMargin, baselineMargin)
    value = [controlledMargin(:); baselineMargin(:); 0.0];
    finiteValue = value(isfinite(value));
    minimum = min(finiteValue);
    lowerPadding = max(0.5, 0.06*abs(minimum));
    lower = min(-1.0, minimum-lowerPadding);
    upper = min(45.0, max(5.0, max(finiteValue)+0.5));
    limits = [lower, upper];
end

function [writerPath, profile, transcodeToMp4] = ...
        localWriterConfiguration(outputPath)
    [outputDirectory, ~, extension] = fileparts(outputPath);
    transcodeToMp4 = lower(string(extension)) == ".mp4";
    if transcodeToMp4
        writerPath = string(tempname(outputDirectory))+".avi";
        profile = "Motion JPEG AVI";
    else
        writerPath = outputPath;
        profile = "Motion JPEG AVI";
    end
end

function localTranscodeToMp4(inputPath, outputPath, options)
    [locationStatus, ffmpegLocation] = ...
        system("command -v ffmpeg");
    ffmpegLocation = strtrim(string(ffmpegLocation));
    if locationStatus ~= 0 || strlength(ffmpegLocation) == 0
        error("renderEstimatedStateAvoidanceVideo:ffmpegUnavailable", ...
            "ffmpeg is required for H.264 MP4 output.");
    end
    ffmpegCommand = "env -u LD_LIBRARY_PATH " ...
        + localShellQuote(ffmpegLocation);
    [ffmpegStatus, ~] = system(ffmpegCommand+" -version");
    if ffmpegStatus ~= 0
        error("renderEstimatedStateAvoidanceVideo:ffmpegUnavailable", ...
            "The system ffmpeg executable could not be started.");
    end
    command = ffmpegCommand ...
        + " -hide_banner -loglevel error -y -i " ...
        + localShellQuote(inputPath) ...
        + " -an -c:v libx264 -preset " ...
        + localShellQuote(options.ffmpegPreset) ...
        + " -crf " + string(options.ffmpegCrf) ...
        + " -pix_fmt yuv420p -movflags +faststart " ...
        + localShellQuote(outputPath);
    [status, message] = system(command);
    if status ~= 0
        error("renderEstimatedStateAvoidanceVideo:transcodeFailed", ...
            "ffmpeg failed: %s", strtrim(message));
    end
end

function quoted = localShellQuote(value)
    quoted = "'" + replace(string(value), "'", "'""'""'") + "'";
end

function localCloseWriter(writer)
    try
        close(writer);
    catch
    end
end

function localCloseFigure(figureHandle)
    if isgraphics(figureHandle)
        close(figureHandle);
    end
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localValidQuality(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0 && value <= 100.0;
end

function valid = localValidCrf(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0 && value <= 51.0;
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localTextScalar(value)
    valid = ischar(value) || (isstring(value) && isscalar(value));
end
