function result = runCenterlineCruiseScenario(varargin)
% runCenterlineCruiseScenario Simulate centerline tracking with the MPC.
%
% The collision-avoidance controller is connected directly to the
% PassVeh14DOF plant from Vehicle Dynamics Blockset. The ego vehicle starts
% on the supplied centerline at the configured reference speed. An optional
% target-state function supplies target truth at every controller sample.
% When UseStateEstimator is true, that truth is visible only to the
% synthetic GNSS/IMU/gyroscope/radar layer and to result evaluation; the
% controller receives the online NRMM ego and target estimates.
% A controller failure stops the experiment and retains the failed sample.
% The adapter
% initializes wheel speed from the plant's loaded rolling radius, maps the
% Blockset SAE y-right convention to the controller's y-left convention,
% and copies the plant's inertial and geometric parameters into the
% controller configuration.

    options = localOptions(varargin{:});
    previousThreads = maxNumCompThreads(options.computationalThreads);
    threadCleanup = onCleanup(@() maxNumCompThreads(previousThreads));
    repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repositoryRoot, "config"));
    addpath(fullfile(repositoryRoot, "controller"));
    addpath(genpath(fullfile(repositoryRoot, "estimator")));

    plantContext = localOpenPlant();
    plantCleanup = onCleanup(@() localClosePlant(plantContext));
    plantAdapter = localPlantAdapter(plantContext.model);
    plantParameters = localPlantParameters( ...
        plantContext.model, plantAdapter);
    cfg = collisionAvoidanceControllerConfig(options.controllerConfiguration);
    cfg = localControllerConfigurationForPlant( ...
        cfg, plantParameters, options.referenceSpeed);
    if ~isempty(options.targetCollisionSize)
        cfg.target.defaultLength = options.targetCollisionSize(1);
        cfg.target.defaultWidth = options.targetCollisionSize(2);
    end
    collisionAvoidanceController("resetNominalTrajectory");
    sampleTime = cfg.controller.sampleTime;
    requestedStepCount = round(options.duration / sampleTime);
    if abs(requestedStepCount * sampleTime - options.duration) ...
            > 100.0 * eps(max(1.0, options.duration))
        error("runCenterlineCruiseScenario:invalidDuration", ...
            "Duration must be an integer multiple of the controller sample time.");
    end

    initialVehicleParameters = localInitialVehicleParameters( ...
        plantContext.model, plantAdapter, cfg.referenceSpeed, ...
        options.initialPosition, options.initialYaw, ...
        options.initialLateralVelocity, options.initialYawRate);
    initialization = localPlantInitialization( ...
        plantContext.model, plantAdapter, ...
        initialVehicleParameters, sampleTime, cfg.referenceSpeed);
    plantAdapter.forceToTorqueRadius = ...
        initialization.effectiveRollingRadius;
    plantParameters = localActiveTireParameters(plantParameters, plantAdapter.tireBlock);
    cfg = localControllerConfigurationForPlant(cfg,plantParameters,options.referenceSpeed);
    % The initialized tire refresh must preserve an explicit collision
    % rectangle. Its dimensions are a scenario abstraction, distinct from
    % the physical plant's track and tire width.
    if ~isempty(options.egoCollisionSize)
        cfg.vehicle.length = options.egoCollisionSize(1);
        cfg.vehicle.width = options.egoCollisionSize(2);
    end
    cfg.roadLoad = localRoadLoadForPlant(plantParameters, ...
        initialization.effectiveRollingRadius, cfg.roadLoad);
    cfg = collisionAvoidanceControllerConfig(cfg);

    if options.initializeCruiseEquilibrium
        if ~isfield(options.geometry,"referenceCurve")
            error("runCenterlineCruiseScenario:missingReferenceCurve", ...
                "Cruise initialization requires a declared analytic reference.");
        end
        equilibrium = ltvBicycleModel.cruiseEquilibrium(options.geometry.referenceCurve.curvature,cfg);
        options.initialYaw = options.initialYaw+equilibrium(3);
        options.initialLateralVelocity = equilibrium(5);
        options.initialYawRate = equilibrium(6);
        initialVehicleParameters = localInitialVehicleParameters( ...
            plantContext.model,plantAdapter,cfg.referenceSpeed,options.initialPosition, ...
            options.initialYaw,options.initialLateralVelocity,options.initialYawRate);
        initialization.pathEquilibriumState = equilibrium;
        initialization.pathEquilibriumScope = "frozenBicycleInitialCondition";
    end

    centerline = options.centerline;
    operatingPoint = [];
    state = localEgoState( ...
        options.initialPosition(1), options.initialPosition(2), ...
        options.initialYaw, ...
        cfg.referenceSpeed, options.initialLateralVelocity, ...
        options.initialYawRate);
    estimatorContext = [];
    estimatorInitialization = struct();
    if options.useStateEstimator
        estimatorConfiguration = options.estimatorConfiguration;
        if isempty(fieldnames(estimatorConfiguration))
            estimatorConfiguration = estimatorControllerIntegrationConfig();
        end
        % The kinematic course-yaw channel uses the ego rear-axle distance,
        % so bind its estimator geometry to the same loaded plant parameter
        % used by the controller instead of retaining a nominal duplicate.
        estimatorConfiguration.observer.ego.yaw.rearAxleDistance = ...
            plantParameters.rearAxleDistance;
        % Declared planar tire-force envelope: |Iz*rDot| <= lf*|FyF|+lr*|FyR|.
        % This supplies a physical intersample premise, not a fitted noise
        % reduction. The nonlinear plant remains an independent validation.
        tireEnvelope = modifiedFialaTire.parameters(cfg);
        estimatorConfiguration.observer.ego.domain.yawAccelerationMaximum = ...
            dot([cfg.vehicle.lf;cfg.vehicle.lr],tireEnvelope.longitudinalForceScale)/cfg.vehicle.Iz;
        if isfinite(options.perceptionRange)
            estimatorConfiguration.sensor.radar.rangeMaximum = ...
                options.perceptionRange;
        end
        observerSamplePeriod = ...
            estimatorConfiguration.observer.runtime.samplePeriod;
        observerSamplesPerControl = sampleTime/observerSamplePeriod;
        sampleTimeError = abs( ...
            observerSamplesPerControl-round(observerSamplesPerControl));
        if observerSamplePeriod > sampleTime ...
                || sampleTimeError > 100.0*eps(max( ...
                    1.0, observerSamplesPerControl))
            error("runCenterlineCruiseScenario:" ...
                + "inconsistentEstimatorSampleTime", ...
                "The controller sample time must contain a whole number " ...
                + "of NRMM observer samples.");
        end
        [estimatorContext, estimatorInitialization] = ...
            nrmmEstimatorControllerAdapter( ...
                "initialize", estimatorConfiguration, state, ...
                options.targetStateFunction);
    else
        estimatorConfiguration = struct();
    end

    controlTime = NaN(requestedStepCount + 1, 1);
    controlState = NaN(requestedStepCount + 1, 6);
    controlTime(1) = 0.0;
    controlState(1, :) = localStateRow(state);
    command = cell(requestedStepCount, 1);
    targetEstimate = cell(requestedStepCount, 1);
    targetTruthAtControlSample = cell(requestedStepCount, 1);
    egoEstimate = cell(requestedStepCount, 1);
    sensorFrame = cell(requestedStepCount, 1);
    sensorAudit = cell(requestedStepCount, 1);
    roadPerception = cell(requestedStepCount, 1);
    controllerRoadAudit = cell(requestedStepCount, 1);
    targetDetectionAvailable = false(requestedStepCount, 1);
    solveTime = NaN(requestedStepCount, 1);
    controllerMetadata = cell(requestedStepCount, 1);
    attemptedStepCount = 0;
    plantTrace = localEmptyTrace();
    failure = localEmptyFailure();
    failureContext = localEmptyFailureContext();
    completedStepCount = 0;
    terminalTaskCompleted = false;
    maximumTargetCount = 0;
    controllerPreparation = struct("performed", false, "elapsedSeconds", 0.0);

    for stepIdx = 1:requestedStepCount
        attemptedStepCount = stepIdx;
        intervalStart = (stepIdx - 1) * sampleTime;
        intervalEnd = stepIdx * sampleTime;
        targetTruthAtControlSample{stepIdx} = ...
            options.targetStateFunction(intervalStart, state);
        if options.useStateEstimator
            [estimatorContext, egoEstimate{stepIdx}, ...
                targetEstimate{stepIdx}, sensorFrame{stepIdx}, ...
                sensorAudit{stepIdx}] = ...
                nrmmEstimatorControllerAdapter( ...
                    "sample", estimatorContext, intervalStart, ...
                    state, targetTruthAtControlSample{stepIdx});
            controllerState = egoEstimate{stepIdx};
        else
            controllerState = state;
            controllerState.stateTime = intervalStart;
            controllerState.perception = struct("time",intervalStart,"range",options.perceptionRange,"completeWithinRange",true);
            if stepIdx>1, controllerState.heldActuatorInput = command{stepIdx-1}.actuatorInput; end
            egoEstimate{stepIdx} = controllerState;
            targetEstimate{stepIdx} = localRangeGateTargets( ...
                targetTruthAtControlSample{stepIdx}, ...
                state.position, options.perceptionRange);
        end
        if options.useStateEstimator
            targetDetectionAvailable(stepIdx) = ...
                sensorFrame{stepIdx}.radarDetectionAvailable;
        else
            targetDetectionAvailable(stepIdx) = ...
                ~isempty(targetEstimate{stepIdx});
        end
        if isempty(options.roadBoundaryOffsets)
            % Retain route and shoulder geometry for scenario diagnostics.
            % No sensed boundary constraint is asserted in this mode.
            terminalGeometryPerceptionRange = ...
                min(options.perceptionRange, 30.0);
            roadPerception{stepIdx} = fitPerceivedRoadBoundaries( ...
                centerline, localControllerPose(controllerState), ...
                PerceptionRange=terminalGeometryPerceptionRange, ...
                RightOffset=6.0, LeftOffset=8.0, ...
                ShoulderWidth=options.roadShoulderWidth);
            controllerRoadGeometry = ...
                roadPerception{stepIdx}.roadGeometry;
            controllerRoadGeometry.boundaries = struct([]);
        else
            roadPerception{stepIdx} = fitPerceivedRoadBoundaries( ...
                centerline, localControllerPose(controllerState), ...
                PerceptionRange=options.perceptionRange, ...
                RightOffset=options.roadBoundaryOffsets(1), ...
                LeftOffset=options.roadBoundaryOffsets(2), ...
                ShoulderWidth=options.roadShoulderWidth);
            controllerRoadGeometry = ...
                roadPerception{stepIdx}.roadGeometry;
        end
        maximumTargetCount = max( ...
            maximumTargetCount, numel(targetEstimate{stepIdx}));
        if isfield(options.geometry, "referenceCurve")
            controllerRoadGeometry.referenceCurve = options.geometry.referenceCurve;
        end
        if stepIdx == 1 && options.prepareController
            controllerPreparation = prepareCollisionAvoidanceController( ...
                controllerState, controllerRoadGeometry, cfg);
        end
        solveTimer = tic;
        try
            [command{stepIdx}, ~, planningProblem] = ...
                collisionAvoidanceController( ...
                    controllerState, targetEstimate{stepIdx}, ...
                    controllerRoadGeometry, cfg);
            solveTime(stepIdx) = toc(solveTimer);
            controllerRoadAudit{stepIdx} = ...
                localControllerRoadAudit(planningProblem);
            controllerMetadata{stepIdx} = planningProblem.metadata;
        catch exception
            solveTime(stepIdx) = toc(solveTimer);
            if startsWith(string(exception.identifier), ...
                    "collisionAvoidanceController:")
                failure = localControllerFailure( ...
                    exception, stepIdx, intervalStart);
                failureContext = struct( ...
                    "controllerState", controllerState, ...
                    "targetEstimate", targetEstimate{stepIdx}, ...
                    "controllerRoadGeometry", ...
                        controllerRoadGeometry);
                break;
            end
            rethrow(exception);
        end
        if isempty(command{stepIdx})
            terminalTaskCompleted = true;
            break;
        end

        inputDataset = localPlantInputDataset( ...
            command{stepIdx}, intervalStart, intervalEnd, plantAdapter);
        in = localSimulationInput( ...
            plantContext.model, inputDataset, intervalEnd, ...
            operatingPoint, initialVehicleParameters, initialization);
        out = sim(in);
        operatingPoint = out.xFinal;
        segmentTrace = localExtractPlantTrace( ...
            out.yout, plantAdapter);
        plantTrace = localAppendTrace(plantTrace, segmentTrace);

        state = localEgoState( ...
            segmentTrace.positionX(end), ...
            segmentTrace.positionY(end), ...
            segmentTrace.yaw(end), ...
            segmentTrace.longitudinalVelocity(end), ...
            segmentTrace.lateralVelocity(end), ...
            segmentTrace.yawRate(end));
        completedStepCount = stepIdx;
        controlTime(stepIdx + 1) = intervalEnd;
        controlState(stepIdx + 1, :) = localStateRow(state);
        if options.progress
            fprintf("  step %d/%d, t = %.2f s, solve = %.3f s\n", ...
                stepIdx, requestedStepCount, intervalEnd, ...
                solveTime(stepIdx));
        end
    end

    attempts = struct( ...
        "time", (0:attemptedStepCount-1).'*sampleTime, ...
        "targetVisible", targetDetectionAvailable(1:attemptedStepCount), ...
        "solveTime", solveTime(1:attemptedStepCount), ...
        "metadata", {controllerMetadata(1:attemptedStepCount)}, ...
        "controllerEgoEstimate", {egoEstimate(1:attemptedStepCount)}, ...
        "targetEstimate", {targetEstimate(1:attemptedStepCount)}, ...
        "sensorFrame", {sensorFrame(1:attemptedStepCount)}, ...
        "measurementAudit", {sensorAudit(1:attemptedStepCount)}, ...
        "targetTruth", {targetTruthAtControlSample(1:attemptedStepCount)}, ...
        "roadPerception", {roadPerception(1:attemptedStepCount)});
    controlTime = controlTime(1:(completedStepCount + 1));
    controlState = controlState(1:(completedStepCount + 1), :);
    command = command(1:completedStepCount);
    targetEstimate = targetEstimate(1:completedStepCount);
    targetTruthAtControlSample = ...
        targetTruthAtControlSample(1:completedStepCount);
    egoEstimate = egoEstimate(1:completedStepCount);
    sensorFrame = sensorFrame(1:completedStepCount);
    sensorAudit = sensorAudit(1:completedStepCount);
    roadPerception = roadPerception(1:completedStepCount);
    controllerRoadAudit = controllerRoadAudit(1:completedStepCount);
    targetDetectionAvailable = ...
        targetDetectionAvailable(1:completedStepCount);
    solveTime = solveTime(1:completedStepCount);
    criteria = localAcceptanceCriteria(options);
    [metrics, controlTracking] = localMetrics( ...
        controlState, command, failure, ...
        completedStepCount, requestedStepCount, ...
        terminalTaskCompleted, cfg.referenceSpeed, ...
        centerline, criteria, solveTime, sampleTime);
    if isempty(plantTrace.longitudinalSlip)
        initialization.actualInitialLongitudinalSlip = NaN(4, 1);
        initialization.actualMaximumAbsoluteLongitudinalSlip = NaN;
    else
        initialization.actualInitialLongitudinalSlip = ...
            plantTrace.longitudinalSlip(1, :).';
        initialization.actualMaximumAbsoluteLongitudinalSlip = ...
            max(abs(initialization.actualInitialLongitudinalSlip));
    end

    result = struct();
    result.scenario = struct( ...
        "description", options.description, ...
        "centerline", centerline, ...
        "geometry", options.geometry, ...
        "initialState", controlState(1, :), ...
        "targetCount", maximumTargetCount, ...
        "duration", options.duration, ...
        "sampleTime", sampleTime, ...
        "targetSampleTime", sampleTime, ...
        "stateSource", localStateSource(options.useStateEstimator), ...
        "referenceSpeed", cfg.referenceSpeed);
    result.plant = struct( ...
        "model", plantContext.model, ...
        "source", "Vehicle Dynamics Blockset PassVeh14DOF", ...
        "modelFile", plantContext.modelFile, ...
        "adapter", plantAdapter, ...
        "parameters", plantParameters, ...
        "initialization", initialization);
    result.controllerConfiguration = cfg;
    result.controllerPreparation = controllerPreparation;
    result.computationalThreads = options.computationalThreads;
    result.criteria = criteria;
    result.controlTime = controlTime;
    result.controlState = controlState;
    result.controlStateOrder = [ ...
        "positionX", "positionY", "yaw", ...
        "longitudinalVelocity", "lateralVelocity", "yawRate"];
    result.controlTracking = controlTracking;
    result.command = command;
    result.targetEstimate = targetEstimate;
    result.targetTruthAtControlSample = targetTruthAtControlSample;
    result.controllerEgoEstimate = egoEstimate;
    result.solveTime = solveTime;
    result.attempts = attempts;
    result.plantTrace = plantTrace;
    result.failure = failure;
    result.failureContext = failureContext;
    result.metrics = metrics;
    if isempty(options.roadBoundaryOffsets)
        roadSafety = localDisabledRoadSafety();
        terminalBandOffsets = [6.0; 8.0];
    else
        roadSafety = evaluatePerceivedRoadBoundarySafety( ...
            plantTrace, roadPerception, sampleTime, ...
            [cfg.vehicle.length; cfg.vehicle.width]);
        terminalBandOffsets = options.roadBoundaryOffsets;
    end
    result.perception = struct( ...
        "rangeMaximum", options.perceptionRange, ...
        "targetDetectionAvailable", targetDetectionAvailable, ...
        "roadBoundaryOffsets", options.roadBoundaryOffsets, ...
        "roadShoulderWidth", options.roadShoulderWidth, ...
        "roadOuterBoundaryOffsets", ...
            options.roadBoundaryOffsets ...
                + options.roadShoulderWidth, ...
        "roadTotalWidthIncludingShoulders", ...
            sum(options.roadBoundaryOffsets) ...
                + 2.0*options.roadShoulderWidth, ...
        "shoulderWidthToVehicleWidthRatio", ...
            options.roadShoulderWidth/cfg.vehicle.width, ...
        "roadCurbCoveragePolicy", "perceptionLimited", ...
        "terminalSetGeometrySource", ...
            "nominalPathFrenetOffsetBands", ...
        "terminalLateralOffsetBands", struct( ...
            "right", [ ...
                -terminalBandOffsets(1)-options.roadShoulderWidth, ...
                -terminalBandOffsets(1)], ...
            "left", [terminalBandOffsets(2), ...
                terminalBandOffsets(2) ...
                    + options.roadShoulderWidth]), ...
        "roadBoundaryFit", {roadPerception}, ...
        "controllerRoadAudit", {controllerRoadAudit});
    result.roadSafety = roadSafety;
    result.passed = metrics.cruiseMaintained ...
        && roadSafety.noBoundaryCrossing;
    result.estimator = localEstimatorResult( ...
        options.useStateEstimator, estimatorConfiguration, ...
        estimatorInitialization, sensorFrame, sensorAudit, ...
        egoEstimate, targetEstimate, targetTruthAtControlSample, ...
        controlState);
    if options.useStateEstimator
        audits = cellfun(@(value) value.truthEnclosure,attempts.measurementAudit);
        result.estimator.truthAudit = audits;
        result.estimator.metrics.sampledEgoPremisesSatisfied = all([audits.egoPremisesSatisfied]);
        result.estimator.metrics.allPublishedBoundsContainTruth = ...
            all([audits.egoContained]) && all([audits.checkedTargetComponentsContained]);
        result.passed = result.passed ...
            && result.estimator.metrics.sampledEgoPremisesSatisfied ...
            && result.estimator.metrics.allPublishedBoundsContainTruth;
    end

    if options.report
        localReport(result);
    end
    if options.plot
        localPlot(result);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = "runCenterlineCruiseScenario";
    addParameter(parser, "Centerline", [], @localValidCenterline);
    addParameter(parser, "InitialPosition", [0.0; 0.0], ...
        @localFiniteTwoVector);
    addParameter(parser, "InitialYaw", 0.0, @localFiniteScalar);
    addParameter(parser, "InitialLateralVelocity", 0.0, ...
        @localFiniteScalar);
    addParameter(parser, "InitialYawRate", 0.0, @localFiniteScalar);
    addParameter(parser, "Description", ...
        "Centerline, constant reference speed, no targets", ...
        @localTextScalar);
    addParameter(parser, "Geometry", struct(), @localScalarStruct);
    addParameter(parser, "Duration", 4.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "TargetStateFunction", ...
        @(time, egoState) struct([]), @localFunctionHandle);
    addParameter(parser, "UseStateEstimator", false, ...
        @localLogicalScalar);
    addParameter(parser, "EstimatorConfiguration", struct(), ...
        @localScalarStruct);
    addParameter(parser, "ControllerConfiguration", struct(), ...
        @localScalarStruct);
    addParameter(parser, "PerceptionRange", Inf, ...
        @localPositiveOrInfScalar);
    addParameter(parser, "RoadBoundaryOffsets", [], ...
        @localEmptyOrPositiveTwoVector);
    addParameter(parser, "RoadShoulderWidth", 2.6, ...
        @localPositiveScalar);
    addParameter(parser, "EgoCollisionSize", [], ...
        @localEmptyOrPositiveTwoVector);
    addParameter(parser, "TargetCollisionSize", [], ...
        @localEmptyOrPositiveTwoVector);
    addParameter(parser, "SpeedTolerance", 0.5, @localPositiveScalar);
    addParameter(parser, "LateralTolerance", 0.2, @localPositiveScalar);
    addParameter(parser, "HeadingTolerance", 0.02, @localPositiveScalar);
    addParameter(parser, "Plot", false, @localLogicalScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", false, @localLogicalScalar);
    addParameter(parser,"InitializeCruiseEquilibrium",false,@localLogicalScalar);
    addParameter(parser, "PrepareController", true, @localLogicalScalar);
    addParameter(parser, "ComputationalThreads", 1, ...
        @(value) localPositiveScalar(value) && value == fix(value));
    parse(parser, varargin{:});
    if isempty(parser.Results.Centerline)
        error("runCenterlineCruiseScenario:missingCenterline", ...
            "Centerline must be supplied.");
    end

    options = struct();
    options.centerline = double(parser.Results.Centerline);
    options.initialPosition = ...
        double(parser.Results.InitialPosition(:));
    options.initialYaw = double(parser.Results.InitialYaw);
    options.initialLateralVelocity = ...
        double(parser.Results.InitialLateralVelocity);
    options.initialYawRate = double(parser.Results.InitialYawRate);
    options.description = string(parser.Results.Description);
    options.geometry = parser.Results.Geometry;
    options.duration = double(parser.Results.Duration);
    options.referenceSpeed = double(parser.Results.ReferenceSpeed);
    options.targetStateFunction = parser.Results.TargetStateFunction;
    options.useStateEstimator = ...
        logical(parser.Results.UseStateEstimator);
    options.estimatorConfiguration = ...
        parser.Results.EstimatorConfiguration;
    options.controllerConfiguration = parser.Results.ControllerConfiguration;
    options.prepareController = parser.Results.PrepareController;
    options.computationalThreads = parser.Results.ComputationalThreads;
    options.perceptionRange = ...
        double(parser.Results.PerceptionRange);
    options.roadBoundaryOffsets = ...
        double(parser.Results.RoadBoundaryOffsets(:));
    options.roadShoulderWidth = ...
        double(parser.Results.RoadShoulderWidth);
    options.egoCollisionSize = ...
        double(parser.Results.EgoCollisionSize(:));
    options.targetCollisionSize = ...
        double(parser.Results.TargetCollisionSize(:));
    options.speedTolerance = double(parser.Results.SpeedTolerance);
    options.lateralTolerance = double(parser.Results.LateralTolerance);
    options.headingTolerance = double(parser.Results.HeadingTolerance);
    options.plot = logical(parser.Results.Plot);
    options.report = logical(parser.Results.Report);
    options.progress = logical(parser.Results.Progress);
    options.initializeCruiseEquilibrium = logical(parser.Results.InitializeCruiseEquilibrium);
end

function valid = localValidCenterline(value)
    valid = isempty(value) || ( ...
        isnumeric(value) && isreal(value) && ismatrix(value) ...
        && size(value, 2) == 2 && size(value, 1) >= 2 ...
        && all(isfinite(value), "all") ...
        && all(vecnorm(diff(double(value), 1, 1), 2, 2) > 0.0));
end

function valid = localFiniteTwoVector(value)
    valid = isnumeric(value) && isreal(value) ...
        && numel(value) == 2 && all(isfinite(value), "all");
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localTextScalar(value)
    valid = (ischar(value) || (isstring(value) && isscalar(value))) ...
        && strlength(string(value)) > 0;
end

function valid = localScalarStruct(value)
    valid = isstruct(value) && isscalar(value);
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localPositiveOrInfScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && ~isnan(value) && value > 0.0;
end

function valid = localEmptyOrPositiveTwoVector(value)
    valid = isempty(value) || ( ...
        isnumeric(value) && isreal(value) && numel(value) == 2 ...
        && all(isfinite(value), "all") ...
        && all(value > 0.0, "all"));
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localFunctionHandle(value)
    valid = isa(value, "function_handle");
end

function pose = localControllerPose(state)
    if isfield(state, "egoState")
        pose = [ ...
            state.egoState(1); state.egoState(5); state.egoYaw];
    else
        pose = [state.position(:); state.yawAngle];
    end
end

function perceived = localRangeGateTargets( ...
        target, egoPosition, perceptionRange)
    if isempty(target) || ~isfinite(perceptionRange)
        perceived = target;
        return;
    end
    keep = false(size(target));
    for targetIdx = 1:numel(target)
        relativePosition = ...
            target(targetIdx).targetPositionInertial(:) ...
            - egoPosition(:);
        tolerance = 100.0 * eps(max(1.0, perceptionRange));
        keep(targetIdx) = norm(relativePosition) ...
            <= perceptionRange + tolerance;
    end
    perceived = target(keep);
end

function audit = localControllerRoadAudit(problem)
    % Report the retained swept road rows of the finite certificate.
    if isempty(problem)
        audit = struct( ...
            "boundaryCount", 0, ...
            "candidateSafetyRowCount", 0, ...
            "retainedQpRowCount", 0);
        return;
    end
    audit = struct( ...
        "boundaryCount", numel(problem.model.road.boundaries), ...
        "candidateSafetyRowCount", ...
            nnz(startsWith(problem.qp.geometry.label, "road:")), ...
        "retainedQpRowCount", ...
            nnz(startsWith(problem.qp.geometry.label, "road:")));
end

function safety = localDisabledRoadSafety()
    safety = struct( ...
        "boundaryIds", strings(1, 0), ...
        "controlStep", zeros(0, 1), ...
        "fittedBoundaryFunctionMargin", zeros(0, 0), ...
        "conservativeBoundaryFunctionMargin", zeros(0, 0), ...
        "sourceDomainCovered", true(0, 0), ...
        "allRectanglesCoveredByPerceivedSegments", true, ...
        "minimumBoundaryFunctionMargin", Inf, ...
        "minimumBoundaryFunctionMarginByBoundary", zeros(1, 0), ...
        "noBoundaryCrossing", true, ...
        "contactTolerance", 0.0, ...
        "method", "road-boundary perception disabled");
end

function source = localStateSource(useStateEstimator)
    if useStateEstimator
        source = "onlineNrmmTrackingRuntime";
    else
        source = "plant and target truth";
    end
end

function estimator = localEstimatorResult( ...
        enabled, cfg, initialization, sensorFrame, sensorAudit, ...
        egoEstimate, targetEstimate, targetTruth, controlState)
    if ~enabled
        estimator = struct("enabled", false);
        return;
    end

    sampleCount = numel(egoEstimate);
    egoPositionError = NaN(sampleCount, 2);
    egoVelocityError = NaN(sampleCount, 2);
    egoYawError = NaN(sampleCount, 1);
    targetPositionError = NaN(sampleCount, 2);
    targetVelocityError = NaN(sampleCount, 2);
    estimatesFinite = true;
    inputsFromEstimator = true;
    expectedSensorFields = sort([ ...
        "time"; "xGps"; "yGps"; "vxGps"; "vyGps"; ...
        "longitudinalAcceleration"; "lateralAcceleration"; ...
        "yawRateMeasured"; "radarRelativePosition"; ...
        "radarDetectionAvailable"]);
    sensorContractValid = true;
    detectionWithinRange = true;
    detectionOccurred = false;
    maximumDetectedRange = -Inf;
    targetEstimateAvailable = false(sampleCount, 1);
    targetPublicationWithinRadarVisibility = true;
    targetAcquisitionTime = NaN;

    for sampleIdx = 1:sampleCount
        output = egoEstimate{sampleIdx};
        truthState = controlState(sampleIdx, :);
        estimatedPosition = output.egoState([1, 4]).';
        estimatedVelocity = output.egoState([2, 5]).';
        truthRotation = [ ...
            cos(truthState(3)), -sin(truthState(3)); ...
            sin(truthState(3)), cos(truthState(3))];
        truthVelocity = ...
            (truthRotation*truthState(4:5).').';
        egoPositionError(sampleIdx, :) = ...
            estimatedPosition-truthState(1:2);
        egoVelocityError(sampleIdx, :) = ...
            estimatedVelocity-truthVelocity;
        egoYawError(sampleIdx) = localWrapAngle( ...
            output.egoYaw-truthState(3));

        estimate = targetEstimate{sampleIdx};
        truth = targetTruth{sampleIdx};
        audit = sensorAudit{sampleIdx};
        estimatesFinite = estimatesFinite ...
            && all(isfinite(output.egoState), "all") ...
            && isfinite(output.egoYaw);
        if isempty(estimate)
            inputsFromEstimator = inputsFromEstimator ...
                && isfield(output, "targetEstimates") ...
                && isempty(output.targetEstimates);
        else
            targetEstimateAvailable(sampleIdx) = true;
            targetPublicationWithinRadarVisibility = ...
                targetPublicationWithinRadarVisibility ...
                && audit.radarDetectionAvailable;
            targetPositionError(sampleIdx, :) = ...
                (estimate.targetPositionInertial ...
                    - truth.targetPositionInertial).';
            targetVelocityError(sampleIdx, :) = ...
                (estimate.targetVelocityInertial ...
                    - truth.targetVelocityInertial).';
            estimatesFinite = estimatesFinite ...
                && all(isfinite( ...
                    estimate.targetPositionInertial), "all") ...
                && all(isfinite( ...
                    estimate.targetVelocityInertial), "all");
            inputsFromEstimator = inputsFromEstimator ...
                && isfield(output, "targetEstimates") ...
                && isfield(estimate, "trackId") ...
                && string(estimate.trackId) ...
                    == "synthetic-radar-track-1";
            if isnan(targetAcquisitionTime) ...
                    && isfield(output, "targetAcquisitionTime")
                targetAcquisitionTime = ...
                    output.targetAcquisitionTime;
            end
        end

        fields = sort(string(fieldnames(sensorFrame{sampleIdx})));
        sensorContractValid = sensorContractValid ...
            && isequal(fields, expectedSensorFields) ...
            && audit.sampledSensorNoiseWithinBounds;
        if audit.radarDetectionAvailable
            detectionOccurred = true;
            maximumDetectedRange = max( ...
                maximumDetectedRange, audit.targetRange);
            detectionWithinRange = detectionWithinRange ...
                && audit.targetRange ...
                    <= audit.radarRangeMaximum ...
                        + 100.0*eps(max( ...
                            1.0, audit.radarRangeMaximum));
        else
            detectionWithinRange = detectionWithinRange ...
                && all(isnan( ...
                    sensorFrame{sampleIdx}.radarRelativePosition));
        end
    end
    if ~detectionOccurred
        maximumDetectedRange = NaN;
    end

    metrics = struct( ...
        "egoPositionRmse", localVectorRmse(egoPositionError), ...
        "egoVelocityRmse", localVectorRmse(egoVelocityError), ...
        "egoYawRmse", sqrt(mean(egoYawError.^2)), ...
        "targetPositionRmse", ...
            localVectorRmse(targetPositionError), ...
        "targetVelocityRmse", ...
            localVectorRmse(targetVelocityError), ...
        "egoPositionErrorMaximum", ...
            localVectorMaximum(egoPositionError), ...
        "egoVelocityErrorMaximum", ...
            localVectorMaximum(egoVelocityError), ...
        "egoYawErrorMaximum", max(abs(egoYawError), [], "omitnan"), ...
        "targetPositionErrorMaximum", ...
            localVectorMaximum(targetPositionError), ...
        "targetVelocityErrorMaximum", ...
            localVectorMaximum(targetVelocityError), ...
        "allEstimatesFinite", estimatesFinite, ...
        "controllerInputsFromEstimator", inputsFromEstimator, ...
        "sensorContractValid", sensorContractValid, ...
        "radarDetectionOccurred", detectionOccurred, ...
        "allRadarDetectionsWithinRange", detectionWithinRange, ...
        "maximumDetectedTargetRange", maximumDetectedRange, ...
        "targetAcquisitionOccurred", ...
            any(targetEstimateAvailable), ...
        "targetPublicationWithinRadarVisibility", ...
            targetPublicationWithinRadarVisibility, ...
        "targetAcquisitionTime", targetAcquisitionTime, ...
        "targetEstimateSampleCount", ...
            nnz(targetEstimateAvailable));
    estimator = struct( ...
        "enabled", true, ...
        "configuration", cfg, ...
        "observerDesign", initialization.observerDesign, ...
        "initialization", initialization, ...
        "sensorFrame", {sensorFrame}, ...
        "measurementAudit", {sensorAudit}, ...
        "metrics", metrics);
end

function value = localVectorMaximum(errorValue)
% Largest Euclidean error norm over the run.
%
% A robust constraint margin is driven by the worst sample the estimator
% produced, not by its root-mean-square behaviour, so the maxima are
% reported next to the RMSE figures rather than in place of them.

    finiteRow = all(isfinite(errorValue), 2);
    if ~any(finiteRow)
        value = NaN;
    else
        value = max(sqrt(sum(errorValue(finiteRow, :).^2, 2)));
    end
end

function value = localVectorRmse(errorValue)
    finiteRow = all(isfinite(errorValue), 2);
    if ~any(finiteRow)
        value = NaN;
    else
        value = sqrt(mean(sum(errorValue(finiteRow, :).^2, 2)));
    end
end

function angle = localWrapAngle(angle)
    angle = mod(angle+pi, 2.0*pi)-pi;
end

function context = localOpenPlant()
    model = "PassVeh14DOF";
    context = struct( ...
        "model", model, ...
        "modelFile", "", ...
        "createdProject", false, ...
        "project", [], ...
        "temporaryFolder", "", ...
        "originalFolder", string(pwd));

    if bdIsLoaded(model)
        context.modelFile = string(get_param(model, "FileName"));
        return;
    end

    templateFile = which("PassVeh14DOF.sltx");
    if isempty(templateFile)
        error("runCenterlineCruiseScenario:missingPlant", ...
            ["The PassVeh14DOF Vehicle Dynamics Blockset template " ...
            "is not installed or is not on the MATLAB path."]);
    end

    context.temporaryFolder = string(tempname);
    mkdir(context.temporaryFolder);
    try
        context.project = Simulink.createFromTemplate( ...
            templateFile, ...
            Folder=context.temporaryFolder, ...
            Name="CenterlineCruisePlant");
        modelFiles = dir(fullfile( ...
            context.temporaryFolder, "**", model + ".slx"));
        if numel(modelFiles) ~= 1
            error("runCenterlineCruiseScenario:missingPlant", ...
                "The template did not create exactly one PassVeh14DOF model.");
        end
        context.modelFile = string(fullfile( ...
            modelFiles(1).folder, modelFiles(1).name));
        load_system(context.modelFile);
        context.createdProject = true;
    catch exception
        localClosePlant(context);
        rethrow(exception);
    end
end

function localClosePlant(context)
    if bdIsLoaded(context.model)
        % Release compiled resources before closing the template project.
        set_param(context.model, FastRestart="off");
    end
    if context.createdProject && bdIsLoaded(context.model)
        close_system(context.model, 0);
    end
    if context.createdProject && ~isempty(context.project)
        try
            close(context.project);
        catch
        end
    end
    if isfolder(context.originalFolder)
        cd(context.originalFolder);
    end
    if context.createdProject && isfolder(context.temporaryFolder)
        try
            rmdir(context.temporaryFolder, "s");
        catch
        end
    end
end

function adapter = localPlantAdapter(model)
    modelWorkspace = get_param(model, "ModelWorkspace");
    staticLoadedRadius = double( ...
        modelWorkspace.getVariable("StatLdWhlR"));
    staticLoadedRadius = staticLoadedRadius(:);
    if numel(staticLoadedRadius) ~= 4 ...
            || any(~isfinite(staticLoadedRadius)) ...
            || any(staticLoadedRadius <= 0.0)
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "PassVeh14DOF must define four positive static wheel radii.");
    end

    tireBlock = model + ...
        "/Wheels and Tires/VDBS/Tires/MF Tires Vector/" + ...
        "Combined Slip Wheel 2DOF";
    diskBore = localMaskScalar(tireBlock, "disk_abore");
    padCount = localMaskScalar(tireBlock, "num_pads");
    effectiveBrakeRadius = localMaskScalar(tireBlock, "Rm");
    kineticFriction = localMaskScalar(tireBlock, "mu_kinetic");
    brakeTorquePerPressure = (pi / 4.0) * diskBore^2 ...
        * padCount * effectiveBrakeRadius * kineticFriction;
    if ~isfinite(brakeTorquePerPressure) ...
            || brakeTorquePerPressure <= 0.0
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "The PassVeh14DOF disk-brake parameters are invalid.");
    end

    adapter = struct();
    adapter.wheelOrder = ["FL", "FR", "RL", "RR"];
    adapter.staticLoadedRadius = staticLoadedRadius;
    adapter.brakeTorquePerPressure = brakeTorquePerPressure;
    adapter.brakePressureUnit = "Pa";
    adapter.axleTorqueUnit = "N*m";
    adapter.wheelAngleUnit = "rad";
    adapter.tireBlock = tireBlock;
    adapter.controllerCoordinateConvention = "xForwardYLeftZUp";
    adapter.plantCoordinateConvention = "saeXForwardYRightZDown";
    adapter.lateralStateSign = -1.0;
    adapter.yawStateSign = -1.0;
    adapter.steeringAngleSign = -1.0;
    adapter.forceToTorqueRadius = staticLoadedRadius;
end

function parameters = localPlantParameters(model, adapter)
    modelWorkspace = get_param(model, "ModelWorkspace");
    vehicle = modelWorkspace.getVariable("VEH");
    bodyBlock = model + "/Vehicle/Vehicle Body 6DOF";

    gravity = localMaskScalar(bodyBlock, "g");
    nominalVerticalLoad = localMaskScalar( ...
        adapter.tireBlock, "FNOMIN");
    lateralStiffnessFactor = localMaskScalar( ...
        adapter.tireBlock, "PKY1");
    lateralStiffnessShape = localMaskScalar( ...
        adapter.tireBlock, "PKY2");
    peakFriction = localMaskScalar(adapter.tireBlock, "PDY1");
    loadFrictionSlope = localMaskScalar(adapter.tireBlock, "PDY2");
    tireWidth = localMaskScalar(adapter.tireBlock, "WIDTH");

    staticNormalLoad = gravity * [ ...
        vehicle.StaticNormalFrontLoad.FL; ...
        vehicle.StaticNormalFrontLoad.FR; ...
        vehicle.StaticNormalRearLoad.RL; ...
        vehicle.StaticNormalRearLoad.RR];
    corneringStiffness = abs( ...
        lateralStiffnessFactor * nominalVerticalLoad ...
        .* sin(2.0 * atan(staticNormalLoad ...
        / (lateralStiffnessShape * nominalVerticalLoad))));
    relativeLoad = ...
        (staticNormalLoad - nominalVerticalLoad) / nominalVerticalLoad;
    frictionCoefficient = ...
        peakFriction + loadFrictionSlope * relativeLoad;

    parameters = struct();
    parameters.mass = double(vehicle.Mass);
    parameters.yawInertia = double(vehicle.YawMomentInertia);
    parameters.frontAxleDistance = ...
        double(vehicle.FrontAxlePositionfromCG);
    parameters.rearAxleDistance = ...
        double(vehicle.RearAxlePositionfromCG);
    parameters.wheelbase = double(vehicle.WheelBase);
    parameters.trackWidth = double(vehicle.TrackWidth);
    parameters.cgHeight = double(vehicle.HeightCG);
    parameters.gravity = gravity;
    parameters.frontalArea = double(vehicle.FrontalArea);
    parameters.dragCoefficient = localMaskScalar(bodyBlock, "Cd");
    parameters.airDensity = localMaskScalar(bodyBlock, "Pabs") ...
        /(287.058*localMaskScalar(bodyBlock, "Tair"));
    parameters.rollingNominalLoad = nominalVerticalLoad;
    parameters.rollingNominalSpeed = localMaskScalar(adapter.tireBlock, "LONGVL");
    parameters.rollingUnloadedRadius = localMaskScalar(adapter.tireBlock, "UNLOADED_RADIUS");
    parameters.rollingNominalPressure = localMaskScalar(adapter.tireBlock, "NOMPRES");
    parameters.rollingPressure = localMaskScalar( ...
        model+"/Wheels and Tires/VDBS/Pressure", "const");
    parameters.rollingCoefficients = arrayfun(@(index) localMaskScalar( ...
        adapter.tireBlock, "QSY"+index), (1:8).');
    parameters.tireWidth = tireWidth;
    parameters.staticNormalLoad = staticNormalLoad;
    parameters.corneringStiffness = corneringStiffness;
    parameters.frictionCoefficient = frictionCoefficient;
end

function roadLoad = localRoadLoadForPlant(parameters, rollingRadius, roadLoad)
% Static-load, zero-camber reduction of the plant's Magic Formula moment.
% Convert each wheel's rolling moment to an equivalent force with the
% initialized effective radius. Dynamic loads, slip, and axle losses remain
% model residuals. No fitted constant acceleration bias is introduced.
    coefficients = parameters.rollingCoefficients;
    if any(coefficients([2, 5, 6]) ~= 0.0)
        error("runCenterlineCruiseScenario:unsupportedRoadLoad", ...
            "The reduced rolling model requires QSY2, QSY5, and QSY6 to be zero.");
    end
    forceScale = sum(parameters.rollingUnloadedRadius./rollingRadius ...
        * parameters.rollingNominalLoad ...
        .* (parameters.staticNormalLoad/parameters.rollingNominalLoad).^coefficients(7)) ...
        * (parameters.rollingPressure/parameters.rollingNominalPressure)^coefficients(8);
    coefficientScale = forceScale/(parameters.mass*parameters.gravity);
    roadLoad.airDensity = parameters.airDensity;
    roadLoad.dragCoefficient = parameters.dragCoefficient;
    roadLoad.frontalArea = parameters.frontalArea;
    roadLoad.rollingCoefficient = coefficientScale*coefficients(1);
    roadLoad.rollingSpeedCoefficient = coefficientScale*coefficients(3) ...
        /parameters.rollingNominalSpeed;
    roadLoad.rollingQuarticCoefficient = coefficientScale*coefficients(4) ...
        /parameters.rollingNominalSpeed^4;
end

function parameters = localActiveTireParameters(parameters, tireBlock)
% The built-in tire preset overrides inactive values retained in the mask.
% Read its initialized MF62 parameter vector, not the external-file settings.
% This adapter is deliberately tied to the verified R2026a template layout.
    variables = get_param(tireBlock, "MaskWSVariables");
    index = find(strcmp({variables.Name}, "vdynMF"), 1);
    if isempty(index) || ~strcmp(version("-release"), "2026a") ...
            || string(get_param(tireBlock, "tireType")) ~= "Mid-size passenger car 235/45R18"
        error("runCenterlineCruiseScenario:unsupportedRoadLoad", ...
            "The active tire-preset parameter layout must be verified for this template.");
    end
    values = variables(index).Value(:);
    if numel(values) ~= 279 || values(12) ~= 62 || values(4) ~= 0 ...
            || any(~isfinite(values([14, 24, 30, 38, 177:178,185:186,188,218:225]))) ...
            || any(values([14, 24, 30, 38]) <= 0)
        error("runCenterlineCruiseScenario:unsupportedRoadLoad", ...
            "The initialized built-in MF62 vector does not match the verified layout.");
    end
    parameters.rollingParameterSource = "R2026a initialized built-in MF62 preset";
    parameters.rollingInactiveMaskCoefficients = parameters.rollingCoefficients;
    parameters.rollingNominalSpeed = values(14);
    parameters.rollingUnloadedRadius = values(24);
    parameters.rollingNominalPressure = values(30);
    parameters.rollingNominalLoad = values(38);
    parameters.rollingCoefficients = values(218:225);
    % The built-in preset also overrides the inactive lateral-force mask
    % coefficients. The R2026a MF62 zero-camber, zero-slip derivative uses
    % PKY1, PKY2 and PKY4 from this same initialized vector. Its preset mode
    % uses nominal pressure; this reduction is checked against the active
    % MathWorks tire evaluator, not against the inactive dialog values.
    parameters.lateralParameterSource = parameters.rollingParameterSource;
    parameters.lateralInactiveCorneringStiffness = parameters.corneringStiffness;
    parameters.lateralInactiveFrictionCoefficient = parameters.frictionCoefficient;
    nominalLoad = values(38);
    loadRatio = parameters.staticNormalLoad/nominalLoad;
    parameters.corneringStiffness = abs(values(185)*nominalLoad ...
        .*sin(values(188)*atan(loadRatio/values(186))));
    parameters.frictionCoefficient = values(177)+values(178)*(loadRatio-1);
    parameters.lateralPresetCoefficients = values([177,178,185,186,188]);
    if any(parameters.corneringStiffness<=0) || any(parameters.frictionCoefficient<=0)
        error("runCenterlineCruiseScenario:unsupportedTirePreset","The active lateral tire parameters are invalid.");
    end
end

function cfg = localControllerConfigurationForPlant( ...
        cfg, parameters, referenceSpeed)
    cfg.referenceSpeed = referenceSpeed;
    cfg.vehicle.m = parameters.mass;
    cfg.vehicle.Iz = parameters.yawInertia;
    cfg.vehicle.lf = parameters.frontAxleDistance;
    cfg.vehicle.lr = parameters.rearAxleDistance;
    cfg.vehicle.wheelbase = parameters.wheelbase;
    cfg.vehicle.centerOfGravityHeight = parameters.cgHeight;
    cfg.vehicle.gravity = parameters.gravity;
    cfg.vehicle.width = max( ...
        cfg.vehicle.width, parameters.trackWidth + parameters.tireWidth);
    cfg.tire.corneringStiffness = [ ...
        sum(parameters.corneringStiffness(1:2)); ...
        sum(parameters.corneringStiffness(3:4))];
    frontNormalLoad = sum(parameters.staticNormalLoad(1:2));
    rearNormalLoad = sum(parameters.staticNormalLoad(3:4));
    cfg.tire.frictionCoefficient = [ ...
        dot(parameters.frictionCoefficient(1:2), ...
            parameters.staticNormalLoad(1:2)) / frontNormalLoad; ...
        dot(parameters.frictionCoefficient(3:4), ...
            parameters.staticNormalLoad(3:4)) / rearNormalLoad];
    % Residual rates come only from the supplied controller configuration.
    % Reading physical parameters does not certify that residual allowance.
end

function initialization = localPlantInitialization( ...
        model, adapter, vehicleParameters, sampleTime, referenceSpeed)
    zeroCommand = struct( ...
        "frontWheelSteeringAngle", 0.0, ...
        "axleLongitudinalForce", zeros(2, 1));
    previewDataset = localPlantInputDataset( ...
        zeroCommand, 0.0, sampleTime, adapter);
    previewInput = Simulink.SimulationInput(model);
    previewInput = previewInput.setExternalInput(previewDataset);
    previewInput = previewInput.setVariable( ...
        "VEH", vehicleParameters, Workspace=model);
    previewInput = previewInput.setModelParameter( ...
        StartTime="0", ...
        StopTime="0", ...
        SaveOutput="on", ...
        OutputSaveName="yout", ...
        SaveFormat="Dataset", ...
        ReturnWorkspaceOutputs="on");
    previewOutput = sim(previewInput);
    wheelElement = previewOutput.yout.getElement("Wheels");
    rollingRadius = double( ...
        wheelElement.Values.TireFrame.Re.Data(end, :)).';
    if numel(rollingRadius) ~= 4 ...
            || any(~isfinite(rollingRadius)) ...
            || any(rollingRadius <= 0.0)
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "PassVeh14DOF did not return four positive loaded rolling radii.");
    end

    maskWheelAngularSpeed = referenceSpeed / mean(rollingRadius);
    initialWheelAngularSpeed = ...
        maskWheelAngularSpeed * ones(4, 1);
    longitudinalSlip = ...
        (initialWheelAngularSpeed .* rollingRadius - referenceSpeed) ...
        / max(referenceSpeed, eps);

    initialization = struct();
    initialization.method = ...
        "zeroTimeLoadedRollingRadiusAndMatchedWheelSpeed";
    initialization.tireBlock = adapter.tireBlock;
    initialization.effectiveRollingRadius = rollingRadius;
    initialization.maskWheelAngularSpeed = maskWheelAngularSpeed;
    initialization.initialWheelAngularSpeed = ...
        initialWheelAngularSpeed;
    initialization.longitudinalSlip = longitudinalSlip;
    initialization.maximumAbsoluteLongitudinalSlip = ...
        max(abs(longitudinalSlip));
end

function value = localMaskScalar(block, parameterName)
    parameterNames = string(get_param(block, "MaskNames"));
    parameterValues = string(get_param(block, "MaskValues"));
    parameterIdx = find(parameterNames == parameterName, 1);
    if isempty(parameterIdx)
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "PassVeh14DOF is missing mask parameter '%s'.", ...
            parameterName);
    end
    value = str2double(parameterValues(parameterIdx));
    if ~isscalar(value) || ~isfinite(value)
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "PassVeh14DOF mask parameter '%s' is not a finite scalar.", ...
            parameterName);
    end
end

function vehicleParameters = localInitialVehicleParameters( ...
        model, adapter, referenceSpeed, initialPosition, initialYaw, ...
        initialLateralVelocity, initialYawRate)
    modelWorkspace = get_param(model, "ModelWorkspace");
    vehicleParameters = modelWorkspace.getVariable("VEH");
    vehicleParameters.InitialLongPosition = initialPosition(1);
    vehicleParameters.InitialLatPosition = ...
        adapter.lateralStateSign * initialPosition(2);
    vehicleParameters.InitialYawAngle = ...
        adapter.yawStateSign * initialYaw;
    vehicleParameters.InitialLongVel = referenceSpeed;
    vehicleParameters.InitialLatVel = ...
        adapter.lateralStateSign * initialLateralVelocity;
    vehicleParameters.InitialYawRate = ...
        adapter.yawStateSign * initialYawRate;
end

function dataset = localPlantInputDataset( ...
        command, intervalStart, intervalEnd, adapter)
    time = [intervalStart; intervalEnd];
    wheelAngle = [ ...
        adapter.steeringAngleSign ...
            * command.frontWheelSteeringAngle * ones(2, 1); ...
        0.0; 0.0];
    % command.axleLongitudinalForce = beta*[mu_f*Fzf; mu_r*Fzr].
    % Apply the common signed ratio to both axles through drive/brake torque.
    wheelForce = 0.5*command.axleLongitudinalForce([1; 1; 2; 2]);
    axleTorque = max(wheelForce, 0.0) ...
        .* adapter.forceToTorqueRadius;
    brakeTorque = max(-wheelForce, 0.0) ...
        .* adapter.forceToTorqueRadius;
    brakePressure = brakeTorque ...
        / adapter.brakeTorquePerPressure;

    directionCosineMatrix = zeros(3, 3, 4, 2);
    for sampleIdx = 1:2
        for wheelIdx = 1:4
            directionCosineMatrix(:, :, wheelIdx, sampleIdx) = eye(3);
        end
    end

    portNames = [ ...
        "WhlAng", "AxlTrq", "BrkPrs", "WindXYZ", ...
        "Ground", "Friction", "DCM"];
    portData = { ...
        repmat(wheelAngle.', 2, 1), ...
        repmat(axleTorque.', 2, 1), ...
        repmat(brakePressure.', 2, 1), ...
        zeros(2, 3), ...
        zeros(2, 4), ...
        ones(2, 4), ...
        directionCosineMatrix};

    dataset = Simulink.SimulationData.Dataset;
    for portIdx = 1:numel(portNames)
        signal = Simulink.SimulationData.Signal;
        signal.Name = portNames(portIdx);
        signal.Values = timeseries(portData{portIdx}, time);
        dataset = dataset.addElement(signal, portNames(portIdx));
    end
end

function in = localSimulationInput( ...
        model, inputDataset, intervalEnd, ...
        operatingPoint, initialVehicleParameters, initialization)
    in = Simulink.SimulationInput(model);
    in = in.setExternalInput(inputDataset);
    in = in.setBlockParameter( ...
        initialization.tireBlock, "omegao", ...
        sprintf("%.17g", initialization.maskWheelAngularSpeed));
    in = in.setVariable( ...
        "VEH", initialVehicleParameters, Workspace=model);
    if ~isempty(operatingPoint)
        in = in.setInitialState(operatingPoint);
    end
    in = in.setModelParameter( ...
        FastRestart="on", ...
        StartTime="0", ...
        StopTime=string(intervalEnd), ...
        SaveOutput="on", ...
        OutputSaveName="yout", ...
        SaveFormat="Dataset", ...
        ReturnWorkspaceOutputs="on", ...
        SaveFinalState="on", ...
        FinalStateName="xFinal", ...
        SaveOperatingPoint="on");
end

function trace = localExtractPlantTrace(outputDataset, adapter)
    vehicleElement = outputDataset.getElement("Veh");
    vehicle = vehicleElement.Values;
    wheelElement = outputDataset.getElement("Wheels");
    wheel = wheelElement.Values.TireFrame;
    trace = struct();
    trace.time = vehicle.BdyFrm.Cg.Vel.xdot.Time(:);
    trace.positionX = vehicle.InertFrm.Cg.Disp.X.Data(:);
    trace.positionY = adapter.lateralStateSign ...
        * vehicle.InertFrm.Cg.Disp.Y.Data(:);
    trace.yaw = adapter.yawStateSign ...
        * vehicle.InertFrm.Cg.Ang.psi.Data(:);
    trace.longitudinalVelocity = ...
        vehicle.BdyFrm.Cg.Vel.xdot.Data(:);
    trace.lateralVelocity = adapter.lateralStateSign ...
        * vehicle.BdyFrm.Cg.Vel.ydot.Data(:);
    trace.yawRate = adapter.yawStateSign ...
        * vehicle.BdyFrm.Cg.AngVel.r.Data(:);
    trace.bodyAerodynamicForceX = vehicle.BdyFrm.Forces.Drag.Fx.Data(:);
    trace.bodyGravityForceX = vehicle.BdyFrm.Forces.Grvty.Fx.Data(:);
    trace.bodyNetForceX = vehicle.BdyFrm.Forces.Body.Fx.Data(:);
    trace.bodyPitch = vehicle.InertFrm.Cg.Ang.theta.Data(:);
    sampleCount = numel(trace.time);
    trace.wheelAngularSpeed = localWheelTimeRows( ...
        wheel.Omega.Data, sampleCount, "wheel angular speed");
    trace.effectiveRollingRadius = localWheelTimeRows( ...
        wheel.Re.Data, sampleCount, "effective rolling radius");
    trace.longitudinalSlip = localWheelTimeRows( ...
        wheel.Kappa.Data, sampleCount, "longitudinal slip");
    trace.wheelLongitudinalForce = localWheelTimeRows( ...
        wheel.Fx.Data, sampleCount, "longitudinal tire force");
    trace.wheelRollingMoment = localWheelTimeRows( ...
        wheel.My.Data, sampleCount, "rolling resistance moment");
    trace.wheelNormalLoad = localWheelTimeRows( ...
        wheel.Fz.Data, sampleCount, "normal tire load");
end

function values = localWheelTimeRows(data, sampleCount, signalName)
    values = reshape(double(data), sampleCount, []);
    if size(values, 2) ~= 4 || any(~isfinite(values), "all")
        error("runCenterlineCruiseScenario:invalidPlant", ...
            "PassVeh14DOF %s must contain four finite wheel channels.", ...
            signalName);
    end
end

function trace = localEmptyTrace()
    trace = struct( ...
        "time", zeros(0, 1), ...
        "positionX", zeros(0, 1), ...
        "positionY", zeros(0, 1), ...
        "yaw", zeros(0, 1), ...
        "longitudinalVelocity", zeros(0, 1), ...
        "lateralVelocity", zeros(0, 1), ...
        "yawRate", zeros(0, 1), ...
        "bodyAerodynamicForceX", zeros(0, 1), ...
        "bodyGravityForceX", zeros(0, 1), ...
        "bodyNetForceX", zeros(0, 1), ...
        "bodyPitch", zeros(0, 1), ...
        "wheelAngularSpeed", zeros(0, 4), ...
        "effectiveRollingRadius", zeros(0, 4), ...
        "longitudinalSlip", zeros(0, 4), ...
        "wheelLongitudinalForce", zeros(0, 4), ...
        "wheelRollingMoment", zeros(0, 4), ...
        "wheelNormalLoad", zeros(0, 4));
end

function combined = localAppendTrace(combined, segment)
    if isempty(combined.time)
        firstSample = 1;
    else
        firstSample = 2;
    end
    fields = string(fieldnames(combined));
    for fieldIdx = 1:numel(fields)
        field = fields(fieldIdx);
        combined.(field) = [ ...
            combined.(field); segment.(field)(firstSample:end, :)];
    end
end

function ego = localEgoState( ...
        positionX, positionY, yaw, longitudinalVelocity, ...
        lateralVelocity, yawRate)
    ego = struct();
    ego.position = [positionX; positionY];
    ego.yawAngle = yaw;
    ego.longitudinalVelocity = longitudinalVelocity;
    ego.lateralVelocity = lateralVelocity;
    ego.yawRate = yawRate;
end

function row = localStateRow(state)
    row = [ ...
        state.position(1), state.position(2), state.yawAngle, ...
        state.longitudinalVelocity, state.lateralVelocity, ...
        state.yawRate];
end

function failure = localEmptyFailure()
    failure = struct( ...
        "occurred", false, ...
        "identifier", "", ...
        "message", "", ...
        "controlStep", NaN, ...
        "time", NaN);
end

function context = localEmptyFailureContext()
    context = struct( ...
        "controllerState", [], ...
        "targetEstimate", struct([]), ...
        "controllerRoadGeometry", []);
end

function failure = localControllerFailure(exception, stepIdx, time)
    failure = struct( ...
        "occurred", true, ...
        "identifier", string(exception.identifier), ...
        "message", string(exception.message), ...
        "controlStep", stepIdx, ...
        "time", time);
end

function criteria = localAcceptanceCriteria(options)
    criteria = struct( ...
        "maximumAbsoluteSpeedError", options.speedTolerance, ...
        "maximumAbsoluteLateralError", options.lateralTolerance, ...
        "maximumAbsoluteLateralPosition", options.lateralTolerance, ...
        "maximumAbsoluteHeadingError", options.headingTolerance);
end

function [metrics, tracking] = localMetrics( ...
        controlState, command, failure, ...
        completedStepCount, requestedStepCount, ...
        terminalTaskCompleted, referenceSpeed, ...
        centerline, criteria, solveTime, sampleTime)
    speedError = controlState(:, 4) - referenceSpeed;
    tracking = localCenterlineTracking(controlState, centerline);
    lateralError = tracking.lateralError;
    headingError = tracking.headingError;
    controllerCompleted = ( ...
        completedStepCount == requestedStepCount ...
        || terminalTaskCompleted) ...
        && ~failure.occurred;

    if isempty(command)
        firstFrontAxleForce = NaN;
        firstLongitudinalAcceleration = NaN;
        meanFrontWheelSteeringAngle = NaN;
    else
        firstFrontAxleForce = command{1}.axleLongitudinalForce(1);
        firstLongitudinalAcceleration = ...
            command{1}.longitudinalAcceleration;
        meanFrontWheelSteeringAngle = mean(cellfun( ...
            @(value) value.frontWheelSteeringAngle, command));
    end
    speedWithinTolerance = max(abs(speedError)) ...
        <= criteria.maximumAbsoluteSpeedError;
    lateralWithinTolerance = max(abs(lateralError)) ...
        <= criteria.maximumAbsoluteLateralError;
    headingWithinTolerance = max(abs(headingError)) ...
        <= criteria.maximumAbsoluteHeadingError;

    metrics = struct();
    metrics.requestedControlSteps = requestedStepCount;
    metrics.completedControlSteps = completedStepCount;
    metrics.terminalTaskCompleted = terminalTaskCompleted;
    metrics.controllerCompletedScenario = controllerCompleted;
    metrics.maximumAbsoluteSpeedError = max(abs(speedError));
    metrics.finalSpeedError = speedError(end);
    metrics.maximumAbsoluteLateralError = ...
        max(abs(lateralError));
    metrics.finalLateralError = lateralError(end);
    metrics.maximumAbsoluteLateralPosition = ...
        metrics.maximumAbsoluteLateralError;
    metrics.maximumAbsoluteHeadingError = max(abs(headingError));
    metrics.finalHeadingError = headingError(end);
    metrics.centerlineDistanceTravelled = ...
        tracking.distanceAlongCenterline(end) ...
        - tracking.distanceAlongCenterline(1);
    metrics.meanFrontWheelSteeringAngle = ...
        meanFrontWheelSteeringAngle;
    metrics.speedWithinTolerance = speedWithinTolerance;
    metrics.lateralWithinTolerance = lateralWithinTolerance;
    metrics.headingWithinTolerance = headingWithinTolerance;
    metrics.firstFrontAxleForce = firstFrontAxleForce;
    metrics.firstLongitudinalAcceleration = ...
        firstLongitudinalAcceleration;
    if isempty(solveTime)
        metrics.meanSolveTime = NaN;
        metrics.maximumSolveTime = NaN;
        metrics.solveDeadlineMetEveryStep = false;
    else
        metrics.meanSolveTime = mean(solveTime);
        metrics.maximumSolveTime = max(solveTime);
        metrics.solveDeadlineMetEveryStep = all(solveTime <= sampleTime);
    end
    metrics.cruiseMaintained = controllerCompleted ...
        && speedWithinTolerance ...
        && lateralWithinTolerance ...
        && headingWithinTolerance;
end

function tracking = localCenterlineTracking(controlState, centerline)
    segment = diff(centerline, 1, 1);
    segmentLength = vecnorm(segment, 2, 2);
    segmentLengthSquared = segmentLength.^2;
    cumulativeLength = [0.0; cumsum(segmentLength)];
    stateCount = size(controlState, 1);

    projectedPosition = NaN(stateCount, 2);
    referenceHeading = NaN(stateCount, 1);
    lateralError = NaN(stateCount, 1);
    headingError = NaN(stateCount, 1);
    distanceAlongCenterline = NaN(stateCount, 1);

    for stateIdx = 1:stateCount
        position = controlState(stateIdx, 1:2);
        relativePosition = position - centerline(1:(end - 1), :);
        fraction = sum(relativePosition .* segment, 2) ...
            ./ segmentLengthSquared;
        fraction = min(max(fraction, 0.0), 1.0);
        projection = centerline(1:(end - 1), :) ...
            + fraction .* segment;
        distanceSquared = sum((position - projection).^2, 2);
        [~, segmentIdx] = min(distanceSquared);

        tangent = segment(segmentIdx, :) ...
            / segmentLength(segmentIdx);
        offset = position - projection(segmentIdx, :);
        projectedPosition(stateIdx, :) = ...
            projection(segmentIdx, :);
        referenceHeading(stateIdx) = atan2(tangent(2), tangent(1));
        lateralError(stateIdx) = ...
            tangent(1) * offset(2) - tangent(2) * offset(1);
        headingDifference = controlState(stateIdx, 3) ...
            - referenceHeading(stateIdx);
        headingError(stateIdx) = atan2( ...
            sin(headingDifference), cos(headingDifference));
        distanceAlongCenterline(stateIdx) = ...
            cumulativeLength(segmentIdx) ...
            + fraction(segmentIdx) * segmentLength(segmentIdx);
    end

    tracking = struct();
    tracking.projectedPosition = projectedPosition;
    tracking.referenceHeading = referenceHeading;
    tracking.lateralError = lateralError;
    tracking.headingError = headingError;
    tracking.distanceAlongCenterline = distanceAlongCenterline;
end

function localReport(result)
    metrics = result.metrics;
    fprintf("\n%s\n", result.scenario.description);
    fprintf("  Plant: %s\n", result.plant.source);
    fprintf("  Reference speed: %.3f m/s\n", ...
        result.scenario.referenceSpeed);
    fprintf("  Completed controller steps: %d / %d\n", ...
        metrics.completedControlSteps, metrics.requestedControlSteps);
    fprintf("  Mean / maximum solve time: %.6f / %.6f s\n", ...
        metrics.meanSolveTime, metrics.maximumSolveTime);
    fprintf("  Maximum absolute speed error: %.6f m/s\n", ...
        metrics.maximumAbsoluteSpeedError);
    fprintf("  Maximum absolute lateral tracking error: %.6f m\n", ...
        metrics.maximumAbsoluteLateralError);
    fprintf("  Maximum absolute heading error: %.6f rad\n", ...
        metrics.maximumAbsoluteHeadingError);
    fprintf("  First front-axle longitudinal force: %.6f N\n", ...
        metrics.firstFrontAxleForce);
    fprintf("  First predicted longitudinal acceleration: %.6f m/s^2\n", ...
        metrics.firstLongitudinalAcceleration);
    if result.failure.occurred
        fprintf("  Controller failure at t = %.3f s: %s\n", ...
            result.failure.time, result.failure.identifier);
        fprintf("  Failure message: %s\n", result.failure.message);
    end
    if result.passed
        fprintf("  Result: PASS\n\n");
    else
        fprintf("  Result: FAIL\n\n");
    end
end

function localPlot(result)
    figure(Name=result.scenario.description);
    tiledlayout(2, 1);

    nexttile;
    plot(result.plantTrace.positionX, ...
        result.plantTrace.positionY, LineWidth=1.5);
    hold on;
    plot(result.scenario.centerline(:, 1), ...
        result.scenario.centerline(:, 2), "k--");
    grid on;
    axis equal;
    xlabel("Inertial x (m)");
    ylabel("Inertial y (m)");
    legend("Ego CG", "Centerline", Location="best");

    nexttile;
    plot(result.plantTrace.time, ...
        result.plantTrace.longitudinalVelocity, LineWidth=1.5);
    hold on;
    yline(result.scenario.referenceSpeed, "k--");
    grid on;
    xlabel("Time (s)");
    ylabel("Longitudinal speed (m/s)");
    legend("Vehicle", "Reference", Location="best");
end
