function result = runCircularCenterlineCruiseScenario(varargin)
% runCircularCenterlineCruiseScenario Test left circular-arc cruise.
%
% The centerline is a polygonal sampling of a circle with constant positive
% curvature. Its chord through the initial position is horizontal, so the
% ego vehicle starts exactly on the centerline with zero heading error.

    options = localOptions(varargin{:});
    [centerline, geometry] = circularCenterlinePolyline(options);
    geometry.type = "circularArc";
    description = sprintf( ...
        "Left circular-arc centerline, radius %.3f m, " ...
        + "constant reference speed, no targets", options.radius);

    result = runCenterlineCruiseScenario( ...
        "Centerline", centerline, ...
        "InitialPosition", [0.0; 0.0], ...
        "InitialYaw", 0.0, ...
        "InitialLateralVelocity", 0.0, ...
        "InitialYawRate", ...
            options.referenceSpeed / options.radius, ...
        "InitializeCruiseEquilibrium",true, ...
        "ControllerConfiguration",options.controllerConfiguration, ...
        "Description", description, ...
        "Geometry", geometry, ...
        "Duration", options.duration, ...
        "ReferenceSpeed", options.referenceSpeed, ...
        "SpeedTolerance", options.speedTolerance, ...
        "LateralTolerance", options.lateralTolerance, ...
        "HeadingTolerance", options.headingTolerance, ...
        "Plot", options.plot, ...
        "Report", options.report);
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = "runCircularCenterlineCruiseScenario";
    addParameter(parser, "Radius", 100.0, @localPositiveScalar);
    addParameter(parser, "ArcLengthBefore", 40.0, ...
        @localNonnegativeScalar);
    addParameter(parser, "ArcLengthAfter", 200.0, ...
        @localPositiveScalar);
    addParameter(parser, "CenterlineSpacing", 0.1, ...
        @localPositiveScalar);
    addParameter(parser, "Duration", 4.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "SpeedTolerance", 0.5, @localPositiveScalar);
    addParameter(parser, "LateralTolerance", 0.2, @localPositiveScalar);
    addParameter(parser, "HeadingTolerance", 0.02, @localPositiveScalar);
    addParameter(parser, "Plot", false, @localLogicalScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser,"ControllerConfiguration",struct(),@(x) isstruct(x)&&isscalar(x));
    parse(parser, varargin{:});

    options = struct();
    options.radius = double(parser.Results.Radius);
    options.arcLengthBefore = ...
        double(parser.Results.ArcLengthBefore);
    options.arcLengthAfter = ...
        double(parser.Results.ArcLengthAfter);
    options.centerlineSpacing = ...
        double(parser.Results.CenterlineSpacing);
    options.duration = double(parser.Results.Duration);
    options.referenceSpeed = double(parser.Results.ReferenceSpeed);
    options.speedTolerance = double(parser.Results.SpeedTolerance);
    options.lateralTolerance = double(parser.Results.LateralTolerance);
    options.headingTolerance = double(parser.Results.HeadingTolerance);
    options.plot = logical(parser.Results.Plot);
    options.report = logical(parser.Results.Report);
    options.controllerConfiguration = parser.Results.ControllerConfiguration;
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end
