function result = ...
        runCircularCenterlineStraightTargetAvoidanceScenario(varargin)
% runCircularCenterlineStraightTargetAvoidanceScenario Test avoidance on an arc.
%
% The ego nominally cruises at constant speed on a left circular
% centerline. The target moves at constant speed on a straight line tangent
% to the centerline. Its initial position is constructed so that the target
% and nominal ego centers coincide at the nominal collision time. Thus the
% no-avoidance trajectory is geometrically guaranteed to collide.

    options = localOptions(varargin{:});
    [centerline, centerlineGeometry] = ...
        circularCenterlinePolyline(options);
    collisionGeometry = localCollisionGeometry( ...
        centerline, options);
    targetStateFunction = @(time, egoState) ...
        localTargetState(time, egoState, ...
            collisionGeometry, options);
    geometry = centerlineGeometry;
    geometry.type = "circularArcStraightTargetCollision";
    geometry.targetMotion = "constantVelocityStraightLine";
    geometry.targetInitialDistance = ...
        collisionGeometry.targetInitialDistance;
    geometry.targetInitialPosition = ...
        collisionGeometry.targetInitialPosition;
    geometry.targetVelocity = collisionGeometry.targetVelocity;
    geometry.nominalCollisionTime = ...
        collisionGeometry.nominalCollisionTime;
    geometry.nominalCollisionPosition = ...
        collisionGeometry.nominalCollisionPosition;
    geometry.nominalTargetCollisionPosition = ...
        collisionGeometry.nominalTargetCollisionPosition;
    geometry.nominalCollisionHeading = ...
        collisionGeometry.nominalCollisionHeading;
    geometry.targetCollisionLateralOffset = ...
        options.targetCollisionLateralOffset;
    geometry.perceptionRange = options.perceptionRange;
    geometry.rightRoadBoundaryOffset = ...
        options.rightRoadBoundaryOffset;
    geometry.leftRoadBoundaryOffset = ...
        options.leftRoadBoundaryOffset;
    geometry.roadShoulderWidth = options.roadShoulderWidth;

    description = sprintf( ...
        "Left circular centerline (R = %.1f m) with a straight-line " ...
        + "target constructed to collide at t = %.3f s", ...
        options.radius, collisionGeometry.nominalCollisionTime);
    result = runCenterlineCruiseScenario( ...
        Centerline=centerline, ...
        InitialPosition=[0.0; 0.0], ...
        InitialYaw=0.0, ...
        InitialLateralVelocity=0.0, ...
        InitialYawRate=options.referenceSpeed / options.radius, ...
        Description=description, ...
        Geometry=geometry, ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetStateFunction=targetStateFunction, ...
        UseStateEstimator=options.useStateEstimator, ...
        EstimatorConfiguration=options.estimatorConfiguration, ...
        PerceptionRange=options.perceptionRange, ...
        RoadBoundaryOffsets=[ ...
            options.rightRoadBoundaryOffset; ...
            options.leftRoadBoundaryOffset], ...
        RoadShoulderWidth=options.roadShoulderWidth, ...
        EgoCollisionSize=[ ...
            options.egoLength; options.egoWidth], ...
        TargetCollisionSize=[ ...
            options.targetLength; options.targetWidth], ...
        SpeedTolerance=options.recoverySpeedTolerance, ...
        LateralTolerance=options.recoveryLateralTolerance, ...
        HeadingTolerance=options.recoveryHeadingTolerance, ...
        Plot=false, ...
        Report=false, ...
        Progress=options.progress);

    result = localAvoidanceEvaluation( ...
        result, centerline, collisionGeometry, options);
    if options.report
        localReport(result);
    end
    if options.plot
        localPlot(result);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = ...
        "runCircularCenterlineStraightTargetAvoidanceScenario";
    addParameter(parser, "Radius", 100.0, @localPositiveScalar);
    addParameter(parser, "ArcLengthBefore", ...
        40.0, @localNonnegativeScalar);
    addParameter(parser, "ArcLengthAfter", ...
        220.0, @localPositiveScalar);
    addParameter(parser, "CenterlineSpacing", ...
        0.1, @localPositiveScalar);
    addParameter(parser, "Duration", 10.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", ...
        15.0, @localPositiveScalar);
    addParameter(parser, "TargetSpeed", ...
        15.0, @localPositiveScalar);
    addParameter(parser, "TargetInitialDistance", ...
        50.0, @localPositiveScalar);
    addParameter(parser, "TargetCollisionLateralOffset", ...
        1.5, @localFiniteScalar);
    addParameter(parser, "TargetLength", ...
        5.0, @localPositiveScalar);
    addParameter(parser, "TargetWidth", ...
        2.0, @localPositiveScalar);
    addParameter(parser, "PerceptionRange", ...
        30.0, @localPositiveScalar);
    addParameter(parser, "RightRoadBoundaryOffset", ...
        6.0, @localPositiveScalar);
    addParameter(parser, "LeftRoadBoundaryOffset", ...
        8.0, @localPositiveScalar);
    addParameter(parser, "RoadShoulderWidth", ...
        2.6, @localPositiveScalar);
    addParameter(parser, "EgoLength", ...
        5.0, @localPositiveScalar);
    addParameter(parser, "EgoWidth", ...
        2.0, @localPositiveScalar);
    addParameter(parser, "UseStateEstimator", false, ...
        @localLogicalScalar);
    addParameter(parser, "EstimatorConfiguration", struct(), ...
        @localScalarStruct);
    addParameter(parser, "RecoveryWindow", ...
        1.0, @localPositiveScalar);
    addParameter(parser, "RecoverySpeedTolerance", ...
        0.5, @localPositiveScalar);
    addParameter(parser, "RecoveryLateralTolerance", ...
        0.2, @localPositiveScalar);
    addParameter(parser, "RecoveryHeadingTolerance", ...
        0.02, @localPositiveScalar);
    addParameter(parser, "Plot", false, @localLogicalScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", false, @localLogicalScalar);
    parse(parser, varargin{:});

    options = struct( ...
        "radius", double(parser.Results.Radius), ...
        "arcLengthBefore", ...
            double(parser.Results.ArcLengthBefore), ...
        "arcLengthAfter", ...
            double(parser.Results.ArcLengthAfter), ...
        "centerlineSpacing", ...
            double(parser.Results.CenterlineSpacing), ...
        "duration", double(parser.Results.Duration), ...
        "referenceSpeed", ...
            double(parser.Results.ReferenceSpeed), ...
        "targetSpeed", double(parser.Results.TargetSpeed), ...
        "targetInitialDistance", ...
            double(parser.Results.TargetInitialDistance), ...
        "targetCollisionLateralOffset", ...
            double(parser.Results.TargetCollisionLateralOffset), ...
        "targetLength", double(parser.Results.TargetLength), ...
        "targetWidth", double(parser.Results.TargetWidth), ...
        "perceptionRange", ...
            double(parser.Results.PerceptionRange), ...
        "rightRoadBoundaryOffset", ...
            double(parser.Results.RightRoadBoundaryOffset), ...
        "leftRoadBoundaryOffset", ...
            double(parser.Results.LeftRoadBoundaryOffset), ...
        "roadShoulderWidth", ...
            double(parser.Results.RoadShoulderWidth), ...
        "egoLength", double(parser.Results.EgoLength), ...
        "egoWidth", double(parser.Results.EgoWidth), ...
        "useStateEstimator", ...
            logical(parser.Results.UseStateEstimator), ...
        "estimatorConfiguration", ...
            parser.Results.EstimatorConfiguration, ...
        "recoveryWindow", ...
            double(parser.Results.RecoveryWindow), ...
        "recoverySpeedTolerance", ...
            double(parser.Results.RecoverySpeedTolerance), ...
        "recoveryLateralTolerance", ...
            double(parser.Results.RecoveryLateralTolerance), ...
        "recoveryHeadingTolerance", ...
            double(parser.Results.RecoveryHeadingTolerance), ...
        "plot", logical(parser.Results.Plot), ...
        "report", logical(parser.Results.Report), ...
        "progress", logical(parser.Results.Progress));
end

function geometry = localCollisionGeometry(centerline, options)
    initialPosition = [0.0, 0.0];
    initialAbscissa = localProjectToCenterline( ...
        initialPosition, centerline);
    centerlineLength = localCenterlineLength(centerline);
    maximumCollisionTime = ...
        (centerlineLength - initialAbscissa) ...
        / options.referenceSpeed;
    residual = @(time) localInitialDistanceResidual( ...
        time, initialAbscissa, centerline, options);

    lowerTime = 0.0;
    upperTime = min(maximumCollisionTime, ...
        2.0 * options.targetInitialDistance ...
        / (options.referenceSpeed + options.targetSpeed));
    while residual(upperTime) < 0.0 ...
            && upperTime < maximumCollisionTime
        upperTime = min(maximumCollisionTime, ...
            max(upperTime + 0.5, 1.5 * upperTime));
    end
    if residual(upperTime) < 0.0
        error( ...
            "runCircularCenterlineStraightTargetAvoidanceScenario:" ...
            + "centerlineTooShort", ...
            "ArcLengthAfter is too short to construct the collision.");
    end
    collisionTime = fzero(residual, [lowerTime, upperTime]);
    collisionAbscissa = initialAbscissa ...
        + options.referenceSpeed * collisionTime;
    [collisionPosition, collisionHeading] = ...
        localCenterlinePose(centerline, collisionAbscissa);
    tangent = [cos(collisionHeading); sin(collisionHeading)];
    normal = [-tangent(2); tangent(1)];
    targetDirection = -tangent;
    targetVelocity = options.targetSpeed * targetDirection;
    targetCollisionPosition = collisionPosition.' ...
        + options.targetCollisionLateralOffset * normal;
    targetInitialPosition = targetCollisionPosition ...
        - collisionTime * targetVelocity;

    geometry = struct( ...
        "initialCenterlineAbscissa", initialAbscissa, ...
        "nominalCollisionTime", collisionTime, ...
        "nominalCollisionPosition", collisionPosition, ...
        "nominalTargetCollisionPosition", ...
            targetCollisionPosition, ...
        "nominalCollisionHeading", collisionHeading, ...
        "collisionTangent", tangent, ...
        "targetInitialPosition", targetInitialPosition, ...
        "targetVelocity", targetVelocity, ...
        "targetYaw", atan2(targetVelocity(2), targetVelocity(1)), ...
        "targetInitialDistance", ...
            norm(targetInitialPosition - initialPosition.'));
end

function residual = localInitialDistanceResidual( ...
        time, initialAbscissa, centerline, options)
    abscissa = initialAbscissa ...
        + options.referenceSpeed * time;
    [position, heading] = localCenterlinePose( ...
        centerline, abscissa);
    tangent = [cos(heading); sin(heading)];
    normal = [-tangent(2); tangent(1)];
    targetInitialPosition = position.' ...
        + options.targetCollisionLateralOffset * normal ...
        + options.targetSpeed * time * tangent;
    residual = norm(targetInitialPosition) ...
        - options.targetInitialDistance;
end

function target = localTargetState( ...
        time, ~, geometry, options)
    targetPosition = geometry.targetInitialPosition ...
        + geometry.targetVelocity * time;
    target = struct( ...
        "targetPositionInertial", targetPosition, ...
        "targetVelocityInertial", geometry.targetVelocity, ...
        "targetAccelerationInertial", [0.0; 0.0], ...
        "targetYawInertial", geometry.targetYaw, ...
        "targetYawRate", 0.0, ...
        "targetLength", options.targetLength, ...
        "targetWidth", options.targetWidth);
end

function result = localAvoidanceEvaluation( ...
        result, centerline, geometry, options)
    sampleTimeTolerance = 100.0 * eps(max( ...
        1.0, result.scenario.sampleTime));
    if abs(result.scenario.sampleTime - 0.1) > sampleTimeTolerance
        error( ...
            "runCircularCenterlineStraightTargetAvoidanceScenario:" ...
            + "invalidSampleTime", ...
            "The perception and control sample time must be 0.1 s.");
    end

    traceTime = result.plantTrace.time;
    if isempty(traceTime)
        result.targetTruth = localEmptyTargetTruth(options);
        result.baseline = localEmptyBaseline();
        result.controlled = struct( ...
            "separatingAxisMargin", zeros(0, 1));
        result.avoidance = localEmptyAvoidance(geometry, options);
        result.passed = false;
        return;
    end

    targetPosition = geometry.targetInitialPosition.' ...
        + traceTime * geometry.targetVelocity.';
    targetYaw = geometry.targetYaw * ones(size(traceTime));
    egoPosition = [ ...
        result.plantTrace.positionX, ...
        result.plantTrace.positionY];
    egoYaw = result.plantTrace.yaw;
    vehicle = result.controllerConfiguration.vehicle;
    controlledMargin = rectangleSeparationMargin( ...
        egoPosition, egoYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    baselineAbscissa = geometry.initialCenterlineAbscissa ...
        + options.referenceSpeed * traceTime;
    [baselinePosition, baselineYaw] = ...
        localCenterlinePose(centerline, baselineAbscissa);
    baselineMargin = rectangleSeparationMargin( ...
        baselinePosition, baselineYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    collisionTargetPosition = ...
        geometry.targetInitialPosition ...
        + geometry.targetVelocity ...
            * geometry.nominalCollisionTime;
    constructionError = norm(collisionTargetPosition ...
        - geometry.nominalTargetCollisionPosition);
    nominalCollisionMargin = ...
        rectangleSeparationMargin( ...
            geometry.nominalCollisionPosition, ...
            geometry.nominalCollisionHeading, ...
            collisionTargetPosition.', geometry.targetYaw, ...
            vehicle.length, vehicle.width, ...
            options.targetLength, options.targetWidth);

    relativeApproachCoordinate = ...
        (targetPosition - egoPosition) ...
        * geometry.collisionTangent;
    passingIdx = find(relativeApproachCoordinate <= 0.0, 1);
    if isempty(passingIdx)
        passedTarget = false;
        passingTime = NaN;
        passingSpeed = NaN;
    else
        passedTarget = true;
        passingTime = traceTime(passingIdx);
        passingSpeed = ...
            result.plantTrace.longitudinalVelocity(passingIdx);
    end

    [minimumControlledMargin, closestIdx] = ...
        min(controlledMargin);
    minimumBaselineMargin = min(baselineMargin);
    trackingState = [egoPosition, egoYaw];
    tracking = localCenterlineTracking( ...
        trackingState, centerline);
    velocityCourse = egoYaw + atan2( ...
        result.plantTrace.lateralVelocity, ...
        result.plantTrace.longitudinalVelocity);
    courseTracking = localCenterlineTracking( ...
        [egoPosition, velocityCourse], centerline);
    recoveryStartTime = max(0.0, ...
        options.duration - options.recoveryWindow);
    recoveryMask = traceTime >= recoveryStartTime;
    recoverySpeedError = ...
        result.plantTrace.longitudinalVelocity(recoveryMask) ...
        - options.referenceSpeed;
    recoveryLateralError = ...
        tracking.lateralError(recoveryMask);
    recoveryCourseError = ...
        courseTracking.headingError(recoveryMask);
    recoveryBodyHeadingError = ...
        tracking.headingError(recoveryMask);
    recoveredCruise = ~isempty(recoverySpeedError) ...
        && max(abs(recoverySpeedError)) ...
            <= options.recoverySpeedTolerance ...
        && max(abs(recoveryLateralError)) ...
            <= options.recoveryLateralTolerance ...
        && max(abs(recoveryCourseError)) ...
            <= options.recoveryHeadingTolerance;
    collisionFree = minimumControlledMargin > 0.0;
    baselineCollides = minimumBaselineMargin < 0.0;
    minimumEgoLongitudinalSpeed = min( ...
        result.plantTrace.longitudinalVelocity);
    remainedMoving = minimumEgoLongitudinalSpeed > 0.0;
    constructionTolerance = 1000.0 * eps(max( ...
        1.0, norm(geometry.nominalCollisionPosition)));
    collisionConstructionExact = ...
        constructionError <= constructionTolerance;

    avoidance = struct( ...
        "targetInitialDistance", ...
            geometry.targetInitialDistance, ...
        "targetInitialPosition", ...
            geometry.targetInitialPosition, ...
        "targetVelocity", geometry.targetVelocity, ...
        "nominalCollisionTime", ...
            geometry.nominalCollisionTime, ...
        "nominalCollisionPosition", ...
            geometry.nominalCollisionPosition, ...
        "nominalTargetCollisionPosition", ...
            geometry.nominalTargetCollisionPosition, ...
        "targetCollisionLateralOffset", ...
            options.targetCollisionLateralOffset, ...
        "collisionConstructionError", constructionError, ...
        "collisionConstructionExact", ...
            collisionConstructionExact, ...
        "nominalCollisionSeparatingAxisMargin", ...
            nominalCollisionMargin, ...
        "minimumControlledSeparatingAxisMargin", ...
            minimumControlledMargin, ...
        "minimumBaselineSeparatingAxisMargin", ...
            minimumBaselineMargin, ...
        "baselineCollides", baselineCollides, ...
        "collisionFree", collisionFree, ...
        "closestApproachTime", traceTime(closestIdx), ...
        "passedTarget", passedTarget, ...
        "passingTime", passingTime, ...
        "egoSpeedAtPassing", passingSpeed, ...
        "minimumEgoLongitudinalSpeed", ...
            minimumEgoLongitudinalSpeed, ...
        "remainedMoving", remainedMoving, ...
        "noRoadBoundaryCrossing", ...
            result.roadSafety.noBoundaryCrossing, ...
        "minimumRoadBoundaryFunctionMargin", ...
            result.roadSafety.minimumBoundaryFunctionMargin, ...
        "minimumLateralTrackingError", ...
            min(tracking.lateralError), ...
        "maximumLateralTrackingError", ...
            max(tracking.lateralError), ...
        "recoveredCruise", recoveredCruise, ...
        "recoveryWindow", options.recoveryWindow, ...
        "maximumRecoverySpeedError", ...
            max(abs(recoverySpeedError)), ...
        "maximumRecoveryLateralError", ...
            max(abs(recoveryLateralError)), ...
        "recoveryOrientationMetric", ...
            "inertialVelocityCourseRelativeToCenterline", ...
        "maximumRecoveryHeadingError", ...
            max(abs(recoveryCourseError)), ...
        "maximumRecoveryBodyHeadingError", ...
            max(abs(recoveryBodyHeadingError)));

    result.targetTruth = struct( ...
        "time", traceTime, ...
        "position", targetPosition, ...
        "yaw", targetYaw, ...
        "length", options.targetLength, ...
        "width", options.targetWidth);
    result.baseline = struct( ...
        "egoPosition", baselinePosition, ...
        "egoYaw", baselineYaw, ...
        "separatingAxisMargin", baselineMargin);
    result.controlled = struct( ...
        "separatingAxisMargin", controlledMargin, ...
        "centerlineTracking", tracking);
    result.avoidance = avoidance;
    result.passed = ~result.failure.occurred ...
        && result.metrics.controllerCompletedScenario ...
        && collisionConstructionExact ...
        && baselineCollides ...
        && collisionFree ...
        && result.roadSafety.noBoundaryCrossing ...
        && passedTarget ...
        && remainedMoving ...
        && recoveredCruise;
end

function targetTruth = localEmptyTargetTruth(options)
    targetTruth = struct( ...
        "time", zeros(0, 1), ...
        "position", zeros(0, 2), ...
        "yaw", zeros(0, 1), ...
        "length", options.targetLength, ...
        "width", options.targetWidth);
end

function baseline = localEmptyBaseline()
    baseline = struct( ...
        "egoPosition", zeros(0, 2), ...
        "egoYaw", zeros(0, 1), ...
        "separatingAxisMargin", zeros(0, 1));
end

function avoidance = localEmptyAvoidance(geometry, options)
    avoidance = struct( ...
        "targetInitialDistance", ...
            geometry.targetInitialDistance, ...
        "targetInitialPosition", ...
            geometry.targetInitialPosition, ...
        "targetVelocity", geometry.targetVelocity, ...
        "nominalCollisionTime", ...
            geometry.nominalCollisionTime, ...
        "nominalCollisionPosition", ...
            geometry.nominalCollisionPosition, ...
        "nominalTargetCollisionPosition", ...
            geometry.nominalTargetCollisionPosition, ...
        "targetCollisionLateralOffset", ...
            options.targetCollisionLateralOffset, ...
        "collisionConstructionError", NaN, ...
        "collisionConstructionExact", false, ...
        "nominalCollisionSeparatingAxisMargin", NaN, ...
        "minimumControlledSeparatingAxisMargin", NaN, ...
        "minimumBaselineSeparatingAxisMargin", NaN, ...
        "baselineCollides", false, ...
        "collisionFree", false, ...
        "closestApproachTime", NaN, ...
        "passedTarget", false, ...
        "passingTime", NaN, ...
        "egoSpeedAtPassing", NaN, ...
        "minimumEgoLongitudinalSpeed", NaN, ...
        "remainedMoving", false, ...
        "noRoadBoundaryCrossing", false, ...
        "minimumRoadBoundaryFunctionMargin", NaN, ...
        "minimumLateralTrackingError", NaN, ...
        "maximumLateralTrackingError", NaN, ...
        "recoveredCruise", false, ...
        "recoveryWindow", options.recoveryWindow, ...
        "maximumRecoverySpeedError", NaN, ...
        "maximumRecoveryLateralError", NaN, ...
        "recoveryOrientationMetric", ...
            "inertialVelocityCourseRelativeToCenterline", ...
        "maximumRecoveryHeadingError", NaN, ...
        "maximumRecoveryBodyHeadingError", NaN);
end

function length = localCenterlineLength(centerline)
    length = sum(vecnorm(diff(centerline, 1, 1), 2, 2));
end

function abscissa = localProjectToCenterline(position, centerline)
    segment = diff(centerline, 1, 1);
    segmentLength = vecnorm(segment, 2, 2);
    segmentLengthSquared = segmentLength.^2;
    relativePosition = position - centerline(1:(end - 1), :);
    fraction = sum(relativePosition .* segment, 2) ...
        ./ segmentLengthSquared;
    fraction = min(max(fraction, 0.0), 1.0);
    projection = centerline(1:(end - 1), :) ...
        + fraction .* segment;
    distanceSquared = sum((position - projection).^2, 2);
    [~, segmentIdx] = min(distanceSquared);
    cumulativeLength = [0.0; cumsum(segmentLength)];
    abscissa = cumulativeLength(segmentIdx) ...
        + fraction(segmentIdx) * segmentLength(segmentIdx);
end

function [position, heading] = ...
        localCenterlinePose(centerline, abscissa)
    segment = diff(centerline, 1, 1);
    segmentLength = vecnorm(segment, 2, 2);
    cumulativeLength = [0.0; cumsum(segmentLength)];
    queryAbscissa = abscissa(:);
    if any(queryAbscissa < 0.0) ...
            || any(queryAbscissa > cumulativeLength(end))
        error( ...
            "runCircularCenterlineStraightTargetAvoidanceScenario:" ...
            + "centerlineQueryOutsideDomain", ...
            "A requested nominal pose lies outside the centerline.");
    end

    position = NaN(numel(queryAbscissa), 2);
    heading = NaN(numel(queryAbscissa), 1);
    for queryIdx = 1:numel(queryAbscissa)
        segmentIdx = find( ...
            cumulativeLength <= queryAbscissa(queryIdx), ...
            1, "last");
        if segmentIdx == numel(cumulativeLength)
            segmentIdx = numel(segmentLength);
            fraction = 1.0;
        else
            fraction = (queryAbscissa(queryIdx) ...
                - cumulativeLength(segmentIdx)) ...
                / segmentLength(segmentIdx);
        end
        tangent = segment(segmentIdx, :) ...
            / segmentLength(segmentIdx);
        position(queryIdx, :) = centerline(segmentIdx, :) ...
            + fraction * segment(segmentIdx, :);
        heading(queryIdx) = atan2(tangent(2), tangent(1));
    end
    if isscalar(abscissa)
        position = position(1, :);
        heading = heading(1);
    end
end

function tracking = localCenterlineTracking(state, centerline)
    segment = diff(centerline, 1, 1);
    segmentLength = vecnorm(segment, 2, 2);
    segmentLengthSquared = segmentLength.^2;
    stateCount = size(state, 1);
    lateralError = NaN(stateCount, 1);
    headingError = NaN(stateCount, 1);

    for stateIdx = 1:stateCount
        position = state(stateIdx, 1:2);
        relativePosition = position ...
            - centerline(1:(end - 1), :);
        fraction = sum(relativePosition .* segment, 2) ...
            ./ segmentLengthSquared;
        fraction = min(max(fraction, 0.0), 1.0);
        projection = centerline(1:(end - 1), :) ...
            + fraction .* segment;
        distanceSquared = sum( ...
            (position - projection).^2, 2);
        [~, segmentIdx] = min(distanceSquared);
        tangent = segment(segmentIdx, :) ...
            / segmentLength(segmentIdx);
        offset = position - projection(segmentIdx, :);
        lateralError(stateIdx) = ...
            tangent(1) * offset(2) ...
            - tangent(2) * offset(1);
        referenceHeading = ...
            atan2(tangent(2), tangent(1));
        headingDifference = ...
            state(stateIdx, 3) - referenceHeading;
        headingError(stateIdx) = atan2( ...
            sin(headingDifference), cos(headingDifference));
    end
    tracking = struct( ...
        "lateralError", lateralError, ...
        "headingError", headingError);
end

function localReport(result)
    metrics = result.avoidance;
    fprintf("\n%s\n", result.scenario.description);
    fprintf("  Perception/control sample time: %.3f s\n", ...
        result.scenario.sampleTime);
    fprintf("  Target initial distance: %.6f m\n", ...
        metrics.targetInitialDistance);
    fprintf("  Constructed nominal collision time: %.6f s\n", ...
        metrics.nominalCollisionTime);
    fprintf("  Collision construction error: %.12g m\n", ...
        metrics.collisionConstructionError);
    fprintf("  Nominal collision SAT margin: %.6f m\n", ...
        metrics.nominalCollisionSeparatingAxisMargin);
    fprintf("  Baseline minimum SAT margin: %.6f m\n", ...
        metrics.minimumBaselineSeparatingAxisMargin);
    fprintf("  Controlled minimum SAT margin: %.6f m\n", ...
        metrics.minimumControlledSeparatingAxisMargin);
    fprintf("  Passing time / ego speed: %.3f s / %.3f m/s\n", ...
        metrics.passingTime, metrics.egoSpeedAtPassing);
    fprintf("  Minimum ego longitudinal speed: %.3f m/s\n", ...
        metrics.minimumEgoLongitudinalSpeed);
    fprintf("  Final-window maximum speed/lateral/heading errors: " ...
        + "%.6f m/s, %.6f m, %.6f rad\n", ...
        metrics.maximumRecoverySpeedError, ...
        metrics.maximumRecoveryLateralError, ...
        metrics.maximumRecoveryHeadingError);
    fprintf("  Mean / maximum solve time: %.6f / %.6f s\n", ...
        result.metrics.meanSolveTime, ...
        result.metrics.maximumSolveTime);
    if result.passed
        fprintf("  Result: PASS\n\n");
    else
        fprintf("  Result: FAIL\n\n");
    end
end

function localPlot(result)
    figure(Name=result.scenario.description);
    tiledlayout(2, 1);

    nexttile;
    plot(result.plantTrace.positionX, ...
        result.plantTrace.positionY, LineWidth=1.5);
    hold on;
    plot(result.targetTruth.position(:, 1), ...
        result.targetTruth.position(:, 2), LineWidth=1.5);
    plot(result.scenario.centerline(:, 1), ...
        result.scenario.centerline(:, 2), "k--");
    plot(result.baseline.egoPosition(:, 1), ...
        result.baseline.egoPosition(:, 2), ...
        Color=[0.6, 0.6, 0.6], LineStyle=":");
    grid on;
    axis equal;
    xlabel("Inertial x (m)");
    ylabel("Inertial y (m)");
    legend("Controlled ego", "Straight target", ...
        "Centerline", "Nominal ego", Location="best");

    nexttile;
    plot(result.plantTrace.time, ...
        result.plantTrace.longitudinalVelocity, LineWidth=1.5);
    hold on;
    yline(result.scenario.referenceSpeed, "k--");
    grid on;
    xlabel("Time (s)");
    ylabel("Ego longitudinal speed (m/s)");
    legend("Ego", "Reference", Location="best");
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localScalarStruct(value)
    valid = isstruct(value) && isscalar(value);
end
