function result = runEstimatedStateAvoidanceScenarios(varargin)
% runEstimatedStateAvoidanceScenarios Run the two active avoidance tests.
%
% The active scope contains straight and circular roads. Every scenario
% must independently satisfy estimator, collision, road, motion, recovery,
% and pre-detection-cruise acceptance. When requested, significant coupled
% motion is a suite-coverage requirement: at least one scenario must meet
% the unchanged acceleration and duration thresholds.

    options = localOptions(varargin{:});
    localAddProjectPaths();
    if isempty(fieldnames(options.controllerConfiguration))
        options.controllerConfiguration = finiteSensingValidationConfig();
    end
    baseConfiguration = estimatorControllerIntegrationConfig();
    baseConfiguration.vehicle.targetSpeed = options.targetSpeed;
    baseConfiguration.initialization.targetSpeedPrior = ...
        options.targetSpeed;
    baseConfiguration = localConfigurationForGeometry( ...
        baseConfiguration, options);

    straightConfiguration = baseConfiguration;
    straightConfiguration.randomSeed = options.seed;
    straight = runOncomingVehicleAvoidanceScenario( ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetSpeed=options.targetSpeed, ...
        TargetInitialLongitudinalDistance= ...
            options.straightTargetInitialDistance, ...
        TargetLateralOffset=options.straightTargetLateralOffset, ...
        TargetWidth=options.straightTargetWidth, ...
        RecoveryWindow=options.recoveryWindow, ...
        UseStateEstimator=true, ...
        EstimatorConfiguration=straightConfiguration, ...
        ControllerConfiguration=options.controllerConfiguration, ...
        Plot=false, Report=false, Progress=options.progress);
    straight = localAddScenarioEvaluations(straight, options);

    circularConfiguration = baseConfiguration;
    circularConfiguration.randomSeed = options.seed+1;
    circular = ...
        runCircularCenterlineStraightTargetAvoidanceScenario( ...
            Duration=options.duration, ...
            ReferenceSpeed=options.referenceSpeed, ...
            TargetSpeed=options.targetSpeed, ...
            Radius=options.circularRadius, ...
            ArcLengthAfter=options.curvedArcLengthAfter, ...
            TargetInitialDistance=options.curvedTargetInitialDistance, ...
            TargetCollisionLateralOffset= ...
                options.curvedTargetCollisionLateralOffset, ...
            TargetWidth=options.curvedTargetWidth, ...
            RecoveryWindow=options.recoveryWindow, ...
            UseStateEstimator=true, ...
            EstimatorConfiguration=circularConfiguration, ...
            ControllerConfiguration=options.controllerConfiguration, ...
            Plot=false, Report=false, Progress=options.progress);
    circular = localAddScenarioEvaluations(circular, options);

    scenarioPassed = [ ...
        localAvoidanceSucceeded( ...
            straight, options.requireCruiseRecovery, ...
            options.requirePreDetectionCruise); ...
        localAvoidanceSucceeded( ...
            circular, options.requireCruiseRecovery, ...
            options.requirePreDetectionCruise)];
    coupledScenario = [ ...
        straight.maneuverCoupling.significant; ...
        circular.maneuverCoupling.significant];
    couplingRequirementMet = ~options.requireCoupledManeuver ...
        || any(coupledScenario);
    couplingCriteria = struct( ...
        "longitudinalAccelerationThreshold", ...
            options.longitudinalAccelerationThreshold, ...
        "lateralAccelerationThreshold", ...
            options.lateralAccelerationThreshold, ...
        "minimumCoupledDuration", ...
            options.minimumCoupledDuration);
    result = struct( ...
        "configuration", baseConfiguration, ...
        "scenarioNames", [ ...
            "straight"; "circular"], ...
        "scenarioPassed", scenarioPassed, ...
        "allScenariosPassed", ...
            all(scenarioPassed) && couplingRequirementMet, ...
        "requireCruiseRecovery", options.requireCruiseRecovery, ...
        "requireCoupledManeuver", options.requireCoupledManeuver, ...
        "coupledScenario", coupledScenario, ...
        "couplingRequirementMet", couplingRequirementMet, ...
        "requirePreDetectionCruise", ...
            options.requirePreDetectionCruise, ...
        "couplingCriteria", couplingCriteria, ...
        "preDetectionCruiseCriteria", struct( ...
            "minimumDuration", ...
                options.minimumPreDetectionCruiseDuration, ...
            "speedTolerance", ...
                options.preDetectionSpeedTolerance, ...
            "lateralTolerance", ...
                options.preDetectionLateralTolerance, ...
            "headingTolerance", ...
                options.preDetectionHeadingTolerance), ...
        "straight", straight, ...
        "circular", circular);
    if options.report
        localReport(result);
    end
end

function result = localAddScenarioEvaluations(result, options)
    result.maneuverCoupling = evaluateManeuverCoupling( ...
        result, ...
        LongitudinalAccelerationThreshold= ...
            options.longitudinalAccelerationThreshold, ...
        LateralAccelerationThreshold= ...
            options.lateralAccelerationThreshold, ...
        MinimumCoupledDuration=options.minimumCoupledDuration);
    result.preDetectionCruise = evaluatePreDetectionCruise( ...
        result, ...
        MinimumDuration= ...
            options.minimumPreDetectionCruiseDuration, ...
        SpeedTolerance=options.preDetectionSpeedTolerance, ...
        LateralTolerance=options.preDetectionLateralTolerance, ...
        HeadingTolerance=options.preDetectionHeadingTolerance);
end

function succeeded = localAvoidanceSucceeded( ...
        result, requireCruiseRecovery, requirePreDetectionCruise)
    succeeded = ~result.failure.occurred ...
        && result.metrics.controllerCompletedScenario ...
        && result.avoidance.collisionFree ...
        && result.roadSafety.noBoundaryCrossing ...
        && result.avoidance.passedTarget ...
        && result.avoidance.remainedMoving ...
        && result.estimator.metrics.allEstimatesFinite ...
        && result.estimator.metrics.controllerInputsFromEstimator ...
        && result.estimator.metrics.sensorContractValid ...
        && result.estimator.metrics.sampledEgoPremisesSatisfied ...
        && result.estimator.metrics.allPublishedBoundsContainTruth ...
        && result.estimator.metrics.targetAcquisitionOccurred ...
        && result.estimator.metrics.allRadarDetectionsWithinRange;
    if requireCruiseRecovery
        succeeded = succeeded && result.avoidance.recoveredCruise;
    end
    if requirePreDetectionCruise
        succeeded = succeeded && result.preDetectionCruise.passed;
    end
end

function localReport(result)
    fprintf("\nNRMM estimator-in-the-loop collision avoidance\n");
    for scenarioIdx = 1:numel(result.scenarioNames)
        name = result.scenarioNames(scenarioIdx);
        scenario = result.(name);
        fprintf("  %s: %s, SAT margin %.4f m, min speed %.3f m/s\n", ...
            name, localPassText(result.scenarioPassed(scenarioIdx)), ...
            scenario.avoidance.minimumControlledSeparatingAxisMargin, ...
            scenario.avoidance.minimumEgoLongitudinalSpeed);
        fprintf("    ego position/velocity RMSE %.4f m / %.4f m/s\n", ...
            scenario.estimator.metrics.egoPositionRmse, ...
            scenario.estimator.metrics.egoVelocityRmse);
        fprintf("    target position/velocity RMSE %.4f m / %.4f m/s\n", ...
            scenario.estimator.metrics.targetPositionRmse, ...
            scenario.estimator.metrics.targetVelocityRmse);
        fprintf("    final-window speed/lateral/course-heading errors " ...
            + "%.4f m/s / %.4f m / %.4f rad; recovered: %d\n", ...
            scenario.avoidance.maximumRecoverySpeedError, ...
            scenario.avoidance.maximumRecoveryLateralError, ...
            scenario.avoidance.maximumRecoveryHeadingError, ...
            scenario.avoidance.recoveredCruise);
        fprintf("    road boundary margin %.4f; no crossing: %d\n", ...
            scenario.roadSafety.minimumBoundaryFunctionMargin, ...
            scenario.roadSafety.noBoundaryCrossing);
        fprintf("    initial target range %.2f m; first detection " ...
            + "%.2f s at %.2f m; pre-detection cruise %.2f s " ...
            + "(required %.2f s): %d\n", ...
            scenario.preDetectionCruise.initialTargetRange, ...
            scenario.preDetectionCruise.firstDetectionTime, ...
            scenario.preDetectionCruise.firstDetectionRange, ...
            scenario.preDetectionCruise.preDetectionDuration, ...
            scenario.preDetectionCruise.minimumRequiredDuration, ...
            scenario.preDetectionCruise.passed);
        fprintf("    body acceleration peaks |a_x| / |a_y| " ...
            + "%.3f / %.3f m/s^2; coupled %.2f s " ...
            + "(required %.2f s): %d\n", ...
            scenario.maneuverCoupling ...
                .maximumAbsoluteLongitudinalAcceleration, ...
            scenario.maneuverCoupling ...
                .maximumAbsoluteLateralAcceleration, ...
            scenario.maneuverCoupling ...
                .maximumContinuousCoupledDuration, ...
            scenario.maneuverCoupling.minimumCoupledDuration, ...
            scenario.maneuverCoupling.significant);
    end
    if result.requireCoupledManeuver
        coupledNames = result.scenarioNames(result.coupledScenario);
        fprintf("  Suite-level coupled-maneuver coverage: %s (%s)\n", ...
            localPassText(result.couplingRequirementMet), ...
            strjoin(coupledNames, ", "));
    end
    fprintf("  Overall: %s\n\n", ...
        localPassText(result.allScenariosPassed));
end

function value = localPassText(passed)
    if passed
        value = "PASS";
    else
        value = "FAIL";
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    % Eighteen seconds leaves several seconds after the close encounter for
    % both geometries to demonstrate renewed centerline constant-speed
    % cruise, rather than merely being collision-free at the video end.
    addParameter(parser, "Duration", 18.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 10.0, @localPositiveScalar);
    addParameter(parser, "TargetSpeed", 10.0, @localPositiveScalar);
    addParameter(parser, "StraightTargetInitialDistance", 100.0, ...
        @localPositiveScalar);
    addParameter(parser, "StraightTargetLateralOffset", 0.8, ...
        @localFiniteScalar);
    addParameter(parser, "StraightTargetWidth", 2.00, ...
        @localPositiveScalar);
    addParameter(parser, "CurvedTargetInitialDistance", 100.0, ...
        @localPositiveScalar);
    addParameter(parser, "CurvedTargetWidth", 2.00, ...
        @localPositiveScalar);
    addParameter(parser, "CurvedTargetCollisionLateralOffset", ...
        0.8, @localFiniteScalar);
    addParameter(parser, "CurvedArcLengthAfter", 300.0, ...
        @localPositiveScalar);
    addParameter(parser, "CircularRadius", 60.0, ...
        @localPositiveScalar);
    addParameter(parser, "RecoveryWindow", 1.0, ...
        @localPositiveScalar);
    addParameter(parser, "RequireCruiseRecovery", true, ...
        @localLogicalScalar);
    addParameter(parser, "LongitudinalAccelerationThreshold", 1.0, ...
        @localPositiveScalar);
    addParameter(parser, "LateralAccelerationThreshold", 3.0, ...
        @localPositiveScalar);
    addParameter(parser, "MinimumCoupledDuration", 0.3, ...
        @localPositiveScalar);
    addParameter(parser, "RequireCoupledManeuver", true, ...
        @localLogicalScalar);
    addParameter(parser, "MinimumPreDetectionCruiseDuration", ...
        2.0, @localNonnegativeScalar);
    addParameter(parser, "PreDetectionSpeedTolerance", ...
        0.5, @localNonnegativeScalar);
    addParameter(parser, "PreDetectionLateralTolerance", ...
        0.25, @localNonnegativeScalar);
    addParameter(parser, "PreDetectionHeadingTolerance", ...
        0.03, @localNonnegativeScalar);
    addParameter(parser, "RequirePreDetectionCruise", true, ...
        @localLogicalScalar);
    addParameter(parser, "Seed", 20260728, @localIntegerScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", false, @localLogicalScalar);
    addParameter(parser,"ControllerConfiguration",struct(),@(x) isstruct(x)&&isscalar(x));
    parse(parser, varargin{:});
    options = struct( ...
        "controllerConfiguration",parser.Results.ControllerConfiguration, ...
        "duration", double(parser.Results.Duration), ...
        "referenceSpeed", double(parser.Results.ReferenceSpeed), ...
        "targetSpeed", double(parser.Results.TargetSpeed), ...
        "straightTargetInitialDistance", ...
            double(parser.Results.StraightTargetInitialDistance), ...
        "straightTargetLateralOffset", ...
            double(parser.Results.StraightTargetLateralOffset), ...
        "straightTargetWidth", ...
            double(parser.Results.StraightTargetWidth), ...
        "curvedTargetInitialDistance", ...
            double(parser.Results.CurvedTargetInitialDistance), ...
        "curvedTargetWidth", ...
            double(parser.Results.CurvedTargetWidth), ...
        "curvedTargetCollisionLateralOffset", ...
            double(parser.Results ...
                .CurvedTargetCollisionLateralOffset), ...
        "curvedArcLengthAfter", ...
            double(parser.Results.CurvedArcLengthAfter), ...
        "circularRadius", double(parser.Results.CircularRadius), ...
        "recoveryWindow", double(parser.Results.RecoveryWindow), ...
        "requireCruiseRecovery", ...
            logical(parser.Results.RequireCruiseRecovery), ...
        "longitudinalAccelerationThreshold", ...
            double(parser.Results.LongitudinalAccelerationThreshold), ...
        "lateralAccelerationThreshold", ...
            double(parser.Results.LateralAccelerationThreshold), ...
        "minimumCoupledDuration", ...
            double(parser.Results.MinimumCoupledDuration), ...
        "requireCoupledManeuver", ...
            logical(parser.Results.RequireCoupledManeuver), ...
        "minimumPreDetectionCruiseDuration", ...
            double(parser.Results ...
                .MinimumPreDetectionCruiseDuration), ...
        "preDetectionSpeedTolerance", ...
            double(parser.Results.PreDetectionSpeedTolerance), ...
        "preDetectionLateralTolerance", ...
            double(parser.Results.PreDetectionLateralTolerance), ...
        "preDetectionHeadingTolerance", ...
            double(parser.Results.PreDetectionHeadingTolerance), ...
        "requirePreDetectionCruise", ...
            logical(parser.Results.RequirePreDetectionCruise), ...
        "seed", double(parser.Results.Seed), ...
        "report", logical(parser.Results.Report), ...
        "progress", logical(parser.Results.Progress));
end

function cfg = localConfigurationForGeometry(cfg, options)
    nominalYawRateMaximum = ...
        options.referenceSpeed/options.circularRadius;
    cfg.observer.ego.domain.yawRateMaximum = max( ...
        cfg.observer.ego.domain.yawRateMaximum, ...
        1.5*nominalYawRateMaximum);
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localIntegerScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value == floor(value);
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function localAddProjectPaths()
    repositoryRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repositoryRoot, "config"));
    addpath(fullfile(repositoryRoot, "scripts"));
end
