function summary = runInputDeviationPenaltyExperiment(outputDirectory, weights, duration, scenarios)
%runInputDeviationPenaltyExperiment Closed-loop fixed-linearization cost sweep.
% Raw MAT results and Simulink artifacts belong outside the repository.
% A shortened run is not evidence of completed avoidance or recovery.
    arguments
        outputDirectory (1,1) string
        weights (1,:) double {mustBeNonnegative,mustBeFinite} = [0,10,1000]
        duration (1,1) double {mustBePositive} = 18
        scenarios (1,:) string = ["straight","circular","sCurve"]
    end
    if ~isfolder(outputDirectory),mkdir(outputDirectory);end
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root,'controller'),fullfile(root,'config'),fullfile(root,'scripts'));
    Simulink.fileGenControl('set','CacheFolder',fullfile(outputDirectory,'simulink-cache'), ...
        'CodeGenFolder',fullfile(outputDirectory,'simulink-codegen'),'createDir',true);
    functions=struct('straight',@runOncomingVehicleAvoidanceScenario, ...
        'circular',@runCircularCenterlineStraightTargetAvoidanceScenario, ...
        'sCurve',@runVaryingCurvatureStraightTargetAvoidanceScenario);
    summary=struct([]);
    for weight=weights
        for scenario=scenarios
            name=scenario+"_w"+string(weight)+"_t"+string(duration);
            filename=fullfile(outputDirectory,name+'.mat');
            assert(~isfile(filename),'Refusing to overwrite an existing experiment.');
            fprintf('\nBEGIN %s\n',name);
            override=struct('jointCertificate',struct('inputDeviationWeight',weight));
            runScenario=functions.(scenario);timer=tic;
            result=runScenario(Duration=duration,ReferenceSpeed=10,TargetSpeed=10, ...
                RecoveryWindow=2,ControllerConfiguration=override, ...
                Plot=false,Report=false,Progress=true);
            elapsed=toc(timer);
            save(filename,'result','weight','scenario','duration','elapsed','-v7.3');
            input=cell2mat(cellfun(@(c)c.actuatorInput,result.command.',UniformOutput=false));
            if isempty(input),input=nan(2,1);end
            row=struct('name',name,'weight',weight,'requestedSeconds',duration, ...
                'completed',result.metrics.controllerCompletedScenario, ...
                'failureTime',result.failure.time,'failureIdentifier',string(result.failure.identifier), ...
                'collisionFree',result.avoidance.collisionFree, ...
                'minimumSeparation',result.avoidance.minimumControlledSeparatingAxisMargin, ...
                'passedTarget',result.avoidance.passedTarget,'recoveredCruise',result.avoidance.recoveredCruise, ...
                'maxSteeringRad',max(abs(input(1,:)),[],'omitnan'), ...
                'maxBrakingRatio',max(abs(input(2,:)),[],'omitnan'), ...
                'controllerMedianMs',1000*median(result.runtime.controllerSeconds), ...
                'controllerP95Ms',1000*prctile(result.runtime.controllerSeconds,95), ...
                'controllerMaxMs',1000*max(result.runtime.controllerSeconds), ...
                'wallSeconds',elapsed);
            summary=[summary;row]; %#ok<AGROW>
            writetable(struct2table(summary),fullfile(outputDirectory,'summary.csv'));
            fprintf('END %s: completed=%d failure=%.3f %s\n', ...
                name,row.completed,row.failureTime,row.failureIdentifier);
        end
    end
end
