function summary=runJointSupportCertificateValidation(options)
%runJointSupportCertificateValidation Paired offline admission and continuation.
% Raw MAT traces are written only to the caller's explicit output directory.
% Timings include admission and are observations, not deadline guarantees.
    arguments
        options.OutputDirectory (1,1) string
        options.SampleCount (1,1) double {mustBeInteger,mustBePositive} = 120
        options.Curvatures (1,:) double {mustBeFinite} = [0,.01,-.01]
        options.Scenarios (1,:) string = ["stationary","oncoming","crossing"]
        options.Methods (1,:) string = ["fixedNormal","jointSupport"]
    end
    if ~isfolder(options.OutputDirectory),mkdir(options.OutputDirectory);end
    originalThreads=maxNumCompThreads(1);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
    summary=struct('matlabVersion',string(version),'seed',20260912,'sampleTime',.1, ...
        'sampleCount',options.SampleCount,'deadlineSeconds',30,'searchTimeLimitSeconds',30, ...
        'scope',"Exact sampled affine plant, exact sensing, no road boundaries; offline algorithm study", ...
        'trials',{{}});
    for curvature=options.Curvatures
        for scenario=options.Scenarios
            for method=options.Methods
                directory=fullfile(options.OutputDirectory,sprintf('%s-%s-%g',method,scenario,curvature));
                try
                    result=runExactStateRecursiveFeasibilityScenario(Scenario=scenario, ...
                        RoadCurvature=curvature,SampleCount=options.SampleCount, ...
                        CertificateMethod=method,DeadlineSeconds=30,SearchTimeLimitSeconds=30, ...
                        OutputDirectory=directory);
                catch exception
                    file=fullfile(directory,scenario+"-exact-state.mat");
                    if ~isfile(file),rethrow(exception);end
                    saved=load(file,'report');result=saved.report;
                end
                trial=struct('method',method,'scenario',scenario,'curvature',curvature, ...
                    'completed',result.completed,'sampledClearancePassed',result.passed, ...
                    'executedHolds',result.executedHolds,'minimumNodeSeparationMargin',result.minimumNodeSeparationMargin, ...
                    'minimumSampledSeparationMargin',result.minimumSampledSeparationMargin, ...
                    'maximumJointViolation',max(result.jointSeparationViolation,[],'omitmissing'), ...
                    'maximumShiftedJointViolation',max(result.shiftedJointSeparationViolation,[],'omitmissing'), ...
                    'restorationSolves',sum(result.restorationSolverCallCount), ...
                    'maximumConicCalls',max(result.solverCallCount), ...
                    'maximumFrameSeconds',result.runtime.maximumSeconds,'medianFrameSeconds',result.runtime.medianSeconds, ...
                    'allIssuedCommandsCertified',all(result.hardCertificateVerified), ...
                    'confirmedRelease',any(result.confirmedRelease),'finalTrackingError',result.trackingError(:,end), ...
                    'failureTime',result.failureTime,'failureIdentifier',result.failureIdentifier, ...
                    'failureMessage',result.failureMessage,'artifact',directory);
                summary.trials{end+1}=trial;
                file=fopen(fullfile(options.OutputDirectory,'summary.json'),'w');assert(file>=0);
                fprintf(file,'%s\n',jsonencode(summary,PrettyPrint=true));fclose(file);
                fprintf('%s %s k=%g: completed=%d, holds=%d, node=%g, sampled=%g\n', ...
                    method,scenario,curvature,trial.completed,trial.executedHolds, ...
                    trial.minimumNodeSeparationMargin,trial.minimumSampledSeparationMargin);
            end
        end
    end
end
