function report = runNonlinearPredictiveSafetyValidation(options)
%runNonlinearPredictiveSafetyValidation Deterministic nonlinear closed-loop audit.
% A tight ode45 replay checks each issued hold independently of the affine prediction.
% The audit is offline evidence; it is not an execution admission layer.
% A positive RecoveryDwellSeconds enables sampled nominal-recovery stopping.
% Frames is a cumulative observation cap, including when resuming a saved
% continuation. A completed duration is distinct from confirmed recovery.
    arguments
        options.Frames (1,1) double {mustBeInteger,mustBePositive} = 8
        options.Scenarios (1,:) string = ["recovery","oncoming","circular","turningTarget"]
        options.OutputFile (1,1) string = ""
        options.ControllerConfiguration (1,1) struct = struct('referenceSpeed',8, ...
            'controller',struct('horizonSteps',8))
        options.StateTransition (1,1) string {mustBeMember(options.StateTransition,["ode45","nominalRk4"])} = "ode45"
        options.RequireCollisionThreat (1,1) logical = false
        options.RecoveryDwellSeconds (1,1) double {mustBeNonnegative,mustBeFinite} = 0
        options.RecoveryMinimumSeconds (1,1) double {mustBeNonnegative,mustBeFinite} = 0
        options.RecoveryTolerances (5,1) double {mustBePositive,mustBeFinite} = [.1;pi/180;.1;.05;.01]
        options.ContinuationFile (1,1) string = ""
        options.ResumeFrom (1,1) string = ""
    end
    assert((strlength(options.ContinuationFile)==0 && strlength(options.ResumeFrom)==0) ...
        || isscalar(options.Scenarios),'Continuation files require exactly one scenario.');
    root=fileparts(fileparts(mfilename('fullpath')));addpath(fullfile(root,'controller'),fullfile(root,'config'));
    results=cell(1,numel(options.Scenarios));
    for index=1:numel(options.Scenarios)
        name=options.Scenarios(index);
        [ego,target,road,cfg,initialTarget]=localFixture(name,options.ControllerConfiguration);prior=[];
        baseline=givenPathCollisionBaseline(road,initialTarget,cfg,options.Frames*cfg.controller.sampleTime);
        if options.RequireCollisionThreat && (~baseline.collisionDetected || baseline.initialClearanceMeters<=0)
            error('runNonlinearPredictiveSafetyValidation:notCollisionThreat', ...
                'Scenario %s must start separated and collide under given-path constant-speed cruise.',name);
        end
        frames=0;minimumClearance=Inf;minimumRoadMargin=Inf;maximumSeconds=0;failure="";
        maximumDeviation=0;
        firstClf=NaN;lastClf=NaN;maximumSlack=0;maxHorizon=0;warmStartedFrames=0;finalError=[];
        trace=struct([]);failedFrameSeconds=NaN;failureTime=NaN;passedTarget=false;
        recovery=struct('enabled',options.RecoveryDwellSeconds>0,'recovered',false, ...
            'tolerances',options.RecoveryTolerances,'errorOrder', ...
            ["lateralMeters","headingRadians","speedMetersPerSecond","lateralVelocityMetersPerSecond","yawRateRadiansPerSecond"], ...
            'dwellSeconds',options.RecoveryDwellSeconds,'minimumTimeSeconds',options.RecoveryMinimumSeconds, ...
            'entryTimeSeconds',NaN,'confirmationTimeSeconds',NaN);
        % A recovery dwell must follow the prescribed encounter, rather than
        % an arbitrary elapsed duration or the initially nominal state.
        if options.RequireCollisionThreat
            recovery.minimumTimeSeconds=max(recovery.minimumTimeSeconds,baseline.lastCollisionSeconds);
        end
        recoveryStart=NaN;
        if strlength(options.ResumeFrom)>0
            saved=load(options.ResumeFrom,'continuation');saved=saved.continuation;r=saved.result;
            assert(isequaln(r.configuration,cfg) && r.scenario==name ...
                && saved.stateTransition==options.StateTransition ...
                && saved.prior.version==71, ...
                'Continuation scenario, configuration and transition must match.');
            assert(isequaln(saved.recoveryOptions,recovery),'Recovery settings must match.');
            assert(strlength(r.failure)==0 && ~r.recovery.recovered && r.executedFrames<options.Frames, ...
                'Only an unfinished, successful duration can be extended.');
            ego=saved.ego;target=saved.target;prior=saved.prior;frames=r.executedFrames;
            minimumClearance=r.minimumReplayClearanceMeters;minimumRoadMargin=r.minimumReplayRoadMarginMeters;
            maximumSeconds=r.maximumFrameSeconds;maximumDeviation=r.maximumReplayLateralDeviationMeters;firstClf=r.initialClfValue;lastClf=r.finalClfValue;
            maximumSlack=r.maximumClfSlack;maxHorizon=r.maximumHorizonSteps;finalError=r.finalTransverseError;
            warmStartedFrames=r.warmStartedFrames;trace=r.trace;passedTarget=r.passedTarget;
            recoveryStart=saved.recoveryStart;
        end
        recoveryOptions=recovery;
        for frame=frames+1:options.Frames
            frameTimer=tic;
            try
                [command,~,problem,prior]=collisionAvoidanceController(ego,target,road,cfg,prior);
                frameSeconds=toc(frameTimer);
                maximumSeconds=max(maximumSeconds,frameSeconds);maxHorizon=max(maxHorizon,problem.metadata.horizonSteps);
                x=problem.model.initialState;input=command.actuatorInput;
                h=cfg.controller.sampleTime;
                [times,states]=ode45(@(~,state)nonlinearBicycleModel.derivative(state,input,cfg), ...
                    linspace(0,h,31),x,odeset('RelTol',1e-11,'AbsTol',1e-12));
                shape=[cfg.vehicle.length/2;cfg.vehicle.width/2;cfg.vehicle.rectangleOffset];
                for j=1:numel(times)
                    q=predictiveSafetyGeometry.targetFlow(problem.model.targetEpoch,problem.model.sampleIndex*h+times(j));
                    if ~isempty(q)
                        distance=predictiveSafetyGeometry.rectangle(states(j,1:3).',shape,q(1:3),q(8:11));
                        minimumClearance=min(minimumClearance,distance);
                    end
                    rotation=[cos(states(j,3)),-sin(states(j,3));sin(states(j,3)),cos(states(j,3))];
                    vertices=states(j,1:2).'+rotation*(shape(3:4)+shape(1:2).*[-1,1,1,-1;-1,-1,1,1]);
                    for vertex=1:4
                        projection=laneGeometry.project(vertices(:,vertex),problem.model.lane);
                        minimumRoadMargin=min([minimumRoadMargin;projection.lateralPosition+4;4-projection.lateralPosition]);
                    end
                end
                centerProjection=laneGeometry.project(states(:,1:2).',problem.model.lane);
                maximumDeviation=max(maximumDeviation,max(abs(centerProjection.lateralPosition)));
                if frame==1,firstClf=problem.metadata.clfInitialValue;end
                lastClf=problem.metadata.clfNextValue;maximumSlack=max(maximumSlack,problem.metadata.clfSlack);
                next=states(end,:).';
                if options.StateTransition=="nominalRk4",next=nonlinearBicycleModel.sample(x,input,cfg);end
                ego=localEgo(next,ego.stateTime+h,input);
                finalError=nonlinearBicycleModel.error(next,problem.model.lane,problem.model.nominalReference);
                warmStartedFrames=warmStartedFrames+(problem.metadata.search.initialization=="shiftedInputRollout");
                search=problem.metadata.search;
                entry=struct('time',ego.stateTime-h,'controllerSeconds',frameSeconds, ...
                    'horizonSteps',problem.metadata.horizonSteps,'source',search.source, ...
                    'solverCalls',search.solverCalls,'initialization',search.initialization, ...
                    'flowRestarted',search.flowRestarted,'initializationFailure',search.initializationFailure, ...
                    'linearizationCount',search.linearizationCount,'attempts',search.attempts, ...
                    'refinementCount',search.refinementCount,'predictionAgreement',problem.metadata.predictionAgreement, ...
                    'modelAgreementHistory',search.modelAgreementHistory,'modelAgreementSatisfied',search.modelAgreementSatisfied, ...
                    'lineSearchHistory',search.lineSearchHistory,'lineSearchSeconds',search.lineSearchSeconds, ...
                    'lineSearchTrials',search.lineSearchTrials,'acceptedStepFraction',search.acceptedStepFraction, ...
                    'slackCap',search.slackCap,'primaryOptimum',search.primaryOptimum, ...
                    'budgetSource',search.budgetSource,'firstSlackCap',search.firstSlackCap, ...
                    'budgetAnchorResidual',search.budgetAnchorResidual,'stageSlacks',problem.solution.stageSlacks, ...
                    'primaryLowerBound',search.primaryLowerBound,'selectedAttempt',search.selectedAttempt,'inputTrustScale',search.inputTrustScale, ...
                    'absoluteSampleIndex',problem.model.sampleIndex,'endpointIndex',problem.model.terminal.epochIndex, ...
                    'terminalPhaseMeters',problem.metadata.terminalPhaseMeters, ...
                    'terminalSeparationMargin',problem.metadata.terminalSeparationMargin, ...
                    'completionSteps',problem.metadata.completionSteps, ...
                    'optimizationReturned',search.returned,'optimizationConverged',search.converged,'terminationReason',search.terminationReason, ...
                    'solverStages',search.stages,'affineFeasibilityTolerance',cfg.solver.feasibilityTolerance, ...
                    'affineValidationPerformed',false,'nonlinearValidationPerformed',false, ...
                    'predictiveBarrierValue',problem.metadata.predictiveBarrierValue, ...
                    'hardResidual',problem.solution.hard,'clfSlack',problem.metadata.clfSlack, ...
                    'clfInitialValue',problem.metadata.clfInitialValue,'clfNextValue',problem.metadata.clfNextValue, ...
                    'clfFunction',problem.metadata.clfFunction,'clfRequiredDecrease',problem.metadata.clfRequiredDecrease, ...
                    'clfTieBound',problem.metadata.clfTieBound,'clfLocalModel',problem.metadata.clfLocalModel, ...
                    'clfStageAttempted',search.clfStageAttempted,'clfStageCompleted',search.clfStageCompleted, ...
                    'clfLowerBound',search.clfLowerBound,'clfInitialSlack',search.clfInitialSlack, ...
                    'state',x,'nextState',next,'input',input,'transverseError',finalError, ...
                    'auditTimes',times,'auditStates',states, ...
                    'predictionCollisionMargin',problem.metadata.minimumCollisionMargin);
                if isempty(trace),trace=entry;else,trace(end+1)=entry;end %#ok<AGROW>
                if ~isempty(target)
                    q=predictiveSafetyGeometry.targetFlow(problem.model.targetEpoch,(problem.model.sampleIndex+1)*h);
                    target=localTarget(q);
                    passedTarget=passedTarget || next(1)-q(1)>cfg.vehicle.length/2+q(8);
                end
                frames=frames+1;
                if recovery.enabled
                    inside=all(abs(finalError)<=options.RecoveryTolerances) ...
                        && ego.stateTime>=recovery.minimumTimeSeconds;
                    if ~inside,recoveryStart=NaN;
                    elseif isnan(recoveryStart),recoveryStart=ego.stateTime;
                    end
                    if inside && ego.stateTime-recoveryStart>=options.RecoveryDwellSeconds-1e-10
                        recovery.recovered=true;recovery.entryTimeSeconds=recoveryStart;
                        recovery.confirmationTimeSeconds=ego.stateTime;break;
                    end
                end
                if mod(frame,4)==0,fprintf('%s: %d/%d holds, last %.3f s, source %s\n', ...
                    name,frame,options.Frames,frameSeconds,search.source);end
                if recovery.enabled && mod(frame,100)==0
                    fprintf('Recovery at %.2f s: e = [%s], W = %.6g\n', ...
                        ego.stateTime,num2str(finalError.',' %.6g'),lastClf);
                end
            catch exception
                failedFrameSeconds=toc(frameTimer);failureTime=(frame-1)*cfg.controller.sampleTime;
                failure=string(exception.identifier)+": "+string(exception.message);break;
            end
        end
        seconds=[];solverCalls=0;
        if ~isempty(trace),seconds=[trace.controllerSeconds];solverCalls=sum([trace.solverCalls]);end
        later=seconds(2:end);
        firstSeconds=NaN;if ~isempty(seconds),firstSeconds=seconds(1);end
        medianLater=NaN;p95Later=NaN;
        if ~isempty(later),medianLater=median(later);p95Later=prctile(later,95);end
        results{index}=struct('scenario',name,'requestedFrames',options.Frames,'executedFrames',frames, ...
            'completed',frames==options.Frames || recovery.recovered,'recovery',recovery, ...
            'failure',failure,'minimumReplayClearanceMeters',minimumClearance, ...
            'minimumReplayRoadMarginMeters',minimumRoadMargin,'maximumFrameSeconds',maximumSeconds, ...
            'maximumHorizonSteps',maxHorizon,'initialClfValue',firstClf,'finalClfValue',lastClf, ...
            'maximumClfSlack',maximumSlack,'sampleTimeSeconds',cfg.controller.sampleTime,'randomSeed',[], ...
            'finalTransverseError',finalError,'warmStartedFrames',warmStartedFrames, ...
            'requiredClearanceMeters',cfg.collision.safetyMarginMeters, ...
            'roadConstraintsEnforced',false, ...
            'maximumReplayLateralDeviationMeters',maximumDeviation, ...
            'maximumLateralDeviationMeters',cfg.controller.maximumLateralDeviationMeters, ...
            'pathDeviationLimitSatisfied',maximumDeviation<=cfg.controller.maximumLateralDeviationMeters, ...
            'firstFrameSeconds',firstSeconds,'subsequentMedianSeconds',medianLater, ...
            'subsequentP95Seconds',p95Later,'deadlineMisses',nnz(seconds>cfg.controller.sampleTime), ...
            'failedFrameSeconds',failedFrameSeconds,'failureTime',failureTime,'passedTarget',passedTarget, ...
            'totalSolverCalls',solverCalls,'targetInitialState',initialTarget,'configuration',cfg, ...
            'baselineCruise',baseline,'trace',trace);
        if strlength(options.ContinuationFile)>0
            continuation=struct('ego',ego,'target',target,'prior',prior,'result',results{index}, ...
                'stateTransition',options.StateTransition, ...
                'recoveryOptions',recoveryOptions,'recoveryStart',recoveryStart);
            save(options.ContinuationFile,'continuation','-v7.3');
        end
        fprintf('%s: %d/%d frames, max %.3f s, failure %s\n',name,frames,options.Frames,maximumSeconds,failure);
    end
    report=struct('model',"nonlinear combined-slip Fiala; one constant-acceleration/constant-sideslip target", ...
        'targetStateOrder',["X","Y","psi","V","A","beta","lr","halfLength","halfWidth","offsetX","offsetY"], ...
        'scope',"two-stage affine PCBF/CLF with independent offline replay", ...
        'stateObservation',options.StateTransition+" ego successor; fixed target epoch; no observer, noise or delay", ...
        'replay',struct('integrator',"ode45",'relativeTolerance',1e-11, ...
            'absoluteTolerance',1e-12,'samplesPerHold',31),'results',[results{:}]);
    if strlength(options.OutputFile)>0
        file=fopen(options.OutputFile,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
        fprintf(file,'%s\n',jsonencode(report));
    end
end

function [ego,target,road,cfg,q]=localFixture(name,controllerConfiguration)
    cfg=collisionAvoidanceControllerConfig(controllerConfiguration);
    road=struct('centerline',[-100,0;1000,0],'lateralClearance',[4;4]);
    x=[0;0;0;cfg.referenceSpeed;0;0];target=[];q=[];lr=cfg.target.rearAxleDistance;
    switch name
        case "recovery",x(2)=.01;
        case "oncoming"
            q=[24;0;pi;8;0;0;lr;2.4;.95;0;0];
        case "circular"
            road=struct('referenceCurve',struct('origin',[0;0],'heading',0,'curvature',.005,'length',200), ...
                'lateralClearance',[4;4]);
            trim=nonlinearBicycleModel.cruise(cfg,.005);x=trim.state;x(1:2)=0;
        case "turningTarget"
            q=[24;0;pi;8;0;atan(-.1*lr);lr;2.4;.95;0;0];
        case "acceleratingTarget"
            q=[24;0;pi;8;1;0;lr;2.4;.95;0;0];
        case "acceleratingTurn"
            q=[24;0;pi;8;1;atan(-.1*lr);lr;2.4;.95;0;0];
        case "brakingTarget"
            q=[24;6;pi;2;-1;0;lr;2.4;.95;0;0];
        case {"headOn","acceleratingHeadOn","brakingLead","crossing","turningCrossing","curvedHeadOn","curvedCrossing"}
            [x,q,road,cfg]=collisionThreatScenario(name,controllerConfiguration);
        otherwise,error('runNonlinearPredictiveSafetyValidation:unknownScenario','Unknown scenario %s.',name);
    end
    if ~isempty(q),target=localTarget(q);end
    ego=localEgo(x,0,[0;0]);
end
function ego=localEgo(x,time,input)
    ego=struct('position',x(1:2),'yaw',x(3),'speed',x(4),'lateralVelocity',x(5),'yawRate',x(6), ...
        'stateTime',time,'heldActuatorInput',input);
end
function target=localTarget(q)
    direction=[cos(q(3)+q(6));sin(q(3)+q(6))];velocity=q(4)*direction;
    yawRate=q(4)*sin(q(6))/q(7);
    target=struct('targetPositionInertial',q(1:2),'targetVelocityInertial',velocity, ...
        'targetYawInertial',q(3),'targetYawRate',yawRate,'targetSideslip',q(6), ...
        'targetTangentialAcceleration',q(5),'targetRearAxleDistance',q(7), ...
        'targetAccelerationInertial',q(5)*direction+yawRate*[-velocity(2);velocity(1)], ...
        'targetLength',2*q(8),'targetWidth',2*q(9),'targetRectangleOffset',q(10:11));
end
