function result = runOnlineNrmmComplexManeuverScenario(varargin)
% runOnlineNrmmComplexManeuverScenario Exercise the cascaded NRMM observer.
%
% Open-loop research scenario for the cascaded measured-input observer in
% the transformed target coordinates [rho; q; s]. The ego truth is a
% jerk-rich maneuver with visibly nonzero jerk and yaw acceleration; the
% observer requires neither to vanish, which is the point of the cascade.
% The target truth satisfies the Sharma NRMM assumptions exactly (constant
% scalar acceleration, constant sideslip, kinematic single track with rear
% axle distance design.target.domain.rearAxleDistance). Synchronized GNSS
% position+velocity, IMU body-acceleration, gyroscope, and radar frames
% are generated at cfg.runtime.samplePeriod and fed through
% onlineNrmmTrackingRuntime.
%
% result = runOnlineNrmmComplexManeuverScenario(Name, Value) accepts:
%   Plot       - logical, default true; plotting is skipped automatically
%                in -batch sessions.
%   Report     - logical, default true.
%   Duration   - scenario length in seconds, default 12.0.
%   Seed       - noise seed, default 7 (used only with bounded noise).
%   NoiseModel - "none" (default) or "boundedUniform" within the
%                configured measurement bounds.
% All observer gains are solved from the declared domains, deterministic
% sensor bounds, and sample period; the scenario exposes no gain option.
%
% The observer is initialized from truth plus a documented offset (ego
% position +[1.0; -0.8] m, yaw +0.03 rad, body velocity +[0.5; -0.3] m/s,
% target [rho; q; s] +[1.0; -0.5; 0.5; 0.5; 0.2; -0.2]). The rho offset
% excites the deliberate high-gain peaking transient, so result.metrics
% reports RMSE values only after discarding the first
% metrics.transientDuration seconds. The cumulative certified
% speed-domain flag may be false because of that peaking while the
% final-interval flag recovers; both are reported honestly.

    options = localOptions(varargin{:});
    localAddProjectPaths();
    % Declared initial transient discarded before every RMSE evaluation.
    transientDuration = 2.0;                          % s

    cfg = nrmmTrackingConfig();
    design = synthesizeNrmmObserverGains(cfg);
    time = (0.0:cfg.runtime.samplePeriod:options.duration).';
    truth = localTruth(time, ...
        design.yaw.courseModel.rearAxleDistance, ...
        design.target.domain.rearAxleDistance);
    measurements = localMeasurements(truth, cfg, options);
    initial = localInitialEstimate(truth);
    estimate = localRunObserver(time, measurements, initial, cfg, design);
    metrics = localMetrics(truth, estimate, time, transientDuration);

    result = struct();
    result.config = cfg;
    result.design = design;
    result.truth = truth;
    result.measurements = measurements;
    result.initialEstimate = initial;
    result.estimate = estimate;
    result.metrics = metrics;

    if options.report
        localReport(metrics, design);
    end
    if options.plot && ~batchStartupOptionUsed
        localPlot(result);
    end
end

function truth = localTruth(time, ...
        egoRearAxleDistance, targetRearAxleDistance)
% localTruth Single-track ego maneuver and an exact Sharma-model target.
%
% Ego: sinusoidal speed and yaw-rate profiles, with betaE recovered from
% VE*sin(betaE)/lrE = psiEdot. Jerk and yaw acceleration are analytically
% nonzero. Target: VCdot = AC (constant), betaC constant, and
% psiCdot = VC*sin(betaC)/lrC, so [rho; q; s] follows the observer model.

    egoSpeed = 12.0+1.2*sin(0.25*time);
    egoSpeedDot = 0.30*cos(0.25*time);
    egoSpeedDdot = -0.075*sin(0.25*time);
    egoYawRate = 0.12*sin(0.35*time);
    egoYawAcceleration = 0.042*cos(0.35*time);
    egoYawJerk = -0.0147*sin(0.35*time);
    egoYaw = (0.12/0.35)*(1.0-cos(0.35*time));
    normalizedYawRate = egoRearAxleDistance*egoYawRate./egoSpeed;
    normalizedYawRateDerivative = egoRearAxleDistance ...
        .* (egoYawAcceleration.*egoSpeed-egoYawRate.*egoSpeedDot) ...
        ./ egoSpeed.^2;
    normalizedYawRateSecondDerivative = egoRearAxleDistance .* ( ...
        egoYawJerk./egoSpeed ...
        - 2.0*egoYawAcceleration.*egoSpeedDot./egoSpeed.^2 ...
        - egoYawRate.*egoSpeedDdot./egoSpeed.^2 ...
        + 2.0*egoYawRate.*egoSpeedDot.^2./egoSpeed.^3);
    egoSideslip = asin(normalizedYawRate);
    egoSingleTrackMismatch = egoYawRate ...
        - egoSpeed.*sin(egoSideslip)/egoRearAxleDistance;
    egoSideslipRate = normalizedYawRateDerivative ...
        ./ sqrt(1.0-normalizedYawRate.^2);
    egoSideslipAcceleration = normalizedYawRateSecondDerivative ...
            ./ sqrt(1.0-normalizedYawRate.^2) ...
        + normalizedYawRate.*normalizedYawRateDerivative.^2 ...
            ./ (1.0-normalizedYawRate.^2).^(3.0/2.0);
    egoCourse = egoYaw+egoSideslip;
    egoCourseRate = egoYawRate+egoSideslipRate;
    egoCourseAcceleration = ...
        egoYawAcceleration+egoSideslipAcceleration;
    egoVelocity = egoSpeed.*[cos(egoCourse), sin(egoCourse)];
    egoPosition = [cumtrapz(time, egoVelocity(:, 1)), ...
        cumtrapz(time, egoVelocity(:, 2))];
    egoSideslipDirection = [cos(egoSideslip), sin(egoSideslip)];
    egoSideslipNormal = [-sin(egoSideslip), cos(egoSideslip)];
    egoBodyAcceleration = egoSpeedDot.*egoSideslipDirection ...
        + (egoSpeed.*egoCourseRate).*egoSideslipNormal;
    egoAcceleration = localRotateRows(egoYaw, egoBodyAcceleration);
    egoCourseDirection = [cos(egoCourse), sin(egoCourse)];
    egoCourseNormal = [-sin(egoCourse), cos(egoCourse)];
    egoJerk = (egoSpeedDdot-egoSpeed.*egoCourseRate.^2) ...
            .* egoCourseDirection ...
        + (2.0*egoSpeedDot.*egoCourseRate ...
            + egoSpeed.*egoCourseAcceleration).*egoCourseNormal;

    % Sharma target parameters (all constant by assumption).
    targetInitialSpeed = 12.5;                        % m/s VC(0)
    targetScalarAcceleration = 0.08;                  % m/s^2 AC
    targetSideslip = 0.0064;                          % rad betaC
    targetInitialHeading = 0.10;                      % rad psiC(0)
    targetInitialPosition = [25.0, 4.0];              % m, inertial

    targetSpeed = targetInitialSpeed+targetScalarAcceleration*time;
    targetHeading = targetInitialHeading ...
        + (sin(targetSideslip)/targetRearAxleDistance) ...
        .*(targetInitialSpeed*time+0.5*targetScalarAcceleration*time.^2);
    targetCourse = targetHeading+targetSideslip;
    targetYawRate = targetSpeed*sin(targetSideslip) ...
        / targetRearAxleDistance;
    targetVelocity = targetSpeed.*[cos(targetCourse), sin(targetCourse)];
    targetPosition = targetInitialPosition ...
        + [cumtrapz(time, targetVelocity(:, 1)), ...
        cumtrapz(time, targetVelocity(:, 2))];
    % aC = AC*e(course) + VC*omegaC*J*e(course).
    targetAcceleration = ...
        targetScalarAcceleration*[cos(targetCourse), sin(targetCourse)] ...
        + (targetSpeed.*targetYawRate) ...
        .*[-sin(targetCourse), cos(targetCourse)];

    sampleCount = numel(time);
    targetTransformedState = zeros(sampleCount, 6);
    for sampleIdx = 1:sampleCount
        rotationTranspose = localRotation(egoYaw(sampleIdx)).';
        rho = rotationTranspose*(targetPosition(sampleIdx, :) ...
            - egoPosition(sampleIdx, :)).';
        q = rotationTranspose*targetVelocity(sampleIdx, :).';
        s = rotationTranspose*targetAcceleration(sampleIdx, :).';
        targetTransformedState(sampleIdx, :) = [rho; q; s].';
    end

    truth = struct( ...
        "time", time, ...
        "egoPosition", egoPosition, ...
        "egoVelocity", egoVelocity, ...
        "egoAcceleration", egoAcceleration, ...
        "egoJerk", egoJerk, ...
        "egoSpeed", egoSpeed, ...
        "egoYaw", egoYaw, ...
        "egoSideslip", egoSideslip, ...
        "egoCourse", egoCourse, ...
        "egoSingleTrackMismatch", egoSingleTrackMismatch, ...
        "egoYawRate", egoYawRate, ...
        "egoYawAcceleration", egoYawAcceleration, ...
        "egoBodyAcceleration", egoBodyAcceleration, ...
        "targetPosition", targetPosition, ...
        "targetVelocity", targetVelocity, ...
        "targetAcceleration", targetAcceleration, ...
        "targetSpeed", targetSpeed, ...
        "targetHeading", targetHeading, ...
        "targetCourse", targetCourse, ...
        "targetYawRate", targetYawRate, ...
        "targetTransformedState", targetTransformedState);
end

function measurements = localMeasurements(truth, cfg, options)
% localMeasurements Synchronized sensor frames from truth signals.
%
% Bounded-uniform noise respects the configured per-sensor bounds; the
% two-component channels are scaled by 1/sqrt(2) so the vector norm stays
% within the deterministic bound.

    sampleCount = numel(truth.time);
    switch options.noiseModel
        case "none"
            unitNoise = zeros(sampleCount, 9);
        case "boundeduniform"
            previousRandomState = rng;
            restoreRandomState = onCleanup( ...
                @() rng(previousRandomState));
            rng(options.seed, "twister");
            unitNoise = 2.0*rand(sampleCount, 9)-1.0;
        otherwise
            error("runOnlineNrmmComplexManeuverScenario:invalidNoiseModel", ...
                "NoiseModel must be 'none' or 'boundedUniform'.");
    end
    componentScale = 1.0/sqrt(2.0);
    gpsPositionBound = componentScale ...
        * cfg.measurement.gps.positionNoiseMaximum;
    gpsVelocityBound = componentScale ...
        * cfg.measurement.gps.velocityNoiseMaximum;
    imuBound = componentScale*cfg.measurement.imu.noiseMaximum;
    gyroscopeBound = cfg.measurement.gyroscope.noiseMaximum;
    radarBound = componentScale*cfg.measurement.radar.noiseMaximum;

    measurements = struct();
    measurements.gpsPosition = truth.egoPosition ...
        + gpsPositionBound*unitNoise(:, 1:2);
    measurements.gpsVelocity = truth.egoVelocity ...
        + gpsVelocityBound*unitNoise(:, 3:4);
    measurements.bodyAcceleration = truth.egoBodyAcceleration ...
        + imuBound*unitNoise(:, 5:6);
    measurements.yawRate = truth.egoYawRate+gyroscopeBound*unitNoise(:, 7);
    measurements.radarRelativePosition = ...
        truth.targetTransformedState(:, 1:2)+radarBound*unitNoise(:, 8:9);
end

function initial = localInitialEstimate(truth)
% localInitialEstimate Truth plus the documented initialization offsets.
%
% The target q offset norm is kept moderate (<= 1 m/s) so the high-gain
% peaking transient stays representative of a plausible track handover.

    initial = struct( ...
        "egoPosition", truth.egoPosition(1, :).'+[1.0; -0.8], ...
        "egoYaw", truth.egoYaw(1)+0.03, ...
        "egoBodyVelocity", [truth.egoSpeed(1); 0.0]+[0.5; -0.3], ...
        "targetState", truth.targetTransformedState(1, :).' ...
        + [1.0; -0.5; 0.5; 0.5; 0.2; -0.2]);
end

function estimate = localRunObserver(time, measurements, initial, cfg, design)
% localRunObserver Step the runtime over the synchronized frame sequence.

    runtimeOptions = struct( ...
        "initialTime", time(1), ...
        "targetCount", 1, ...
        "targetIdentifiers", "scenario-target-1", ...
        "egoInitialPosition", initial.egoPosition, ...
        "egoInitialYaw", initial.egoYaw, ...
        "egoInitialBodyVelocity", initial.egoBodyVelocity, ...
        "targetInitialState", initial.targetState);
    runtime = onlineNrmmTrackingRuntime( ...
        "initialize", cfg, runtimeOptions, design);

    sampleCount = numel(time);
    egoState = NaN(sampleCount, 6);
    egoYaw = NaN(sampleCount, 1);
    egoYawRate = NaN(sampleCount, 1);
    targetState = NaN(sampleCount, 6);
    targetVelocityInertial = NaN(sampleCount, 2);
    targetHeadingInertial = NaN(sampleCount, 1);
    targetSpeed = NaN(sampleCount, 1);
    targetYawRate = NaN(sampleCount, 1);

    % Sample 1 carries the initial estimate mapped through the same output
    % transformations the runtime applies.
    initialRotation = localRotation(initial.egoYaw);
    initialVelocity = initialRotation*initial.egoBodyVelocity;
    initialAcceleration = initialRotation ...
        *measurements.bodyAcceleration(1, :).';
    egoState(1, :) = [initial.egoPosition(1); initialVelocity(1); ...
        initialAcceleration(1); initial.egoPosition(2); ...
        initialVelocity(2); initialAcceleration(2)].';
    egoYaw(1) = initial.egoYaw;
    egoYawRate(1) = measurements.yawRate(1);
    targetState(1, :) = initial.targetState.';
    initialEgo = struct( ...
        "bodyVelocity", initial.egoBodyVelocity, ...
        "yawRate", measurements.yawRate(1));
    [~, initialTargetEstimate] = nrmmTargetTrackerDerivative( ...
        initial.targetState, initialEgo, design.target.domain);
    targetVelocityInertial(1, :) = ...
        (initialRotation*initialTargetEstimate.targetVelocity).';
    targetHeadingInertial(1) = localWrapToPi(initial.egoYaw ...
        + initialTargetEstimate.targetCourseAngleEgoFrame ...
        - initialTargetEstimate.targetSideslip);
    targetSpeed(1) = initialTargetEstimate.targetSpeed;
    targetYawRate(1) = initialTargetEstimate.targetYawRate;

    output = struct();
    for sampleIdx = 1:(sampleCount-1)
        frame = struct( ...
            "time", time(sampleIdx), ...
            "xGps", measurements.gpsPosition(sampleIdx, 1), ...
            "yGps", measurements.gpsPosition(sampleIdx, 2), ...
            "vxGps", measurements.gpsVelocity(sampleIdx, 1), ...
            "vyGps", measurements.gpsVelocity(sampleIdx, 2), ...
            "longitudinalAcceleration", ...
                measurements.bodyAcceleration(sampleIdx, 1), ...
            "lateralAcceleration", ...
                measurements.bodyAcceleration(sampleIdx, 2), ...
            "yawRateMeasured", measurements.yawRate(sampleIdx), ...
            "radarRelativePosition", ...
                measurements.radarRelativePosition(sampleIdx, :), ...
            "radarDetectionAvailable", true);
        [runtime, output] = onlineNrmmTrackingRuntime( ...
            "step", runtime, frame);
        targetOutput = output.targetEstimates(1);
        egoState(sampleIdx+1, :) = output.egoState.';
        egoYaw(sampleIdx+1) = output.egoYaw;
        egoYawRate(sampleIdx+1) = output.egoYawRate;
        targetState(sampleIdx+1, :) = output.targetStates(1, :);
        targetVelocityInertial(sampleIdx+1, :) = ...
            targetOutput.targetVelocityInertial.';
        targetHeadingInertial(sampleIdx+1) = ...
            targetOutput.targetHeadingInertial;
        targetSpeed(sampleIdx+1) = targetOutput.targetSpeed;
        targetYawRate(sampleIdx+1) = targetOutput.targetYawRate;
    end

    estimate = struct( ...
        "egoState", egoState, ...
        "egoYaw", egoYaw, ...
        "egoYawRate", egoYawRate, ...
        "targetState", targetState, ...
        "targetVelocityInertial", targetVelocityInertial, ...
        "targetHeadingInertial", targetHeadingInertial, ...
        "targetSpeed", targetSpeed, ...
        "targetYawRate", targetYawRate, ...
        "finalOutput", output, ...
        "runtime", runtime);
end

function metrics = localMetrics(truth, estimate, time, transientDuration)
% localMetrics RMSE against truth after the declared transient window.

    evaluation = time >= transientDuration;
    finalOutput = estimate.finalOutput;
    metrics = struct();
    metrics.transientDuration = transientDuration;
    metrics.egoPositionRmse = localVectorRmse( ...
        estimate.egoState(:, [1, 4])-truth.egoPosition, evaluation);
    metrics.egoVelocityRmse = localVectorRmse( ...
        estimate.egoState(:, [2, 5])-truth.egoVelocity, evaluation);
    metrics.egoAccelerationRmse = localVectorRmse( ...
        estimate.egoState(:, [3, 6])-truth.egoAcceleration, evaluation);
    metrics.egoYawRmse = sqrt(mean(localWrapToPi( ...
        estimate.egoYaw(evaluation)-truth.egoYaw(evaluation)).^2));
    metrics.relativePositionRmse = localVectorRmse( ...
        estimate.targetState(:, 1:2) ...
        - truth.targetTransformedState(:, 1:2), evaluation);
    metrics.targetVelocityRmse = localVectorRmse( ...
        estimate.targetVelocityInertial-truth.targetVelocity, evaluation);
    metrics.targetAccelerationRmse = localVectorRmse( ...
        estimate.targetState(:, 5:6) ...
        - truth.targetTransformedState(:, 5:6), evaluation);
    metrics.targetHeadingRmse = sqrt(mean(localWrapToPi( ...
        estimate.targetHeadingInertial(evaluation) ...
        - truth.targetHeading(evaluation)).^2));
    metrics.allSamplesFinite = ...
        all(isfinite(estimate.egoState), "all") ...
        && all(isfinite(estimate.egoYaw), "all") ...
        && all(isfinite(estimate.egoYawRate), "all") ...
        && all(isfinite(estimate.targetState), "all") ...
        && all(isfinite(estimate.targetVelocityInertial), "all") ...
        && all(isfinite(estimate.targetHeadingInertial), "all");
    metrics.targetSpeedDomainValidCumulative = ...
        finalOutput.targetCertifiedSpeedDomainValid;
    metrics.targetSpeedDomainValidFinalInterval = ...
        finalOutput.targetCertifiedSpeedDomainValidThisInterval;
    metrics.operatingDomainValidCumulative = ...
        finalOutput.estimatedOperatingDomainValid;
    metrics.operatingDomainValidFinalInterval = ...
        finalOutput.estimatedOperatingDomainValidThisInterval;
    metrics.minimumReconstructedTargetSpeed = ...
        finalOutput.minimumReconstructedTargetSpeed;
    metrics.maximumAuditedRelativePosition = ...
        finalOutput.estimatedOperatingDomainAudit.maximumRelativePosition;
    metrics.domainViolationQuantities = unique( ...
        finalOutput.estimatedOperatingDomainAudit.violationQuantities, ...
        "stable");
end

function value = localVectorRmse(error, evaluation)
    magnitude = vecnorm(error, 2, 2);
    value = sqrt(mean(magnitude(evaluation).^2));
end

function localReport(metrics, design)
% localReport Print the synthesized design surface and the run metrics.

    fprintf("\nCascaded measured-input NRMM observer scenario\n");
    fprintf("  sample period: %.6g s\n", design.samplePeriod);
    fprintf("  solved yaw correction bandwidth kt: %.6g 1/s\n", ...
        design.yaw.correctionBandwidth);
    fprintf("  body-velocity gain kv and certified lambda_v: " ...
        + "%.6g 1/s, %.6g 1/s\n", ...
        design.velocity.gain, design.velocity.lambda);
    fprintf("  position gain kp: %.6g 1/s\n", design.position.gain);
    fprintf("  target shape / solved bandwidth / stability threshold: " ...
        + "%s / %.6g / %.6g 1/s\n", char(design.target.shape), ...
        design.target.bandwidth, ...
        design.target.lipschitzCertificate.minimumStabilityBandwidth);
    fprintf("  core comparison eigenvalues: %s 1/s\n", ...
        mat2str(real(eig(design.coreIss.matrix)).', 4));
    fprintf("  ultimate bounds: yaw %.4g rad, position %.4g m, " ...
        + "body velocity %.4g m/s\n", design.ultimateBounds.yaw, ...
        design.ultimateBounds.position, ...
        design.ultimateBounds.bodyVelocity);
    fprintf("  ultimate bounds: relative position %.4g m, target " ...
        + "velocity %.4g m/s, target acceleration %.4g m/s^2\n", ...
        design.ultimateBounds.relativePosition, ...
        design.ultimateBounds.targetVelocity, ...
        design.ultimateBounds.targetAcceleration);
    fprintf("  transient discarded before RMSE: %.3g s\n", ...
        metrics.transientDuration);
    fprintf("  ego position / velocity / acceleration RMSE: " ...
        + "%.4g m / %.4g m/s / %.4g m/s^2\n", metrics.egoPositionRmse, ...
        metrics.egoVelocityRmse, metrics.egoAccelerationRmse);
    fprintf("  ego yaw RMSE: %.4g rad\n", metrics.egoYawRmse);
    fprintf("  relative-position RMSE: %.4g m\n", ...
        metrics.relativePositionRmse);
    fprintf("  target velocity / acceleration RMSE: " ...
        + "%.4g m/s / %.4g m/s^2\n", metrics.targetVelocityRmse, ...
        metrics.targetAccelerationRmse);
    fprintf("  target heading RMSE: %.4g rad\n", ...
        metrics.targetHeadingRmse);
    fprintf("  all samples finite: %d\n", metrics.allSamplesFinite);
    fprintf("  certified speed domain valid (cumulative / final " ...
        + "interval): %d / %d\n", ...
        metrics.targetSpeedDomainValidCumulative, ...
        metrics.targetSpeedDomainValidFinalInterval);
    fprintf("  estimated operating domain valid (cumulative / final " ...
        + "interval): %d / %d\n", ...
        metrics.operatingDomainValidCumulative, ...
        metrics.operatingDomainValidFinalInterval);
    fprintf("  minimum reconstructed target speed: %.6g m/s\n", ...
        metrics.minimumReconstructedTargetSpeed);
    fprintf("  maximum audited relative position: %.6g m\n", ...
        metrics.maximumAuditedRelativePosition);
    if ~isempty(metrics.domainViolationQuantities)
        fprintf("  audited domain violations: %s\n", ...
            strjoin(metrics.domainViolationQuantities, ", "));
    end
end

function localPlot(result)
    figure(Name="Cascaded measured-input NRMM observer scenario");
    tiledlayout(2, 2);
    nexttile;
    plot(result.truth.egoPosition(:, 1), result.truth.egoPosition(:, 2), ...
        LineWidth=1.5);
    hold on;
    plot(result.truth.targetPosition(:, 1), ...
        result.truth.targetPosition(:, 2), LineWidth=1.5);
    axis equal;
    grid on;
    legend("ego", "target", Location="best");
    title("Truth trajectories");
    nexttile;
    plot(result.truth.time, result.estimate.egoState(:, [1, 4]) ...
        - result.truth.egoPosition);
    grid on;
    title("Ego position error (m)");
    nexttile;
    plot(result.truth.time, result.estimate.targetState(:, 1:2) ...
        - result.truth.targetTransformedState(:, 1:2));
    grid on;
    title("Relative-position (rho) error (m)");
    nexttile;
    plot(result.truth.time, result.estimate.targetVelocityInertial ...
        - result.truth.targetVelocity);
    grid on;
    title("Target inertial-velocity error (m/s)");
end

function rotated = localRotateRows(angle, vectors)
    rotated = [ ...
        cos(angle).*vectors(:, 1)-sin(angle).*vectors(:, 2), ...
        sin(angle).*vectors(:, 1)+cos(angle).*vectors(:, 2)];
end

function rotation = localRotation(angle)
    rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
end

function value = localWrapToPi(value)
    value = mod(value+pi, 2.0*pi)-pi;
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "Plot", true, ...
        @(x) islogical(x) && isscalar(x));
    addParameter(parser, "Report", true, ...
        @(x) islogical(x) && isscalar(x));
    addParameter(parser, "Seed", 7, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x));
    addParameter(parser, "Duration", 12.0, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0.0);
    addParameter(parser, "NoiseModel", "none", ...
        @(x) isstring(x) || ischar(x));
    parse(parser, varargin{:});
    options = struct( ...
        "plot", parser.Results.Plot, ...
        "report", parser.Results.Report, ...
        "seed", double(parser.Results.Seed), ...
        "duration", double(parser.Results.Duration), ...
        "noiseModel", lower(string(parser.Results.NoiseModel)));
end

function localAddProjectPaths()
    repoRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repoRoot, "config"));
    addpath(fullfile(repoRoot, "estimator"));
end
