function benchmark = runOnlineNrmmTrackingErrorBenchmark(varargin)
% runOnlineNrmmTrackingErrorBenchmark Quantify cascaded observer errors.
%
% Monte-Carlo RMSE benchmark for the cascaded measured-input NRMM observer
% in the transformed target coordinates [rho; q; s]. Each declared case
% fixes a synthetic maneuver, a measurement-error mode, an initialization
% mode, a sample rate, and optional configuration overrides on the
% nrmmTrackingConfig schema. Observer gains are synthesized per case with
% synthesizeNrmmObserverGains; synthesis failures are recorded through
% their exception identifier rather than aborting the benchmark.
%
% Measurement errors are seeded bounded-uniform draws within the
% configured deterministic bounds (GNSS position and velocity, IMU
% body acceleration, gyroscope, radar). Radar noise enters the target
% acceleration channel with an omega_T^3 innovation coefficient, so noisy
% cases legitimately show large s-channel RMSE values; they are reported
% honestly, not tuned away. Initialization is either "truth" or "offset"
% with fixed documented offsets (target rho +[1.0; -0.5] m,
% q +[0.5; 0.5] m/s, s +[0.2; -0.2] m/s^2, ego position +[1.0; -0.8] m,
% yaw +0.03 rad, body velocity +[0.5; -0.3] m/s). RMSE values exclude a
% burn-in interval; the relative-position peak covers the complete trial.
%
% benchmark = runOnlineNrmmTrackingErrorBenchmark(Name, Value) accepts
% Report (default true), Seed (default 17), Duration (default 12.0 s),
% MonteCarloRuns (default 5, noisy cases only), and BurnInFraction
% (default 0.25). Repeated runs with identical options are bit-identical.

    options = localOptions(varargin{:});
    localAddProjectPaths();
    definitions = localBenchmarkDefinitions();
    trialRecords = struct([]);
    representatives = repmat(struct( ...
        "caseName", "", ...
        "trial", struct()), numel(definitions), 1);

    for caseIdx = 1:numel(definitions)
        definition = definitions(caseIdx);
        cfg = nrmmTrackingConfig();
        cfg.runtime.samplePeriod = 1.0/definition.sampleRateHz;
        cfg = localApplyConfigOverrides(cfg, definition.configOverrides);
        observerDesign = struct();
        synthesisFailureIdentifier = "";
        try
            observerDesign = synthesizeNrmmObserverGains(cfg);
        catch exception
            synthesisFailureIdentifier = string(exception.identifier);
        end
        runCount = localRunCount(definition.noise, options.monteCarloRuns);
        for runIdx = 1:runCount
            seed = options.seed+1000*caseIdx+runIdx-1;
            if strlength(synthesisFailureIdentifier) > 0
                failureMetrics = localFailureMetrics();
                failureMetrics.truthWithinCertifiedDomain = ...
                    localDefinitionTruthWithinDomain( ...
                    definition, options, cfg);
                record = localTrialRecord(definition, seed, false, ...
                    synthesisFailureIdentifier, failureMetrics);
            else
                try
                    trial = localRunTrial( ...
                        definition, options, seed, cfg, observerDesign);
                    record = localTrialRecord( ...
                        definition, seed, true, "", trial.metrics);
                    if runIdx == 1
                        representatives(caseIdx).caseName = ...
                            definition.name;
                        representatives(caseIdx).trial = trial;
                    end
                catch exception
                    failureMetrics = localFailureMetrics();
                    failureMetrics.truthWithinCertifiedDomain = ...
                        localDefinitionTruthWithinDomain( ...
                        definition, options, cfg);
                    record = localTrialRecord(definition, seed, false, ...
                        string(exception.identifier), failureMetrics);
                end
            end
            if isempty(trialRecords)
                trialRecords = record;
            else
                trialRecords(end+1, 1) = record; %#ok<AGROW>
            end
        end
    end

    summaryRecords = repmat(localSummaryRecord( ...
        definitions(1), trialRecords(1)), numel(definitions), 1);
    for caseIdx = 1:numel(definitions)
        definition = definitions(caseIdx);
        selected = [trialRecords.caseName].' == definition.name;
        summaryRecords(caseIdx) = localSummaryRecord( ...
            definition, trialRecords(selected));
    end

    benchmark = struct();
    benchmark.options = options;
    benchmark.caseDefinitions = struct2table(definitions);
    benchmark.summary = struct2table(summaryRecords);
    benchmark.trials = struct2table(trialRecords);
    benchmark.representativeTrials = representatives;
    benchmark.metricWindow = struct( ...
        "rmseBurnInFraction", options.burnInFraction, ...
        "peakWindow", "complete trial");
    benchmark.scope = [ ...
        "sampled synthetic endpoint evaluation", ...
        "not a proof of the deterministic ultimate bounds"];

    if options.report
        localReport(benchmark);
    end
end

function definitions = localBenchmarkDefinitions()
% localBenchmarkDefinitions Declared benchmark cases.
%
% Sample rates are implementation-layer choices. Every case resolves the
% gains from its physical bounds; there are no shape or decay overrides.
% The final cases exercise automatic re-synthesis under a tighter target
% domain and larger radar or single-track uncertainty.

    noOverride = cell(0, 1);
    tightDomain = { ...
        {{'target', 'domain', 'speedMaximum'}, 15.0}; ...
        {{'target', 'domain', 'sideslipMaximum'}, 0.01}};
    largerRadarError = { ...
        {{'measurement', 'radar', 'noiseMaximum'}, 0.20}};
    largerCourseMismatch = { ...
        {{'ego', 'yaw', 'singleTrackYawRateMismatchMaximum'}, 0.04}};
    definitions = [ ...
        localDefinition("straight-clean-50Hz", ...
            "straight", "none", "truth", 50.0, noOverride); ...
        localDefinition("coupled-clean-50Hz", ...
            "coupled", "none", "truth", 50.0, noOverride); ...
        localDefinition("coupled-clean-offset-50Hz", ...
            "coupled", "none", "offset", 50.0, noOverride); ...
        localDefinition("coupled-noise-50Hz", ...
            "coupled", "boundedUniform", "truth", 50.0, noOverride); ...
        localDefinition("coupled-noise-offset-50Hz", ...
            "coupled", "boundedUniform", "offset", 50.0, noOverride); ...
        localDefinition("coupled-noise-tight-domain-25Hz", ...
            "coupled", "boundedUniform", "truth", 25.0, ...
            tightDomain); ...
        localDefinition("coupled-noise-larger-radar-error-50Hz", ...
            "coupled", "boundedUniform", "truth", 50.0, ...
            largerRadarError); ...
        localDefinition("coupled-noise-larger-course-mismatch-50Hz", ...
            "coupled", "boundedUniform", "truth", 50.0, ...
            largerCourseMismatch)];
end

function definition = localDefinition( ...
        name, maneuver, noise, initialization, sampleRateHz, ...
        configOverrides)
    definition = struct( ...
        "name", name, ...
        "maneuver", maneuver, ...
        "noise", noise, ...
        "initialization", initialization, ...
        "sampleRateHz", sampleRateHz, ...
        "configOverrides", {configOverrides});
end

function cfg = localApplyConfigOverrides(cfg, configOverrides)
% localApplyConfigOverrides Apply {path, value} overrides on the new schema.

    for overrideIdx = 1:numel(configOverrides)
        pathAndValue = configOverrides{overrideIdx};
        cfg = setfield(cfg, pathAndValue{1}{:}, pathAndValue{2});
    end
end

function runCount = localRunCount(noise, monteCarloRuns)
    if noise == "boundedUniform"
        runCount = monteCarloRuns;
    else
        runCount = 1;
    end
end

function trial = localRunTrial(definition, options, seed, cfg, observerDesign)
    time = localTimeGrid(options.duration, definition.sampleRateHz);
    truth = localTruth(time, definition.maneuver, ...
        cfg.ego.yaw.rearAxleDistance, ...
        cfg.target.domain.rearAxleDistance);
    measurements = localMeasurements(truth, cfg, definition.noise, seed);
    initial = localInitialEstimate(truth, definition.initialization);
    estimate = localRunObserver( ...
        time, measurements, initial, cfg, observerDesign);
    metrics = localMetrics( ...
        truth, estimate, time, cfg, options.burnInFraction);

    trial = struct( ...
        "seed", seed, ...
        "config", cfg, ...
        "observerDesign", observerDesign, ...
        "truth", truth, ...
        "measurements", measurements, ...
        "initialEstimate", initial, ...
        "estimate", estimate, ...
        "metrics", metrics);
end

function time = localTimeGrid(duration, sampleRateHz)
    sampleCount = floor(duration*sampleRateHz)+1;
    time = (0:(sampleCount-1)).'/sampleRateHz;
end

function within = localDefinitionTruthWithinDomain(definition, options, cfg)
    time = localTimeGrid(options.duration, definition.sampleRateHz);
    truth = localTruth(time, definition.maneuver, ...
        cfg.ego.yaw.rearAxleDistance, ...
        cfg.target.domain.rearAxleDistance);
    within = localTruthWithinDomain(truth, cfg);
end

function truth = localTruth(time, maneuver, ...
        egoRearAxleDistance, targetRearAxleDistance)
% localTruth Synthetic single-track ego and exact Sharma-model target.
%
% The ego satisfies psiEdot = VE*sin(betaE)/lrE exactly. The target obeys
% VCdot = AC (constant), betaC constant, and
% psiCdot = VC*sin(betaC)/lrC, so [rho; q; s] follows the observer model
% exactly up to the quadrature of the truth positions.

    switch maneuver
        case "straight"
            egoSpeed = 12.0*ones(size(time));
            egoSpeedDot = zeros(size(time));
            egoYawRate = zeros(size(time));
            egoYawAcceleration = zeros(size(time));
            egoYaw = zeros(size(time));
            target = struct( ...
                "initialSpeed", 12.4, ...
                "scalarAcceleration", 0.0, ...
                "sideslip", 0.0, ...
                "initialHeading", 0.0, ...
                "initialPosition", [30.0, 3.0]);
        case "coupled"
            egoSpeed = 12.0+1.2*sin(0.25*time);
            egoSpeedDot = 0.30*cos(0.25*time);
            egoYawRate = 0.12*sin(0.35*time);
            egoYawAcceleration = 0.042*cos(0.35*time);
            egoYaw = (0.12/0.35)*(1.0-cos(0.35*time));
            target = struct( ...
                "initialSpeed", 12.5, ...
                "scalarAcceleration", 0.08, ...
                "sideslip", 0.0064, ...
                "initialHeading", 0.10, ...
                "initialPosition", [25.0, 4.0]);
        otherwise
            error("runOnlineNrmmTrackingErrorBenchmark:invalidManeuver", ...
                "Unsupported maneuver '%s'.", maneuver);
    end

    normalizedYawRate = egoRearAxleDistance*egoYawRate./egoSpeed;
    normalizedYawRateDerivative = egoRearAxleDistance ...
        .* (egoYawAcceleration.*egoSpeed-egoYawRate.*egoSpeedDot) ...
        ./ egoSpeed.^2;
    egoSideslip = asin(normalizedYawRate);
    egoSideslipRate = normalizedYawRateDerivative ...
        ./ sqrt(1.0-normalizedYawRate.^2);
    egoCourse = egoYaw+egoSideslip;
    egoCourseRate = egoYawRate+egoSideslipRate;
    egoVelocity = egoSpeed.*[cos(egoCourse), sin(egoCourse)];
    egoPosition = [cumtrapz(time, egoVelocity(:, 1)), ...
        cumtrapz(time, egoVelocity(:, 2))];
    egoSideslipDirection = [cos(egoSideslip), sin(egoSideslip)];
    egoSideslipNormal = [-sin(egoSideslip), cos(egoSideslip)];
    egoBodyAcceleration = egoSpeedDot.*egoSideslipDirection ...
        + (egoSpeed.*egoCourseRate).*egoSideslipNormal;
    egoAcceleration = localRotateRows(egoYaw, egoBodyAcceleration);
    egoSingleTrackMismatch = egoYawRate ...
        - egoSpeed.*sin(egoSideslip)/egoRearAxleDistance;

    targetSpeed = target.initialSpeed+target.scalarAcceleration*time;
    targetHeading = target.initialHeading ...
        + (sin(target.sideslip)/targetRearAxleDistance) ...
        .*(target.initialSpeed*time ...
        + 0.5*target.scalarAcceleration*time.^2);
    targetCourse = targetHeading+target.sideslip;
    targetYawRate = targetSpeed*sin(target.sideslip) ...
        / targetRearAxleDistance;
    targetVelocity = targetSpeed.*[cos(targetCourse), sin(targetCourse)];
    targetPosition = target.initialPosition ...
        + [cumtrapz(time, targetVelocity(:, 1)), ...
        cumtrapz(time, targetVelocity(:, 2))];
    targetAcceleration = ...
        target.scalarAcceleration*[cos(targetCourse), sin(targetCourse)] ...
        + (targetSpeed.*targetYawRate) ...
        .*[-sin(targetCourse), cos(targetCourse)];

    sampleCount = numel(time);
    targetTransformedState = zeros(sampleCount, 6);
    for sampleIdx = 1:sampleCount
        rotationTranspose = localRotation(egoYaw(sampleIdx)).';
        rho = rotationTranspose*(targetPosition(sampleIdx, :) ...
            - egoPosition(sampleIdx, :)).';
        q = rotationTranspose*targetVelocity(sampleIdx, :).';
        s = rotationTranspose*targetAcceleration(sampleIdx, :).';
        targetTransformedState(sampleIdx, :) = [rho; q; s].';
    end

    truth = struct( ...
        "time", time, ...
        "egoPosition", egoPosition, ...
        "egoVelocity", egoVelocity, ...
        "egoAcceleration", egoAcceleration, ...
        "egoSpeed", egoSpeed, ...
        "egoYaw", egoYaw, ...
        "egoYawRate", egoYawRate, ...
        "egoSideslip", egoSideslip, ...
        "egoCourse", egoCourse, ...
        "egoSingleTrackMismatch", egoSingleTrackMismatch, ...
        "egoBodyAcceleration", egoBodyAcceleration, ...
        "targetPosition", targetPosition, ...
        "targetVelocity", targetVelocity, ...
        "targetAcceleration", targetAcceleration, ...
        "targetSpeed", targetSpeed, ...
        "targetHeading", targetHeading, ...
        "targetCourse", targetCourse, ...
        "targetYawRate", targetYawRate, ...
        "targetTransformedState", targetTransformedState);
end

function measurements = localMeasurements(truth, cfg, noise, seed)
% localMeasurements Seeded bounded-uniform noise within configured bounds.
%
% Two-component channels are scaled by 1/sqrt(2) so the vector norm stays
% within the deterministic bound. The random state is restored so the
% benchmark leaves the global generator untouched.

    sampleCount = numel(truth.time);
    switch noise
        case "none"
            unitNoise = zeros(sampleCount, 9);
        case "boundedUniform"
            previousRandomState = rng;
            restoreRandomState = onCleanup( ...
                @() rng(previousRandomState));
            rng(seed, "twister");
            unitNoise = 2.0*rand(sampleCount, 9)-1.0;
        otherwise
            error("runOnlineNrmmTrackingErrorBenchmark:invalidNoiseMode", ...
                "Unsupported noise mode '%s'.", noise);
    end
    componentScale = 1.0/sqrt(2.0);
    gpsPositionBound = componentScale ...
        * cfg.measurement.gps.positionNoiseMaximum;
    gpsVelocityBound = componentScale ...
        * cfg.measurement.gps.velocityNoiseMaximum;
    imuBound = componentScale*cfg.measurement.imu.noiseMaximum;
    gyroscopeBound = cfg.measurement.gyroscope.noiseMaximum;
    radarBound = componentScale*cfg.measurement.radar.noiseMaximum;

    measurements = struct();
    measurements.gpsPosition = truth.egoPosition ...
        + gpsPositionBound*unitNoise(:, 1:2);
    measurements.gpsVelocity = truth.egoVelocity ...
        + gpsVelocityBound*unitNoise(:, 3:4);
    measurements.bodyAcceleration = truth.egoBodyAcceleration ...
        + imuBound*unitNoise(:, 5:6);
    measurements.yawRate = truth.egoYawRate+gyroscopeBound*unitNoise(:, 7);
    measurements.radarRelativePosition = ...
        truth.targetTransformedState(:, 1:2)+radarBound*unitNoise(:, 8:9);
end

function initial = localInitialEstimate(truth, initialization)
% localInitialEstimate Truth or truth-plus-fixed-offset initialization.

    initial = struct( ...
        "egoPosition", truth.egoPosition(1, :).', ...
        "egoYaw", truth.egoYaw(1), ...
        "egoBodyVelocity", [truth.egoSpeed(1); 0.0], ...
        "targetState", truth.targetTransformedState(1, :).');
    switch initialization
        case "truth"
            % Exact truth initialization; no perturbation.
        case "offset"
            initial.egoPosition = initial.egoPosition+[1.0; -0.8];
            initial.egoYaw = initial.egoYaw+0.03;
            initial.egoBodyVelocity = ...
                initial.egoBodyVelocity+[0.5; -0.3];
            initial.targetState = initial.targetState ...
                + [1.0; -0.5; 0.5; 0.5; 0.2; -0.2];
        otherwise
            error("runOnlineNrmmTrackingErrorBenchmark:" ...
                + "invalidInitialization", ...
                "Unsupported initialization '%s'.", initialization);
    end
end

function estimate = localRunObserver( ...
        time, measurements, initial, cfg, observerDesign)
% localRunObserver Step the runtime over the synchronized frame sequence.

    runtimeOptions = struct( ...
        "initialTime", time(1), ...
        "targetCount", 1, ...
        "targetIdentifiers", "benchmark-target-1", ...
        "egoInitialPosition", initial.egoPosition, ...
        "egoInitialYaw", initial.egoYaw, ...
        "egoInitialBodyVelocity", initial.egoBodyVelocity, ...
        "targetInitialState", initial.targetState);
    runtime = onlineNrmmTrackingRuntime( ...
        "initialize", cfg, runtimeOptions, observerDesign);

    sampleCount = numel(time);
    egoState = NaN(sampleCount, 6);
    egoYaw = NaN(sampleCount, 1);
    targetState = NaN(sampleCount, 6);
    targetPositionInertial = NaN(sampleCount, 2);
    targetVelocityInertial = NaN(sampleCount, 2);
    targetSpeed = NaN(sampleCount, 1);
    targetYawRate = NaN(sampleCount, 1);

    % Sample 1 carries the initial estimate mapped through the same output
    % transformations the runtime applies; the target quantities come from
    % the direct measured-input tracker map.
    initialRotation = localRotation(initial.egoYaw);
    initialVelocity = initialRotation*initial.egoBodyVelocity;
    initialAcceleration = initialRotation ...
        *measurements.bodyAcceleration(1, :).';
    egoState(1, :) = [initial.egoPosition(1); initialVelocity(1); ...
        initialAcceleration(1); initial.egoPosition(2); ...
        initialVelocity(2); initialAcceleration(2)].';
    egoYaw(1) = initial.egoYaw;
    targetState(1, :) = initial.targetState.';
    initialEgo = struct( ...
        "bodyVelocity", initial.egoBodyVelocity, ...
        "yawRate", measurements.yawRate(1));
    [~, initialTargetEstimate] = nrmmTargetTrackerDerivative( ...
        initial.targetState, initialEgo, observerDesign.target.domain);
    targetPositionInertial(1, :) = (initial.egoPosition ...
        + initialRotation*initialTargetEstimate.relativePosition).';
    targetVelocityInertial(1, :) = ...
        (initialRotation*initialTargetEstimate.targetVelocity).';
    targetSpeed(1) = initialTargetEstimate.targetSpeed;
    targetYawRate(1) = initialTargetEstimate.targetYawRate;

    output = struct();
    for sampleIdx = 1:(sampleCount-1)
        frame = struct( ...
            "time", time(sampleIdx), ...
            "xGps", measurements.gpsPosition(sampleIdx, 1), ...
            "yGps", measurements.gpsPosition(sampleIdx, 2), ...
            "vxGps", measurements.gpsVelocity(sampleIdx, 1), ...
            "vyGps", measurements.gpsVelocity(sampleIdx, 2), ...
            "longitudinalAcceleration", ...
                measurements.bodyAcceleration(sampleIdx, 1), ...
            "lateralAcceleration", ...
                measurements.bodyAcceleration(sampleIdx, 2), ...
            "yawRateMeasured", measurements.yawRate(sampleIdx), ...
            "radarRelativePosition", ...
                measurements.radarRelativePosition(sampleIdx, :), ...
            "radarDetectionAvailable", true);
        [runtime, output] = onlineNrmmTrackingRuntime( ...
            "step", runtime, frame);
        targetOutput = output.targetEstimates(1);
        egoState(sampleIdx+1, :) = output.egoState.';
        egoYaw(sampleIdx+1) = output.egoYaw;
        targetState(sampleIdx+1, :) = output.targetStates(1, :);
        targetPositionInertial(sampleIdx+1, :) = ...
            targetOutput.targetPositionInertial.';
        targetVelocityInertial(sampleIdx+1, :) = ...
            targetOutput.targetVelocityInertial.';
        targetSpeed(sampleIdx+1) = targetOutput.targetSpeed;
        targetYawRate(sampleIdx+1) = targetOutput.targetYawRate;
    end

    estimate = struct( ...
        "egoState", egoState, ...
        "egoYaw", egoYaw, ...
        "targetState", targetState, ...
        "targetPositionInertial", targetPositionInertial, ...
        "targetVelocityInertial", targetVelocityInertial, ...
        "targetSpeed", targetSpeed, ...
        "targetYawRate", targetYawRate, ...
        "finalOutput", output, ...
        "runtime", runtime);
end

function metrics = localMetrics(truth, estimate, time, cfg, burnInFraction)
% localMetrics RMSE after burn-in plus complete-trial peaks and audits.

    evaluation = time >= burnInFraction*time(end);
    finalOutput = estimate.finalOutput;
    relativePositionError = vecnorm(estimate.targetState(:, 1:2) ...
        - truth.targetTransformedState(:, 1:2), 2, 2);

    metrics = struct();
    metrics.allEstimatesFinite = ...
        all(isfinite(estimate.egoState), "all") ...
        && all(isfinite(estimate.egoYaw), "all") ...
        && all(isfinite(estimate.targetState), "all") ...
        && all(isfinite(estimate.targetPositionInertial), "all") ...
        && all(isfinite(estimate.targetVelocityInertial), "all");
    metrics.truthWithinCertifiedDomain = ...
        localTruthWithinDomain(truth, cfg);
    metrics.egoPositionRmseM = localVectorRmse( ...
        estimate.egoState(:, [1, 4])-truth.egoPosition, evaluation);
    metrics.egoVelocityRmseMps = localVectorRmse( ...
        estimate.egoState(:, [2, 5])-truth.egoVelocity, evaluation);
    metrics.egoAccelerationRmseMps2 = localVectorRmse( ...
        estimate.egoState(:, [3, 6])-truth.egoAcceleration, evaluation);
    metrics.egoYawRmseDeg = rad2deg(sqrt(mean(localWrapToPi( ...
        estimate.egoYaw(evaluation)-truth.egoYaw(evaluation)).^2)));
    metrics.relativePositionRmseM = ...
        sqrt(mean(relativePositionError(evaluation).^2));
    metrics.relativePositionPeakM = max(relativePositionError);
    metrics.targetVelocityEgoRmseMps = localVectorRmse( ...
        estimate.targetState(:, 3:4) ...
        - truth.targetTransformedState(:, 3:4), evaluation);
    metrics.targetAccelerationEgoRmseMps2 = localVectorRmse( ...
        estimate.targetState(:, 5:6) ...
        - truth.targetTransformedState(:, 5:6), evaluation);
    metrics.targetInertialPositionRmseM = localVectorRmse( ...
        estimate.targetPositionInertial-truth.targetPosition, evaluation);
    metrics.targetInertialVelocityRmseMps = localVectorRmse( ...
        estimate.targetVelocityInertial-truth.targetVelocity, evaluation);
    metrics.minimumEstimatedTargetSpeedMps = ...
        finalOutput.minimumReconstructedTargetSpeed;
    metrics.targetSpeedDomainValidCumulative = ...
        finalOutput.targetCertifiedSpeedDomainValid;
    metrics.targetSpeedDomainValidFinalInterval = ...
        finalOutput.targetCertifiedSpeedDomainValidThisInterval;
    metrics.operatingDomainValidCumulative = ...
        finalOutput.estimatedOperatingDomainValid;
    metrics.operatingDomainValidFinalInterval = ...
        finalOutput.estimatedOperatingDomainValidThisInterval;
    metrics.maximumAuditedRelativePositionM = ...
        finalOutput.estimatedOperatingDomainAudit.maximumRelativePosition;
end

function metrics = localFailureMetrics()
    metrics = struct( ...
        "allEstimatesFinite", false, ...
        "truthWithinCertifiedDomain", false, ...
        "egoPositionRmseM", Inf, ...
        "egoVelocityRmseMps", Inf, ...
        "egoAccelerationRmseMps2", Inf, ...
        "egoYawRmseDeg", Inf, ...
        "relativePositionRmseM", Inf, ...
        "relativePositionPeakM", Inf, ...
        "targetVelocityEgoRmseMps", Inf, ...
        "targetAccelerationEgoRmseMps2", Inf, ...
        "targetInertialPositionRmseM", Inf, ...
        "targetInertialVelocityRmseMps", Inf, ...
        "minimumEstimatedTargetSpeedMps", -Inf, ...
        "targetSpeedDomainValidCumulative", false, ...
        "targetSpeedDomainValidFinalInterval", false, ...
        "operatingDomainValidCumulative", false, ...
        "operatingDomainValidFinalInterval", false, ...
        "maximumAuditedRelativePositionM", Inf);
end

function within = localTruthWithinDomain(truth, cfg)
% localTruthWithinDomain Sampled truth check against the certified domain.
%
% Evaluated directly from the configuration so it stays available when
% gain synthesis fails; the derived target yaw-rate and acceleration-norm
% bounds repeat the closed forms in synthesizeNrmmObserverGains.

    targetDomain = cfg.target.domain;
    targetYawRateMaximum = targetDomain.speedMaximum ...
        * sin(targetDomain.sideslipMaximum)/targetDomain.rearAxleDistance;
    targetAccelerationNormBound = hypot( ...
        targetDomain.scalarAccelerationMaximum, ...
        targetDomain.speedMaximum*targetYawRateMaximum);
    tolerance = 1.0e-9;
    within = ...
        all(truth.egoSpeed <= cfg.ego.domain.speedMaximum+tolerance) ...
        && all(abs(truth.egoYawRate) ...
            <= cfg.ego.domain.yawRateMaximum+tolerance) ...
        && all(abs(truth.egoSideslip) ...
            <= cfg.ego.yaw.sideslipDomainMaximum+tolerance) ...
        && all(abs(truth.egoSingleTrackMismatch) ...
            <= cfg.ego.yaw.singleTrackYawRateMismatchMaximum+tolerance) ...
        && all(truth.targetSpeed ...
            >= targetDomain.speedMinimum-tolerance) ...
        && all(truth.targetSpeed ...
            <= targetDomain.speedMaximum+tolerance) ...
        && all(abs(truth.targetYawRate) ...
            <= targetYawRateMaximum+tolerance) ...
        && all(vecnorm(truth.targetAcceleration, 2, 2) ...
            <= targetAccelerationNormBound+tolerance) ...
        && all(vecnorm(truth.targetTransformedState(:, 1:2), 2, 2) ...
            <= targetDomain.relativePositionMaximum+tolerance);
end

function value = localVectorRmse(error, evaluation)
    magnitude = vecnorm(error, 2, 2);
    value = sqrt(mean(magnitude(evaluation).^2));
end

function record = localTrialRecord( ...
        definition, seed, completed, failureIdentifier, metrics)
% localTrialRecord Case labels followed by every trial metric field.

    record = struct( ...
        "caseName", definition.name, ...
        "maneuver", definition.maneuver, ...
        "noise", definition.noise, ...
        "initialization", definition.initialization, ...
        "sampleRateHz", definition.sampleRateHz, ...
        "seed", seed, ...
        "completed", completed, ...
        "failureIdentifier", failureIdentifier);
    for fieldName = string(fieldnames(metrics)).'
        record.(fieldName) = metrics.(fieldName);
    end
end

function summary = localSummaryRecord(definition, records)
    successful = [records.completed] & [records.allEstimatesFinite];
    successfulRecords = records(successful);
    failedRecords = records(~[records.completed]);
    failureIdentifiers = strings(0, 1);
    if ~isempty(failedRecords)
        failureIdentifiers = unique([failedRecords.failureIdentifier]);
    end
    summary = struct( ...
        "caseName", definition.name, ...
        "maneuver", definition.maneuver, ...
        "noise", definition.noise, ...
        "initialization", definition.initialization, ...
        "sampleRateHz", definition.sampleRateHz, ...
        "runCount", numel(records), ...
        "completedRunCount", sum([records.completed]), ...
        "failedRunCount", sum(~[records.completed]), ...
        "failureIdentifiers", strjoin(failureIdentifiers, "; "), ...
        "truthWithinCertifiedDomain", ...
            all([records.truthWithinCertifiedDomain]), ...
        "egoPositionRmseMeanM", localMeanMetric( ...
            successfulRecords, "egoPositionRmseM"), ...
        "egoVelocityRmseMeanMps", localMeanMetric( ...
            successfulRecords, "egoVelocityRmseMps"), ...
        "egoAccelerationRmseMeanMps2", localMeanMetric( ...
            successfulRecords, "egoAccelerationRmseMps2"), ...
        "egoYawRmseMeanDeg", localMeanMetric( ...
            successfulRecords, "egoYawRmseDeg"), ...
        "relativePositionRmseMeanM", localMeanMetric( ...
            successfulRecords, "relativePositionRmseM"), ...
        "relativePositionRmseWorstM", localMaximumMetric( ...
            successfulRecords, "relativePositionRmseM"), ...
        "relativePositionPeakWorstM", localMaximumMetric( ...
            successfulRecords, "relativePositionPeakM"), ...
        "targetVelocityEgoRmseMeanMps", localMeanMetric( ...
            successfulRecords, "targetVelocityEgoRmseMps"), ...
        "targetAccelerationEgoRmseMeanMps2", localMeanMetric( ...
            successfulRecords, "targetAccelerationEgoRmseMps2"), ...
        "targetAccelerationEgoRmseWorstMps2", localMaximumMetric( ...
            successfulRecords, "targetAccelerationEgoRmseMps2"), ...
        "targetInertialPositionRmseMeanM", localMeanMetric( ...
            successfulRecords, "targetInertialPositionRmseM"), ...
        "minimumEstimatedTargetSpeedWorstMps", localMinimumMetric( ...
            successfulRecords, "minimumEstimatedTargetSpeedMps"), ...
        "speedDomainValidCumulativeAll", isempty(successfulRecords) ...
            || all([successfulRecords.targetSpeedDomainValidCumulative]), ...
        "speedDomainValidFinalIntervalAll", isempty(successfulRecords) ...
            || all([ ...
            successfulRecords.targetSpeedDomainValidFinalInterval]));
end

function value = localMeanMetric(records, fieldName)
    if isempty(records)
        value = Inf;
    else
        value = mean([records.(fieldName)]);
    end
end

function value = localMaximumMetric(records, fieldName)
    if isempty(records)
        value = Inf;
    else
        value = max([records.(fieldName)]);
    end
end

function value = localMinimumMetric(records, fieldName)
    if isempty(records)
        value = -Inf;
    else
        value = min([records.(fieldName)]);
    end
end

function localReport(benchmark)
    fprintf("\nOnline NRMM tracking error benchmark\n");
    fprintf("  duration: %.3f s\n", benchmark.options.duration);
    fprintf("  Monte Carlo runs for noisy cases: %d\n", ...
        benchmark.options.monteCarloRuns);
    fprintf("  RMSE burn-in fraction: %.3f (peaks cover the " ...
        + "complete trial)\n", benchmark.options.burnInFraction);
    fprintf("  Error statistics use completed finite runs; failure " ...
        + "counts are separate.\n\n");
    fprintf("Execution and sampled truth-domain audit\n");
    disp(benchmark.summary(:, [ ...
        "caseName", "sampleRateHz", "completedRunCount", ...
        "failedRunCount", "failureIdentifiers", ...
        "truthWithinCertifiedDomain"]));
    fprintf("\nEgo-state RMSE\n");
    disp(benchmark.summary(:, [ ...
        "caseName", "egoPositionRmseMeanM", "egoVelocityRmseMeanMps", ...
        "egoAccelerationRmseMeanMps2", "egoYawRmseMeanDeg"]));
    fprintf("\nTarget RMSE in [rho; q; s] coordinates\n");
    fprintf("  Radar noise reaches the s channel through the " ...
        + "omega_T^3 innovation gain;\n  large s-channel RMSE in " ...
        + "noisy cases is expected and reported as measured.\n");
    disp(benchmark.summary(:, [ ...
        "caseName", "relativePositionRmseMeanM", ...
        "relativePositionRmseWorstM", "relativePositionPeakWorstM", ...
        "targetVelocityEgoRmseMeanMps", ...
        "targetAccelerationEgoRmseMeanMps2", ...
        "targetAccelerationEgoRmseWorstMps2"]));
    fprintf("\nTarget inertial reconstruction and domain audit\n");
    disp(benchmark.summary(:, [ ...
        "caseName", "targetInertialPositionRmseMeanM", ...
        "minimumEstimatedTargetSpeedWorstMps", ...
        "speedDomainValidCumulativeAll", ...
        "speedDomainValidFinalIntervalAll"]));
    failures = benchmark.trials(~benchmark.trials.completed, ...
        ["caseName", "seed", "failureIdentifier"]);
    if height(failures) > 0
        fprintf("\nRecorded failures (synthesis or runtime)\n");
        disp(failures);
    end
end

function rotated = localRotateRows(angle, vectors)
    rotated = [ ...
        cos(angle).*vectors(:, 1)-sin(angle).*vectors(:, 2), ...
        sin(angle).*vectors(:, 1)+cos(angle).*vectors(:, 2)];
end

function rotation = localRotation(angle)
    rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
end

function value = localWrapToPi(value)
    value = mod(value+pi, 2.0*pi)-pi;
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = mfilename;
    addParameter(parser, "Report", true, ...
        @(x) islogical(x) && isscalar(x));
    addParameter(parser, "Seed", 17, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x));
    addParameter(parser, "Duration", 12.0, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0.0);
    addParameter(parser, "MonteCarloRuns", 5, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
        && x >= 1.0 && x == floor(x));
    addParameter(parser, "BurnInFraction", 0.25, ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x) ...
        && x >= 0.0 && x < 1.0);
    parse(parser, varargin{:});
    options = struct( ...
        "report", parser.Results.Report, ...
        "seed", double(parser.Results.Seed), ...
        "duration", double(parser.Results.Duration), ...
        "monteCarloRuns", double(parser.Results.MonteCarloRuns), ...
        "burnInFraction", double(parser.Results.BurnInFraction));
end

function localAddProjectPaths()
    repoRoot = fileparts(fileparts(mfilename("fullpath")));
    addpath(fullfile(repoRoot, "config"));
    addpath(fullfile(repoRoot, "estimator"));
end
