function result = runOncomingVehicleAvoidanceScenario(varargin)
% runOncomingVehicleAvoidanceScenario Test head-on collision avoidance.
%
% The ego and target start on the same straight centerline with equal and
% opposite speeds. The target has a small lateral offset that breaks the
% left/right symmetry but is insufficient to prevent an uncontrolled
% rectangle overlap. Perception, optimization, and actuation are updated at
% the configured controller sample time.

    options = localOptions(varargin{:});
    centerline = [ ...
        -options.centerlineLengthBefore, 0.0; ...
        options.centerlineLengthAfter, 0.0];
    targetStateFunction = @(time, egoState) ...
        localTargetState(time, egoState, options);
    geometry = struct( ...
        "type", "straightOncomingVehicle", ...
        "targetInitialLongitudinalDistance", ...
            options.targetInitialLongitudinalDistance, ...
        "targetLateralOffset", options.targetLateralOffset, ...
        "targetSpeed", options.targetSpeed, ...
        "perceptionRange", options.perceptionRange, ...
        "rightRoadBoundaryOffset", options.rightRoadBoundaryOffset, ...
        "leftRoadBoundaryOffset", options.leftRoadBoundaryOffset, ...
        "roadShoulderWidth", options.roadShoulderWidth);

    result = runCenterlineCruiseScenario( ...
        Centerline=centerline, ...
        InitialPosition=[0.0; 0.0], ...
        InitialYaw=0.0, ...
        InitialLateralVelocity=0.0, ...
        InitialYawRate=0.0, ...
        Description="Straight-centerline oncoming-vehicle avoidance", ...
        Geometry=geometry, ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetStateFunction=targetStateFunction, ...
        UseStateEstimator=options.useStateEstimator, ...
        EstimatorConfiguration=options.estimatorConfiguration, ...
        ControllerConfiguration=options.controllerConfiguration, ...
        DeadlineSeconds=options.deadlineSeconds,EnforceRuntimeDeadline=options.enforceRuntimeDeadline, ...
        PerceptionRange=options.perceptionRange, ...
        RoadBoundaryOffsets=[ ...
            options.rightRoadBoundaryOffset; ...
            options.leftRoadBoundaryOffset], ...
        RoadShoulderWidth=options.roadShoulderWidth, ...
        EgoCollisionSize=[ ...
            options.egoLength; options.egoWidth], ...
        TargetCollisionSize=[ ...
            options.targetLength; options.targetWidth], ...
        SpeedTolerance=options.recoverySpeedTolerance, ...
        LateralTolerance=options.recoveryLateralTolerance, ...
        HeadingTolerance=options.recoveryHeadingTolerance, ...
        Plot=false, ...
        Report=false, ...
        Progress=options.progress);

    result = localAvoidanceEvaluation(result, options);
    if options.report
        localReport(result);
    end
    if options.plot
        localPlot(result);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = "runOncomingVehicleAvoidanceScenario";
    addParameter(parser, "Duration", 10.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "TargetSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "TargetInitialLongitudinalDistance", ...
        50.0, @localPositiveScalar);
    addParameter(parser, "TargetLateralOffset", ...
        1.5, @localFiniteScalar);
    addParameter(parser, "TargetLength", 5.0, @localPositiveScalar);
    addParameter(parser, "TargetWidth", 2.0, @localPositiveScalar);
    addParameter(parser, "PerceptionRange", 30.0, ...
        @localPositiveScalar);
    addParameter(parser, "RightRoadBoundaryOffset", 6.0, ...
        @localPositiveScalar);
    addParameter(parser, "LeftRoadBoundaryOffset", 8.0, ...
        @localPositiveScalar);
    addParameter(parser, "RoadShoulderWidth", 2.6, ...
        @localPositiveScalar);
    addParameter(parser, "EgoLength", 5.0, @localPositiveScalar);
    addParameter(parser, "EgoWidth", 2.0, @localPositiveScalar);
    addParameter(parser, "UseStateEstimator", false, ...
        @localLogicalScalar);
    addParameter(parser, "EstimatorConfiguration", struct(), ...
        @localScalarStruct);
    addParameter(parser,"ControllerConfiguration",struct(),@localScalarStruct);
    addParameter(parser,"DeadlineSeconds",0.1,@localPositiveScalar);
    addParameter(parser,"EnforceRuntimeDeadline",false,@localLogicalScalar);
    addParameter(parser, "RecoveryWindow", 1.0, @localPositiveScalar);
    addParameter(parser, "RecoverySpeedTolerance", ...
        0.5, @localPositiveScalar);
    addParameter(parser, "RecoveryLateralTolerance", ...
        0.2, @localPositiveScalar);
    addParameter(parser, "RecoveryHeadingTolerance", ...
        0.02, @localPositiveScalar);
    addParameter(parser, "CenterlineLengthBefore", ...
        200.0, @localPositiveScalar);
    addParameter(parser, "CenterlineLengthAfter", ...
        300.0, @localPositiveScalar);
    addParameter(parser, "Plot", false, @localLogicalScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", false, @localLogicalScalar);
    parse(parser, varargin{:});

    options = struct();
    options.duration = double(parser.Results.Duration);
    options.referenceSpeed = double(parser.Results.ReferenceSpeed);
    options.targetSpeed = double(parser.Results.TargetSpeed);
    options.targetInitialLongitudinalDistance = ...
        double(parser.Results.TargetInitialLongitudinalDistance);
    options.targetLateralOffset = ...
        double(parser.Results.TargetLateralOffset);
    options.targetLength = double(parser.Results.TargetLength);
    options.targetWidth = double(parser.Results.TargetWidth);
    options.perceptionRange = ...
        double(parser.Results.PerceptionRange);
    options.rightRoadBoundaryOffset = ...
        double(parser.Results.RightRoadBoundaryOffset);
    options.leftRoadBoundaryOffset = ...
        double(parser.Results.LeftRoadBoundaryOffset);
    options.roadShoulderWidth = ...
        double(parser.Results.RoadShoulderWidth);
    options.egoLength = double(parser.Results.EgoLength);
    options.egoWidth = double(parser.Results.EgoWidth);
    options.useStateEstimator = ...
        logical(parser.Results.UseStateEstimator);
    options.estimatorConfiguration = ...
        parser.Results.EstimatorConfiguration;
    options.controllerConfiguration = parser.Results.ControllerConfiguration;
    options.deadlineSeconds = parser.Results.DeadlineSeconds;
    options.enforceRuntimeDeadline = parser.Results.EnforceRuntimeDeadline;
    options.recoveryWindow = double(parser.Results.RecoveryWindow);
    options.recoverySpeedTolerance = ...
        double(parser.Results.RecoverySpeedTolerance);
    options.recoveryLateralTolerance = ...
        double(parser.Results.RecoveryLateralTolerance);
    options.recoveryHeadingTolerance = ...
        double(parser.Results.RecoveryHeadingTolerance);
    options.centerlineLengthBefore = ...
        double(parser.Results.CenterlineLengthBefore);
    options.centerlineLengthAfter = ...
        double(parser.Results.CenterlineLengthAfter);
    options.plot = logical(parser.Results.Plot);
    options.report = logical(parser.Results.Report);
    options.progress = logical(parser.Results.Progress);
end

function target = localTargetState(time, ~, options)
    target = struct( ...
        "trackId","synthetic-target-1", ...
        "predictionMotion",struct("kind","finite-sensing-motion-v1","jerkBound",[0;0], ...
            "yawAccelerationBound",0,"scalarAccelerationMaximum",0), ...
        "targetPositionInertial", [ ...
            options.targetInitialLongitudinalDistance ...
                - options.targetSpeed * time; ...
            options.targetLateralOffset], ...
        "targetVelocityInertial", [-options.targetSpeed; 0.0], ...
        "targetAccelerationInertial", [0.0; 0.0], ...
        "targetYawInertial", pi, ...
        "targetYawRate", 0.0, ...
        "targetLength", options.targetLength, ...
        "targetWidth", options.targetWidth);
end

function result = localAvoidanceEvaluation(result, options)
    sampleTimeTolerance = 100.0 * eps(max( ...
        1.0, result.scenario.sampleTime));
    if abs(result.scenario.targetSampleTime ...
            - result.scenario.sampleTime) > sampleTimeTolerance
        error("runOncomingVehicleAvoidanceScenario:invalidSampleTime", ...
            "The target observation and control sample times must agree.");
    end

    traceTime = result.plantTrace.time;
    if isempty(traceTime)
        result.targetTruth = struct( ...
            "time", zeros(0, 1), ...
            "position", zeros(0, 2), ...
            "yaw", zeros(0, 1), ...
            "length", options.targetLength, ...
            "width", options.targetWidth);
        result.baseline = struct( ...
            "egoPosition", zeros(0, 2), ...
            "egoYaw", zeros(0, 1), ...
            "separatingAxisMargin", zeros(0, 1));
        result.avoidance = localEmptyAvoidance(options);
        result.passed = false;
        return;
    end
    targetPosition = [ ...
        options.targetInitialLongitudinalDistance ...
            - options.targetSpeed * traceTime, ...
        options.targetLateralOffset * ones(size(traceTime))];
    targetYaw = pi * ones(size(traceTime));
    egoPosition = [ ...
        result.plantTrace.positionX, result.plantTrace.positionY];
    egoYaw = result.plantTrace.yaw;
    vehicle = result.controllerConfiguration.vehicle;
    controlledMargin = rectangleSeparationMargin( ...
        egoPosition, egoYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    baselinePosition = [ ...
        options.referenceSpeed * traceTime, zeros(size(traceTime))];
    baselineYaw = zeros(size(traceTime));
    baselineMargin = rectangleSeparationMargin( ...
        baselinePosition, baselineYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    relativeLongitudinalPosition = ...
        targetPosition(:, 1) - egoPosition(:, 1);
    passingIdx = find(relativeLongitudinalPosition <= 0.0, 1);
    if isempty(passingIdx)
        passedTarget = false;
        passingTime = NaN;
        passingSpeed = NaN;
    else
        passedTarget = true;
        passingTime = traceTime(passingIdx);
        passingSpeed = result.plantTrace.longitudinalVelocity(passingIdx);
    end

    [minimumControlledMargin, closestIdx] = min(controlledMargin);
    minimumBaselineMargin = min(baselineMargin);
    recoveryStartTime = max(0.0, options.duration ...
        - options.recoveryWindow);
    recoveryMask = traceTime >= recoveryStartTime;
    recoverySpeedError = result.plantTrace.longitudinalVelocity( ...
        recoveryMask) - options.referenceSpeed;
    recoveryLateralError = result.plantTrace.positionY(recoveryMask);
    recoveryBodyHeadingError = atan2( ...
        sin(result.plantTrace.yaw(recoveryMask)), ...
        cos(result.plantTrace.yaw(recoveryMask)));
    recoveryVelocityCourse = result.plantTrace.yaw(recoveryMask) ...
        + atan2( ...
            result.plantTrace.lateralVelocity(recoveryMask), ...
            result.plantTrace.longitudinalVelocity(recoveryMask));
    recoveryCourseError = atan2( ...
        sin(recoveryVelocityCourse), ...
        cos(recoveryVelocityCourse));
    recoveredCruise = ~isempty(recoverySpeedError) ...
        && max(abs(recoverySpeedError)) ...
            <= options.recoverySpeedTolerance ...
        && max(abs(recoveryLateralError)) ...
            <= options.recoveryLateralTolerance ...
        && max(abs(recoveryCourseError)) ...
            <= options.recoveryHeadingTolerance;
    collisionFree = ~isempty(controlledMargin) ...
        && minimumControlledMargin > 0.0;
    baselineCollides = ~isempty(baselineMargin) ...
        && minimumBaselineMargin < 0.0;
    minimumEgoLongitudinalSpeed = min( ...
        result.plantTrace.longitudinalVelocity);
    remainedMoving = minimumEgoLongitudinalSpeed > 0.0;
    offsetBelowCombinedHalfWidths = ...
        abs(options.targetLateralOffset) ...
        < 0.5 * (vehicle.width + options.targetWidth);

    avoidance = struct();
    avoidance.targetInitialLongitudinalDistance = ...
        options.targetInitialLongitudinalDistance;
    avoidance.targetLateralOffset = options.targetLateralOffset;
    avoidance.offsetBelowCombinedHalfWidths = ...
        offsetBelowCombinedHalfWidths;
    avoidance.minimumControlledSeparatingAxisMargin = ...
        minimumControlledMargin;
    avoidance.minimumBaselineSeparatingAxisMargin = ...
        minimumBaselineMargin;
    avoidance.baselineCollides = baselineCollides;
    avoidance.collisionFree = collisionFree;
    avoidance.closestApproachTime = traceTime(closestIdx);
    avoidance.passedTarget = passedTarget;
    avoidance.passingTime = passingTime;
    avoidance.egoSpeedAtPassing = passingSpeed;
    avoidance.minimumEgoLongitudinalSpeed = ...
        minimumEgoLongitudinalSpeed;
    avoidance.remainedMoving = remainedMoving;
    avoidance.noRoadBoundaryCrossing = ...
        result.roadSafety.noBoundaryCrossing;
    avoidance.minimumRoadBoundaryFunctionMargin = ...
        result.roadSafety.minimumBoundaryFunctionMargin;
    avoidance.minimumEgoLateralPosition = ...
        min(result.plantTrace.positionY);
    avoidance.maximumEgoLateralPosition = ...
        max(result.plantTrace.positionY);
    avoidance.recoveredCruise = recoveredCruise;
    avoidance.recoveryWindow = options.recoveryWindow;
    avoidance.maximumRecoverySpeedError = ...
        max(abs(recoverySpeedError));
    avoidance.maximumRecoveryLateralError = ...
        max(abs(recoveryLateralError));
    avoidance.recoveryOrientationMetric = ...
        "inertialVelocityCourseRelativeToCenterline";
    avoidance.maximumRecoveryHeadingError = ...
        max(abs(recoveryCourseError));
    avoidance.maximumRecoveryBodyHeadingError = ...
        max(abs(recoveryBodyHeadingError));

    result.targetTruth = struct( ...
        "time", traceTime, ...
        "position", targetPosition, ...
        "yaw", targetYaw, ...
        "length", options.targetLength, ...
        "width", options.targetWidth);
    result.baseline = struct( ...
        "egoPosition", baselinePosition, ...
        "egoYaw", baselineYaw, ...
        "separatingAxisMargin", baselineMargin);
    result.avoidance = avoidance;
    result.passed = ~result.failure.occurred ...
        && result.metrics.controllerCompletedScenario ...
        && offsetBelowCombinedHalfWidths ...
        && baselineCollides ...
        && collisionFree ...
        && result.roadSafety.noBoundaryCrossing ...
        && passedTarget ...
        && remainedMoving ...
        && recoveredCruise;
    if result.estimator.enabled
        result.passed = result.passed ...
            && result.estimator.metrics.sampledEgoPremisesSatisfied ...
            && result.estimator.metrics.allPublishedBoundsContainTruth;
    end
end

function avoidance = localEmptyAvoidance(options)
    avoidance = struct( ...
        "targetInitialLongitudinalDistance", ...
            options.targetInitialLongitudinalDistance, ...
        "targetLateralOffset", options.targetLateralOffset, ...
        "offsetBelowCombinedHalfWidths", false, ...
        "minimumControlledSeparatingAxisMargin", NaN, ...
        "minimumBaselineSeparatingAxisMargin", NaN, ...
        "baselineCollides", false, ...
        "collisionFree", false, ...
        "closestApproachTime", NaN, ...
        "passedTarget", false, ...
        "passingTime", NaN, ...
        "egoSpeedAtPassing", NaN, ...
        "minimumEgoLongitudinalSpeed", NaN, ...
        "remainedMoving", false, ...
        "noRoadBoundaryCrossing", false, ...
        "minimumRoadBoundaryFunctionMargin", NaN, ...
        "minimumEgoLateralPosition", NaN, ...
        "maximumEgoLateralPosition", NaN, ...
        "recoveredCruise", false, ...
        "recoveryWindow", options.recoveryWindow, ...
        "maximumRecoverySpeedError", NaN, ...
        "maximumRecoveryLateralError", NaN, ...
        "recoveryOrientationMetric", ...
            "inertialVelocityCourseRelativeToCenterline", ...
        "maximumRecoveryHeadingError", NaN, ...
        "maximumRecoveryBodyHeadingError", NaN);
end

function localReport(result)
    metrics = result.avoidance;
    fprintf("\n%s\n", result.scenario.description);
    fprintf("  Perception/control sample time: %.3f s\n", ...
        result.scenario.sampleTime);
    fprintf("  Complete online frame median / maximum / deadline: %.3f / %.3f / %.3f ms\n", ...
        1000*median(result.runtime.frameSeconds),1000*max(result.runtime.frameSeconds), ...
        1000*result.runtime.deadlineSeconds);
    fprintf("  Complete frame deadline met / enforced: %d / %d\n", ...
        result.runtime.deadlineMet,result.runtime.enforced);
    fprintf("  Target lateral offset: %.3f m\n", ...
        metrics.targetLateralOffset);
    fprintf("  No-control minimum SAT margin: %.6f m\n", ...
        metrics.minimumBaselineSeparatingAxisMargin);
    fprintf("  Controlled minimum SAT margin: %.6f m\n", ...
        metrics.minimumControlledSeparatingAxisMargin);
    fprintf("  Passing time / ego speed: %.3f s / %.3f m/s\n", ...
        metrics.passingTime, metrics.egoSpeedAtPassing);
    fprintf("  Minimum ego longitudinal speed: %.3f m/s\n", ...
        metrics.minimumEgoLongitudinalSpeed);
    fprintf("  Minimum ego lateral position: %.6f m\n", ...
        metrics.minimumEgoLateralPosition);
    fprintf("  Final-window maximum speed/lateral/heading errors: " ...
        + "%.6f m/s, %.6f m, %.6f rad\n", ...
        metrics.maximumRecoverySpeedError, ...
        metrics.maximumRecoveryLateralError, ...
        metrics.maximumRecoveryHeadingError);
    fprintf("  Mean / maximum solve time: %.6f / %.6f s\n", ...
        result.metrics.meanSolveTime, result.metrics.maximumSolveTime);
    if result.passed
        fprintf("  Result: PASS\n\n");
    else
        fprintf("  Result: FAIL\n\n");
    end
end

function localPlot(result)
    figure(Name=result.scenario.description);
    tiledlayout(2, 1);

    nexttile;
    plot(result.plantTrace.positionX, ...
        result.plantTrace.positionY, LineWidth=1.5);
    hold on;
    plot(result.targetTruth.position(:, 1), ...
        result.targetTruth.position(:, 2), LineWidth=1.5);
    plot(result.scenario.centerline(:, 1), ...
        result.scenario.centerline(:, 2), "k--");
    grid on;
    axis equal;
    xlabel("Inertial x (m)");
    ylabel("Inertial y (m)");
    legend("Ego CG", "Target CG", "Centerline", Location="best");

    nexttile;
    plot(result.plantTrace.time, ...
        result.plantTrace.longitudinalVelocity, LineWidth=1.5);
    hold on;
    yline(result.scenario.referenceSpeed, "k--");
    grid on;
    xlabel("Time (s)");
    ylabel("Ego longitudinal speed (m/s)");
    legend("Ego", "Reference", Location="best");
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localScalarStruct(value)
    valid = isstruct(value) && isscalar(value);
end
