function result = runStraightCenterlineCruiseScenario(varargin)
% runStraightCenterlineCruiseScenario Test straight-line cruise.

    centerline = [-1000.0, 0.0; 1000.0, 0.0];
    geometry = struct( ...
        "type", "straightLine", ...
        "curvature", 0.0);
    result = runCenterlineCruiseScenario( ...
        "Centerline", centerline, ...
        "InitialPosition", [0.0; 0.0], ...
        "InitialYaw", 0.0, ...
        "Description", ...
            "Straight centerline, constant reference speed, no targets", ...
        "Geometry", geometry, ...
        varargin{:});
end
