function result = ...
        runVaryingCurvatureStraightTargetAvoidanceScenario(varargin)
% runVaryingCurvatureStraightTargetAvoidanceScenario Test S-curve avoidance.
%
% The ego nominally follows one sinusoidal-curvature S bend between straight
% entry and exit segments. A target travels on a straight line opposite the
% centerline tangent at a constructed collision point. Its initial position
% is selected so that the target and nominal ego centers coincide and its
% initial distance has the requested value.

    options = localOptions(varargin{:});
    [centerline, parameterization, geometry] = ...
        localVaryingCurvatureCenterline(options);
    collisionGeometry = localCollisionGeometry( ...
        parameterization, options);
    targetStateFunction = @(time, egoState) ...
        localTargetState(time, egoState, collisionGeometry, options);

    geometry.type = "sinusoidalCurvatureSCurveStraightTargetCollision";
    geometry.targetMotion = "constantVelocityStraightLine";
    geometry.targetInitialDistance = ...
        collisionGeometry.targetInitialDistance;
    geometry.targetInitialPosition = ...
        collisionGeometry.targetInitialPosition;
    geometry.targetVelocity = collisionGeometry.targetVelocity;
    geometry.nominalCollisionTime = ...
        collisionGeometry.nominalCollisionTime;
    geometry.nominalCollisionPosition = ...
        collisionGeometry.nominalCollisionPosition;
    geometry.nominalTargetCollisionPosition = ...
        collisionGeometry.nominalTargetCollisionPosition;
    geometry.nominalCollisionHeading = ...
        collisionGeometry.nominalCollisionHeading;
    geometry.targetCollisionLateralOffset = ...
        options.targetCollisionLateralOffset;
    geometry.perceptionRange = options.perceptionRange;
    geometry.rightRoadBoundaryOffset = ...
        options.rightRoadBoundaryOffset;
    geometry.leftRoadBoundaryOffset = ...
        options.leftRoadBoundaryOffset;
    geometry.roadShoulderWidth = options.roadShoulderWidth;

    description = sprintf( ...
        "Single-wave sinusoidal-curvature S bend with a straight-line " ...
        + "target constructed to collide at t = %.3f s", ...
        collisionGeometry.nominalCollisionTime);
    result = runCenterlineCruiseScenario( ...
        Centerline=centerline, ...
        InitialPosition=[0.0; 0.0], ...
        InitialYaw=0.0, ...
        InitialLateralVelocity=0.0, ...
        InitialYawRate=0.0, ...
        Description=description, ...
        Geometry=geometry, ...
        Duration=options.duration, ...
        ReferenceSpeed=options.referenceSpeed, ...
        TargetStateFunction=targetStateFunction, ...
        UseStateEstimator=options.useStateEstimator, ...
        EstimatorConfiguration=options.estimatorConfiguration, ...
        PerceptionRange=options.perceptionRange, ...
        RoadBoundaryOffsets=[ ...
            options.rightRoadBoundaryOffset; ...
            options.leftRoadBoundaryOffset], ...
        RoadShoulderWidth=options.roadShoulderWidth, ...
        EgoCollisionSize=[ ...
            options.egoLength; options.egoWidth], ...
        SpeedTolerance=options.recoverySpeedTolerance, ...
        LateralTolerance=options.recoveryLateralTolerance, ...
        HeadingTolerance=options.recoveryHeadingTolerance, ...
        Plot=false, ...
        Report=false, ...
        Progress=options.progress);

    result = localAvoidanceEvaluation( ...
        result, parameterization, collisionGeometry, options);
    if options.report
        localReport(result);
    end
    if options.plot
        localPlot(result);
    end
end

function options = localOptions(varargin)
    parser = inputParser;
    parser.FunctionName = ...
        "runVaryingCurvatureStraightTargetAvoidanceScenario";
    addParameter(parser, "MaximumCurvature", 0.01, ...
        @localPositiveScalar);
    addParameter(parser, "CurvatureWavelength", 80.0, ...
        @localPositiveScalar);
    addParameter(parser, "ArcLengthBefore", 40.0, ...
        @localNonnegativeScalar);
    addParameter(parser, "ArcLengthAfter", 220.0, ...
        @localPositiveScalar);
    addParameter(parser, "CenterlineSpacing", 0.1, ...
        @localPositiveScalar);
    addParameter(parser, "Duration", 10.0, @localPositiveScalar);
    addParameter(parser, "ReferenceSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "TargetSpeed", 15.0, @localPositiveScalar);
    addParameter(parser, "TargetInitialDistance", ...
        50.0, @localPositiveScalar);
    addParameter(parser, "TargetCollisionLateralOffset", ...
        1.5, @localFiniteScalar);
    addParameter(parser, "TargetLength", 5.0, @localPositiveScalar);
    addParameter(parser, "TargetWidth", 2.0, @localPositiveScalar);
    addParameter(parser, "PerceptionRange", 30.0, ...
        @localPositiveScalar);
    addParameter(parser, "RightRoadBoundaryOffset", 6.0, ...
        @localPositiveScalar);
    addParameter(parser, "LeftRoadBoundaryOffset", 8.0, ...
        @localPositiveScalar);
    addParameter(parser, "RoadShoulderWidth", 2.6, ...
        @localPositiveScalar);
    addParameter(parser, "EgoLength", 5.0, @localPositiveScalar);
    addParameter(parser, "EgoWidth", 2.0, @localPositiveScalar);
    addParameter(parser, "UseStateEstimator", false, ...
        @localLogicalScalar);
    addParameter(parser, "EstimatorConfiguration", struct(), ...
        @localScalarStruct);
    addParameter(parser, "RecoveryWindow", 1.0, @localPositiveScalar);
    addParameter(parser, "RecoverySpeedTolerance", ...
        0.5, @localPositiveScalar);
    addParameter(parser, "RecoveryLateralTolerance", ...
        0.2, @localPositiveScalar);
    addParameter(parser, "RecoveryHeadingTolerance", ...
        0.02, @localPositiveScalar);
    addParameter(parser, "Plot", false, @localLogicalScalar);
    addParameter(parser, "Report", true, @localLogicalScalar);
    addParameter(parser, "Progress", false, @localLogicalScalar);
    parse(parser, varargin{:});

    options = struct( ...
        "maximumCurvature", ...
            double(parser.Results.MaximumCurvature), ...
        "curvatureWavelength", ...
            double(parser.Results.CurvatureWavelength), ...
        "arcLengthBefore", ...
            double(parser.Results.ArcLengthBefore), ...
        "arcLengthAfter", ...
            double(parser.Results.ArcLengthAfter), ...
        "centerlineSpacing", ...
            double(parser.Results.CenterlineSpacing), ...
        "duration", double(parser.Results.Duration), ...
        "referenceSpeed", double(parser.Results.ReferenceSpeed), ...
        "targetSpeed", double(parser.Results.TargetSpeed), ...
        "targetInitialDistance", ...
            double(parser.Results.TargetInitialDistance), ...
        "targetCollisionLateralOffset", ...
            double(parser.Results.TargetCollisionLateralOffset), ...
        "targetLength", double(parser.Results.TargetLength), ...
        "targetWidth", double(parser.Results.TargetWidth), ...
        "perceptionRange", ...
            double(parser.Results.PerceptionRange), ...
        "rightRoadBoundaryOffset", ...
            double(parser.Results.RightRoadBoundaryOffset), ...
        "leftRoadBoundaryOffset", ...
            double(parser.Results.LeftRoadBoundaryOffset), ...
        "roadShoulderWidth", ...
            double(parser.Results.RoadShoulderWidth), ...
        "egoLength", double(parser.Results.EgoLength), ...
        "egoWidth", double(parser.Results.EgoWidth), ...
        "useStateEstimator", ...
            logical(parser.Results.UseStateEstimator), ...
        "estimatorConfiguration", ...
            parser.Results.EstimatorConfiguration, ...
        "recoveryWindow", double(parser.Results.RecoveryWindow), ...
        "recoverySpeedTolerance", ...
            double(parser.Results.RecoverySpeedTolerance), ...
        "recoveryLateralTolerance", ...
            double(parser.Results.RecoveryLateralTolerance), ...
        "recoveryHeadingTolerance", ...
            double(parser.Results.RecoveryHeadingTolerance), ...
        "plot", logical(parser.Results.Plot), ...
        "report", logical(parser.Results.Report), ...
        "progress", logical(parser.Results.Progress));
end

function [centerline, parameterization, geometry] = ...
        localVaryingCurvatureCenterline(options)
    spacing = options.centerlineSpacing;
    firstIndex = -ceil(options.arcLengthBefore / spacing);
    lastIndex = ceil(options.arcLengthAfter / spacing);
    arcLength = spacing * (firstIndex:lastIndex).';
    waveNumber = 2.0 * pi / options.curvatureWavelength;
    curvature = zeros(size(arcLength));
    bendMask = arcLength >= 0.0 ...
        & arcLength <= options.curvatureWavelength;
    curvature(bendMask) = options.maximumCurvature ...
        * sin(waveNumber * arcLength(bendMask));
    heading = cumtrapz(arcLength, curvature);
    initialIdx = find(arcLength == 0.0, 1);
    heading = heading - heading(initialIdx);
    positionX = cumtrapz(arcLength, cos(heading));
    positionY = cumtrapz(arcLength, sin(heading));
    positionX = positionX - positionX(initialIdx);
    positionY = positionY - positionY(initialIdx);
    centerline = [positionX, positionY];

    parameterization = struct( ...
        "arcLength", arcLength, ...
        "position", centerline, ...
        "heading", heading);
    geometry = struct( ...
        "curvatureLaw", ...
            "kappa(s)=kappaMax*sin(2*pi*s/lambda) for " ...
                + "0<=s<=lambda; kappa(s)=0 otherwise", ...
        "maximumCurvature", options.maximumCurvature, ...
        "minimumCurvature", -options.maximumCurvature, ...
        "curvatureWavelength", options.curvatureWavelength, ...
        "straightEntryEndArcLength", 0.0, ...
        "straightExitStartArcLength", options.curvatureWavelength, ...
        "curvatureAtInitialPosition", curvature(initialIdx), ...
        "headingAtInitialPosition", heading(initialIdx), ...
        "arcLengthBefore", options.arcLengthBefore, ...
        "arcLengthAfter", options.arcLengthAfter, ...
        "centerlineSpacing", spacing);
end

function geometry = localCollisionGeometry(parameterization, options)
    maximumCollisionTime = ...
        parameterization.arcLength(end) / options.referenceSpeed;
    residual = @(time) localInitialDistanceResidual( ...
        time, parameterization, options);
    upperTime = min( ...
        maximumCollisionTime, ...
        2.0 * options.targetInitialDistance ...
            / (options.referenceSpeed + options.targetSpeed));
    while residual(upperTime) < 0.0 ...
            && upperTime < maximumCollisionTime
        upperTime = min( ...
            maximumCollisionTime, max(upperTime + 0.5, 1.5 * upperTime));
    end
    if residual(upperTime) < 0.0
        error( ...
            "runVaryingCurvatureStraightTargetAvoidanceScenario:" ...
            + "centerlineTooShort", ...
            "ArcLengthAfter is too short to construct the collision.");
    end

    collisionTime = fzero(residual, [0.0, upperTime]);
    collisionAbscissa = options.referenceSpeed * collisionTime;
    [collisionPosition, collisionHeading] = ...
        localCenterlinePose(parameterization, collisionAbscissa);
    tangent = [cos(collisionHeading); sin(collisionHeading)];
    normal = [-tangent(2); tangent(1)];
    targetVelocity = -options.targetSpeed * tangent;
    targetCollisionPosition = collisionPosition.' ...
        + options.targetCollisionLateralOffset * normal;
    targetInitialPosition = targetCollisionPosition ...
        - collisionTime * targetVelocity;

    geometry = struct( ...
        "nominalCollisionTime", collisionTime, ...
        "nominalCollisionPosition", collisionPosition, ...
        "nominalTargetCollisionPosition", ...
            targetCollisionPosition, ...
        "nominalCollisionHeading", collisionHeading, ...
        "collisionTangent", tangent, ...
        "targetInitialPosition", targetInitialPosition, ...
        "targetVelocity", targetVelocity, ...
        "targetYaw", atan2(targetVelocity(2), targetVelocity(1)), ...
        "targetInitialDistance", norm(targetInitialPosition));
end

function residual = localInitialDistanceResidual( ...
        time, parameterization, options)
    collisionAbscissa = options.referenceSpeed * time;
    [position, heading] = ...
        localCenterlinePose(parameterization, collisionAbscissa);
    tangent = [cos(heading); sin(heading)];
    normal = [-tangent(2); tangent(1)];
    targetInitialPosition = position.' ...
        + options.targetCollisionLateralOffset * normal ...
        + options.targetSpeed * time * tangent;
    residual = norm(targetInitialPosition) ...
        - options.targetInitialDistance;
end

function target = localTargetState(time, ~, geometry, options)
    target = struct( ...
        "targetPositionInertial", ...
            geometry.targetInitialPosition ...
                + time * geometry.targetVelocity, ...
        "targetVelocityInertial", geometry.targetVelocity, ...
        "targetAccelerationInertial", [0.0; 0.0], ...
        "targetYawInertial", geometry.targetYaw, ...
        "targetYawRate", 0.0, ...
        "targetLength", options.targetLength, ...
        "targetWidth", options.targetWidth);
end

function result = localAvoidanceEvaluation( ...
        result, parameterization, geometry, options)
    traceTime = result.plantTrace.time;
    if isempty(traceTime)
        result.targetTruth = struct( ...
            "time", zeros(0, 1), ...
            "position", zeros(0, 2), ...
            "yaw", zeros(0, 1), ...
            "length", options.targetLength, ...
            "width", options.targetWidth);
        result.baseline = struct( ...
            "egoPosition", zeros(0, 2), ...
            "egoYaw", zeros(0, 1), ...
            "separatingAxisMargin", zeros(0, 1));
        result.controlled = struct( ...
            "separatingAxisMargin", zeros(0, 1));
        result.avoidance = localEmptyAvoidance(geometry, options);
        result.passed = false;
        return;
    end

    targetPosition = geometry.targetInitialPosition.' ...
        + traceTime * geometry.targetVelocity.';
    targetYaw = geometry.targetYaw * ones(size(traceTime));
    egoPosition = [ ...
        result.plantTrace.positionX, result.plantTrace.positionY];
    egoYaw = result.plantTrace.yaw;
    vehicle = result.controllerConfiguration.vehicle;
    controlledMargin = rectangleSeparationMargin( ...
        egoPosition, egoYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    baselineAbscissa = options.referenceSpeed * traceTime;
    [baselinePosition, baselineYaw] = ...
        localCenterlinePose(parameterization, baselineAbscissa);
    baselineMargin = rectangleSeparationMargin( ...
        baselinePosition, baselineYaw, targetPosition, targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    collisionTargetPosition = geometry.targetInitialPosition ...
        + geometry.nominalCollisionTime * geometry.targetVelocity;
    constructionError = norm( ...
        collisionTargetPosition ...
            - geometry.nominalTargetCollisionPosition);
    nominalCollisionMargin = rectangleSeparationMargin( ...
        geometry.nominalCollisionPosition, ...
        geometry.nominalCollisionHeading, ...
        collisionTargetPosition.', geometry.targetYaw, ...
        vehicle.length, vehicle.width, ...
        options.targetLength, options.targetWidth);

    relativeApproachCoordinate = ...
        (targetPosition - egoPosition) * geometry.collisionTangent;
    passingIdx = find(relativeApproachCoordinate <= 0.0, 1);
    if isempty(passingIdx)
        passedTarget = false;
        passingTime = NaN;
        passingSpeed = NaN;
    else
        passedTarget = true;
        passingTime = traceTime(passingIdx);
        passingSpeed = ...
            result.plantTrace.longitudinalVelocity(passingIdx);
    end

    [minimumControlledMargin, closestIdx] = min(controlledMargin);
    minimumBaselineMargin = min(baselineMargin);
    recoveryStartTime = max(0.0, ...
        options.duration - options.recoveryWindow);
    recoveryMask = result.controlTime >= recoveryStartTime;
    recoverySpeedError = ...
        result.controlState(recoveryMask, 4) - options.referenceSpeed;
    recoveryLateralError = ...
        result.controlTracking.lateralError(recoveryMask);
    recoveryBodyHeadingError = ...
        result.controlTracking.headingError(recoveryMask);
    recoveryVelocityCourse = result.controlState(recoveryMask, 3) ...
        + atan2( ...
            result.controlState(recoveryMask, 5), ...
            result.controlState(recoveryMask, 4));
    referenceHeading = result.controlTracking ...
        .referenceHeading(recoveryMask);
    recoveryCourseError = atan2( ...
        sin(recoveryVelocityCourse-referenceHeading), ...
        cos(recoveryVelocityCourse-referenceHeading));
    recoveredCruise = ~isempty(recoverySpeedError) ...
        && max(abs(recoverySpeedError)) ...
            <= options.recoverySpeedTolerance ...
        && max(abs(recoveryLateralError)) ...
            <= options.recoveryLateralTolerance ...
        && max(abs(recoveryCourseError)) ...
            <= options.recoveryHeadingTolerance;
    minimumEgoLongitudinalSpeed = min( ...
        result.plantTrace.longitudinalVelocity);
    remainedMoving = minimumEgoLongitudinalSpeed > 0.0;
    collisionFree = minimumControlledMargin > 0.0;
    baselineCollides = minimumBaselineMargin < 0.0;
    constructionTolerance = 1000.0 * eps(max( ...
        1.0, norm(geometry.nominalCollisionPosition)));
    collisionConstructionExact = ...
        constructionError <= constructionTolerance;

    result.targetTruth = struct( ...
        "time", traceTime, ...
        "position", targetPosition, ...
        "yaw", targetYaw, ...
        "length", options.targetLength, ...
        "width", options.targetWidth);
    result.baseline = struct( ...
        "egoPosition", baselinePosition, ...
        "egoYaw", baselineYaw, ...
        "separatingAxisMargin", baselineMargin);
    result.controlled = struct( ...
        "separatingAxisMargin", controlledMargin);
    result.avoidance = struct( ...
        "targetInitialDistance", geometry.targetInitialDistance, ...
        "targetInitialPosition", geometry.targetInitialPosition, ...
        "targetVelocity", geometry.targetVelocity, ...
        "nominalCollisionTime", geometry.nominalCollisionTime, ...
        "nominalCollisionPosition", geometry.nominalCollisionPosition, ...
        "nominalTargetCollisionPosition", ...
            geometry.nominalTargetCollisionPosition, ...
        "targetCollisionLateralOffset", ...
            options.targetCollisionLateralOffset, ...
        "collisionConstructionError", constructionError, ...
        "collisionConstructionExact", collisionConstructionExact, ...
        "nominalCollisionSeparatingAxisMargin", ...
            nominalCollisionMargin, ...
        "minimumControlledSeparatingAxisMargin", ...
            minimumControlledMargin, ...
        "minimumBaselineSeparatingAxisMargin", ...
            minimumBaselineMargin, ...
        "baselineCollides", baselineCollides, ...
        "collisionFree", collisionFree, ...
        "closestApproachTime", traceTime(closestIdx), ...
        "passedTarget", passedTarget, ...
        "passingTime", passingTime, ...
        "egoSpeedAtPassing", passingSpeed, ...
        "minimumEgoLongitudinalSpeed", ...
            minimumEgoLongitudinalSpeed, ...
        "remainedMoving", remainedMoving, ...
        "noRoadBoundaryCrossing", ...
            result.roadSafety.noBoundaryCrossing, ...
        "minimumRoadBoundaryFunctionMargin", ...
            result.roadSafety.minimumBoundaryFunctionMargin, ...
        "minimumLateralTrackingError", ...
            min(result.controlTracking.lateralError), ...
        "maximumLateralTrackingError", ...
            max(result.controlTracking.lateralError), ...
        "recoveredCruise", recoveredCruise, ...
        "recoveryWindow", options.recoveryWindow, ...
        "maximumRecoverySpeedError", ...
            max(abs(recoverySpeedError)), ...
        "maximumRecoveryLateralError", ...
            max(abs(recoveryLateralError)), ...
        "recoveryOrientationMetric", ...
            "inertialVelocityCourseRelativeToCenterline", ...
        "maximumRecoveryHeadingError", ...
            max(abs(recoveryCourseError)), ...
        "maximumRecoveryBodyHeadingError", ...
            max(abs(recoveryBodyHeadingError)));
    result.passed = ~result.failure.occurred ...
        && result.metrics.controllerCompletedScenario ...
        && collisionConstructionExact ...
        && baselineCollides ...
        && collisionFree ...
        && result.roadSafety.noBoundaryCrossing ...
        && passedTarget ...
        && remainedMoving ...
        && recoveredCruise;
end

function avoidance = localEmptyAvoidance(geometry, options)
    avoidance = struct( ...
        "targetInitialDistance", geometry.targetInitialDistance, ...
        "targetInitialPosition", geometry.targetInitialPosition, ...
        "targetVelocity", geometry.targetVelocity, ...
        "nominalCollisionTime", geometry.nominalCollisionTime, ...
        "nominalCollisionPosition", geometry.nominalCollisionPosition, ...
        "nominalTargetCollisionPosition", ...
            geometry.nominalTargetCollisionPosition, ...
        "targetCollisionLateralOffset", ...
            options.targetCollisionLateralOffset, ...
        "collisionConstructionError", NaN, ...
        "collisionConstructionExact", false, ...
        "nominalCollisionSeparatingAxisMargin", NaN, ...
        "minimumControlledSeparatingAxisMargin", NaN, ...
        "minimumBaselineSeparatingAxisMargin", NaN, ...
        "baselineCollides", false, ...
        "collisionFree", false, ...
        "closestApproachTime", NaN, ...
        "passedTarget", false, ...
        "passingTime", NaN, ...
        "egoSpeedAtPassing", NaN, ...
        "minimumEgoLongitudinalSpeed", NaN, ...
        "remainedMoving", false, ...
        "noRoadBoundaryCrossing", false, ...
        "minimumRoadBoundaryFunctionMargin", NaN, ...
        "minimumLateralTrackingError", NaN, ...
        "maximumLateralTrackingError", NaN, ...
        "recoveredCruise", false, ...
        "recoveryWindow", options.recoveryWindow, ...
        "maximumRecoverySpeedError", NaN, ...
        "maximumRecoveryLateralError", NaN, ...
        "recoveryOrientationMetric", ...
            "inertialVelocityCourseRelativeToCenterline", ...
        "maximumRecoveryHeadingError", NaN, ...
        "maximumRecoveryBodyHeadingError", NaN);
end

function [position, heading] = ...
        localCenterlinePose(parameterization, arcLength)
    position = [ ...
        interp1( ...
            parameterization.arcLength, ...
            parameterization.position(:, 1), arcLength, "linear"), ...
        interp1( ...
            parameterization.arcLength, ...
            parameterization.position(:, 2), arcLength, "linear")];
    heading = interp1( ...
        parameterization.arcLength, ...
        parameterization.heading, arcLength, "linear");
end

function localReport(result)
    metrics = result.avoidance;
    fprintf("\n%s\n", result.scenario.description);
    fprintf("  Target initial distance: %.6f m\n", ...
        metrics.targetInitialDistance);
    fprintf("  Constructed nominal collision time: %.6f s\n", ...
        metrics.nominalCollisionTime);
    fprintf("  Collision construction error: %.12g m\n", ...
        metrics.collisionConstructionError);
    fprintf("  Baseline / controlled minimum SAT margin: " ...
        + "%.6f / %.6f m\n", ...
        metrics.minimumBaselineSeparatingAxisMargin, ...
        metrics.minimumControlledSeparatingAxisMargin);
    fprintf("  Passing time / ego speed: %.3f s / %.3f m/s\n", ...
        metrics.passingTime, metrics.egoSpeedAtPassing);
    fprintf("  Minimum ego longitudinal speed: %.3f m/s\n", ...
        metrics.minimumEgoLongitudinalSpeed);
    fprintf("  Final-window maximum speed/lateral/heading errors: " ...
        + "%.6f m/s, %.6f m, %.6f rad\n", ...
        metrics.maximumRecoverySpeedError, ...
        metrics.maximumRecoveryLateralError, ...
        metrics.maximumRecoveryHeadingError);
    fprintf("  Mean / maximum solve time: %.6f / %.6f s\n", ...
        result.metrics.meanSolveTime, result.metrics.maximumSolveTime);
    if result.passed
        fprintf("  Result: PASS\n\n");
    else
        fprintf("  Result: FAIL\n\n");
    end
end

function localPlot(result)
    figure(Name=result.scenario.description);
    tiledlayout(2, 1);

    nexttile;
    plot(result.plantTrace.positionX, ...
        result.plantTrace.positionY, LineWidth=1.5);
    hold on;
    plot(result.targetTruth.position(:, 1), ...
        result.targetTruth.position(:, 2), LineWidth=1.5);
    plot(result.scenario.centerline(:, 1), ...
        result.scenario.centerline(:, 2), "k--");
    plot(result.baseline.egoPosition(:, 1), ...
        result.baseline.egoPosition(:, 2), ...
        Color=[0.6, 0.6, 0.6], LineStyle=":");
    grid on;
    axis equal;
    xlabel("Inertial x (m)");
    ylabel("Inertial y (m)");
    legend("Controlled ego", "Straight target", ...
        "Centerline", "Nominal ego", Location="best");

    nexttile;
    plot(result.plantTrace.time, ...
        result.plantTrace.longitudinalVelocity, LineWidth=1.5);
    hold on;
    yline(result.scenario.referenceSpeed, "k--");
    grid on;
    xlabel("Time (s)");
    ylabel("Ego longitudinal speed (m/s)");
    legend("Ego", "Reference", Location="best");
end

function valid = localPositiveScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value > 0.0;
end

function valid = localNonnegativeScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value) && value >= 0.0;
end

function valid = localFiniteScalar(value)
    valid = isnumeric(value) && isreal(value) && isscalar(value) ...
        && isfinite(value);
end

function valid = localLogicalScalar(value)
    valid = (islogical(value) || isnumeric(value)) ...
        && isscalar(value) && isfinite(value);
end

function valid = localScalarStruct(value)
    valid = isstruct(value) && isscalar(value);
end
