function validation = validateSharmaFairnessAudit(outputDirectory)
% validateSharmaFairnessAudit Regression tests and deterministic paired replay.
% Run from the repository root after runSharmaFairnessAudit completes.
    arguments
        outputDirectory (1, 1) string
    end
    root = fileparts(fileparts(mfilename("fullpath")));
    assert(string(pwd) == string(root), "Run validation from the repository root.");
    tests = ["sharmaBaselineObserverTest", "sharmaFairnessAuditTest", ...
        "onlineNrmmTrackingRuntimeTest", "nrmmDirectVelocityTest", ...
        "nrmmStructuredHighGainTest", "nrmmCascadeCertificateTest", ...
        "nrmmYawObserverTest", "observerGainSynthesisTest"];
    results = runtests(cellstr(fullfile(root, "tests", tests + ".m")));
    tableOfResults = table(string({results.Name}).', [results.Passed].', ...
        [results.Failed].', [results.Incomplete].', [results.Duration].', ...
        VariableNames=["Name", "Passed", "Failed", "Incomplete", "Duration"]);
    writetable(tableOfResults, fullfile(outputDirectory, "tests.csv"));

    loaded = load(fullfile(outputDirectory, "traces.mat"), "traces");
    recorded = loaded.traces.straightOncoming;
    prepared = rmfield(recorded.runs, ["estimate", "metrics"]);
    replay = runObserverComparisonScenario(Scenario="straightOncoming", ...
        Seed=recorded.options.Seed, Estimators=prepared, Report=false);
    exactMeasurements = isequaln(recorded.measurements, replay.measurements);
    exactTruth = isequaln(recorded.truth, replay.truth);
    exactEstimates = true;
    for index = 1:numel(prepared)
        exactEstimates = exactEstimates ...
            && isequaln(recorded.runs(index).estimate.targetState, replay.runs(index).estimate.targetState) ...
            && isequaln(recorded.runs(index).estimate.egoYaw, replay.runs(index).estimate.egoYaw);
    end
    sources = [fullfile("scripts", ["runSharmaFairnessAudit.m", ...
        "runNrmmOracleTargetComparison.m", "prepareSharmaGainCandidates.m", ...
        "runObserverComparisonScenario.m", "prepareObserverComparisonEstimators.m", ...
        "validateSharmaFairnessAudit.m", "runSharmaScenarioTunedAudit.m"]), ...
        fullfile("estimator", ["sharmaMultistageObserverRuntime.m", ...
        "sharmaMultistageObserverDesign.m", "sharmaNrmmCompanionDerivative.m"]), ...
        fullfile("tests", ["sharmaBaselineObserverTest.m", "sharmaFairnessAuditTest.m"])];
    analyzer = struct([]);
    for source = sources
        findings = checkcode(source, "-id");
        for finding = findings.'
            identifier = "";
            if isfield(finding, "id")
                identifier = string(finding.id);
            end
            analyzer = [analyzer; struct("source", source, "line", finding.line, ...
                "id", identifier, "message", string(finding.message))]; %#ok<AGROW>
        end
    end
    validation = struct("passed", nnz([results.Passed]), "failed", nnz([results.Failed]), ...
        "incomplete", nnz([results.Incomplete]), "exactReplayMeasurements", exactMeasurements, ...
        "exactReplayTruth", exactTruth, "exactReplayTargetAndYaw", exactEstimates, ...
        "analyzer", analyzer, "analyzedFiles", sources);
    file = fopen(fullfile(outputDirectory, "validation.json"), "w");
    closeFile = onCleanup(@() fclose(file));
    fprintf(file, "%s\n", jsonencode(validation, PrettyPrint=true));
    assertSuccess(results);
    assert(exactMeasurements && exactTruth && exactEstimates, ...
        "The deterministic trajectory replay must agree exactly (excluding wall time).");
end
