function result = verifyObserverControllerIntegration(outputFile)
%verifyObserverControllerIntegration Measure the implemented uncertainty interface.
% These are deterministic integration probes, not a robust closed-loop safety
% certificate. All true target hypotheses have constant acceleration/sideslip.
    arguments
        outputFile (1,1) string = ""
    end
    root=fileparts(fileparts(mfilename('fullpath')));
    addpath(fullfile(root,'controller'),fullfile(root,'config'),fullfile(root,'estimator'));
    [x,q,road,cfg]=collisionThreatScenario("headOn",struct('referenceSpeed',8,'controller',struct('horizonSteps',8)));
    probes=struct([]);inputPlans=cell(1,2);radii=[.01,.10];
    for index=1:numel(radii)
        [ego,target]=localPublication(x,q,0,radii(index));
        [command,inputs,prediction]=collisionAvoidanceController(ego,target,road,cfg,[]);
        inputPlans{index}=inputs;
        entry=struct('targetPositionRadiusMeters',radii(index),'input',command.actuatorInput, ...
            'maximumCollisionTighteningMeters',prediction.metadata.maximumCollisionTighteningMeters, ...
            'pcbfSlack',prediction.solution.safety,'clfSlack',prediction.solution.clfSlack, ...
            'solverCalls',prediction.metadata.solverCallCount,'runtimeSeconds',prediction.metadata.runtimeSeconds);
        probes=[probes,entry]; %#ok<AGROW>
    end
    [ego,target]=localPublication(x,q,0,.001);
    target.predictionErrorSet.accelerationInterval=q(5)+[-.002;.002];
    target.controllerErrorBound.bounds(5:6)=.002;
    [command,~,~,prior]=collisionAvoidanceController(ego,target,road,cfg,[]);
    next=nonlinearBicycleModel.sample(x,command.actuatorInput,cfg);
    updated=predictiveSafetyGeometry.predictTarget(q,cfg.controller.sampleTime);
    updated(1)=updated(1)+.001;updated(5)=updated(5)+.001;
    [ego,target]=localPublication(next,updated,cfg.controller.sampleTime,.001);
    target.predictionErrorSet.accelerationInterval=updated(5)+[-.002;.002];
    target.controllerErrorBound.bounds(5:6)=.002;
    ego.heldActuatorInput=command.actuatorInput;
    [~,~,second]=collisionAvoidanceController(ego,target,road,cfg,prior);

    % A genuine runtime publication with a declared, valid initial error prior.
    % Truth equals the initialized point; the bounds are deliberately nonzero.
    observerCfg=nrmmTrackingConfig();
    options=struct('initialTime',0,'egoInitialPosition',[0;0],'egoInitialYaw',0, ...
        'egoInitialBodyVelocity',[10;0],'targetInitialState',[20;5;-12;0;0;0], ...
        'initialErrorBounds',struct('yaw',.002,'bodyVelocity',.02,'targetComponents',[.12;.05;.02]));
    runtime=onlineNrmmTrackingRuntime("initialize",observerCfg,options);
    frame=struct('time',0,'xGps',0,'yGps',0,'vxGps',10,'vyGps',0, ...
        'longitudinalAcceleration',0,'lateralAcceleration',0,'yawRateMeasured',0,'radarRelativePosition',[20,5]);
    publication=onlineNrmmTrackingRuntime("output",runtime,frame);
    observerControllerCfg=collisionAvoidanceControllerConfig(struct('referenceSpeed',10,'controller',struct('horizonSteps',8)));
    line=struct('centerline',[-50,0;200,0]);
    [parsed,lane,~,observation]=readControllerInputs(publication,publication.targetEstimate,line,observerControllerCfg);
    targetCenter=predictiveSafetyGeometry.target(observation,publication.targetEstimate,observerControllerCfg);
    uncertainty=predictiveSafetyGeometry.observerUncertainty(parsed,observation,targetCenter);
    exact=publication;exact=rmfield(exact,{'controllerErrorBound','controllerStateErrorBound'});
    exact.targetEstimate=rmfield(exact.targetEstimate,{'controllerErrorBound','predictionErrorSet'});
    [~,~,baseline]=collisionAvoidanceController(exact,exact.targetEstimate,line,observerControllerCfg,[]);
    model=baseline.model;model.uncertainty=uncertainty;
    [solution,search,model]=solvePredictiveControl(model,[]);
    terminal=model.uncertaintyPrediction;
    runtimeProbe=struct('egoBounds',publication.controllerErrorBound.bounds, ...
        'parameterSet',publication.targetEstimate.predictionErrorSet, ...
        'relativeFrame',uncertainty.relativeFrame,'solutionReturned',~isempty(solution), ...
        'terminationReason',search.terminationReason,'terminalCoreRadius',terminal.terminalCoreRadius, ...
        'terminalReserve',terminal.terminalReserve, ...
        'terminalReserveToRadiusRatio',terminal.terminalReserve/terminal.terminalCoreRadius, ...
        'terminalLongitudinalSpeedHalfWidth',terminal.terminalCoreRadius/norm(model.terminal.quotientFactor(:,1)), ...
        'propagatedLongitudinalSpeedRadius',terminal.egoStateRadius(4,end), ...
        'uncertaintyHorizonSeconds',terminal.time(end),'targetPositionRadiusAtEnd',terminal.target.positionRadius(end));

    result=struct('scope',"Finite observer/controller integration probes; not nonlinear robust safety validation", ...
        'targetContract',"constantTangentialAccelerationAndSideslip",'configuration',cfg, ...
        'radiusProbes',probes,'inputPlanDifferenceFrobenius',norm(inputPlans{2}-inputPlans{1},'fro'), ...
        'estimateUpdate',struct('positionCorrectionMeters',.001,'accelerationCorrectionMetersPerSecondSquared',.001, ...
            'trueConstantAcceleration',q(5),'updatedAccelerationInterval',target.predictionErrorSet.accelerationInterval, ...
            'initialization',second.metadata.search.initialization,'budgetSource',second.metadata.safetyBudgetSource, ...
            'linearizationCount',second.metadata.search.linearizationCount), ...
        'runtimePublicationProbe',runtimeProbe, ...
        'nonlinearRobustSafetyCertified',false,'lane',lane);
    assert(result.inputPlanDifferenceFrobenius>1e-5);
    assert(probes(2).maximumCollisionTighteningMeters>probes(1).maximumCollisionTighteningMeters);
    assert(second.metadata.safetyBudgetSource=="primaryOptimum");
    if strlength(outputFile)>0
        folder=fileparts(outputFile);if strlength(folder)>0 && ~isfolder(folder),mkdir(folder);end
        fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
        fprintf(fid,'%s\n',jsonencode(result));
    end
    fprintf('Plan difference %.6g; real observer terminal reserve/core = %.6g; returned = %d.\n', ...
        result.inputPlanDifferenceFrobenius,runtimeProbe.terminalReserveToRadiusRatio,runtimeProbe.solutionReturned);
end

function [ego,target]=localPublication(x,q,time,radius)
    ego=struct('position',x(1:2),'yaw',x(3),'speed',x(4),'lateralVelocity',x(5),'yawRate',x(6), ...
        'stateTime',time,'heldActuatorInput',zeros(2,1), ...
        'controllerErrorBound',struct('kind',"ego-state-v1",'time',time,'bounds',zeros(6,1),'available',true));
    target=struct('targetPositionInertial',q(1:2),'targetVelocityInertial',q(4)*[cos(q(3)+q(6));sin(q(3)+q(6))], ...
        'targetAccelerationInertial',q(5)*[cos(q(3)+q(6));sin(q(3)+q(6))] ...
            +q(4)^2*sin(q(6))/q(7)*[-sin(q(3)+q(6));cos(q(3)+q(6))], ...
        'targetYawInertial',q(3),'targetSideslip',q(6),'targetTangentialAcceleration',q(5), ...
        'targetRearAxleDistance',q(7),'targetLength',2*q(8),'targetWidth',2*q(9),'targetRectangleOffset',q(10:11), ...
        'controllerErrorBound',struct('kind',"target-state-v1",'time',time, ...
            'bounds',[radius;radius;zeros(6,1)],'available',true));
    rotation=[cos(x(3)),-sin(x(3));sin(x(3)),cos(x(3))];
    target.predictionErrorSet=struct('kind',"nrmm-constant-parameter-set-v1",'time',time,'available',true, ...
        'referenceEgoPose',x(1:3),'relativePosition',rotation.'*(q(1:2)-x(1:2)), ...
        'positionRadius',radius,'courseCenter',q(3)+q(6)-x(3),'courseRadius',0, ...
        'speedInterval',q(4)*ones(2,1),'accelerationInterval',q(5)*ones(2,1), ...
        'curvatureInterval',sin(q(6))/q(7)*ones(2,1),'rearAxleDistance',q(7));
end
