function certificate = certifyAvoidancePlan(qp, prediction, model, decision)
%certifyAvoidancePlan Check the exact vector to be stored and committed.
% Checks bounds, hard rows, rest equalities, exact first-step CLF and actual
% rectangle clearance at every prediction node. Solver status is separate.

    arguments
        qp (1,1) struct
        prediction (1,1) struct
        model (1,1) struct
        decision
    end
    certificate = struct("accepted", false, "boundViolation", inf, ...
        "hardRowViolation", inf, "equalityViolation", inf, ...
        "clfViolation", inf, "nodeClearanceMargin", -inf, ...
        "routeCoordinateValid", false, "failedConditions", "decision");
    if ~isnumeric(decision) || ~isreal(decision) || ~isvector(decision) ...
            || numel(decision) ~= qp.layout.decisionCount ...
            || any(~isfinite(decision), "all")
        return;
    end
    decision = decision(:);
    plan = decision(qp.layout.planIndex);
    tolerance = 10.0*model.cfg.solver.constraintTolerance;
    certificate.boundViolation = max([0.0; qp.lowerBound-decision; ...
        decision-qp.upperBound]);
    certificate.hardRowViolation = max([0.0; ...
        qp.inequalityMatrix*decision-qp.inequalityBound]);
    certificate.equalityViolation = norm( ...
        qp.equalityMatrix*decision-qp.equalityBound, inf);
    clf = qp.clf;
    currentError = clf.errorOffset(:, 1);
    nextError = clf.errorMatrix(:, :, 2)*plan+clf.errorOffset(:, 2);
    certificate.clfViolation = nextError.'*clf.lyapunovMatrix*nextError ...
        - currentError.'*(clf.lyapunovMatrix-clf.decreaseMatrix)*currentError ...
        - decision(qp.layout.relaxationIndex);
    clfTolerance = max(tolerance, 100.0*eps(1.0+clf.initialValue));
    state = squeeze(pagemtimes(prediction.egoStateMatrix, plan)) ...
        + prediction.egoStateOffset;
    if any(~isfinite(state), "all")
        certificate.failedConditions = "finitePrediction";
        return;
    end
    [position, heading] = lanePoseFromFrenet(state, model.lane);
    certificate.nodeClearanceMargin = inf;
    certificate.routeCoordinateValid = true;
    dimensions = [model.egoHalfLength; model.egoHalfWidth; ...
        model.targetHalfLength; model.targetHalfWidth];
    for nodeIdx = 1:prediction.nodeCount
        frame = qp.geometry.frames(nodeIdx);
        certificate.routeCoordinateValid = certificate.routeCoordinateValid ...
            && state(1, nodeIdx) >= frame.stationLower-tolerance ...
            && state(1, nodeIdx) <= frame.stationUpper+tolerance;
        if model.hasTarget
            distance = rectangleConfigurationDistance(position(:, nodeIdx), ...
                heading(nodeIdx), ...
                model.targetHorizon.targetPosition(:, nodeIdx), ...
                model.targetHorizon.targetYaw(nodeIdx), dimensions);
            certificate.nodeClearanceMargin = min(certificate.nodeClearanceMargin, ...
                distance-model.cfg.collision.clearanceMargin);
        end
    end
    names = ["bounds", "hardRows", "terminalRest", "exactClf", ...
        "routeDomain", "nodeClearance", "finiteProblem"];
    conditions = [certificate.boundViolation <= tolerance, ...
        certificate.hardRowViolation <= tolerance, ...
        certificate.equalityViolation <= tolerance, ...
        certificate.clfViolation <= clfTolerance, ...
        certificate.routeCoordinateValid, ...
        certificate.nodeClearanceMargin >= -tolerance, ...
        ~qp.certifiedInfeasible];
    certificate.failedConditions = names(~conditions);
    certificate.accepted = all(conditions);
end
