function [command,predictedInput,planningProblem,controllerState] = ...
        collisionAvoidanceController(egoState,targetEstimate,laneCenterline,cfg,previousState)
%collisionAvoidanceController Joint-state predictive safety and lane CLF recovery.
% Every input belongs to a validated nonlinear plan ending in an invariant
% cruise backup. See NONLINEAR_PREDICTIVE_CBF.md for the exact-model contract.
    persistent lastState
    if nargin==1 && (ischar(egoState) || isstring(egoState))
        if ~isscalar(string(egoState)) || string(egoState)~="resetNominalTrajectory"
            error('collisionAvoidanceController:invalidAction','Use resetNominalTrajectory.');
        end
        lastState=[];command=[];predictedInput=[];planningProblem=[];controllerState=[];return;
    end
    explicitState=nargin>=5;
    if ~explicitState,previousState=lastState;end
    if nargin<4,cfg=[];end
    if nargin<3,laneCenterline=[];end
    if nargin<2,targetEstimate=[];end
    timer=tic;cfg=collisionAvoidanceControllerConfig(cfg);
    if cfg.collision.safetyMarginMeters<=0
        error('collisionAvoidanceController:positiveClearanceRequired','Rectangular separation requires strictly positive clearance.');
    end
    if exist('nonlinearSafetyMex','file')~=3 || exist('fialaFeedbackSampleMex','file')~=3
        error('collisionAvoidanceController:missingFialaVerifier', ...
            'Build the MPFR verifiers using buildFialaIntervalVerifier and add their output directory.');
    end
    [ego,lane,road,observation]=readPlanningInputs(egoState,targetEstimate,laneCenterline,cfg);
    if any(ego.stateErrorBound) || any(cfg.model.ltvModelErrorRateBound) ...
            || any(cfg.model.plantModelResidualRateBound) || ego.longitudinalAccelerationBias~=0
        error('collisionAvoidanceController:nonexactStudyInput', ...
            'This witness requires exact state and model data; uncertainty needs a robust invariant backup.');
    end
    if isempty(targetEstimate) && isfield(egoState,'targetEstimate'),targetEstimate=egoState.targetEstimate;end
    q=nonlinearSafetyCertificate.target(observation,targetEstimate,cfg);
    [q,targetAnchor,targetStep]=localTargetContinuation(q,previousState,ego.stateTime,cfg);
    frame=nonlinearSafetyCertificate.roadFrame(lane,road);
    backup=nonlinearSafetyCertificate.backup(cfg,frame);
    previous=zeros(2,1);
    if ~isempty(ego.heldActuatorInput),previous=ego.heldActuatorInput;
    elseif isstruct(previousState) && isfield(previousState,'appliedInput'),previous=previousState.appliedInput;
    elseif any(isfinite([cfg.model.frontWheelSteeringRateMaximum,cfg.model.brakingRatioRateMaximum]))
        error('collisionAvoidanceController:missingInputMemory','Finite slew limits require the previous applied input.');
    end
    identityCfg=rmfield(cfg,'solver');identityCfg.nonlinear.initialPlan=zeros(2,0);
    identityCfg.nonlinear.proposalFunction=[];identityCfg.nonlinear.maximumImprovementIterations=0;
    identityCfg.nonlinear.maximumAdmissionIterations=0;identityCfg.nonlinear.trustRadius=0;
    identityCfg.nonlinear.recoveryHorizonSeconds=0;identityCfg.nonlinear.optimizationClearanceMeters=0;
    identityCfg.nonlinear.maximumCertificateSeconds=Inf;identityCfg.nonlinear.maximumCertificateCells=20000;
    identity=struct('configuration',identityCfg,'lane',lane,'road',road,'targetAnchor',targetAnchor);
    jointState=ego.modelState;targetParameters=zeros(7,0);
    if ~isempty(q),jointState=[jointState;q(1:3)];targetParameters=q(4:10);end
    model=struct('cfg',cfg,'initialState',ego.modelState,'jointState',jointState, ...
        'targetParameters',targetParameters,'previousInput',previous,'target',q, ...
        'lane',lane,'road',road,'frame',frame,'backup',backup,'identity',identity, ...
        'targetAnchor',targetAnchor,'targetStep',targetStep,'stateTime',ego.stateTime);
    [certificate,search]=solveNonlinearPredictivePlan(model,previousState);
    if isempty(certificate)
        error('collisionAvoidanceController:optimizationFailed', ...
            'No nonlinear continuation into the invariant backup was certified (%s). No command was issued.',search.lastRejection);
    end
    predictedInput=certificate.inputs;first=predictedInput(:,1);
    command=localCommand(first,ego.modelState,cfg);
    command.measurementTime=ego.stateTime;command.actuationTime=ego.stateTime;command.holdSeconds=cfg.controller.sampleTime;
    metadata=struct('planCertified',true,'predictiveBarrierValue',0, ...
        'safetyScope',"nonlinearHorizonThenInvariantCruise", ...
        'predictionModel',"nonlinearCombinedSlipFialaZoh",'certificateArithmetic',"directed128BitMpfr", ...
        'wholeHoldCertificate',true,'certificateSampling',"validatedSweptIntervals", ...
        'recursiveFeasibilityGuaranteed',true, ...
        'recursiveFeasibilityScope',"exactSuccessorsAndUnchangedTargetRoadModelContracts", ...
        'terminalContinuationCertified',true,'terminalPolicyRole',"executableInvariantBackup", ...
        'stateAndSlipBoundsEnforced',false,'stateBoundsEnforced',true,'positiveSpeedDomainEnforced',true, ...
        'hasTarget',~isempty(q),'targetMotionModel',"constantTangentialSpeedAndHeadingRate", ...
        'jointStateDimension',numel(jointState),'safetyObjective',"sumOfStageSafetySlacks", ...
        'preplannedAvoidanceTrajectoryRequired',false,'drivingModeSwitching',false, ...
        'clfSlack',certificate.clfSlack,'clfInitialValue',certificate.clfInitialValue, ...
        'clfNextValue',certificate.clfNextValueUpper,'clfDecayPerHold',cfg.nonlinear.clfDecay, ...
        'clfDissipationCertified',certificate.clfAvailable && certificate.clfSlack==0, ...
        'clfAvailable',certificate.clfAvailable, ...
        'clfDissipationScope',"verifiedFirstHoldOnConstantCurvatureReference", ...
        'clfMatrix',backup.reference.matrix,'clfReferenceState',backup.reference.state, ...
        'clfOperatingInput',backup.reference.input,'clfOperatingCurvature',frame(4), ...
        'certificateSource',search.source,'carriedWitnessAvailable',search.shiftAttempted, ...
        'fallbackUsed',certificate.inherited,'inheritedCertificate',certificate.inherited, ...
        'terminalBackupDispatched',certificate.terminalOnly, ...
        'solverAlgorithm',"huangSafetyPriorityLiDualSequentialConvexification", ...
        'convexSubproblemsAreCertifiedInnerApproximations',false, ...
        'nonlinearAcceptanceRequired',true,'positiveSlackExecutionAllowed',false, ...
        'solverCallCount',search.solverCalls,'admissionSearch',search, ...
        'minimumCollisionMargin',certificate.minimumCollisionMargin,'minimumRoadMargin',certificate.minimumRoadMargin, ...
        'horizonSteps',size(predictedInput,2),'certifiedDuration',size(predictedInput,2)*cfg.controller.sampleTime, ...
        'predictedNextState',certificate.states(:,2),'initialEgoState',ego.modelState,'runtimeSeconds',toc(timer));
    predictedJointState=certificate.states;
    if ~isempty(q)
        targetStates=zeros(3,size(certificate.states,2));
        for index=1:size(targetStates,2)
            future=nonlinearSafetyCertificate.targetFlow(targetAnchor,(targetStep+index-1)*cfg.controller.sampleTime);
            targetStates(:,index)=future(1:3);
        end
        predictedJointState=[predictedJointState;targetStates];
    end
    controllerState=struct('version',48,'identity',identity,'stateTime',ego.stateTime, ...
        'jointState',jointState,'predictedJointState',predictedJointState, ...
        'appliedInput',first,'plan',predictedInput,'predictedState',certificate.states, ...
        'certificate',certificate,'backup',backup,'target',q,'targetAnchor',targetAnchor,'targetStep',targetStep);
    planningProblem=struct('problemClass',"nonlinearPredictiveCbfClf",'model',model, ...
        'inputPlan',predictedInput,'predictedState',certificate.states,'predictedJointState',predictedJointState, ...
        'certificate',certificate,'metadata',metadata);
    if ~explicitState,lastState=controllerState;end
end

function [q,anchor,step]=localTargetContinuation(q,prior,time,cfg)
    anchor=q;step=0;
    if (~isempty(q) || (isstruct(prior) && isfield(prior,'targetAnchor') && ~isempty(prior.targetAnchor))) && ~isfinite(time)
        error('collisionAvoidanceController:missingTargetClock','A retained target trajectory requires a finite stateTime.');
    end
    if ~isstruct(prior) || ~isfield(prior,'version') || prior.version~=48 ...
            || ~isfield(prior,'targetAnchor') || isempty(prior.targetAnchor),return;end
    tolerance=cfg.nonlinear.targetConsistencyTolerance;
    h=cfg.controller.sampleTime;
    if h~=prior.identity.configuration.controller.sampleTime ...
            || (isfinite(time) && isfinite(prior.stateTime) && abs(time-prior.stateTime-h)>tolerance)
        error('collisionAvoidanceController:inconsistentTargetClock', ...
            'A retained constant-parameter target requires one unchanged sampling interval per call.');
    end
    anchor=prior.targetAnchor;step=prior.targetStep+1;
    expected=nonlinearSafetyCertificate.targetFlow(anchor,step*h);
    if ~isempty(q)
        difference=q-expected;difference(3)=atan2(sin(difference(3)),cos(difference(3)));
        if any(abs(difference)>tolerance)
            error('collisionAvoidanceController:inconsistentTargetObservation', ...
                'The target differs from its immutable constant-speed/heading-rate prediction. Reset for a new admission.');
        end
    end
    % Observation agreement is a diagnostic, not an uncertainty certificate.
    % The immutable epoch model remains authoritative, including during dropout.
    q=expected;
end

function command=localCommand(input,state,cfg)
    tire=modifiedFialaTire.parameters(cfg);force=modifiedFialaTire.longitudinalForce(input(2),cfg);
    slip=atan2([state(5)+cfg.vehicle.lf*state(6);state(5)-cfg.vehicle.lr*state(6)],state(4))-[input(1);0];
    lateral=modifiedFialaTire.evaluate(slip,input(2),cfg);dx=nonlinearBicycleModel.derivative(state,input,cfg);
    [road,~,components]=ltvBicycleModel.roadLoad(state(4),cfg);
    rolling=components.rollingResistanceForce*tire.staticNormalLoad/(cfg.vehicle.m*cfg.vehicle.gravity);
    command=struct('actuatorInput',input,'frontWheelSteeringAngle',input(1),'brakingRatio',input(2), ...
        'actuatorInputOrder',["frontWheelSteeringAngle","brakingRatio"], ...
        'longitudinalAcceleration',modifiedFialaTire.accelerationGain(cfg)*input(2), ...
        'bodyLongitudinalVelocityDerivative',dx(4),'lateralAcceleration',dx(5),'yawAcceleration',dx(6), ...
        'totalLongitudinalActuatorForce',sum(force),'totalLongitudinalTireForce',sum(force-rolling), ...
        'axleLongitudinalTireForce',force-rolling,'axleLongitudinalForce',force, ...
        'axleLateralForce',lateral,'axleNormalLoad',tire.staticNormalLoad,'tireSideslipAngle',slip, ...
        'aerodynamicResistanceForce',components.aerodynamicForce, ...
        'rollingResistanceForce',components.rollingResistanceForce,'totalRoadLoadForce',road);
end
