function [command,predictedInput,prediction,controllerState] = ...
        collisionAvoidanceController(egoState,targetEstimate,laneCenterline,cfg,previousState)
%collisionAvoidanceController Two-stage PCBF/CLF optimization; no fallback algorithm.
% Controller state retains a target prediction and a linearization trajectory.
% Every current target estimate updates the prediction; its A and beta are
% held constant within this frame, independently of proof-metadata availability.
% Passing [] as previousState starts a new problem and a new target epoch.
% Collision interaction is active inside the configured position radius.
% A complete current sensor scan with no target clears the previous forecast.
    persistent lastState
    if nargin==1 && (ischar(egoState) || isstring(egoState))
        if ~isscalar(string(egoState)) || string(egoState)~="resetNominalTrajectory"
            error('collisionAvoidanceController:invalidAction','Use resetNominalTrajectory.');
        end
        lastState=[];command=[];predictedInput=[];prediction=[];controllerState=[];return;
    end
    explicitState=nargin>=5;
    if ~explicitState,previousState=lastState;end
    if isstruct(previousState) && (~isfield(previousState,'version') || previousState.version~=77),previousState=[];end
    if nargin<4,cfg=[];end
    if nargin<3,laneCenterline=[];end
    if nargin<2,targetEstimate=[];end
    timer=tic;cfg=collisionAvoidanceControllerConfig(cfg);
    [ego,lane,road,observation]=readControllerInputs(egoState,targetEstimate,laneCenterline,cfg);
    if isempty(targetEstimate) && isfield(egoState,'targetEstimate'),targetEstimate=egoState.targetEstimate;end
    observed=predictiveSafetyGeometry.target(observation,targetEstimate,cfg);
    uncertainty=predictiveSafetyGeometry.observerUncertainty(ego,observation,observed);
    frame=predictiveSafetyGeometry.roadFrame(lane,road);
    context={cfg.vehicle,cfg.tire,cfg.roadLoad,cfg.model,cfg.actuation,cfg.collision, ...
        cfg.controller,cfg.referenceSpeed,cfg.clf,cfg.nominalClf,cfg.initialization, ...
        cfg.nonlinear.integrationStep,cfg.terminal,frame,lane};
    index=0;epochTime=ego.stateTime;targetEpoch=observed;
    if isstruct(previousState)
        if ~isequaln(context,previousState.context)
            error('collisionAvoidanceController:changedContinuationProblem', ...
                'Model, constraints or reference path changed. Pass an empty previousState to initialize a new problem.');
        end
        index=previousState.sampleIndex+1;epochTime=previousState.epochTime;targetEpoch=previousState.targetEpoch;
        expectedTime=epochTime+index*cfg.controller.sampleTime;
        if isfinite(ego.stateTime) && isfinite(epochTime) && abs(ego.stateTime-expectedTime)>1e-9*max(1,abs(expectedTime))
            error('collisionAvoidanceController:invalidSampleTime','Continuation requires consecutive absolute sample times.');
        end
    end
    if isempty(observed) && isfield(egoState,'perception')
        perception=egoState.perception;
        if isstruct(perception) && isscalar(perception) ...
                && all(isfield(perception,{'time','completeWithinRange'})) ...
                && isequal(perception.completeWithinRange,true) && isequal(perception.time,ego.stateTime)
            targetEpoch=[];
        end
    end
    q=predictiveSafetyGeometry.predictTarget(targetEpoch,index*cfg.controller.sampleTime);
    if ~isempty(observed) && ~isempty(q)
        observed(3)=q(3)+atan2(sin(observed(3)-q(3)),cos(observed(3)-q(3)));
    end
    if ~isempty(observed)
        % Reanchor the prediction at the current estimate without resetting
        % the ego input warm start. Cross-frame constancy is not required.
        targetEpoch=predictiveSafetyGeometry.predictTarget(observed,-index*cfg.controller.sampleTime);
        q=observed;
    end
    previous=zeros(2,1);
    if ~isempty(ego.heldActuatorInput),previous=ego.heldActuatorInput;
    elseif isstruct(previousState),previous=previousState.appliedInput;
    elseif isfinite(cfg.model.brakingRatioRateMaximum)
        error('collisionAvoidanceController:missingInputMemory','Finite slew limits require the previous applied input.');
    end
    jointState=ego.modelState;targetParameters=zeros(7,0);
    if ~isempty(q),jointState=[jointState;q(1:4)];targetParameters=q(5:11);end
    nominalReference=nonlinearBicycleModel.cruise(cfg,frame(4));
    model=struct('cfg',cfg,'initialState',ego.modelState,'jointState',jointState, ...
        'targetParameters',targetParameters,'previousInput',previous,'target',q,'targetEpoch',targetEpoch, ...
        'sampleIndex',index,'epochTime',epochTime,'lane',lane,'road',road,'frame',frame, ...
        'nominalReference',nominalReference,'stateTime',ego.stateTime, ...
        'uncertainty',uncertainty);
    [solution,search,model]=solvePredictiveControl(model,previousState,timer);
    if isempty(solution)
        error('collisionAvoidanceController:noOptimizationSolution', ...
            'The two-stage affine optimization did not complete (%s).',search.terminationReason);
    end
    predictedInput=solution.inputs;first=predictedInput(:,1);
    command=localCommand(first,ego.modelState,cfg);
    command.measurementTime=ego.stateTime;command.actuationTime=ego.stateTime;command.holdSeconds=cfg.controller.sampleTime;
    predictedJointState=solution.states;
    if ~isempty(q)
        targetStates=zeros(4,size(solution.states,2));
        for step=1:size(targetStates,2)
            future=predictiveSafetyGeometry.predictTarget(targetEpoch,(index+step-1)*cfg.controller.sampleTime);
            targetStates(:,step)=future(1:4);
        end
        predictedJointState=[predictedJointState;targetStates];
    end
    metadata=struct('optimizationReturned',search.returned,'predictiveBarrierValue',solution.safety, ...
        'zeroSlack',solution.safety<=cfg.solver.lexicographicTieTolerance+cfg.solver.feasibilityTolerance,'safetyScope',"nonlinearRolloutSampledConstraints", ...
        'predictionModel',"nonlinearFialaRk4RolloutOfAffineStep",'affineValidationPerformed',false,'nonlinearValidationPerformed',true, ...
        'recursiveFeasibilityScope',"shiftedPlanOnDeclaredModelWithConsistentForecast", ...
        'hasTarget',~isempty(q),'targetMotionModel',"constantTangentialAccelerationAndSideslip", ...
        'jointStateDimension',numel(jointState), ...
        'safetyObjective',"sumOfPrefixSafetySlacks",'primaryOptimumComputed',true, ...
        'safetyValueInterpretation',"nonlinearPrefixDeficitSum", ...
        'secondaryObjective',"minimumClfSlackWithBoundedProximalTie", ...
        'secondaryOptimumApplied',true, ...
        'tertiaryObjective',"none",'clfTieTolerance',cfg.solver.clfTieTolerance, ...
        'preplannedAvoidanceTrajectoryRequired',false,'drivingModeSwitching',false, ...
        'clfSlack',solution.clfSlack,'clfInitialValue',solution.clfInitialValue, ...
        'clfNextValue',solution.clfNextValue,'clfSatisfied',search.clfLowerBound,'clfContraction',nominalReference.contraction,'clfConvergenceTimeConstantSeconds',cfg.clf.convergenceTimeConstantSeconds, ...
        'clfFunction',solution.clfFunction,'clfRequiredDecrease',solution.clfRequiredDecrease, ...
        'clfTieBound',solution.clfTieBound,'clfLocalModel',"quadraticOnAffineFirstSuccessor", ...
        'nominalTrackingMatrix',nominalReference.matrix,'clfReferenceState',nominalReference.state, ...
        'clfOperatingInput',nominalReference.input,'clfOperatingCurvature',frame(4), ...
        'controlSource',search.source,'solverAlgorithm',"budgetedConicQp", ...
        'nonlinearPredictionEvaluated',true, ...
        'solverCallCount',search.solverCalls,'search',search,'hardConstraintResidual',solution.hard, ...
        'optimizationConverged',search.converged,'affineFeasibilityTolerance',cfg.solver.feasibilityTolerance,'minimumCollisionMargin',solution.minimumCollisionMargin, ...
        'roadConstraintsEnforced',~isempty(road.lateralClearance),'roadConstraintScope',"rectangleAtEveryPredictedNode", ...
        'horizonSteps',size(predictedInput,2), ...
        'prefixSteps',cfg.controller.horizonSteps,'completionSteps',size(predictedInput,2)-cfg.controller.horizonSteps, ...
        'absoluteSampleIndex',index,'endpointIndex',index+size(predictedInput,2), ...
        'terminalSet',"laneHoldBackupSafeExit", ...
        'terminalValue',solution.terminalValue,'terminalLevel',solution.terminalLevel, ...
        'terminalExitSeconds',solution.terminalExitSeconds,'terminalLaneOffset',solution.terminalLaneOffset, ...
        'terminalEnd',solution.terminalEnd, ...
        'terminalDistanceMeters',solution.terminalDistanceMeters, ...
        'terminalRoadMarginMeters',solution.terminalRoadMarginMeters, ...
        'acceptedStep',solution.acceptedStep,'candidateFeasible',solution.candidateFeasible, ...
        'anchorCertified',search.anchorCertified,'appendedTerminalSteps',search.appendedTerminalSteps, ...
        'linearizationGapMeters',solution.linearizationGap, ...
        'encounterRangeMeters',cfg.collision.encounterRangeMeters,'encounterExitStep',solution.encounterExit, ...
        'predictedNextState',solution.states(:,2),'initialEgoState',ego.modelState,'runtimeSeconds',toc(timer));
    metadata.trust=search.trust;
    metadata.uncertaintyIncluded=uncertainty.specified;
    metadata.commonPoseCancelled=uncertainty.relativeFrame;
    metadata.targetUncertaintyModel="constantParametersRestartedEachHoldFromCurrentObserverSet";
    metadata.egoUncertaintyModel="currentPosteriorEnclosurePropagatedThroughEachHold";
    metadata.robustNonlinearSafetyCertified=false;
    metadata.maximumCollisionTighteningMeters=solution.maximumCollisionTighteningMeters;
    metadata.clfWorstNextValue=solution.clfWorstNextValue;
    metadata.clfCurrentBudget=solution.clfCurrentBudget;
    if uncertainty.specified
        metadata.safetyScope="observerTightenedAffineSampledConstraints";
    end
    if model.robustnessRelaxation
        metadata.safetyObjective="sumOfRobustnessDeficitsWithHardNominalCollisionRows";
        metadata.safetyScope="hardNominalGeometryWithRelaxedObserverMargins";
    end
    controllerState=struct('version',77,'trust',model.trust,'stateTime',ego.stateTime,'sampleTime',cfg.controller.sampleTime, ...
        'sampleIndex',index,'epochTime',epochTime,'targetEpoch',targetEpoch,'context',{context}, ...
        'jointState',jointState,'predictedJointState',predictedJointState, ...
        'appliedInput',first,'inputTrajectory',predictedInput,'stateTrajectory',solution.states, ...
        'stageSlacks',solution.stageSlacks,'safetyBudget',solution.safety, ...
        'target',q,'uncertaintySpecified',uncertainty.specified);
    prediction=struct('problemClass',"jointPredictiveCbfClf",'model',model, ...
        'inputTrajectory',predictedInput,'predictedState',solution.states,'predictedJointState',predictedJointState, ...
        'solution',solution,'metadata',metadata);
    if ~explicitState,lastState=controllerState;end
end

function command=localCommand(input,state,cfg)
    tire=modifiedFialaTire.parameters(cfg);force=modifiedFialaTire.longitudinalForce(input(2),cfg);
    slip=atan2([state(5)+cfg.vehicle.lf*state(6);state(5)-cfg.vehicle.lr*state(6)],state(4))-[input(1);0];
    lateral=modifiedFialaTire.evaluate(slip,input(2),cfg);dx=nonlinearBicycleModel.derivative(state,input,cfg);
    [road,~,components]=nonlinearBicycleModel.roadLoad(state(4),cfg);
    rolling=components.rollingResistanceForce*tire.staticNormalLoad/(cfg.vehicle.m*cfg.vehicle.gravity);
    command=struct('actuatorInput',input,'frontWheelSteeringAngle',input(1),'brakingRatio',input(2), ...
        'actuatorInputOrder',["frontWheelSteeringAngle","brakingRatio"], ...
        'longitudinalAcceleration',modifiedFialaTire.accelerationGain(cfg)*input(2), ...
        'bodyLongitudinalVelocityDerivative',dx(4),'lateralAcceleration',dx(5),'yawAcceleration',dx(6), ...
        'totalLongitudinalActuatorForce',sum(force),'totalLongitudinalTireForce',sum(force-rolling), ...
        'axleLongitudinalTireForce',force-rolling,'axleLongitudinalForce',force, ...
        'axleLateralForce',lateral,'axleNormalLoad',tire.staticNormalLoad,'tireSideslipAngle',slip, ...
        'aerodynamicResistanceForce',components.aerodynamicForce, ...
        'rollingResistanceForce',components.rollingResistanceForce,'totalRoadLoadForce',road);
end
