function [command,predictedInput,prediction,controllerState] = ...
        collisionAvoidanceController(egoState,targetEstimate,laneCenterline,cfg,previousState)
%collisionAvoidanceController Joint-state PCBF, lane CLF and dual-variable SCvx.
% The first control of the nominal MPC solution is applied directly. See
% PCBF_CLF_ARCHITECTURE.md for the terminal assumptions and numerical scope.
    persistent lastState
    if nargin==1 && (ischar(egoState) || isstring(egoState))
        if ~isscalar(string(egoState)) || string(egoState)~="resetNominalTrajectory"
            error('collisionAvoidanceController:invalidAction','Use resetNominalTrajectory.');
        end
        lastState=[];command=[];predictedInput=[];prediction=[];controllerState=[];return;
    end
    explicitState=nargin>=5;
    if ~explicitState,previousState=lastState;end
    if isstruct(previousState) && (~isfield(previousState,'version') || previousState.version~=51)
        previousState=[];
    end
    if nargin<4,cfg=[];end
    if nargin<3,laneCenterline=[];end
    if nargin<2,targetEstimate=[];end
    timer=tic;cfg=collisionAvoidanceControllerConfig(cfg);
    [ego,lane,road,observation]=readControllerInputs(egoState,targetEstimate,laneCenterline,cfg);
    if isempty(targetEstimate) && isfield(egoState,'targetEstimate'),targetEstimate=egoState.targetEstimate;end
    q=predictiveSafetyGeometry.target(observation,targetEstimate,cfg);
    % Each observation initializes the current joint state. During a dropout,
    % propagate the previous target with the same constant-parameter model.
    if isempty(q) && isstruct(previousState) && isfield(previousState,'target') && ~isempty(previousState.target)
        elapsed=cfg.controller.sampleTime;
        if isfinite(ego.stateTime) && isfinite(previousState.stateTime)
            elapsed=max(0,ego.stateTime-previousState.stateTime);
        end
        q=predictiveSafetyGeometry.targetFlow(previousState.target,elapsed);
    end
    frame=predictiveSafetyGeometry.roadFrame(lane,road);
    terminal=predictiveSafetyGeometry.terminalSet(cfg,frame);
    previous=zeros(2,1);
    if ~isempty(ego.heldActuatorInput),previous=ego.heldActuatorInput;
    elseif isstruct(previousState) && isfield(previousState,'appliedInput'),previous=previousState.appliedInput;
    elseif any(isfinite([cfg.model.frontWheelSteeringRateMaximum,cfg.model.brakingRatioRateMaximum]))
        error('collisionAvoidanceController:missingInputMemory','Finite slew limits require the previous applied input.');
    end
    jointState=ego.modelState;targetParameters=zeros(7,0);
    if ~isempty(q),jointState=[jointState;q(1:4)];targetParameters=q(5:11);end
    model=struct('cfg',cfg,'initialState',ego.modelState,'jointState',jointState, ...
        'targetParameters',targetParameters,'previousInput',previous,'target',q, ...
        'lane',lane,'road',road,'frame',frame,'terminal',terminal,'stateTime',ego.stateTime);
    [solution,search]=solvePredictiveControl(model,previousState);
    if isempty(solution)
        error('collisionAvoidanceController:optimizationFailed', ...
            'SCvx returned no control result (%s).',search.terminationReason);
    end
    predictedInput=solution.inputs;first=predictedInput(:,1);
    command=localCommand(first,ego.modelState,cfg);
    command.measurementTime=ego.stateTime;command.actuationTime=ego.stateTime;command.holdSeconds=cfg.controller.sampleTime;
    predictedJointState=solution.states;
    if ~isempty(q)
        targetStates=zeros(4,size(solution.states,2));
        for index=1:size(targetStates,2)
            future=predictiveSafetyGeometry.targetFlow(q,(index-1)*cfg.controller.sampleTime);
            targetStates(:,index)=future(1:4);
        end
        predictedJointState=[predictedJointState;targetStates];
    end
    metadata=struct('optimizationReturned',true,'predictiveBarrierValue',solution.safety, ...
        'zeroSlack',solution.safety<=cfg.solver.feasibilityTolerance, ...
        'safetyScope',"nominalSampledPrediction",'predictionModel',"nonlinearCombinedSlipFialaRk4", ...
        'recursiveFeasibilityScope',"nominalMpcWithInvariantTerminalSetAndFeasibleScvxSolve", ...
        'hasTarget',~isempty(q),'targetMotionModel',"constantTangentialAccelerationAndSideslip", ...
        'jointStateDimension',numel(jointState),'safetyObjective',"sumOfStageSafetySlacks", ...
        'preplannedAvoidanceTrajectoryRequired',false,'drivingModeSwitching',false, ...
        'clfSlack',solution.clfSlack,'clfInitialValue',solution.clfInitialValue, ...
        'clfNextValue',solution.clfNextValue,'clfDecayPerHold',cfg.nonlinear.clfDecay, ...
        'clfMatrix',terminal.reference.matrix,'clfReferenceState',terminal.reference.state, ...
        'clfOperatingInput',terminal.reference.input,'clfOperatingCurvature',frame(4), ...
        'controlSource',search.source, ...
        'solverAlgorithm',"huangSafetyPriorityLiDualSequentialConvexification", ...
        'solverCallCount',search.solverCalls,'search',search, ...
        'hardConstraintResidual',solution.hard,'scvxConverged',search.converged, ...
        'minimumCollisionMargin',solution.minimumCollisionMargin,'minimumRoadMargin',solution.minimumRoadMargin, ...
        'horizonSteps',size(predictedInput,2),'predictedNextState',solution.states(:,2), ...
        'initialEgoState',ego.modelState,'runtimeSeconds',toc(timer));
    controllerState=struct('version',51,'stateTime',ego.stateTime,'sampleTime',cfg.controller.sampleTime, ...
        'jointState',jointState,'predictedJointState',predictedJointState, ...
        'appliedInput',first,'inputTrajectory',predictedInput,'stateTrajectory',solution.states,'target',q);
    prediction=struct('problemClass',"jointPredictiveCbfClf",'model',model, ...
        'inputTrajectory',predictedInput,'predictedState',solution.states,'predictedJointState',predictedJointState, ...
        'solution',solution,'metadata',metadata);
    if ~explicitState,lastState=controllerState;end
end

function command=localCommand(input,state,cfg)
    tire=modifiedFialaTire.parameters(cfg);force=modifiedFialaTire.longitudinalForce(input(2),cfg);
    slip=atan2([state(5)+cfg.vehicle.lf*state(6);state(5)-cfg.vehicle.lr*state(6)],state(4))-[input(1);0];
    lateral=modifiedFialaTire.evaluate(slip,input(2),cfg);dx=nonlinearBicycleModel.derivative(state,input,cfg);
    [road,~,components]=nonlinearBicycleModel.roadLoad(state(4),cfg);
    rolling=components.rollingResistanceForce*tire.staticNormalLoad/(cfg.vehicle.m*cfg.vehicle.gravity);
    command=struct('actuatorInput',input,'frontWheelSteeringAngle',input(1),'brakingRatio',input(2), ...
        'actuatorInputOrder',["frontWheelSteeringAngle","brakingRatio"], ...
        'longitudinalAcceleration',modifiedFialaTire.accelerationGain(cfg)*input(2), ...
        'bodyLongitudinalVelocityDerivative',dx(4),'lateralAcceleration',dx(5),'yawAcceleration',dx(6), ...
        'totalLongitudinalActuatorForce',sum(force),'totalLongitudinalTireForce',sum(force-rolling), ...
        'axleLongitudinalTireForce',force-rolling,'axleLongitudinalForce',force, ...
        'axleLateralForce',lateral,'axleNormalLoad',tire.staticNormalLoad,'tireSideslipAngle',slip, ...
        'aerodynamicResistanceForce',components.aerodynamicForce, ...
        'rollingResistanceForce',components.rollingResistanceForce,'totalRoadLoadForce',road);
end
