function parameters = fialaIntervalParameters(cfg)
%fialaIntervalParameters Authoritative binary constants shared by verifiers.
    tire=modifiedFialaTire.parameters(cfg);road=cfg.roadLoad;
    parameters=[cfg.vehicle.m;cfg.vehicle.Iz;cfg.vehicle.lf;cfg.vehicle.lr; ...
        tire.corneringStiffness;tire.longitudinalForceScale;road.airDensity; ...
        road.dragCoefficient;road.frontalArea;road.rollingCoefficient; ...
        road.rollingSpeedCoefficient;road.rollingQuarticCoefficient; ...
        road.rollingTransitionSpeed;cfg.vehicle.gravity;cfg.model.scheduleSpeedFloor];
end
