function [minimumAcceleration, maximumAcceleration] = ...
        longitudinalAccelerationBounds(cfg)
% longitudinalAccelerationBounds Bounds for the MPC input a [m/s^2].
%
% The Ge et al. controller commands longitudinal tire acceleration
% directly.  Its actuator contract therefore requires explicit acceleration
% limits; force- and torque-input compatibility paths are intentionally not
% part of this formulation.

    if ~isstruct(cfg) || ~isscalar(cfg) ...
            || ~isfield(cfg, "actuation") ...
            || ~isstruct(cfg.actuation) || ~isscalar(cfg.actuation)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "cfg must contain a scalar actuation structure.");
    end
    requiredFields = ["longitudinalAccelerationMinimum", ...
        "longitudinalAccelerationMaximum"];
    if ~all(isfield(cfg.actuation, requiredFields))
        error("collisionAvoidanceController:invalidConfiguration", ...
            "cfg.actuation must explicitly provide " ...
            + "longitudinalAccelerationMinimum and " ...
            + "longitudinalAccelerationMaximum for input [deltaF; a].");
    end
    minimumAcceleration = localFiniteScalar( ...
        cfg.actuation.longitudinalAccelerationMinimum, ...
        "actuation.longitudinalAccelerationMinimum");
    maximumAcceleration = localFiniteScalar( ...
        cfg.actuation.longitudinalAccelerationMaximum, ...
        "actuation.longitudinalAccelerationMaximum");

    if minimumAcceleration >= maximumAcceleration ...
            || minimumAcceleration > 0.0 || maximumAcceleration < 0.0
        error("collisionAvoidanceController:invalidConfiguration", ...
            "Longitudinal-acceleration limits must satisfy " ...
            + "aMinimum <= 0 <= aMaximum and aMinimum < aMaximum.");
    end
end

function value = localFiniteScalar(value, fieldName)
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) ...
            || ~isfinite(value)
        error("collisionAvoidanceController:invalidConfiguration", ...
            "%s must be a finite real scalar.", fieldName);
    end
    value = double(value);
end
