function prediction = ltvBicyclePrediction(model, storedSchedule)
%ltvBicyclePrediction One scheduled bicycle model over the complete plan.
% Both steering and acceleration are decisions at every stage. The final
% zero-speed schedule admits a rest equilibrium. A carried schedule is
% shifted verbatim, including across the performance/continuation boundary.
% Error boxes obey r(k+1) = abs(A(k))*r(k) + Ts*w at every node.

    arguments
        model (1,1) struct
        storedSchedule = []
    end
    cfg = model.cfg;
    headSteps = model.horizonSteps;
    stageCount = headSteps+model.tailSteps;
    nodeCount = stageCount+1;
    planCount = model.inputDimension*stageCount;
    sampleTime = model.sampleTime;
    inputGain = cfg.model.longitudinalInputGain;
    scheduleShifted = ~isempty(storedSchedule);
    if scheduleShifted
        schedule = storedSchedule;
    else
        schedule = localInitialSchedule(model, nodeCount);
    end
    if numel(schedule.speedProfile) ~= nodeCount ...
            || numel(schedule.station) ~= nodeCount ...
            || numel(schedule.curvature) ~= nodeCount ...
            || any(~isfinite([schedule.speedProfile, ...
                schedule.station, schedule.curvature])) ...
            || any(schedule.speedProfile < 0.0) ...
            || schedule.speedProfile(end) ~= 0.0
        error("collisionAvoidanceController:invalidCertificate", ...
            "The carried schedule must be finite and end at zero speed.");
    end

    stateMatrix = zeros(6, 6, stageCount);
    inputMatrix = zeros(6, 2, stageCount);
    affine = zeros(6, stageCount);
    stateMap = zeros(6, planCount, nodeCount);
    stateOffset = zeros(6, nodeCount);
    stateOffset(:, 1) = model.initialEgoState;
    errorBound = zeros(6, nodeCount);
    measured = model.measuredEgoStateErrorBound(:);
    errorBound(:, 1) = [sum(measured(1:2)); sum(measured(1:2)); measured(3:6)];
    disturbance = sampleTime*(cfg.model.ltvModelErrorRateBound(:) ...
        + cfg.model.plantModelResidualRateBound(:));
    for stageIdx = 1:stageCount
        if stageIdx > 1 && schedule.curvature(stageIdx) == schedule.curvature(stageIdx-1) ...
                && schedule.speedProfile(stageIdx) == schedule.speedProfile(stageIdx-1)
            stateMatrix(:, :, stageIdx) = stateMatrix(:, :, stageIdx-1);
            inputMatrix(:, :, stageIdx) = inputMatrix(:, :, stageIdx-1);
            affine(:, stageIdx) = affine(:, stageIdx-1);
        else
            [stateMatrix(:, :, stageIdx), inputMatrix(:, :, stageIdx), ...
                affine(:, stageIdx)] = ltvBicycleStageMatrices( ...
                schedule.curvature(stageIdx), schedule.speedProfile(stageIdx), ...
                sampleTime, cfg);
            affine(:, stageIdx) = affine(:, stageIdx) ...
                + inputMatrix(:, 2, stageIdx)*(model.longitudinalAccelerationBias/inputGain);
        end
        inputRange = 2*stageIdx-1:2*stageIdx;
        stateMap(:, :, stageIdx+1) = ...
            stateMatrix(:, :, stageIdx)*stateMap(:, :, stageIdx);
        stateMap(:, inputRange, stageIdx+1) = ...
            stateMap(:, inputRange, stageIdx+1)+inputMatrix(:, :, stageIdx);
        stateOffset(:, stageIdx+1) = ...
            stateMatrix(:, :, stageIdx)*stateOffset(:, stageIdx)+affine(:, stageIdx);
        errorBound(:, stageIdx+1) = ...
            abs(stateMatrix(:, :, stageIdx))*errorBound(:, stageIdx)+disturbance;
    end

    reference = zeros(2, stageCount);
    reference(1, :) = atan(cfg.vehicle.wheelbase*schedule.curvature(1:end-1));
    reference(2, :) = (diff(schedule.speedProfile)/sampleTime ...
        - model.longitudinalAccelerationBias)/inputGain;
    reference(:, end) = [0.0; -model.longitudinalAccelerationBias/inputGain];
    prediction = struct( ...
        "scheduleSpeed", max(schedule.speedProfile(1), cfg.model.scheduleSpeedFloor), ...
        "scheduleShifted", scheduleShifted, ...
        "scheduleSpeedProfile", schedule.speedProfile, ...
        "scheduleStation", schedule.station, ...
        "scheduleCurvature", schedule.curvature, ...
        "referenceInput", reference(:, 1:headSteps), ...
        "referencePlan", reference(:), ...
        "stageMatrixA", stateMatrix, "stageMatrixB", inputMatrix, ...
        "stageAffine", affine, "stageCount", stageCount, ...
        "inputCount", 2*headSteps, "tailSteps", model.tailSteps, ...
        "planCount", planCount, "tailIndex", 2*headSteps+1:planCount, ...
        "headNodeCount", headSteps+1, "nodeCount", nodeCount, ...
        "tailNodeIndex", headSteps+2:nodeCount, ...
        "egoStateMatrix", stateMap, "egoStateOffset", stateOffset, ...
        "egoStateErrorBound", errorBound, "scheduleForStore", schedule);
end

function schedule = localInitialSchedule(model, nodeCount)
    cfg = model.cfg;
    speed = min(max(model.initialEgoState(4), 0.0), cfg.model.speedMaximum);
    speedProfile = repmat(speed, 1, nodeCount);
    braking = brakingSchedule("profile", cfg, model.tailSteps, speed);
    speedProfile(model.horizonSteps+2:end) = ...
        max(0.0, speed+model.sampleTime*cumsum(braking));
    speedProfile(end-1:end) = 0.0;
    station = model.initialEgoState(1) ...
        + 0.5*model.sampleTime*[0.0, ...
            cumsum(speedProfile(1:end-1)+speedProfile(2:end))];
    segment = discretize(station, [-inf; model.lane.segmentStation(2:end); inf]);
    curvature = reshape(model.lane.segmentCurvature(segment), 1, []);
    schedule = struct("speed", speed, "station", station, ...
        "speedProfile", speedProfile, "curvature", curvature);
end
